### ISSUE TITLE
FlexLayout inside of an ScrollView doesn't scroll on iOS

### ISSUE THREAD

**Issue by fiedlrob** [dotnet/maui#10256]
### Description

I use an FlexLayout inside of an ScrollView and the user can add items at runtime. If the user inputs more items the FlexLayout should scroll to display all items. This works on Android but not on iOS.

dotnet --version 
6.0.401

Some more info:

[https://learn.microsoft.com/en-us/answers/questions/1011478/flexlayout-inside-of-scrollview.html](url)

### Steps to Reproduce

1. Clone the demo repo 
2. Run the solution on iOS Simulator
3. Add some items via the input field

### Link to public reproduction project repository

https://github.com/fiedlrob/flexview-demo.git

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio 17.7.0 Preview 1.0. Can repro on iOS platform with sample project. [flexview-demo.git](https://github.com/fiedlrob/flexview-demo.git)

**Comment by samhouts** [comment]
Looks like this was resolved for Android and Windows but not iOS. Related to #6881

**Comment by jfversluis** [comment]
From the linked issue I can see it's resolved there and we can't reproduce anymore with the latest changes. However, testing happened based on the description here since the reproduction is not available anymore. I'm going to assume this is fixed, also seeing that this is an older issue by now without much traction.

If there is still something not right according to you, please open a new issue with all the details. Thanks!
