### ISSUE TITLE
[Bug] "Live Visual Tree" doesn't work for a MAUI app on Windows, but works for a WinUI3 app

### ISSUE THREAD

**Issue by andreinitescu** [dotnet/maui#10339]
For a **MAUI** app running on **Windows** (and uses WinUI3),  LVT doesn't work 😟:

![image](https://user-images.githubusercontent.com/743918/192466534-48e3a13a-3dcc-46ee-ac5e-9cd09b890337.png)

For a **WinUI3** app, LVT does work 😃:

![image](https://user-images.githubusercontent.com/743918/192466560-0d2eab36-3732-4599-b792-25ba84d656d5.png)

Why's that 🤔 since the MAUI app uses WinUI3?

**Comment by PureWeen** [comment]
@drasticactions

**Comment by drasticactions** [comment]
If you disable Just My XAML, do you see an LVT for the MAUI application? Basically, when you start a MAUI App using WinUI 3, there should be two "Platforms" shown in the LVT, MAUI and WinUI 3. The WinUI 3 one shows up if you disable Just My XAML. If it's completely blank, XAML Hot Reload isn't working at all. If you only see the WinUI 3 platform, then something is causing the MAUI portion to not work.

Does this happen with every project you have, or just one?

**Comment by andreinitescu** [comment]
The first picture I posted shows the "Just My XAML" button is **disabled**. I cannot even click on it to enable/disable the "Just My XAML" feature.
If I change the target to Android, the LVT works. So it looks like it's an issue with MAUI on Windows specific. 
It happens on every MAUI app I create.
Visual Studio is 17.3.5.

Here's how the Output when running on Windows:
![image](https://user-images.githubusercontent.com/743918/192703267-023366eb-502e-4bdd-b1e4-ac1192990576.png)
![image](https://user-images.githubusercontent.com/743918/192703514-801c7c0c-7794-4a24-b651-30f4b1f9ad47.png)

Is the MAUI Hot Reload supposed to work on Windows?

**Comment by drasticactions** [comment]
Yes it is, it depends on WinUI's XAML Hot Reload to work, however. If you don't see any LVT at all, then WinUI's Hot Reload itself is not working, so MAUI Hot Reload can't work. Now, something with MAUI could maybe cause the WinUI Hot Reload to not work though, breaking everything.

The "Xamarin hot reload" output window says that everything did connect, which is weird since WinUI's Hot Reload doesn't seem to? I'm not sure what that means in this context.

Yes, I would file this to VSFeedback and we can track it there. This isn't something that, at the moment, could be fixed within this repo.

Also, the "hot reload output" is for C# Hot Reload. It means nothing for XAML Hot Reload.  And yes, that is annoying, and yes, we should fix that, lol.

**Comment by andreinitescu** [comment]
> Yes it is, it depends on WinUI's XAML Hot Reload to work, however. If you don't see any LVT at all, then WinUI's Hot Reload itself is not working, so MAUI Hot Reload can't work. 

WinUI's Hot Reload works on my machine. See 2nd picture in the 1st post:

![image](https://user-images.githubusercontent.com/743918/192745890-c68d1e98-f0f4-47b9-a797-0f8be30e3b80.png)


> Now, **something with MAUI** could maybe cause the WinUI Hot Reload to not work though, breaking everything.

Yes.

**Comment by andreinitescu** [comment]
Just to be sure, is LVT for a MAUI app targeting Windows **supposed** to work **today**?
In other words, is it a **bug** on my PC or is it **expected** not to work currently?

Unfortunately https://learn.microsoft.com/en-us/visualstudio/xaml-tools/inspect-xaml-properties-while-debugging?view=vs-2022
 does not say at all. It's very confusing to know which framework is expected it work.

The table there is very outdated:
![image](https://user-images.githubusercontent.com/743918/192749290-8cbe21d5-7d1e-4cf1-bfb8-866a791bbbae.png)
