### ISSUE TITLE
[Android] Modal Pages do not fill screen when in Fullscreen

### ISSUE THREAD

**Issue by ewerspej** [dotnet/maui#10364]
### Description

On Android 12.0, modal pages do not cover the entire screen when going into fullscreen and hiding system and navigation bars. It appears that modal pages are not pushed up all the way, because the content is not centered correctly, either. This occurs with real devices (in my case Samsung S10 + S22), but not in emulators.

### Steps to Reproduce

1. Create a new MAUI App project
2. Add a modal page
3. Enable full screen mode in Android
4. Debug App on Android
5. Open Modal page

Expected behavior: The modal page fills the entire screen when fullscreen is enabled
Actual behavior: The modal page is not pushed up all the way and the underlying page is still visible

### Link to public reproduction project repository

https://github.com/ewerspej/dotnet-maui-bug-repro-modal-fullscreen

### Version with bug

7.0.100-rc.1.22431.12

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12.0

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
@ewerspej can you give me some more specifics it seems to work fine for me?

![image](https://user-images.githubusercontent.com/5375137/192868258-8d4d13d9-7c63-4704-8c7a-32608cf86408.png)

**Comment by ewerspej** [comment]
> @ewerspej can you give me some more specifics it seems to work fine for me?
> 

I'm running it on a Samsung S22 with Android 12.0. My dev environment is Windows 10 running Visual Studio 17.4 Preview 2.1 and the latest .NET 7.0 RC1.

What other kind of information are you thinking of?
How did you try to reproduce it?

I can reliably reproduce it with the example repo as well as with one of the apps I'm working on (which is why I reported this).

**Comment by ewerspej** [comment]
@PureWeen It seems to work fine with Android emulators, but on my Android 12.0 devices (Samsung Galaxy S10 + S22) it's definitely displayed incorrectly as you can see in the screenshots that are attached in the repository.

**Comment by ewerspej** [comment]
I hope it makes it to the next release then, because fullscreen support is important for many apps that want to provide an immersive experience. Thanks for taking it up.

**Comment by ewerspej** [comment]
@rachelkang @PureWeen
## Update
It appears that this is a general MAUI or Shell issue with Android on Samsung devices. This issue is also reproducible with non-modal pages that are created via Shell navigation. The status bar area, which on many Samsung devices features a cutout for the front camera, turns black when opening any type of Page (modals are just slightly worse because their content isn't placed right) and when going back to the previous page, it stays black despite having it set to a different color.

**Comment by jwestes** [comment]
I am seeing the same behavior on a Google Pixel 6, but only in landscape orientation.  Portrait works as expected.  I'm running Visual Studio 2022 - 17.5.4 Pixel is running Android 13 - March 5, 2023

**Comment by PureWeen** [comment]
@jwestes can you include a screen shot?

**Comment by jwestes** [comment]
![Screenshot_20230413-153457](https://user-images.githubusercontent.com/8738822/231898432-d322002f-03a6-42dd-aff2-a21c11d20cb9.png)
![Screenshot_20230413-153506](https://user-images.githubusercontent.com/8738822/231898459-8829fc84-c8a3-440d-865c-25f30e5fc446.png)

**Comment by duandre** [comment]
I am seeing the same behavior on a Motorola edge 20 pro in landscape orientation

**Comment by jrc14** [comment]
This issue is also impacting me, on a Google Pixel 6 device.  It looks fine in landscape mode, but in portrait mode there is a gap, as described above.
Phone is running Android 13 (system update 1 Feb 2023, security update 5 Mar 2023).  Build environment is VS 17.5.3

This issue is blocking me from releasing the app!

**Comment by PureWeen** [comment]
@duandre @jrc14 are you using full screen settings like the issue here dictates or are you doing something else?

**Comment by jrc14** [comment]
@PureWeen yes, this is the same issue with full screen settings.  In my case, I have Shell app that, from one of the shell tabs is using Shell.Current.GoToAsync to display a ContentPage with PresentationMode.Modal, and in that page's code-behind it is switching into full-screen mode by calling insetsController.Hide(WindowInsets.Type....Bars()).  The result is that everything in the ContentPage is being pushed down the screen (so, like with duandre's case, the content of the earlier page on the stack is showing through).
I note that I can change this behaviour by modifying mainActivity.Window.Attributes.LayoutInDisplayCutoutMode.  If I set it to Always then, in Portrait mode, the gap doesn't appear and my modal page ends up in the right place (overlapping the cutout, so the camera lens takes a chunk out of the top-centre of my page content).  This is not a complete fix for the problem because my modal ContentPage is now displaced when the phone is in Landscape mode.  I didn't find one single setting for LayoutInDisplayCutoutMode that gives me a reliably correct appearance in both Portrait and Landscape, full-screen and non-full-screen.  Nor is the behaviour completely repeatable (sometimes the layout I get is different, depending on the series of switches I do between full/non-full-screen and landscape/portrait).

**Comment by duandre** [comment]
@jrc14 @PureWeen just an update: in my case I realize my problem was occurring when controls of MediaElement was shown. I set ShouldShowPlaybackControls="False" and the problem with modal stopped.

**Comment by davibittencourtome** [comment]
Any news about the modal page not showing in fullscreen ? 
Any workaround?

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on Android platform with sample project.
https://github.com/ewerspej/dotnet-maui-bug-repro-modal-fullscreen
![image](https://github.com/dotnet/maui/assets/82450723/ef721b20-67ab-4be7-a1bc-a10e305ecbf2)

**Comment by ewerspej** [comment]
The issue has indeed been improved, but the status bar is still visible when using fullscreen and immersive mode on Android (Samsumg Galaxy S22):

<img src="https://github.com/ewerspej/dotnet-maui-bug-repro-modal-fullscreen/raw/main/modal_17.7.0.jpg" width=400/>

The status bar should be hidden by modal pages, at least that's how it used to be in Xamarin.Forms when fullscreen and immersive mode were enabled.

I wouldn't consider this fixed, yet.

**Comment by mhrastegari** [comment]
Same issue on Pixel 3 emulator

**Comment by jrc14** [comment]
Any update on this issue.  It still persists, and in the latest visual studio version, even my work-around (with mainActivity.Window.Attributes.LayoutInDisplayCutoutMode) no longer works.

**Comment by tschramme86** [comment]
Same here. Issue is still reproducible even on MAUI 8.0.3. Hope it will get fixed soon.

**Comment by PavloLukianets** [comment]
@PureWeen here is another repro, would be cool to have at least a direction where to search for the fix. It looks like the content is being shifted down for some reason (see the nav buttons below) 

[Archive.zip](https://github.com/dotnet/maui/files/13877775/Archive.zip)

![Screenshot_1704825852](https://github.com/dotnet/maui/assets/109070173/644cb067-b219-4b4f-8be6-2e9e3ece92ae)

**Comment by jwestes** [comment]
Is there any progress on this?  I'm getting close to being ready for release and it looks terrible.  It has been well over a year since this was reported and there has been nothing but discussion.

**Comment by PATRICKdallat** [comment]
@PavloLukianets 
When is this fix projected for release?
