### ISSUE TITLE
MAUI Blazor App allow enabling WebGPU on Android/iOS/Mac

### ISSUE THREAD

**Issue by wave9d** [dotnet/maui#10395]
### Description

At the moment the EnvironmentOptions on the BlazorWebView initializing is available just for windows, is it possible to offer support for using WebGPU on android/ios/mac ? 

### Public API Changes

The code below is the one working for windows, it would be great if it would work on the other platforms as well.
```
e.EnvironmentOptions = new Microsoft.Web.WebView2.Core.CoreWebView2EnvironmentOptions()
                {
                    AdditionalBrowserArguments = "--enable-features=enable-unsafe-webgpu"
                };
```

### Intended Use-Case

Rendering webgpu aided content inside a blazorwebview inside the MAUI application.

**Comment by Eilon** [comment]
@wave9d - do you know how to enable this feature on other system's webviews? In BlazorWebView we enable customizing any platform's webview, but you have to use that platform's specific APIs to enable features you want (assuming there's a way to do it at all).

Do you know which API you need to call on those platforms to enable WebGPU?

**Comment by wave9d** [comment]
> @wave9d - do you know how to enable this feature on other system's webviews? In BlazorWebView we enable customizing any platform's webview, but you have to use that platform's specific APIs to enable features you want (assuming there's a way to do it at all).
> 
> Do you know which API you need to call on those platforms to enable WebGPU?

I don't know

**Comment by Eilon** [comment]
I spent a few minutes playing around with this but I couldn't get it to work on Windows. It could be I did something incorrect, or it could be that it isn't supported.

Here's what I tried, in case it helps:

1. I installed Microsoft Edge Canary (latest bits): https://www.microsoftedgeinsider.com/download
2. In `MauiProgram.cs` I enabled using the Canary version for the webview: `Environment.SetEnvironmentVariable("WEBVIEW2_RELEASE_CHANNEL_PREFERENCE", "1");`
3. I added a `BlazorWebViewInitializing="BlazorWebView_BlazorWebViewInitializing"` event handler to the BlazorWebView
4. With this implementation (note that I tried all kinds of options and names, with the `--` prefix and without, etc.):
    ```c#
    private void BlazorWebView_BlazorWebViewInitializing(object sender, Microsoft.AspNetCore.Components.WebView.BlazorWebViewInitializingEventArgs e)
    {
    #if WINDOWS
        e.EnvironmentOptions = new Microsoft.Web.WebView2.Core.CoreWebView2EnvironmentOptions
        {
            AdditionalBrowserArguments = "enable-unsafe-webgpu --enable-unsafe-webgpu --enable-unsafe-webgpu-service",
        };
    #endif
    }
    ```
5. And in `index.html` I checked if the WebGPU is enabled via JavaScript code such as checking if `navigator.gpu` is null

And no matter what I tried, `navigator.gpu` was always null.

For now I'm putting this aside because ultimately I don't think there's anything for BlazorWebView to do, and it's up to people to enable whatever they want via platform-specific features, some of which might not be available on all platforms.

If there does end up being something that we need to enable in BlazorWebView itself, please do let us know.

**Comment by mkArtakMSFT** [comment]
Potentially related: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1285

**Comment by orosbogdan** [comment]
> I spent a few minutes playing around with this but I couldn't get it to work on Windows. It could be I did something incorrect, or it could be that it isn't supported.
> 
> Here's what I tried, in case it helps:
> 
> 1. I installed Microsoft Edge Canary (latest bits): https://www.microsoftedgeinsider.com/download
> 2. In `MauiProgram.cs` I enabled using the Canary version for the webview: `Environment.SetEnvironmentVariable("WEBVIEW2_RELEASE_CHANNEL_PREFERENCE", "1");`
> 3. I added a `BlazorWebViewInitializing="BlazorWebView_BlazorWebViewInitializing"` event handler to the BlazorWebView
> 4. With this implementation (note that I tried all kinds of options and names, with the `--` prefix and without, etc.):
>    ```cs
>    private void BlazorWebView_BlazorWebViewInitializing(object sender, Microsoft.AspNetCore.Components.WebView.BlazorWebViewInitializingEventArgs e)
>    {
>    #if WINDOWS
>        e.EnvironmentOptions = new Microsoft.Web.WebView2.Core.CoreWebView2EnvironmentOptions
>        {
>            AdditionalBrowserArguments = "enable-unsafe-webgpu --enable-unsafe-webgpu --enable-unsafe-webgpu-service",
>        };
>    #endif
>    }
>    ```
> 5. And in `index.html` I checked if the WebGPU is enabled via JavaScript code such as checking if `navigator.gpu` is null
> 
> And no matter what I tried, `navigator.gpu` was always null.
> 
> For now I'm putting this aside because ultimately I don't think there's anything for BlazorWebView to do, and it's up to people to enable whatever they want via platform-specific features, some of which might not be available on all platforms.
> 
> If there does end up being something that we need to enable in BlazorWebView itself, please do let us know.

Even with latest microsoft edge canary (as of today) I'm getting navigator.gpu as null

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
