### ISSUE TITLE
Live Visual Tree is missing "Defined in..." arrow for objects

### ISSUE THREAD

**Issue by eyalkapah** [dotnet/maui#10434]
### Description

Objects in the Live Visual Tree (LVT) don't have next to them the <> symbol which directly navigate to the location in XAML.

### Steps to Reproduce

1. Debug the application 
2. Using the in-app toolbar, select an object
3. Observe the LVT and note there is no <> next to the tree item.

It happens in .NET 7.0.100-rc.1.22431.12 preview.
Not happening in UWP development.

![image](https://user-images.githubusercontent.com/32191482/193356934-7f763a7a-c849-44f3-875f-8cc2fe0a82e4.png)

### Link to public reproduction project repository

dfdf

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

### Did you find any workaround?

No

**Comment by rachelkang** [comment]
@drasticactions thoughts on this one?

**Comment by PureWeen** [comment]
@drasticactions thoughts?

**Comment by drasticactions** [comment]
@eyalkapah Those appear if you disable "Just My XAML". That's intended to only show XAML you have written and is in your app, and hide elements that are nested or not defined by you. They are in the live visual tree but have no source info and so are hidden by default.

In the case of WinUI, there are two "platform" heads. One MAUI and one WinUI. WinUI is "hidden" unless you disable Just My Xaml since the majority of the app is not in WinUI XAML (so it has no XAML nor Source Info). For the MAUI head, it should show source info links for the XAML you defined. If what you wrote is in C#, it won't show source links. If you did write it in XAML, then most likely MAUI is not providing the source info back to generate the links.
