### ISSUE TITLE
FilePicker Android mime-type for gpx files not working

### ISSUE THREAD

**Issue by Tardigrade42** [dotnet/maui#10449]
### Description

I tried to define a `FilePickerFileType` for Android for gpx files. According to my research, `application/gpx+xml` should work, but the gpx-file is not selectable with this mime-type. At the end I tried all tree possibilities: `{DevicePlatform.Android, new[] { "application/gpx+xml", "application/gpx", "text/xml" }` but it is still not working.

I used `Visual Studio Community 2022 - 17.3.5` and tried it on multiple Android devices.

### Steps to Reproduce

1. Clone the repository
2. Copy the test gpx file ([see here](https://github.com/Tardigrade42/MauiIssue-FilePicker-Android-GPX-MimeType/blob/main/Example%20gpx/example.gpx)) to your testing device or vm
3. Deploy the app on the device
4. Make sure, that it has the required permissions (perhaps manually grand it in the app-settings)
5. Start the app and hit the "Select a file" button
6. Navigate to the gpx file
7. The 🐛: The file is grayed out / is not selectable

### Link to public reproduction project repository

https://github.com/Tardigrade42/MauiIssue-FilePicker-Android-GPX-MimeType

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10 / Android 12

**Comment by jfversluis** [comment]
I've checked with your repro, it seems the functionality in .NET MAUI is working. However, the GPX file doesn't have the right mime-type, see the screenshot. So the filtering and the .NET MAUI functionality works as expected, but the file is not selectable since it doesn't have the right mime-type.

Adding the `application/octet-stream` to the filter works, unfortunately that is not specific to the gpx files.

![image](https://user-images.githubusercontent.com/939291/193611740-84d23127-dbc3-45ab-8da2-5bcd9b513f10.png)

**Comment by Tardigrade42** [comment]
Thank you for the fast solution. Is there any way to work with file-extensions as a filter on Android, or do I have to live with this issue?
