### ISSUE TITLE
[Android]First added entry get focus when unfocusing the second added entry dynamically  in navigation page

### ISSUE THREAD

**Issue by jeya-kasipandi** [dotnet/maui#10486]
### Description

When adding multiple entries in a page, unfocused the second added entry in button click. First added entry get focus in Android platform. 

### Steps to Reproduce

1.Run the attached sample in Android platform.
[EntryFocusSample.zip](https://github.com/dotnet/maui/files/9707164/EntryFocusSample.zip)

2.Click the button to navigate to entry page.
3.Focus the second entry by clicking on second entry.
4.Click the button to unfocus the second entry.
5.First entry get focus when unfocusing the second entry.
Expected Output:
First entry not get focus when unfocusing second entry.
Actual Output:
First entry get focus when unfocusing the second entry.

### Link to public reproduction project repository

https://github.com/dotnet/maui/files/9707164/EntryFocusSample.zip

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by PureWeen** [comment]
@jeya-kasipandi Something has to gain focus when you unfocus the second entry. You can't have an absence of focus on Android. In Xamarin.Forms the `Page` itself was made a focusable element which is where the focus would go. But this behavior wreaks havoc on accessibility. If you have a valid use case that maintains accessibility, please let me know. Otherwise, if you want to achieve this behavior you have to give something else focus. For example, you'd have to make a layout focusable and then give that layout focus, which (AFAIK) will make your app experience hostile to keyboard users. 

For example, 
https://stackoverflow.com/a/6118033
