### ISSUE TITLE
WebAuthenticator Broken on iOS15

### ISSUE THREAD

**Issue by nwestfall** [dotnet/maui#10534]
### Description

On iOS 15, `WebAuthenticator` will not launch the browser when calling `AuthenticateAsync`.  From what I can tell, this is because of the deprecation of `UIApplication.Windows` in iOS15.

When using iOS13+, this code gets called in the `WebAuthenticator` implementation
https://github.com/dotnet/maui/blob/4ebbdd8ba0d9263291e8b556c3480da9ddc0aa77/src/Essentials/src/WebAuthenticator/WebAuthenticator.ios.tvos.cs#L77

`WindowStateManager` then calls the following, which doesn't return anything.
https://github.com/dotnet/maui/blob/4ebbdd8ba0d9263291e8b556c3480da9ddc0aa77/src/Essentials/src/Platform/WindowStateManager.ios.cs#L88-L88

### Steps to Reproduce

1. Create a new .NET Maui App (or probably use the sample for Essentials)
2. Add `WebAuthenticator`
3. Run on an iOS 15 Simulator

Expected: Web Browser is launched with login
Actual: Nothing happens

### Link to public reproduction project repository

https://github.com/dotnet/maui/tree/main/src/Essentials/samples

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS15

### Did you find any workaround?

To confirm this issue, I remove `WebAuthenticator.AuthenticateAsync` from my app for iOS and rewrote my own class for the implementation.  I replace the line for `WindowStateManager` with following (it's crude, but proves the bug).
```c#
var window = (MauiUIApplicationDelegate.Current.Application.Windows[0].Handler.PlatformView as UIWindow);
var ctx = new ContextProvider(window);
```

Once this code is used instead of `WebAuthenticator`, it behaves like expected.

**Comment by mattleibow** [comment]
Looking at the code and testing things, the real issue seems to be in the fact that you may be using scenes.

In traditional iOS development with no scenes and a single key window, the value of `UIApplication.SharedApplication.KeyWindow` is that window.

With scenes, there is no key window, but a set of scenes and each has a window.

**Comment by nwestfall** [comment]
I will just add that this app was very early in the development stages.  It is a new .NET Maui Blazor app, running on iOS/Android.  It has just the MainPage (containing the Blazor page) and then a LoginPage which prompts WebAuthenticator.  If it is using scenes, it's not from anything outside of what's above.

Thank you for all your help on the PR!  😄

**Comment by Ghevi** [comment]
I'm using iOS 15 and the webauthenticator works. I'm not using scenes. 

Now, and i'm sorry if this is off topic, in my case i'm setting the web authenticator to an `OidcClient` and then call `client.LoginAsync()` which opens a browser page with our identity provider. The user set his password and then he is redirected back to the app. 
At this point sometimes both on iOS and Android I get a Discovery Exception with a null reference, sometimes it fails to connect, even subsequential calls fail. BUT if i turn off and on the network data then it goes trough...

I'm not opening an issue because maybe it depends on the configuration on our part and I'm not sure how I would produce a repo. So I'm just throwing it out here if someone encountered a similar behaviour.
