### ISSUE TITLE
[Enhancement] MAUI Must Emulate The UNO/Flutter Architecture and Ditch Native UI Entirely

### ISSUE THREAD

**Issue by brencode** [dotnet/maui#1057]
Let me begin with: I've been developing with Xamarin.Forms for nearly seven years. I want MAUI to be a tool that is better than competing UI frameworks on the market like Flutter for building mobile, desktop, and web apps.

Here's an overview of my development experience over the years with Xamarin that informs this imperative request: Every client I've worked for has wanted as close to an identical UI as possible on all target platforms. Clients do not want or need native controls/widgets/views to be rendered typically. It is a rare edge case. Rather, clients need platform independent non-native controls rendered by a vector graphics library. All clients I've worked for have adopted Xamarin because existing .NET developers could use C#/.NET to build mobile apps, while being able to consume existing libraries without reinventing the wheel. Clients and developers I've spoken to want Microsoft to ditch the native UI approach, and to emulate the Flutter and UNO approach of rendering controls independently of the constraints of the platform. 

The majority of development time is spent trying to tweak the UI to make it look identical on both platforms for current Xamarin developers. With the release of Flutter 2.2, it is becoming increasingly difficult to rationalize further investment in MAUI until this becomes THE primary architecture for the platform. Mimicking the Flutter/UNO approach highly simplifies the development process on your end, and working prototypes are already alive and well that should be used to accelerate development. This is where developers want MS and the MAUI/Xamarin team to invest in. The holy grail for developers is for MS to emulate Flutter's architecture while giving we developers the massive advantage of being able to continue to use .NET and C# so we don't have to reinvent the wheel by rewriting libraries in an immature language like Dart.

Finally, Microsoft is investing in working with Google to allow Flutter to target Windows. MS should instead be investing in competing directly with Google by building MAUI the way its veteran developers need. By doing so, you will see the open-source community flood this project with support because .NET developers WANT to keep using C# and avoid having to invest in Flutter/Dart. Personally, I will spend hundreds of hours helping to make this a reality if the Xamarin/MAUI team changes its approach. People are currently holding out on investing because they are cautious with how they expend their valuable time. The market is strongly indicating that Flutter is the cross-platform UI framework to beat. If MAUI goes with native UI first at launch, it will be considered by every peer I know who have developed with Xamarin to be obsolete the day it is released. Half of the developers I know who have used Xamarin have ditched the framework for Flutter because of this. If this happens, after seven years of using Xamarin/.NET to develop mobile apps, I will be forced to move on and invest in Flutter instead, because it will end up being the best tool for the job.

**Comment by AmrAlSayed0** [comment]
While the approach of using a graphics library might seem very appealing, I don't think Microsoft should ditch using native controls. Native controls do a huge part of the heavy lifting. Using a graphics library to render UI views requires a **_HUGE_** (and I can't stress this enough) effort and for that effort you won't get what you expect. Sure, UI itself might be implemented moderately easily without bugs given sometime invested in it, but can you say the same thing about interactivity (touches, drags, keyboard-view interactions, system-view interactions)? What about accessibility? That's probably out the window unless it is recreated in .NET somehow. What about theming and dark mode? What about new features rolling out in newer OSes? What about performance?

Those native views have been developed over **_literal decades_** and used by millions and millions of people and pretty much every bug possible that appeared in those views has been addressed. Starting over by creating your own views will cause you to eventually hit much of the same bugs Google and Apple hit, even if you have the most tested code base in the world. And bar the bugs, performance is a huge issue too. Again, native views are battle tested and every performance optimization you can think of was used to get the views to have the performance you see today. Throwing all of that away doesn't make sense. "But hey,  Google did it, why not Microsoft?" Well, Google has the advantage of already being the mobile space through Android and I willing to bet that much of the same engineers who worked on Android also worked/working on Flutter and they brought their experience (and maybe the code) with them. I am not saying Microsoft doesn't have they expertise. Microsoft have developed UI frameworks before but I don't think it will be the same. 

With native views it is a matter of creating an interface to expose those features and _maybe_ emulate or shim a feature that isn't there. The cost of adding a new feature is **_much much MUCH_** lower. The Xamarin.Forms team in the last year or so have changed their strategy from only exposing supported features by all platforms to shimming a feature if it is not there and I think that will continue. As for looking identical, this is a matter of providing a base styling for all views that would make the default view without any styles look identical so that the developer can then apply their styles. I think this was already partially done in Xamarin.Forms with Material Design Components. If the problem you have with MAUI is controls not looking identical, throwing away the whole OS provided controls and drawing your own seems a bit much. There are easier ways to solve that problem.

**Comment by Happypig375** [comment]
@AmrAlSayed0 Sure the native controls may be battle-tested and bugfree, but Xamarin Forms itself is so buggy that this argument goes down the drain.

**Comment by saint4eva** [comment]
@brencode If I may ask, how many clients do you have? And I believe the Surface team is working with flutter to providing dual screen support for Android and Surface duo. For Windows support, some community guys are doing that. But if they come to Windows team for technical support, Windows team could do that. Maui is going to support for Native control as well as graphics rendering using Microsoft.Maui.Graphics and Microsoft.Maui.Graphics.Controls
