### ISSUE TITLE
VisualTreeElementExtensions.GetVisualTreeElements does not take into account device orientation

### ISSUE THREAD

**Issue by etvorun** [dotnet/maui#10593]
### Description

Selecting elements in XAML Live Preview when Android Emulator is rotated is broken

### Steps to Reproduce

1. Create MAUI app
2. Set debug target to Android Emulator.
3. F5
4. Rotate emulator 90 degrees.
5. In VS open Debug > Windows > XAML Live Preview and try selecting elements

**Actual**: element selection works as if emulator has not been rotated
**Expected**: element selection should work correctly
**Note**: It might related to the fact that DeviceInfo does not change Orientation and/or Rotation

![image](https://user-images.githubusercontent.com/48451158/194920018-37b89fc2-da14-4cfa-91e5-2aa7f052032c.png)

### Link to public reproduction project repository

n/a

### Version with bug

7.0

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

all

**Comment by drasticactions** [comment]
AFAIK looking at what's being returned, I don't think GetVisualTreeElements is wrong. When you rotate the emulator HWND, you're not rotating the actual app. So the math returned from Android is the same as if you took your physical device and rotated it. The default MAUI template, AFAIK, doesn't support landscape modes, so it doesn't do anything. 

If you look at the raw images coming off of the device, they would still appear in portrait because that's what Android itself thinks it's in. I would try to enable landscape mode within the app and see what values it returns.

**Comment by drasticactions** [comment]
I tried this on a physical device and updated the MAUI template app to support landscape mode. When I rotated the device, the images coming from the app updated and rotated to match what was on screen, and the values returned from GetVisualTreeElements returned the correct values for landscape mode.
