### ISSUE TITLE
.gitignore / "obj" folder corrupt program

### ISSUE THREAD

**Issue by Mielesgames** [dotnet/maui#10685]
### Description

The default .gitignore which can be generated, Will automatically ignore the "obj" folder which can't be correctly recovered by Visual Studio for some reason because after re-downloading your application from GitHub, the options "Color", "BackgroundColor" and "TextColor" will completely Vanish from your project.

(This is a follow up from a previous issue, but this time I have more information about the bug)

### Steps to Reproduce

1. Generate a new .gitignore with the "dotnet new gitignore"
2. Commit and Push it to github
3. Download the project from your github repository
4. Open in Visual Studio
5. Try using any color option (for example "TextColor")

Alternative way: 
1. Delete the "obj" folder trough the File Explorer
2. Open the project
3. Try using any color option (for example "TextColor")

### Link to public reproduction project repository

Not required for this bug.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All

### Did you find any workaround?

Removing the obj folder from your .gitignore

### Relevant log output

```shell
No Log output
```

**Comment by Mielesgames** [comment]
I know its kind of a clone of a previous issue report, but this one has more information about it.

**Comment by jfversluis** [comment]
As discussed offline: the bin & obj folder are not included by design. These folders contain files, mostly binary, that are generated from your source. You should not want nor have to include these folders and their contents in your git repo. That is why they are in the `.gitignore` file.

If you're seeing issues like these, you can try a couple of things:
* right-click on your solution file and choose Restore NuGet packages, wait until there is no exclamation mark on the Dependencies node anymore under your projects
* Do a clean on your solution, then choose build or maybe the rebuild options
* Do a `dotnet build` from the command-line

Pay close attention to the build output or any other output windows as they might give a hint on what might not be going right here.

If you still can't figure it out, you probably want to report this through Visual Studio. Under the Help menu go to > Provide Feedback > Report a Problem. That will include all the logs etc. and route it to the right team to have a look.

Thanks!
