### ISSUE TITLE
Grouped collectionview problem with performance

### ISSUE THREAD

**Issue by XamerDev** [dotnet/maui#10700]
### Description

I'm facing an issue with scrolling collectionview which is groupped. I prepared an example repo which has the simplest possible view and vm. Wrrapping item grid in frame boost performance at least in this repo. In my source app which I can't upload, wrapping in frame helps but only when in grid you have max 2 labels. Adding more labels significantly increase problem with scrolling. Seems for me like some kind of memory leaks.
The problem has been discussed with Javier, James, Jean among others 

### Steps to Reproduce

1. steps described in repo comments
2. wrap grid in frame for better performance

### Link to public reproduction project repository

https://github.com/XamerDev/CollViewApp

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

tested on android 11 and 10 and some older

### Did you find any workaround?

Wrapping controls in frame but only in case with basic light view

**Comment by Redth** [comment]
I tried the repro on the latest release of net7.0 MAUI and I'm not perceiving a performance issue on the emulator.

Also it's important to evaluate these issues in a release build which is not using the interpreter (as Debug does by default) since this will affect the performance significantly in these types of scenarios.

I think we need more information here to proceed.
