### ISSUE TITLE
MAUI Blazor Microsoft.AspNetCore.Components.WebView.Maui Dependency version error

### ISSUE THREAD

**Issue by neoayi** [dotnet/maui#10775]
### Description

MAUI Blazor Dependency version error

MauiBlazor7RC -> Microsoft.AspNetCore.Components.WebView.Maui 7.0.0-rc.2.6866 -> Microsoft.AspNetCore.Authorization 7.0.0-rc.2.22476.2 -> **Microsoft.Extensions.Logging.Abstractions (>= 7.0.0-rc.2.22472.3)** 
 MauiBlazor7RC -> **Microsoft.Extensions.Logging.Abstractions (>= 7.0.0-rc.2.22430.11)**	MauiBlazor7RC	C:\Users\*User*\source\repos\MauiBlazor7RC\MauiBlazor7RC\MauiBlazor7RC.csproj	1	

### Steps to Reproduce

1. Create App -> Use MAUI Blazor Template -> .net 7.0
2. Compiler;
3. Error.

### Link to public reproduction project repository

no

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Not, Only Compiler.

### Did you find any workaround?

NO

### Relevant log output

```shell
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	NU1605	检测到包降级: Microsoft.Extensions.Logging.Abstractions 从 7.0.0-rc.2.22472.3 降级到 7.0.0-rc.2.22430.11。直接从项目引用包以选择不同版本。 
 MauiBlazor7RC -> Microsoft.AspNetCore.Components.WebView.Maui 7.0.0-rc.2.6866 -> Microsoft.AspNetCore.Authorization 7.0.0-rc.2.22476.2 -> Microsoft.Extensions.Logging.Abstractions (>= 7.0.0-rc.2.22472.3) 
 MauiBlazor7RC -> Microsoft.Extensions.Logging.Abstractions (>= 7.0.0-rc.2.22430.11)	MauiBlazor7RC	C:\Users\Max.Huang\source\repos\MauiBlazor7RC\MauiBlazor7RC\MauiBlazor7RC.csproj	1
```

**Comment by gpproton** [comment]
I'm also having the same error.

Severity	Code	Description	Project	File	Line	Suppression State
Warning		NU1603: XClaim.Mobile depends on Microsoft.Extensions.Logging.Abstractions (>= 7.0.0-rc.2.22430.11) but Microsoft.Extensions.Logging.Abstractions 7.0.0-rc.2.22430.11 was not found. An approximate best match of Microsoft.Extensions.Logging.Abstractions 7.0.0-rc.2.22472.3 was resolved.		 	0

**Comment by Stxtics** [comment]
Same issue here

**Comment by Redth** [comment]
MAUI has implicit package references to some of these at an older version, so if you're trying to update nuget packages because the package manager tells you there's an update, you may see this.

You can force them to update (just as the error indicates) by explicitly setting the version for the conflicting packages.

In this case you could use:

```
<PackageReference Include="Microsoft.Extensions.Logging" Version="7.0.0-rc.2.22472.3" />
<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0-rc.2.22472.3" />
<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.0-rc.2.22472.3" />
```

In addition to trying to update the `Microsoft.Extensions.Logging.Debug` package defined explicitly in the new project.

**Comment by TrueGeek** [comment]
@Redth this gives the warning

`Warning NETSDK1023: A PackageReference for 'Microsoft.Extensions.DependencyInjection' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project`

I think the problem is that Maui is referencing `>= 7.0.0-rc.2.22430.11` but there is no such version. In an ideal world nuget would just silently pick the next highest version (7.0.0-rc.2.224723.3) but instead it complains and logs a warning which is super fun for those of us with `treat warnings as errors` turned on.

It's not a huge deal (and maybe I'm wrong about what's happening here with nuget?) but if Maui could reference a version that exist so that the warnings aren't being thrown it'd be awesome!

**Comment by PirasathLuxchumykanthan** [comment]
Just add NU1603; in "suppress specific warnings" 

then is fix..
