### ISSUE TITLE
[iOS] CollectionView Header gets moved when keyboard or picker show up

### ISSUE THREAD

**Issue by harry-cpp** [dotnet/maui#10947]
### Description

CollectionView Header gets moved when keyboard or picker show up.

Before clicking on entry or picker:
![Screenshot 2022-10-26 at 22 48 13](https://user-images.githubusercontent.com/6773302/198134537-7ecf5cef-e41f-4fdb-ac8d-387595ce28a7.png)

After clicking on entry or picker:
![Screenshot 2022-10-26 at 22 48 22](https://user-images.githubusercontent.com/6773302/198134565-d4fbc749-b2fc-4153-8fed-1ae42714a2e4.png)

### Steps to Reproduce

1. Add entry or picker to a collectionview header, in some layout
2. Run the application and press it

### Link to public reproduction project repository

https://github.com/harry-cpp/MauiBugSamples/tree/main/iOSCollectionViewHeader

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

All

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio 17.7.0 Preview 1.0. Can repro on iOS platform with sample project.
[iOSCollectionViewHeader](https://github.com/harry-cpp/MauiBugSamples/tree/main/iOSCollectionViewHeader).

**Comment by tj-devel709** [comment]
I was also able to repro this issue!

**Comment by tj-devel709** [comment]
Did some digging into this issue but was not able to find the solution yet. 

### The Process
Inside `src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs`, we can follow the process from when the CollectionView header is added in our code:
1. The CollectionView Header is added as a Subview to the UICollectionView putting the header in front of the start of the CollectionView.
2. We add ContentInset to the top of the CollectionView the size of the header since we now how additional content we want included in the header.
3. We then add a negative ContentOffset in the Y axis to the CollectionView so that the CollectionView essentially scrolls upwards to show the new header content. (although it appears to me that we may not need this anymore - at least for newer versions of iOS since it seemed to have the same behavior when this part was removed)

### Where is the issue
In the `ViewWillLayoutSubviews()` method inside `src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs`, we can see that the ContentOffset for the CollectionView is being changed after firing multiple times when certain views are clicked in the CollectionView Header (views that prompt something such as editor, entry, picker, datepicker, and timepicker but not things like checkbox). The amount that the ContentOffset changes seems to be proportional to the location of the view clicked in the header. In the example I attached here, it seems that the `contentOffset -= top of focused view - distance to the end of the header`. In the example, the header is 300 pixels tall and contains a picker and two entries inside of a grid.

You can also see that when unfocusing the view and then focusing a different view while the ContentOffset has the not good value, if we click a view lower than the current view, the ViewWillLayoutSubviews method does not fire and no recalculating is done. If we click a view higher than the current view, it will fire the method and recalculate the ContentOffset. After scrolling up a little bit, the top of the header snaps back into place.

Other important things to note:
* `CollectionView.AutomaticallyAdjustsScrollIndicatorInsets = false;` did not help
* `CollectionView.ContentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentBehavior.Never;` did not help
* It did not appear that adding an empty subview to the CollectionView before or after the header content helped


https://github.com/dotnet/maui/assets/50846373/fc331330-c476-4a74-8cab-0cc78b55bf35

**Comment by borrmann** [comment]
@borealoh 
1. put the CollectionView inside a Grid. 
2. add your header and the collectionview to the grid without any rowdefinitions.
3. Bind the headers height as a Margin to the collectionview 
-> Height is a double and Margin of type thickness so you need a Converter like the one below


``` 
<Grid>
    <Grid VerticalOptions="Start" x:Name="header">
         <Label Text="Header" />
    </Grid>
    <CollectionView ItemsSource="{Binding Blobs}"
                    x:Name="collView"
                    Margin="{Binding Source={x:Reference Name=header}, Path=Height, converters:DoubleToTopMarginConverter}">
        </CollectionView>
  </Grid>

public class DoubleToTopMarginConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        if(value is double margin)
        {
            return new Thickness(0, margin, 0, 0);
        }
        return new Thickness(0, 0, 0, 0);
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        return throw new NotImplementedException();
    }
}
```
