### ISSUE TITLE
RadioButton IsChecked Binding does not work on iOS nor Windows

### ISSUE THREAD

**Issue by NestorPV** [dotnet/maui#11125]
### Description

RadioButton IsChecked Binding does not work on iOS nor Windows

### Steps to Reproduce

Create a new Maui app
Add a RadioButton and add a Binding to IsChecked
Change the IsChecked property programmatically 

Expected, it would update the IsChecked state
Actual, The RadioButton stays checked

Also the default Background color should be transparent 

### Link to public reproduction project repository

https://github.com/NestorPV/AppOne.git

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows

### Affected platform versions

iOS 16, Windows 11

### Did you find any workaround?

*Only for the background*
On the  ..\Resources\Styles\Styles.xaml file change 
```
 <Style TargetType="RadioButton">
        <Setter Property="Background" Value="Transparent"/>
```
to
```
 <Style TargetType="RadioButton">
        <Setter Property="BackgroundColor" Value="Transparent"/>
```

**Comment by mattleibow** [comment]
I had a look at this and I believe it is because you have attached the tap gesture to the radio button. What is happening when you tap is that the radio button is selected and then your tap gesture flips it off.

If you add the gesture to another control it works correctly.

What is the reason to add a tap to the radio button? The default action is to select. If you are wanting to support selection and then deselection, a checkbox may be the thing you are looking for?

**Comment by PradoVargasN** [comment]
I agree a checkbox is more suitable, but it was just convenient to use it as a rounded checkbox with a label without going for a custom controller. 

What is annoying is that it works on some platforms but not on others.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio 17.7.0 Preview 1.0. Can repro on iOS and windows platform with sample project.
[AppOne.git](https://github.com/NestorPV/AppOne.git)

**Comment by dustin-wojciechowski** [comment]
Tested this with NET 8.0 and had it check the box on initialize and it worked. Looks like it was fixed.

![Image](https://github.com/dotnet/maui/assets/89540402/ca736fb7-b3a1-4c86-8169-dcde52ce8fdd)
