### ISSUE TITLE
Issues AMM0000 error in the AndroidManifest

### ISSUE THREAD

**Issue by tradegear** [dotnet/maui#11172]
### Description

I get errors from PlayStore trying to upload my *-signed.aab file.  (after following Jerald Versluis instructions on https://www.youtube.com/watch?v=jfSVb_RR7X0)
I get an error: You uploaded an APK or Android App Bundle that was signed in debug mode. You need to sign your APK or Android App Bundle in release mode
After researching solutions to this problem, it appears that the configurations for debugging aren't always consistently followed, so on a mission, I set out to disable any remnants that sound at all related to debugging.   I edited the project file and set:
1.
Build -> General -> Debug symbols 
from: PDB file, portable across platforms
to: No Symbols are emitted
2.
Developer instrumentation
I unchecked the option for "Debug" (now it is empty/false)
3.
iOS-> Debug -> Debugging
changed from True to False

Now when I do only the build of release mode (not the Publish which signs the *.aab), I get this error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	AMM0000	
	uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library C:\MTRClient\MTRClient\obj\Release\net6.0-android\lp\130\jl\AndroidManifest.xml as the library might be using APIs not available in 19
	Suggestion: use a compatible library with a minSdk of at most 19,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="androidx.security" to force usage (may lead to runtime failures)
	MTRClient	C:\MTRClient\MTRClient\obj\Release\net6.0-android\AndroidManifest.xml	28	

so...
I can't upload because of debug mode, and I can't turn off debug mode.  Quite difficult to publish to the Google Play store...

### Steps to Reproduce

Change debugging settings in Project file as explained above.

### Link to public reproduction project repository

no

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android

### Did you find any workaround?

Not even after spending several hours was I able to find a way to publish my app to the Google Play store.

### Relevant log output

```shell
no
```

**Comment by tradegear** [comment]
I set these 3 values back to their original values (and I was very careful to keep track of what these changes were, so that I could report them here in anticipation of this breaking), now after solution - clean, and rebuild project (which I would expect to pretty much clean up everything?)  I continue to get the AMM000 error.
Reverting back to a backup from a couple hours ago...

**Comment by tradegear** [comment]
@rachelkang - thank you for the predictable and typical response - "needs repro".  Does Microsoft have anyone on staff who can fix issues instead of triage them into oblivion?  This seems to be how Microsoft deflects and punts issues until we developers work around them, forget about them if unessential, or give up on the platform.  I will not be supplying a "needs repro" project that fails, because it only fails in my current build which contains too much intellectual property.  At least five times in the past 8 weeks working on this project, I have restarted my dev project on a "newed-up cute-bot" app, and carefully copy/pasted my code into the new project, and then it compiles again.  That's what I did on this issue again here.  You might as well close this ticket, but you'll see it again when some other poor soul stumbles upon it.

**Comment by Redth** [comment]
@tradegear that comment is not productive, and does not adhere to our [Code of Conduct](https://dotnetfoundation.org/about/policies/code-of-conduct).  Please read the policy and conduct your interactions accordingly in the future.

The error looks like you could have a couple of potential issues:
1. Your android manifest has the `android:debuggable="true"` set in your final build.  I believe we disable this by default in the Android build targets when you use the build configuration `Release`.  I'd suggest building with `dotnet build -f net7.0-android -c Release MyApp.csproj` and inspecting the resulting .apk file's manifest to confirm.
2. You may not be signing correctly.  I'd suggest reviewing the [documentation](https://learn.microsoft.com/en-us/dotnet/maui/android/deployment/publish-cli?view=net-maui-7.0#create-a-keystore-file) to create the appropriate keys.
3. Unfortunately the "Debug symbols" in the project settings is slightly misleading as those refer to .NET _managed_ debug settings, and do not directly influence the _platform_ settings for debug options which is what Google cares about.

Yes we ask for repro samples, because it's one of the best ways for us to quickly analyze an issue and plan for how to fix and prioritize it in the future.  Help us help you by narrowing down reproductions of your issues.  We are doing our best to priortize issues that have the biggest impact across the community with the time and resources we have.  If we can't easily reproduce a problem, and we don't have a good idea that many people are experiencing it as well, we are less likely to be able to confirm it, and prioritize fixing it.

**Comment by tradegear** [comment]
This was marked "fixed", but it didn't get fixed.  I wasn't willing to upload my project as it has IP embedded.  I've moved on to a different platform.

**Comment by chandlerturner** [comment]
I was running into this same issue while using the CLI method and was able to sign in release mode by providing the password in the PropertyGroup as shown [here](https://learn.microsoft.com/en-us/dotnet/maui/android/deployment/publish-cli?view=net-maui-7.0#code-try-3). Not ideal for pipelines, but will get it done if you need it.
