### ISSUE TITLE
[Bug] Using statement for RCL error

### ISSUE THREAD

**Issue by mohaaron** [dotnet/maui#1123]
### Description
I'm starting a Blazor Maui app and trying to include a Razor Component Library. When I add the following code into the Index.razor file the app won't run. There is an error that is not appearing in the error console.

The "using" statement option also does not show up for IntelliSense.

### Steps to Reproduce

1. Add Razor Component Library project to the solution.
2. Reference RCL project in base project to use in razor files.
3. Add @using statement for RCL project namespace.

### Expected Behavior
Should provide access to RCL component in razor file. This works as expected in a Blazor app.

### Actual Behavior
Causes unknown error.

### Basic Information

- Version with issue:
- Last known good version: None
- IDE: VS2019 Preview Version 16.11.0 Preview 1.0
- Platform Target Frameworks: Running on windows 10 from VS2019 Preview

**Comment by mohaaron** [comment]
Something I've found about the unknow error is that it appears to be caused by a using statement that points to a location that does not exist. I'm not sure how referencing other projects is supposed to work, but I have had to reference the RCL project with the root project (containing the razor pages) as well as the WinUI3 project for the RCL namespace to work.

**Comment by Eilon** [comment]
@mohaaron ah, so it worked once you added a reference from MyProject _and_ MyProject.WinUI3? If so, that's a limitation due to some of the workarounds we had to do to get WinUI targets to work alongside the Android/iOS/MacCatalyst projects. The WinUI project doesn't reference the non-WinUI project; rather, it is sort of a "copy" of it that points to all the same source files. That means that things such as project references need to be duplicated.

But, we are working on a real fix so that this workaround won't be needed, but that fix is not yet ready. So for now during the previews you will need to add project/package references to both the WinUI and non-WinUI project (assuming you want them in both, which you usually would).

**Comment by Eilon** [comment]
BTW this would affect more than just RCLs. If you added any reference to any other project/package I think you'd get the same issue.

**Comment by mohaaron** [comment]
Thank you for the feedback. I wanted to let anyone interested know about what I found.
