### ISSUE TITLE
[Bug] An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in System.Private.CoreLib.dll

### ISSUE THREAD

**Issue by samchivers** [dotnet/maui#1127]
### Description
After getting a 'Congratulations, everything looks great' from MAUI check and going file -> new -> .NET MAUI App in VS 16.11.0 Preview 1.0, project will not run due to the error message `An unhandled exception of type System.Reflection.TargetInvocationException occurred in System.Private.CoreLib.dll
Exception has been thrown by the target of an invocation.`

### Steps to Reproduce

1. Install VS Preview 16.11.0 Preview 1.0
2. Install / Run MAUI check, getting green all the way down, and ending with 'Congratulations, everything looks great!'
3. Open VS Preview, go to file -> new -> .NET MAUI App
4. Add https://aka.ms/maui-preview/index.json as a nuget package source
5. Set the target to WinUI3
6. Click Run
7. Observe error window entitled 'Exception Unhandled', contents: `System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.
Inner Exception: COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))`
8. Observe contents of Output window stating `An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in System.Private.CoreLib.dll
Exception has been thrown by the target of an invocation.`

### Expected Behavior
Default template app would run

### Actual Behavior
Exception described above occurs

### Basic Information

- Version with issue: 6.0.100-preview.4.21255.9
- Last known good version: N/A
- IDE: VS 16.11.0 Preview 1.0
- W10Pro 21H1 19043.985
- MAUI nuget versions 6.0.100-preview.4.634

**Comment by Nyaoso** [comment]
I am having the same problem.

This is what is logged in the Windows Event Viewer

Application: MauiSample.WinUI3.exe
CoreCLR Version: 6.0.21.25307
.NET Version: 6.0.0-preview.4.21253.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName) in Microsoft.WinUI.dll:token 0x6000023+0x6e
   at Microsoft.UI.Xaml.Application._IApplicationStatics..ctor() in Microsoft.WinUI.dll:token 0x60135ef+0x1c
   at System.RuntimeType.CreateInstanceOfT() in System.Private.CoreLib.dll:token 0x6000632+0x3e
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceOfT() in System.Private.CoreLib.dll:token 0x6000632+0x4e
   at System.Activator.CreateInstance[T]() in System.Private.CoreLib.dll:token 0x6000950+0x0
   at WinRT.WeakLazy`1.get_Value() in Microsoft.WinUI.dll:token 0x6000019+0x20
   at Microsoft.UI.Xaml.Application._IApplicationStatics.get_Instance() in Microsoft.WinUI.dll:token 0x60135f0+0x0
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback) in Microsoft.WinUI.dll:token 0x600917b+0x0
   at MauiSample.WinUI.Program.Main(String[] args) in MauiSample.WinUI3.dll:token 0x6000011+0x21

**Comment by Nyaoso** [comment]
**I have resolved the problem as follows:**

Right Click on the Packaging project and set as startup-project;

**Comment by samchivers** [comment]
Many thanks @Nyaoso, your fix worked for me 👍

**Comment by Darkatek7** [comment]
> **I have resolved the problem as follows:**
> 
> _Right Click on the Packaging project and set as startup-project;_
> 
> **Steps to Reproduce**
> 
> 1. Install VS Preview 16.11.0 Preview 1.0
> 2. Install / Run MAUI check, getting green all the way down, and ending with 'Congratulations, everything looks great!'
> 3. Open VS Preview, go to file -> new -> .NET MAUI App
> 4. Add https://aka.ms/maui-preview/index.json as a nuget package source
> 5. Set the target to WinUI3 (Package) <== **RIGHT CLICK AND SET AS STARTUP PROJECT**
> 6. Ensure the Target is LOCAL MACHINE
> 7. Click Run

This worked!

**Comment by xela-trawets** [comment]
Yup and to set the extra package source 
in the  "package Manager" pane 
look top right, where it says package source, and click on the gear.
the dialog pops up, and you click the green plus at the top,
then go to the bottom to enter the  url
 then update.
long winded, sorry, but might help.

**Comment by sinsedrix** [comment]
Packaging project is not available any more in the prevew6. Any idea of how to fix this issue?

**Comment by GavinRay97** [comment]
Also ran into this. If it weren't for you helpful people before me finding an answer and sharing it, I probably would have given up after searching tonight.

Not very intuitive behavior IMO, and the error message doesn't give any context clues 🙁 

I'm not very familiar with .NET or Visual Studio, I thought that selecting the project from the dropdown at the top so that `WinUI3` was the target would do what that sort of implies.

Apparently not and it needs to be set as "Startup Project" and run on "local machine" instead of `x64` or whatnot.

Thank-you to those who posted before! All working with your help =)
