### ISSUE TITLE
FileSystem.AppDataDirectory get different path between debug and  deployed

### ISSUE THREAD

**Issue by blackcatpolice** [dotnet/maui#11306]
### Description

My code : 
` Path.Combine(FileSystem.AppDataDirectory, "OptionsDB.db3");`

Result  on  Debug : C:\Users\{MyName}\AppData\Local\Packages\{AppId}\LocalState\OptionsDB.db3

Result on Deployed: C:\Users\{MyName}\AppData\Roaming\User Name\{AppId}\Data\OptionsDB.db3

If you deployed , the path after Roaming is "User Name" , this is wrong words,  and I can not find this path my computer

### Steps to Reproduce

1. Create a new MAUI blazor project 
2. In index.razor page , write code `string path =  Path.Combine(FileSystem.AppDataDirectory, "test.txt")`
3. display the variable `<div>@path</div>`
4. Step one :  Run F5 the page 
5 Step two :  use deployed cmd : 'dotnet publish -f net6.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None'
   and click MauiBugReport.exe 
6. Now you can see the diffrent result

### Link to public reproduction project repository

https://github.com/blackcatpolice/MAUIBUReport.git

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

 OS Name:    Windows  OS Version:  10.0.22623  OS Platform: Windows  RID:   win10-x64   Microsoft.WindowsDesktop.App 6.0.11

### Did you find any workaround?

On windows : I write this code `        Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), DatabaseFilename);
` it can be worked. but this director is common app data location , not private .

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on Windows 11 with below Project:
[MauiBugReport.zip](https://github.com/dotnet/maui/files/11633680/MauiBugReport.zip)(**.NET 7**)

Result on Debug:
![image](https://github.com/dotnet/maui/assets/97647558/b3a0af36-4a1f-4072-a18d-b72fc9c72215)

Result on Deployed
![image](https://github.com/dotnet/maui/assets/97647558/e7a73179-193e-4d75-8a29-5ca2b97d8fc1)

**Comment by Eilon** [comment]
I suspect this is by design.

The text `User Name` is simply because it's part of the app's identity, as seen in this file: https://github.com/blackcatpolice/MAUIBUReport/blob/master/MauiBugReport/Platforms/Windows/Package.appxmanifest#L15

And when running without deploying vs. with deploying there are differences regarding where the app is located, so the choice of data folder is different between them, because they are not the same "installed application identity."

Apps can always choose some particular specific location to store data that won't change, but by default each instance of an app will likely have its own storage location.
