### ISSUE TITLE
[Enhancement] F# Support from Day 1

### ISSUE THREAD

**Issue by staypufd** [dotnet/maui#115]
## Summary
F# support from day 1 is critical. F# consistently gets left off of supported tooling with MS UI frameworks, this leaves it unsupported and it never recovers. Teams have made excuses for not supporting it and never seem to find the time or resources and thus F# support never happens. We’ve asked and pleaded for F# to truly be supported like the first class language it is held up to be. Please this time make it truly one from day 1 so that it isn’t behind from the very start and then dies as a option for so many who would use it if it was truly supported 100%. Please.

## Intended Use Case
Many of us functional developers use F# and want to use it for our GUI apps as well.

**Comment by nbevans** [comment]
Project system and templates is a bare minimum.

**Comment by Happypig375** [comment]
For inclusivity, add Visual Basic to the list as well.

**Comment by mrwcjoughin** [comment]
@Happypig375 vb.net is basically dead. I doubt it will even be supported in .net 7

**Comment by Padanian** [comment]
No doubt vb needs to be here. It's the 5th or 6th most used dev lang in the world, for both front ends and back ends, for CLI and GUI. 
F# is not necessary.

**Comment by mrwcjoughin** [comment]
@Padanian I don't believe that's accurate. While Microsoft is supporting it in .net 5, there is no commitment for anything after that, and they are flat out saying they are not adding new features to it at all:
https://visualstudiomagazine.com/articles/2020/03/12/vb-in-net-5.aspx

Bottom line: move to C# if you want to stay on .net - there really is no reason not to and so many reasons to move to it.

**Comment by Padanian** [comment]
I know what is their position _at this time_ . It's most probably going to change. 
And I'm not going to the curly bracket. Now back to the regular program.

**Comment by nbevans** [comment]
> No doubt vb needs to be here. It's the 5th or 6th most used dev lang in the world, for both front ends and back ends, for CLI and GUI.
> F# is not necessary.

Please don't say that. We have a 600k line codebase written in F# built on top Xamarin.Forms. If they remove F# support - we are toast. We would need to rewrite everything within the 12 months period they have allocated to continue supporting Xamarin.Forms.

All languages that Xamarin Forms supported should continue to be supported by MAUI in at least equitable functionality.

**Comment by ncarandini** [comment]
> And I'm not going to the curly bracket.
Ok, that say it all. Good luck!

**Comment by brase** [comment]
@Padanian 
| And I'm not going to the curly bracket.

No problem. Try F# ;)

**Comment by 7sharp9** [comment]
It's not hard adding a template unless there is a lot go magic tooling occurring within.

**Comment by Krzysztof-Cieslak** [comment]
> No doubt vb needs to be here. [...]. F# is not necessary.

Don't have VB and F# communities bigger problems than shouting at each other?

**Comment by nbevans** [comment]
I support VB - they should experience no loss of functionality either in this Xamarin Forms to MAUI transition.

I don't think this should be a fight or choice between whether VB or F# is to be the lucky 2nd language that gets supported by MAUI. Let's just support all 3 to maximise the platform's reach and minimise arguments, pretty please?

**Comment by Happypig375** [comment]
This issue's like count has surpassed #34. Feels good man

**Comment by GiampaoloGabba** [comment]
I'm not (yet) an F# developer, i'm studying it a bit and is pure awesomeness :)
I'm sure that .net MAUI will bring some love to F#.

Regarding VB.NET i doubt it will get more than what it gets now: basically nothing. 
Some community effort will be ok, but i dont think (and hope) no one in the maui team will loose even a second to bring some love to VB.NET... i mean... come on...

**Comment by Padanian** [comment]
[By TIOBE index](https://www.tiobe.com/tiobe-index/), VB is the 6th largest community of developers at around 4%.
F# is the 46th with 0.2%. By _any standard_, it's a negligible minority.

**Comment by charlesroddie** [comment]
> Teams have made excuses for not supporting it and never seem to find the time or resources and thus F# support never happens.

Xamarin.Forms already has support for netstandard projects written in any .net language and there is no plan to remove it. I am sure there are some teams out there that have failed to support F# but how is that relevant to Xamarin.Forms or MAUI?

MAUI has the possibility of improving the experience for developing UI using code, and so having previews/live updates of code-defined UI would benefit F# usage. So it's important that's not done in a C#-specific way. Assuming that happens, the experience will be even better than it is at the moment.

Templates will probably be updated but that's a negligible issue as in Xamarin.Forms/MAUI very little code lives in the platform-specific project(s).

Overall there is a lot of emotion in this thread and it's hard to understand what is causing it.

**Comment by PureWeen** [comment]
We're really excited to work with @TimLariviere so that Fabulous can be developed into a first class citizen with .NET MAUI

https://github.com/fsprojects/Fabulous/issues/747

The work we're doing on the slim renderers
https://github.com/dotnet/maui/issues/28

Is going to allow Fabulous to really structure itself how ever it wants without having to just use wrappers for Forms elements

@TimLariviere has already put together a very descriptive spec on what he's thinking the direction should be

https://github.com/fsprojects/Fabulous/issues/738

If you're interested in F# as a first class citizen for coding UI's I would head over to Fabulous and tell Tim what you think

**Comment by maxenko** [comment]
Chick and the egg thing as well, lack of basic templates keeps a lot of people from even thinking about trying it.

But those of us who use it do know - once you complete a simple project its hard to go back to C#.

**Comment by davidortinau** [comment]
To those who are using F# today with Xamarin.Forms, would you please shoot me a description and perhaps some screenshots of what you're shipping? That'll help me get a clearer picture. david.ortinau@microsoft.com 

Happy to setup some calls as well. :)

**Comment by TimLariviere** [comment]
I would be really happy to help shape MAUI so we can remove all the internal MVVM -> MVU mapping happening inside Fabulous. This would be hugely beneficial, both in terms of performance and time/work necessary for a new release supporting the latest version of MAUI/XF.

That said, not every F# Xamarin developers use Fabulous.

One major pain today, when it comes to using F# for building Xamarin/XF apps, is the F# tooling lagging behind or all the little things missing that would make life so much easier, like updated official templates and samples.

It's not directly linked to MAUI, but it is a mandatory part before F# developers can even think about MAUI.

Examples of this today are:
- [Mono supporting only F# 4.5 (released in 2018), when 4.7 is available](https://github.com/mono/mono/issues/16763)
- [PackageReference not supported in old-style F# projects](https://github.com/dotnet/fsharp/issues/5849)
- No official F# samples (I tried to migrate Fabulous's F# Android template to AndroidX, but was met with a lot of guessing work and frictions)

So, since MAUI will introduce a new project type and I guess lots of tooling around it like Hot Reload and such, it is important to make sure those work with F# like they will do with C#.

Though I have to note that Xamarin is one of the few places where F# is well considered and most likely get support... at least one day.

**Comment by Happypig375** [comment]
This has become the most liked issue in this repository in 2 days! 🎉🚀

@TimLariviere
>I tried to migrate Fabulous's F# Android template to AndroidX, but was met with a lot of guessing work and frictions

The official C# Xamarin.Forms project template doesn't use AndroidX either. Its `TargetFramework` is still at `v9.0`, which indicates the use of Android Support libraries instead of AndroidX. However, I have successfully upgraded my Fabulous project to AndroidX through manual editing of `.fsproj`s, `packages.config`s and Android `.axml`s (and searching StackOverflow), will try opening a pull request today.

**Comment by nbevans** [comment]
It is exceptionally rare to witness a F# thread, in a non-F# repo, get this much activity and upvotes in such a short space of time. I always knew F# and Xamarin had a special relationship of sorts and this proves it without question.

@davidortinau Thank you (and @TimLariviere) for responding on here - it is good to know we have your attention at this primordial moment for MAUI. In terms of a description/screenshots etc I will see what I can put together and get it over to you.

**Comment by Happypig375** [comment]
@nbevans I think that this issue must have circulated around twitter/reddit/slack/... which other issues did not.

**Comment by JamesRandall** [comment]
@davidortinau  I'd be happy to provide some feedback on my usage of F# with Xamarin Forms - my work has been all through Fabulous. Give me a shout if you'd like a conversation about the apps themselves and more detail.

**Comment by vshapenko** [comment]
As an f# dev currently developing on Fabulous, i would be greatly appreciated if MAUI had f# support from day one.

**Comment by fwaris** [comment]
Recently I used F#/Fabulous for the very first time and already I know this is how I would like to build all future applications (see https://github.com/fwaris/BertQA).

Most abstractions are leaky. However in Fabulous I was able to construct the app by only relying on the mental model afforded by the abstraction. Did not need to know (still don't know) how it all works under the covers.

**Comment by r4mp4l** [comment]
Please include F#

**Comment by charlesroddie** [comment]
> @TimLariviere So, since MAUI will introduce a new project type and I guess lots of tooling around it like Hot Reload and such, it is important to make sure those work with F# like they will do with C#.

I don't think the new project type as such will make a difference because there will be [backwards compatibility](https://github.com/dotnet/maui/issues/70#issuecomment-632978443) with "existing" projects.

Preview or hot reload would be very valuable for F# and C#-defined UI, and it's important that they do this in a way that is [.net](https://github.com/xamarin/Xamarin.Forms/issues/9166#event-3157403646) rather than [c# - specific](https://developercommunity.visualstudio.com/idea/650684/c-hot-reload-xamarin.html). Anything that requires an interpreter might be tricky.

**Comment by TimLariviere** [comment]
@charlesroddie It's one thing to be backward compatible, it's another to have the new project type fully supported.
F# developers shouldn't be stuck with 3 or more projects because the F# tooling inside Visual Studio and other IDEs didn't follow and they only checked for `csproj` to allow a single project.

**Comment by charlesroddie** [comment]
SDK-style platform-specific projects [will come with .net 5](https://github.com/dotnet/runtime/issues/34173).

The intent of XF/MAUI is to do things in a platform-independent way most of the time. E.g. we have 98% of our XF .Net code as F# code in netstandard libraries, and the remaining 2% as C# living in platform projects, mostly boilerplate. Converting that 2% to F# doesn't seem like a big deal to me. The XF/MAUI/F# teams have more important things to do IMO.

**Comment by TimLariviere** [comment]
It still leaves the message that C# is the only important thing. If it happens to work for F# too, that's great. If it doesn't, meh.
I understand your point, but people who might be interested by F# will turn away if the tooling is lacking compared to a language they have a high chance of knowing already.

And suddenly, when you only have a single project, you're forced to either support 100% or not at all.

**Comment by Liminiens** [comment]
As a developer on an application written with Fabulous, I really hope that maui will progress with F# in mind from the first days of development.

**Comment by DualBrain** [comment]
Please let me say how much a appreciate some of the responses here... it truly helps to reinforce what I've come to believe about the F# community!  The VB community can learn so much from the F# community if they would just take the time to do so. 

Not that I have any sway in the matter... but I will share what @Padanian stated was uncalled for and he should really apologize.  His comments are regurgitating the negative behavior that I'm sure he wishes didn't have to face C# devs toward VB.  It's uncalled for, it's unnecessary and it's very much counter productive to getting any sort of positive change.

With that out of the way... let me say a public thank you to the F# community for continuing to help remind Microsoft that the CLR doesn't stand for "C# Runtime Library". ;-)  It would be helpful if those building the tooling and stacks on top of .NET would also keep this in mind when designing their stuff.

(And, yes, I'd love to see support for VB (AND F#) in MAUI - if they are going to evolve / redesign; maybe now would be a good time to design it with support for multiple languages from the go.)

To my F# brothers and sisters; keep fighting the good fight!

**Comment by Happypig375** [comment]
![image](https://user-images.githubusercontent.com/19922066/83427418-4c79f500-a463-11ea-9284-8e591939f96b.png)
#Unexpected

**Comment by DualBrain** [comment]
@Happypig375 I would suggest that 100% of the thumb downs on your comment would fall into the  "#Unexpected" category. ;-)

**Comment by Padanian** [comment]
> but I will share what @Padanian stated was uncalled for and he should really apologize. 

I won't. If anything, I will reiterate my opinion.

**Comment by cartermp** [comment]
Just to make some of this concrete:

* Project tooling support for F# _should_ come "for free" because things are based on the the ".NET project system" (also known as "SDK-style project system", or CPS). F# already works there.
* Templates would need to be figured out. They're not expensive to create, but they are a fixed cost to maintain. We've had a pretty good and easy time maintaining F# templates for ASP.NET, so I don't think it would be too expensive doing that here. What will take more time is agreeing on the scope of the templates.
* Visual designer tooling, if it exists at all, will be unlikely to happen for F#. These are incredibly expensive to build and maintain even for C# (and it shouldn't be a surprise that there hasn't been much focus on visual designer tooling in VS for many years...)

**Comment by uxsoft** [comment]
I wouldn't like to speak for all F# devs, but for me personally visual designer tooling for MVU is completely irrelevant. 

I'd be very happy if I can go file a new project and have hot reload working with F# & MAUI.

**Comment by fwaris** [comment]
Don't think a visual designer is much help for dynamic UI's. As @uxsoft  said hot reload is very much desired.

**Comment by pstricks-fans** [comment]
Ability to render mathematics equations in LaTeX format should be covered in the MAUI core library. :-)

**Comment by Happypig375** [comment]
@pstricks-fans There is a reason why this functionality is covered by [libraries](https://github.com/verybadcat/CSharpMath). Xamarin.Forms/MAUI only wrap platform-provided native controls (UIKit or Android.Widgets).

**Comment by MattMS** [comment]
The up-votes on this issue are currently over 5x the next nearest (260 vs 50) https://github.com/dotnet/maui/issues/101 ([src](https://github.com/dotnet/maui/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc))
This is really inspiring and I hope the Microsoft acquisition (and usage) of GitHub includes listening to these community signals.

It is disappointing when people are acting like we are in a zero-sum game, when we have F# people supporting VB usage and encouraging them to advocate for more VB support.
I would think that keeping .NET multi-language is in all of our interests.
Considering this issue is labeled as F# support, I'd hope we could organise a separate issue for VB, to gather battle details there.

At the end, I hope we can see all 3 in that `dotnet new` menu 😄

**Comment by Happypig375** [comment]
>The up-votes on this issue are currently over 5x the next nearest

🤓 Closed issues should also be considered, which beings the factor down to ~2.34x. #43 was just closed 3 days ago.

**Comment by fc1943s** [comment]
Thanks for speaking up guys. One day Microsoft will realize how important F# is for the company's future.
