### ISSUE TITLE
Entry.CursorPosition not working all the time

### ISSUE THREAD

**Issue by XJonOneX** [dotnet/maui#11512]
### Description

When setting CursorPosition on an Entry, it doesn't work all the time.

When setting CursorPosition to 0 on:
Android on every keypress, it only works every other time.
Windows on every keypress, it works every time.
Android on Entry.Focused it doesn't work.
Windows on Entry.Focused it works every other time.

### Steps to Reproduce

Run repro on Android
Click SomeText, doesn't set CursorPosition to 0
Click Garbage, then back to SomeText, doesn't set CursorPosition to 0
Click SomeText, start typing, it should always start at position 0, but every other kepress it starts at 1

Run repro on Windows
Click SomeText, doesn't set CursorPosition to 0
Click Garbage, then back to SomeText, CursorPosition is set to 0
Alternate clicking Entry boxes to see CursorPosition set to 0 every other focused event
Click SomeText, start typing, CursorPosition is set to 0

### Link to public reproduction project repository

https://github.com/XJonOneX/Entry.CursorPosition-Bug

### Version with bug

6.0.486

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 13, Windows 10 Home 21H2

### Did you find any workaround?

I could not find a workaround

**Comment by rmarinho** [comment]
Hello @XJonOneX 

I think there's 2 issues, but most related with racing conditions.

_"Click SomeText, doesn't set CursorPosition to 0
Click Garbage, then back to SomeText, doesn't set CursorPosition to 0"_
- Problem with the focus is that when you click the label you are setting the carret in some position so it cause an update the CursorPosition and it causes issue.  If you change focus using tab it works fine on android CursorPosition is always 0.

_"Click SomeText, start typing, it should always start at position 0, but every other kepress it starts at 1"_
- For setting the CursorPosition always to 0, instead of text change, can you try update the property CursorPosition when it changes and you always set it to 0. So you are setting the CursorPosition on Text changes, problem is that after Android fires SelectionChanged and we update the CursorPosition with what Android reports as selection start and that value is 1. I m still trying to figure the best way, but i think the workaround below will work for what you want. Please report if it helps.  

```
void EntryTextPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
{
	if(e.PropertyName == nameof(Entry.CursorPosition))
	{
		entryText.CursorPosition = 0;
	}
}
```

**Comment by drasticactions** [comment]
Checking with iOS/Catalyst, there are similar issues. The initial EntryFocused event should set the cursor to 0, but that setting gets ignored, and the cursor gets set to either the start or end of the word, as it would normally. Text entry does set the cursor to the start with each new character.

@XJonOneX What is your goal with what you're trying to accomplish with this code? Forcing all inputted text to be the first character? Is there a use case for this within your app?

**Comment by kordenv** [comment]
Unfortunately as of today 14.09.2023 the bug is still active on windows 11 too (everything is the latest version).

the first time you click - the cursor is set to 0, then click somewhere else (to remove focus), click again, the cursor is where you clicked, again unfocus, click again, the cursor is set to 0, and so on and so forth.

**Comment by jfversluis** [comment]
I know some work has gone into this. Is someone able to confirm the current status of this with .NET 8? Thanks!
