### ISSUE TITLE
Will there be a window control library similar WPF in the future?

### ISSUE THREAD

**Issue by Kukutx** [dotnet/maui#11595]
### Description

I hope that a mature front-end window control library similar WPF will appear on the Internet in the future, which will greatly improve the convenience of window design. At the same time, I also hope that the xaml style of maui in the future can be compatible with the xaml style of wpf

### Public API Changes

。

### Intended Use-Case

。

**Comment by jfversluis** [comment]
Hi there, thanks for this idea!

I'm not 100% sure what you mean, but there are a couple of great control libraries already out there. Have a look at the usual suspects like Telerik, SyncFusion, DevExpress, Grial Kit, etc. Besides those there are a good number of controls and control sets from our amazing community. Additionally, we will continue working on our controls as well, both the existing ones that we will keep working on making them better as well as introducing new ones over time.

As for the other part of your question/proposal: we don't have any plans to make big changes to our XAML dialect or make it more in line with WPF. We can't predict the future, but I don't think there will be efforts in this area any time soon.

While I really appreciate you coming to us with this feedback, this issue is not really actionable. It lacks concrete ideas and I hope that I have answered the things you were wondering anyway. Therefore I will be closing this one.

Thanks!
