### ISSUE TITLE
Winform Blazor Support JavaScript

### ISSUE THREAD

**Issue by anan1213095357** [dotnet/maui#11814]
### Description

I need to support javascript because i need some js interaction.

### Public API Changes

        var nav= await JSRuntime.InvokeAsync<IJSObjectReference>("import", "./Nav.js");
        await nav.InvokeVoidAsync("NavTo","/counter");

### Intended Use-Case

        var nav= await JSRuntime.InvokeAsync<IJSObjectReference>("import", "./Nav.js");
        await nav.InvokeVoidAsync("NavTo","/counter");

**Comment by Eilon** [comment]
Hi @anan1213095357 , can you please share more info about what you tried and what doesn't work? In general, JSRuntime / JSInterop works the same in Blazor Hybrid (including WinForms, WPF, and .NET MAUI).

Please post a complete app to a public GitHub repro that demonstrates the problem so that we can investigate further. Thank you!
