### ISSUE TITLE
Be able to pick which environments MAUI targets instead of all of them

### ISSUE THREAD

**Issue by jlipford** [dotnet/maui#11959]
### Description

We have B2B application that we would only really need to support Windows desktop and web as delivery models.
We are finding it very difficult to choose MAUI as we can only use controls that satisfy all environments which most likely means mobile support which also limits the quality of application we can delivery.

Given that WinUI 3 does not have official BlazorWebView support, was wondering if would be nice if we could configure MAUI "a la carte" style of the environment and it would allow controls and features based on those specific environments instead of the entire landscape.

### Public API Changes

Not knowlegdable enough to suggest the changes.

### Intended Use-Case

Be able to target desktop0 (windows) and web only.
Officially supporting BlazorWebView in WinUI3 would also satisfy this need.

**Comment by Eilon** [comment]
Hi @jlipford , when you create a new .NET MAUI project by default it targets Windows, macOS, iOS, and Android. If you edit the `.csproj` file you can remove any targets you don't want. You can also remove any files from the project that you no longer need.

For example, a default .NET MAUI project has these lines in the `.csproj` file:

```csproj
		<TargetFrameworks>net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>
```

And if you want to target only Windows, you can change that to:

```csproj
		<TargetFrameworks>net7.0-windows10.0.19041.0</TargetFrameworks>
```

And then you can delete any Android/macOS/iOS files or other settings from the project.

**Comment by jlipford** [comment]
@Eilon but does that mean that I can only use maui components and it locks me out of all the WinUI 3 control suite that isnt supported across the original environments?

**Comment by Eilon** [comment]
@jlipford ah, I think I understand: you ultimately want to build a WinUI3 app, but you want to use Blazor Hybrid, which isn't directly supported there. So, instead, you're using .NET MAUI because that combines both of those, but you want to be able to continue using the full suite of WinUI3 controls instead of the .NET MAUI wrappers. Is that correct?

I just did a search and saw that .NET MAUI seems to support "native embedding," which might do what you need: https://learn.microsoft.com/dotnet/maui/platform-integration/native-embedding?view=net-maui-7.0

You'd probably be the first person to try this with BlazorWebView, but I suggest giving that a try and letting us know how that goes. It does seem promising to me!

**Comment by mattleibow** [comment]
Moving this to be a feature request to support WinUI 3 directly with blazor hybrid (like WOF/WinForms)

**Comment by Eilon** [comment]
Closing this because we have https://github.com/dotnet/maui/issues/7380 to track potential WinUI3 support.
