### ISSUE TITLE
[Spec]  VisualElement Handler Lifecycle Events

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#1198]
| Event   | Description   |  Use Cases |
|---|---|---|
|  AttachingHandler  |  Fires before handler has created native view  | This is used to make sure all properties on your xplat view have been initialized so they are correctly set on inception of the native view |
|  AttachedHandler  |   Fires after handler has created and set the native view   | The NativeView is present and all of the VirtualView properties have been applied. This is where you can interact with native element |
|  DetachingHandler  |  Fires before the handler is going to get removed from the virtual view  | The NativeView is about to get removed from this Virtual element so you should unwire any native events  |
|  DetachedHandler  |   Fires after native handler has removed the native view   | |

**Comment by AmrAlSayed0** [comment]
Now that every view can have a ContainerView, can the Appearing/Appeared/Disappearing/Disappeared events be subscribed to only when needed? What I have in mind is a custom implementation for the event the keeps track of when there are subscribers or not and only use a ContainerView with the expensive overrides when it is needed to avoid unnecessary performance effects.

**Comment by PureWeen** [comment]
@AmrAlSayed0 can you elaborate on your performance concerns? Appearing/disappearing currently don't cause any additional performance overhead that I'm aware of

**Comment by AmrAlSayed0** [comment]
@PureWeen I vaguely miss-remembered this comment https://github.com/dotnet/maui/issues/30#issuecomment-632265916 plus I already know that the Java -> .NET (maybe Objective-C -> .NET too?) interop layer can be a bit slow so subclassing might cause performance issues especially if it is a method that is called multiple times in a short time.

What I'm suggesting is using the ContainerView as proxy for the actual view and do all the expensive hooking into in that rather than every MAUI control. If it is not needed then the ContainerView should be unwrapped.
