### ISSUE TITLE
[Spec] Proposed Keyboard/Mouse Specs for .NET8

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#12004]
### Currently planned for .NET8
- [x] https://github.com/dotnet/maui/issues/5211
- [x] https://github.com/dotnet/maui/issues/16216
- [x] https://github.com/dotnet/maui/issues/13346
- [ ] https://github.com/dotnet/maui/issues/11565
- [ ] https://github.com/dotnet/maui/issues/12003
- [x] https://github.com/dotnet/maui/issues/16330

### Not Planned for .NET8
- [ ] https://github.com/dotnet/maui/issues/11562
- [ ] https://github.com/dotnet/maui/issues/11979
- [ ] https://github.com/dotnet/maui/issues/11983
- [ ] https://github.com/dotnet/maui/issues/16218
- [ ] https://github.com/dotnet/maui/issues/16217
- [ ] https://github.com/dotnet/maui/issues/16202
- [ ] https://github.com/dotnet/maui/issues/16214
- [ ] https://github.com/dotnet/maui/issues/16357

### Duplicates
- https://github.com/dotnet/maui/issues/3858
- https://github.com/dotnet/maui/issues/3739

### Implementation examples

https://github.com/PureWeen/ShanedlerSamples/tree/main/ShanedlerSamples/Keyboard

**Comment by Dokug** [comment]
Not sure if this is the place, but I would love to have access to something like a
`OnKeyboardPressed(object? sender, KeyPressedEventArgs e)` Event (on desktop platforms at least), so that I could have any UI element listen to the keyboard.

For example to use as `<Frame KeyBoardPressed="{Binding OnKeyboardPressed}" />`

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/16799
