### ISSUE TITLE
Maui TabbedPage  breaks in windows when navigating

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#12065]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui-TabbedPage--breaks-in-windows-when-/10225430)._

---
When you run the application and you navigate to the tabbed page it works fine. 
But if you press the back button en try to navigate again to the tabbed page, the app breaks immediately or when you navigate to another tab.

Video:
[TabbedPageCrashing_Windows_platformMAUI.mp4](https://aka.ms/dc/file?name=B7a21bdb172ca46d7a714fce36b8ce099638060902554826238_TabbedPageCrashing_Windows_platformMAUI.mp4&tid=7a21bdb172ca46d7a714fce36b8ce099638060902554826238)

Test project:
[TabNavigationBug.zip](https://aka.ms/dc/file?name=B624b34ba666c408196de99596dc0622c638060904491351885_TabNavigationBug.zip&tid=624b34ba666c408196de99596dc0622c638060904491351885)

---
#### Feedback Bot on 12/8/2022, 05:47 PM: 

(private comment, text removed)
#### Roi Chen -MSFT [MSFT] on 12/8/2022, 11:06 PM: 

(private comment, text removed)
#### Niels Van Maelzaeke on 12/8/2022, 11:44 PM: 

(private comment, text removed)
#### Roi Chen -MSFT [MSFT] on 12/13/2022, 02:35 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 4.0. Not repro on android platform with sample project [maui-samples/7.0/Navigation/TabbedPage at main · dotnet/maui-samples (github.com)](https://github.com/dotnet/maui-samples/tree/main/7.0/Navigation/TabbedPage).

Since [TabNavigationBug.zip](https://aka.ms/dc/file?name=B624b34ba666c408196de99596dc0622c638060904491351885_TabNavigationBug.zip&tid=624b34ba666c408196de99596dc0622c638060904491351885) cannot download now, so verify the issue using this sample project [TabbedPage](https://github.com/dotnet/maui-samples/tree/main/7.0/Navigation/TabbedPage)
