### ISSUE TITLE
MAUI - AbsoluteLayout has 3 problems - SetLayoutBounds, Add and RaiseChild

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#12069]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI---AbsoluteLayout-has-3-problems---S/10219679)._

---
1. AbsoluteLayout.SetlayoutBounds(View, new Rect(x, y, w, h)) does not set width and height. You must accompany this statement with View.WidthRequest = w and View.HeightRequest = h;

2. Adding children to AbsoluteLayout Add(view, Rect) no longer exists.

3. RaiseChild no longer exists

---
#### Feedback Bot on 12/1/2022, 10:07 PM: 

(private comment, text removed)
#### Alexander Perelberg on 12/2/2022, 09:43 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
cc @hartez

**Comment by sjorsmiltenburg** [comment]
In my app I want place a label on an Absolutelayout.
Before I place it I want to measure the label height to calculate where to put it.
In XF I could put the label on the Abolutelayout off screen, measure it, and move it to the correct position.
Because now AbsoluteLayout.Add(item, point) is not available I am no longer able to do this.
Also MyAbsoluteLayout.SetLayoutBounds requires a rectangle, and can't handle a point like the old .Add method did.

Is there a workaround for this scenario?

**Comment by sjorsmiltenburg** [comment]
I spoke too soon I guess, or you could say I have found a workaround:
MyAbsoluteLayout.SetLayoutBounds(label, new Rect(0, Height, width, AbsoluteLayout.AutoSize));

**Comment by jfversluis** [comment]
I think that might be the new way to do things, also see: https://github.com/dotnet/maui/blob/main/docs/design/layout.md

If there is still something you think might be wrong or not working with this approach, please feel free to open a new issue. Thanks!
