### ISSUE TITLE
Setter showing a Build Error when using XAML OnPlatform Markup Extension

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#12064]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Setter-showing-a-Build-Error-when-using-/10217373)._

---
[severity:I'm unable to use this version]
If I try to use an On Platform XAML Markup Extension and Build the project I get an error, "Missing Value For Setter".  This does not stop the project running in debug mode, where the error disappears from the list.
However this does stop Publishing because the project will not Build (Failed to create App archive 'ProjectPlannerMAUI'. Please ensure your project builds before archiving it.).
The following shows a snippet where the first Setter is OK but the second Setter gives an error:

Error		Position 43:18. Missing Value for Setter	ProjectPlannerMAUI	C:\VSProjects\ProjectPlannerMAUI\ProjectPlannerMAUI\App.xaml	43	

```
<Style x:Key="controlStyleSmallAndroid" TargetType="Label">
                <Setter Property="FontSize" Value="18"/>
            </Style>
            <Style x:Key="controlStyleLargeAndroid" TargetType="Label">
                <Setter Property="FontSize" Value="{OnPlatform iOS=18, Android=24, WinUI=18}"/>
            </Style>
```

---
#### Feedback Bot on 11/30/2022, 06:35 PM: 

(private comment, text removed)
#### Glenn Taylor on 12/2/2022, 06:23 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
cc @StephaneDelcroix

**Comment by Hooterr** [comment]
This issue still exists. If you use `{OnPlatform}` in a app-level resource dictionary it causes build error in Visual Studio on windows. 
Weirdly enough on VS for mac it works fine...
@jsuarezruiz

**Comment by jinxinjuan** [comment]
Could you provide a sample project to repro this issue? Also other more info? Thanks.

**Comment by GDT48** [comment]
I have created a small sample project available at https://github.com/GDT48/SetterError
Added a Picker to MainPage.
Added a Style to App.XML which contains a conditional property.
Project runs in Debug without issue.
However will not build, errors:
Error		Position 14:18. Missing Value for Setter
Error		Position 14:18. Missing Value for Setter

**Comment by Hooterr** [comment]
@GDT48 looks like the repo is private.

**Comment by GDT48** [comment]
Thanks, my apologies. I have now made public.

**Comment by BretJohnson** [comment]
This works if there's a `Default` value present in OnPlatform, so that's a workaround. I believe we just need to update the error message to be more specific on what's missing.

**Comment by GDT48** [comment]
Hi Bret,

Thanks for getting back to me.

 

I tried adding iOS=#FFfafafe, but still get the error – note get only one error message rather than 2.

I tried adding default, this builds without issue.  Does not need iOS.

For completeness I also tried Value="{OnIdiom Tablet=#FFfafafe, Desktop=#FFfdfdfe}". This, without default, builds without issue which makes sense because you don’t build for a specific Idiom.

 

This suggests, for OnPlatform, you always need Default. Maybe if you referenced all possible properties you may not need Default – I tried MacCatalyst, which also gave an error without default – but I did not try all options.

 

Suggest also looking at the documentation to better explain the need for a default with OnPlatform.

 

Regards,

Glenn

**Comment by BretJohnson** [comment]
Update: I looked more at OnPlatform functionality in Xamarin.Forms and confirmed that when the platform doesn't match, there should just be no property set, not an error. So while setting a default is a workaround, we really should fix this. Looking at that now.

**Comment by BretJohnson** [comment]
Another update: With this issue, when XAML is compiled it results in the "Missing Value For Setter" XamlC error, but when XAML compilation is turned off, the result is a runtime NullReferenceException crash. So that's all the more reason to fix it, which my PR here https://github.com/dotnet/maui/pull/17061 does.

**Comment by mtarros** [comment]
> I have created a small sample project available at https://github.com/GDT48/SetterError Added a Picker to MainPage. Added a Style to App.XML which contains a conditional property. Project runs in Debug without issue. However will not build, errors: Error Position 14:18. Missing Value for Setter Error Position 14:18. Missing Value for Setter

Try removing the <ResourceDictionary> tags in App.XML and see if that fixes your issue.

I have a similar issue were debug mode runs just fine but in release build I get missing key errors and removing the ResourceDictionary tags solved my issue.
