### ISSUE TITLE
MAUI iOS is not working properly after it is delivered to Appstore, or TestFlight

### ISSUE THREAD

**Issue by christallire** [dotnet/maui#12353]
### Description

This is created because https://github.com/dotnet/maui/issues/11349 is closed.

The interpreter is not a solution, we need real AOT that we can use with Appstore / TestFlight.
Don't turn a blind eye - this is the most basic and important part of MAUI.

need to be addressed ASAP.

### Steps to Reproduce

Upload to TestFlight or Appstore

### Link to public reproduction project repository

N/A

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

**Comment by Eilon** [comment]
Hi @christallire , we need a sample app that demonstrates the issue or otherwise it's nearly impossible to determine the cause. We know there are many apps in the Apple App Store that are built with .NET MAUI, so it clearly isn't the case that .NET MAUI fundamentally doesn't work in published apps.

We need information about exactly what doesn't work so that we can try to reproduce the issue, determine the cause, and consider options to fix it.

**Comment by christallire** [comment]
I put the wrong issue link - https://github.com/dotnet/maui/issues/9597
I'll provide the repro project If you can't reproduce

**Comment by Eilon** [comment]
@christallire unfortunately in that linked issue there was not enough information to reproduce any issue, so we cannot provide any fix. Please provide a repro project in a publicly accessible GitHub repo along with details on how to reproduce the error, including any error messages, stack traces, or crash reports.

**Comment by asabbah1** [comment]
Hi Dears, 

Kindly note that I'm facing the same issue after last update of maui [7.0.52 Service Release 1.1], I'm unable to publish version due to crash after splash screen appeared, known that in debug mode it's working perfctly, and below the crash after uploading to testflight

Last version that worked well
[7.0.49]

`
Hardware Model:      iPhone10,6
Process:             Bridge [13660]
Path:                /private/var/containers/Bundle/Application/BDB9E6F4-4F76-45DE-AB4D-EDF4F7B08F0A/Bridge.app/Bridge
Identifier:          ****
Version:             4.1 (6.2)
AppStoreTools:       14C17
AppVariant:          1:iPhone10,6:16
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           ****[1446]

Date/Time:           2023-01-01 15:11:31.1616 +0300
Launch Time:         2023-01-01 15:11:30.9061 +0300
OS Version:          iPhone OS 16.0 (20A362)
Release Type:        User
Baseband Version:    5.03.01
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  0


Thread 0 name:
Thread 0 name:
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001ff41c2f4 __pthread_kill + 8 (:-1)
1   libsystem_pthread.dylib       	0x000000020dfe4654 pthread_kill + 208 (pthread.c:1670)
2   libsystem_c.dylib             	0x00000001cdb01e9c abort + 124 (abort.c:118)
3   Bridge                        	0x0000000106c4e80c 0x10437c000 + 42805260
4   Bridge                        	0x0000000106bdd968 mono_runtime_setup_stat_profiler + 42342760 (mini-posix.c:662)
5   libsystem_platform.dylib      	0x000000020df43c10 _sigtramp + 52 (sigtramp.c:116)
6   libsystem_pthread.dylib       	0x000000020dfe4654 pthread_kill + 208 (pthread.c:1670)
7   libsystem_c.dylib             	0x00000001cdb01e9c abort + 124 (abort.c:118)
8   Bridge                        	0x000000010698c3b4 print_callback(char const*, int) + 39912372 (runtime.m:1173)
9   Bridge                        	0x0000000106c176cc monoeg_g_logv + 42579660 (goutput.c:173)
10  Bridge                        	0x0000000106c17800 monoeg_g_log + 42579968 (goutput.c:184)
11  Bridge                        	0x0000000106bb83e0 load_aot_module + 42189792 (aot-runtime.c:2323)
12  Bridge                        	0x0000000106aab81c mono_assembly_request_load_from + 41089052 (assembly.c:2028)
13  Bridge                        	0x0000000106aab33c mono_assembly_request_open + 41087804 (assembly.c:1635)
14  Bridge                        	0x0000000106aacf38 mono_assembly_open + 41094968 (assembly.c:1838)
15  Bridge                        	0x000000010698baf4 xamarin_open_and_register + 39910132 (runtime.m:1000)
16  Bridge                        	0x0000000106c1a720 xamarin_register_assemblies_impl() + 42592032 (main.arm64.mm:171)
17  Bridge                        	0x0000000106994908 xamarin_main + 39946504 (monotouch-main.m:444)
18  Bridge                        	0x0000000106c1a920 main + 42592544 (main.arm64.mm:228)
19  dyld                          	0x00000001e365ade0 start + 2080 (dyldMain.cpp:1168)

Thread 1:
0   libsystem_pthread.dylib       	0x000000020dfd8674 _pthread_cond_updateval + 272 (pthread_cond.c:992)

Thread 2 name:
Thread 2:
0   libsystem_kernel.dylib        	0x00000001ff4169e0 __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x000000020dfd9584 _pthread_cond_wait$VARIANT$armv81 + 1220 (pthread_cond.c:636)
2   Bridge                        	0x0000000106ba26a0 thread_func + 42100384 (sgen-thread-pool.c:198)
3   libsystem_pthread.dylib       	0x000000020dfda060 _pthread_start + 116 (pthread.c:893)
4   libsystem_pthread.dylib       	0x000000020dfd8688 thread_start + 8 (:-1)


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0xffffffff9b39ba3f   x5: 0x0000000000000018   x6: 0x000000016ba821d0   x7: 0x000000016ba818c0
    x8: 0x00000002223f42c0   x9: 0xe9a16ecc4d8aebf0  x10: 0x3d3d3d3d3d3d3d3d  x11: 0x3d3d3d3d3d3d3d3d
   x12: 0x3d3d3d3d3d3d3d3d  x13: 0x3d3d3d3d3d3d3d3d  x14: 0x3d3d3d3d3d3d3d3d  x15: 0x0a3d3d3d3d3d3d3d
   x16: 0x0000000000000148  x17: 0x00000001c1f9f158  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000000000103  x21: 0x00000002223f43a0  x22: 0x0000000000000007  x23: 0x0000000000002788
   x24: 0x0000000106ffa0a4  x25: 0x0000000000000038  x26: 0x0000000000000268  x27: 0x0000000106e93698
   x28: 0x0000000282964000   fp: 0x000000016ba821e0   lr: 0x000000020dfe4654
    sp: 0x000000016ba821c0   pc: 0x00000001ff41c2f4 cpsr: 0x40000000
   esr: 0x56000080  Address size fault


Binary Images:
0x10437c000 - 0x106e43fff Bridge arm64  <e2655dc56c313cf6a34216dc1886fc48> /private/var/containers/Bundle/Application/BDB9E6F4-4F76-45DE-AB4D-EDF4F7B08F0A/Bridge.app/Bridge
0x1cdae2000 - 0x1cdb5dfff libsystem_c.dylib arm64  <637814c516103a04b2544eb2b26b750b> /usr/lib/system/libsystem_c.dylib
0x1e3647000 - 0x1e36c0dcb dyld arm64  <39fb7cd57af23e3c9cefb214ddbc3353> /usr/lib/dyld
0x1ff415000 - 0x1ff44afff libsystem_kernel.dylib arm64  <f984bd5d5eb83894b57d307eab4e7b07> /usr/lib/system/libsystem_kernel.dylib
0x20df41000 - 0x20df4cfff libsystem_platform.dylib arm64  <d5407b3ff61c3a1d8a11c713f8a9e920> /usr/lib/system/libsystem_platform.dylib
0x20dfd7000 - 0x20dfe7fff libsystem_pthread.dylib arm64  <c505adfd68fb3e92aaa8af0ed030c66b> /usr/lib/system/libsystem_pthread.dylib

EOF`

**Comment by asabbah1** [comment]
Repo URL: https://github.com/asabbah1/BridgeMaui

**Comment by mattleibow** [comment]
This issue was moved to xamarin/xamarin-macios#17142
