### ISSUE TITLE
ScrollView Inside StackLayout Not Working in MAUI

### ISSUE THREAD

**Issue by TonyLugg** [dotnet/maui#12452]
### Description

ScrollView doesn't seem to work in MAUI.  In Xamarin Forms I would put a large margin at the bottom of a long entry form so that the keyboard didn't cover the bottom entry boxes.  It isn't working in MAUI.

### Steps to Reproduce

<AbsoluteLayout x:Name="LayoutRoot">
        <StackLayout
              AbsoluteLayout.LayoutFlags="All"
              AbsoluteLayout.LayoutBounds="0,0,1,1">
            <ScrollView>
                <StackLayout Padding="10,10,10,300">
...

### Link to public reproduction project repository

(https://github.com/ctapcorp/MauiScrollViewIssue)

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

11-16

### Did you find any workaround?

I resolved it by removing the top stack panel and making the ScrollView a direct child of AbsoluteLayout.  This would not be a feasible solution for some pages that have more than the ScrollView in the StackLayout.

**Comment by TonyLugg** [comment]
I created a [repro](https://github.com/ctapcorp/MauiScrollViewIssue)

**Comment by hartez** [comment]
```
<AbsoluteLayout x:Name="LayoutRoot">
        <StackLayout
              AbsoluteLayout.LayoutFlags="All"
              AbsoluteLayout.LayoutBounds="0,0,1,1">
            <ScrollView>
```

What's the intent  of the StackLayout? Is there some reason not to make the ScrollView the immediate child of the AbsoluteLayout?

**Comment by TonyLugg** [comment]
@mattleibow I created a repro.  @hartez It is a pattern I've used.  Sometimes there are other elements above the ScrollView.  I may change to the DockLayout, but the existing XAML worked in Xamarin Forms.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on Windows 11, Android 13.0-API33 and iOS 16.4 with below Project:
[MauiScrollViewIssue.zip](https://github.com/dotnet/maui/files/11743454/MauiScrollViewIssue.zip)

**Comment by hartez** [comment]
This is by design. A vertically-oriented StackLayout is supposed to give its child controls as much vertical space as they want; the ScrollView inside the StackLayout gets all the space it wants (enough to lay out the entire child StackLayout). Since the ScrollView's viewport is not vertically constrained, there's no reason for it to scroll. 

Xamarin.Forms did some weird things to make this specific layout work, basically special-casing the behavior of a ScrollView in a vertical StackLayout. It was confusing, bad for performance, and not consistent across platforms, so we didn't port that behavior to MAUI.Controls. 

There are several ways to make this sort of layout work on MAUI:

1. The easiest thing to do is to set the VerticalOptions on the ScrollView to "StartAndExpand". This will trigger the legacy behavior for StackLayout and make it act as if it were a single-column Grid. (This is effectively what it's doing in Forms when it special-cases the "ScrollView inside StackLayout" behavior.) 

2. Alternatively, replace the outer StackLayout with a Grid. This will constrain the ScrollView vertically and allow for scrolling. 

3. "But wait, I want to stack things above the ScrollView." Okay, divide your Grid up into two rows, and put a StackLayout in the first row: 

```xaml
<Grid RowDefinitions="Auto,*">
	<StackLayout Grid.Row="0">

		<Label Text="A header or whatever" />
		<Label Text="Other stuff" />

	</StackLayout>
        <ScrollView Grid.Row="1">
        ...
        </ScrollView>
</Grid>
```
