### ISSUE TITLE
BlazorWinFormsApp and BlazorWpfApp throw NullReferenceException when using ExampleJsInterop in .NET 6 Preview 3

### ISSUE THREAD

**Issue by Jinjinov** [dotnet/maui#1245]
### Describe the bug

If ExampleJsInterop is called from WinForms or from WPF it throws a NullReferenceException

### To Reproduce

In WinForms:
- open https://github.com/dotnet/aspnetcore/tree/main/src/Components/WebView/Samples/BlazorWinFormsApp
- `Form1.cs`, add `WebviewAppShared.ExampleJsInterop exampleJsInterop;` to `class Form1`
- add `exampleJsInterop.Prompt("Hello world!");` to `button1_Click`
- add `serviceCollection.AddScoped<WebviewAppShared.ExampleJsInterop>();` below `var serviceCollection = new ServiceCollection();`
- replace `blazorWebView1.Services = serviceCollection.BuildServiceProvider();` with

        IServiceProvider serviceProvider = serviceCollection.BuildServiceProvider();
        blazorWebView1.Services = serviceProvider;
        exampleJsInterop = serviceProvider.GetRequiredService<WebviewAppShared.ExampleJsInterop>();

- run app
- click on `Click to see counter value`

In WPF:
- open https://github.com/dotnet/aspnetcore/tree/main/src/Components/WebView/Samples/BlazorWpfApp
- `MainWindow.xaml.cs`, add `WebviewAppShared.ExampleJsInterop exampleJsInterop;` to `class MainWindow`
- add `exampleJsInterop.Prompt("Hello world!");` to `Button_Click`
- add `serviceCollection.AddScoped<WebviewAppShared.ExampleJsInterop>();` below `var serviceCollection = new ServiceCollection();`
- replace `Resources.Add("services", serviceCollection.BuildServiceProvider());` with

        IServiceProvider serviceProvider = serviceCollection.BuildServiceProvider();
        Resources.Add("services", serviceProvider);
        exampleJsInterop = serviceProvider.GetRequiredService<WebviewAppShared.ExampleJsInterop>();

- run app
- click on `Check counter`

### Exceptions (if any)

    System.NullReferenceException: 'Object reference not set to an instance of an object.'

### Further technical details
- ASP.NET Core version: `16.10.127.22515`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: `Visual Studio 2019 - Version 16.10.0 Preview 1.0`
- Include the output of `dotnet --info`

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

.NET SDKs installed:
  3.1.406 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.21077.7 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspN
etCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspN
etCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [C:\Program Files\dotnet\sha
red\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore
.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore
.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [C:\Program Files\dotnet\shared\
Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.W
indowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.
WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.
WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.W
indowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.W
indowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.3.21201.3 [C:\Program Files\dotnet\
shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by Eilon** [comment]
I tried this with the Photino.NET sample in the repo and it works. But WPF isn't working. Will investigate more.

**Comment by Eilon** [comment]
For some reason in WPF (and probably WinForms), we get more than 1 instance of `WebViewJSRuntime`, and the "later" ones are not properly initialized, meaning that they don't have an `ipcSender`, so they null-ref.

**Comment by Eilon** [comment]
Just guessing, but it appears that because the `WebViewJSRuntime` is a scoped service, that for some reason a new instance is being created from a new scope, and that new instance is not properly initialized.

So why did the Photino.NET sample work? Because the sample code was different. In my Photino.NET repro I was using `@inject RazorClassLibrary1.ExampleJsInterop exampleJsInterop` from one of the Razor components to call the JS code. That presumably uses the correct scope. But in the WPF repro the code is getting the `ExampleJsInterop` service from the "WPF" code, and I guess that's using a different scope.

**Comment by Eilon** [comment]
@SteveSandersonMS / @javiercn - I'd love your input on this one. I'm guessing that this behavior might be by-design, but then I'm not sure the right way to build this sample.

I sense that I want to somehow "run some .NET code as if it's in the context ("scope") of the code in the Razor component" and thus share the same DI scope, and thus get the same instances of services that are available within that scope.

**Comment by SteveSandersonMS** [comment]
@Eilon The slightly awkward thing is that, each time the page inside the BlazorWebView reloads, we set up a new scope. We have to do that because (for example) you have a new JS context with no pre-existing state so we have to reset everything to do with it. It's like reloading the page with WebAssembly or Server - those create new DI contexts too.

So given this, if some code outside that system asks for a scope, which scope does it get? One that might become obsolete later if the page is reloaded? Kind of dangerous, but represents the truth about what's going on.

We could address this simply by exposing some `IServiceProvider? CurrentPageServices { get; set; }` property from WebViewManager whose value may be null (if no page has yet loaded) or may change (if the page navigates) and then trust the developer to understand this and not store a reference to the instance anywhere. TBH this is probably not too bad really.

Alternatively we could have some kind of `RunAsync(Func<IServiceProvider, Task>` method on WebViewManager that's some kind of combo of "dispatch" and "give me the current service provider" to encourage people to treat it as a transient thing. Not sure people will follow the reasoning though.

What do you think?

**Comment by Eilon** [comment]
@SteveSandersonMS yes the `RunAsync` sounds pretty neat, because it should always work (right?). The problem with `CurrentPageServices` is that I feel that there's no good way to predict when it's valid and non-null (right?).

I'm basically thinking about how I would want to write the sample code in the app in a way that is predictably correct, and I think something like:

```c#
void Button_Click()
{
    blazorWebView1.RunAsync(async (services, more_context_needed(?)) => {
        var js = services.Get(...);
        await js.DoStuff();
    });
}
```

I wonder if there's any other context that we would want to provider? Or, if the entire purpose of this is to provide the scoped services, then logically that's the only context that's needed, so it would be sufficient.

**Comment by VincentBu** [comment]
I try the Winform Sample and run into the same error.

**Comment by MackinnonBuck** [comment]
Confirmed that this is still an issue.

**Comment by MackinnonBuck** [comment]
We've decided that since we don't yet have enough data about how JS interop could be used outside of a Razor component context, or if doing so is even a common scenario at all, we are going to de-prioritize this issue for now.

JS interop occurring within a Razor component (which is the context for which JS interop was designed) is not impacted by this issue.

Leaving this issue open in case this is something we want to consider for the future.

**Comment by Jinjinov** [comment]
> we don't yet have enough data about how JS interop could be used outside of a Razor component context

I have one use case for a Blazor WPF app that shares 99% of the code with a Blazor WASM PWA:

I would like to load my data from IndexedDB right after I setup `IServiceCollection` and `IServiceProvider`.

You can do this in a Blazor WASM before `await host.RunAsync()` so all your Razor components can use the data right away.

This way you don't have to override `async Task OnInitializedAsync()`
