### ISSUE TITLE
Calling async method inside CreateMauiApp

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/maui#12524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

I ran into a problem when migrating existing Blazor WASM app to Blazor MAUI.

I need to issue an async call inside ``public static CreateMauiApp()`` method which is synchronous. Using discard seems to work but I wonder if there is a plan to eventually create ``public static Task CreateMauiAppAsync()`` method or if there is something that I'm missing:

```csharp
_= host.Services.GetRequiredService<BlazorComponentLibState>().InitializeAsync();
```

Thanks!

**Comment by javiercn** [comment]
Removing `area/blazor` as the question is not Blazor specific.

We'll let maui triage the question to see if they have additional guidance to offer.

**Comment by mattleibow** [comment]
The reason that `CreateMauiApp` is NOT a Task or anything async because on some platforms the app has to be complete and loaded in a matter of seconds. I think on iOS you have 3 seconds.

To do something like this you probably want to have some inti method on the service as you have, but then make sure to catch any exceptions. So you might want to make the init method like this:

```cs
class BlazorComponentLibState
{
  private Task initTask;
  public BlazorComponentLibState(ILogger logger) {}

  public async void Initialize()
  {
    try 
    {
      initTask = InitializeAsync();
      await initTask;
    }
    catch (Exception ex)
    {
      logger.LogError(ex);
    }
  }

  public void InitializeAsync()
  {
    
  }

  public async Task DoSomething()
  {
    await initTask;
    // do more
  }
}
