### ISSUE TITLE
WYSIWYG designer or drag and drop interface

### ISSUE THREAD

**Issue by GeraudFabien** [dotnet/maui#126]
## Summary
Since it was out of scope there https://github.com/dotnet/maui/issues/43

>All of you are right, but an option should also be available for beginners
to build apps crossplatform using something similar to windows forms drag
and drop, because ir makes things so much easier and manageable and
automatically, i think their should always be an option like this, in
modern day too, development shouldn't be only code code code it should be a
bit fun too.

**Comment by robloo** [comment]
This is a good point. It's also a reason why Windows Forms and WPF/UWP continue to co-exist. For simple apps and beginners nothing is faster than Windows Forms with it's drag-and-drop approach to UI design. For advanced scenarios Windows Forms cannot compete with XAML and WPF/UWP though.

**Comment by GeraudFabien** [comment]
I don't agree with this since it's more problem even for beginner than anythinks else.
The fact that WinForm is WYSIWYG oriented is it's main default in my POV
It cost a lot to implement and don't bring anythinks more thant just a Hot Reload.
Hot reload enable to see the real render when you're not sure with WYSIWYG when there is a lot of plateform

**Comment by davidbuckleyni** [comment]
This is not a proper spec than just suggestion

**Comment by davidbuckleyni** [comment]
Please see the spec here Xamrain wont except one line proposals you have to be through in your design and reasoning behind it.

https://github.com/dotnet/maui/issues/128

They will prob be doing a cleanse of issues that deam not worthy so please be precise with your request.

**Comment by GeraudFabien** [comment]
I'm sorry my goal was to make a neutral comment. Since i don't really agree. That why i didn't add more than one line. But you're reply get me the idea to quote the Xamarin Issue. Thanks :)

**Comment by GeraudFabien** [comment]
Close since @davidbuckleyni open a reply here https://github.com/dotnet/maui/issues/128

**Comment by Joebeazelman** [comment]
> I don't agree with this since it's more problem even for beginner than anythinks else.
> The fact that WinForm is WYSIWYG oriented is it's main default in my POV
> It cost a lot to implement and don't bring anythinks more thant just a Hot Reload.
> Hot reload enable to see the real render when you're not sure with WYSIWYG when there is a lot of plateform

I can tell you've never used a real WYSIWYG editor. We had tons of them back in the 80s and 90s using C/C++. They were a joy to use and extremely productive. The most well known among them, VB, expanded Windows development.  Delphi which the .NET Forms designer is based on, was even better.  It seamlessly mapped source code to controls. Even the basic Windows resource editor allowed the developer to quickly flesh out a UI with a minimal amount of code. These tools were used by professionals and beginners. Today, these productivity tools are seen as tools of the inept?  It shows a race to the bottom.

It's laughable to hear the term "responsive" thrown around as if it is something entirely new. While most desktop interfaces were fixed width, many WYSIWYG tools generated flexible interfaces. The lengths I see developers go through to implement it, is laughable by comparison. Both NEXT's Interface Builder and Metrowerk's PowerPlant, made responsive layouts a non-issue.  

WYSIWYG GUI development and other technologies fell by the wayside in favor of ancient and user hostile ones such as the command line, archaic screen editors and Git borrowed because they are free.  Apple understands developers are also humans and tries to make their user experience equally as painless as the rest of their users.
