### ISSUE TITLE
[Android]camera permission is not enabled on launching the maui app

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [dotnet/maui#12711]
### Description

I have enabled camera permission on launching the app, it suppose to prompt the user with options instead throws the below exception.
![image](https://user-images.githubusercontent.com/44390143/212876253-d8ccc5e9-a7df-4976-9083-ae1f6b844e60.png)

Tried adding in MauiProgram.cs as well still same response.

### Steps to Reproduce

1. Open any maui sample
2. Enable camera permission as in snap shot.
3. Deploy app in android device.

### Link to public reproduction project repository

occurs in simple sample itself

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

11.0

**Comment by rachelkang** [comment]
Hi, @GnanaPriyaNamasivayam - unfortunately, you can't request the permissions from App.cs. Try requesting permissions once the app is started. If you continue to have issues, please share a repro so that we can investigate further!

@davidbritch could we improve [our docs](https://learn.microsoft.com/dotnet/maui/platform-integration/appmodel/permissions?view=net-maui-7.0&tabs=android) perhaps to help developers understand where to request permissions?

**Comment by davidbritch** [comment]
@rachelkang I've added an issue to the docs repo to cover this, so it can be closed here.

**Comment by GnanaPriyaNamasivayam** [comment]
Thanks @rachelkang & @davidbritch That helps. It's working as expected now.
