### ISSUE TITLE
Missing property for Entry control (TextContentType)

### ISSUE THREAD

**Issue by npostma** [dotnet/maui#12985]
### Description

To port my xamarin custom renders i need the `TextContentType` exposed in the contols for iOS. But i cant find this anywhere. In the custom Renderer (extended form EntryRenderer) i have a `Control` property with a `TextContentType` . I can set it to  NewPassword, Username, Password, etc. But when i create a controle i only have IsPassword. This is not enough . I need to set my fields specific to username, newpassword and password.  

### Steps to Reproduce

A way to change:

```
public class UsernameEntry: EntryRenderer
    {
        protected override void OnElementChanged(ElementChangedEventArgs<Entry> e)
        {
            base.OnElementChanged(e);

            if (Control != null)
            {
                Control.TextContentType = UITextContentType.Username;
            }
        }
    }
    ```
    
    to 
    
    ```
internal class UsernameEntry : Entry
    {



        public UsernameEntry() : base()
        {
#if __IOS__ || __MACCATALYST__
            // This does not work
            TextContentType = UITextContentType.Username;
#endif

        }

    }
```
    

### Link to public reproduction project repository

no link,

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS all versions.

### Did you find any workaround?

No workaround yet. Setting IsPassword is not enough and gives issues with the iOS strong generated password. This is not storing in the keychain. Having fine grained control i can turn off this functionality. Now i cant, and then i have the issue that accounts are created for users with a strong password but not stored in the keychain. So their account is useless. 

### Relevant log output

```shell
No output to display here.
```

**Comment by jsuarezruiz** [comment]
https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize?view=net-maui-7.0

**Comment by jfversluis** [comment]
Heya Nick!

Simply doing as you tried to do unfortunately won't work.

```csharp
internal class UsernameEntry : Entry
{
        public UsernameEntry() : base()
        {
#if __IOS__ || __MACCATALYST__
            // This does not work
            TextContentType = UITextContentType.Username;
#endif
        }
}
```

This way what you are still trying to do is set the `Entry.TextContentType` which isn't a thing. Just setting the `#if __IOS__ || __MACCATALYST__` doesn't automatically turn an `Entry` into the iOS equivalent. 

If you look at the renderer you posted, you see that you're also setting this property on `Control` which is the platform counterpart of entry.

```csharp
public class UsernameEntry: EntryRenderer
{
    protected override void OnElementChanged(ElementChangedEventArgs<Entry> e)
    {
        base.OnElementChanged(e);

        if (Control != null)
        {
            Control.TextContentType = UITextContentType.Username;
        }
    }
}
```

What you want to do, is change something in the mapping which is the replacement of a renderer basically. You can read all about handlers and mappers [here](https://learn.microsoft.com/dotnet/maui/user-interface/handlers/), so I won't go over it in all the detail here, but in short its like this: each control now has their own handler and each property of that control has their own mapper.

With that in mind, let's consider this code.

```csharp
Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping("SetUserNameContentType", (handler, view) =>
{
#if IOS || MACCATALYST
    if (view is UsernameEntry)
    {
        handler.PlatformView.TextContentType = UITextContentType.Username;
    }
#endif
});
```

Through the static `EntryHandler` I can access it from anywhere, so put this wherever your want. Then the `AppendToMapping` will first run the mapping we have in place for all properties on an `Entry` and then it will append whatever you put in this block.

Now, this mapper will run for all platforms, but we just want to make use of specific iOS functionality, so add the `#if` for that and inside of that we can get the associated `UITextField` for this `Entry` with `handler.PlatformView`. On that `PlatformView` we can now set the platform-specific property that you are after.

In this case I checked if our `Entry` is your specialized `UsernameEntry` if you leave that out it will apply to all `Entry` instances.

For all this in more detail, also on how to structure your code different if you don't like `#if` check out the [documentation](https://learn.microsoft.com/dotnet/maui/user-interface/handlers/customize).

Hope this helps!

There isn't a lot for us to do here since there isn't really a bug. So I will be closing this one now. Thanks!

**Comment by npostma** [comment]
Thanks! I am looking into it. I think i know where i thought wrong, i thought `this` was the control  (or better that entry was a specialization of Control) . I've red that every control had its own (and only one) mapper/hander and this is global. So having specializations of entry is still needed.
