### ISSUE TITLE
Cursor is trapped in text field during fast text copying/text input.

### ISSUE THREAD

**Issue by true-perfect-code** [dotnet/maui#13064]
### Description

There is a strange behaviour. If you have several text fields and you enter the values very quickly via Control V or Enter, the cursor is caught in the field. No matter where you click with the mouse, nothing happens. At first we assumed that it came from the Ant-Blazor UI component, but in the meantime we have been able to exclude this.

### Steps to Reproduce

We have put a sample project on GitHub that you can use to reproduce this behaviour. See https://github.com/true-perfect-code/AntBugsMAUI.git

### Link to public reproduction project repository

https://github.com/true-perfect-code/AntBugsMAUI.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

If you enter the values slowly, there are no problems.

**Comment by Eilon** [comment]
Hi, this is a known issue with WebView2 on WinUI/WindowsAppSDK, which is what Blazor Hybrid's BlazorWebView uses.

You can track the main issue here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3003

**Comment by alelom** [comment]
Thank you for reporting that @Eilon, I can finally stop going mad searching for a reason.
However it is worth noting that the bug there has been opened for a long time, without a solution in sight.

That issue is a major dealbreaker for MAUI too and it should well highlighted. I am now forced to consider porting my MAUI Hybrid app to other frameworks.
