### ISSUE TITLE
🙋🏽‍♀️ [Survey] GitHub contributor experience

### ISSUE THREAD

**Issue by samhouts** [dotnet/maui#13252]
### .NET MAUI Community! We want to hear from YOU! 

Last year, we asked you for your feedback, and we heard that you wanted more transparency on what we're working on, better instructions for getting started, and more videos showing you how to work in the repository! As a result, we added the MAUI SDK Ongoing project, updated our getting started documentation, and upped our YouTube game. Have you seen these??? https://www.youtube.com/watch?v=8LRfy6Omp9I https://www.youtube.com/watch?v=nxdApcTMjz8

Now, we're asking you again to let us know how we're doing as maintainers. Fill out the survey in the link below and tell us what you think.

Whether you've been involved for years or you're relatively new, please tell us about your experience participating and contributing to the project. It should only take a few minutes, and you can answer for up to 3 repos:

https://www.surveymonkey.com/r/8KTX9VT?Source=dotnet/maui

**Comment by Xyncgas** [comment]
I wish github makes it easier, for me to search stuffs up in .NET source code (like https://source.dot.net/), then make the change and sumbit change as PR all in one go online

**Comment by Xyncgas** [comment]
Since we are working so hard to maintain projects for our users, we can have a 'sponsored' section of issues in our repositories that we can work on first, while clients can give more money if they want the issue to be fixed faster than others

**Comment by Ghostbird** [comment]
> Since we are working so hard to maintain projects for our users, we can have a 'sponsored' section of issues in our repositories that we can work on first, while clients can give more money if they want the issue to be fixed faster than others. Since we have limited resources, if a bug is causing a company to lose millions monthly then they are willing to pay 1 million for you to get it fixed this week, it helps both sides on what to focus and we are rewarded on both sides to get what we need. We can also out source some of these issue for free lancers out there who are willing to fix it and whoever fixed it the fastest claims the price this way we can create an entire industry of bug hunters and you can now hire a bunch bounty hunters for your product if you are a very rich company instead of facing 2k issues daily

I think the idea may have merit, but your argumentation is faulty. A company that loses millions monthly because of a bug in an Open Source repo will not sponsor it for a lot of money. That's ineffective compared to the sensible alternative, donate manpower. This might not apply in all cases, but in the case of MAUI, the software is written in C# .NET and the users are mostly developers that use C# .NET, so it's a good fit. See for example #12766. This was preventing Android 13 releases for everyone who wanted to take a picture. Once I'd proven to my boss that it was a bug in MAUI, and not in our code, I told him we could for now build using Android API 32, but I could probably fix it within a few hours and make a PR. He approved, and it will be in the next release.
