### ISSUE TITLE
Connectivity.ConnectionProfiles contains WiFi instead of Ethernet when Ethernet connection is available

### ISSUE THREAD

**Issue by kegesch** [dotnet/maui#13299]
### Description

`ConnectionProfiles` should contain `Ethernet` when the iOS device is connected via ethernet. Instead, `WiFi` is shown.
This screenshot of the reproduction example app shows, that the device is not connected to `WiFi` (there would be an icon in the title bar), but is connected to ethernet and the output of `ConnectionProfiles` shows `WiFi`.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/7421630/218493160-4f771cdb-5ffe-4f57-b5a3-3c127578da97.png)

### Steps to Reproduce

Call `Connectivity.Current.ConnectionProfiles`

### Link to public reproduction project repository

https://github.com/kegesch/maui-connection-profile-ethernet-bug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.3

**Comment by vik-koch** [comment]
It seems like the problem exists due to the use of the older legacy SCNetworkReachability API ([opened issue](https://github.com/dotnet/maui/issues/2574)), where there is no differentiation between WI-FI and Ethernet connection.

Here is a platform-specific workaround we used to detect an active Ethernet connection:

```
using Network;
...
var monitor = new NWPathMonitor();
monitor.SetQueue(CoreFoundation.DispatchQueue.DefaultGlobalQueue);
monitor.Start();

if (monitor.CurrentPath?.UsesInterfaceType(NWInterfaceType.Wired) == true)
{
   // Active Ethernet connection is present
};
```

Without setting the DefaultGlobalQueue this monitor was reacting only to the connection changes.

The same problem might also persist on MacCatalyst.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Not repro on iOS platform with sample project.
[maui-connection.zip](https://github.com/dotnet/maui/files/11878176/maui-connection.zip)
![IMG_5589](https://github.com/dotnet/maui/assets/77434865/59256eca-562a-4ed5-a88f-bfeaa6a2d7ef)
