### ISSUE TITLE
Title bar lags behind when resizing

### ISSUE THREAD

**Issue by PerfectlyFineCode** [dotnet/maui#13479]
### Description

The title bar lags behind when resizing the window for Windows.

https://user-images.githubusercontent.com/70201838/220348433-4c709f46-a6fc-42bb-bcd8-aeecb277e7c2.mp4

### Steps to Reproduce

1.) Create a new .NET MAUI App project
2.) Start the app
3.) Resize the window horizontally.
4.) The title bar should now lag behind

### Link to public reproduction project repository

https://github.com/PerfectlyFineCode/RecipeManager

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 (22621.1265)

### Did you find any workaround?
https://github.com/dotnet/maui/issues/13479#issuecomment-1442431197

**Comment by Eilon** [comment]
I wonder if this is an issue in WinUI itself?

**Comment by PerfectlyFineCode** [comment]
> I wonder if this is an issue in WinUI itself?

It is very possible.

**Comment by Eilon** [comment]
This doesn't seem to happen on a default WinUI3 app. And regarding MAUI, even if I remove every non-absolutely-required thing from a default MAUI project, it _still_ has that little bit of lag in the title bar.

1. Create new MAUI project (.NET 7)
2. Remove all AppShell, custom fonts, etc.
3. Change MainPage to have just a Label, and set it as the main page in App.xaml.cs
4. Run the app
5. Resize the window's width back and forth rapidly

Result: The "min/max/restore" buttons have some lag and delay their movement a tiny bit. This is on a very high end modern machine.

This strikes me as possibly a performance issue, such as something re-computing during every resize, and causing other UI artifacts such as this.

**Comment by rachelkang** [comment]
@hartez "related to ContentPanel sizing issues"

**Comment by cyberrex5** [comment]
this is a winui 3 issue: https://github.com/microsoft/microsoft-ui-xaml/issues/5446

**Comment by cyberrex5** [comment]
i think the only solution is to not render the titlebar in winui, i.e. use a native titlebar. (at least until the winui issue gets resolved, which is very unlikely)

**Comment by Eilon** [comment]
> this is a winui 3 issue: https://github.com/microsoft/microsoft-ui-xaml/issues/5446

Oh, does MAUI "custom draw" the title bar? I don't know that part of the codebase, but if that's the case, then it does sound like that.

**Comment by hartez** [comment]
> This doesn't seem to happen on a default WinUI3 app.

Default WinUI 3, or default UWP app? Because in addition to https://github.com/microsoft/microsoft-ui-xaml/issues/5446, there's also https://github.com/microsoft/microsoft-ui-xaml/issues/2506 and https://github.com/microsoft/microsoft-ui-xaml/issues/5148. 

> Oh, does MAUI "custom draw" the title bar? I don't know that part of the codebase, but if that's the case, then it does sound like that.

We don't draw the default title bar. I think they're referring to a native Windows titlebar, as opposed to whatever WinUI is doing.

**Comment by cyberrex5** [comment]
all those issues are talking about the same issue.
the 'flickering" is the content resize being slow and showing the actual background color which is white if your using light mode, and black if you're using dark mode.

as you can see in all of those the title bar does *not* resize slowly with the rest of the window, because winui 3 uses a native titlebar.

also afaik winui 3 is a seperate framework than uwp. you can either use uwp + winui 2, or winui 3.
I think what they mean by winui 3 uwp is packaged winui 3.
uwp does not suffer from this issue.

**Comment by hartez** [comment]
So we customize the title bar for a WinUI MAUI app, but we're just using the built-in WinUI methods for doing so. Nothing extreme, and it's just using WinUI controls. But as soon as we start doing that, the same resizing problem that happens for window content starts happening with the title bar. 

For users who want to work around this (until it's fixed at the WinUI level), you _can_ use the default Windows title bar as @cyberrex5 is suggesting. Just add this to your MauiProgram.cs to disable the MAUI customizations:

```
#if WINDOWS
			Microsoft.Maui.Handlers.WindowHandler.Mapper.Add("UseDefaultTitleBar", (handler, _) => { handler.PlatformView.ExtendsContentIntoTitleBar = false; });
#endif
```

That will disable all the MAUI customizations (
