### ISSUE TITLE
Visual Studio cannot launch Android Emulator

### ISSUE THREAD

**Issue by chentow2x** [dotnet/maui#13511]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

![image](https://user-images.githubusercontent.com/73778261/220823103-e294a17d-93e6-431b-b03a-55ad78ec37a4.png)

> VS bug [#1752742](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1752742)

**Comment by mariaghiondea** [comment]
@chentow2x what version of Visual Studio are you using? Did you get a chance to log a feedback item?

**Comment by chentow2x** [comment]
Hi Marria,

   Please see below:
![image](https://user-images.githubusercontent.com/73778261/221440729-a39b9638-7126-4b24-adcc-797512057cef.png)
   I dont see any log so far. Can you guide me where should I be looking?

Regards,
Ray

**Comment by mariaghiondea** [comment]
@chentow2x did you log a Developer Community feedback? By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks.

Go to the [Visual Studio for Windows feedback tool](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) or [Visual Studio for Mac feedback tool](https://learn.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2022) to report the issue
Close this bug, and consider adding a link to the VS Feedback issue so that others can follow its activity there.
