### ISSUE TITLE
Project build error

### ISSUE THREAD

**Issue by bhavesh4asi** [dotnet/maui#1379]
Hello Team,

Here are steps,

1. Brand new machine. Windows 10.
2. Install Visual Studio 2019 Preview 16.11.0 Preview 2.0
3. Perform maui-check and all up to date
4. Start Visual Studio and create project from Maui template. 

I am not able to build my project. Here are the issues.

1. It created two projects, "MauiApp2" and "MauiApp2.WinUI". I did everything but in project 2 (WinUI) Dependencies warning under SDK is not going away. I installed Windows 10 SDK also. 

2. I setup windows to MAC link but every time I compile my 1st project "MauiApp2" it is giving me "No Available connection to Mac error". 

3. I try to rebuild the project from VS but it's not working. 

4. I try to build project via command line still it's not working. 

I attach the complete build log zip file.

Can you please suggest to 

me how I remove those dependencies warning signs and how to resolve those build errors so I perform basic testing?

Thank you

Attached following items,

1. Build log
2. Dependencies warning 

[msbuild.zip](https://github.com/dotnet/maui/files/6679702/msbuild.zip)
![image](https://user-images.githubusercontent.com/80860213/122625131-5fed0380-d058-11eb-8104-0c33e931a2d3.png)

**Comment by ncarandini** [comment]
Hi,
I've succeeded after following  [.NET MAUI installation instructions](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation) because it seems that maui-check don’t install the Project Reunion needed stuffs.

After doing that, the project build and the app starts, but:
1) On the WinUI project the Dependencies node in the Solution Explorer still shows a warning sign of missing SDK but I’ve double checked and the SDK is installed. Moreover, the projects builds and the app run fine.
2) When the app starts, the window has only the background color and nothing else is shown. The text, the “click me” button and the image are shown only when I resize the window.
3) When I click on the “click me” button, the layout of the page changes showing a wider margin.

**Comment by bhavesh4asi** [comment]
I did all possible try but still not working. I am stuck at the same original error. 

1. I installed Project reunion stuff.
2. I connect my windows machine to Mac.
3. I attach iPhone also to my windows machine but it still not recognize iPhone and keep looking for a device.

I still not pass through the original build log two errors.

**Comment by Eilon** [comment]
I'm closing this issue because these issues should be resolved by now. Please note that at this time Visual Studio 2022 is required (not 2019).

The steps at https://docs.microsoft.com/dotnet/maui/get-started/installation are the most up-to-date.
