### ISSUE TITLE
Easy way to get Color from Colors.xaml

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#14007]
### Description

Hi,

Referring to this Q&A:

[https://learn.microsoft.com/en-us/answers/questions/1190458/setappthemecolor-throws-exception-has-been-thrown](https://learn.microsoft.com/en-us/answers/questions/1190458/setappthemecolor-throws-exception-has-been-thrown
)

It will be great if you implement an easier way to get the value from the Colors.xaml

### Public API Changes

`Color myColor = App.Current.Color["MyColorFromXAML"];
`

and it should be Color type by default so we don't need to convert it because it is already defined as <Color> inside the Colors.xaml

### Intended Use-Case

This will make it just a straightforward line to retrieve the colors from the Colors.xaml for all kind of apps.

**Comment by mattleibow** [comment]
This is interesting since the Colors.xaml file is actually arbitrary and has no bearing in the final app. It all gets loaded into the app's resources. However, the default Colors.xaml also has SolidColorBrush. How would you see this working?

I do loke the way Android did resources with code access using an ID.

I wonder if there is a way to get app-level resources generated using source generators. They can be lazy loaded, but this will keep it strongly typed.

@StephaneDelcroix is this even something that is doable?

**Comment by StephaneDelcroix** [comment]
it's very easy to get the convenience you're looking for using an extension method in your own app, but that's something that's not general enough to implement in the SDK
