### ISSUE TITLE
When using Frame to wrap CollectionView, the bound data is not displayed under certain operations.

### ISSUE THREAD

**Issue by BaY1251** [dotnet/maui#14059]
Original Title: 当使用Frame包裹CollectionView时,特定操作下绑定数据不显示

### Description

我尝试使用MVVM绑定数据,在使用CollectionView展示数据时,发现如果被Frame包裹,CollectionView表现会在特定条件下异常.按如下步骤操作,会发现绑定数据无法刷新.

### Steps to Reproduce

1. 下载 https://github.com/BaY1251/MauiDebug.git
2. 打开/MVVM/TestAlignment.sln
3. 编译通过后启动应用
4. 点击"Binding"按钮,然后点击"Update"按钮.
会发现界面下方被Frame包裹的CollectionView所有数据都消失了.
而没有被Frame包裹的CollectionView是正常的

### Link to public reproduction project repository

https://github.com/BaY1251/MauiDebug.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

### Did you find any workaround?

删除Frame控件即可解决

**Comment by Ghostbird** [comment]
Can you try if it works when using a `Border` instead of a `Frame`? `Frame` is a control that only exists for compatibility reasons, but it is recommended to use a `Border` instead. I've had trouble with `Frame` controls too, which were solved when I replaced them with `Border`s.

References:

https://github.com/dotnet/docs-maui/issues/414
https://stackoverflow.com/questions/71738210/difference-between-net-maui-border-and-frame/71739057#71739057

**Comment by BaY1251** [comment]
> Can you try if it works when using a `Border` instead of a `Frame`? `Frame` is a control that only exists for compatibility reasons, but it is recommended to use a `Border` instead. I've had trouble with `Frame` controls too, which were solved when I replaced them with `Border`s.
> 
> References:
> 
> [dotnet/docs-maui#414](https://github.com/dotnet/docs-maui/issues/414) https://stackoverflow.com/questions/71738210/difference-between-net-maui-border-and-frame/71739057#71739057

谢谢, Border 无此问题. 由于迁移自Xamarin,故使用Frame
