### ISSUE TITLE
TextToSpeech

### ISSUE THREAD

**Issue by gogo1008** [dotnet/maui#14130]
### Description

https://learn.microsoft.com/dotnet/maui/platform-integration/device-media/text-to-speech?view=net-maui-7.0&tabs=android    Android greater than 11 (R API 30)  AndroidManifest.xml  How to configure

### Public API Changes

  TextToSpeech.Default.SpeakAsync("used text-to-speech");

### Intended Use-Case

  TextToSpeech.Default.SpeakAsync("used text-to-speech");

**Comment by Eilon** [comment]
Hi @gogo1008 , in your project there should be a file called `Platforms\Android\AndroidManifest.xml` that you need to edit to add the required setting.

The file should look like this: https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/Platforms/Android/AndroidManifest.xml

Does that answer your question? If not, can you please provide more details about what the issue is?

**Comment by gogo1008** [comment]
@Eilon 
1. Test the use of text to speech under Android

2. Problem: When the API is greater than 30, the development environment execution code is stuck, such as: TextToSpeech. Default. SpeakAsync ("hello");

3. Problem: When the API is less than 30, it is released as APK. After the real machine is installed, the flash screen exits

4. Current environment:
![image](https://user-images.githubusercontent.com/36293698/227121774-7f4c4d8a-beff-4dfd-a098-cf4cc9b77eb0.png)

5. Case code: TextToSpeech. Default. SpeakAsync ("hello");
![image](https://user-images.githubusercontent.com/36293698/227121870-d9e0ef62-b472-4a8e-87b5-3ef752687aa2.png)

6、dotnet sdk 7.0.201
![image](https://user-images.githubusercontent.com/36293698/227122181-c58da1dc-ba04-4c7a-963f-3089db3ccbd1.png)
