### ISSUE TITLE
Wrong DisplayName and EnglishName in CultureInfo on iOS

### ISSUE THREAD

**Issue by Sebastian1989101** [dotnet/maui#14148]
As the title already says, in the CultureInfo instance for "en", "de", "fr", "es", ... is the DisplayName and EnglishName not set properly. 

<img width="584" alt="Bildschirm­foto 2023-03-22 um 23 14 11" src="https://user-images.githubusercontent.com/25636075/227050738-bb8c35a2-febf-4326-9ac8-403957e30084.png">

**Comment by jfversluis** [comment]
I don't think this is a .NET MAUI problem, it probably is in the runtime. Maybe (somewhat) related: https://github.com/dotnet/runtime/issues/70028

**Comment by Sebastian1989101** [comment]
> I don't think this is a .NET MAUI problem, it probably is in the runtime. Maybe (somewhat) related: [dotnet/runtime#70028](https://github.com/dotnet/runtime/issues/70028).
> 
> Please add your findings to that and or open an issue with them. You could verify by creating a iOS project without .NET MAUI (use `dotnet new ios`) and inspect the same code. I'm pretty confident that it will have the same issue. Could you verify that?
> 
> Additionally please use the issue template we have in place next time. Thanks!

I do not have this issue when building a older app with Xamarin.Forms on iOS. So I think it is just one more for the pile of bugs called MAUI.

**Comment by drasticactions** [comment]
I got bit by this issue and saw this bug.

> I do not have this issue when building a older app with Xamarin.Forms on iOS. So I think it is just one more for the pile of bugs called MAUI.

This is, 100%, a runtime issue, https://github.com/dotnet/runtime/issues/70028

It works for you in Xamarin.Forms because that's running on Mono. The code in the newer .NET runtimes is, apparently, linking out some of this data used for region info, and stripped out the names. This has no relationship to the MAUI UI project. If you built a .NET iOS or Catalyst app without MAUI UI code, the same thing would happen (as I'm doing right now, hence why I saw it.)
