### ISSUE TITLE
unexpected platformView for grid layout

### ISSUE THREAD

**Issue by pitMobile** [dotnet/maui#14144]
### Description

When using a behavior, I noticed that for grid layouts, the platformView does not match what would be expected. Instead of 
Windows.UI.Xaml.Controls.Grid it is Microsoft.Maui.Platform.LayoutPanel (inherits from Microsoft.UI.Xaml.Controls.Panel). As a result, numerous options for visual and functional customization are not available. For examples settings for borders and corners. 

### Steps to Reproduce

Create a grid layout and assign it its own behavior for Windows. The platformView in the OnAttachedTo method is then of the wrong type.

**Expected:** Windows.UI.Xaml.Controls.Grid 
**Actual:** Microsoft.Maui.Platform.LayoutPanel 

### Link to public reproduction project repository

none

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

**Comment by hartez** [comment]
@pitMobile Why do you think this is a bug?

**Comment by pitMobile** [comment]
When I create a grid in MAUI, I would have expected a grid on the opposite side as well. Unfortunately, since I could not read anything else in the documentation, I assumed that this is a bug. 

However, there may be reasons for the current behavior, which makes it a feature rather than a bug. That would be interesting to know then. :-)

If the current behavior should be really so desired, this would become a feature request after which if possible all functionalities of a Grid should be taken over to the LayoutPanel.

But then the question would still remain, how can you currently define a border and rounded corners for a grid on Windows? On iOS and Android, this is possible with a Behavior.

**Comment by hartez** [comment]
The functionality of a MAUI Grid may not map one-to-one with a Windows Grid; while they perform a similar function, they are not the same control. And the use of LayoutPanel is intentional - it is capable of supporting the features we need for supporting cross-platform layouts when running MAUI code on Windows. 

> But then the question would still remain, how can you currently define a border and rounded corners for a grid on Windows? On iOS and Android, this is possible with a Behavior.

I would suggest using a Border control: https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/border?view=net-maui-7.0

You can also achieve this with a behavior and custom code on Windows, but using the cross-platform Border is easier.
