### ISSUE TITLE
OnNavigatedTo and OnAppearing not being called

### ISSUE THREAD

**Issue by williambuchanan2** [dotnet/maui#14284]
### Description

In the view, I override OnNavigatedTo and OnAppearing but they do not get called.

This seems to be related to the pages being in an AppShell tab.

See demo app from repository below for example.

### Steps to Reproduce

Run demo app from repo below.
Click OnNavigatedTo Problem.
On bottom right corner tap 'NavIssue'.
Select either of the 3 tabs - notice nothing happens.
But look in the code - an alert should be displaying when you navigate to the views.

### Link to public reproduction project repository

https://github.com/williambuchanan2/MauiNavigation

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 - 13, iOS 16

### Did you find any workaround?

No. Some advice would be good because i'm stuck!

**Comment by drasticactions** [comment]
@williambuchanan2 Is this issue unique to MAUI? Does it work correctly in Forms, or does it do the same behavior?

**Comment by williambuchanan2** [comment]
> @williambuchanan2 Is this issue unique to MAUI? Does it work correctly in Forms, or does it do the same behavior?

I think it is unique to the use of AppShell. Not sure AppShell is something I would use in Forms, but then I am fairly new to this so might be wrong...

**Comment by williambuchanan2** [comment]
It looks like Appearing might be working now... NavigatedTo still not working though.

**Comment by williambuchanan2** [comment]
I stand corrected. It's still not working. Seems to be something that is intermittent. It is working on some pages where it wasn't working before, but now it doesn't work on other pages.

**Comment by shadowfoxish** [comment]
I don't think tabs get those events when simply switching, because they're not whole pages/being displayed. 

The OnAppearing and OnNavigatedTo events do fire reliably for me, but only if you switch from one shell content item to the NavIssue one. Not individual tabs within NavIssue. I suspect this is because they're all kind of shown at once and not individually activated. 

![image](https://user-images.githubusercontent.com/12143535/234393295-f448f27a-da08-4909-a74b-310e3d9cfcb6.png)

The Maui team can comment, but I suspect this is by-design.

**Comment by williambuchanan2** [comment]
> I don't think tabs get those events when simply switching, because they're not whole pages/being displayed.


I guess that could be the case. The issue is these are important events because this is generally when you would trigger the loading/refreshing of data on these pages, so without these events how can we do that? If there is another way of doing that then the problem isn't such a big deal...

**Comment by shadowfoxish** [comment]
Conceptually, at least for me, tabs used like this would be one ViewModel with different sectional views (each tab, displaying some subset of the same viewmodel data). Not 3 distinct pages with separate VMs. 

I've been using an intermediate layer inside my view models which has a longer-lived, shared-instance object that gets passed around between different views. I use it for caching, so I dont have to always make server requests every time. Since you do get OnAppearing once (just not one for each tab), if you share a view model object (or a service), maybe you can use that event to trigger a refresh/load on your model?

**Comment by williambuchanan2** [comment]
> Conceptually, at least for me, tabs used like this would be one ViewModel with different sectional views (each tab, displaying some subset of the same viewmodel data). Not 3 distinct pages with separate VMs.
> 

Thanks for the tip. I guess that could be a workaround for now. I don't like the idea of not knowing when the user goes to these tabs due to the risk of the data being stale but this is better than nothing.

A the end of the day, these pages are just pages the same as all the rest, so I would expect them to behave in a consistent manner.

**Comment by mnidhk** [comment]
Just started with MAUI on iOS. When i take the template and place  "OnAppearing" on the main-page, app to background, app to foreground, function "OnAppearing" is not called! In my apps with xamarin forms it does work. Use it on all my pages. Why is this basic and important functionality not in MAUI?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on android platform with sample project. 
[MauiNavigation-main.zip](https://github.com/dotnet/maui/files/11765148/MauiNavigation-main.zip)
![14284](https://github.com/dotnet/maui/assets/77434865/6e7c5d90-568b-4cf6-997e-3789a33b220e)

**Comment by pzimmermaninmo** [comment]
@Zhanglirong-Winnie I'm confused, you added the "try latest version tag" but still said this bug still is reproducible on ios?  If it is fixed, what version of maui are we supposed to be using?
