### ISSUE TITLE
MAUI WebView does not execute JS chart lib function on Mac

### ISSUE THREAD

**Issue by linkaiyu** [dotnet/maui#14394]
### Description

in a MAUI app, the WebView points to a customer URL where a html file contains the JS lib for displaying chart.
this chart displays and the tools for the chart such as draw a line/arrow/heart etc works properly when the runs on windows, but the chart tools don't work on Mac

### Steps to Reproduce

1. down load the repro app, build and run.
2. after the app start, when you see the hour glass in the middle of the screen where the WebView control is, Click the button "Execute JS in WebView"
3. on windows, the stock price chart for AAPL will display and you can use the tools menu such as draw line/arrow/heart, change chart format to candle/line/ etc. 
4. run the app on Mac, and observe the chart tools behavior. they just don't work
5. in the code behind .cs file, there is comment and JS code that can be directly executed in the Developers Tools console to demonstrate that the chart JS lib works in Safari, so as to rule out the problem with JS lib.

### Link to public reproduction project repository

https://github.com/linkaiyu/Maui-WebViewTest

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

maccatalyst 12 and up

### Did you find any workaround?

no workaround

### Relevant log output

```shell
no
```

**Comment by drasticactions** [comment]
I created a [.NET Catalyst app with a WKWebView](https://github.com/drasticactions/MauiRepros/tree/main/WebviewTest) and set it to use the site and Javascript you listed, and the chart loaded.

<img width="1049" alt="スクリーンショット 2023-04-05 15 51 58" src="https://user-images.githubusercontent.com/898335/230003371-7e55ef57-fe22-491a-9a6e-3840566e3710.png">

I then ran your sample and got the same result, is this correct?

**Comment by drasticactions** [comment]
I tried the draw commands, and they did not work. But they don't work in my [Mac Catalyst](https://github.com/drasticactions/MauiRepros/tree/main/WebviewTest) example as well. It appears your issue is with the underlying WKWebKit control.

**Comment by fidofitzy** [comment]
@drasticactions when you tried drawing, were you just clicking the menu item, or did you click inside the chart body? Drawing tools usually work by one click in the chart body then moving mouse to another position and clicking again- I can't tell from watching the video above/


https://user-images.githubusercontent.com/97212366/230142913-a8a47d04-a721-437b-8f91-eeedb8c31c71.mp4

**Comment by linkaiyu** [comment]
@drasticactions, reviewing your video, yes, your observations are correct. 
I went thru your WebViewTest that uses the UIKit to create the WKWebView. If you observe the same behavior, then it does look like the issue is with underlying WKWebKit.
So what would be the next steps from here? Since the chart lib works from Safari, what is the difference here? Does Safari use WKWebKit? (excuse my ignorance on Mac/iOS etc)

**Comment by drasticactions** [comment]
@linkaiyu I'm not sure yet.

I wrote a test in Swift (https://github.com/drasticactions/MauiRepros/tree/main/WebViewChartTest) to make sure this was, for sure, a root Mac Catalyst issue and I can reproduce it there: It works on iOS on the iPhone and iPad, but fails in Catalyst. Moreover, I tried it on [macOS in AppKit](https://github.com/drasticactions/MauiRepros/tree/main/MacOSWebviewTest) (The macOS-only UI Platform, Mac Catalyst is based on UIKit and used by MAUI for the base of its stack for Mac), which also includes WKWebView. Frustratingly, your code works in AppKit WKWebView just fine, I could click and draw elements, and it appears to work fine.

Even more frustrating, while there are Developer Tools you can hook into the underlying webview and let you debug it from Safari, I need help getting them to run in Catalyst. They work in iOS and MacOS AppKit, but Mac Catalyst refuses to work. However, I don't think anything is boken in your code. Looking at the behavior in AppKit and Catalyst, I think whatever is being used to track mouse movements isn't working correctly in the Catalyst version, and since it works on iOS and AppKit, it's _seems_ like a Catalyst-specific bug. There may be something you could do to work around it in your code (Granted, not having the Safari Developer Tools, which also seems like a bug in Catalyst, makes that hard to do when it works everywhere else). This feels like something we need to go to Apple to help debug and fix. 

@Eilon What do you think?

**Comment by fidofitzy** [comment]
@prerakpatel2

**Comment by linkaiyu** [comment]
@drasticactions , I think you are right on spot with our observations. Fidelity customizes the chartiq lib and they may hit a spot that does not work. Comparing with the chartiq demo, the chart works on MacCatalyst. I updated the repro with the webview that points to https://demo.chartiq.com so that you can see the two chart behavior side by side now

**Comment by linkaiyu** [comment]
@drasticactions, @mikeparker104, @Eilon, 
Customer is investigating their implementation of chart JS code. MS can pause work until we hear back from customer.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Can repro on macOS with sample project. [Maui-WebViewTest](https://github.com/linkaiyu/Maui-WebViewTest)

**Comment by hartez** [comment]
> @drasticactions, @mikeparker104, @Eilon, Customer is investigating their implementation of chart JS code. MS can pause work until we hear back from customer.

@linkaiyu Any updates on this? Is there anything more we can do to help?
