### ISSUE TITLE
VS 2022 Maui is does not give the option for the GoogleServiceJson build action

### ISSUE THREAD

**Issue by philm001** [dotnet/maui#14486]
### Description

I downloaded the following nuget packages:

Firebase.common
Firebase.Messaging
GoogleplayServices.Base
GoogleplayServices.Basement
GoogleplayServices.Tasks

I have restarted VS 2022 multiple times. When I import the google-services.json file under the Android platform folder and when I go to Properties->Build Action. There is no option for GoogleServicesJson.

### Steps to Reproduce

See above

### Link to public reproduction project repository

n/a

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

Latest version of Android

### Did you find any workaround?

A workaround has been discovered:

See this link here:

https://developercommunity.visualstudio.com/t/googleservicesjson-build-action-is-not-available/294192?viewtype=solutions

Here is the description of the work around:

Unfortunately, sometimes including the Xamarin.GooglePlayservices.Basement Nuget Package, cleaning, and restarting Visual Studio doesn't result in the necessary update to the projects csproj file. In this case its easiest to update the csproj file manually in a text editor (obviously after having tried the above!):

<Import Project="..\..\YOUR_PROJECT_PATH\packages\Xamarin.GooglePlayServices.Basement.60.1142.1\build\MonoAndroid80\Xamarin.GooglePlayServices.Basement.targets" Condition="Exists('..\..\YOUR_PROJECT_PATH\packages\Xamarin.GooglePlayServices.Basement.60.1142.1\build\MonoAndroid80\Xamarin.GooglePlayServices.Basement.targets')" />

replacing "YOUR_PROJECT_PATH\packages\Xamarin.GooglePlayServices.Basement.60.1142.1\build\MonoAndroid80" with the correct relative path to the location of the package within your solution. Take a look at other import statements in csproj to get an idea of the correct relative path and verify the location with File Explorer (in case the dlls are stored under a different project in your solution).

Note that this comment is from 2019. So the version numbers will be higher. But the idea is the same. In the project file, you need to manually point to the targets file that is inside of the Xamarin.GooglePlayServices.Basement package in order to get this to work.

**Comment by jonpryor** [comment]
@philm001: you mention that you "downloaded" `GoogleplayServices.Basement` and other packages.  What does "downloaded" mean here?  Used "Manage NuGet Packages…" within Visual Studio, resulting in a `<PackageReference/>` within the `.csproj`?  What `<PackageReference/>`s does your `.csproj` have?

Part of the problem may be that [`nuget.org` has *three* "GoogleplayServices.Basement" packages](https://www.nuget.org/packages?q=GoogleplayServices.Basement):

  * [GooglePlayServices.Basement](https://www.nuget.org/packages/GooglePlayServices.Basement), published by [Vinayaka-Hebbar](https://www.nuget.org/profiles/Vinayaka-Hebbar) and last updated in *2019*.
  * [Xamarin.GooglePlayServices.Basement](https://www.nuget.org/packages/Xamarin.GooglePlayServices.Basement), published by [Microsoft](https://www.nuget.org/profiles/Microsoft) [Xamarin](https://www.nuget.org/profiles/Xamarin), and last updated in January 2023.
  * [Crosslight.Xamarin.GooglePlayServices.Basement](https://www.nuget.org/packages/Crosslight.Xamarin.GooglePlayServices.Basement), published by [intersoftsolutions](https://www.nuget.org/profiles/intersoftsolutions), and last updated in *2018*.

*Which* of these packages did you add?

The one you *need* to add is [Xamarin.GooglePlayServices.Basement](https://www.nuget.org/packages/Xamarin.GooglePlayServices.Basement), which [contains](https://nuget.info/packages/Xamarin.GooglePlayServices.Basement/118.1.0.2) a `build/net6.0-android31.0/Xamarin.GooglePlayServices.Basement.targets`, which in turn contains:

```xml
<ItemGroup>
  <AvailableItemName Include="GoogleServicesJson" />
</ItemGroup>
```

which is what Visual Studio uses to populate the **Build action** options.

When I use Visual Studio 17.5.4, create a new .NET Android project, and add the `Xamarin.GooglePlayServices.Basement` NuGet package, I then see the `GoogleServicesJson` build action within the File Properties panel.  (This appeared to require reloading the project for a Classic Xamarin.Android app, but a .NET Android project did not require reloading.  This *may* be because I created the Xamarin.Android project first and reloaded the solution while trying to repro this.)

**Comment by juniorsaraviao** [comment]
I continue seeing this issue targeting `net7.0-android33.0` and GoogleServicesJson doesn't appear.
If I target net7.0-android or net6.0-android, the GoogleServicesJson appears.

**Comment by bryansjenks** [comment]
Targeting `net7.0-android33.0`, I have the issue as well.

I'm adding `Shiny.Push.AzureNotificationHubs` to get ` Xamarin.GooglePlayServices.Basement` (probably there were other ways to do this - maybe I could even have added ` Xamarin.GooglePlayServices.Basement` directly).
I had to add the `google-services.json` file to the project, then manually edit the `.csproj` file to add
```
<ItemGroup>
    <GoogleServicesJson Include="google-services.json" />
</ItemGroup>
```
and it does seem to be initializing play services now, but neither the `GoogleServiceJson` build action, nor the `google-services.json` file shows up in my solution at this point. (all that matters is that it's working though)

**Comment by nysand** [comment]
I had the same problem and had to delete my project clone it again install Xamarin.GooglePlayServices.Base and then I was able to see the GoogleServiceJson build action. Working with VS22 17.4.7

**Comment by philm001** [comment]
@bryansjenks 

I actually got mine to work somehow. I forgot what I did but just want to confirm that adding that specific item group, everything is working for you now?

**Comment by jfversluis** [comment]
Even though you might not see it in Visual Studio, if you install the `Xamarin.GooglePlayServices.Basement` package (through Shiny or not) it will be there and you can manually add that through your csproj. As indicated before, this is ultimately seemingly a tooling issue. If you want to have that resolved, please report it through the process outlined above.  Thanks!
