### ISSUE TITLE
Unable to show images in a collection view due to layout issues

### ISSUE THREAD

**Issue by williambuchanan2** [dotnet/maui#14606]
### Description

Created a view which has a scrollable list of images and text. Due to the various layout issues in iOS I am unable to get the page to display properly.

The images don't resize - in fact they get cut off, and then I have a big blank white space between all the images.

Same page on Android vs iOS:

Android:

![image](https://user-images.githubusercontent.com/32165641/232355612-f7c7827a-be67-4d3d-9cb9-881eaaae8b20.png)

iOS:

![image](https://user-images.githubusercontent.com/32165641/232355677-ec103bb3-162f-4e20-a102-12fe33d0f564.png)

Notice how image pointed to by arrow is chopped off, and there is the big white space below it in the red square. There are also a whole bunch of other issues with iOS layout which is making it impossible to have a release ready product.

### Steps to Reproduce

Open the solution in the repository below.
Click the 'Image Error' button.
View should load - scroll down to see the problem.

### Link to public reproduction project repository

https://github.com/williambuchanan2/MauiNavigation

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

No

**Comment by xtuzy** [comment]
Your layout have many problem, 

1. not use ~AndExpand, because it is Obsolete, see [api](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.layoutoptions.centerandexpand?view=net-maui-7.0), it will mislead you
2. do you want expand all image in [CollectionView](https://github.com/williambuchanan2/MauiNavigation/blob/c55f108333b6f0e46dba5e2198c2f40c87034691/Views/ImageError.xaml#L121) ? if not, not let vertical CollectionView in vertical StackLayout if you don't set a fixed w/h for CollectionView, because it will expand all content in CollectionView, if you have 1000 item in CollectionView, it will expand all.
3. if your height of items of CollectionView is not same, maybe you need use ItemSizingStrategy="MeasureAllItems"

i don't know how to fix, it is strange

https://user-images.githubusercontent.com/17793881/233314809-ae3c9925-ab83-4f7c-bf79-30854b821ee4.mp4

**Comment by williambuchanan2** [comment]
Hi. 

1. Noted on ~AndExpand. I assumed since it was still a valid option that it did something, but I had noticed it was inconsistent.

2. My aim is to make it look the same on iOS as it does in Android (as per the android screenshot above). The only reason I set a width and height is because without it the result is even worse - the images just seem to get a random size. 

3. I just tried ItemSizingStrategy="MeasureAllItems". Didn't make any difference.

When you said "Your layout have many problem" - do you mean there are problems with the XAML I wrote, or do you mean the end result has many problems?

Thanks

**Comment by xtuzy** [comment]
I don't know why i can't run your app use android emulator, so i don't how it work.
![sharex-20230420142753](https://user-images.githubusercontent.com/17793881/233322400-bd55c62d-957d-43bc-9c46-2686979f8ae5.png)
your images can scroll vertical?

**Comment by williambuchanan2** [comment]
This is how it looks in Android:

https://j.gifs.com/LZVoKA.gif

**Comment by Xyncgas** [comment]
it's weird how things worked in one platform but not another, for a platform that meant to be unified it sends a mixed signal as if sticking a knife to usrrs' back to have them implement platform sepecific changes. Therefore imo an appropriate alternative solution is to drop in a webview whenever things are not working the way expected to speed up progress

**Comment by williambuchanan2** [comment]
> an appropriate alternative solution is to drop in a webview whenever things are not working the way expected to speed up progress

It may well come to that!

**Comment by jknaudt21** [comment]
Linked to: #16120
