### ISSUE TITLE
MAUI Blazor Project Publish Bug

### ISSUE THREAD

**Issue by RiuHDuo** [dotnet/maui#14732]
### Description

If remove net7.0-ios and net7.0-android from TargetFrameworks Tag in csproj file.
Publish windows package will get an error. 
MSB4057 The target "_GenerateAppxPackage" does not exist in the project.

### Steps to Reproduce

1. Create A New Maui Blazor Project with vs 2022
2. Open csproj file
3. Remove both net7.0-ios and net7.0-android from TargetFrameworks Tag
4. Click Publish.

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

7.0 (current)

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

Any Version

### Relevant log output

```shell
MSB4057 The target "_GenerateAppxPackage" does not exist in the project.
```

**Comment by bainn** [comment]
I am having the same problem here.  I have only one platform though, that is Windows only.

**Comment by bainn** [comment]
I have tried already Windows and maccatalyst only and it didn't work. The create new Profile doesn't show up too. Surprisingly, this happened after the update to version 17.6.3. Because I have already published an app with only Windows platform and it worked in the previous version.  Now, I have done the full compliments, with all the platforms there and it worked. So, what got broken in version 17.6.3? Please give us the ability to publish only windows. I know you will fix it. Thank you very much indeed.

**Comment by b-f-** [comment]
> I have tried already Windows and maccatalyst only and it didn't work. The create new Profile doesn't show up too. Surprisingly, this happened after the update to version 17.6.3. Because I have already published an app with only Windows platform and it worked in the previous version. Now, I have done the full compliments, with all the platforms there and it worked. So, what got broken in version 17.6.3? Please give us the ability to publish only windows. I know you will fix it. Thank you very much indeed.

[This](https://johnnys.news/2023/04/Windows-Publishing-with-NET-MAUI) should work as a workaround.
`dotnet publish -f net7.0-windows10.0.19041.0 -c Release`
