### ISSUE TITLE
Release build doesn't deploy on iOS/iPhone emulator

### ISSUE THREAD

**Issue by fischberg** [dotnet/maui#14979]
### Description

In Visual Studio, when I select Release build and an iPhone emulator, the application builds but fails to deploy to the emulator. Deployment to a physical device works.

### Steps to Reproduce

Try creating a Release build of any MAUI app and deploying it to an iPhone emulator. I receive the error message

`
"Can not execute ...Release/net7.0-ios/iossimulator-x64/MyProjectName.exe. The selected execution mode is not supported for .NET projects."
`

### Link to public reproduction project repository

https://github.com/fischberg/CollectionViewRepro

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

None. I have to use a physical device to test a release build.

**Comment by Kapusch** [comment]
I have the same issue, and I think it's specific to every other configuration than the "Debug" one.

**Comment by Kapusch** [comment]
Actually, there are many tickets about this error:

- #8894
- #11368
- #12231
- #12225
- #12226

It really sounds like a VS Mac issue, for which I can see several tickets that are considered as closed...
- https://developercommunity.visualstudio.com/t/Error---selected-execution-mode-not-supp/10098896
- https://developercommunity.visualstudio.com/t/Building-in-Release-mode-for-iOS-results/10235007

**Comment by Kapusch** [comment]
Hello @fischberg , apparently this is a known bug, and the workaround for this is simple.
In a Release configuration, you can run the app by clicking on "Start Without Debugging" under the "Debug" menu tab:
<img width="238" alt="image" src="https://github.com/dotnet/maui/assets/9576733/d1383937-2cde-4aaf-a7b2-8b4dcade6665">

The reason why it doesn't work when using the play button is because it runs in debug mode.
However, debugging is NOT supported in Release configuration!

I have open a ticket for Visual Studio [here](https://developercommunity.visualstudio.com/t/The-selected-execution-mode-is-not-suppo/10358767).

**Comment by samhouts** [comment]
Thank you for the report! I see that there is a relevant VS feedback ticket for this issue. As this is ourside the scope of the .NET MAUI SDK product, I will close this in favor of [that ticket](https://developercommunity.visualstudio.com/t/The-selected-execution-mode-is-not-suppo/10358767). Please follow up on the feedback ticket for further assistance.

**Comment by Kapusch** [comment]
If it helps, I have detailed [a complete example on my blog](https://www.mauicestclair.fr/en/posts/tips/multi-environments-project-configuration/).
