### ISSUE TITLE
Views always returning -1 as Width

### ISSUE THREAD

**Issue by banditoth** [dotnet/maui#15046]
### Description

Seems like Views are always retuning -1 as Width when you don't specify any exact width.
Works on MacOS catalyst, but not in iOS simulator. 

### Steps to Reproduce

On video:
https://youtu.be/UPzfEImXrhE

### Link to public reproduction project repository

https://github.com/banditoth/mauibug_measurement

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 16

**Comment by mattleibow** [comment]
I think this may be because you are listening to the OnSizeAllocated method on the PAGE, and this does not guarantee that the contents is ready. It is just when the page has a size - and this may be before/during the contents sizing. This may also be different on different platforms depending on how the OS does things.

Maybe you could do the same thing based on the `SizeChanged` event on the box view?

**Comment by banditoth** [comment]
> I think this may be because you are listening to the OnSizeAllocated method on the PAGE, and this does not guarantee that the contents is ready. It is just when the page has a size - and this may be before/during the contents sizing. This may also be different on different platforms depending on how the OS does things.
> 
> Maybe you could do the same thing based on the `SizeChanged` event on the box view?

Hey @mattleibow  thanks for the hint. The SizeChanged does the trick pretty well.
My bad.
