### ISSUE TITLE
.NET MAUI App template not showing

### ISSUE THREAD

**Issue by omerkaraoglu** [dotnet/maui#15094]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

There is no MAUI option on the project types drop-down, and nothing could be found when I searched explicitly from the search bar.

**Comment by Eilon** [comment]
Hi @omerkaraoglu , can you launch the Visual Studio Installer and confirm that you have the `.NET Multi-platform App UI development` workload checked?

<img width="636" alt="image" src="https://github.com/dotnet/maui/assets/202643/1e2c7e38-4929-4795-b80f-dc79864c3320">

**Comment by omerkaraoglu** [comment]
> Hi @omerkaraoglu , can you launch the Visual Studio Installer and confirm that you have the `.NET Multi-platform App UI development` workload checked?
> 
> <img alt="image" width="636" src="https://user-images.githubusercontent.com/202643/238486393-1e2c7e38-4929-4795-b80f-dc79864c3320.png">

Yes I did that and checked twice before posting this issue.

**Comment by Eilon** [comment]
@omerkaraoglu alright thank you for checking. Can you open a command prompt window and run `dotnet workload list` to see what it lists?

**Comment by dvlpme** [comment]
Having the same issue, was working before 17.6.x, collogue has same issue on 17.5.5 

- Uninstalled VS2022 & .NET than reinstalled without success 
- Have .NET 6.0.16, 7.0.5 and 8.0.100 preview3 installed
- Multi platform workload installed, verified Maui is installed
- Ran manual install from Package manager, successfully completed but no templates added

Existing Maui projects load and build but I can't create a new one due to the missing templates.  


Installed Workload Id      Manifest Version                            Installation Source  
--------------------------------------------------------------------------------------------
tizen                      7.0.108/8.0.100-preview.4                   SDK 8.0.100-preview.4
maui-windows               8.0.0-preview.3.8149/8.0.100-preview.3      VS 17.6.33723.286    
maui-maccatalyst           8.0.0-preview.3.8149/8.0.100-preview.3      VS 17.6.33723.286    
maccatalyst                16.2.462-net8-p3/8.0.100-preview.3          VS 17.6.33723.286    
maui-ios                   8.0.0-preview.3.8149/8.0.100-preview.3      VS 17.6.33723.286    
ios                        16.2.462-net8-p3/8.0.100-preview.3          VS 17.6.33723.286    
maui-android               8.0.0-preview.3.8149/8.0.100-preview.3      VS 17.6.33723.286    
android                    34.0.0-preview.3.224/8.0.100-preview.3      VS 17.6.33723.286 


![image](https://github.com/dotnet/maui/assets/135060684/35b46fdb-352c-4f68-89a4-fdeb5581e31f)

![image](https://github.com/dotnet/maui/assets/135060684/684e7b92-6c6e-48a8-8f4f-440b6a1ffe5f)

**Comment by omerkaraoglu** [comment]
> @omerkaraoglu alright thank you for checking. Can you open a command prompt window and run `dotnet workload list` to see what it lists?

C:\Users\user>dotnet workload list
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'workload' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

**Comment by jfversluis** [comment]
Looks like there is something not right with the dotnet installation or workloads then if it can't find that command. It's a bit hard to diagnose remotely without going back and forth a lot 😅  I suspect you might have installed both .NET MAUI through the command-line as well as Visual Studio and now things are confused.

There is [this gist](https://gist.github.com/jonathanpeppers/63beb491a9185ac06710261536cc35c9) which describes steps to untangle it. But it's some work and assumes you know some things in this regard. So it might get you even in further trouble. Use at your own risk.

If you have the possibility, it might be better to just start clean. Wipe your machine and install Visual Studio with .NET MAUI checked (from the UI) and it should be all good from there. Or maybe setup a virtual machine to do that?

This issue is a bit older, so I hope you have something figured out by now. Therefore, I will close this for now. If you still have issues feel free to open something new. Or maybe use the Discussions tab or Stack Overflow which might be better suited for these types of things.

Thanks!
