### ISSUE TITLE
Problem With MAUI and Angular in Visual 22

### ISSUE THREAD

**Issue by kingsalah94** [dotnet/maui#15097]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
So the that I encountered is : i cant see as an option of language in the visual studio 22 after installed th .NET MAUI as worked Charged
and now I have create an ASP and ANgular whitch isn;t working

**Comment by Eilon** [comment]
Hi @kingsalah94 , can you please share more details on exactly what isn't working? Did you get any errors? You can add screenshots or other info to this issue so that we can try to help resolve the issue.

**Comment by kingsalah94** [comment]
![Capture d’écran 2023-05-16 232205](https://github.com/dotnet/maui/assets/99025273/1ddccd6c-65e3-4fcd-b0aa-17696d137b89)
this is the Angular project that i've just created and no thing is done,
the MAUI problem
![Capture d’écran 2023-05-16 232746](https://github.com/dotnet/maui/assets/99025273/ff419d54-7acf-478d-bd23-430d8ffa4190)

https://github.com/dotnet/maui/assets/99025273/0aec3b61-3fd7-4834-9622-20a914e45e4b

**Comment by jfversluis** [comment]
If I understand correctly you're missing the templates in Visual Studio.

In your video I did see the Mobile category. They are not under there? Or when you search for MAUI? If they are missing you are able to install them manually by opening a command-line window and use this command: `dotnet new install Microsoft.Maui.Templates`. That should also make them show up in Visual Studio.

I see this issue is from a while ago, so I hope you are well underway in your .NET MAUI journey by now. If there is anything else we can do for you, feel free to open a new issue. Thanks!
