### ISSUE TITLE
How  to  destroy the webview or  BlazorWebView on a page

### ISSUE THREAD

**Issue by lkd3063601** [dotnet/maui#15125]
### Description

I want to destroy the webview or BlazorWebView on the page, but I don't know how to destroy it

### Public API Changes

none

### Intended Use-Case

none

**Comment by Eilon** [comment]
@lkd3063601 can you share more details about what you're trying to achieve, what you've tried, and where the problem(s) are? In general there's no need to directly dispose things because they will simply be garbage collected once they are no longer used. But if you have a case where that is not enough, please let us know.
