### ISSUE TITLE
Scroll does not work on Mac (Mac Catalyst)

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#15310]
### Description

I have a page with lots of content inside a scrollview. On MacOS the scrollview does not scroll. Hence majority of the content is not accessible.  The MacOS is Monterey. It's old Mac Book thus unable to test on latest MacOS Ventura.

### Steps to Reproduce

Run the repro project and try to scroll the page. 

### Link to public reproduction project repository

https://github.com/HobDev/MauiBugs/tree/MacOSScrollViewIssue

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Mac (Catalyst) mnacOS Monterey Version 12.6.6

**Comment by drasticactions** [comment]
https://github.com/dotnet/maui/assets/898335/28b6ca15-c399-44ac-ba1f-98b5a6bfe8a6

Running this on Ventura. As far as I can tell it's working?

Workload list:

```
macos                   13.3.7060/7.0.100      SDK 7.0.300
maui-android            7.0.86/7.0.100         SDK 7.0.300
ios                     16.4.7060/7.0.100      SDK 7.0.300
maccatalyst             16.4.7060/7.0.100      SDK 7.0.300
maui                    7.0.86/7.0.100         SDK 7.0.300
tvos                    16.4.7060/7.0.100      SDK 7.0.300
android                 33.0.46/7.0.100        SDK 7.0.300
```

I don't have access to a Monterey Mac, so I can't test that, but I would be surprised if it worked only in Ventura. I'm not sure if it's your specific example of grids with Auto width and fixed widths/heights that is causing it? ScrollView itself seems fine, you should be able to see that in the default template since that's wrapped in a scroll view.
