### ISSUE TITLE
Adding UseMaui to .NET Android app hides emulators and devices

### ISSUE THREAD

**Issue by assurasc** [dotnet/maui#15388]
### Description

Adding `<UseMaui>True</UseMaui>` to a .NET Android project file causes any local devices and emulators to disappear.

I'm following the steps in [this article](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/native-embedding) to use native embedding but this bug prevents me from debugging on a local Android phone. I'm implementing barcode scanning so it has to be an actual device.

I tested in both Visual Studio 17.6 and 17.7 Preview.

### Steps to Reproduce

1. Create a new .NET Android App
2. Look at the start menu - local devices and emulators are listed
![image](https://github.com/dotnet/maui/assets/130938758/39a8b946-3e5b-46d3-a846-e2ed0b32fda3)
3. Open the project file
4. Add `<UseMaui>True</UseMaui>`
5. Save the changes and re-load the project
6. Look at the start menu - local devices and emulators are no longer listed
![image](https://github.com/dotnet/maui/assets/130938758/b41925c7-a608-4b43-8d21-230402e8e1d0)

### Link to public reproduction project repository

https://github.com/assurasc/UseMauiIssue.git

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 33

### Did you find any workaround?

No workaround found.

**Comment by drasticactions** [comment]
Unfortunately, the Visual Studio team handles the tooling you see, so it can not be fixed here. If you refile this with VSFeedback, the team there can fix it. The devices/emulators layout differs between MAUI and traditional .NET Android/iOS apps, so I guess there is a bug in their code with how it handles "UseMaui", with it assuming that you're building an MAUI App, rather than native embedding, so it shows the wrong menu.

Checking on VSMac, and it does work correctly there. To work around this on Windows, you could also deploy this from CLI but I'm not sure of the exact steps for how to do that with devices, @jonathanpeppers Do you know of any docs for that?
