### ISSUE TITLE
CollectionView with default VerticalOptions: Android does not scroll, iOS incomplete scroll

### ISSUE THREAD

**Issue by BigT-88** [dotnet/maui#15402]
### Description

This demo shows CollectionView with default (no value set) VerticalOptions:
Android does not scroll; iOS only partially scrolls; both platforms do not render controls defined in XAML below the CollectionView (see Label that should display below the CollectionView).

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-android                      7.0.86/7.0.100         SDK 7.0.300
ios                                    16.4.7060/7.0.100      SDK 7.0.300

### Steps to Reproduce

iOS:
1. Open BugCollectionViewScrollDemo.sln in Visual Studio for Mac 17.5.6.
2. Debug on iPhone 12 Pro Max (iOS 16.3.1).
3. Observe that CollectionView will not scroll and remain at the last item.

Android:
1. Open BugCollectionViewScrollDemo.sln in Visual Studio for Mac 17.5.6.
2. Debug on Samsung Galaxy S21 Ultra (Android 13).
3. Observe that CollectionView will not scroll.

### Link to public reproduction project repository

https://github.com/BigT-88/dnm-b5

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 16, Android 13

### Did you find any workaround?

Android:
Setting VerticalOptions to any of the following: CenterAndExpand, EndAndExpand, FillAndExpand & StartAndExpand.
iOS: Setting VerticalOptions to FillAndExpand.

**Comment by xtuzy** [comment]
you set CollectionView in StackLayout, try CollectionView need a fixed height

**Comment by jsuarezruiz** [comment]
@davidbritch Should we maybe include a note about this scenario in the docs?

**Comment by drasticactions** [comment]
> The CollectionView inside the VerticalStackLayout takes up all the necessary space. This has an impact on the behavior of the CollectionView as well as the number of items rendered.
> 
> @davidbritch Should we maybe include a note about this scenario in the docs?

Yeah, this is because of VerticalStackLayout, switching it to Grid and it works fine, https://github.com/drasticactions/MauiRepros/blob/main/dnm-b5-main/BugCollectionViewScrollDemo/BugCollectionViewScrollDemo/MainPage.xaml#L12

**Comment by jknaudt21** [comment]
An alternative workaround to this issue is put a MaximumHeightRequest to the CollectionView.

I suspect that what's happening is that the CollectionView tries to take the height of the container, which for the VerticalStackLayout may be infinite, and then determines that it doesn't need to scroll. I'll investigate further though

**Comment by jknaudt21** [comment]
Hello! So upon investigating further I see that his behavior is **by design**. A [StackLayout allows its content to be whatever height it wants](https://github.com/dotnet/maui/blob/main/src/Core/src/Layouts/VerticalStackLayoutManager.cs#L31).

In the case of a CollectionView inside a StackLayout, this means that the CollectionView will have the size of the entire collection without the need for a scrollbar. As noted in by other users, the workarounds for this are to: 

1. Use a `Grid` instead. Grids put height/width constraints to their children
2. Add specific height or maximumHeight request to the CollectionView inside the StackLayout.

**Comment by jknaudt21** [comment]
@davidbritch could this be clarified in the docs> Currently the tip reads 
> Placing a [CollectionView](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.collectionview) inside a [VerticalStackLayout](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.verticalstacklayout) can stop the [CollectionView](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.collectionview) scrolling, and can limit the number of items that are displayed. In this situation, replace the [VerticalStackLayout](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.verticalstacklayout) with a [Grid](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.grid).

It sounds as if this is unintended behavior, whereas I believe we could a bit clearer on stating that placing a CollectionView inside a StackLayout will let the CV grow as much as it needs, without scrolling. For those cases either the height should be limited or grid should be used.
