### ISSUE TITLE
CollectionView only measure first item on Windows

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#15468]
### Description

I want to set    `ItemSizingStrategy= ItemSizingStrategy.MeasureAllItems,` in CollectionView on Windows Platform. But it does not have any effect and only measure first item  when `ItemsLayout = new GridItemsLayout(ItemsLayoutOrientation.Horizontal)`. 

### Steps to Reproduce

Run the sampe repo. The items in CollectionView have different sizes. But  the items does not resize. All the items are of first item size only. 

### Link to public reproduction project repository

https://github.com/HobDev/MauiBugs/tree/CollectionViewMeasurementIssue

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Relevant log output

```shell
LinearItemsLayout don't have this bug. Also don't able to replicate this bug on GridItemsLayout with VerticalOrientation.
```

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 4.0. Repro on Windows 11 .NET8, not repro on Android 13.0-API33 and iOS 16.4 with below Project:
[MauiBugs.zip](https://github.com/dotnet/maui/files/12101616/MauiBugs.zip)

![image](https://github.com/dotnet/maui/assets/97647558/2dd09434-f0b7-42cb-94d5-bb7c11da1f2b)

**Comment by SamuelJames101** [comment]
I can reproduce this on Net8 RC1

**Comment by spencerdahl** [comment]
I'm having the same issue on .NET 8 RC 1.

**Comment by SamuelJames101** [comment]
Still an issue in RC2. When is this being fixed?

**Comment by malsabi** [comment]
Still the issue exists in RC2 latest, I have the items to be in a horizontal layout with span of 4. The first card height is changed but the others remain the same and some of the content is clipped due to the height is not being changed. Seems like the option is always MeasureFirstItem and its ignoring MeasureAllItems.

**Comment by SamuelJames101** [comment]
@HobDev  Can you still see this issue? I can't see this anymore on NET8 GA

**Comment by malsabi** [comment]
Is there any update on this issue? i'm still having this on the latest release 8.0.3

**Comment by deejcoder** [comment]
This still seems to happen on 8.0.4.
ItemSizingStrategy := MeasureAllItems
ItemsLayout := GridItemsLayout with Vertical Orientation, and any Span (even 1).
In my particular case this occurs when text wraps to a new line within a particular item.

There's also inconsistency on iOS where if one item is bigger, then the other item will be centred instead of matching the height of the other item in the same row.

Works perfectly on Android.

**Comment by deejcoder** [comment]
I was able to reproduce this on the latest version, 8.0.6. WinUI doesn't seem to respect "MeasureAllItems", rather all items are the same size as the first item.

The number of columns or orientation does not seem to change this behaviour. In my case, I have cards where text may wrap to a new line. When text wraps, but not on the first card, then it is cut off.
![image](https://github.com/dotnet/maui/assets/8052327/8e5e6f82-098b-4d2d-9f30-5fa00250da65)

**Comment by BaY1251** [comment]
+1,  repro on 8.0.60

**Comment by BaY1251** [comment]
Why close it?!
