### ISSUE TITLE
Wrong Time On Android Apps

### ISSUE THREAD

**Issue by musictopia2** [dotnet/maui#1560]
Here is a sample repository to demostrate the problem.
https://github.com/musictopia2/WrongTimeSample 

What happens is if I use the DateTime.Now, it always shows the UTC time no matter what I try to do.
That is wrong.  Needs to show the localtime.
Tried to use the .ToLocalTime but that did not work.
Even tried to use the .ToUniversalTime then the .ToLocalTime and that did not work either.
I would be disappointed if maui requires only UTC time if showing the time via an app.

**Comment by hartez** [comment]
What time zone is your test device set to?

**Comment by musictopia2** [comment]
The time zone was arizona time.  I know because the time was correct on the device if not using a program.  I tested on 3 devices and same issue.  The problem only started occuring when using maui.  When using old xamarin forms, the problem does not happen.

**Comment by yiszza** [comment]
I have the same problem.

**Comment by mattleibow** [comment]
I am unable to reproduce this. I am based in South Africa and have a timezone of +2. DateTime.Now is always the time of my devices. This may have been a bug in some part of the Android runtime as I know we had some issues with a few core components as we were putting the bits together for the first set of previews of .NET 6.

If this is still the issue, please re-open this issue with any more details that you can provide.

**Comment by Thomr77** [comment]
Hi,

We found an issue like this yesterday but on **iOS** with a **real iPhone** where the time-zone is UTC not local.
**Important:** this issue does not show on an iOS iPhone Simulator where the time-zone is correct!

Steps to reproduce:

+ Create a new Maui App (with Version 17.1.0 Preview 1.1).
+ Register the App with Apple so that it can get deployed to a real device - change [App].csproj ApplicationId etc.
+ Open 'MainPage.xaml' and change: <br>'Text="Hello, World!"' to 'x:Name="x_zone_time"'.
+ Open 'MainPage.xaml.cs' and add to end of 'public MainPage()':<br> 'x_zone_time.Text = TimeZoneInfo.Local.Id + " " + DateTime.Now.ToShortTimeString();'.
+ Compile/deploy to a real iOS device (via Mac) - the time-zone shows 'UTC' and the time is displayed in UTC-time not local-time.

Thanks!

**Comment by hartez** [comment]
@Thomr77 please open a separate issue for this, since it's on a different operating system.
