### ISSUE TITLE
When I Capture a photo the second time the camera does not open - IOS

### ISSUE THREAD

**Issue by mreugenevanrooyen** [dotnet/maui#15899]
Good day, I am still having the same issue as previously mentioned, I have now tested with the latest version - Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.7.0 Preview 2.0 
and the problem still persists.

https://user-images.githubusercontent.com/26383481/221207572-ae90c92c-0c0c-44af-8d09-f2e2546874ca.mp4

The issue has not been fixed in the latest version as per my screen recording.

_Originally posted by @mreugenevanrooyen in https://github.com/dotnet/maui/issues/13477#issuecomment-1443786140_

**Comment by mreugenevanrooyen** [comment]
Here is a link to the repro - https://github.com/mreugenevanrooyen/CapturePhotoTest1

**Comment by cucumber-sp** [comment]
Have you find any workaround? I have the same issue and it's critical for my app

**Comment by mreugenevanrooyen** [comment]
> Have you find any workaround? I have the same issue and it's critical for my app

I have not found a workaround, which is why I logged this issue, it is also very critical for my app.

**Comment by cucumber-sp** [comment]
Turned out, that popup caused the issue. Close() method worked as "Fire And Forget" as described here https://github.com/CommunityToolkit/Maui/issues/1222 So you call open camera when popup was still presented on the screen. Recently CloseAsync() method stuff was merged into main repository, so I just cloned CommunityToolkit, built it and added as reference. Then I replaced `myPopup.Close();
await MediaPicker.CapturePhotoAsync()` with `await myPopup.CloseAsync()
await MediaPicker.CapturePhotoAsync()` and it works now! I think this and other related issues can be closed because it was issue in CommunityToolkit and now there's workaround for this

**Comment by mreugenevanrooyen** [comment]
> Turned out, that popup caused the issue. Close() method worked as "Fire And Forget" as described here [CommunityToolkit/Maui#1222](https://github.com/CommunityToolkit/Maui/issues/1222) So you call open camera when popup was still presented on the screen. Recently CloseAsync() method stuff was merged into main repository, so I just cloned CommunityToolkit, built it and added as reference. Then I replaced `myPopup.Close(); await MediaPicker.CapturePhotoAsync()` with `await myPopup.CloseAsync() await MediaPicker.CapturePhotoAsync()` and it works now! I think this and other related issues can be closed because it was issue in CommunityToolkit and now there's workaround for this

Great find, will implement the workaround asap.
