### ISSUE TITLE
[Android] DeviceDisplay.Current.MainDisplayInfoChanged does not work when auto rotate is off

### ISSUE THREAD

**Issue by greg84** [dotnet/maui#15927]
### Description

On Android, when auto rotate is off, the MainDisplayInfoChanged event doesn't work - it is called seemingly randomly when screen orientation changes.

### Steps to Reproduce

Add this code to a page in the constructor:

```
DeviceDisplay.Current.MainDisplayInfoChanged += (sender, args) =>
{
    System.Diagnostics.Debug.WriteLine(args.DisplayInfo.Orientation);
};
```

Run the app on Android
Change the orientation of the device.

Expected: The debug messages "Landscape" and "Portrait" are output after each orientation change.
Actual: The orientation messages are output randomly. For example, it outputs "Landscape" when transitioning from landscape back to portrait, and before the orientation button in the navigation bar has been pressed.

### Link to public reproduction project repository

See steps to reproduce

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All

### Did you find any workaround?

No

**Comment by greg84** [comment]
@drasticactions why have you added the needs-repro label? I have added steps to reproduce to the issue description. Just make a new project and copy/paste the code to reproduce it on Android.

**Comment by drasticactions** [comment]
https://github.com/dotnet/maui/assets/898335/efbee029-3348-4c59-9027-56bfaa8cf098

Running this in the emulator and on my Pixel 6, unless I'm misunderstanding your issue, I don't think I can reproduce what you're seeing.

As you didn't provide a sample (And the default MAUI template does not enable screen orientation changes, so you had to change that setting AFAIK) I could be doing something different then what you're doing, or

**Comment by greg84** [comment]
@drasticactions This issue seems to be related to having "auto rotate" switched off in Android.

I created a new project in VS for Mac and made no other changes except adding the debug line to the event handler.

When I switch Auto Rotate on in Android settings, it works correctly. But when auto rotate is off, I need to press the orientation button in the navigation bar, and that's when this defect is observed. Here's an example:

https://github.com/dotnet/maui/assets/4529974/1db06614-35aa-4143-9973-16f39b52f693

**Comment by drasticactions** [comment]
Thank you for the update. Debugging your issue further, I think I understand what's happening:

https://github.com/dotnet/maui/blob/700944b2ac65c4807c657336b49c72c30e4da1da/src/Essentials/src/DeviceDisplay/DeviceDisplay.android.cs#L103-L114

https://github.com/dotnet/maui/blob/700944b2ac65c4807c657336b49c72c30e4da1da/src/Essentials/src/DeviceDisplay/DeviceDisplay.shared.cs#L137-L144

OnMainDisplayInfoChanged is called from an OrientationEventListener that we apply as part of your application. That gets called whenever you rotate your device. When you rotate from Portrait to Landscape, the orientation event fires and calls OnMainDisplayInfoChanged . However, when you disable Auto-Rotate, and you rotate, the Android display settings are the same as it was in the previous mode, so the check for if the display mode actually changed says it's equal, so nothing gets fired. This, IMO, is the correct behavior. You did not rotate your app, so this should be correct.

However, when you click the button to rotate, because MAUI only checks on device rotation, it doesn't send another event to say that the app itself rotated, and that should, most likely, be another event that should fire this API. This is the missing event that should be added or fixed.

That said, the last issue, (it outputs "Landscape" when transitioning from landscape back to portrait), I believe this is correct behavior. After you use the Auto-rotate and your app flips to match, and you rotate your device again, OnMainDisplayInfoChanged is correctly called and the display output for that view is exactly what Android says it is. So when you rotate from Landscape to Portrait, with Auto-Rotate turned off, the rotation event fires, OnMainDisplayInfoChanged is called, and it correctly states that the device orientation is Landscape, because according to Android, it is. It only changes when you specifically call the rotate button.

I think the missing event on the rotate button is the key issue here, whenever that button is pressed (or some other Android event fires that should invoke this API) that should be called here for this use case.

@mattleibow, do you have thoughts on this?

**Comment by jaosnz-rep** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 4. Can not repro on Android platform with steps.
