### ISSUE TITLE
Setting a PublishItemsOutputGroup's PublishProfilePath property leads to empty msi file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#15952]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Setting-a-PublishItemsOutputGroups-Publ/10396254)._

---
[severity:It's more difficult to complete my work]
I have a BlazorApp I need to deploy using an MSI package.
When I add a VS Setup project to the solution, I can add the "PublishItemsOutputGroup" of my Blazor project to the setup project and the main binaries together with a few JSON files get packaged into the MSI file.
If I explicitely set the PublishProfilePath to the .pubxml file for folder publish from my Blazor project (it can be selected in the combo box), no files are packaged into my msi anymore, even though the Outputs from the PublishItemsOutputGroup are exactly the same compared to leaving PublishProfilePath empty.

Apart from that, I cannot seem to understand which files are part of the PublishItemsOutputGroup.
When I perform a "regular" publish-to-folder action, the whole wwwroot folder from the Blazor project gets published to the target folder.
Yet it's not part of the PublishItemsOutputGroup.
I have a really hard time trying to find out which of the over 20 different output groups to add to my setup.
Is there any documentation about how projects outputs are assigned to those output groups?

---
#### Feedback Bot on 6/20/2023, 01:50 AM: 

(private comment, text removed)
#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 6/27/2023, 03:13 AM: 

(private comment, text removed)
#### martin mueller on 6/27/2023, 03:53 AM: 

(private comment, text removed)
#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 6/27/2023, 07:08 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by MackinnonBuck** [comment]
@Eilon do you have any ideas about what's happening here?

**Comment by Eilon** [comment]
@MackinnonBuck hmm not something I'm familiar with. I don't think we've tested this particular installer project type - I'm guessing it's this one: https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2022InstallerProjects

I couldn't find any docs on whether it's supposed to work with WinUI / WindowsAppSDK or not. If I had to guess, I'd guess it's a problem that's more broad than just .NET MAUI Blazor, because once the project is "assembled", it's just a .NET MAUI project with MAUI Assets. The static files are no longer Static Web Assets at that point. My guess is that it's a problem that is more easily experienced with Blazor Hybrid.

Of course, without actually testing it locally, I could be totally wrong, and maybe it's something to fix in the MAUI Blazor targets.

**Comment by surayya-MS** [comment]
@Eilon could you please confirm that this works with MAUI in general? If not please remove blazor label. Thanks!

**Comment by Eilon** [comment]
I couldn't get this to work with a regular WinUI3 Packaged project and an installer project. I think that Packaged projects can't use MSI, but rather it has to be an MSIX so that it can be properly installed and activated by Windows. You can't just run an EXE file for such apps (I have no idea _why_, but that's how it is.)

Original poster: Can you specify the exact steps and project types you're using to create this? Is this a .NET MAUI Blazor project, or some other kind of Blazor Hybrid project?

If it's a .NET MAUI Blazor project then I think this is not a supported scenario at this time due to how WinUI applications work.

**Comment by jfversluis** [comment]
Ask for more information went unanswered for a long time. Without it this issue is hardly actionable. Closing for now.

If you find this and this is (still) important to you, please feel free to open a new issue with all the details.
