### ISSUE TITLE
Memory Leak: MAUI-Windows are not garbage-collected after destroy of MainActivity

### ISSUE THREAD

**Issue by markusroessler** [dotnet/maui#15972]
### Description

The Window created by the MainActivity and all services in the Window ServiceScope are not garbage-collected after the MainActivity is destroyed.
Please have a look at: https://github.com/markusroessler/MauiWindowScopeSample
This sample app does the following:
-  Starts an Android Foreground Service (see MainApplication.OnCreate) - this prevents the Application from terminating when the last Activity terminates
- Periodically invokes the garbage collector (see App constructor)
- Creates a custom Window from the Window ServiceScope (see App.CreateWindow)
- Injects a "ScopedService" into the Window instance, that is never referenced by anything but the ServiceScope
- The custom "MainWindow" writes the current instance count to the console (see constructor and finalizer)

There are two reasons for this Memory Leak (see "Steps to Reproduce" for workarounds):
1. The method Window.IWindow.Destroying() is never invoked and therefore Application.RemoveWindow() isn't either.
2. The method AlertManager.AlertRequestHelper.Dispose() is never invoked and therefore the MessagingCenter subscriptions are not removed

### Steps to Reproduce

- Start the sample app
- Terminate the MainActivity via the app drawer and start again via launcher icon  
-> in the console output you will see, that the Window and ScopedService instances **don't** get garbage-collected

- Enable the workarounds:
   - App.xaml.cs CreateWindow: `typeof(MessagingCenter).GetMethod("ClearSubscribers", BindingFlags.NonPublic | BindingFlags.Static).Invoke(null, null);`
  - MainActivity.cs OnDestory: `window.Destroying();`
- Start the app and repeat the steps above
-> in the console output you will see, that the Window and ScopedService instances **do** get garbage-collected

### Link to public reproduction project repository

https://github.com/markusroessler/MauiWindowScopeSample

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10 / 13

### Did you find any workaround?

see "Steps to Reproduce" - but they are obviously not meant for productive apps

**Comment by jsuarezruiz** [comment]
cc @jonathanpeppers

**Comment by Mistofs** [comment]
Try restarting your computer and reinstalling .NET

Otherwise IHostedService is holding a reference to your service for a while

**Comment by markusroessler** [comment]
> Try restarting your computer and reinstalling .NET
> 
> Otherwise IHostedService is holding a reference to your service for a while

Should I also try to reinstall windows or just .net? Maybe also replace my PC memory just to be sure?

**Comment by jonathanpeppers** [comment]
The issue here appears to be `IsFinishing` is `false` in `OnStop` here:

https://github.com/dotnet/maui/blob/462ca409a0e924719c840901df753d0dc9a42926/src/Core/src/Hosting/LifecycleEvents/AppHostBuilderExtensions.Android.cs#L53-L54

And then `IsFinishing` is `true` in `OnDestroy` here;

https://github.com/dotnet/maui/blob/462ca409a0e924719c840901df753d0dc9a42926/src/Core/src/Hosting/LifecycleEvents/AppHostBuilderExtensions.Android.cs#L62-L66

So, then the `Window` is never destroyed when you close the app. I just swiped away the app to terminate it on an Android API 33 device.

I don't actually know how this is supposed to work. @jsuarezruiz do you know who on the MAUI team would know?

These were the changes I made to debug this:

* https://github.com/markusroessler/MauiWindowScopeSample/compare/main...jonathanpeppers:MauiWindowScopeSample:peppers
* https://github.com/dotnet/maui/compare/main...jonathanpeppers:DebugAndroidLifecycle

**Comment by markusroessler** [comment]
This might also resolve #6993 by the way

**Comment by markusroessler** [comment]
@jonathanpeppers thank you for the quick fix. Any chance we are also getting this for .NET 7?
