### ISSUE TITLE
MAUI push notifications not received in OnMessageReceived unless trimming disabled on android

### ISSUE THREAD

**Issue by LewisEKay** [dotnet/maui#16014]
### Description

Using the package Plugin.Firebass to set up push notifications for MAUI. Many tutorials online exist for setting up push notifications now, however none showing how to receive messages.

if you send a message to the device onMessageReceiced will receive it as expected. However if you go to publish, it will not work. This is because by default MAUI disabled trimming for debug and enables it for release. So if you disable trimming along with AoT (doesn’t work without trimming enabled) then push notifications work fine and all is good. However, trimming and AoT are now disabled which is not ideal.

### Steps to Reproduce

1. Create new project.
2. Follow install instructions for setting up Plugin.Firebase
3. Create a new ServiceIntent for receiving push notifications like we used to do in Xamarin.Forms.
4. Send notification to device, it won’t call onMessageReceived and instead only show a notification in the devices notification window.

### Link to public reproduction project repository

None

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

Android 11 and up

### Did you find any workaround?

Disable Trimming and AoT

**Comment by jkommeren** [comment]
Please, any updates on this?

**Comment by jkommeren** [comment]
And still an issue with 8.0.3 GA

**Comment by johngraumann** [comment]
Following this. Same issue here. I have tried any number of combinations of attributes, linker XML files, etc, but I can't find the right mix. So far only disabling Trimming entirely works.

**Comment by jfversluis** [comment]
This is something that lives on the .NET for Android layer and is not something we can influence on the .NET MAUI side. The Android SDK trimming safe work is tracked here https://github.com/xamarin/xamarin-android/issues/5652. Additionally more information on this regarding this particular plugin can also be found here: https://github.com/TobiasBuchholz/Plugin.Firebase/issues/258. 

In the meanwhile to scope it down more you might try what is in the docs here: https://learn.microsoft.com/dotnet/maui/android/linking?view=net-maui-8.0&tabs=vs#preserve-code

In order to not duplicate efforts here, I will close this one.
