### ISSUE TITLE
Image only Aspect fill

### ISSUE THREAD

**Issue by Essama-Official** [dotnet/maui#16076]
### Description

The image that I get does not want to adapt to appear smaller while displaying correctly it is in fill and we see nothing
In rest: The default image is what is expected but when I add the image it will zoom it
Here for more info: https://stackoverflow.com/questions/76644025/image-only-aspect-fill?noredirect=1#comment135151720_76644025

### Steps to Reproduce

When I click on Clicked="Upload_Clicked" to add Image, the image is zoomed

### Link to public reproduction project repository

https://github.com/Essama-Official/DemoImageBug

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

iOS, Android, Windows

### Affected platform versions

Windows, Android

### Did you find any workaround?

Only by default it displays correctly (in Source)

**Comment by ToolmakerSteve** [comment]
Note: 
> Only by default it displays correctly (in Source)

means that if the image is requested as `<ImageButton Source="somefilename.jpg" ... />`, the image displays correctly.

This was confirmed as part of the StackOverflow discussion. `<Image ...` had the same failure, according to the discussion.

Therefore, the problem seems to be in MediaPicker, or how MediaPicker is used. As shown in linked repo.

 (I did not attempt to verify.)

**Comment by Essama-Official** [comment]
The only way that can work is to enlarge the image enormously, so that it takes up almost all the space, which is unpleasant
