### ISSUE TITLE
BlazorWebView&WebView Unable to load on the windows11 system, the program crashes directly

### ISSUE THREAD

**Issue by FFcodec** [dotnet/maui#16161]
### Description

.net maui for Blazor,It runs normally in win10, but the win11 system crashes directly

### Steps to Reproduce

<Grid Grid.Column="1" Grid.Row="1">
                <BlazorWebView x:Name="MyWebView"
                         Margin="10,0"
                         HostPage="wwwroot/index.html"
                         BackgroundColor="{AppThemeBinding Light={StaticResource Grey1}, Dark={StaticResource Grey9}}">
                    <BlazorWebView.RootComponents>
                        <RootComponent Selector="#app"
                                 ComponentType="{x:Type pages:SocchatComponent}" />
                    </BlazorWebView.RootComponents>
                </BlazorWebView>
            </Grid>

### Link to public reproduction project repository

no

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

21H2 22000.318

**Comment by drasticactions** [comment]
Based on your lack of reproduction project, it doesn't work for you on any app that uses Blazor Webview, regardless of what it is. It works for me, and I'm assuming others as well (since we would be getting a lot more attention for it if that was the case) so this isn't enough information to be actionable. We would need some kind of reproduction or logs for more information.

Have you tried building a WinUI app and using Webview2 in it? Does it crash there?

Does it crash in all applications? If you load any app that uses Webview2, does it fail?

**Comment by FFcodec** [comment]
![image](https://github.com/dotnet/maui/assets/96287345/7826298b-20d2-4f98-9b38-63550db84b8c)

I found the cause of this problem. My windows 11 does not have the operating environment of webView2. After I installed it, the program returned to normal

**Comment by FFcodec** [comment]
> Based on your lack of a reproduction project, I assume it doesn't work for you on any app that uses Blazor Webview, regardless of what it is. It works for me, and I'm assuming others as well (since we would be getting a lot more attention if that was the case) so this isn't enough information to be actionable. We would need some reproduction or logs for more information.
> 
> Have you tried building a WinUI app and using Webview2 in it? Does it crash there?
> 
> Does it crash in all applications? If you load any app that uses Webview2, does it fail?

Thank you,It has been resolved
