### ISSUE TITLE
overscroll stretching in Android 12 BlazorMaui

### ISSUE THREAD

**Issue by Ali1Jamal** [dotnet/maui#16239]
### Description

The overscroll stretching animation is messing up the navbar. The navbar should stay sticky at the top. Additionally, many users don't like this animation, so we need an option to disable it.
the video about the problem :
https://github.com/dotnet/maui/assets/40013555/ea72cb25-ba48-4b17-bbb2-0ad722e43d83

### Public API Changes

`        var blazorWebView = new BlazorWebView();`
       ` blazorWebView.OverScrollAnimation = false;
`

### Intended Use-Case

the use case is to disable the overscroll stretching animation .

**Comment by drasticactions** [comment]
https://github.com/drasticactions/MauiRepros/blob/8c37c53de0b99ab1889ac559e191d4e989b3507f/OverflowAndroid/MainPage.xaml.cs#L12-L18

You can override the default Android WebView control (which the BlazorWebview is based on for Android) to disable the over-scroll effect. That animation is a part of their defaults for the control, so MAUI matches it, and it's one you can change by modifying it yourself. It could require better documentation so you can find it, but creating a new API just for this function seems needless, especially since you can access the control yourself.

For the navbar not being sticked at the top, that's the default behavior of the Blazor and Bootstrap templates it includes. That could be something they could change in the template to make it a default, but that would need to happen in [their repo](https://github.com/dotnet/aspnetcore).

**Comment by Ali1Jamal** [comment]
ok thank you very much for helping me to solve it ...
Well, it was a misexpression from me, I meant that overscroll stretching affects all content, for example, if it affected everyone except navbar, I would have left it, but it affects the shape of navbar as well.
I will close the issue, since the solution is simple and limited to Android only so we do not need this api.
