### ISSUE TITLE
Rsrp/Rsrq Signal Information Not Updating with CellSignalStrengths changing

### ISSUE THREAD

**Issue by ragiovan** [dotnet/maui#16242]
### Description

Using Android.Telephony and a StateChange listener, the signal strength listener is called whenever rsrp changes (When it happens can be verified going into the sim status changes and looking at rsrp) . However, when looking through the actual Registered LTE signals LTE rsrp/rsrq is not changing at all. 

### Steps to Reproduce

Open tst solution. Connect android phone and start waving it all around. Put in a faraday cage if you want. The rsrp/rsrq received will never change.

### Link to public reproduction project repository

https://github.com/ragiovan/cellularstrengthsNotChanging

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13 at a minimum

### Did you find any workaround?

No.

**Comment by drasticactions** [comment]
This issue is not related to the MAUI UI Project. You're accessing Android functions through the [Android SDK bindings](https://github.com/xamarin/xamarin-android), and either the bindings are fault or there's something else at play within Android.

I can't transfer issues to different organizations, but I would refile this under https://github.com/xamarin/xamarin-android, they could point you in the right direction.
