### ISSUE TITLE
Touchscreen not working after rapidly clicking while app startup

### ISSUE THREAD

**Issue by Letiz0** [dotnet/maui#16251]
### Description

https://github.com/dotnet/maui/assets/103472129/377c891b-18c5-47ca-ad27-354289b74a45

Just like the video shows, if I rapidly click anywhere inside the app while starting up and loading, the touchsrceen will be broken but the mouse is still working.

### Steps to Reproduce

1. Create a new Maui Blazor Project
2. Deploy it on any tablet
3. Repeatly touch the screen inside the app window as quickly as you can

### Link to public reproduction project repository

https://github.com/Letiz0/MauiApp1

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

2023/08/01 update:
I found that if I force reload the page (e.g. NavigationManager.NavigateTo(NavigationManager.Uri, forceLoad: true)), it would be solved.

**Comment by trivalik** [comment]
If the MAUI app could not be used, is the operating system still useable via touch?

**Comment by Letiz0** [comment]
> If the MAUI app could not be used, is the operating system still useable via touch?

I can even close the MAUI app by touching the top-right "X" icon, it seems touchscreen is only broken inside the app.

**Comment by Eilon** [comment]
Hi @Letiz0 , I wonder if this is the same as https://github.com/MicrosoftEdge/WebView2Feedback/issues/3003 (even though in your case it's touch actions instead of keyboard/mouse).

A fix for that bug is listed here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3003#issuecomment-1499349079

So it's probably worth trying that to see if it resolves your issue.

**Comment by Letiz0** [comment]
> Hi @Letiz0 , I wonder if this is the same as [MicrosoftEdge/WebView2Feedback#3003](https://github.com/MicrosoftEdge/WebView2Feedback/issues/3003) (even though in your case it's touch actions instead of keyboard/mouse).
> 
> A fix for that bug is listed here: [MicrosoftEdge/WebView2Feedback#3003 (comment)](https://github.com/MicrosoftEdge/WebView2Feedback/issues/3003#issuecomment-1499349079)
> 
> So it's probably worth trying that to see if it resolves your issue.

 I've tried the solution you mentioned last month, unfortunately it seemed not solving the problem.
Just like what you said it's about the touch screen instead of the mouse.

**Comment by Eilon** [comment]
> 
> I've tried the solution you mentioned last month, unfortunately it seemed not solving the problem. Just like what you said it's about the touch screen instead of the mouse.

Alright thanks for trying it out. I guess we'll need to investigate further. I'd say there's a strong chance we'll end up redirecting this to the WindowsAppSDK (WinUI) or WebView2 team because it's unlikely there's any Blazor- or MAUI-specific issue here.

**Comment by Eilon** [comment]
I've tried reproducing this on my Surface Book 3 with a touch screen and so far I am unsuccessful. I tried tapping the white part of the screen as much as possible while it loads but the app remains fully responsive to all input types. I'll keep trying.

**Comment by Eilon** [comment]
Alright now I can repro it! I lowered the max CPU power settings to 25% and that seemed to slow everything down enough. I then launched the app, randomly tapped on it while it loaded, and then touch doesn't work at all in the app. Interestingly, both mouse and keyboard work fine.

**Comment by Letiz0** [comment]
> Alright now I can repro it! I lowered the max CPU power settings to 25% and that seemed to slow everything down enough. I then launched the app, randomly tapped on it while it loaded, and then touch doesn't work at all in the app. Interestingly, both mouse and keyboard work fine.

Thanks for your efforts, and yes, the worse hardware is, the more often problem happens.
It also happens when navigation and loading data from EF Core, and that's what actually annoying me.
The video just shows the easiest way to reproduce it.

**Comment by Letiz0** [comment]
> > Alright now I can repro it! I lowered the max CPU power settings to 25% and that seemed to slow everything down enough. I then launched the app, randomly tapped on it while it loaded, and then touch doesn't work at all in the app. Interestingly, both mouse and keyboard work fine.
> 
> Thanks for your efforts, and yes, the worse hardware is, the more often problem happens. It also happens when navigation and loading data from EF Core, and that's what actually annoying me. The video just shows the easiest way to reproduce it.
> 
> I found that if I force reload the page when the problem happened (e.g. NavigationManager.NavigateTo(NavigationManager.Uri, forceLoad: true)), the touch-screen would be resumed and everything worked fine, so I guess it's all about WebView2.

**Comment by Eilon** [comment]
I was able to repro something very similar in a pure WindowsAppSDK (WinUI) + WebView2 app:

1. Create new WinUI default app in VS
2. Replace the app's content with: `<WebView2 Source="https://microsoft.com/" />`
3. Set your tablet PC's CPU to some extremely low speed, like this:<br>
<img width="824" alt="image" src="https://github.com/dotnet/maui/assets/202643/3b084b17-2b71-4160-9b04-49b5850ce75d">
4. While launching the app w/ debugger from VS, tap the blank white app loading screen _a lot_
5. Eventually the app "loads", but it remains entirely a blank screen
6. Interestingly, the app did load the page because you can see it in the F12 dev tools!<ve>
<img width="1313" alt="image" src="https://github.com/dotnet/maui/assets/202643/39789586-9b91-4fa3-9415-367f3dc80ef6">

So, I'm not quite sure if it's _exactly_ the same bug, but it's super similar.

**Comment by Eilon** [comment]
This issue was moved to MicrosoftEdge/WebView2Feedback#3685
