### ISSUE TITLE
Hot-Reload Not Detecting XAML Changes

### ISSUE THREAD

**Issue by sangeethnandakumar** [dotnet/maui#16267]
### Description

# ISSUE SUMMARY
###  Hot-Reload was unable to detect changes made in XAML with the default MAUI template

1. Open Visual Studio
2. Choose the MAUI template 
3. Build and deploy the default template to a real Android device (I used Samsung Galaxy S22)
4. Update XAML like label text or something etc..
5. HotReload cannot detect the change, No app refresh in the phone

# DEMO
1min Quick YouTube Video: https://www.youtube.com/watch?v=8N0auUQr88I

# APPS & DEVICES I USED
- Microsoft Visual Studio Community 2022 (64-bit) - Preview
      - Version 17.7.0 Preview 4.0
- Samsung Galaxy S22 
      - Model: SM-S901E/DS 
      - One Ul version: 5.1
      - Version: S901EXXUSCWEC/S901EOXMSCWEC/S901EXXU5CWEC

# Targeted Frameworks
```xml
<TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
```

### Steps to Reproduce

1. Open Visual Studio
2. Choose the MAUI template 
3. Build and deploy the default template to a real Android device (I used Samsung Galaxy S22)
4. Update XAML like label text or something etc..
5. HotReload cannot detect the change, No app refresh in the phone

### Link to public reproduction project repository

No Repo, Use default MAUI template on latest preview Visual Studio

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

13

### Did you find any workaround?

1. Delete app from phone
2. Rebuld and deploy

### Relevant log output

```shell
In demo video
```

**Comment by drasticactions** [comment]
@sangeethnandakumar Looking at your video, a few notes:

- XAML Hot Reload does not use the Hot Reload button you're pushing. I can tell you that does nothing. Changes are applied either whenever you type something in, or hit save, depending on the settings you have in Visual Studio.
- The output logs you show are for general .NET Hot Reload (As in, C#) so the logs are correct, there are no changes because it's unrelated to XAML Hot Reload.
- For these two above issues, they are very confusing and it's something we're working on sorting out.


- Can you check if XAML Hot Reload is enabled in your visual studio settings?
- Can you verify that breakpoints work in your application? For example, try setting a breakpoint in the template click handler  for the button and run it a few times, does it stop?
- Does XAML Hot Reload work for you when running on WinUI? Does it work in Xamarin.Forms?
- If you leave the app running for awhile, do you see a yellow bar saying there's a timeout? Or does nothing happen?

Based on the video, my guess is that either XAML Hot Reload is turned off, or the debugger is not correctly sending over and starting the assemblies necessary for XAML Hot Reload to work. There's no Live Visual Tree, meaning nothing for hot reload has started.

**Comment by sangeethnandakumar** [comment]
Hi @drasticactions, Here is the information

> XAML Hot Reload does not use the Hot Reload button you're pushing. I can tell you that does nothing. Changes are applied either whenever you type something in or hit save, depending on the settings you have in Visual Studio.

You can see I'm doing file saving on video (Ctrl + S). The visual studio marks the line to green from yellow on the sidebar

> For these two above issues, they are very confusing and it's something we're working on sorting out.

I experienced this a few times in different scenarios. But mostly with real devices, This is evident not all time but random and often when connecting and disconnecting different mobiles. Sometimes mobile ADB authorization is done after plugging in USB. While sometimes already ADB-authorized devices. One other glitch I experienced one day was immediately building after VS updated the same issue. But it's happening sometime randomly. As you said hot reload may not be initializing

> Can you check if XAML Hot Reload is enabled in your visual studio settings?

Already on

> Can you verify that breakpoints work in your application? For example, try setting a breakpoint in the template click handler for the button and run it a few times, does it stop?

It does stop. There's no issue with the debugger. As you can see in the video, Breakpoint is hit when I click that button.

> Does XAML Hot Reload work for you when running on WinUI? Does it work in Xamarin?Forms?

Yes, I checked before raising this issue. It updates in real-time with Windows. The issue is with Android. Haven't checked with iOS. I never used Xamarin. I was coming from .NET WebAPI and Flutter world

> If you leave the app running for a while, do you see a yellow bar saying there's a timeout? Or does nothing happen?

Left app running for 20mins. Nothing happened.

I strongly belive this is because of hot-reload not able to initialize on Android device correctly

**Comment by drasticactions** [comment]
Thank you, some more questions

- The defaults for XAML Hot Reload are to update in real(ish) time as you type. Unless you've changed the defaults, it should update as you type. Again though, I believe the process has yet to start since there's no Live Visual Tree.
- Could you please upload the [Xamarin logs](https://learn.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/questions/version-logs#-visual-studio-tools-for-xamarin). Generally, these would be already uploaded if filed through [VSFeedback](https://developercommunity.visualstudio.com/).
- Does it work on an Android Emulator? Does it only fail on Device? 

Based on what you wrote then, my guess is that:

- Normally, after starting the application, there's a breakpoint XAML Hot Reload sets on the application startup to start the injection process and start XAML Hot Reload. What could be happening is that this breakpoint, for whatever reason, is being missed or skipped over so to XAML Hot Reload, nothing has happened. Normally if there's at least one breakpoint hit, it will try to inject and if it can't, fail with an error. But if it's not being injected at all or that initial breakpoint is being missed, then the process will fail and timeout with an error.

**Comment by drasticactions** [comment]
I also tested this on the same version of Visual Studio you're running, with what I believe to be the same workloads, and it works correctly on my Pixel 6 and Pixel 4a running Android 13. Maybe this is specific to your device? How are you debugging your application? Wireless? directly connected to your PC?

**Comment by sangeethnandakumar** [comment]
Hey sorry, I was busy running behind a release and deployment the past week.

Here's a summary:

- [ ] Yeah, I only prefer using a real device to test my apps. And it's USB debugging latched to my PC with a cable, not wireless ADB.
- [ ] The device I used was Samsung Galaxy S22.
- [ ] Normal debugging breakpoints hit easily. No issues at all. XAML won't update
- [ ] Works fine with Windows, Fails sometimes random with Android real device
- [ ] Tried other devices other than my Galaxy S22, Same issue randomly. I believe it's originating from VS, not the smartphone
- [ ] This is mostly prominent when building after updating Visual Studio MAUI workload for first time
