### ISSUE TITLE
[iOS] When using a ScrollView with Shell the ContentSize isn't sizing consistently with Forms

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#16352]
### Description

We currently have a failing test on our Legacy test runs (EntryScrollTest). This is caused when `ScrollView` is the root layout of `Shell`. The contentSize of the `ScrollView` gets set to the size of the entire page whereas in XF it looks like it was subtracting out the danger zone. This only started failing after this [PR](https://github.com/dotnet/maui/pull/16093). 

A few other observations
- If you hide the NavigationBar then everything lays out the same. 
- When using NavigationPage as the root page that's consistent with Shell. 

I'm still not too sure who's wrong here :-) 
Need to investigate a bit more. 

### Reproduction code

The Sandbox [here](https://github.com/dotnet/maui/pull/16339) has Repro code.

Here's the layout on MAUI

![image](https://github.com/dotnet/maui/assets/5375137/de36bc2f-0e43-4787-9e62-51f0306cabf8)

Here's the same layout on Xamarin.Forms

![image](https://github.com/dotnet/maui/assets/5375137/ed608b84-c968-4319-8837-cc3e47061369)

This only reproduces with Shell because with Shell the UIScrollView is underneath the NavigationBAr where as with NavigationPage it is not. 

The fix here is to flesh out our ISafeArea (IDangerZone) APIs and expose those APIS on ScrollView. Right now ScrollView sets the adjustedContentInset if it's in the danger zone and that's currently not configurable.

**Comment by borrmann** [comment]
maybe related to #16360

**Comment by PureWeen** [comment]
> maybe related to #16360 . Since the linked PR, IgnoreSafeArea adds a padding for all Layouts except ScrollView because it doesnt have this property. Before the PR, this only shouldve happened when UseSafeArea=False was set on the page

I was really optimistic this was the issue, but I just tested, and it didn't seem to help.

**Comment by borrmann** [comment]
@PureWeen Yeah I realised too. Though, I can imagine this default behaviour may have led to designing some incorrect calculations while passing tests. Because the defaults differ so much between iOS and Android. I have read a lot of related issues about layout sizing and SafeArea on iOS and in many of them it seemed like some of your developers weren't aware how UseSafeArea and IgnoreSafeArea are supposed to work. When this is not taken into account while writing tests for android and ios, it seems very easy to make a mistake calculating heights. 

When using UseSafeArea=True, the layout sizes are mostly fine, when using the other option, there is no way to get it right. 

**I would really hope there would be a way to just get access to the entire Screen on all platforms and leave the rest to the developer if they wish so. **

If the insets of the safe area are accessible through a simple service or as a Property, it would be really easy to set this padding just where it is wanted. This should be a lot easier then the current way of UseSafeArea and IgnoreSafeArea

**Comment by rudyspano** [comment]
I have a simple workaround based on native management (ContentInsetAdjustmentBehavior is set as Automatic by default)

```
ScrollViewHandler.Mapper.AppendToMapping("ForceContentInsetAdjustmentBehavior", (handler, view) =>
{
    if (handler is IScrollViewHandler scrollViewHandler)
    {
        scrollViewHandler.PlatformView.ContentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentBehavior.Never;
    }
});

```
