### ISSUE TITLE
Cookies are not sent in .NET MAUI Blazor with ASP.NET MVC API

### ISSUE THREAD

**Issue by Woselko** [dotnet/maui#16409]
### Description

I have 2 applications:
-.Net Maui Blazor mobile app
-ASP.NET MVC API to do some server stuff.

and now I have a couple of methods in LanguageController, one of them is ChangeLanguageApi() (MVC application)

```
 [HttpPost]
        public IActionResult ChangeLanguageApi([FromBody]string culture)
        {
            if (culture == null || !_supportedLanguages.Contains(culture))
            {
                return StatusCode(StatusCodes.Status404NotFound,
                    new Response { IsSuccess = false, Message = Common.SomethingWentWrong,  });
            }
            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddMonths(6) });

            return StatusCode(StatusCodes.Status200OK,
                    new Response { IsSuccess = true, Message = Common.Success});
        }
```

Program.cs looks like this (MVC application):

```
builder.Services.Configure<LanguageSettings>(options => builder.Configuration.GetSection("LanguageSettings").Bind(options));
builder.Services.AddLocalization(options => options.ResourcesPath = "Resources");
var mvcBuilder = builder.Services.AddControllersWithViews().AddDataAnnotationsLocalization(options =>
{
    var type = typeof(Resources.Common);
    var assembly = new AssemblyName(type.GetTypeInfo().Assembly.FullName);
    var factory = builder.Services.BuildServiceProvider().GetService<IStringLocalizerFactory>();
    var localizer = factory.Create("Common", assembly.Name);
    options.DataAnnotationLocalizerProvider = (t, f) => localizer;
});
var app = builder.Build();
var languageSettings = builder.Configuration.GetSection("LanguageSettings:SupportedLanguages").Get<List<string>>();
var supportedCultures = new List<CultureInfo>();
languageSettings.ForEach(x => supportedCultures.Add(new CultureInfo(x)));
app.UseRequestLocalization(new RequestLocalizationOptions
{
    DefaultRequestCulture = new RequestCulture("en"),
    SupportedCultures = supportedCultures,
    SupportedUICultures = supportedCultures
});
```

Below code in Blazor App responsible for changing language (returnResponse.Message is always in same langugage):

```        
		public async Task<Response> ChangeLanguage(string language)
        {
			var returnResponse = new Response();
			using (var client = new HttpClient())
			{
				var url = $"{Settings.BaseUrl}{Apis.ChangeLanguage}";

                var serializedStr = JsonConvert.SerializeObject(language);

                var response = await client.PostAsync(url, new StringContent(serializedStr, Encoding.UTF8, "application/json"));
                if (response.IsSuccessStatusCode)
				{
					string contentStr = await response.Content.ReadAsStringAsync();
					returnResponse = JsonConvert.DeserializeObject<Response>(contentStr);
				}
			}
			return returnResponse;
		}
```

So basically I store some available cultures in appsettings.json in MVC app and every resource is keeped in .resx files

And now, when I use Swagger/Postman to test my API, I get translated message in response object according to culture that I post, but in my Blazor mobile app it does not change. It looks like this cookie does not work for my Blazor app. 
Cookie for changing to polish language in swagger:
![image](https://github.com/dotnet/maui/assets/76818798/a4d8be1f-1f0c-46b0-8b9f-fd662c9a5bc2)
Cookie for changing to english language in swagger:
![image](https://github.com/dotnet/maui/assets/76818798/e0c7e971-417f-4b6c-8821-601de830905e)
**No coockie in blazor when it is used same endpoint**:
![image](https://github.com/dotnet/maui/assets/76818798/b1fe2628-4a49-461b-8984-682415394580)
Android Emulator and Windows app build work in the same way. I would like to display messages according to posted `string culture`  Can anyone help me with that?

### Steps to Reproduce

Create .Net Maui Blazor App with request to api for change language
Run api from https://github.com/Woselko/Actively
Observe that cookie is not sent to blazor but works in swagger

in general
Try to send cookie with method provided in description to .net maui blazor app

### Link to public reproduction project repository

https://github.com/Woselko/Actively
https://github.com/Woselko/ActivelyMobile/tree/Language_changes

### Version with bug

7.0.81

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

windows 10, windows 11

**Comment by Woselko** [comment]
it could be similar issue https://github.com/dotnet/maui/issues/16266

**Comment by Eilon** [comment]
Hi @Woselko can you show the "-.Net Maui Blazor mobile app" that you have? I'm not sure I understand the connection between the MAUI Blazor app and the ASP.NET MVC app. In a MAUI Blazor app there is no need for cookies because it is a client application running locally. Cookies are used between a web browser and server, but neither of those exist in MAUI Blazor.

**Comment by Woselko** [comment]
@Eilon here is a link to branch with changes https://github.com/Woselko/ActivelyMobile/tree/Language_changes

**Comment by Eilon** [comment]
@Woselko thanks for sharing the code. I was only able to read through a small portion of the code, but it appears to be trying to use Blazor Server or WebAssembly patterns that assume a web browser and web server by setting cookies for purposes such as authentication. In a Blazor Hybrid app, such as a .NET MAUI Blazor app, these concepts don't apply in the same way because there's no web browser or web server or HTTP (as far as Blazor is concerned). A Blazor Hybrid app is simply a native client app and should follow client authentication patterns, which never involve cookies.

As far as I could tell, I couldn't find any part of this issue that would lead me to believe there's an issue with BlazorWebView or Blazor Hybrid in general, so I am closing this issue.

If you believe there is still an issue in Blazor Hybrid, please post a simplified repro that demonstrates the specific problem with it.
