### ISSUE TITLE
XAML can't find outer converter and fails to build

### ISSUE THREAD

**Issue by StanislavIlchenko** [dotnet/maui#16468]
### Description

ERROR XFC0000 Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:toolkit:IntToBoolConverter" D:\Dev\MauiResourcesTest\MauiResourcesTest\Resources\Styles\Converters.xaml	7	

### Steps to Reproduce

1. Using latest VS 17.6.5 create new MAUI solution for .net 7
2. Install CommunityToolkit.Maui package (5.2.0)
3. Create new resource file Converters.xaml
![image](https://github.com/dotnet/maui/assets/141010748/a7ea8cd9-eeec-4960-b42e-9f4fa03fd887)

Note that IntToBoolConverter is visible by Visual Studio:
![image](https://github.com/dotnet/maui/assets/141010748/8805322c-4add-46e4-b650-cf4b1df25bb6)

### Link to public reproduction project repository

https://github.com/StanislavIlchenko/MauiBugReproduce

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041, and others

**Comment by awasilik** [comment]
Hi, 
We are able to reproduce this issue as well.
This happens when you reference any component of CommunityToolkit in .xaml files via markup extension:
```
Converter={toolkit:InvertedBoolConverter}}"
```
Build fails with error:
<img width="788" alt="image" src="https://github.com/dotnet/maui/assets/33750371/5075f153-16f6-4a8b-9eb9-5e90a25f3588">


Workaround for this issue is to either add converter as Resource:
```
<ContentPage.Resources>
   <converters:InvertedBoolConverter x:Key="InvertedBoolConverter" x:Name="InvertedBoolConverter" />
</ContentPage.Resources>
```

or to add a file similar to "LinkerPleaseInclude.cs"
which references CommunityToolkit in csharp files

**Comment by StanislavIlchenko** [comment]
Yes after that error disappears. But both of them lead to exception on app startup:

![image](https://github.com/dotnet/maui/assets/141010748/6c48c359-6cd7-4b94-94d4-f0bd2ebd4788)
Converters.xaml is added to resource dictionary:
![image](https://github.com/dotnet/maui/assets/141010748/fa1ae2b9-fd6b-4e08-a54b-85d712df4cfb)

Also "x:Name workaround" requires removing x:Class attribute and removing Converters.xaml.cs file which could inappropriate in some use cases.

**Comment by jfversluis** [comment]
I have looked into this before back for Xamarin.Forms. The root cause here is that there is no reference in code, only in XAML, and therefore the linker/compiler does not load the assembly that it's contained in. In turn the type can't be found because that assembly isn't loaded.

By specifying the `x:Name` it will create a reference in code and everything will start working. Same would probably work if you just put `_ = new IntToBoolConverter()` somewhere.

However, for the .NET MAUI Community Toolkit this problem should not really be happening because for the Toolkit you need to add `UseMauiCommunityToolkit()` to your `MauiProgram.cs` and there will always be a reference in code because of that. 

Since a while we have an analyzer in the Toolkit that will throw a compile error if you don't include it. In the reproduction I don't see that `UseMauiCommunityToolkit()` line, and therefore the project won't even compile. If you do add that initialization line, does that resolve the problem as well?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 5. Not repro on Windows platform with sample project.
https://github.com/StanislavIlchenko/MauiBugReproduce
![image](https://github.com/dotnet/maui/assets/77434865/b1d28c5d-8544-43a1-bd4b-af1949bd1b45)
