### ISSUE TITLE
Web Inspector cannot use app

### ISSUE THREAD

**Issue by CarterBoyd** [dotnet/maui#16611]
### Description

When running the Maui Blazor app on an iPhone 13 Max, iPad mini (6th generation), and MacBook Pro 2019 The web inspector will not show that the app exists in its typical 0.0.0.0 name. both IOS devices have web inspector turned on and will appear for web inspect if I open safari on the devices. I have followed the steps provided from https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/developer-tools?view=aspnetcore-7.0&pivots=ios

### Steps to Reproduce

1. Create Maui blazor app
2. Deploy app to IOS device
3. Make sure IOS device has web inspector turned on (Settings > Safari > Advanced > WebInspector
4. Make sure MacBook Pro allows for web inspector (Safari > Settings... > Advanced > Show Develop menu in menu bar
5. With IOS device plugged into MacBook running the app, navigate on the MacBook to Develop > Your devices name and there will be no option to inspect app

Expected result:
<img width="741" src="https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/developer-tools/_static/ios.png?view=aspnetcore-7.0">
Actual result:
<img width="741" alt="Screenshot 2023-08-08 at 4 17 38 PM" src="https://github.com/dotnet/maui/assets/70919992/511f2032-f605-4867-b3d3-a59788b0d76c">

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

IOS 16.6 for both iPhone and iPad, macOS Ventura 13.5 (22G74)

**Comment by drasticactions** [comment]
@CarterBoyd Testing on Catalyst on net7.0 and net8.0 Preview 7, it did work correctly for me. I could see it show in the developer device dropdown and connect to it. Can you try that again and take a picture showing it missing?

For iOS, I think this is partially a documentation issue and possibly a bug.

https://github.com/drasticactions/maui/blob/d612643feeefd61a6bda6fb6c6c810e393ae9625/src/BlazorWebView/src/Maui/iOS/BlazorWebViewHandler.iOS.cs#L98-L101

This is the code that adds the web inspector. It only works if your app targets Catalyst 13.3 or greater or IOS 16.4 or greater. That's because those APIs only exist on those platform versions and would blow up if you were targeting anything lower. MAUIs  Runtime Identifier default for Catalyst is 13.3, but for iOS is 14. So, AFAIK, this code will only fire if you're targetting at least 16.4.

But that said, I'm not sure if you can target that version with the iOS SDK. As far as I can see the limit is `IOS16_1_OR_GREATER` and when I placed in the original code, I used `IOS16_4_OR_GREATER` because I wanted to make sure that it only ran on versions that high. 

@rolfbjarne  Did I make a mistake here? Should I have used `IOS16_1_OR_GREATER`?

@CarterBoyd For the moment, if you do

https://github.com/drasticactions/MauiRepros/blob/302ae56fea910cf106d803d826db6ac6352d63de/WebInspectorTest/MainPage.xaml.cs#L17-L23

Then it should work for iOS too.

**Comment by rolfbjarne** [comment]
> @rolfbjarne Did I make a mistake here? Should I have used `IOS16_1_OR_GREATER`?

I believe you should have used a runtime check, not a compile-time check, because your code will not:

> fire if you're targetting at least 16.4.

it will fire if _MAUI_ is _built_ referencing a Microsoft.iOS SDK that support iOS 16.4 (which you always do, so the check has no effect really).

**Comment by drasticactions** [comment]
> it will fire if _MAUI_ is _built_ referencing a Microsoft.iOS SDK that support iOS 16.4 (which you always do, so the check has no effect really).

Oops, yeah, that's my mistake. That makes total sense. How should I do that then? Are there docs for that?
