### ISSUE TITLE
Support for ARKit and ARCore on .Net MAUI

### ISSUE THREAD

**Issue by bonniemathew** [dotnet/maui#16623]
### Description

I would love to have ARKit and ARCore APIs on .Net MAUI. This was supported on Xamarin. Our framework is built on Xamarin and we were thinking of porting it to .Net MAUI and the lack of AR APIs is blocker for us. 

### Public API Changes

Support for all the ARKit and ARCore features. 

### Intended Use-Case

Our framework is built on Xamarin and we were thinking of porting it to .Net MAUI and the lack of AR APIs is blocker for us.

**Comment by drasticactions** [comment]
The APIs you're talking about are SDK-specific. This repo is for the MAUI UI project, so requests for binding of APIs should go to the SDK projects instead (xamarin-android and xamarin-macios)

That said, [ARKit](https://github.com/xamarin/xamarin-macios/tree/main/src/ARKit) is still bound in the .NET iOS/Mac SDK. AFAIK it should function the same as before, there were no breaking changes between the older and newer tooling (CC @rolfbjarne if I'm wrong on that)

For [ARCore](https://github.com/xamarin/XamarinComponents/tree/main/Android/ARCore), that was a Xamarin Component project. It hasn't been touched in a few years from the looks of it, and I'm not sure if it was replaced or not, or if there was any timeline on what's going on with those. @Redth would you know?

In both cases, it has no relation to the MAUI UI project. These would need to be bound outside of this repo.

**Comment by rolfbjarne** [comment]
> That said, [ARKit](https://github.com/xamarin/xamarin-macios/tree/main/src/ARKit?rgh-link-date=2023-08-09T08%3A37%3A27Z) is still bound in the .NET iOS/Mac SDK. AFAIK it should function the same as before, there were no breaking changes between the older and newer tooling (CC @rolfbjarne if I'm wrong on that)

There may have been minor breaking changes in specific APIs (no feature removal, but we fixed numerous typos and broken bindings all over the place, so existing code might need a few touchups), but ARKit as a whole is present in .NET, just as it was in Xamarin.

**Comment by drasticactions** [comment]
@PureWeen I agree that this issue should be closed, but do we know the answer for ARCore? @jonathanpeppers @Redth?

**Comment by Redth** [comment]
@moljac can you help answer about ARCore bindings?

**Comment by moljac** [comment]
ARCore bindings are in XamarinComponents repo:

https://github.com/xamarin/XamarinComponents/tree/main/Android/ARCore

and the latest version released by Microsoft/Xamarin was 1.29

https://www.nuget.org/packages/Xamarin.Google.ARCore
https://www.nuget.org/packages/Xamarin.Google.ARCore/1.29.0

Google documentation for ARCore:

https://developers.google.com/ar
https://github.com/google-ar/arcore-android-sdk


ARCore was used by SceneForm and update requests came mostly in conjunction with SceneForm SDK:

https://github.com/xamarin/XamarinComponents/tree/main/Android/SceneForm
https://www.nuget.org/packages?q=Xamarin.Android.SceneForm&prerel=true&sortby=relevance
https://www.nuget.org/packages/Xamarin.Android.SceneForm.Core

Google documentation for SceneForm:

https://developers.google.com/sceneform/develop
https://github.com/google-ar/sceneform-android-sdk

Since SceneForm was deprecated, open sourced, archived, the roadmap was unclear and we did not manage to bind alternatives like:

- Filament 
   https://github.com/google/filament
- SceneView - SceneForm fork 
   https://github.com/SceneView/sceneform-android
- SceneForm fork
  https://github.com/SceneView/sceneform-android
  
     
the decision was to stop maintaining both ARCore and SceneForm.

**Comment by bonniemathew** [comment]
Well, my question is to understand whether the ARKit APIs are available on .Net for iOS and ARCore APIs on .Net for Android? As far as I understand, .Net MAUI is based on .Net for Android and .Net for iOS. 

I was using ARKit and ARCore APIs on our Xamarin based framework and it was working fine. I am thinking for migrating our project from Xamarin to .Net MAUI. But now after creating a the project using .Net MAUI App template in Visual Studio 2022, it does not seem to find ARKit and ARCore APIs. 

If I add the old Xamarin bindings for ARCore(Xamarin.Google.AR Nuget pacakge) it does not fix the errors since its targeted for monoandroid and not .Net for Android.

**Comment by monkeyK1n9** [comment]
@bonniemathew please can you tell me how you integrate arkit and arcore in .net maui? do you have a repo I can look to learn from it. I am working on a similar project and I really need your help.
