### ISSUE TITLE
: WindowsPackageType is set to None, but GenerateAppxPackageOnBuild is set to true.

### ISSUE THREAD

**Issue by nicolgit** [dotnet/maui#16696]
### Description

when I try to publish the following solution

https://github.com/nicolgit/Open.Padlock/

I receive the following error:

`error : Improper project configuration: WindowsPackageType is set to None, but GenerateAppxPackageOnBuild
is set to true. [C:\myprojects\github\Open.Padlock\code\Blast.Model\Blast.Model.csproj::TargetFramework=net7.0-windows1
0.0.19041.0]`
 

### Steps to Reproduce

clone https://github.com/nicolgit/Open.Padlock/

execute the following 

`dotnet publish code/Blast/Blast.sln -c Release -f:net7.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="<your thumbprint"`

### Link to public reproduction project repository

 https://github.com/nicolgit/Open.Padlock/

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

no

**Comment by mattleibow** [comment]
I think this issue is happening because you are passing the `GenerateAppxPackageOnBuild=true` on a solution build - which is instructing all projects (including libraries) to produce .appX packages. I understand this does not make sense, but the WinUI targets maybe are not able to decide what you are trying to do.

I would open an issue over there: https://github.com/microsoft/WindowsAppSDK/issues

A workaround/alternate solution would be to either set this property directly in your app csproj - or - instead of building the _solution_, you would build the _project_. If you publish a solution, it will try publish _every_ project in it. If you publish a project, it just publishes the single.

Also, a publish does not need the GenerateAppxPackageOnBuild property as that is now implicit with a publish of an app project.

**Comment by nicolgit** [comment]
@mattleibow your workaround solved thank you! As you suggested am opening an issue also on windows App SDK repo

**Comment by mattleibow** [comment]
Glad to hear the building of the project worked. I am going to close this issue because publishing a project is the correct way to publish apps.
