### ISSUE TITLE
MessagingCenter is now internal in .net 8

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#16714]
### Description

There are a large number of projects that haven't yet migrated to .NET Maui, actions like this make it more difficult to migrate from Xamarin Forms.

I know that supporting existing XF developers isn't your highest priority, but actions like this are ill thought out. Please consider reversing decisions like this.

<shouting into the void...>

### Steps to Reproduce

Convert a XF app that uses MessagingCenter
You are now forced to refactor code to use a version from the community toolkit (and you can't see the deprecation message as the class is now internal, just says you can't use it due to protection level).

That is a poor decision from MS unless your intention is to:
Make your lives easier at the expense of 1000s of Xamarin Forms developers
Intending to make the adoption of .NET Maui more difficult

### Link to public reproduction project repository

Ha, funny

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Did you find any workaround?

.NET 7 Maui, but that isn't in a great state so we are looking if we can migrate straight to .NET 8.

**Comment by Symbai** [comment]
This must be by design as the samples were updated to use the community toolkit instead which should be your workaround alias solution.

https://github.com/dotnet/maui/commit/487845d8536615b8c7151b50bc045fc577b5957b
https://github.com/dotnet/maui/commit/762e07e04d1fdf8fca3edd948bab294c8762cd2c

**Comment by mattleibow** [comment]
This was deprecated in net7

https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/messagingcenter

@jfversluis should we maybe copy this API into the MCT and use the new MVVM stuff?

**Comment by jfversluis** [comment]
Not sure if I'd want to add that to the .NET MAUI Community Toolkit because it would be very temporary and doesn't do anything except for providing some compat. I understand it's a hassle to also take this on, but if you're converting your apps anyway I think this should definitely be part of it as the perf between our `MessagingCenter` and the MVVM Toolkit implementation is a HUGE improvement.

If it helps anything I'd be willing to wrap something in a separate library to provide some mitigation here, but I don't think we will be reverting this. Would that help anything?

**Comment by mattleibow** [comment]
Maybe @PureWeen can wrap it with his shandlers? That is meant to be the compat/bugfixy/temp stuff...

**Comment by mattleibow** [comment]
Seems a negative thing to add migration pain, so we maybe can revert for now and re-think in net9.
