### ISSUE TITLE
Extend KeyboardAccelerator to all controls

### ISSUE THREAD

**Issue by rachelkang** [dotnet/maui#16936]
### Description

KeyboardAccelerator currently only works for MenuFlyoutItem.
We should investigate further on how KeyboardAccelerator might apply to other controls and consider extending the API to them all.
As a part of this change, we will also make KeyboardAccelerator an attached property.

### Public API Changes

```cs
public static readonly BindableProperty KeyboardAcceleratorProperty = BindableProperty.Create**Attached**(nameof(KeyboardAccelerator), typeof(KeyboardAccelerator), typeof(MenuItem), null);
```

### Intended Use-Case

Improve keyboard desktop experience for customers

**Comment by mattleibow** [comment]
I now doubt myself. If we add it to the base VisualElement, then we don't need an attached property. I investigated WinUI / UWP some more and they have the property on their base `UIEmement`. This leads me to think maybe we don't need to do fancy attached properties. Plain properties are fine.

Sure, we could have an attached property and attach to anything and everything, but that might be more misleading now. I could of course make some drawn API canvas and attach a accelerators to random Element derived types, but in that case I can also add the property to my types since I will be controlling it.

The nice thing about an attached property is that it is a single API that _can_ be used everywhere. But maybe not super relevant?
