### ISSUE TITLE
[regression/8.0.0-preview.4.8333] Windows application frame is now black

### ISSUE THREAD

**Issue by hilmican-yuksel** [dotnet/maui#16969]
### Description

Windows Application Frame color is black on net8.0-windows10.0.19041.0 

![Screenshot 2023-08-24 102705](https://github.com/dotnet/maui/assets/89516279/18934aa2-d7e7-4a3d-ac2a-9e68dd0ee134)

### Version with bug

[8.0.0-preview.4.8333](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.4.8333)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

[8.0.0-preview.3.8149](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.3.8149)

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

**Comment by jeremy-visionaid** [comment]
I also observe this upgrading to 8.0.0-preview.7.8842

**Comment by jeremy-visionaid** [comment]
Here's a repo - just a new .NET MAUI App template switched to dotnet 8:

https://github.com/molesmoke/MauiTestApp/tree/dotnet8

**Comment by jeremy-visionaid** [comment]
@PureWeen Looks like this was caused by https://github.com/dotnet/maui/pull/14517

**Comment by PureWeen** [comment]
@jeremy-visionaid hmm is it a particular version of windows or OS level styling you have set?

I created a new template and using light theme everything look white to me.

<img width="403" alt="image" src="https://github.com/dotnet/maui/assets/5375137/f38e261b-2945-41ec-b574-c53d0cd378a2">

NET7 does style with a slightly different grey

<img width="408" alt="image" src="https://github.com/dotnet/maui/assets/5375137/ee83ef8c-dae3-4498-b05a-098c48595869">


But I'm not seeing black.

Your sample
<img width="397" alt="image" src="https://github.com/dotnet/maui/assets/5375137/d876a0d1-c7af-45e2-8661-3cd70af22cae">

**Comment by jeremy-visionaid** [comment]
@PureWeen Ah yup, looks like it's not default Windows behaviour, looks like both @hilmican-yuksel and I are running with:
"Show accent colour on title bars and window borders" in "Settings -> Personalisation -> Colours"

Also looks like you're running the main branch - the repro for this issue is on the dotnet8 branch (I have a branch per MAUI bug).

Overall, it's obviously not a major one, but I write apps for visually impaired users, so style/consistency and usability for high contrast/custom DPI/scaling, accessibility etc. is particuarly important to that group. Ideally I'd like to be able to follow the underlying WinUI themes closely (though that also has it's own problems).

With the lack of consistency between Microsoft's UI frameworks, I'm not sure what the "correct" behaviour should be here. But I'd guess it should at least be all one way or all the other, and preferably configurable via styles/themes.

**Comment by Foda** [comment]
@jeremy-visionaid: In the dotnet8 branch we set a custom titlebar by default -- but don't override the caption buttons so they default to the behavior of using the Windows theme settings. We should probably just make the default behavior for the caption buttons to have a transparent background w/ the correct text foreground resource.

However, for now, you can work around this by setting the caption button colors manually. This might be better anyways since you're designing for visually impaired users and gives you more consistent control.

To do this for an app with a Light theme you can add the following code to your `MauiProgram.CreateBuilder` logic:

```csharp
builder.ConfigureLifecycleEvents(events =>
{
    events.AddWindows(windows =>
        windows.OnWindowCreated(window =>
        {
            window.AppWindow.TitleBar.ButtonBackgroundColor = Microsoft.UI.Colors.Transparent;
            window.AppWindow.TitleBar.ButtonForegroundColor = Microsoft.UI.Colors.Black;
        }));
});
```

**Comment by jeremy-visionaid** [comment]
@Foda Thanks for the workaround. I need something that works adaptively to system settings and theme changes, but I'm sure I can come up with something from there. 👍

**Comment by samhouts** [comment]
Confirmed that this regressed between https://github.com/dotnet/maui/compare/8.0.0-preview.3.8149...8.0.0-preview.4.8333. https://github.com/dotnet/maui/pull/14517 is most sus (thanks @jeremy-visionaid!). I would think that the buttons and the bar would all be the same color, so it does look a bit weird. Also, my accent colors are now red and yellow from testing this. #hotdogstandforever

**Comment by pledi** [comment]
Before I was able to change the TitleBar Color with changing the window's `ExtendsContentIntoTitleBar` Property to true and setting the color of the `WindowCaptionBackground` Resource, now that doesnt work anymore. 

Anyone already got a workaround for changing the Titlebar Color dynamically?

**Comment by pledi** [comment]
I think this is still not fixed in RC2. 
If I start my application with the OS Theme set to Dark, I do have a black window border. 
If I start it with Light Mode, it's white. 

I do need to provide a theme switch option in my application, and therefore I need to toggle between both light and dark mode at runtime. On Xamarin I did this by setting `ExtendsContentIntoTitleBar` to true, and overriding `WindowCaptionBackground`. On RC2 on Windows 10 this results in the following: 

![window](https://github.com/dotnet/maui/assets/9287613/bdaf6bcd-fbad-4928-b886-66abc2401d6d)

So for me the Window application frame is still black (or white if I switch the OS Theme). That little box on the right it byw the Color set for `WindowCaptionBackground`, before this filled the whole frame.

**Comment by jeremy-visionaid** [comment]
@Foda I concur with @pledi, the issue remains in RC2 and this issue should be reopened. 

However, my expectations of the correct behaviour is different. For other WinUI 3 apps, the user accent does not apply to the caption buttons - and this should probably be the default behaviour for MAUI. At least it should be all one way or all another, not the current half and half of the current situation.

I can get reasonable behavior through lifecycle events (but you also need to set inactive colours and repond the theme changes), so thanks for the hints for the workaround.
