### ISSUE TITLE
What should be done to make Maui WebView renders last page instead of home page of the domain when web token expires?

### ISSUE THREAD

**Issue by udayvalluri** [dotnet/maui#17065]
### Description

Our mobile app uses Microsoft.Maui.Controls.WebView to launch a web page. The user gets authenticated when accessing this page. Once the login is successful if a user does not interact with the page for a long time, and if the token expires then the page signs out and shows a sign in, once the user signs in, web view displays the home page of the domain instead of my initial page where my token expired. How do we make sure we take the user back to the original page instead of taking the user to the home page? We want to take the user back to the page where they were when the token was expired. 

### Version with bug

7.0.92

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

**Comment by jfversluis** [comment]
Hey @udayvalluri thanks for the report! I realize it has been a while, did you figure out a solution in the meantime? Have you been able to test this with the latest versions of .NET MAUI?

If this hasn't been resolved, would it be possible to add some more details? Based on this information it's a bit hard to diagnose what might be going on here. I understand that this is also hard to put in a reproduction because there is a whole auth configuration involved.

Why do you think this might be a bug in .NET MAUI? Did you have this functionality in Xamarin.Forms and it did work there? Is this happening on one platform but does it work for the other? Maybe some screenshots of what you're seeing would help?

Thanks!
