### ISSUE TITLE
[regression/8.0.0-rc.1.9171] Grid rows aren't same height on iOS

### ISSUE THREAD

**Issue by BretJohnson** [dotnet/maui#17125]
### Description

The Issues15330 Appium test is failing now, where the grid rows for this XAML (https://github.com/dotnet/maui/blob/55d806e929bd1564cb2e159cff72db92eba55715/src/Controls/samples/Controls.Sample.UITests/Issues/Issues15330.xaml) aren't all the same height. 

Here's the chronology (copied from a Teams chat on this):

- Originally bug 15330 existed: https://github.com/dotnet/maui/issues/15330. The row heights were far off, obviously wrong.
- That was fixed on May 29. It was much better, but apparently not perfect on iOS (which we didn't notice).

- On Aug 3rd I added a screenshot for the Issue15330 test, thinking it's completely fixed. I didn't notice at the time that the row heights were still slightly off on iOS (719 pixel height first row, 723 pixels for the second row). The screenshot captured the current (slightly wrong) state.

- Then recently something changed that made it even worse (692 pixels for first row, 723 for the second row). I suspected it was Hollander's PR ([Grid distribution fix by john-hollander · Pull Request #17023 · dotnet/maui (github.com)](https://github.com/dotnet/maui/pull/17023)) that broke it, but maybe it was something else. And I see Hollander's PR was merged when UI tests were turned off (since they weren't fully working), which makes it a bit harder to tell. But it must have been a recent change.

This bug is to track the problem, so we can investigate and fix. See OKR 2.2 Teams chat for full context.

### Steps to Reproduce

See Description.

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.7.8842

### Affected platforms

iOS

### Did you find any workaround?

no

**Comment by john-hollander** [comment]
I'll take a look at this in a couple of hours, when I have a chance.

**Comment by john-hollander** [comment]
So far I've tested with Windows and Android (emulator or local) and not yet able to reproduce, even by forcing the execution to skip over the full size expansion section and enter the distribution into available space section (the section modified by https://github.com/dotnet/maui/pull/17023).

I've also run the updated code through all of the unit tests in the GridLayoutManagerTests group with the new code (the code at the time of my pull request, with the changes included, not the latest from main), and all of the tests are passing, including the ones that reach the updated section, which are:

ViewsInUnconstrainedStarColumnsDoNotOverlapWhenArrangeWidthChanges
ViewsInUnconstrainedStarRowsDoNotOverlapWhenArrangeHeightChanges
MultipleArrangeCallsProduceConsistentResults

Which are the some of the ones mentioned in the fix (https://github.com/dotnet/maui/pull/14902) for https://github.com/dotnet/maui/issues/15330.

I will test on my Mac at home when I'm able to later on.

Is this only being observed in iOS right now, or is it being observed on the Mac as well? And if anyone is able to reproduce on Windows or Android, I'd love to know the setup so I can reproduce as well.

**Comment by john-hollander** [comment]
My Mac took too long to update last night (particularly XCode), so I'll have to test that tomorrow.

I added the following to the MainPage of the MauiGridWrongRowSize project for testing:

```
protected override void LayoutChildren(double x, double y, double width, double height)
{
    base.LayoutChildren(x, y, width, height);

    if (bv1.Height != bv2.Height || bv1.Height != bv4.Height || 2 * bv1.Height != bv3.Height)
    {
        Debug.Print("Issue...");
    }

    Debug.Print($"1: {bv1.Height:0.000000000000000}, 2: {bv2.Height:0.000000000000000}, 3: {bv3.Height:0.000000000000000}, 4: {bv4.Height:0.000000000000000}");
}
```

Along with naming the BoxViews bv1, bv2, bv3 and bv4. And I copied the Grid, GridLayoutManager, CastingEnumerator, and ReadOnlyCastingList objects into the project for testing.

I tested with the current .NET 7 and .NET 8 builds. I was unable to trip the "Issue..." debug line in Windows or Android so far. I tried at 100% and 150% scale on Windows. Unfortunately I haven't had the chance to test on iOS yet, but I'll do that as soon as I am able to.

**Comment by john-hollander** [comment]
For consideration:

These two commits may also have affected the result of the above test, since they also occurred within the last week, and touch on code that was changed in the fix for the above (i.e. [Platform/iOS/ContentView.cs](https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/iOS/ContentView.cs)) and directly relate to iOS:

1. https://github.com/dotnet/maui/commit/9eb2fd370e1b5e14018fb64a4d6617871b8760c0
2. https://github.com/dotnet/maui/commit/8eaa9f1939e7a899d89a034e31e9471a98e9f5ab

I haven't done a deep dive on that code yet - just noticing the commit dates.

**Comment by john-hollander** [comment]
I'm able to duplicate the issue on iOS now, and I've spent a bit of time investigating.

I haven't found the solution yet, but the issue occurs due to inconsistent handling of the safe area for iOS. The bounds being sent to the ArrangeChildren method of the Grid Manager take the safe area into account, but the Measure method uses a height constraint that doesn't take the safe area into account (they seem to be passed through by the parent window that does not check for the safe area).

This causes one of the row's minimum heights to be set to a value that is tied to the (larger) height that doesn't take the safe area into account, but the target size for the star handlers is sent the (smaller) one that does take the safe area into account. Because of this, one of the rows has a minimum larger than 1/3 of the target size sent to the star handlers, one is consistent with it (1/3 of the target sent), and one is half of the size (1/6 of the target sent). With both expansion methods, this results in third rows that are smaller than the first two, but the old method creates a larger distance in the third row, and the new method splits the difference optimally (so the stdev of the three rows returned is smaller in the new method). In the end, the third row gets cut off in both methods by the safe area either way.

I'll investigate further on Monday.

**Comment by BretJohnson** [comment]
@john-hollander thanks for the update. I'm glad to see we're honing in on the problem. cc @hartez

**Comment by SebastianReibel** [comment]
I’ve been experiencing the same issue and I also came to the conclusion that the safe area isn’t taken into account consistently.

To get around this problem, I am currently using 
```
On<iOS>().SetUseSafeArea(true) 
```
in my base implementation of ContentPage.

This makes sure that the IgnoreSafeArea property is set to false and therefore the heightConstraint for the page is adjusted correctly.

**Comment by john-hollander** [comment]
I believe I have a solution for this, but I'll run more tests on the solution before I do a pull request for it to check everything out.
