### ISSUE TITLE
Only one of multiple DropGestureRecognizers under Android will receive the message.(.NET 8 preview 7) 

### ISSUE THREAD

**Issue by bestvcboy** [dotnet/maui#17186]
### Description

Only one of multiple DropGestureRecognizers under Android will receive the message.(.NET 8 preview 7) 
Description
If there are multiple DropGestureRecognizers under a ContentPage in Android, only one will receive the message. There is no problem under the windows environment.

### Steps to Reproduce

<Image x:Name="BoxOne" Color="Red" WidthRequest="100" HeightRequest="100">
    <Image.GestureRecognizers>
        <DropGestureRecognizer Dropped="OnBoxOneDropped" />
    </Image.GestureRecognizers>
</BoxView>

<Image x:Name="BoxTwo" Color="Blue" WidthRequest="100" HeightRequest="100">
    <Image.GestureRecognizers>
        <DropGestureRecognizer Dropped="OnBoxTwoDropped" />
    </Image.GestureRecognizers>
</Image>

private void OnBoxOneDropped(object sender, DropEventArgs e)
{
    
}

private void OnBoxTwoDropped(object sender, DropEventArgs e)
{
    
}

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by jfversluis** [comment]
This issue is quite old by now and didn't gain a lot of traction. Also, from the description I'm not really clear what the issue is here. Please try again with the latest releases and see if this is still something you encounter.

If it is, feel free to open a new issue, but please provide clear steps on how to reproduce including relevant code and ideally a [reproduction project](https://github.com/dotnet/maui/blob/main/.github/repro.md) that shows this behavior so we can quickly diagnose and hopefully fix it. 

Thanks!
