### ISSUE TITLE
MAUI Class Library cannot convert jar files.

### ISSUE THREAD

**Issue by TKumadaki** [dotnet/maui#17185]
### Description

MAUI Class Library cannot correctly convert jar files containing the following classes.

```java:Lib.java
package com.example.lib;

public class Lib {
    public String GetMessage()
    {
        return "Hello";
    }
}
```

When I convert this class, the namespace and class name are the same, so
An error will occur.

```java:Reader.java
package com.example.lib;

public class Reader {
    public boolean reader = true;

    public boolean CanRead()
    {
        return  reader;
    }
}
```

When I convert this class, the property name and class name are the same, so
An error will occur.

```java:Tree.java
package com.example.lib;

public class Tree {

    public Fruit fruit;

    public static enum Fruit {
        APPLE,
        Orange;

        private Fruit() {
        }
    }
}
```

When I convert this class, the enum names and public field names are the same, so
"warning BG8401" will occur.

I ran into these problems trying to use a jar file provided by the manufacturer that created the mobile device.

### Link to public reproduction project repository

[MauiClassLibraryError](https://github.com/TKumadaki/MauiClassLibraryError.git)

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by moljac** [comment]
@TKumadaki 

Thanks for the feedback, but this is not MAUI issue.

I have done quick-n-dirty Android bindings fix for you, both app and library build w/o issues:

[17185.zip](https://github.com/dotnet/maui/files/12507543/17185.zip)

In order to understand what I have done, you will need some reading about bindings. It is advanced and very broad topic, so do not give up. If I can do it -  everybody can do it too.

Closing this issue.

**Comment by TKumadaki** [comment]
Thank you @moljac.
I have confirmed that the error is gone with your correction.
It was very helpful.
