### ISSUE TITLE
[Android] PRISM absolute navigation changes app window and MainActivity is being recreated

### ISSUE THREAD

**Issue by DenisLaky** [dotnet/maui#17233]
### Description

During PRISM absolute navigation app main window changes and MAUI recreates MainActivity of the app. Because of that we can't set LaunchMode equals to one of that values" SingleInstance or SingleTop, SingleTask, SingleInstancePerTask. Because android app just crashes . Moreover if we use standard LaunchMode and allow app to create new activity on window change we always see splash screen background. We want to see splash screen only during app process first start.

This is caused because this [ApplicationExtensions.RequestWindow method](https://github.com/dotnet/maui/blob/c05b2a023fad4d316cf80dffcbe6a9ddfd75b0eb/src/Core/src/Platform/Android/ApplicationExtensions.cs#L24) sets these intent flags ActivityPlags.NewTask and ActivityFlags.MultipleTask together. ActivityFlags.MultipleTask causes that new activity is being created.

It is something that we don't expect and it is completely different from Xamarin.Forms behaviour. We want use single activity per app process life time.

### Steps to Reproduce

1. Create new MAUI project;
2. Add Prism framework for MAUI;
3. Add views registration;
4. Add NavigationPage with initial view;
5. Navigate to another view with absolute navigation;
6. Observe app MainActivity is recreated and splash screen background is visible during navigation;

### Link to public reproduction project repository

[Link to sample](https://github.com/DenisLaky/Issues)

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

Not use Prism absolute navigation and remove required pages from navigation stack after navigation to required page.

**Comment by DenisLaky** [comment]
@PureWeen Added link to sample

**Comment by AdrianoBinhara** [comment]
Same issue here. Any workaround for this? How can I clean the navigation stack?

**Comment by alfredotsco** [comment]
> Same issue here. Any workaround for this? How can I clean the navigation stack?

Same here, any updates?

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 1(8.0.3). Repro on Android 14.0-API34, not repro on iOS 17.0 with below Project:
[PrismIssue.zip](https://github.com/dotnet/maui/files/13556932/PrismIssue.zip)
Android:
![spalsh](https://github.com/dotnet/maui/assets/97647558/a4ed9eb2-c23d-4a52-939f-313fda428cf6)

**Comment by aqua-ix** [comment]
As of Prism 8.1.273-pre, if a page is specified using an absolute path, the screen cannot be updated due to a bug in MAUI, so the new window is started and the old one is closed.
Relevant code: https://github.com/PrismLibrary/Prism.Maui/blob/8.1.273-pre/src/Prism.Maui/Navigation/PageNavigationService.cs#L1044-L1051
Corresponding issue (resolved): https://github.com/PrismLibrary/Prism/issues/2833

When you execute MAUI's OpenWindow method, the Activity is started with ActivityFlags.NewTask, so when you change the screen using an absolute path, the history appears to be continuous.
Relevant code: https://github.com/dotnet/maui/blob/c05b2a023fad4d316cf80dffcbe6a9ddfd75b0eb/src/Core/src/Platform/Android/ApplicationExtensions.cs#L24

However, the latest version of Prism code does not include the process to open the new window, so the problem has been resolved in .NET 8 and later (it will be resolved by upgrading Prism to latest version).
https://github.com/PrismLibrary/Prism/blob/master/src/Maui/Prism.Maui/Navigation/PageNavigationService.cs#L1049
