### ISSUE TITLE
iOS, Android Border calculates it's size in a wrong way

### ISSUE THREAD

**Issue by StanislavIlchenko** [dotnet/maui#17275]
### Description

**Android** border takes width more than screen size
![image](https://github.com/dotnet/maui/assets/141010748/1206c5ab-180a-45e7-baf1-17c0e0b4da2c)

**iOS** border takes whole screen height and width is more than screen size
![MicrosoftTeams-image (2)](https://github.com/dotnet/maui/assets/141010748/f72cb73c-780c-4f90-9b84-4f890f51f6c9)

**Widnows** border takes size based on it's content
![image](https://github.com/dotnet/maui/assets/141010748/39a67c99-5db1-4826-80cf-e8c313670892)

### Steps to Reproduce

1. Use https://github.com/StanislavIlchenko/MauiIosFrameContentBug repo
2. Switch to LanguageChangeTest branch
3. Run app on Windows/Android/iOS (iOS has other exception but result the same - application closes)
4. On appearing screen tap on purple rectangle
![image](https://github.com/dotnet/maui/assets/141010748/185fe74c-6a42-4955-8be1-4c4308edf46a)

### Link to public reproduction project repository

https://github.com/StanislavIlchenko/MauiIosFrameContentBug

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Windows10.0.19041.0, Android 11 API 30, iOS 16.1.2

**Comment by drasticactions** [comment]
https://github.com/StanislavIlchenko/MauiIosFrameContentBug/blob/LanguageChangeTest/CollectionViewPopupTest/Pages/Popups/CollectionViewPopup.xaml#L6

You're putting a width and height on the border, and as far as I can tell the caluclations on each platform are correct for the settings you provided. The iOS screenshot is overshooting the sides because the width is smaller than the one you specifically set. Likewise on Android and Windows. Those seem to be reflective of what you're telling the code to do. Are you trying to do proportial layout for the screensize? If you are, you may not want to use hardcoded values like that.

CC @hartez
