### ISSUE TITLE
CollectionView can't show all items

### ISSUE THREAD

**Issue by StanislavIlchenko** [dotnet/maui#17274]
### Description

When I try to show popup with CollectionView inside CollectionView contains only first element
![image](https://github.com/dotnet/maui/assets/141010748/8be888c8-48b9-480d-a1aa-a9d75064bcaa)

### Steps to Reproduce

1. Use https://github.com/StanislavIlchenko/MauiIosFrameContentBug repo
2. Switch to LanguageChangeTest branch
3. Run app on Windows/Android/iOS (iOS has other exception but result the same - application closes)
4. On appearing screen tap on blue rectangle
![image](https://github.com/dotnet/maui/assets/141010748/fab89c2b-13f6-40a9-8cf8-933ffd4fb4fb)

### Link to public reproduction project repository

https://github.com/StanislavIlchenko/MauiIosFrameContentBug

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows10.0.19041.0, Android 11 API 30, iOS 16.1.2

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
I think the issue here may be your code

https://github.com/StanislavIlchenko/MauiIosFrameContentBug/blob/LanguageChangeTest/CollectionViewPopupTest/Pages/Popups/LanguageSelectPopup_CollectionView.xaml#L23

You have the Image on the same column as the text, and that's breaking the underlying elements. You can see in the Live Visual Tree that the elements are at least represented in the view.

![image](https://github.com/dotnet/maui/assets/898335/016a5dc7-310e-4be3-bece-c0621e28704d)

If you change the Column on Image to `0`, it should work.
