### ISSUE TITLE
Click events not working in Blazor Hybrid since Preview 7

### ISSUE THREAD

**Issue by danielchalmers** [dotnet/maui#17375]
### Description

I have a Blazor Hybrid app that builds for Android and Windows, and since Preview 7, button clicks don't work on either of them. Preview 6 and earlier worked perfectly.

Adding a simple non-MudBlazor button and using the @onpointer event as mentioned here https://github.com/dotnet/maui/issues/16875 doesn't seem to work either.

Sorry if I've missed something obvious.

### Steps to Reproduce

1. Clone project repository
2. Debug Windows Machine
3. Try clicking any button on the app

### Link to public reproduction project repository

https://github.com/danielchalmers/JournalApp

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

Android, Windows

**Comment by danielchalmers** [comment]
Ok after having this issue for over a month it randomly started working again after updating to Visual Studio 2022 version 17.8 Preview 2 (???).

I don't know if you want to investigate this or consider it sorted so I'll leave the issue open for now but feel free to close.

**Comment by Eilon** [comment]
Hi @danielchalmers this sound suspiciously like a bug in .NET 8 Preview 7 (specifically that exact release) that has since been fixed in .NET 8 RC1 that was released this week. In your repro it says you were using .NET 8 RC1, but maybe you still had some kind of reference to .NET 8 Preview 7, which had this bug?

Either way, it sounds like this issue isn't happening anymore, so I'm inclined to believe that was the case, and this issue can be closed.

**Comment by danielchalmers** [comment]
@Eilon I did have `8.0.100-rc.1.23455.8` in my global.json and the SDK installed but it's totally possible that there was something leftover. Either way at least it works now!

**Comment by Eilon** [comment]
Thanks again @danielchalmers I'm glad you got it working. Please do let us know if you encounter any new issues!
