### ISSUE TITLE
[Bug] Changing the default template icon names in the Resources folder breaks the WinUI deployment

### ISSUE THREAD

**Issue by pjmagee** [dotnet/maui#1742]
### Steps to Reproduce

1.  Change names from appicon.png / appiconfg.png / appicon.ico 
2. The generated icons for the Assets folder are generated correctly
3. The WinUI package manifest values are not updated, meaning the packaging fails because it is looking for the default names
4. Updating the values in the `.csproj` file like `<MauiImage />` etc does not fix the problem.`

### Expected Behavior

When changing the names with the `<Maui*` MS Build Tasks - It should be aware of the WinUI manifest and images used in side that, since Maui is controlling the WinUI deployment and it should update those references too. The Maui tasks should let you pass in custom names of images, right now it doesnt let you change them there, without also having to manually change the WinUI package manifest. 

### Actual Behavior

It does not update them, so you must manually change those references. 

### Workaround

in the WinUI Manifest file based on what the Maui MSBuild tasks generate for each of the images it generates for the app (splash screen, main app icon, etc etc) by looking at the Assets generated,  manually update the manifest accordingly.

**Comment by VincentBu** [comment]
Hi @pjmagee , here is how I change name of default template icon names:
1. create a blank maui app
2. rename `appicon.svg` with `appicon1.svg` in Solution Explorer, Visual Studio should update project file for you
![image](https://user-images.githubusercontent.com/44959937/156977201-936a89c9-38ad-40bd-b113-002bdc639381.png)
![image](https://user-images.githubusercontent.com/44959937/156977446-8d67ab77-aecc-4b10-b324-69f83472c6cd.png)
3. build and run.

This approach works for me currently. Feel free to point out if there is anything doesn't make sense in my repro steps

**Comment by mattleibow** [comment]
This is actually by design as well as the fact that the build did nothing. It does something now, but still by design.

The values in the manifest _always_ override any generated values. The build process does not update the manifest. In preview 14 we added a feature to generate more of the manifest - including the app icon things. However, this is a new and separate feature to updating the manifest.

What is in the manifests/plists for any of the platforms _always_ override the generated and automatic values. If you don't want to hardcode a value in the manifest, then you an remove it and let the compiler insert it at build time. But this will happen as part of the build and not update the file on disk.
