### ISSUE TITLE
Label with TextType="Html" will crash on Windows if html is invalid.

### ISSUE THREAD

**Issue by DaveNatalieTripArc** [dotnet/maui#17457]
### Description

I have a Label, and I am trying to bind the Text property to some simple HTML. When the html is invalid, it causes my app to crash with no details or error message.

I believe this to only be an issue on Windows.

### Steps to Reproduce

Create a Label and set the `TextType` property to `Html`. Bind the label's Text property to a string value that contains invalid HTML

For example, try using HTML that doesn't have a proper end tag.

```
string html = "<h1>Hello World<h1>";
```

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net8.0-windows10.0.19041.0

**Comment by drasticactions** [comment]
It's caused by https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/Windows/TextBlockExtensions.cs#L122

There's a wrapper around XML Reader to try and parse the HTML into elements. If it fails on an exception, it calls on Windows to parse the HTML into text, which fails since it's not valid. As far as I can tell, it's a native crash, so no exceptions.

https://github.com/dotnet/maui/pull/17470
