### ISSUE TITLE
[Bug] JAVA_TOOL_OPTIONS breaks Java output parsing

### ISSUE THREAD

**Issue by errorx666** [dotnet/maui#1748]
### Description

Having the `JAVA_TOOL_OPTIONS` environment variable causes `java` stdout parsing to fail.

### Steps to Reproduce

1. Start Visual Studio 2022 Preview 2 with the `JAVA_TOOL_OPTIONS` variable set to any value.
2. Try to compile a MAUI Preview 6 project for Android.

### Expected Behavior

Compile succeeds.

### Actual Behavior

Cannot detect Java version, unexpected output from `javac`.

### Basic Information

- Version with issue: MAUI Preview 6
- Last known good version: N/A
- IDE: Visual Studio 2022 Preview 2
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: N/A
  - UWP:  N/A
- Android Support Library Version: 
- Nuget Packages: N/A
- Affected Devices: N/A

### Workaround

Unset `JAVA_TOOL_OPTIONS` environment variable

**Comment by VincentBu** [comment]
Here are the repro steps:
1. open Developer PowerShell for VS 2022
2. in the powershell window, run `$env:JAVA_TOOL_OPTIONS="-agentlib:hprof"`
3. run `devenv.exe`
4. compile a MAUI Preview 6 project for Android

**Comment by Redth** [comment]
@jonpryor could your team please have a look at this?

**Comment by jonpryor** [comment]
This was *partially* fixed with https://github.com/xamarin/xamarin-android/commit/a0d83441d4f1d842508b76bfd2244269fb74da60 , and the fix should be present in any 2022 .NET 6 preview release of MAUI.

However, it's only "fixed" in that if `JAVA_TOOLS_OPTIONS` is set, we'll ignore "extra" lines of `javac -version` output in order to properly extract the version number.

This should fix @errorx666's original issue.

*However*, there is still an implicit requirement that the `javac -version` command *actually run* and not error out, which in turn requires that `JAVA_TOOLS_OPTIONS` be valid.

For example:

```bash
$ export JAVA_TOOL_OPTIONS="-this-is-garbage"
$ javac -version
Picked up JAVA_TOOL_OPTIONS: -this-is-garbage
Unrecognized option: -this-is-garbage
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Which is where @VincentBu's [comment](https://github.com/dotnet/maui/issues/1748#issuecomment-1055153732) comes in: `-agentlib:hprof` may cause the app to exit!

```bash
$ export JAVA_TOOL_OPTIONS="-agentlib:hprof"
$ javac -version
Picked up JAVA_TOOL_OPTIONS: -agentlib:hprof
Error occurred during initialization of VM
Could not find agent library hprof on the library path, with error: dlopen(libhprof.dylib, 0x0001): tried: '$HOME/android-toolchain/jdk-11/lib/server/./libhprof.dylib' (no such file), '$HOME/android-toolchain/jdk-11/lib/server/../libhprof.dylib' (no such file), '$HOME/android-toolchain/jdk-11/bin/../lib/jli/libhprof.dylib' (no such file), 'libhprof.dylib' (no such file), '/usr/lib/libhprof.dylib' (no such file), '$CWD/libhprof.dylib' (no such file)
```

So… Don't Do That™.  `JAVA_TOOL_OPTIONS` must be a valid value which doesn't cause `java`/`javac`/etc. to immediately exit with an error.

(Aside: the alternative solution would be for the .NET 6 + Android build system to *clear* the `JAVA_TOOLS_OPTIONS` environment variable.  This would allow "unsupported" or "garbage" values to be present in the environment variable without breaking the build process.  However, this also means that if anyone sets `JAVA_TOOLS_OPTIONS` in order to attempt to mitigate security issues -- such as Log4Shell and a suggestion at the time to disable trustURLCodebase -- then we'd be *removing* the ability to apply those mitigations.)
