### ISSUE TITLE
[regression/8.0.0-rc.1.9171] Grid * Row is broken on iOS

### ISSUE THREAD

**Issue by arahmancsd** [dotnet/maui#17581]
### Description

This is the same issue #15968 

On iOS Grid Rowdefinitions with * size take up the whole screen.

`<Grid RowDefinitions="*,auto" />
`
everything placed in the auto row is below the end of the screen.

This is currently working in  7.0.92

### Steps to Reproduce

1. Change the repo to .net 8.0
2. run it in ios

### Link to public reproduction project repository

https://github.com/arahmancsd/MauiGridRow

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

```
<OnPlatform x:TypeArguments="View">
        <On Platform="iOS">
            <FlexLayout Direction="Column">
                ....
            </FlexLayout>
       </On>

       <On Platform="Android">
           <Grid RowDefinitions="*,Auto">
              ...
           </Grid>
      </On>
</OnPlatform>
```

**Comment by Jt-damien** [comment]
I am also having the same issue since updating to .NET 8. .NET 7 works fine.

**Comment by Redth** [comment]
I'd like to make sure we understand the issue here.  Could you please describe what you expect to happen compared what's in the video I captured of it running on .NET8 RC1 below?

https://github.com/dotnet/maui/assets/271950/afbfb187-4387-41ab-ad5f-b0573377caf8

Looking at the code I believe this is displaying correctly.  The bottom-most button with the text "Test" shows in the bottom of the view, the scrollview is measuring large enough to hide the "Where is the button" button because of the border it is contained in which is sized to 1000 height.

If you can add more information about what isn't working correctly that would be helpful, thanks!

**Comment by arahmancsd** [comment]
Hi @Redth Thanks, I updated the repo to easily spot the issue in iOS.

The shell has two tabs. The issue is in the first tab (MainPage).

Please use this repo => https://github.com/arahmancsd/MauiGridRow

**Comment by Redth** [comment]
Thank you!  The updated sample is helpful.

Here's the updated sample on net7.0 which appears to be working more correctly, so I think it's fair to call this a regression still.

<img width="467" alt="Screenshot 2023-10-24 at 4 20 00 PM" src="https://github.com/dotnet/maui/assets/271950/fd1b70c5-865e-4f71-b755-3086d67d7958">

**Comment by arahmancsd** [comment]
@Redth does it mean it will not be addressed in GA (Nov 2023)?

**Comment by Redth** [comment]
Tested this with [Nightly](https://github.com/dotnet/maui/wiki/Nightly-Builds) build version `8.0.4-nightly.9705` and it looks like it is working correctly, which should be due to some SafeArea fixes that have since been made:

![Simulator Screenshot - iPhone 15 - 2023-12-05 at 13 33 58](https://github.com/dotnet/maui/assets/271950/b71a1cdb-03b8-4209-b2fb-2d0a3c0156a6)

This means that SR1 should be working as expected in this scenario.

**Comment by arahmancsd** [comment]
Thanks, @Redth this is working as expected in dotnet 8 GA.
