### ISSUE TITLE
[regression/8.0.0-rc.1.9171] [Android] DisplayAlert modal background is not darken

### ISSUE THREAD

**Issue by NXDMN** [dotnet/maui#17708]
### Description

When calling `DisplayAlert` on `Page`, the page beneath the popup modal will not be darken, it used to work in MAUI version 7.0.92, I never try on .NET 8 Preview

### Steps to Reproduce

1. Create a new .NET 8 MAUI project
2. Call DisplayAlert in a Page

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

7.0.92

### Affected platforms

Android

**Comment by samhouts** [comment]
I checked this on both NET 7 and NET 8 with an API 34 emulator, and the alert has a shadow now instead of just darkening the whole page like a modal.

I tested again on both NET 7 and NET 8 with an API 33 emulator, and the screen darkens like a modal.

This appears to be a design change in Android 14/API 34 itself, and it is expected. It it not caused by .NET MAUI.
