### ISSUE TITLE
Project is not compatible with net8.0 (.NETCoreApp,Version=v8.0)

### ISSUE THREAD

**Issue by Jocrod1** [dotnet/maui#17791]
### Description

Can't do Unit Tests because it says the xUnit Project is not compatible

### Steps to Reproduce

try to run tests

### Link to public reproduction project repository

https://github.com/Jocrod1/MauiProjWTests

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

I was *not* able test on other platforms

**Comment by drasticactions** [comment]
Your repository link 404s, I think it's private?

**Comment by Jocrod1** [comment]
i accidentally uploaded the repo in private. It's now public.

**Comment by drasticactions** [comment]
Thank you!

I believe the error is correct:

https://github.com/Jocrod1/MauiProjWTests/blob/master/TestsProj/TestsProj.csproj#L4

https://github.com/Jocrod1/MauiProjWTests/blob/master/MauiProjWTests/MauiProjWTests.csproj#L4

The XUnit project is `net8.0`. MAUI UI Single Project files reference individual platforms (`net8.0-android`, etc). You're trying to reference that project inside a non platform specific project, which won't work. It's not a MAUI issue, it's how Target Frameworks operate. You would hit similar issues if you were trying to reference `net8.0-android` class libraries inside a `net8.0` XUnit project.

If you're trying to do UnitTests on non-UI parts of your code, I believe the best thing to do would be move them into another class library that's not platform specific (`net8.0`, `net7.0`, `netstandard2.0` etc) and reference that instead. Otherwise, you would need to set up a device test runner and run them on the actual platform. 

CC @BretJohnson @PureWeen  is there anything else they could do? I know there's a bunch happening right now in the repo with XUnit and device testing.
