### ISSUE TITLE
iOS Crashing when navigating pages / memory leak with imageSource/CollectionView.

### ISSUE THREAD

**Issue by mla03** [dotnet/maui#17790]
### Description

In the linked sample, we have two pages, the starting JobPage which creates a "job" and saves it in the Database, if not already created. Pressing the button will Navigate the user to the PhotoPage, where photos can be added from Camera or Gallery. The Photos information is also saved in the DB, and is "linked" to the "Job" with a JobGuid. Everytime the PhotoPage is navigated to, the photos informations are fetched from the DB, and a CollectionView on the PhotoPage is showing the images. 

When adding photos to the "Job" and navigating back and forth between the JobPage and the PhotoPage, around 10-20 times, the photos starts to turn white, and suddenly the app is terminated. This only occurs on iOS, tested on iPadOS 16.6.1 Ipad Air 5th Gen. 
We have also tested on emulators, where the emulator will freeze instead of terminating the app. 

On Android it works fine. 

We have been strugling with this Issue since .NET 7, and upgraded to .NET 8, because we saw alot of memory leak issue was solved, but this issue still persist. 

### Steps to Reproduce

- Run the linked sample. 
- A db is created upon startup, and a "Job" is created when JobPage is loaded. 
- Press the button and go to PhotoPage.
- Add 8-12 Photos mix of Gallery and Camera.
- Navigate back and forth between JobPage and PhotoPage until app crashes.
- Photos will start to turn white, and after few more navigations the app will get terminated. 

### Link to public reproduction project repository

https://github.com/mla03/MauiPhotoPagePOC

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.6.1

### Did you find any workaround?

No.

### Relevant log output

```shell
System.InvalidOperationException: Unable to load image file.
   at Microsoft.Maui.FileImageSourceService.GetImageAsync(IFileImageSource imageSource, Single scale, CancellationToken cancellationToken)
The app has been terminated.
Error: Garbage collector could not allocate 16384u bytes of memory for major heap section.
```

**Comment by drasticactions** [comment]
I think part of the issue is how you've implemented your ViewModels and Navigation.

https://github.com/mla03/MauiPhotoPagePOC/blob/main/POCPictureGallery/Pages/PageServiceConfigurator.cs#L15-L16

You've set your Pages to be Transient. That means they will be recreated every time you navigate to one; for your `PhotosPage` you are creating both the Page and ViewModel every single time it loads. The Photos Page and ViewModel do not get disposed when you navigate back (you're at the whim of the GC at this point), so you're making new pages and VMs every time you move.

If you change this to be Singletons, that alone should address a major memory issue.

```csharp
        public static MauiAppBuilder ConfigurePages(this MauiAppBuilder builder)
        {

            builder.Services.AddSingleton<JobPage>();
            builder.Services.AddSingleton<PhotosPage>();
            return builder;
        }
```

Likewise, checking on Android and looking at the memory counts between moving pages, it does ever increase as it does on iOS. You're not seeing issues because, depending on how much RAM you have on your Android device, you're probably less likely to notice it getting higher until later. iOS devices also, traditionally, have lower ram and tighter memory restrictions.

**Comment by mla03** [comment]
Thanks for pointing out the Singleton vs Transients. 

I have changed the sample code to Singletons for both the ViewModels and Pages, and it seems to make a difference. 
Before adding 10 photos and navigating 10-15 times the app crashed. 

Now I cannot get the app to crash, but after navigating 30-40 times photos starts to randomly turn either white or black? 
But no errors to see in the console/log. 

 David Ortinau linked me this in mail: https://github.com/dotnet/maui/wiki/Memory-Leaks
 But I cannot seem to get that up and running on either our macbook or my windows pc, to profile the iPad Memory.

**Comment by fischberg** [comment]
While Singleton may work in mla03's case, I can't use Singletons because the contents of my pages change each time I need to render them. Each time I navigate to a page and then pop it from the stack, the memory isn't freed...EVER (at least not after 10+ iterations of displaying a page and calling GC.Collect()). On Mac Catalyst, the memory leak is minor. On iOS it's catastrophic. The app crashes after rendering a page 5 times on a real device. On an iPhone simulator, RAM usage grows about 100MB each time a page is created. I haven't yet tried on Windows. I too waited for .NET 8 hoping it fixed the issue. The 5 month delay didn't yield any love.

I tried replacing CollectionView with a ScrollView containing a VerticalStackLayout. I added all the Children to the VerticalStackLayout using a foreach loop in C# (instead of using a CollectionView in xaml). Performance was unacceptable and memory usage was astronomical (50x higher than using CollectionView). I observed the same behavior of no memory being freed when I popped the page off the navigation stack.

**Comment by AdamEssenmacher** [comment]
MAUI has a systemic issue where a leak in _any_ element will grow to consume its containing page and (quite possibly) associated binding contexts (i.e. view models) as well.

As far as I can tell, this issue affects _all_ platforms. However, it is much more likely to manifest itself on iOS due to native ref-counting memory management.

@mla03 I'm working on a project that addresses this issue: https://github.com/AdamEssenmacher/MemoryToolkit.Maui

If it works as intended, it may mitigate or entirely eliminate your issues with as little as one line of XAML per affected page.

**Comment by jaosnz-rep** [comment]
Verified this issue with Visual Studio Enterprise 17.10 Preview 1.0, can repro on iOS platform with sample project. 
https://github.com/mla03/MauiPhotoPagePOC

**Comment by GUELIANEBelkacem** [comment]
Any news on this issue? 
I have the same problem and after 10 photos or so some of our customer are reporting crashs on older iPads, along with the white/black photos

**Comment by XonyON13** [comment]
> Any news on this issue? I have the same problem and after 10 photos or so some of our customer are reporting crashs on older iPads, along with the white/black photos
I have update Microsoft.Maui.Controls and Microsoft.Maui.Controls.Compatibility NuGets to 8.0.40 version (it is include some memory leak fix related to ImageSource and CollectionView) and our app now more reliable. Some leaks still exists just probably related to other controls. 

Try to update related MAUI NuGets to 8.0.40 version and verify how it is going
https://github.com/dotnet/maui/releases/tag/8.0.40
