### ISSUE TITLE
TranslateTo Animation is not working on Samsung Android tablet 

### ISSUE THREAD

**Issue by joaodarocha1** [dotnet/maui#17815]
### Description

Animation is not working on Samsung sung Galaxy Tab S7+. It is working on my Samsung Galaxy S23, and on the android emulator.

The visual element just gets moved to the position without respecting the animation length. I've attached a sample project and a video with the two devices.

await MovingSquare.TranslateTo(MovingSquare.TranslationX, MovingSquare.TranslationY - 100, animationTime, Easing.Linear);

The same issue exists in .net 8 preview.

### Steps to Reproduce

Sample application, video, and software information is attached.
[MauiApp1.zip](https://github.com/dotnet/maui/files/12798510/MauiApp1.zip)
![20231003_215914](https://github.com/dotnet/maui/assets/48954066/de84fba6-bdd8-43ca-bec6-d9eb100444a2)

https://github.com/dotnet/maui/assets/48954066/94ab0fbe-fc9e-4e23-ac98-2fc6788ecc25

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

No

**Comment by vallgrenerik** [comment]
I got the exact same issue! 
This issue must also be related : https://github.com/dotnet/maui/issues/7632

Devices where it doesn't work:
* Samsung Galaxy S20 FE 5G

Devices where it works:
* Samsung Galaxy S10E
* Samsung Galaxy S23 Ultra

(It also works on all emulators)
On iOS, it works both on simulators and physical devices. 

I've compared the devices but can't find anything hardware-wise that should impact this issue:
https://www.devicespecifications.com/en/comparison/4520217bb3

The author from https://github.com/dotnet/maui/issues/7632 claims that the issue gets resolved when he did a factory reset of his device.   
That does not call for hardware issue right? 

I'm currently migrating a existing a Xamarin.Forms application to MAUI, and since the LayoutTo method is broken in MAUI (https://github.com/dotnet/maui/issues/15439) we are pretty much blocked by this. 
In Xamarin.Forms, both the LayoutTo and TranslateTo method works.

I use the TranslateTo-method and it is not respecting the animation length. 
TranslateTo is not correctly awaited, it goes directly goes to the "final" value.

**Comment by vallgrenerik** [comment]
@jsuarezruiz 
Any idea why this is happening on some devices and not others?

**Comment by HubbleCommand** [comment]
I though I encountered this bug. However I turned off battery saving mode and the animations did play. Pretty cool that MAUI actually does this.

**Comment by vallgrenerik** [comment]
> I though I encountered this bug. However I turned off battery saving mode and the animations did play. Pretty cool that MAUI actually does this. Strange though as #17287 isn't merged.

Interesting! I did have battery saving on, on the device where it didn't work.
I can't test this right now, I did go with a blazor webview instead 😊

**Comment by joaodarocha1** [comment]
@HubbleCommand you are correct. @vallgrenerik I tested the animations on the Samsung Galaxy Tab S7+ with the battery-saving feature turned off, and they worked correctly. I presume this is a feature, not a bug. It is very misleading and lacks documentation.
