### ISSUE TITLE
Only first item in CollectionView is visible if ItemTemplate have multibinding

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#17856]
### Description

Only first item in CollectionView is visible if ItemTemplate have multibinding. If the multibinding Label is commented out than all the items in the ItemSource are visible in CollectionView. 

### Steps to Reproduce

Run the reproduction sample with and without commenting out the timeLabel in CollectionView ItemTemplate. 

### Link to public reproduction project repository

https://github.com/HobDev/DotNet8MauiBugs/tree/MultiBindingCollectionViewIssue

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

Use multiple labels instead of multibinding on one label.

**Comment by jsuarezruiz** [comment]
You are creating the `timeLabel` outside of the ItemTemplate. So, this will create a single instance and will try to reuse it in every cell. Moving the Label inside the template fixes any possible issues (only see a single item, even a possible crash because the parent already has been assigned). 
<img width="867" alt="Captura de pantalla 2023-10-06 a las 14 15 35" src="https://github.com/dotnet/maui/assets/6755973/c3d39fca-3ea0-46a4-9b5d-429f0d3e89b9">

**Comment by HobDev** [comment]
The issue has been fixed after moving the Label inside the ItemTemplate of the CollectionView. After this issue is solved I can say that .NET 8 is a quality release. Lots of issues that were in .NET 7 has been fixed.

**Comment by HobDev** [comment]
Closing this.
