### ISSUE TITLE
Where/how to indicate Win platform already use PublishReadyToRun

### ISSUE THREAD

**Issue by jingliancui** [dotnet/maui#17905]
### Description

https://github.com/dotnet/maui/pull/9357

https://github.com/dotnet/maui/blob/ff50be2f541a7eef49243c4d23c4615db20fc581/src/Workload/Microsoft.Maui.Sdk/Sdk/Microsoft.Maui.Sdk.Before.targets#L7

I know code base already contains this change, but I curious on how to know it's really use r2r after I publish. 
Is ILSPY the tool that can not to decompile the dll? But dll from the release folder can be decompiled.

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

**Comment by jonathanpeppers** [comment]
What is the question? "How do I tell if ReadyToRun is on or not?"

If you look at a `.binlog`, you can see tasks named `ReadToRun` taking a lot of time. https://aka.ms/binlog

You can also compare if you turn it off:

```xml
<!-- Probably don't want to do this permanently, just for testing -->
<PropertyGroup>
  <PublishReadyToRun>false</PublishReadyToRun>
</PropertyGroup>
```

The app should be slightly smaller and start significantly slower if it is off.

**Comment by jingliancui** [comment]
@jonathanpeppers thanks, so does it mean that we still can use ILSPY to decompile it despite we use r2r to comiple tha app? As I know r2r should equal native aot, so dll should be compiled to machine code and it should not be decopiled, is that right?

**Comment by jonathanpeppers** [comment]
@jingliancui no, I think you can still use ILSpy. There is just "additional stuff" embedded in the `.dll` that improves startup performance. ReadyToRun is *like* AOT, but not the same.

NativeAOT is quite different than ReadyToRun. I do not believe you can currently run a WindowsAppSDK app on NativeAOT:

* https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=net7%2Cwindows

Since MAUI sits on top of WindowsAppSDK, it is in the same boat. There is an experimental feature to run iOS apps on NativeAOT in .NET 8, but I don't offhand know if they tried a MAUI app yet or just `dotnet new ios`.

There is also a third flavor of AOT: Mono's AOT. This is used for Release builds on iOS and Android.

I think that answers the question, but let me know if you have others. Thanks!

**Comment by jingliancui** [comment]
great answer, thank you so much
