### ISSUE TITLE
Windows .NET MAUI App throws Exception when closing second window

### ISSUE THREAD

**Issue by jingliancui** [dotnet/maui#17909]
### Description

sorry to repeat this issue again, but multi windows is important in my app, I'm not sure why #12956 was closed, but I still meet this bug with the latest maui sdk on windows platform now.

### Steps to Reproduce

1. run the app
2. click the new window button
3. use mouse click the content of the new window
4. use mouse close the new window
5. repeat step 2 - step 4

### Link to public reproduction project repository

https://github.com/jingliancui/MAUIWindowsCloseIssue

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

7.0.92

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

### Did you find any workaround?

no, If I install the latest windowsappsdk nuget, the app can not be compile.

**Comment by jingliancui** [comment]
Hi @samhouts , do you know the timeline of this fix? thanks.

**Comment by jingliancui** [comment]
https://github.com/jingliancui/MAUIWindowsCloseIssue

**Comment by samhouts** [comment]
Yep, your sample crashes, but it takes a lot more to make it crash than the original issue.

**Comment by drasticactions** [comment]
@jingliancui I believe your issue is unrelated to MAUI... kind of.

The issue you referenced was fixed; it was for how WebView handlers were disposed of. That was put into net7.0 and net8.0, and that code is OK. Your issue is WinUI. The version of WinUI used in MAUI for net7.0 is `1.2.221209.1`. There were fixes in WinUI to handle the access violation error you're seeing, but because WinUI is pinned to that version, you are not seeing, I think, every fix.

If you bump MAUI to net8.0. you will get a newer version of WinUI by default that containes these fixes. If you want to keep using net7.0, you can try including a newer WindowsAppSDK.

```
	<ItemGroup  Condition="$(TargetFramework.Contains('-windows'))">
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.3.230724000" />
	</ItemGroup>
```

I tried this and it should work, but note that updating the WindowsAppSDK out of step with the one in MAUI can produce other issues.

**Comment by jingliancui** [comment]
Hi @drasticactions , thanks your solution, but it doesn't work, still keep crashing.
I just update the repo, you can check out the code to check.

**Comment by jingliancui** [comment]
do I need to install the 1.3.230724000 sdk on my pc? I remember I only update the sdk to 1.4xxxx last night.

**Comment by drasticactions** [comment]
> do I need to install the 1.3.230724000 sdk on my pc? I remember I only update the sdk to 1.4xxxx last night.

No, The Windows SDK and the Windows App SDK are two different things. You did the right thing in your code. Unfortunately, checking again with what I told you for net7.0, yeah, I could get it to crash again, but I'm still not totally convinced this is a MAUI bug in net7.0.

That PR you referenced was for WebView. If you remove the WebView and open and close multiple windows, eventually, you would get that access exception. The WebView issue was fixed, your issue is different. Trying it in net8.0 again to be sure, and I could not get it to crash there at all. There may have been other code changes in MAUI to fix that, or the WinUI Bump since that's, again, on a newer version.

I would try running it with MAUI net8.0 and see what you get.

**Comment by jingliancui** [comment]
Thanks your response.
No rush, my pc'disk almost full, I cannot install vs preview, so I'll wait it untill vs automatically update to the 8.0 stable version.
If you guys tested it fine in 8.0, feel free to close this issue. 
Thanks.

**Comment by ninachen03** [comment]
Verified on Version 17.10.0 Preview 1.0 &17.9.2 it works fine on my side.

**Comment by jingliancui** [comment]
Yes can close this issue as now no crash anymore. Thanks
