### ISSUE TITLE
Application crash when restoring multiple windows on Mac Catalyst

### ISSUE THREAD

**Issue by torfluor** [dotnet/maui#18093]
### Description

On Mac Catalyst the OS remembers the window layout and tries to restore the windows on next launch. This might for instance happen on a crash. On MAUI 7 this would lead to multiple versions of the app being opened in the windows or in my case extra black windows. This was reported in #10939 

After upgrading to MAUI 8 the app now crash with the following exception:

```
Exception has occurred: System.InvalidOperationException
Window was already created
    at at Microsoft.Maui.Controls.Window.Microsoft.Maui.IWindow.Created()
    at at Microsoft.Maui.LifecycleEvents.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__2_0(UIWindow window)
    at at Microsoft.Maui.MauiUISceneDelegate.<>c__DisplayClass4_0.<WillConnect>b__1(OnPlatformWindowCreated del)
    at at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[OnPlatformWindowCreated](IServiceProvider services, Action`1 action)
    at at Microsoft.Maui.MauiUISceneDelegate.WillConnect(UIScene scene, UISceneSession session, UISceneConnectionOptions connectionOptions)
    at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:58
    at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:94
    at TestApp.Program.Main(String[] args) in /Users/tor/dev/TestApp/TestApp/Platforms/MacCatalyst/Program.cs:14
```

This will happen on every launch after the issue has occurred leaving the application unusable.

### Steps to Reproduce

1. Create a MAUI 8 Catalyst application that opens an extra window
2. Run the application and open the extra window
3. Stop the application from the debugger simulating a crash
4. Start the application and see that the application crash with the InvalidOperationException

If the app starts normally, retry steps 2 -4. In my experience it might take a couple tries before the error occurs.

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Mac Ventura 13.3

### Did you find any workaround?

I have tried adding the following workaround to App.xaml.cs as proposed in #10939, but it had no effect

```
protected override Window CreateWindow(IActivationState activationState)
    {
        if (Application.Current.Windows.Count > 0)
            Application.Current.CloseWindow(Application.Current.Windows.FirstOrDefault());
```

The only way I was able to launch my application was to change UIApplicationSupportsMultipleScenes to false in Info.plist, run the app, stop the app, and change UIApplicationSupportsMultipleScenes back to true.
I can do that in the development environment, but a customer will not and will have to reinstall the application.

**Comment by drasticactions** [comment]
If you want to clear the multiple window instances before the app launches, you would need to clear the saved state of the scene delegates, Ex. https://github.com/dotnet/maui/issues/17841#issuecomment-1749132951
Doing this should force only the original App.cs Window to load. As the original bug you linked to mentions, the design of scene delegates in iOS and Catalyst is to restore all of your open Windows when an app gets forced closed.

To workaround your crash, you can override `CreateWindow` in `App.cs` https://github.com/drasticactions/MauiRepros/blob/main/MauiSceneDelegateTest/App.xaml.cs#L4-L18

```csharp
public partial class App : Application
{
	public App()
	{
		InitializeComponent();

		// MainPage = new AppShell();
	}

    protected override Window CreateWindow(IActivationState activationState)
    {
		// Workaround for https://github.com/dotnet/maui/issues/18093
		// Create a Window by overriding CreateWindow and don't use the Single MainPage instance.
        return new Window(new AppShell());
    }
}
```

It's crashing because of

https://github.com/dotnet/maui/blob/0f764ac98e1a0e0e31b797ec991f8bba896a7c9c/src/Controls/src/Core/Window/Window.cs#L491

I believe that, by using the `MainPage` syntax as used in the MAUI Template, it's trying to recreate the same Window multiple times, causing this code to get hit. When creating it yourself by using the override, that does not happen. CC @PureWeen.

**Comment by torfluor** [comment]
Thank you so much @drasticactions, your workaround solved my crash and made my day :)

**Comment by MSicc** [comment]
While this @drasticactions workaround works, this issue should not be closed. The error is still existing in latest .NET 8 MAUI.
