### ISSUE TITLE
Unloded and Loaded events invoke multiple times at start

### ISSUE THREAD

**Issue by Marioo1357** [dotnet/maui#18403]
### Description

After UI control initialize, the Loaded event is triggered twice and Unloaded once between

### Steps to Reproduce

1) Create New Maui project
2) Create xaml page
3) Create any standalone xaml control
4) Attach to Loded and Unloaded events in this control

Actual result:
(After constructor invoke)
- Loaded
- Unloaded
- Loaded
(After navigation back from page)
- Unloaded

Expected result:
(After constructor invoke)
- Loaded
(After navigation back from page)
Unloaded

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.96

### Affected platforms

iOS, Android

### Affected platform versions

Android 12, ios 16

**Comment by PureWeen** [comment]
One thing to note about loaded/unloaded is that these are wired directly to the related platform events
- Android: AttachedToWindow
- iOS: MovedToWindow
- Windows: Loaded

We improved the loaded/unloaded behavior on iOS for NET8, so that it more accurately represents calls from `MovedToWindow. There may have also been some improvements to Android as well.
