### ISSUE TITLE
Cannot change Japanese input method after open basic authentication dialog

### ISSUE THREAD

**Issue by minhhieu219** [dotnet/maui#18619]
### Description

Japanese has multipple input methods for Japanese and romanji.
When you access a page with basic authentication, input method locked to romanji. 
After you login or cancel login, you cannot change to other methods anymore unless you restart the app.

### Steps to Reproduce
1. Install Japansese IME
2. Create an empty project 
3. Add a WebView Control 
`<WebView Source="localhost:8080/main" />`
4. Access any page with basic authentication
5. Login dialog popups, cancel it
6. In developer tool, use window.location.replace in console to move to any page with an input.
`window.location.replace('https://google.com')`
7. Switch to full-width keyboard

Expect result: Be able to type in full-width Japanese
Actual result: Cannot switch to full-width Japanese

### Version with bug

9.0.101

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

No.

**Comment by drasticactions** [comment]
Based on your description, I'm not sure what controls or how your app is structured so that situation could occur. Could you please create a reproduction project showing your issue?

**Comment by minhhieu219** [comment]
It's a simple project with only a WebView. When WebView access to a webpage that has www-authenticate header, login dialog opened and you can only type Romanji. After login or cancel the login dialog, you cannot change input method anymore.

**Comment by drasticactions** [comment]
@minhhieu219 Trying this now on my Japanese Windows setup, and I can reproduce this, but it wasn't just on authentication pages, but any web page with an input box would only allow half-width English characters regardless of what the Windows setting was. I also created a WinUI 3 app with WebView2 and it allowed all inputs fine. The MAUI WebView is a wrapper around WinUIs WebView2, but since it works there and not here, it's very strange.

I'm not convinced this is Japanese IME specific, but more likely something in WinUI or MAUI is forcing plain text output regardless of the IME setting. You could probably reproduce this with other IMEs. Are you sure you can input other IME settings fine in input boxes? Do you have an example page where it works for you?

**Comment by minhhieu219** [comment]
Hi @drasticactions, thank you for your confirmation. I haven't tested with other IMEs and I don't think it's Japanese IMEs specific either.

**Comment by jfversluis** [comment]
It would be super helpful if we can get some relevant code here or a reproduction sample that shows this behavior if this is possible at all?

**Comment by minhhieu219** [comment]
@jfversluis 
I have updated steps to reproduce. 
Any workaround would be appreciated.
