### ISSUE TITLE
 Microsoft.Maui.Controls.Element: Warning: Microsoft.Maui.Controls.VerticalStackLayout is already a child of Microsoft.Maui.Controls.ContentPage. Remove Microsoft.Maui.Controls.VerticalStackLayout from Microsoft.Maui.Controls.ContentPage before adding to MauiAppPopupError.LoadingView.

### ISSUE THREAD

**Issue by acaliaro** [dotnet/maui#18614]
### Description

If I use a CommunityToolkit popup with a VerticalStackLayout, I see this warning on VS console. What is this?

### Steps to Reproduce

run the project and click on the button

### Link to public reproduction project repository

https://github.com/acaliaro/MauiAppPopupError

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ios15

### Did you find any workaround?

no

### Relevant log output

```shell
Loaded assembly: /private/var/containers/Bundle/Application/954C8A11-0FD0-497A-A8AE-C720CF8EF8EF/MauiAppPopupError.app/System.Runtime.Intrinsics.dll [External]
[0:] Microsoft.Maui.Controls.Element: Warning: Microsoft.Maui.Controls.VerticalStackLayout is already a child of Microsoft.Maui.Controls.ContentPage. Remove Microsoft.Maui.Controls.VerticalStackLayout from Microsoft.Maui.Controls.ContentPage before adding to MauiAppPopupError.LoadingView.
2023-11-08 09:19:38.909 Xamarin.PreBuilt.iOS[768:21591] Warning: observer object was not disposed manually with Dispose()

2023-11-08 09:19:38.910 Xamarin.PreBuilt.iOS[768:21591] Warning: observer object was not disposed manually with Dispose()
```

**Comment by drasticactions** [comment]
This question would probably be more apt for the [MAUI CommunityToolkit repo](https://github.com/CommunityToolkit/Maui) unless you can replicate it with standard MAUI controls without the popup wrapping, but my guess is with this: https://github.com/acaliaro/MauiAppPopupError/blob/master/BaseViewModel.cs#L22-L25

The inner content of the loading view is created, either through Shell or some element within the CommunityToolkit popup view, then placed inside the popup container. Since there is a parent connection of a ContentPage somewhere being created, this code is being invoked

https://github.com/dotnet/maui/blame/baa86b20786f75632dd99ae13df7d268a5b843f9/src/Controls/src/Core/Element/Element.cs#L349

IMO, I would file this as an issue with CommunityToolkit.Maui. It would probably be better to start there and then file an issue here if it can be replicated outside of that control context.

**Comment by acaliaro** [comment]
> This question would probably be more apt for the [MAUI CommunityToolkit repo](https://github.com/CommunityToolkit/Maui) unless you can replicate it with standard MAUI controls without the popup wrapping, but my guess is with this: https://github.com/acaliaro/MauiAppPopupError/blob/master/BaseViewModel.cs#L22-L25
> 
> The inner content of the loading view is created, either through Shell or some element within the CommunityToolkit popup view, then placed inside the popup container. Since there is a parent connection of a ContentPage somewhere being created, this code is being invoked
> 
> https://github.com/dotnet/maui/blame/baa86b20786f75632dd99ae13df7d268a5b843f9/src/Controls/src/Core/Element/Element.cs#L349
> 
> IMO, I would file this as an issue with CommunityToolkit.Maui. It would probably be better to start there and then file an issue here if it can be replicated outside of that control context.

Thanks @drasticactions . Can you move the discussion to CommunityToolkit.Maui or should I open a new issue there?
