### ISSUE TITLE
Many compilation errors when building projects with the same root namespaces

### ISSUE THREAD

**Issue by VladMiskaryan** [dotnet/maui#18730]
### Description

I created two projects. First one is .NET MAUI App. Second one is .NET MAUI Class Library. 

App referenced to library.  If I add to the library the same RootNamespace as the application, I'll get thousands of build errors for Android:
>App1\App1\obj\Debug\net7.0-android\Resource.designer.cs(28,4,28,25): warning CS0436: The type 'Resource' in 'App1\App1\obj\Debug\net7.0-android\Resource.designer.cs' conflicts with the imported type 'Resource' in 'Lib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'App1\App1\obj\Debug\net7.0-android\Resource.designer.cs'.
>App1\App1\obj\Debug\net7.0-android\Resource.designer.cs(28,4,28,47): error CS0131: The left-hand side of an assignment must be a variable, property or indexer

![image](https://github.com/dotnet/maui/assets/42138946/849f4725-8e2d-4a21-93b6-6df3e83982bf)

### Steps to Reproduce

1. Create .NET MAUI App project named "App1".
2. Add .NET MAUI Class Library named "Lib1".
3. In "App1" add project reference to "Lib1".
4. In "Lib1.csproj" add tag "<RootNamespace>App1</RootNamespace>".
5. Try to build solution.

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by drasticactions** [comment]
I can't reproduce this. Could you please create a reproduction project with what you did to cause this?

**Comment by VladMiskaryan** [comment]
Reproduction project: https://github.com/VladMiskaryan/MauiSameRootNamespaceError.

**Comment by Redth** [comment]
Seems there's conflicts with the android resource id's generated in the designer files.

@dellis1972 thoughts on this one?  Is this a supported scenario?

**Comment by VladMiskaryan** [comment]
I just tried to reproduce it for net8.0-android target. And it works fine. 
So the problem is only in the net7.0-android target.

**Comment by dellis1972** [comment]
The problem here is that by design library projects use `static int` for its resource Id's in the Resource.designer.cs. But for an app it uses `const int` . Because the `Resouce.designer.cs` classes end up in the exact same namespace this will cause a conflict as one of the types will overwrite the other. Meaning code which would work in a library project would not work in the app one. For example `Resource.Id.Foo = 4` would be fine in a library project but would give this error in an app project. 

So for .net 7 you can't really use the same root namespaces unless you override the `AndroidResgenNamespace` property in one of the projects. 

For .net 8 we completely overhaulled the Resource system, which apparently allows this although that wasn't something we tested.

**Comment by VladMiskaryan** [comment]
So let's summarize: 
In .NET 8 it works fine.
In .NET 7 enough to add AndroidResgenNamespace tag in library csproj file. e.g. <AndroidResgenNamespace>Lib1</AndroidResgenNamespace>
