### ISSUE TITLE
Flyout title doesn't switch on Detail change

### ISSUE THREAD

**Issue by MiKuzminski** [dotnet/maui#18830]
### Description

When switchting from one DetailPage to another using a Flyout the title remains from the initially loaded DetailPage.

### Steps to Reproduce

1. Create new solution.
2. Create a new .NET 8 MAUI project.
3. Implement Flyout according to [Microsoft Flyout Documentation](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pages/flyoutpage?view=net-maui-8.0)
4. Add 2 DetailPages with different titles
5. Switch to different DetailPage using Flyout

Excepted Outcome: Title changes according to shown DetailPage.
Actual Outcome: Title remains from first shown DetailPage.

### Link to public reproduction project repository

https://github.com/MiKuzminski/Net8FlyoutTitleBug

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS, Android

### Did you find any workaround?

Reverting the project to .net7

**Comment by berhir** [comment]
I started to create a similar issue but right before I sent it, I saw this one.
So I am adding my details here instead.
The issue is not only about the title, it's also not possible to navigate back anymore in a navigation page. Instead, the flyout menu opens.

Here is a sample to reproduce the issue: https://github.com/berhir/MauiFlyoutBackIssue
I tested it on Android 11 and 13

Steps to reproduce the issue:
- Start the app on Android
- Click on "Navigate to sub page"

=> App navigates to sub page, the title changes to "Page1Sub" and the hamburger icon changes to a back icon. **OK**

- Click on the back icon

=> App navigates back to Page1, the title changes to "Page1" and the hamburger icon is shown. **OK**

- Click on the hamburger icon
- Click on "Page2"

=> App navigates to Page2, but the title is still "Page1". **NOT OK**

- Click on the hamburger icon again
- Click on "Page1"
- Click on "Navigate to sub page"

=> App navigates to sub page, but the title is still "Page1". **NOT OK**

- Click on the back icon

=> The flyout menu opens instead of navigating back to Page1. **NOT OK**

**Comment by stanbilliet** [comment]
I can confirm this issue, same issue in my project when upgrading from .net 7

**Comment by PureWeen** [comment]
Can you test the nightly [here](https://github.com/dotnet/maui/wiki/Nightly-Builds) let me know if that resolves?

**Comment by berhir** [comment]
@PureWeen I have updated my sample (branch [maui-nightly](https://github.com/berhir/MauiFlyoutBackIssue/tree/maui-nightly)) to use the latest nightly version (8.0.0-nightly.9637).
And I can confirm that the issue is fixed (tested on Android).
