### ISSUE TITLE
Maui Button Color Binding not working

### ISSUE THREAD

**Issue by invisloa** [dotnet/maui#18858]
As the title says when I set the binding of my button to some color it is not working at all. If the same binding is done on label it works fine. The screenshot shows it all.
![image](https://github.com/dotnet/maui/assets/91217120/3f665d79-4eb4-4c53-ad02-ca4b47b797b5)

**Comment by jfversluis** [comment]
That this is not working is correct and I'll try to explain why, this is a bit of XAML magic that you're running into.

When setting the color value from XAML you can indeed use a value like `#FF0000` directly and it will work. This only works, because we have a set of built-in `TypeConverter`s. Those kick in for certain types that we have identified to help you make this a bit easier to work with. See the converter for a color [here](https://github.com/dotnet/maui/blob/main/src/Graphics/src/Graphics/Converters/ColorTypeConverter.cs).

However, if you're going to work with data-binding, this runs _not_ through the `TypeConverter`. When using data-binding, it is the developers job to make sure that the type matches whatever is expected, in this case a `Color`.

So, the fix here is to either add a converter of your own to your binding, the documentation for that can be found [here](https://learn.microsoft.com/dotnet/maui/fundamentals/data-binding/converters). Or make sure to convert your string to a `Color` in the data bound value in your code behind.

Hope that helps!

**Comment by SmartmanApps** [comment]
I've just finished updating a Windows app and libraries to 8.0 and I'm having no issues with that. Having said that, I don't use XAML or Shell either, so the issue may be in there.

**Comment by invisloa** [comment]
first, on my ScreenShot there is the exact same binding set to a button and to a label. Button color is not set according to a binding while the label color shows as intended.
the second thing that I noticed is that when i remove the line with " BackgroundColor="{Binding ButtonColor}"" and add it after like 2 secs it works wonderfull. 
So I doubt the problem lies in using some converters + i switched to strings from using colors to strings since colors didnt work... :)

**Comment by invisloa** [comment]
to keep it as simple as possible: 
the background color Binding for  BUTTONS IS NOT WORKIN IN .NET8
TextColor and BorderColor WORKS but not BackgroundColor
![image](https://github.com/dotnet/maui/assets/91217120/598e7350-0077-42a4-bc9f-fd66058c748f)

**Comment by invisloa** [comment]
I got this :) wasn't binding at all... I had a global button style set in the app.xaml
the problem is that styles set in app.xaml cannot be overriden...
this worked in .net 7 tho
![image](https://github.com/dotnet/maui/assets/91217120/9e3761c5-51bd-4b51-b105-f4dc82f88d4b)
