### ISSUE TITLE
Critical performance degradation in release mode after upgrade to dotnet 8 

### ISSUE THREAD

**Issue by XamerDev** [dotnet/maui#18869]
### Description

Hello after upgrade to dotnet 8 we are facing huge problem with performance degradation during navigation between pages.
Comparing to dotnet 7 app in net 8 baheves criticaly bad in Release Mode!.
Dotnet 7 version was pretty smoth.
I cannot show the code of production app but I recreated more or less same app and surprisingly is bahaving the same bad even with 5% of code that we implement in prod app. 
Guys that is really bad really
here is a video to get the problem:

https://github.com/dotnet/maui/assets/86706851/7536fb07-f6fa-4129-a985-dc455d3f55a7

### Steps to Reproduce

1. Go to second tab and navigate back and forth

### Link to public reproduction project repository

https://github.com/XamerDev/Net8Perf

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

7.0.101

### Affected platforms

Android

### Affected platform versions

Android all

**Comment by kcrg** [comment]
I can reproduce this issue, but I don't think running heavy logic in OnAppearing method is good practise. I changed OnAppearing to OnNavigatedTo and everything is smooth.

`<toolkit:EventToCommandBehavior Command="{Binding GetCommand}" EventName="Appearing" />`
To:
`<toolkit:EventToCommandBehavior Command="{Binding GetCommand}" EventName="NavigatedTo" />`

**Comment by XamerDev** [comment]
ok after deeper investigation of this I can see where the problem was. "NavigatedTo" solved the problem. But I have no idea why then on dotnet7 it was worked differently... OnAppearing didn't cause any problems...
issue can be closed

**Comment by drasticactions** [comment]
https://github.com/XamerDev/Net8Perf/blob/master/ViewModels/DetailsViewModel.cs#L20-L28

Trying your example in net7 and net8, I believe the EventToCommandBehavior was running that command in net7.0 on a background thread, whereas in net8.0 it is off of a UI Thread. ObservableCollection, as far as I know, needs to be updated on the UI Thread. Because in net7.0 it's off of a background thread, the `await delay` does nothing, and adding the item to the ObsersableCollection does a shim (I think, I could be mistaken here) in MAUI where it puts its item on the UI Thread. Because in net8.0 the entire thing is on the UI Thread, that `await delay` blocks the UI Thread, so it breaks the UI.

That sounds like something that could be explored in the [CommunityToolkit](https://github.com/CommunityToolkit/Maui) repo if that's a change in functionality.
