### ISSUE TITLE
.NET Maui release build crashes but debug build is fine

### ISSUE THREAD

**Issue by sachinkanadia** [dotnet/maui#18870]
### Description

Hello,

I have an app (LightWork) that I want to publish on the Apple App Store. The debug build runs and works fine, however, on submission the release build crashes on start up. The symbolicated crash report can be found here:

https://stackoverflow.com/questions/77495334/net-maui-release-build-crashes-but-debug-build-is-fine

I tried disabling XAML compilation & setting the same build configuration against the debug. So I can confirm I don't think it has anything to do with XAML or the build configuration.

I have no idea why its failing and its preventing release. If anyone can help that would be much appreciated.

Many Thanks!

### Version with bug

7.0.100

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by drasticactions** [comment]
Without a repro project or a stack trace, this will most likely be impossible to debug. Would it be possible to create a project showing your issue, or a stack trace from the release build? @rolfbjarne Are there other things they could provide to help diagnose this?

**Comment by rolfbjarne** [comment]
All the stack trace says is that there was an unhandled exception, but nothing about the exception itself.

As a wild guess, try enabling the interpreter to see if that makes a difference (it's enabled by default for Debug builds already; this would enable it for all builds):

```xml
<PropertyGroup>
    <UseInterpreter>true</UseInterpreter>
</PropertyGroup>
```

**Comment by ahoffmandevelopment** [comment]
I'm having the same issue with both local and Azure pipeline builds. Debug works fine but release crashes immediately on startup.

Things I've tried:

- Setting UseInterpreter to True as described above.
- Disabling the linker for release builds.
- Linking with SdkOnly and leaving in NewsstandKit.

Also, possible related are issues #18652 and #18528 .

**Comment by rolfbjarne** [comment]
Can you attach your csproj?

**Comment by ahoffmandevelopment** [comment]
Unfortunately, I cannot. However, since it's working in Debug but not Release, I changed my Debug build to Link SdkOnly, and now I can see this error immediately upon startup:

`2023-11-27 10:57:51.668 XXXX[454:7918] Unhandled managed exception: Could not resolve type with token 01000007 from typeref (expected class 'System.Reflection.AssemblyDefaultAliasAttribute' in assembly 'System.Private.CoreLib, Version=0.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e') (System.TypeLoadException)
   at System.Reflection.CustomAttribute.GetCustomAttributesBase(ICustomAttributeProvider , Type , Boolean )
   at System.Reflection.CustomAttribute.GetCustomAttributes(ICustomAttributeProvider , Type , Boolean )
   at System.Reflection.RuntimeAssembly.GetCustomAttributes(Type , Boolean )
   at Microsoft.Maui.Platform.ReflectionExtensions.GetCustomAttributesSafe(Assembly assembly, Type attrType)
   at Microsoft.Maui.Controls.Internals.Registrar.RegisterAll(Assembly[] assemblies, Assembly defaultRendererAssembly, Type[] attrTypes, InitializationFlags flags, Action`1 viewRegistered, IFontRegistrar fontRegistrar)
   at Microsoft.Maui.Controls.Internals.Registrar.RegisterAll(Type[] attrTypes, InitializationFlags flags, IFontRegistrar fontRegistrar)
   at Microsoft.Maui.Controls.Internals.Registrar.RegisterAll(Type[] attrTypes, IFontRegistrar fontRegistrar)
   at Microsoft.Maui.Controls.Compatibility.Forms.RegisterCompatRenderers(IMauiContext )
   at Microsoft.Maui.Controls.Compatibility.Forms.SetupInit(IMauiContext , Nullable`1 )
   at Microsoft.Maui.Controls.Compatibility.Forms.Init(IActivationState , Nullable`1 )
   at Microsoft.Maui.Controls.Compatibility.Hosting.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__1_1(IMauiContext )
   at Microsoft.Maui.Platform.ApplicationExtensions.<>c__DisplayClass3_0.<CreatePlatformWindow>b__0(OnMauiContextCreated del)
   at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[OnMauiContextCreated](IServiceProvider services, Action`1 action)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IApplication application, UIWindowScene windowScene, NSDictionary[] states)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IUIApplicationDelegate platformApplication, IApplication application, UIApplication uiApplication, NSDictionary launchOptions)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at UIKit.UIApplication.UIApplicationMain(Int32 , String[] , IntPtr , IntPtr )
   at UIKit.UIApplication.Main(String[] , Type , Type )
   at XXXXXX.Program.Main(String[] args) in /Users/XXXX/Projects/XXXX/XXXXPlatforms/iOS/Program.cs:line 13

**Comment by ahoffmandevelopment** [comment]
So my issue ended up being with a library that I had recently brought in, TinyMapper. While I could have probably taken the time to figure out what was being linked out, I just removed the library and refactored my code, and now release builds are running correctly in Azure.

**Comment by sachinkanadia** [comment]
Not the same here.

@rolfbjarne I tried enabling the interpreter but I got the same crash with the same stack trace.

**Comment by sachinkanadia** [comment]
@rolfbjarne it still fails but I think it produces a different log which I've attached. The IPS file is not symbolicated as I can't seem to find it in the organizer in XCode.

[Crash.zip](https://github.com/dotnet/maui/files/13490375/Crash.zip)

**Comment by sachinkanadia** [comment]
[LightWork-2023-11-28-162617.txt](https://github.com/dotnet/maui/files/13490667/LightWork-2023-11-28-162617.txt)
Doesn't add symbols with the NoSymbolStrip enabled. Be sure to rename the file to ".ips".

**Comment by rolfbjarne** [comment]
That didn't clarify much :/ 

Are you able to reproduce locally by building the Release configuration (as opposed to having to publish the app first)?

**Comment by sachinkanadia-se** [comment]
I am currently building and deploying locally to my physical iOS device. I am setting the release profile and certificate to development. As its release build it doesn't debug, but it does deploy. When I run the deployed app it just crashes immediately and this is without any debugger attached so I can't see any exception raised in VS.

**Comment by rolfbjarne** [comment]
Can you get a [binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) for a working Debug build and a failing Release build and attach them here? That should make it possible to see the differences in the build configuration that causes this.

**Comment by sachinkanadia** [comment]
I now get this log when running the app but the iOS App still crashes on release mode.

![Screenshot 2024-03-03 at 13 18 25](https://github.com/dotnet/maui/assets/18262347/9bc1dd06-db7c-4d09-8fec-7d699d73d4fc)

I'm quite sure the distribution certificate and profile are fine. Any ideas?

**Comment by rolfbjarne** [comment]
@sachinkanadia can you disable stripping of native symbols, try again, and see if the resulting stack trace is more descriptive?

Just add this to the project file:

```xml
<PropertyGroup>
    <NoSymbolStrip>true</NoSymbolStrip>
</PropertyGroup>
```

**Comment by sachinkanadia** [comment]
I did as you mentioned and it produced this crash log.

![Screenshot 2024-03-04 at 19 32 30](https://github.com/dotnet/maui/assets/18262347/e91313bf-4f28-4371-b9a8-abbb30c70a17)

This is annoying. Why does it crash without any info on the exception?

**Comment by sachinkanadia** [comment]
I cleaned the project and rebuilt the project. Still, the same stack trace persists.

**Comment by rolfbjarne** [comment]
> If cleaning doesn't change anything, please get a binary build log ([Wiki: Diagnosis (binary build logs) (xamarin/xamarin-macios)](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs)) and attach it here, which should explain why the symbols are still stripped.

**Comment by sachinkanadia** [comment]
![Screenshot 2024-03-24 at 16 13 03](https://github.com/dotnet/maui/assets/18262347/a6851c85-831e-4297-b979-5520b0ffec62)

My extensions manager is not showing any extensions. I am running VS Mac 17.6.10 (build 428). Is there a source that I need to add? Or do you have a link to Project System Tools for Mac that I can download?

**Comment by rolfbjarne** [comment]
@sachinkanadia no idea, I've never seen that before. And since VSMac is going out of support in a few months, I don't think any issues will be fixed. My recommendation would be to either try building from the command line and getting a binlog that way (which is much easier), or use VSCode.

**Comment by sachinkanadia** [comment]
@rolfbjarne Wouldn't I still need to download the Project System Tools for Mac to build from the command line in order to obtain the binlog? Also would you be able to point me to the instructions for building from the command line, please? Thanks

**Comment by rolfbjarne** [comment]
See https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs or https://aka.ms/binlog

**Comment by sachinkanadia** [comment]
```
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	  <MtouchEnableSGenConc>true</MtouchEnableSGenConc>
	  <CodesignProvision>LightWork</CodesignProvision>
	  <CodesignKey>iPhone Distribution: sachin kanadia (EVLL97WB58)</CodesignKey>
	  <MtouchLink>SdkOnly</MtouchLink>
	  <MtouchFloat32>true</MtouchFloat32>
	  <MtouchNoSymbolStrip>true</MtouchNoSymbolStrip>
	  <NoSymbolStrip>true</NoSymbolStrip>
	</PropertyGroup>
```
The above build configuration has produced the following build log output when executing:

`dotnet publish -f net8.0-ios -p:ArchiveOnBuild=true -bl:publish.binlog`

[publish.binlog.zip](https://github.com/dotnet/maui/files/14824779/publish.binlog.zip)

Please let me know what you find, (Why it is stripping debug symbols which hides the runtime exception) many thanks.

**Comment by rolfbjarne** [comment]
> Hey @rolfbjarne have you had a chance to look at this? Thanks

Sorry for the late reply, I've been away.

> Please let me know what you find, (Why it is stripping debug symbols which hides the runtime exception) many thanks.

Unfortunately that revealed that the symbols are *not* stripped away, so I have no idea why the crash report is so useless.

However, can you try getting the device log (https://support.apple.com/en-in/guide/console/cnsl1012/mac) and see if it says something useful?

**Comment by sachinkanadia** [comment]
I see this error in the device log against my App:

Unhandled managed exception: Attempting to JIT compile method '(wrapper dynamic-method) LightWork.Entities.Exercise object:Thunk1ret_Exercise_QueryContext_DbDataReader_ResultContext_SingleQueryResultCoordinator (System.Func`2<object[], object>,Microsoft.EntityFrameworkCore.Query.QueryContext,System.Data.Common.DbDataReader,Microsoft.EntityFrameworkCore.Query.Internal.ResultContext,Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryResultCoordinator)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
 (System.ExecutionEngineException)
   at System.Delegate.CreateDelegate(Type , Object , MethodInfo , Boolean , Boolean )
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type , Object )
   at System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(Type , Func`2 )
   at System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegate(Type , Func`2 )
   at System.Linq.Expressions.Interpreter.LightLambda.MakeDelega<…>

The question is do you think this is causing the App to crash?
If so I need to track down the method which is causing the issue as the documentation mentions:

Using Delegates to call Native Functions
To call a native function through a C# delegate, the delegate's declaration must be decorated with one of the following attributes:

[UnmanagedFunctionPointerAttribute](preferred, since it is cross-platform and compatible with .NET Standard 1.1+)
[MonoNativeFunctionWrapperAttribute]

**Comment by sachinkanadia** [comment]
Aha! It's solved!

I stumbled upon this article: https://github.com/dotnet/maui/issues/9176

Which helped me get to the solution.

I had to enable the interpreter and delete the obj and bin folders before building in Release mode.

Thanks @rolfbjarne your help has been imperative!
