### ISSUE TITLE
Strategic question: Can MAUI replace UWP and WPF?

### ISSUE THREAD

**Issue by SetTrend** [dotnet/maui#189]
After reading [Scott's strong statement](https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/):
> .NET MAUI simplifies the choices for .NET developers, providing a single stack that supports all modern workloads: Android, iOS, macOS, and Windows. The native features of each platform and UI control are within reach in a simple, cross-platform API for you to deliver no-compromise user experiences while sharing even more code than before.

If that's really the intention: "one .NET to rule them all", then is this supposed to drop the other UI frameworks (incl. `UWP` and `WPF`) and just use MAUI for them all?

That strategic idea sounds very intriguing to me. If that'd be true, this would save a lot in spending resources on learning and maintaining different and distinct UI frameworks, like `Xamarin.Forms`, `UWP` and `WPF`.

In the end, it's all just about front-end programming. All the frameworks claim to fit on every device. There can hardly be any GUI element that cannot be represented on any device and any OS today. However, platform specific controls, like DirectX controls could be added as platform specific packages to a MAUI solution.

Shouldn't MAUI then better be the base framework for UWP, with UWP just providing one or two additional extra packages with OS specific controls, like DirectX controls? (Thereby actually dropping the idea of `UWP` and just adding a few additional, platform specific controls to the `System.Maui.ControlGallery.Windows` namespace?)

![NET UI Stack](https://user-images.githubusercontent.com/9283914/88662896-f0d28d80-d0da-11ea-9601-3f867e9d0c2c.png)

**Comment by mrwcjoughin** [comment]
MAUI is the replacement for Xamarin.Forms - but it does not change what it is: a wrapper UI over the native UI of that platform.

That is not changing for MAUI based on the everything they have shown.
They are going to make it easier, and resolve alot of the issues/bugs that are remaining, and make macOS officially supported (not just community supported) for example, but the essence of what it is remains.

There are lot of advantages to this approach, performance being a big one, but of course there are disadvantages too.
However there is no silver bullet: Java started the same way with AWT (abstract widget toolkit), and then with Java 2 they released Swing which theorectically was better because it was written 100% in java - but it was so SLOW.
This is the quandary, so I for one am happy that Xamarin.Forms and MAUI as its successor works the way it does - so that we get effectively a native UI which is always faster.

The fact they have chosen UWP as the UI for Windows is not something I can comment on, but I can say that it works well enough for my purposes so far, and it will be better in MAUI.

At the end of the day the customer has no idea about any of this - they just want something that works.

**Comment by SetTrend** [comment]
I just noticed that my case is already vividly discussed here in other issues. So I close my particular issue.

My case boils down to: Get all leading heads at Microsoft together and have them decide on one single UI class library, so we all can use the same XAML regardless of the platform.

Using .NET 5+, MAUI's UI class library can compile those classes plus user code to any supported target platform.

Other projects (e.g. WinUI) could provide additional NuGet packages for specific platforms to be added to a MAUI solution.

So we could create a MAUI solution targetting only Windows (UWP?) and add a WinUI NuGet package to it, adding support for DirectX controls. Similar for other platforms.
