### ISSUE TITLE
[Bug] WinUI Crashing with layout cycle on template

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#1908]
### Steps to Reproduce

1. Change the `_pageType` field in the Startup.cs to be `PageType.Template`
2. Run the WinUI app
3. Crashes with layout cycle error

**Comment by mattleibow** [comment]
Seems to be around here it broke, but probably totally unrelated because of a bug elsewhere that this was preventing: https://github.com/dotnet/maui/pull/1885

I notice it fails instantly when loading a Grid in the ScrollView. 

If you change it to a StackLayout, it sometimes launches and resizes just fine until you shrink the window down to narrower than the image. But I only got that once and can't seem to repro it.

**Comment by mattleibow** [comment]
Managed to repro this consistently with 

```xaml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Maui.Controls.Sample.Pages.TemplatePage">

    <ScrollView Padding="{OnPlatform iOS='30,60,30,30', Default='30'}">
        <Grid RowSpacing="25" RowDefinitions="Auto,Auto,Auto,Auto,*">

        </Grid>
    </ScrollView>

</ContentPage>
```
