### ISSUE TITLE
[regression/8.0.3] Android Target Framework and Minimum Android Target Framework list are empty

### ISSUE THREAD

**Issue by 3ma-ChristopheG** [dotnet/maui#19150]
### Description

Hi,

I have a problem with android on .NET version 8. I have empty lists in Android Target Framework. Even on a freshly created project.

In .NET8, for iOS, and Windows, it seems correct
In .NET7 everything works correctly, I have the choice between Android versions.

I have this on 3 different PCs.

![image](https://github.com/dotnet/maui/assets/52324548/829816c8-820f-4f10-bd5c-0eb53d57a6a3)

### Steps to Reproduce

1. Create à .NET MAUI project in .NET8
2. Go to properties on the solution
3. Check combobox "Android Target Framework"
4. The combobox is empty

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Android

**Comment by drasticactions** [comment]
The tooling around these menus are maintained by Visual Studio and not this repo or project. If you could file this to Visual Studio, then it can be triaged appropriately.

**Comment by genifycom** [comment]
Same here

**Comment by 3ma-ChristopheG** [comment]
I think the problem is resolved, and we are waiting for an update : [Link to VS support](https://developercommunity.visualstudio.com/t/Target-Android-framework-cannot-be-selec/10515664)

**Comment by mikebikerider** [comment]
I don't see the problem resolved. 
I see the empty Target Android Framework and empty Minimum Android Framework drop-down list in VS2022 17.8.3 project properties after I select net8.0. 
I tried adding Platform PropertyGroup net8.0-android33.0 (34.0) directly to the project file. Got a kitchen sink of build errors.

When I select back net7.0 Target Android Framework and Minimum Android Framework lists are populated again, and I can restore selections. and build the project after I restart VS2022.
I'd happily use net7.0 as I do for iOS. But Android .net7.0 has issues supposedly fixed in net8.0. I can't use net8.0 for Android at all. 
Nothing to smile about.

**Comment by 3ma-ChristopheG** [comment]
yes it is fixed but not yet deployed _"A fix for this issue has been internally implemented and is being prepared for release. We’ll update you once it becomes available for download."_

**Comment by goodgame365** [comment]
When on earth will it be released? I'm waiting anxiously for it.
I also encountered this issue and now I can't submit to Google Play.

**Comment by 3ma-ChristopheG** [comment]
I don't know. 

I'm not yet in deploy phase, but i found this :
![image](https://github.com/dotnet/maui/assets/52324548/3a1d16b4-84a1-4476-8f0a-5b8cccc0cd43)
in 
![image](https://github.com/dotnet/maui/assets/52324548/14d282c9-2a5c-4281-8f0f-c7b8caed1b00)
and combo are not empty !

**Comment by jfversluis** [comment]
According to the linked VS Feedback item this should have been resolved. If not, please report it through Visual Studio in the Help menu, > Provide Feedback, Report a Problem. That will route it to the right team. Thanks!
