### ISSUE TITLE
[regression/8.0.0] Border is not displayed when inside a Frame in .net 8

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#19274]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/-Border-is-not-displayed-when-inside-a-F/10523262)._

---
As the title of this report says, I had a project in _.net maui_ with _.net 7.0_, where I had border inside the frame and they were visualized well, after updating to _.net 8.0_, they stopped being displayed. To check if it was _.net 8.0_, create a new project as shown in the image.
![Captura de pantalla 2023-11-22 055904.png](https://aka.ms/dc/image?name=B9d2bc74ad1e942a2812cce50c5223cdf638362513096580557_Captura_de_pantalla_2023-11-22_055904.png&tid=9d2bc74ad1e942a2812cce50c5223cdf638362513096580557)

---
#### Feedback Bot on 11/22/2023, 06:27 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ALJASAC** [comment]
Hello,

The same happened to me when I updated from .net 7 to .net 8.

I could reproduce the error ( On **Android** ) using the default code for a new .net 8 maui project in VS2022.

In the MainPage.xaml of the default project, if we wrap the CounterBtn with a border like this:

![image](https://github.com/dotnet/maui/assets/87923433/943c0a6b-d423-48b6-b7c5-5355f8635012)

The button will be correctly shown as in the image below:
![image](https://github.com/dotnet/maui/assets/87923433/8b77d10e-63bf-4a9e-b51e-0d3b921f1486)

Also if we wrap the button with just a frame, the result is good also:
![image](https://github.com/dotnet/maui/assets/87923433/88ac3ec2-db85-4945-93d8-c69a604a878c)

This image shows the result:
![image](https://github.com/dotnet/maui/assets/87923433/8dc7ef4a-3325-4b30-8b72-fdf207bb8eb0)


But if we wrap the button with a border, and then wrap the border with a frame:
![image](https://github.com/dotnet/maui/assets/87923433/b3339741-e49d-47a5-aa2f-8d16db8350e7)

The frame covers the button making it impossible to use as shown in the image below:
![image](https://github.com/dotnet/maui/assets/87923433/a1a1f662-36cd-41b4-8d27-90d153044bda)

If we use the exact same code in the same default MainPage.xaml but using .net MAUI with .net 7 instead of .net 8:
![image](https://github.com/dotnet/maui/assets/87923433/1653d65c-516c-40dc-9d1e-adaacfc66ffc)

The results are as good as expected:
![image](https://github.com/dotnet/maui/assets/87923433/c88a566d-d1cc-4c21-aadd-24cb71d58886)

We can round the border with a frame wihtout affecting the button functionality.
