### ISSUE TITLE
[iOS] Keyboard stays open when tapping outside of an entry

### ISSUE THREAD

**Issue by AaronECS** [dotnet/maui#19375]
### Description

In previous versions of MAUI, tapping on an entry field and then tapping outside of that field would unfocus the entry and close the keyboard. This seems to have been changed with the latest update. Tapping outside of an entry doesn't close the keyboard or unfocus the entry anymore.

### Steps to Reproduce

1. Create a new .NET Maui 8 project
2. Add an Entry in MainPage.xaml
3. Run the app on iOS
4. Select the Entry field
5. Tapping on empty space outside of the entry field doesn't close the keyboard and doesn't unfocus the entry
6. Tapping on the Click Me! button doesn't close the keyboard or unfocus the entry either

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

### Affected platform versions

iOS 17

**Comment by PureWeen** [comment]
https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.contentpage.hidesoftinputontapped?view=net-maui-8.0

**Comment by kaverk** [comment]
The HideSoftInputOnTapped property only applies to ContentPage types; what about reusable _ContentView_ controls? This seems to be a breaking change between .NET 7 and .NET 8 that doesn't currently have a workaround. Entry/Editor controls don't fire the Unfocused event when you click outside them anymore, which means the keyboard stays open. Listening for clicks on all other 15 controls on my page to know when the user has clicked outside of the text box (in order to commit the text) is overly complicated.
