### ISSUE TITLE
Calls to retrieve large byte array in MAUI Android app never completes

### ISSUE THREAD

**Issue by darutter0508** [dotnet/maui#19698]
### Description

Create a MAUI application targeting both iOS and Android that accesses an API. One of the methods on the API returns a byte array (bytes of an image or document). When the call to retrieve the byte array is made from the iOS app, the call succeeds and the byte array is returned successfully. However the same call never completes when made from the Android app. I have verified other calls that return lists of strings or single values all function properly in both iOS and Android. There is no error reported, the call just never returns and the app hangs.

### Steps to Reproduce

1. Create a MAUI app targeting iOS and Android 
2. Create a page that has a button on it whose "click" action is a call to an API that returns the byte array of an image
3. Debug the iOS version of the app and verify the call to the API succeeds
4. Debug the Android version of the app and verify the call to the API never returns

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 and up

### Did you find any workaround?

No

### Relevant log output

```shell
No log produced
```

**Comment by drasticactions** [comment]
Click handlers are on the UI Thread. If you're awaiting a web request on it without going off to a background thread, then I believe that's going to hang the app. Based on your description, it seems like it could be that you're causing a block on the UI Thread with your code. It's not able to download whatever file you have, and it doesn't throw or timeout if it takes too long, so it'll wait until it's done downloading. Since that's on the UI Thread, your app hangs.

If you can create a reproducible project showing that this happens generically, outside of your web service implementation, with how you set up your code, we would be able to identify the issue.
