### ISSUE TITLE
[MAUI] Stuck when entering/exiting G6 page

### ISSUE THREAD

**Issue by Ying-6** [dotnet/maui#19818]
### Description

Stuck when entering/exiting the G6 page, clicking on other pages will be normal.

### Steps to Reproduce

1.Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to Android.
2.Click or tap on test G6.
3.Click the exit button.

Actual result:
The app will stuck when entering/exiting to the G6 page.
![repro](https://github.com/dotnet/maui/assets/126375062/cc989a8d-7c8f-4620-9719-fcc0167c585c)

Expected result:
It works fine when entering/exiting the G6 page.

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug
Microsoft.Maui.Controls 8.0.6-nightly.9831+sha.e1e0328cfb-azdo.8900288
.NET SDK: 8.0.200-preview.23624.5

### Is this a regression from previous behavior?
Not a regression, this issue also repro on 8.0.3.

### Affected platforms
Android

**Comment by PureWeen** [comment]
@Ying-6 can you let us know what type of device you are testing on? What's the size and API version of the device you are testing on?

**Comment by Ying-6** [comment]
@PureWeen The type of device we tested was the Pixel 5. The device Memory is 1G, the sdcard.size is 512 MB, and the API version is API 34.

**Comment by kevinxufei** [comment]
The issue also repro on maccatalyst platform.
VSM Version: 17.6.9 (build 415)
Microsoft.Maui.Controls: 8.0.10-nightly.10215+sha.ce90b585c6-azdo.9163364
![maui2](https://github.com/dotnet/maui/assets/86938401/8ca05b37-f0fc-4a92-86c0-3300564247f6)

**Comment by jsuarezruiz** [comment]
If we drop an infinite value into base.GetDesiredSize for the ItemsView, this will invoke the PlatformArrange method, then RecyclerView OnLayout that will invoke the OnScrolled method of the OnScrollListener. Since RemainingItemsThreshold is used (also with a value of 1), more elements are obtained, and we do again the to Arrange -> OnLayout -> OnScrolled and we repeat and repeat having an infinite loop.

Current behavior:
![issue-19818-before](https://github.com/dotnet/maui/assets/6755973/da38236f-d53d-4725-8d87-ddce84ca0460)

If we get the visible elements and set the size of the RecyclerView based on them:
![issue-19818-after](https://github.com/dotnet/maui/assets/6755973/b3903768-7158-4a9e-9016-1fed138094cb)

Working in a fix. This test fails with respect Xamarin.Forms because the behavior of the StackLayout has changed.

**Comment by PureWeen** [comment]
@Ying-6 I've updated the test so it no longer crashes but this is still a bug on iOS
https://github.com/dotnet/maui/issues/10078

This isn't a regression though. I tested on 8.0.3 and it had the same issue

**Comment by PureWeen** [comment]
related
https://github.com/dotnet/maui/issues/17836

**Comment by jsuarezruiz** [comment]
Already updated the manual test sample to use a Grid (commit a52fd88f634decadda0cc0f8c7a147f9e8351596).

**Comment by jsuarezruiz** [comment]
Also, shared the details with @davidbritch to include some notes in the docs to avoid this scenario.
