### ISSUE TITLE
Datepicker date format display incorrect in windows but ok on android

### ISSUE THREAD

**Issue by BlackThornMusang** [dotnet/maui#19967]
### Description

![image](https://github.com/dotnet/maui/assets/137137319/11a3fba4-2dd2-420d-9865-59371d24194c)

### Steps to Reproduce

 <DatePicker Date="{Binding DateOfBirth}" Format="ddd, dd MMM yyyy"/>

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Window Machine

**Comment by BlackThornMusang** [comment]
<DatePicker Date="{Binding DateOfBirth}" Format="ddd, dd MMM yyyy"/>   in xaml

**Comment by BlackThornMusang** [comment]
Does a simple bug also need a repo? ....or guys have much to look into? 
Maybe .net maui is not ready yet as others said

**Comment by drasticactions** [comment]
@BlackThornMusang Having a repro projects helps makes sure that everyone can see the same issue through the same project, and that there isn't a chance of missing other kinds of changes you may have made to your project that you didn't notice. Even if it's a simple change, it helps reduce the back and forth of "Works on my machine!" That's why they ask.

That said

https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/Windows/CalendarDatePickerExtensions.cs#L87

This should probably be `"{dayofweek.abbreviated}"`

**Comment by drasticactions** [comment]
This issue will be closed when the PR closes
