### ISSUE TITLE
[iOS] Implement PrefersHomeIndicatorAutoHidden, PrefersStatusBarHidden and PreferredStatusBarUpdateAnimation Platform Specifics

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#19970]
### Description

Implement PrefersHomeIndicatorAutoHidden, PrefersStatusBarHidden and PreferredStatusBarUpdateAnimation Platform Specifics on iOS.

### Public API Changes

```
<ContentPage ...
     xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"
     ios:Page.PrefersHomeIndicatorAutoHidden="true">
```

### Intended Use-Case

More information: https://learn.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/page-home-indicator

**Comment by kubaflo** [comment]
@jsuarezruiz I created my first MAUI pull request: https://github.com/dotnet/maui/pull/20069, hope it will be useful :)

**Comment by jfversluis** [comment]
These are properties also implemented on Xamarin.Forms so for migration we should probably have this. At least #20069 is pretty close to merging, thats why we added this to the current sprint. Looking at this issue again I think this might describe more than just what is fixed in the linked PR? So we still have 2 other properties to implement after this as well?

Also see live stream [here](https://www.youtube.com/watch?v=g3UVNa5Bp48) for context
