### ISSUE TITLE
ListView is not currently being Garbage Collected

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#20025]
### Description

Breaking out remaining work for: https://github.com/dotnet/maui/issues/18365

Add tests to ensure that ListView is GC'd.

### Link to public reproduction project repository

https://github.com/heyThorsten/GCTest

**Comment by AdamEssenmacher** [comment]
Here's a possible workaround, and a few notes for whoever comes later.

I believe there are at least two leaks here. The more obvious one occurs because nothing calls `Dispose()` on the `ListViewRenderer`, which is absolutely needed to prevent the typical NSObject ref-counting leaks.

The other(s) I'm not as sure about. **It does seem like the leaks can be eliminated** with the AutoDisconnectBehavior from my memory toolkit: https://github.com/AdamEssenmacher/MemoryToolkit.Maui/blob/6f730d028770d99afcdc1284656589e763c5c5a3/src/MemoryToolkit.Maui/AutoDisconnectBehavior.cs

It needs to be added twice: once on the ListView itself, and once again on the Cell in the DataTemplate:
```xaml
<ListView mtk:AutoDisconnectBehavior.Cascade="True">
    <ListView.ItemTemplate>
        <DataTemplate>
            <ViewCell mtk:AutoDisconnectBehavior.Cascade="True">
                <Grid  />
            </ViewCell>
        </DataTemplate>
    </ListView.ItemTemplate>
</ListView>
```
This behavior walks the visual tree on the Unloaded event, so needing to add it on the ViewCell is a little weird. I investigated some and found that ListView has an odd private field for its visual children: https://github.com/dotnet/maui/blob/dbf7aad4009bcb353556b92c72309e2d29ee350b/src/Controls/src/Core/ListView/ListView.cs#L23

It appears that, on iOS, two Cell **instances** are added to this collection for each ListView item. Android does not behave like this. You can place a breakpoint in SetupContent https://github.com/dotnet/maui/blob/dbf7aad4009bcb353556b92c72309e2d29ee350b/src/Controls/src/Core/ListView/ListView.cs#L441 and see that it is called twice per ListView item. UnhookContent, on the other hand, is only called once per ListView item. https://github.com/dotnet/maui/blob/dbf7aad4009bcb353556b92c72309e2d29ee350b/src/Controls/src/Core/ListView/ListView.cs#L455

This makes me wonder if there's a separate (but related) issue where twice the number of Cells are getting instantiated, with the doubles not getting fully cleaned up and maybe leaking that way.

**Comment by AdamEssenmacher** [comment]
Deleted my previous comment because it contained some bad intel based on my local build just being gummed up.

Anyway... calling `Dispose()` on the ListView's handler is enough to fix the memory leak on iOS. It could probably be rewritten with some weak references to not need this, but at least the workaround is available.

**Comment by brentpbc** [comment]
@AdamEssenmacher Hi Adam, I have just ran into this, can you please share your work around?

**Comment by AdamEssenmacher** [comment]
@brentpbc you can see an example of how to call `Dispose()`on a handler in my [memory toolkit ](https://github.com/AdamEssenmacher/MemoryToolkit.Maui/).

Or, you can use its provided attached property to do this for you automatically :)
