### ISSUE TITLE
Page-level memory leak in NavigationPage on iOS

### ISSUE THREAD

**Issue by AdamEssenmacher** [dotnet/maui#20119]
### Description

NavigationPages are on iOS are not garbage collected after being removed.

Page-level leaks are serious, as they prevent child elements (in this case, whole child pages) from being collected as well.

### Steps to Reproduce

1) Set Application.Current.MainPage to a NavigationPage
2) Swap Application.Current.MainPage with a different page
3) Force GC runs
4) Observe navigation page (and its children) never collected

### Link to public reproduction project repository

https://github.com/AdamEssenmacher/iOSNavigationPageLeak.Maui

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.2

### Did you find any workaround?

Calling `DisconnectHandler()` on the NavigationPage's Handler before removing it from use will prevent the navigation page and its children from leaking.

**Comment by AdamEssenmacher** [comment]
Would the area/perf label be appropriate here as well? This issue causes entire pages (and possibly nav stacks) not to be GC'ed, which causes noticeable performance degradation once the app starts needing swap space, and ultimately leading to forced app termination.

**Comment by marco-skizza** [comment]
I think I'm facing the same problem.
But I have a regular `MainPage = new AppShell();` just like in the starter project.
I navigate to a second page via `await Shell.Current.GoToAsync("MySecondPage");`

It seems that the second page, it's ViewModel and the ViewModel's (big) data don't get garbage collected.
This is a huge problem for me, because I "lose" a lot of memory with each call to a page.

**Comment by kevinxufei** [comment]
Can repro this issue at iOS platform on the latest 17.10 Preview 6(8.0.3/8.0.21).
