### ISSUE TITLE
Android: Keyboard does not close when Entry looses the focus

### ISSUE THREAD

**Issue by omghb** [dotnet/maui#20170]
### Description

When the Button takes the focus the keyboard is still open. In addition it seems to be disconnected, so typing on the keyboard has no effect anymore)

Note:
The default Android MAUI Button does not take the focus. But we are using some Android Buttons which take the Focus on purpose.

![MauiAndroidKeyboardNotClosed](https://github.com/dotnet/maui/assets/47421673/6bd2b9dd-0703-4fc2-9cdf-ca6e4c6853cb)

### Steps to Reproduce

1. Create a new MAUI 8 App in Visual Studio
2. Replace `MainPage.xaml` content with

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">
    <ScrollView>
        <VerticalStackLayout Padding="30,0" Spacing="25" MaximumWidthRequest="500">
            <Entry />
            <Button x:Name="button1" Text="Click me"/>
        </VerticalStackLayout>
    </ScrollView>
</ContentPage>
```

3. Replace 'MainPage.xaml.cs` content with
```c#
using Microsoft.Maui.Handlers;

namespace MauiApp1
{
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
            button1.HandlerChanged += Button1_HandlerChanged;
        }

        private void Button1_HandlerChanged(object? sender, EventArgs e)
        {
#if ANDROID
            var platformView = ((ButtonHandler)button1.Handler!).PlatformView;
            platformView.Focusable = true;
            platformView.FocusableInTouchMode = true;
#endif
        }
    }
}
```

4. Start the App in an Android emulator or on a real Android device.

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tried out with Android 12, 14

### Did you find any workaround?

A workaround is to Close the keyboard manually when the Entry is unfocused:

```C#
        private void Entry_Unfocused(object sender, FocusEventArgs e)
        {
#if ANDROID
            entry1.HideSoftInputAsync(default);
#endif
        }

```

⚠ But this has some side-effects: 
- Example: If the user taps on a second Entry the Keyboard gets now closed for a second and is opened immediately again.

**Comment by PureWeen** [comment]
In developing .NET MAUI, we learned that it is not possible on Android (pre-API28) to unfocus an entry. Some control _must_ always be focused. In Xamarin.Forms, this was approached by setting focus on the page layout; unfortunately, this approach created major accessibility issues. For these reasons, .NET MAUI no longer allows for this behavior by default.
 
If this antipattern can be avoided, we highly recommend using a different approach. If it cannot be avoided, we'd love to learn more about your scenario so that we can better understand your development needs! That being said, we do understand the needs from a migration compatibility standpoint, so for those scenarios, there is a [new property that was introduced in .NET 8](https://github.com/dotnet/maui/pull/16530). Using `HideSoftInputOnTapped` should do the trick.

**Comment by omghb** [comment]
@PureWeen I believe we have a misunderstanding here. 

I do not want to unfocus an entry by tap on the page. But I have other Android controls which take the focus on usage. I used a button to demonstrate this in my example. 

The issue is that the soft keyboard from the entry stays open in some kind of disconnected state which makes it pretty useless (please, see provided video in the original post). 

**Expected behavior:** The keyboard should be closed automatically when another control receives the focus and so the entry looses the focus.
