### ISSUE TITLE
[Bug] ScrollView nested inside StackLayout causes ScrollView to measure incorrectly

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#2022]
### Description
If you have the following structure

SL => ScrollView => SL => Content

The ScrollView measures out as the entire height of the content and is not scrollable on Android (haven't tested iOS)

### Steps to Reproduce

I've added my XAML file here

[MainPage.zip](https://github.com/dotnet/maui/files/6962636/MainPage.zip)

It's basically this
```XAML
    <VerticalStackLayout>

        <ScrollView Padding="{OnPlatform iOS='30,60,30,30', Default='30'}">
            <VerticalStackLayout>

                <!-- add a bunch of content here -->

            </VerticalStackLayout>
        </ScrollView>
    </VerticalStackLayout>
```
### Expected Behavior

The content should be scrollable

### Actual Behavior

The content isn't scrollable

**Comment by hartez** [comment]
This is working as expected, AFAICT. The VerticalStackLayout doesn't put any vertical constraints on the content (by definition), so there are no vertical constraints on the ScrollView. The ScrollView sizes itself to the content until it hits a vertical constraint; after that, it stops expanding and the content becomes scrollable. But since there's no vertical constraint to hit, that never happens.

**Comment by PureWeen** [comment]
On XF the content is scrollable (tested on UWP/Android). Not saying the XF behavior is correct and should be replicated but just an FYI

It seems like the .NET MAUI behavior is more consistent with reality and other frameworks though? I'm guessing the XF implementation required some forced assumptions that probably made the implementation overly complicated and ultimately inaccurate?

**Comment by hartez** [comment]
You would be correct on all of those statements.

**Comment by reepmeDeveloper** [comment]
But how is the solution? ...that doesn't make a lot of sense to me... or I'm working to long wit XF Forms... how to get a StackLayout inside an StackLayout Scrollable?

**Comment by AmrAlSayed0** [comment]
@reepmeDeveloper This happens when the contents of the `ScrollView` is smaller (shorter) than the space provided by the outer `StackLayout`. I think if you put a fixed size on the `ScrollView` or put some other children in the outer `StackLayout` that reduce the height available for the `ScrollView`, it will scroll.
