### ISSUE TITLE
'Unable to activate windows store app {id}. The activation request failed with error code "The parameter is incorrect"'

### ISSUE THREAD

**Issue by BrandonStudio** [dotnet/maui#20340]
### Description

Exactly same as #9324 

### Steps to Reproduce

Create a new MAUI App with .NET 8.0
Debug on Windows Machine
Oops

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19045.0

### Additional Information
I'm not sure what the problem is.
1. There is no log in the Event Viewer following instructions of https://learn.microsoft.com/previous-versions/hh972445(v=vs.140)?f1url=%3FappId%3DDev16IDEF1%26l%3DZH-CN%26k%3Dk(vs.debug.error.app_activation_failure)%26rd%3Dtrue
2. I just now updated VS from 17.8.3 to 17.8.6
3. The issue happens on a Windows 10. I have another Windows 11, where there is also a VS updated from 17.8.3 to 17.8.6 but works well
4. It may be the first time I run a MAUI app on this Windows 10.

**Comment by andrasjani** [comment]
I experience the same (targeting windows10.0.19041.0). During developing I could deploy and debug it on my local machine, but after a time I get the same error when I started to debug (there were no code changes that could have caused this). I've tried to reinstall the OS and it worked just for few starts.

I tested to create a new solution (and copy all codes) without developer accociation, but I get the same result. (tried with .NET 7 and 8)

I haven't been able to solve it since then. It would be my mission to replace my old UWP app to MAUI

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10 Preview 5 (8.0.21&8.0.6). Not repro on windows platform.

**Comment by Zhanglirong-Winnie** [comment]
> What do you mean? Did you see this issue or not?

I can't see the error message you mentioned and can't repro the issue.

**Comment by mattleibow** [comment]
I think this issues was related to an older one where the WASDK broke all apps on the system: https://github.com/dotnet/maui/issues/12080

And now it broke all apps on the system again https://github.com/dotnet/maui/issues/25832

So, make sure you are on the latest Windows 10 and try again. Sorry.
