### ISSUE TITLE
WinUI crash at shell navigation 

### ISSUE THREAD

**Issue by sasharp** [dotnet/maui#20514]
### Description

WinUI crashes at navigation inside shell with System.Runtime.InteropServices.COMException: 'The text associated with this error code could not be found.
![MAUICrash](https://github.com/dotnet/maui/assets/7774486/f4023393-53ab-41a2-b68b-c898ddff07aa)
Conditions for crash are:
1. The CollectionView should have more than 100 items
2. Items should have Border
3. There is ShellContent inside of FyoutItem

### Steps to Reproduce

Click 1. item, go back.
Click 2. item, go back.
Click 3. item, go back.
Click 4. Item...

Sometimes the crash occurs by click on another elements.

### Link to public reproduction project repository

https://github.com/sasharp/MAUI8Bugs

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

try catch, but then freeses flyout half opened

**Comment by drasticactions** [comment]
<img width="737" alt="image" src="https://github.com/dotnet/maui/assets/898335/dd4371fe-6db2-4ef0-b3c8-baffc2b42252">

If you let the program run, you would have seen the message. It's a cycle layout issue. You're only seeing it sometimes because your CollectionView has a default border, which is causing your CollectionView list to load slower than if you change it to something else (Like the StrokeShape to RoundRectangle.) Since it's not fully realized, you can navigate. Once it's done loading, it will fail.

<img width="419" alt="image" src="https://github.com/dotnet/maui/assets/898335/d05a791c-5470-4834-b87d-22b1f303359f">

If you include that change, the CollectionView should load straight away, and then will crash every time you navigate. Removing the border stopping the crashing. Also, if I switched your app to use NavigationPage and not use shell, it also stopped the crashing with the existing XAML (So, with Border)

@PureWeen I'm not sure if this is

- A Shell Issue
- A CollectionView Issue
- A Border Issue
- Some mix of all of them.

It does seem to only happen under Shell, but I'm not sure what could cause the layout cycle from it over NavigationPage.

**Comment by drasticactions** [comment]
Also, that the CollectionView is loading all 250+ items in its list (as in, they are fully rendered and in the UI and never seem to unload) seems like a bug with Virtualization. Page navigation is painfully slow on that page and it's using 300+ Megs of memory on that page alone. That shouldn't be the case, so there could be another bug here with Virtualization.

**Comment by PureWeen** [comment]
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by sasharp** [comment]
@PureWeen with the version 8.0.10-nightly.10050 I can't reproduce the issue. It works.
