### ISSUE TITLE
WebRTC (navigator.mediaDevices) is not available on MacCatalyst but works with iOS

### ISSUE THREAD

**Issue by datvm** [dotnet/maui#20511]
### Description

I have a project that uses `navigator.mediaDevices` for Camera and Microphone following the example at [MackinnonBuck/MauiBlazorPermissionsExample](https://github.com/MackinnonBuck/MauiBlazorPermissionsExample). It works well on iOS (left) but on Mac with the same code and `Info.plist`, `navigator.mediaDevices` is `undefined` (right):

![image](https://github.com/dotnet/maui/assets/6388546/ca0753da-d0e1-407d-b70a-d135865d48e8)

### Steps to Reproduce

1. Clone https://github.com/MackinnonBuck/MauiBlazorPermissionsExample
2. Run it on Mac
3. Go to Camera section:

![image](https://github.com/dotnet/maui/assets/6388546/e8ce5ea5-6808-4efb-afc5-78414ba0958f)

4. Optionally: Open Safari Inspector and check for `navigator.mediaDevices` in the console, it's `undefined`.

### Link to public reproduction project repository

https://github.com/MackinnonBuck/MauiBlazorPermissionsExample

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

**Comment by drasticactions** [comment]
I don't think this is a MAUI bug.

<img width="627" alt="スクリーンショット 2024-02-13 0 50 40" src="https://github.com/dotnet/maui/assets/898335/893e7fdd-f590-4259-b464-8c1746f76ba0">

This is a limitation of WKWebView on Mac. I wrote a [SwiftUI app to show it](https://github.com/drasticactions/MauiRepros/tree/main/WebViewMediaDevicesTest). If you inspect that WKWebView, you'll see it missing there for Catalyst too, but showing up on iPhone. I also tried it on macOS/AppKit with its WKWebView and it didn't show there either: https://github.com/drasticactions/MauiRepros/tree/main/MacOSWebViewMediaTest

I could have missed something in my info.plist, or maybe there's some other setting that needs to be set, but looking online, [others are having similar issues](https://github.com/react-native-webview/react-native-webview/issues/2356) and my guess looking at it here is that the issue is WKWebView on macOS.

If you can show a way to make it work with a straight WKWebView then please reopen this so we can see what we would need to set here, but as far as I can see this is an Apple issue with that control not supporting it. Sorry.
