### ISSUE TITLE
Android - CollectionView DataTemplate with ContentView Content binding causes error when scrolling

### ISSUE THREAD

**Issue by kklose23** [dotnet/maui#20560]
### Description

After scrolling up and down a few times, I get an error saying `Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.'`

### Steps to Reproduce

1. Create a ObservableCollection in a view model, with an item that contains a property `public IView View { get; set; }`
2. Create a CollectionView with a DataTemplate that has the following `<ContentView Content="{Binding View}" />`
3. Scroll up and down a bunch so the CollectionView items get recycled

### Link to public reproduction project repository

https://github.com/kklose23/collectionview-contentview

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
@kklose23 using a view as data in this fashion isn't really supported. If you want to use different views for your template then I'd recommend using a DataTemplateSelector. 

Because of how platform cell reuse works, your view will get moved around to other cells which will cause the exception you are seeing.
