### ISSUE TITLE
Connectivity.Current.ConnectivityChanged += Connectivity_ConnectivityChanged; event is not raised

### ISSUE THREAD

**Issue by FrancescoGiancristofaro** [dotnet/maui#20645]
### Description

Seems to be only in Android 14

### Steps to Reproduce

1. Create a new project
2. Override OnStart in App.xaml.cs
3. Add event handler: Connectivity.Current.ConnectivityChanged += Connectivity_ConnectivityChanged;

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
This should be fixed by https://github.com/dotnet/maui/pull/19968, which is merged but not in a stable build yet. Could you try the nightly builds?

**Comment by AramMar** [comment]
Hi
in what version is it expected to be? thanks.

**Comment by drasticactions** [comment]
In terms of stable, my guess would be whatever the next service release is? I'm not on the MAUI team and I don't know the exact timetable and release schedule for when fixes roll out.

But you can try a [nightly build](https://github.com/dotnet/maui/wiki/Nightly-Builds) since that does include the PR code I linked to, so you can try it now to see if it works, then when it does get release in a stable release you can switch back to it.
