### ISSUE TITLE
Pixelated Edges on Splashscreen on Android

### ISSUE THREAD

**Issue by mlxyz** [dotnet/maui#20823]
### Description

On Android, when using a svg file as splashscreen and setting a high-res base size, the resulting splashscreen image has pixelated edges
![grafik](https://github.com/dotnet/maui/assets/25569187/2743777b-d7d0-4ae7-90bf-71025e3747c2)

Lower base sizes remove the pixelation, but make the imager blurry/low res. Everything works fine on ios.

It happens on physical device and emulator.

Installed Workload Id      Manifest Version       Installation Source
-------------------------------------------------------------------------------------
maccatalyst                17.2.8004/8.0.100      VS 17.9.34414.90, VS 17.8.34601.278
ios                        17.2.8004/8.0.100      VS 17.9.34414.90, VS 17.8.34601.278
maui-windows               8.0.6/8.0.100          VS 17.9.34414.90, VS 17.8.34601.278
android                    34.0.52/8.0.100        VS 17.9.34414.90, VS 17.8.34601.278

### Steps to Reproduce

1. Add svg to Resources/Splash
2. Add `<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#F3F7FE" BaseSize="1024,1024" />` to .csproj
3. Deploy to Android

### Link to public reproduction project repository

https://github.com/mlxyz/maui-pixelated-splashscreen-repro

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

**Comment by mlxyz** [comment]
@asi-evin Thanks for looking into this.
Setting the base size to 288 (no background logo) does remove the pixelated edges but makes the whole logo look blurry:
![Screenshot_20240228-083015](https://github.com/dotnet/maui/assets/25569187/3a4ab7f3-f04b-4f6c-abd0-4d6ae2649271)


I checked the generated images and they look fine - no blur and no pixelation. So is it a device-specific display issue?

**Comment by asi-evin** [comment]
> @asi-evin Thanks for looking into this. Setting the base size to 288 (no background logo) does remove the pixelated edges but makes the whole logo look blurry:
> 
> I checked the generated images and they look fine - no blur and no pixelation. So is it a device-specific display issue?

I wish I knew myself. It could be that some of my phones are already low res, and thus it's just not noticable, or it's the OS version, I haven't found a pattern.

I do notice the maui splash xml file sets the width and height to 108, and then the gravity is set to fill, so maybe it's getting downsized then stretched? Hard to tell, and when I messed with it I ended up clipping the logo. If I find a solution or work-a-round, this will be the first place I post it.

**Comment by asi-evin** [comment]
Ok, here is what I can gather: when MAUI generates the splash style, it looks something like this:

```xml
<!-- Splash theme -->
    <style name="Maui.SplashTheme" parent="Maui.MainTheme.NoActionBar">
        <item name="maui_splash">true</item>
        <item name="android:windowBackground">@drawable/maui_splash</item>
        <!--
          Android 12+ specific settings
          See: https://developer.android.com/guide/topics/ui/splash-screen#set-theme
        -->
        <item name="android:windowSplashScreenBackground">@color/maui_splash_color</item>
        <item name="android:windowSplashScreenAnimatedIcon">@drawable/maui_splash</item>
    </style>
```

As you can see, it references a drawable xml, which will look like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
  <item android:drawable="@color/maui_splash_color" />
  <item android:drawable="@drawable/maui_splash_image" android:gravity="center" />
</layer-list>
```

And from there, it references ANOTHER set of drawables, one for API 31 or higher, and older phones:

```xml
<!-- Android 12 and up -->
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
	<item
		android:width="108dp"
		android:height="108dp"
		android:gravity="center">
		<bitmap
			android:src="@mipmap/android_splash_image"
			android:gravity="fill"
			android:mipMap="true"/>
	</item>
</layer-list>

<!-- Android under 12 -->
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
  <item>
    <bitmap
      android:src="@mipmap/android_splash_image"
      android:gravity="center"
      android:mipMap="true"/>
  </item>
</layer-list>

```

So I pulled these into my old xamarin.forms project, and I was able to re-create the issue. Here is what I notice:

**What I found:** For WHATEVER reason, when you put the bitmap into a layer-list with a resize item, the splash does two things:
1. There will be no rectangular clipping, as in the adaptive layer rule about 1/3 of your image being hidden no longer applies (still circular clipping if the OS does that).
2. There is some weird down/up scaling that happens, and this is what is causing the pixelated blurry look. Not as noticable on smaller screens.

This is where I'm lost, maybe someone more knowledgable than me about how android works can explain this.

**What fixed it**: Instead of having a separate drawable xml file, just reference the image directly in the styling like so:

```xml
    <item name="android:windowSplashScreenAnimatedIcon">@drawable/android_splash_image</item>
```

Then you get the expected behaviour:
- The adaptive layer rules now apply, as in 1/3 of our image is hidden.
- Image is clear and crisp
- Doesn't matter how big the image is; Android will mipmap-scale it to the proper size.

Looking online, I see no official android splash examples that use a layer list with a resized item, so not sure where the MAUI team got this idea, although I suspect it may have to do with how splash screen USED to be made.

**Solution:** Obviously reference the image directly in the style but...

**Repercussions:** 
- Will this break existing projects?
- Is making sure our splash conforms to the adaptive icon hidden area rules necessary, since this is not how it works on iOS and windows?

**Work-a-round:**
I'm afraid I don't have one yet, but probably just have a custom style on startup that switches to MAUI when it's complete like so:

```c#
[Activity(Theme = "@style/Custom.Splash", ... ]
public class MainActivity : MauiAppCompatActivity
{

...

```

```xml
<style name="Custom.Splash" parent="Theme.SplashScreen">
	<item name="windowSplashScreenBackground">@color/maui_splash_color</item>
	<item name="windowSplashScreenIconBackgroundColor">@color/maui_splash_color</item>
	<item name="windowSplashScreenAnimatedIcon">@drawable/android_splash_image</item>

        <!-- item to switch themes -->
	<item name="postSplashScreenTheme">@style/Maui.SplashTheme</item>
</style>
```

I have NOT tried the above, I suspect styles may get overwritten anyhow, but worth a shot.

**Comment by mlxyz** [comment]
@asi-evin Thanks for the detailed investigation. Unfortunately, I had no success adding the custom style as a workaround due to build errors (`resource drawable/android_splash_image (aka ...:drawable/android_splash_image) not found.`). Looks like we'll have to wait for an official fix.

**Comment by asi-evin** [comment]
So, I did end up doing another deep dive, as a new phone revealed the same problem. Turns out that this is an Android bug that affects even their own apps so I filed a bug report there: https://issuetracker.google.com/issues/328559559

If you want smooth splash images, you need to create an animated vector. It turns out it's not too difficult though:

https://medium.com/geekculture/introduction-to-animated-vector-drawable-avd-for-android-8db301ad0776
https://shapeshifter.design/

If you need help, let me know, but I think we can close this issue unless the MAUI team wants to pivot this issue to generating an AVD that fades in quickly, which wouldn't be too difficult so long as the splash supplied is an SVG. You can use the following as a simple template to create a quick-and-dirty AVD, you just need to replace ```pathData``` and ```fillColor```.

```xml
<animated-vector
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt">
  <aapt:attr name="android:drawable">
    <vector
        android:name="vector"
        android:width="288dp"
        android:height="288dp"
        android:viewportWidth="288"
        android:viewportHeight="288">
      <path
          android:name="path"
          android:pathData="M 215.25 184.96 C 215.25 ... (etc)"
          android:fillColor="#ffffff"
          android:strokeWidth="1"/>
    </vector>
  </aapt:attr>
  <target android:name="path">
    <aapt:attr name="android:animation">
      <objectAnimator
          android:propertyName="fillColor"
          android:duration="300"
          android:valueFrom="#00000000"
          android:valueTo="#ffffff"
          android:valueType="colorType"
          android:interpolator="@android:interpolator/fast_out_slow_in"/>
    </aapt:attr>
  </target>
</animated-vector>
```

**Comment by mlxyz** [comment]
Thanks again for the detailed investigation @asi-evin, incredible!
I will close this issue as this is caused by an Android bug, not MAUI.
