### ISSUE TITLE
ProgressColor does not work on Mac Catalyst with the macOS UI Idiom

### ISSUE THREAD

**Issue by piersdeseilligny** [dotnet/maui#20876]
### Description

If you set an app to use the [MacOS UI Idiom](https://learn.microsoft.com/en-us/dotnet/maui/mac-catalyst/user-interface-idiom?view=net-maui-8.0) by updating `Platforms/MacCatalyst/Info.plist` to:

```
<key>UIDeviceFamily</key>
<array>
  <integer>6</integer>
</array>
```

Then the `ProgressColor` property of `ProgressBar` no longer works.

I haven't been able to find any workaround either, even the following does not seem to work:
```
Microsoft.Maui.Handlers.ProgressBarHandler.Mapper.AppendToMapping("TintProgressBar", (handler, view) =>
        {
            if (handler != null && handler.PlatformView != null)
            {
                handler.PlatformView.ProgressTintColor = UIColor.Red;
            }
        });
```

### Steps to Reproduce

1. Create a new .maui app
2. [Set the UI Idiom to MacOS](https://learn.microsoft.com/en-us/dotnet/maui/mac-catalyst/user-interface-idiom?view=net-maui-8.0)
3. Add a ProgressBar and set ProgressColor 

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

**Comment by drasticactions** [comment]
This is a limitation of the Desktop Idiom on Mac Catalyst, not a MAUI bug.

<img width="1114" alt="スクリーンショット 2024-02-28 18 04 30" src="https://github.com/dotnet/maui/assets/898335/daf71b06-f8de-4b2f-ab7d-6346a98ba9cb">

<img width="1058" alt="スクリーンショット 2024-02-28 18 06 04" src="https://github.com/dotnet/maui/assets/898335/09cb2997-31b1-4c2b-9de3-17aa4f41a1c7">

I wrote a UIProgressView in Swift with the desktop idiom set; it also doesn't show the color you set the tint to, where it will when set to iPad mode (or run on an iPhone/iPad). It uses your systems accent color instead and as far as I can tell there's no way to override it. Some UIKit controls have a "preferredBehavioralStyle" property where you can set the specific control to use an iPad or Mac behavior, but that apparently doesn't exist for UIProgressView. So you're stuck with the global default.

This cannot be fixed in MAUI or the .NET Bindings; it's a part of the platform and would have to be addressed with Apple. Sorry.
