### ISSUE TITLE
FlexLayout doesn't scroll. | MAUI.NET USING .NET 8

### ISSUE THREAD

**Issue by kelputoo123** [dotnet/maui#20890]
### Description

Im trying this in a Xiaomi targeting to Android 12.0 (API 31) using .NET 8. 
I've created a FlexLayout inside of a Scrollview and it doesn't scroll.
Everything is updated to the lastest versions.
This is a problem that i've also found reported back in 2022, but Microsoft did nothing with this, so im going to still report it, because i really need the Flexlayout in this case to make it works, and Microsoft should fix this,.

What's even more unfair, is that, i saw reports like this:
[https://github.com/dotnet/maui/issues/6881](https://github.com/dotnet/maui/issues/6881)
being closed saying "not repro" when a lot of people is complaining about this.

### Steps to Reproduce

1. Create a .NET Maui Project
2. Use this code:
```
<Grid>
    <ScrollView>
       <FlexLayout Wrap="Wrap" JustifyContent="SpaceAround">
                 ...
       </FlexLayout>
   </ScrollView>
</Grid>
```
3. Doesn't work! :(

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 12.0 (API 31) using .NET 8. 

### Did you find any workaround?

No, i tried to add Orientation method in ScrollView but nothing really worked.

### Relevant log output

```shell
No,
```

**Comment by drasticactions** [comment]
Can you please create a repro case with some UI showing it? Having a repro project will make it easier for those on the MAUI team to debug this and make sure all sides are seeing the same thing. I.E if I make my own sample and it works, then there's a chance you may have something different or I'm doing something wrong. And having a sample will make it easier to create component tests around it should there be an issue to fix.

**Comment by jfversluis** [comment]
> What's even more unfair, is that, i saw reports like this: https://github.com/dotnet/maui/issues/6881 being closed saying "not repro" when a lot of people is complaining about this.

If we can't reproduce it on our side it's hard to fix. A lot of people seem to indicate that something is wrong, so there probably is, but if we can't see if for ourselves it's near impossible to determine what the root cause is, let alone how to fix it. 

That is the same for this issue, you provide a code snippet, but chances are there is more in your project that might influence this behavior. Please add a public repository with a reproduction project so we can see the full project and all the factors that might be an influencing factor here. That will help us find the problem quicker and the potential fix will come sooner.
