### ISSUE TITLE
Bugs in catching error.

### ISSUE THREAD

**Issue by SoumyadipYT-OSS** [dotnet/maui#20948]
### Description

![IMG_20240301_235410112](https://github.com/dotnet/maui/assets/94290293/9ad924ca-6f01-4a70-9660-25732fb76516)
In this program I have used <Grid> property, here we can the <SearchBar> property is used once but still it is showing "The property 'Content' is set more than once", other ListView and Border too. Is there any solution of this problem?

### Steps to Reproduce

![IMG_20240301_235410112](https://github.com/dotnet/maui/assets/94290293/fc49f98b-49b3-4cb2-a1eb-cb89f5b5cc7a)

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

8.0.0-rc.2.9511

### Affected platforms

Android

### Affected platform versions

Android emulator pixel 5 api 32

**Comment by jfversluis** [comment]
The problem is that you're putting both a `SearchBar` and a `ListView` inside of a `Border`. A `Border` is not made to contain multiple children. If you want that, you'll need a layout like a `HorizontalStackLayout` or a `Grid`. Things like a `Border` or any page can only have 1 child. Layouts can have multiple.

The error message is a bit cryptic, but it refers to the "content" of the `Border`, which is specified more than once.

Hope that helps!

**Comment by SoumyadipYT-OSS** [comment]
Another bugs is arises that I can't use StrokeDashArray="0, 1,0" in Border property. It there any new syntax for this attribute in dotnet 8 LTS?

**Comment by SoumyadipYT-OSS** [comment]
Got the solution for this problem, you should not use commas (,) in the value of the StrokeDashArray property
