### ISSUE TITLE
[Bug] Unable to run maui or maui-blazor template WinUI option from Visual Studio

### ISSUE THREAD

**Issue by rt121212121** [dotnet/maui#2100]
### Description

I create the template, open VS2022, run the WinUI option, and I see an error.

### Steps to Reproduce

1. `dotnet new maui-blazor -n MauiBlzor`
2. Open VS2022 and open the MauiBlzor project.
3. Select the MauiBlzor entry and debug/run it.
4. Observe that it fails due to "target Run does not exist for the project".

### Expected Behavior

Not this. A window should open and show some ui like for the Android emulated version.

### Actual Behavior

msbuild process errors.

### Basic Information

- Version with issue: Fresh VS2022 preview 7 install with all extra MAUI bits.
- Last known good version: Never run it.
- IDE: VS2022 preview 7
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![maui-vs2022](https://user-images.githubusercontent.com/32600614/129434441-09d88b0a-092f-49b0-9b3f-12d208d4e156.png)

### Reproduction Link

See the steps above.

### Workaround

There is another issue on maui-samples talking about using `--no-restore` but that is on the command-line, and does not apply here as there is no place for me to put it in the VS2022 UI that I understand.

**Comment by Eilon** [comment]
Hi @rt121212121 , which platform target of the app were you trying to run: Android, Windows (WinUI), or something else?

**Comment by rt121212121** [comment]
WinUI. Android works fine and presumably MacOS does too if I have a developer certificate.

**Comment by Eilon** [comment]
@rt121212121 for WinUI there should be a separate project called "MyProjectName.WinUI" that you need to set as your startup project, and then deploy/run that one. Do you have that project in the solution?

**Comment by rt121212121** [comment]
This is what happens when I set that as startup and debug it.

![image](https://user-images.githubusercontent.com/32600614/129613206-2a7e6c5c-70cd-4fe2-8d3f-4dc776957c81.png)

**Comment by rt121212121** [comment]
51 errors. This is the MauiBlazor template, I right clicked on the WinUI project and selected Deploy.
![image](https://user-images.githubusercontent.com/32600614/129638556-76c4ad07-1b73-4fbc-ac55-3e2e33aca7db.png)

**Comment by rt121212121** [comment]
Yes, deploy works, just tested with MauiBlazor template.

**Comment by Eilon** [comment]
And you can then run the app from the Start Menu?

If so, then that is currently all that works, and we're working on getting the regular VS experience to work properly, but it wasn't in time for the most recent preview. It makes debugging a bit more difficult because you can't _start_ the app with the debugger attached. Instead, you can run the app from the Start Menu, and then attach the VS debugger to the process, and debug as usual.

**Comment by rt121212121** [comment]
Yes, it runs from the start menu, I classify that as "deploy works".  It would be good if you could document all these foibles and provide people one easy place to go do, as I spent quite a bit of time burning attention and willpower to play with this. I'm quite excited about Maui, and can see the potential of the blazor approach and am looking forward to when it's all in shape.

**Comment by Eilon** [comment]
@rt121212121 yup, understood, this is definitely a frustrating issue right now but I just heard there is a fix for this coming soon.

**Comment by Zachael** [comment]
I'm able to deploy a Maui WinUI sample application. However, it does not run from the start menu. It starts and then exits.

**Comment by Almis90** [comment]
> @rt121212121 ah, that might be a current issue with VS and WinUI projects. Can you right-click on the WinUI project and select "Deploy" and then run the app from the Windows Start Menu? Please see the note at the end of the preview 7 blog post: https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-7/#feedback-welcome

For some reason I don't see the deploy option on WinUI project, it is available only for the other project without the appendix

**Comment by Eilon** [comment]
@Almis90 if the Deploy option isn't showing up, it could be that you need to install this VS extension: https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17

**Comment by tinmac** [comment]
@Eilon I have the Single Project MSIX packaging tools installed & I dont see the deploy option??

**Comment by MaxxDelusional** [comment]
I am getting the "Unable to start debugging" error message when WinUI is set as my startup project. 

I am also unable to deploy. It just says "Deploy Failed" with tno further information.  

Single Project MSIX Packaging Tools extension is installed.

**Comment by Eilon** [comment]
@tinmac / @MaxxDelusional - can you confirm that:

1. You have **Visual Studio 2022** installed, with all updates applied
2. Check that you installed the **VS2022** version of the MSIX tools (There is another version for older Visual Studio)
   * You can check this by opening Visual Studio 2022, going to `Extensions` / `Manage Extensions`
   ![image](https://user-images.githubusercontent.com/202643/132406450-d78d85b4-665f-49f4-8447-93a658e66461.png)
   * Then go to `Installed` / `Tools` and check that you have this item:
   ![image](https://user-images.githubusercontent.com/202643/132406796-88504ca0-8540-4526-99f9-75306bb80d58.png)
   * If you don't have it, download and install this: https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17
   * And then restart Visual Studio

**Comment by dhindrik** [comment]
I didn't have it installed. So I installed it, but I still have the same problem. But I run VS2022 on Windows 11 ARM in parallels on Mac M1 so that can maybe be one reason that it does not work for me.

I will get this error when I try to deploy:

`Error |   | DEP0700: Registration of the app failed. [0x80073CF3] Windows cannot install package 18E11229-B113-4F71-A9E6-81B3E6E6DC1B_1.0.0.0_neutral__9zz4h110yvjzm because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.Debug.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or ARM64 processor architecture and minimum version 14.0.30035.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.Debug.UWPDesktop" currently installed are: {} | MyLife.WinUI |   |   |  
`

<img width="279" alt="Screenshot 2021-09-08 at 09 12 32" src="https://user-images.githubusercontent.com/6691971/132463771-49979655-2194-4448-b851-16c26bbf98cf.png">

**Comment by Eilon** [comment]
Oh boy, Win11 ARM in Parallels on a Mac M1. You might be the first one to try this combo with .NET MAUI! 😁

Just a guess, but can you open the Visual Studio Installer, and for your VS2022 installation click "Modify", then go to "Individual Components" and type in `arm64` in the search box. Check that you have these installed:

* `C++ Universal Windows Platform support for v143 build tools (ARM64)`
* `MSVC v143 - VS 2022 C++ ARM64 build tools (latest)`

![image](https://user-images.githubusercontent.com/202643/132544358-ee8665c1-fc27-4487-b54e-5a6197a39776.png)

I'm not at all certain if this is the issue because I'm not familiar with the exact requirements for this scenario.

**Comment by dhindrik** [comment]
It worked to deploy it now. But I am not able to start it. I find this in the event viewer.

```
Application: MyLife.WinUI.exe
CoreCLR Version: 6.0.21.37719
.NET Version: 6.0.0-preview.7.21377.19
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.BadImageFormatException:  is not a valid Win32 application. (0x800700C1)
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName) in Microsoft.WinUI.dll:token 0x6000023+0x6e
   at Microsoft.UI.Xaml.Application._IApplicationStatics..ctor() in Microsoft.WinUI.dll:token 0x601388f+0x1c
   at System.RuntimeType.CreateInstanceOfT() in System.Private.CoreLib.dll:token 0x60006ca+0x3e
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceOfT() in System.Private.CoreLib.dll:token 0x60006ca+0x4e
   at System.Activator.CreateInstance[T]() in System.Private.CoreLib.dll:token 0x60009ef+0x0
   at WinRT.WeakLazy`1.get_Value() in Microsoft.WinUI.dll:token 0x6000019+0x20
   at Microsoft.UI.Xaml.Application._IApplicationStatics.get_Instance() in Microsoft.WinUI.dll:token 0x6013890+0x0
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback) in Microsoft.WinUI.dll:token 0x6009288+0x0
   at MyLife.WinUI.Program.Main(String[] args) in MyLife.WinUI.dll:token 0x60000de+0x21
```

**Comment by Eilon** [comment]
@dhindrik are you able to run any other WinUI app that you create in VS?

Also, there was a new preview released earlier this week. Can you try updating to the latest VS2022 and try with that?

**Comment by lejando** [comment]
I face the same issue as @dhindrik with Version 17.0.0 Preview 4.1, so this bug is still present.

**Comment by nextfool** [comment]
> I face the same issue as @dhindrik with Version 17.0.0 Preview 4.1, so this bug is still present.

I have exactly the same .

**Comment by nextfool** [comment]
> @rt121212121 for WinUI there should be a separate project called "MyProjectName.WinUI" that you need to set as your startup project, and then deploy/run that one. Do you have that project in the solution?

Hi @Eilon I am new to .net MAUI. So today (2021-09-24) I downloaded and installed the vs 2020 preview 4.1 from the official website , which should be the latest release. Now when I created new apps(both .net MAUI app and .net MAUI blazor app), I only see one single projects created. so there is NO ProjectName.WinUI created. And I can not debug it. the error is exactly the same.

**Comment by Eilon** [comment]
Starting with the most recent preview (from earlier this month), new MAUI projects contain only 1 project that has all supported platforms on it. The separate MyProject.WinUI project is gone (it was a temporary workaround while things were in progress).

Please note that you have to edit the CSPROJ file to un-comment the Windows (WinUI) option, so please make sure you do that first.

**Comment by mattleibow** [comment]
This was fixed in preview 9 and will be even better in preview 10 coming out next week.
