### ISSUE TITLE
How to implement unit test project for maui class library?

### ISSUE THREAD

**Issue by KarthikRajaAKR** [dotnet/maui#2112]
Is there any documentation or sample available for creating unit test project for Maui under android and ios platforms?

**Comment by pictos** [comment]
Hey, @brminnick do you have any tips to share?

**Comment by brminnick** [comment]
I don't.

We're hitting the same problem ourselves trying to unit test the [.NET MAUI Toolkit](https://github.com/communitytoolkit/maui).

👇 Gerald commented on this issue. I'm hoping for a fix.
https://github.com/microsoft/vstest/issues/2985#issuecomment-897569773

**Comment by Daniellled** [comment]
This also appears to be an issue on Windows too - https://github.com/dotnet/maui/issues/2594

**Comment by Eilon** [comment]
Might be nice to have a template for this in the future, but there's a recent PR that, once merged, also includes a small test project sample:

https://github.com/dotnet/maui/pull/3017/files

**Comment by jayveedee** [comment]
Anyone figure out how to do this? Or is it not possible as of yet?

**Comment by brminnick** [comment]
> Anyone figure out how to do this? Or is it not possible as of yet? 

Hi @jayveedee! This Issue was resolved months ago (and should be closed).

For the [.NET MAUI Community Toolkit](https://devblogs.microsoft.com/dotnet/introducing-the-net-maui-community-toolkit-preview/?WT.mc_id=mobile-0000-bramin), we created our Unit Test suite using Xunit. The project is open source and you can see how we've implemented our Unit Tests here: https://github.com/CommunityToolkit/Maui/tree/main/src/CommunityToolkit.Maui.UnitTests
