### ISSUE TITLE
MAUI Application performance issue.

### ISSUE THREAD

**Issue by VaibhavMethuku01** [dotnet/maui#21262]
### Description

Currently we are developing the MAUI application with .Net 7. 

The UI is being created dynamically in the run time
[Code Files.zip](https://github.com/dotnet/maui/files/14633239/Code.Files.zip)
 Here the major issue is from the function BuildCurrentProposedStateParameters() - ProgramEntryPage.Xaml.cs which works with the huge amount of data.
 
[Output.txt](https://github.com/dotnet/maui/files/14632950/Output.txt)
Please find the attached output for reference.

Thanks
Vaibhav Methuku.

### Steps to Reproduce

When Navigating from the landing page to the sub page UI is rendering and at the same time navigating back to landing page and navigating to the same page(sub Page). The UI is being struck and no further UI rendering is happening.

### Version with bug

7.0.49

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by jfversluis** [comment]
Is there any specific reason that you are on .NET 7 and not .NET 8? 

.NET 7 will be [out of support](https://dotnet.microsoft.com/platform/support/policy/maui) soon (May 14, 2024) and there should be no reason for you to not be on .NET 8.

Additionally, there are some resources you could use to dive into this and investigate where this might come for:
* Profiling your .NET MAUI app: https://github.com/dotnet/maui/wiki/Profiling-.NET-MAUI-Apps
* Diagnosing memory leaks: https://github.com/dotnet/maui/wiki/Memory-Leaks
* An extensive description of the improvements for .NET MAUI performance in .NET 8: https://aka.ms/mauiperf8

Additionally, looking at your log output I see a lot of resource files that could not be found which might impact performance here, so that might be something to look into.

Since this is issue does not seem to describe any issue with the .NET MAUI SDK (yet) I'd suggest that you try the above suggestions first and gather more information about what the actual problem is. If you think that this is something that is in .NET MAUI and not your own codebase, please feel free to open a new issue, with all the uncovered info, and we'll have a look, thanks!
