### ISSUE TITLE
Raw asset added to MauiApp replicates the source folder structure in the destination instead of adding it to the assets folder in Android

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#2145]
### Description
Raw asset added to MauiApp replicates the source folder structure in the destination instead of adding it to the assets folder in Android

### Steps to Reproduce

1. Create a new .NET MAUI project, add a folder titled `Raw` under the `Resources` folder and then add an HTML file to it
2. Update the `BuildAction` of that HTML file as `MauiAsset`
3. In any of the Xaml pages, add a `WebView` and set the Source to the Name of the HTML file (with extension)
4. Set Android as the target, do build and run the project
5. Ends up in the **Web page not available** error, refer to the screenshot for details

<img width="721" alt="MauiAsset-Issue" src="https://user-images.githubusercontent.com/81947404/129840579-31191ecc-773b-4933-985f-54c119fbcd09.png">

Note: Fonts are added properly to the assets root folder.

### Expected Behavior
The HTML page, from the assets folder, should be displayed in the WebView

### Actual Behavior
Ends up in Web page not available error.

### Basic Information

- Version with issue: **.NET 6 Preview 7** (6.0.100-preview.7.21379.14)
- Last known good version: **NA**
- IDE: VS2022 17.0.0 Preview 3.1
- Platform Target Frameworks: 
  - iOS:  
  - Android:  **Target API Level 30**
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![Screenshot_20210818-104802](https://user-images.githubusercontent.com/81947404/129841581-d733a5d0-06b1-4064-b5cb-0dcc4d166aeb.png)

**Comment by mindtalk69** [comment]
Hi, 

I thought https://github.com/dotnet/maui/pull/735 status should be relevant with our issue here.

So, curious also tested with environments like these,

-  **VS 2022 Preview 4.1**
- Single Solution Project , android , ios, catalyst including windows.


**Step Reproduce**
- Create new clean project with MauiApps
-  under Resources directory create new folder Raw
-  Insert file index2.html under Resources directory Raw
- Change the the build action as MauiAsset 
- make sure MauiAssets tag include in projects
 - write main.xaml at <webview source = "index2.html"  />
 
![image](https://user-images.githubusercontent.com/84576926/135807338-60331fc0-06b4-46bb-8a46-58d7472fb0d3.png)


Debug Result on Android
![image](https://user-images.githubusercontent.com/84576926/135801164-dc1f7fb1-4ae3-4b3b-b923-f9d5347eeb01.png)

Project file 
![image](https://user-images.githubusercontent.com/84576926/135803904-e5e1584a-cb39-4e34-8424-d726ecb88216.png)

Output
![image](https://user-images.githubusercontent.com/84576926/135806838-be5725b0-f204-4f09-bbd6-4d85702cc11f.png)

Structure Project
![image](https://user-images.githubusercontent.com/84576926/135806930-cff865b6-9dce-4aca-9aac-02d48302e69d.png)

Regards

**Comment by Eilon** [comment]
We're planning on making some improvements to MauiAssets per this comment: https://github.com/dotnet/maui/issues/3270#issuecomment-1023724641

However, replicating the folder structure in this _exact case_ is by design, though our plan for the default project templates is to remove the common prefix `Resources\Raw` by setting the MSBuild `LogicalName` on each item (which currently doesn't always work due to a bug!). It would end up looking something like this in your CSPROJ file:

```msbuild
<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
```

This MSBuild item says that the destination of each item (per the LogicalName) is whatever the `**` of the `Include` specifies, meaning that `Resources\Raw` will NOT be in the destination app. A file `Resources\Raw\Folder\File.txt` will end up as an app resource located in `<App Resource Root>\Folder\File.txt`.
