### ISSUE TITLE
Icon missing  when switching to another app in iOS

### ISSUE THREAD

**Issue by mrjcitadel** [dotnet/maui#21475]
### Description

The icon on top is not reflecting when I am try to switch the app.
Icon is fine on the app drawer.

![nNsp9uBNvp](https://github.com/dotnet/maui/assets/161680740/844e7dfb-8bd5-40ad-b35e-905db2c1cbdf)

### Steps to Reproduce

using svg file as App Icon
and this command on publishing "dotnet publish -f net8.0-ios -c Release -r ios-arm64"

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iPhone 11 iOS 17.3.1

### Did you find any workaround?

Not yet

**Comment by jfversluis** [comment]
Thanks for the report! Based on just this information it will be pretty hard to diagnose what might be going on.

If you can provide a [reproduction project](https://github.com/dotnet/maui/blob/main/.github/repro.md) which also shows this behavior we can comb through that project to see if there is anything suspicious there.

Another thing you might try is to try another Simulator or device and maybe really delete the app first. This happens sometimes due to caching on iOS.

Without any form of reproduction or logs or icons that are in your app bundle it will be impossible for us to track down what might be going on here.
