### ISSUE TITLE
Declared IsGestureEnabled = false but Flyout menu is still work on MAUI .NET8 Android

### ISSUE THREAD

**Issue by ThinhKVT** [dotnet/maui#21522]
### Description

Hi,
We had set "IsGestureEnabled = false" but flyout menu still appear when swipe left to right from the edge of the screen from our application. The issue is only happening on .NET8 MAUI project on Android devices. We tried on default project and the behavior is similar. 
So, is this issue of .NET8 on Android platform? We had tried on .NET7, but it's worked normally.
Please help us for resolving the issue.
Thank all ~!

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by Pastajello** [comment]
Maannn... do I have a good news for you. 
I happened to experience the same issue, didnt inestigate it very much, but from the source code i got the solution.
The issue is easily workaroundable if you create a custom handler for FlyoutPage on Android:

the main bits are:

` 
     
     public class CustomFlyoutViewHandler : FlyoutViewHandler
    {
        DrawerLayout DrawerLayout => (DrawerLayout)PlatformView;

        protected override void ConnectHandler(global::Android.Views.View platformView)
        {
            base.ConnectHandler(platformView);
            var page = (FlyoutPage)VirtualView;
            page.PropertyChanged += Page_PropertyChanged;
        }

        protected override void DisconnectHandler(global::Android.Views.View platformView)
        {
            var page = (FlyoutPage)VirtualView;
            page.PropertyChanged -= Page_PropertyChanged;
            base.DisconnectHandler(platformView);
        }

        private void Page_PropertyChanged(object? sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            if (e.PropertyName == FlyoutPage.IsGestureEnabledProperty.PropertyName)
            {
                var page = (FlyoutPage)VirtualView;
                if (page.IsGestureEnabled)
                {
                    DrawerLayout.SetDrawerLockMode(DrawerLayout.LockModeUnlocked);
                }
                else
                {
                    DrawerLayout.SetDrawerLockMode(DrawerLayout.LockModeLockedClosed);
                }
            }
        }
    }`


and then you put register the handler with something like this:

                   ` handlers.AddHandler(typeof(AppFlyout), typeof(CustomFlyoutViewHandler));`

**Comment by Pastajello** [comment]
It seems the issue is 'caused' by Details PlatformView being null, so setting the IsGesturesEnabled in xaml on the Flyoutpage will always fail.
<img width="602" alt="image" src="https://github.com/dotnet/maui/assets/28345098/7b291dcb-ad65-4627-9ebc-d74036eba28c">

Setting IsGesturesEnabled = false WILL work if you set in in the "Loaded" event of details page.

` 
                     var page = new FlyoutPage

			{
				Title = "asd",
				FlyoutLayoutBehavior = FlyoutLayoutBehavior.Split
			};
			var detail = new ContentPage()
			{
				Title = "detail",
			};
			detail.Loaded += (a, s) =>
			{
				page.IsGestureEnabled = false;
			};
			page.Detail = detail;
			page.Flyout = new ContentPage() { Title = "Flyout" };
			`

**Comment by ThinhKVT** [comment]
The issue is fixed. Thank all for your solutions.

**Comment by jfversluis** [comment]
Thanks for letting us know!
