### ISSUE TITLE
ShellContents navigation to the same ContentTemplate .Net Maui

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#21585]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ShellContents-navigation-to-the-same-Con/10622655)._

---
[severity:It's more difficult to complete my work]
In my AppShell.xaml i have defined a layout as this:
<FlyoutItem FlyoutDisplayOptions="AsMultipleItems">
        <ShellContent  ContentTemplate="{DataTemplate local:Dashboard}" Route="Iesiri" Title="Iesiri" Icon="icon_iesiri_flyout"/>

        <ShellContent ContentTemplate="{DataTemplate local:Dashboard}" Route="Clienti" Title="Clienti" Icon="icon_clienti_flyout"/>

        <ShellContent ContentTemplate="{DataTemplate local:Dashboard}" Route="Articole" Title="Articole" Icon="icon_produse_flyout"/>
</FlyoutItem>

I want to have 3 items that are navigating to the same page, and based on the item clicked, in page Dashboard i want to perform an action like this:

protected override async void OnAppearing()
    {
        _vm.OnAppearing();

        var currentState = Shell.Current.CurrentState;
        var route = Shell.Current.CurrentState.Location.OriginalString;
        switch (route)
        {
            case "//Iesiri":
                await ChangeModCurent(ModCurent.Iesire);
                break;
            case "//Articole":
                await ChangeModCurent(ModCurent.Produse);
                break;
            case "//Clienti":
                await ChangeModCurent(ModCurent.Clienti);
                break;
            default:
                break;
        }

If i press on Iesiri the logic performs fine. If i press on Articole, the logic performs fine. Then, if i press on Iesiri again, the current route is still //Articole. That goes with every combination i try. How can i fix this? Or if there is any better way to handle this logic, im totally open to it.

---
#### Feedback Bot on 3/24/2024, 06:44 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by JamesBrooksbankIceland** [comment]
So, i've had to develop a solution doing something similar to what you have done. I didn't proceed using the shell content in the same manner so this may not solve your solution but may give you an idea on how to get something working.

So i used the IQueryableInterface on the view model and when navigating to the page via shell i passed a dictionary item with a field in it which when the ApplyQueryAttributes event runs, i stored the value from the dictionary item in a private variable, then when the onappearing event fires i use that private variable to run the logic that i require. 

I've also done this with the shell menu bar, but didn't want to rely on the Maui app shell contents forming the menu so i used my own buttons with events which ran the navigation. 

This may seem a bit long winded but it worked for me. Just something to think about which may get you past the point until someone offers a reliable reason why your problem is occurring.
