### ISSUE TITLE
Starts running and pause in Program.cs

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#21598]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Starts-running-and-pause-in-Programcs/10582660)._

---
Starts running for both OS (iOS and Android) and when the splash screen is displayed, it pauses (apparently in Program.cs) and if play is hit, stops the execution.

---
#### Feedback Bot on 2/11/2024, 01:01 AM: 

(private comment, text removed)
#### Nina Chen [MSFT] on 2/18/2024, 10:12 PM: 

(private comment, text removed)
#### Luis Souza on 2/19/2024, 07:56 AM: 

(private comment, text removed)
#### Luis Souza on 2/19/2024, 00:40 PM: 

(private comment, text removed)
#### Nina Chen [MSFT] on 2/20/2024, 06:38 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Looking through the logs in the linked feedback ticket I think this is the most important line: `BasedOn.TargetType is not compatible with TargetType`

Somewhere in your code there is probably a style defined that sets the `TargetType` to a type that is not compatible. Please go through the styles you have defined and comment them out or change them to see if that has any effect on this.

With the information given right now I would assume this is a error in your projects codebase rather than a bug with .NET MAUI.

Could you please share relevant code in regard to the styles you're using and/or let us know the results of you going over the styles in your code with this information?

Thanks!
