### ISSUE TITLE
.NET MAUI IOS APP CRASH on Launch Release Mode (From Azure CI/CD pipeline) after updating the MAUI.Controls to 8.0.20

### ISSUE THREAD

**Issue by thanigaiharan** [dotnet/maui#21770]
### Discussed in https://github.com/dotnet/maui/discussions/21769

<div type='discussions-op-text'>

<sup>Originally posted by **thanigaiharan** April 11, 2024</sup>
Updated the nugget to 8.0.20 for MAUI controls and CommunityToolkit.MAUI.Core to 8.0.1

https://github.com/dotnet/maui/discussions/21743

Note : Android is working Fine. </div>

**Comment by jfversluis** [comment]
Do you have a bit more detail? Is there any log output, error messages anything that you can share? From the title I understand that debug is working? If you downgrade to 8.0.14 it actually starts working on release again too? Are you sure this is because of the .NET MAUI NuGet and not the CommunityToolkit NuGet? And if so, what is it that makes you sure about it?

**Comment by thanigaiharan** [comment]
@jfversluis you are right, issue is happening due to CommunityToolkit.MAUI.Core to 8.0.1.
