### ISSUE TITLE
"Timespan.Days property not found" when production app released to iOS App Store

### ISSUE THREAD

**Issue by chuckgiddens** [dotnet/maui#21930]
### Description

App Insights is trapping an error that occurs ONLY when my iOS App is released on the App Store.  This works fine when I deploy in debug mode to my iOS device using VS 2022 on my Windows machine.  It works fine when using Simulator on my Mac.  This is really tough to deal with because there is no way to debug this.
![image](https://github.com/dotnet/maui/assets/5237149/5b8336c0-8b38-434c-b6ae-5cf3c04fe697)

### Steps to Reproduce

1. Create Maui App
2. Use Timespan.Days in XAML
3. Deploy and publish to iOS App Store
4. Run app...

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

All

### Did you find any workaround?

Nope

**Comment by drasticactions** [comment]
@rolfbjarne What do you think?

**Comment by rolfbjarne** [comment]
My guess this either happens because of different trimmer settings between Debug and Release, or because the interpreter is not enabled in release.

> App Insights is trapping an error that occurs ONLY when my iOS App is released on the App Store.

Does it happen if you try running the Release configuration locally?

That would be the first step: figure out how to reproduce the problem yourself.


Adding this to your csproj should make the configuration consistent between Debug and Release (with regards to trimmer + interpreter), and hopefully this will get a consistent behavior between both and then we can investigate deeper afterwards:

```xml
<PropertyGroup>
    <UseInterpreter>true</UseInterpreter>
    <TrimMode>partial</TrimMode>
</PropertyGroup>
```

**Comment by mattleibow** [comment]
It ill also be helpful to get some part of your XAML or a sample where this happens. I wonder if the Release build is removing some property as Rolf mentions.
