### ISSUE TITLE
[Bug] BlazorWebView crashes and goes black

### ISSUE THREAD

**Issue by markrendle** [dotnet/maui#2211]
### Description

After running for a while the BlazorWebView goes black, and if I have the F12 Dev Tools open it closes. Right-click on the app area has no effect after this happens.

I've tried attaching to the process from VS2022 but there's no output or exception showing up when this happens.

### Steps to Reproduce

1. Use my solution: https://github.com/rendlelabs/streambadger
2. Deploy and run because you can't Debug MAUI apps right now :(
3. Click around and wait for it to crash

### Expected Behavior

Should not crash

### Actual Behavior

Crashes

### Basic Information

- Version with issue: 6.0 Preview 7
- Last known good version: 6.0 Preview 6
- IDE: VS 2022 Preview 3.1
- Platform Target Frameworks: 
  - WinUI: 0.8.2 
- Nuget Packages:
  - MudBlazor 5.1.1
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/178242/130448719-c4aa202a-5464-488c-a59c-a2bb9bff729a.png)

### Reproduction Link

https://github.com/rendlelabs/streambadger

### Workaround

None

**Comment by Eilon** [comment]
Hi @markrendle , I updated the app locally to run against the latest .NET MAUI bits and I have it running locally on Windows and I clicked around with the debugger attached and F12 tools attached and it didn't crash for at least 15 minutes. I'm not quite sure what to do in the app either, though 😄

I made some small changes to get it running locally:
1. First I created a new .NET MAUI project from the latest build, and then copied the "app code" from the existing app into it, plus updated project references
2. I updated various package versions (MudBlazor 6.x, ASP.NET Core 6.0 RTM, etc.)
3. I added some checks for `if (Directory.Exists(_baseDirectory))` in `SoundStore` and `ImageStore`, or alternatively created the AppData folder locally (otherwise the app immediately crashes).
4. I changed the old IStartup pattern to the new MauiAppBuilder/MauiProgram pattern

And it seemed fine to me:

![image](https://user-images.githubusercontent.com/202643/145496865-bbca292f-737c-4198-a273-fba7bcac42aa.png)

If you do see this again, would you be able to run the app under the debugger with it set to catch **ALL** CLR exceptions?
![image](https://user-images.githubusercontent.com/202643/145497125-bfa03283-27e6-4f93-8041-3765f588a6ed.png)

There's a reasonable chance that whatever caused the BlazorWebView to stop working would somehow appear as a handled, but hidden, CLR exception. If we can find out what the exception is, plus the stack trace, that could help us figure out what's going on.

But, also, this could also be something that was fixed in the intervening months, so for now I'm closing this, but I'd love to hear if you see it again.
