### ISSUE TITLE
SetTitleBar not working on Windows

### ISSUE THREAD

**Issue by bdovaz** [dotnet/maui#22178]
### Description

I am trying to customize the titlebar in Windows by following these steps:

https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.window.settitlebar

But no matter what you do, the `SetTitleBar` call does nothing.

### Steps to Reproduce

```csharp
builder.ConfigureLifecycleEvents(events =>
{
    events.AddWindows(windowsLifecycleBuilder =>
    {
        windowsLifecycleBuilder.OnWindowCreated(window =>
        {
            window.ExtendsContentIntoTitleBar = true;
            window.SetTitleBar(new MyWindow().AppTitleBar);
        });
    });
});
```

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/20976#issuecomment-1977173364

**Comment by bdovaz** [comment]
> Here's some info on how to customize the titlebar
> 
> [#20976 (comment)](https://github.com/dotnet/maui/issues/20976#issuecomment-1977173364)

I tried that but the following happens to me:

```xml
<DataTemplate x:Key="MauiAppTitleBarTemplate">
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*"/>
            <ColumnDefinition Width="*"/>
            <ColumnDefinition Width="Auto"/>
        </Grid.ColumnDefinitions>
        <TextBlock VerticalAlignment="Center" Text="MyText" />
        <TextBlock VerticalAlignment="Center" Grid.Column="2" Text="MyText2" />
    </Grid>
</DataTemplate>
```

Output (as you can see, on the right side it overlaps with the buttons of the window):

(AppShell.xaml -> Shell.FlyoutBehavior="Disabled")

![image](https://github.com/dotnet/maui/assets/950602/44d09a29-f77b-44c8-ae0a-2f72d99de708)

(AppShell.xaml -> Shell.FlyoutBehavior="Flyout")

![image](https://github.com/dotnet/maui/assets/950602/59f1bc06-116c-4a32-ba77-71c489f2f8bc)

As you can see, even using this method I can't get it to work.

Besides, what you have not answered me is why `SetTitleBar` doesn't work, is it a MAUI bug? Am I doing something wrong? Because my idea was to follow the "Full customization" tutorial since I want the title bar to be interactive:

https://learn.microsoft.com/en-us/windows/apps/develop/title-bar#full-customization

**Comment by drasticactions** [comment]
I agree that what @PureWeen sent doesn't address your issue directly, but I don't think that "SetTitleBar" doesn't work, it's that you're not using it right, but you also couldn't because the way MAUI apps work. I'll try to explain my thought process.

- First, your example code is wrong. If you're building a WinUI app, you would need to pass in a `UIElement` contained within the existing `Window`. You're passing in a new element (I don't know the type, since you didn't provide a sample) so it's not connected to anything, so it won't work no matter what. 
- So you would, generally, build a WinUI Window, create a UIElement within that Window to represent the TitleBar, then call SetTitleBar with that element. While you can create a new MAUI Window (which itself is a WinUI 3 Window, wrapped), you can't directly set elements contained within it, at least not easily. 
- What @PureWeen's example does show is that the TitleBar is already abstracted within MAUI and you can add additional elements within that. _however_ to the best of my knowledge, elements contained within this TitleBar can't be interactive, apart from the hamburger menu on the left nav, because you would need further customization to allow buttons, etc, to be clickable.

So TL;DR

- `SetTitleBar` does work if you pass in a UIElement...
- But passing in a valid UIElement isn't trivial unless you hack underlying implementations of frameworks...
- But there is a TitleBar you can customize through the Platform XAML...
- But you probably can't add the elements you want to make it interactive without also hacking more of the window...

IMO, you would be better off using [MAUI Native Embedding](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/native-embedding?view=net-maui-8.0&pivots=devices-android) and creating a WinUI 3 app that contains MAUI Elements instead. That would give you full control of the WinUI 3 window without needing to deal with all of that overhead. I have an example of this [here](https://github.com/drasticactions/mauilang) that could help you do it.

**Comment by PureWeen** [comment]
You can set interactive regions here
https://github.com/dotnet/maui/blob/b183cae2982f7c318f796d202f5c811d4da0edd8/src/Controls/src/Core/Window/Window.Windows.cs#L27-L34
