### ISSUE TITLE
I can't create maui apps

### ISSUE THREAD

**Issue by jacintobengui** [dotnet/maui#22509]
I have already upgrade de visual studio and I installed the maui package but, when a go to create a project the maui app options doesn't appear.

**Comment by jfversluis** [comment]
This is unfortunately very little information to go on. Next time please include version numbers of Visual Studio and steps that you have already taken. This is probably also the reason why there was no real response here unfortunately. Higher quality reports will yield higher quality responses 😄 

Since this is a while old by now I hope you fixed this for you already, if not, please feel free to open something new and fill out the template as best as you can. If its more of a question, the Discussions tab might be a good place to start.

Thanks!
