### ISSUE TITLE
MacCatalyst container temporary file will disappear

### ISSUE THREAD

**Issue by 3egirlsdream** [dotnet/maui#22512]
### Description

Import a file using FilePicker,and I'll get a path in container ,just like `Containers/com.thankful.top.watermark/Data/tmp/filepath.jpg`
and  after a while the temporary file is disappear, I didn't close my app.

### Steps to Reproduce

- create a solution
- nuget install LukeMauiFilePicker
- import file
````c#
var Dictionary<DevicePlatform, IEnumerable<string>> FileType = new()
            {
                { DevicePlatform.MacCatalyst, new[] { "image/jpg", "image/png" } },
            };
 await picker.PickFilesAsync("pick", FileType, true);
````
- and you'll see the file in temporary folder, but it will disappear after a while 

### Link to public reproduction project repository

https://github.com/3egirlsdream/Watermark.Win

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Mac Mini M2 Lastest Version

**Comment by 3egirlsdream** [comment]
If I import file with **stream** and **dispose**, Whether files will be deleted？

**Comment by drasticactions** [comment]
You should direct this to the [nuget package](https://github.com/datvm/LukeMauiFilePicker) first, and if there's a bug in MAUI discovered through it to create a new issue.

The temporary folder sandbox in iOS and Mac Catalyst is what it says it is: Temporary storage. I would expect it to disappear when the underlying OS wants to remove the files since it's temporary. So my assumption is that the OS is cleaning up those files. If you need persistent storage, I would move the files you're working with elsewhere.
