### ISSUE TITLE
DatePicker and TimePicker use outdated controls on iOS

### ISSUE THREAD

**Issue by breyed** [dotnet/maui#22669]
### Description

On a native iOS app, DatePicker uses a popover. MAUI should do likewise with its DatePicker and TimePicker (and fall back to an older native control on old OSs).

### Steps to Reproduce

1. Create a new SwiftUI app in Xcode, and add a DatePicker to it:

``` swift
DatePicker("Date", selection: $date, displayedComponents: [.date])
```
<img width="295" alt="image" src="https://github.com/dotnet/maui/assets/1299073/1ec301e8-478a-40c1-928c-e46341686341">

2. Create a new MAUI app, and add a DatePicker to it:
``` xaml
<DatePicker />
```
<img width="450" alt="image" src="https://github.com/dotnet/maui/assets/1299073/5f002e43-a335-46ea-ba65-dbf3dccf310c">

TimePicker is similar.

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

17

### Did you find any workaround?

#19879 shows how to get a better calendar picker, but it still doesn’t provide a popover.

**Comment by drasticactions** [comment]
First, the wheel interface is not "outdated" in such that it's "obsolete." UIKit still supports it and can be used within SwiftUI; it's not the default. 

The problem here is that MAUI's DatePicker for iOS/Catalyst is not directly a UIDatePicker,

https://github.com/dotnet/maui/blob/5bb5ed2ec93cecfd1cb6094677ea88fa39924214/src/Core/src/Platform/iOS/MauiDatePicker.cs#L14-L22

MauiDatePicker brings up an underlying accessory view, which contains the date picker inside it as an input view. I believe this is because UIDatePicker and UIPickerView, in general, are a pain in the ass to style (My words, not the MAUI teams) and match with Android and Windows. So, you have to pick your poison: Use the native UIDatePicker which can't be styled to match Android and Windows and may not line up exactly with those UIs, or do something custom like this where you get more control, but then can't directly access the "newer" styles offered by UIKit itself.

To be blunt, unless the underlying MauiDatePicker in iOS/Catalyst is rewritten to directly use a UIDatePicker, you would get this newer style. Note that .NET iOS/Catalyst itself can access it,

https://github.com/drasticactions/MauiRepros/blob/1aad0aed13b50167492347d3311e7790573726e2/DatePickerTwo/MauiProgram.cs#L14-L23

As https://github.com/dotnet/maui/issues/20285 is the same issue, I'm closing this as a duplicate.

**Comment by breyed** [comment]
When Apple made the transition from UIKit to Storyboards as their primary UI technology, they changed the default size and color:

| Year | Technology  | Default font size and color |
|------|-------------|---------------------|
| 2008 | UIKit       | Small, dark         |
| 2011 | Storyboards | Large, light        |
| 2019 | SwiftUI     | Large, light        |

MAUI is true to UIKit’s defaults, which is the baseline SDK. However, it’s of limited use, since Apple and the world moved on two generations ago. Even though UIKit still serves as the foundation, native UIs within the last dozen years use a either the storyboard or SwiftUI wrapper, which have the updated styling.
