### ISSUE TITLE
Ping on iOS

### ISSUE THREAD

**Issue by metal450** [dotnet/maui#22783]
### Description

There doesn't seem to be a way to ping from iOS on MAUI - there have been several reports of this in the past, all of which were just closed without any solution. i.e.:

https://github.com/dotnet/maui/issues/6187
https://github.com/dotnet/runtime/issues/80253

(The first one was closed due to lack of interest, but the issue prevents anyone from commenting...thus making it impossible to show interest...?)

Previously, you could ping through Xamarin, but as Xamarin is now deprecated, any questions there are being redirected to MAUI. And I haven't found any workaround to get Ping working from MAUI.

What is the correct way to ping from MAUI, similar to what we could do on Xamarin via Xamarin.SimplePing?

### Steps to Reproduce

n/a

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

All

### Did you find any workaround?

No workaround listed in any prior reports of the issue

**Comment by drasticactions** [comment]
If there were an issue here, it would most likely be a runtime issue. System.Net.Ping should work fine on iOS and Mac. Your issue is most likely due to the AppSandbox, a feature of iOS and Mac that is enabled by default in the MAUI UI Template.

https://github.com/drasticactions/MauiRepros/tree/main/PingTest

I wrote a sample to show this. The key for the MAUI UI Template is

https://github.com/drasticactions/MauiRepros/blob/f6e049f573f266607c167bfb9e85d2ca98574e37/PingTest/PingTestMaui/Platforms/MacCatalyst/Entitlements.plist#L5-L14

You need to add the server entitlement for your app to be able to call outside of the app. This is unrelated to the MAUI UI Framework, these are base features of iOS/Mac Catalyst. When you hit issues like this, where it doesn't seem related to UI Features within MAUI itself, you should make a .NET iOS or Catalyst app and try it there here, like I've done with my sample.


Also, I'm not sure why the vendor mentioned in https://github.com/dotnet/maui/issues/6187 would reference a nuget, they were misinformed.  Also, @akoeplinger in https://github.com/dotnet/runtime/issues/80253 mentioned the permission issue, and they were correct, you need to enable your app to call out.

**Comment by metal450** [comment]
That's not what's going on in my case (the AppSandbox is not enabled in my entitlements, and other network client code is able to call out). Since I couldn't get System.Net.Ping to work, I'm instead doing a quick connection attempt, which does work for my specific use-case:

```
public static async Task PseudoPing(string ip, int port, int timeoutMs = 100)
{
    try
    {
        var ipa = IPAddress.Parse(ip);
        var ipe = new IPEndPoint(ipa, port);
        var socket = new Socket(ipe.AddressFamily, SocketType.Stream, ProtocolType.Tcp);
        var connectTask = socket.ConnectAsync(ipe);
        if (await Task.WhenAny(connectTask, Task.Delay(timeoutMs)) == connectTask)
        {
            Logger.LogInfo($"PingResult: Connected={socket.Connected}, IsBound: {socket.IsBound}, RemoteEndpoint: {socket.RemoteEndPoint}");
            socket.Dispose();
        }
        else
        {
            Logger.LogInfo("PingResult: False. Timed out.");
            socket.Dispose();
        }
    }
    catch (SocketException ex)
    {
        Logger.LogInfo($"PingResult: False. Exception: {ex.Message}");
    }
}
```

The reason I flagged this as related to Maui/Xamarin (even though I agree it isn't strictly a UI issue) is because previously, with Xamarin, the suggestion for how to ping from iOS seemed to be via [Xamarin.SimplePing nuget package](https://www.nuget.org/packages/Xamarin.SimplePing). Now that Xamarin is retired in favor of MAUI, I wasn't able to find an alternative.

(The above solution is working for me, so I actually no longer need ping anymore myself - but following up in case it's relevant for others. If the quick-connect approach wasn't working, still not sure how I would've gotten ping to work, given that the issue wasn't AppSandbox).

Thanks for the quick replies in any case :)

**Comment by drasticactions** [comment]
My sample shows System.Net.Ping working. There is no issue with it. Did you run my sample? Does that work for you? Are you running the newest .NET 8 SDK?

**Comment by akoeplinger** [comment]
From what I can see this should work even without the `com.apple.security.network.server` entitlement since https://github.com/dotnet/runtime/pull/52240 incorporated the approach that Xamarin.SimplePing took (which itself is a port of Apple's [SimplePing](https://developer.apple.com/library/archive/samplecode/SimplePing/Introduction/Intro.html) sample).

**Comment by metal450** [comment]
Alright...super strange...but I guess just ignore me - because yeah, it's working now (both in your sample app *and* in mine). It definitely wasn't working previously, but I've also messed with a fair few things since then, so likely something else I changed did it.

One possible culprit: I'm trying to ping something on the LAN, and apparently Apple has a "Local Network access" prompt that you can't explicitly show (like normal permissions) - the OS just shows it when you try to access a LAN resource. And any of the possible fail cases behave the same with no specific type of exception (i.e. the user denied the permission, vs the user hasn't been prompted for the permission for some other reason, vs the prompt is *currently* being shown but the user hasn't yet answered). I've also added a few things to Info.plist to get local server connections working (NSAllowsLocalNetworking, NSLocalNetworkUsageDescription, NSAllowsArbitraryLoads). So I guess somewhere along the way, whatever was causing it to fail previously got fixed.

Sorry for the wild goose chase, & thanks again for the quick replies.
