### ISSUE TITLE
[.NET 9.0 Preview 5] Build error when SkiaSharp.Views.Maui.Controls.Compatibility is added to a project

### ISSUE THREAD

**Issue by GeorgeDarakchiev** [dotnet/maui#23108]
### Description

The following build error can be observed when the SkiaSharp.Views.Maui.Controls.Compatibility package is added to a project targeting .Net 9 Preview 5 and building in Release configuration.

```
Microsoft.MacCatalyst.Sdk.net9.0_17.2/17.2.9639-net9-p5/targets/Xamarin.Shared.Sdk.targets(1256,3): error : Failed to AOT compile SkiaSharp.Views.Maui.Controls.Compatibility.dll, the AOT compiler exited with code 1.

/Microsoft.MacCatalyst.Sdk.net9.0_17.2/17.2.9639-net9-p5/targets/Xamarin.Shared.Sdk.targets(1256,3): error : Failed to AOT compile aot-instances.dll, the AOT compiler exited with code 1.
```

### Steps to Reproduce

1. Download the project from the repo
2. dotnet build -f net9.0-maccatalyst -c Release

### Link to public reproduction project repository

https://github.com/telerik/ms-samples/tree/main/Maui/Net9Preview5SkiaRepo

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.0-preview.4.10690

### Affected platforms

macOS

### Did you find any workaround?

No

**Comment by RoiChen001** [comment]
Can repro this issue at .NET 9.0 Preview 5.24307.10.
![image](https://github.com/dotnet/maui/assets/143168639/503acfbd-c136-419e-a5af-42c2ff2b8d28)

**Comment by PureWeen** [comment]
@rolfbjarne thoughts?

**Comment by rolfbjarne** [comment]
This is the AOT failure:

> Failed to load method 0x600001d from '/Users/rolf/test/bugs/ms-samples/Maui/Net9Preview5SkiaRepo/obj/Release/net9.0-maccatalyst/maccatalyst-arm64/linked/SkiaSharp.Views.Maui.Controls.Compatibility.dll' due to Could not load file or assembly 'Microsoft.Maui.Controls.Compatibility, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies..

This happens because `SkiaSharp.Views.Maui.Controls.Compatibility.dll` somehow references `Microsoft.Maui.Controls.Compatibility.dll` without actually pulling the latter into the build, so the AOT compiler crashes because it fails to resolve references to it.

Binlog: [msbuild.binlog.zip](https://github.com/user-attachments/files/16532851/msbuild.binlog.zip)


No idea what the fix is here - @mattleibow?

**Comment by mattleibow** [comment]
The `SkiaSharp.Views.Maui.Controls.Compatibility` package is no longer part of the future of SkiaSharp, so we probably will not be fixing this.

However, the workaround is very simple in that you just have to manually add the `Microsoft.Maui.Controls.Compatibility` nuget package. This was automatically added in .NET 8, so it worked. But in .NET 9 the Microsoft.Maui.Controls.Compatibility is not included automatically. 

I would not rely on this package for future development because it may be removed since I think it is obsolete or at least mostly obsolete?
