### ISSUE TITLE
Android app throwing Exception_WasThrown Java.Security.GeneralSecurityException

### ISSUE THREAD

**Issue by ganikapudisham** [dotnet/maui#23106]
### Description

I see the below error

Android app throwing Exception_WasThrown Java.Security.GeneralSecurityException

when I try to Sign In.

The website https://www.ChristianJodi.com uses the same api's . I am able to login to the website using the below credentials.

### Steps to Reproduce

Run the app.

Username is  Prince
Password is Prince

try to login

### Link to public reproduction project repository

https://github.com/ganikapudisham/maui-matri

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by logisnextsteve** [comment]
Good morning ganikapudisham,

What did you do to fix this issue.  We're running into it now...

**Comment by mistelltein** [comment]
I'm also want to know how to fix this

**Comment by mistelltein** [comment]
The issue was likely with SecureStorage. This problem appeared recently, although the code hasn't changed significantly.

Following the suggestions, I added these lines to the csproj:

<PropertyGroup Condition="$(Configuration)=='Release'">
    <RunAOTCompilation>false</RunAOTCompilation>
    <PublishTrimmed>false</PublishTrimmed>
</PropertyGroup>

Afterwards, during authentication, I encountered the: "javax.crypto.AEADBadTagException" error, which I resolved by disabling backups in the manifest:

<application android:allowBackup="false" ... >

These solutions helped fix the issues in the release application.
