### ISSUE TITLE
Error when trying to run myfirstapp on pixel device emulation

### ISSUE THREAD

**Issue by gstavi** [dotnet/maui#23192]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When trying to run the pixel device emulation got the following error:

Device error: WARNING | Failed to process .ini file C:\Users\Admin\.android\avd\..\avd\pixel_5_-_api_34.avd\quickbootChoice.ini for reading.
WARNING | unexpected '-prop' value ('monodroid.avdname=pixel_5_-_api_34'), only 'qemu.' properties are supported
WARNING | unexpected '-prop' value ('emu.uuid=e1e115de-b8c6-4a27-88eb-542744264dde'), only 'qemu.' properties are supported
added library vulkan-1.dll
initialize: Supports id properties, got a vulkan device UUID

**Comment by jfversluis** [comment]
Looks like something is wrong with the emulator. Are you running this inside of a virtual machine? Did the emulator work before? Here is a link to the documentation for the [Android emulator troubleshooting](https://learn.microsoft.com/dotnet/maui/android/emulator/troubleshooting), maybe there is something to help you in there.

If not, please report this issue through Visual Studio as this has more to do with the tooling around .NET MAUI rather than .NET MAUI itself. I will add a label right after this comment that will trigger a bot to post some instructions on how to do that exactly. Good luck!
