### ISSUE TITLE
Error: Activity class {../MainActivity} does not exist.

### ISSUE THREAD

**Issue by hossam14102010** [dotnet/maui#23194]
### Discussed in https://github.com/dotnet/maui/discussions/9510

<div type='discussions-op-text'>

<sup>Originally posted by **devonuto** August 18, 2022</sup>
After updating to Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview Version 17.4.0 Preview 1.0 (.NET SDK 6.0.400)

The android emulator isn't in the dropdown as an option to start debugging, only "Windows Machine". When clicking on that, I now get this error:

```
> am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "com.devonuto.myapp/crc6444e428aac7225743.MainActivity"
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.devonuto.myapp/crc6444e428aac7225743.MainActivity }
Error type 3
Error: Activity class {com.devonuto.myapp/crc6444e428aac7225743.MainActivity} does not exist.
Failed to launch android application
```

What has changed?
How do I get this working again?</div>

**Comment by drasticactions** [comment]
This issue would need to be addressed by the Visual Studio team, since that tooling isn't maintained in this repo. My guess would be that the .NET workloads didn't update along with Visual Studio or are missing on your system. If you go to your command line and type `dotnet workload list` you should see a MAUI workload. If you don't, that might be why it's missing in your dropdown.

If you install it with `dotnet workload install maui` and try building your app in the command line (`dotnet build`), and that works, but still fails within Visual Studio, it could be a VS bug that has to be fixed.
