### ISSUE TITLE
[Enhancement] Break out TestUtils.DeviceTests.Sample into separate respository

### ISSUE THREAD

**Issue by SteveBush** [dotnet/maui#2323]
## Summary
Break the TestUtils.DeviceTests.Sample and dependencies into a standalone project and Git repository.  A lot of cross-platform developers need the ability to run unit tests on mobile devices.  The XUnit device runner project hasn't been updated in years: https://github.com/xunit/devices.xunit and doesn't use the MAUI framework.  

I also think having integrated device tests would make a great example of how to structure a MAUI project to support multiple platforms.  

## Features
Sample MAUI cross-platform mobile application for Android, IOS, MacCatalyst, and Windows which includes:
- Maui mobile app
- Cross-platform device Tests for mobile app
- Xharness support for building on Azure Pipelines and GitHub Actions
- Documentation

## Suggestions
- Modify the WeatherTwentyOne sample to include device testing: https://github.com/davidortinau/WeatherTwentyOne
- Create a GitHub template similar to https://github.com/AArnott/Library.Template that includes device testing
- Add device unit testing to dotnet new template for [maui | ios | android | ...]

## Intended Use Case
Provide an example for building a MAUI application integrated with mobile device tests that run on Azure Pipelines and/or GitHub actions.

**Comment by mattleibow** [comment]
Right now we are using the code in here: https://github.com/dotnet/maui/tree/main/src/TestUtils/src
It is run on CI using xharness with this: https://github.com/dotnet/maui/tree/main/eng/devices
Runs are here: https://dev.azure.com/xamarin/public/_build/results?buildId=49371&view=results

**Comment by mattleibow** [comment]
We are closing for now as we are focusing on getting maui working well and then we can re-look at moving this out.

However, we are not opposed to doing this and in fact we wanted to do this in time for the release so that all the community could use it. However, due to time constraints, it will be just remain in the maui repo. If there is someone from the community that would like to move this out and clean it up into a packaged product, they could totally do that.

I know @dansiegel is working on a very similar things so that might be a good option to try.
