### ISSUE TITLE
Can I use MAUI only on the Windows platform?

### ISSUE THREAD

**Issue by xiao-cao-x** [dotnet/maui#2344]
`maui-check` will try to install OpenJDK and Android SDK for me (even if they already exist on my machine).
---
![image](https://user-images.githubusercontent.com/76673990/131657256-daa598a6-f59f-442e-95e8-77ee7e896613.png)

But I don’t need to use MAUI to build applications for other platforms,I just need to use MAUI to build apps for Windows.

---
In addition, is it possible to create MAUI programs for the Windows platform in Visual Studio 2022 Preview 3.1?

**Comment by ziaulhasanhamim** [comment]
if you have everything else try installing maui workloads manually with `dotnet workload install maui`. Maui check didn't work me too

**Comment by jfversluis** [comment]
Sure you can use .NET MAUI to only build your Windows app. I'm not sure if that is the right way to go though. The power of .NET MAUI is to create cross-platform apps from a single codebase. If you just want to build for 1 platform, it feels like you might be bringing in some overhead.

Tied to that, I think for the time being you have to install all the prerequisites for .NET MAUI in order to build it, even if just for one platform.
