### ISSUE TITLE
IWebView.Source has no setter

### ISSUE THREAD

**Issue by pauldavis-dwe** [dotnet/maui#23579]
### Description

I am writing unit tests for a view model that calls `_webView.Source = new UrlWebViewSource { Url = url }` and `await _webView.EvaluateJavaScriptAsync("whatever()");`.
I cannot change my _webView variable from WebView to IWebView for writing unit tests this because IWebView only provides a getter on the source property: `IWebViewSource Source { get; }`

### Steps to Reproduce

Look at the `Source` property in `IWebView`, it has no setter

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by PureWeen** [comment]
These interface properties will only have setters if they are changeable by the platform. For example, the Text property on ITextInput because the user can type into an entry. These interfaces aren't meant to model the exact contract of the XAML controls they just model the behavior at the platform level. 

Maybe look into stubbing or mocking the IWebView if you need to set it to something for testing purposes.
