### ISSUE TITLE
Unable to create the iOS build using the command line from Windows Machine

### ISSUE THREAD

**Issue by VaibhavMethuku01** [dotnet/maui#23609]
### Description

I'm trying to create the iOS build from the Windows machine by establishing the connection between the Windows Visual studio and Mac machine by the help of iP address. And the connection has established successfully and able to build the solution and perform the debug.

But, when I try to create the .ipa from windows machine using a command line getting some error which is 

C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8053\tools\msbuild\iOS\Xamarin.Shared.targets(2816,3): error : Code signing must be enabled to create
an Xcode archive. [C:\WorkSpace\Tco_Main\TVDApp\TVD\TVD.csproj::TargetFramework=net8.0-ios]

I have followed the Microsoft Documentation https://learn.microsoft.com/en-us/dotnet/maui/ios/deployment/publish-cli?view=net-maui-8.0 to try this method

As it is mentioned in the documentation, it is not asking the below prompt in my Mac.Here is my Mac connection established successfully.

![image](https://github.com/user-attachments/assets/870de64d-3899-4426-97ba-157d03e93ebb)

![image](https://github.com/user-attachments/assets/075c3e20-ccb0-478a-bcbc-4a877a2900b7)

 I tried all the way to fix this, but unable to find the solution.

It would be helpful if someone can give some suggestions on this.

Thanks in Advance.

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.1.7762

### Affected platforms

iOS

**Comment by emaf** [comment]
@VaibhavMethuku01 could you share a build binary log? You can get one by adding `-bl` to the build arguments, and the it will generate a file named `msbuild.binlog`.

**Comment by PureWeen** [comment]
@rolfbjarne

**Comment by AnithaRaniT** [comment]
@emaf We are able to create the msbuild.binlog and unable to upkoad here

**Comment by kevinxufei** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 3 (9.0.0-preview.6.24327.7). Can not repro it.
The steps are as follows:
1. Create a maui project and successfully pair the mac in vs (in order to download the required package in the mac).
2. Modify your Bundle Identifier & Version & Build in platform->iOS->info.plist.
![q1](https://github.com/user-attachments/assets/e68c31b2-ec0b-452b-9df0-dd2e19c15bc5)
3. Enter the project path from the command line, change the parameters in the following command to your corresponding information and execute.
![q2](https://github.com/user-attachments/assets/4f960fb5-ed62-4fa2-a057-78d1a85324f3)
