### ISSUE TITLE
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

### ISSUE THREAD

**Issue by Franco007-hun** [dotnet/maui#23799]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current Version 17.10.4

I create the Maui project and get a lot of error:
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
 The remote certificate is invalid according to the validation procedure.	(net8.0-android),

![image](https://github.com/user-attachments/assets/d267303c-2711-4b82-b58e-52656c7e3157)

I can't find any good solution for this.

**Comment by jfversluis** [comment]
Thanks for your interest in .NET MAUI, sorry that you ran into a problem.

Did you fix this by any chance? Usually this happens when your date/time is off on your computer or maybe some proxy is in the way. I've also seen others suggest restarting Visual Studio or their computer. Does that help at all?
