### ISSUE TITLE
Rendering the page using NavigationPage doesn't display Page, renders a blank screen. But works fine if i try to render without NavigationPage

### ISSUE THREAD

**Issue by m1049177** [dotnet/maui#2381]
Rendering the page using NavigationPage doesn't display Page, renders a blank screen. But works fine if i try to render without NavigationPage

### Steps to Reproduce

1. Create a MAUI template and change the MainPage = new MainPage(); to MainPage = new NavigationPage(new MainPage());
2.  Main Page renders in android emulator but content is blank screen

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/50957019/131970441-c9369791-da84-420d-8059-77a10f9d6c12.png)

**Comment by inkysquid** [comment]
I am also experiencing this issue. It works if you start with a NavigationPage, it's *changing to a NavigationPage* that's a problem. I was working around this by:

1. Only set MainPage once and make sure it's a navigation page.
2. Instead of changing the MainPage, instead set the new page as the first page in the stack, then call PopToRootAsync().

Unfortunately Shell does not work inside a NavigationPage. You can set the main page to a Shell, but then you can't change back to a NavigationPage (e.g. to redirect back to a Login page).

`
private async Task PushAsync(Page page, bool clearBackHistory)
{
    if (clearBackHistory)
    {
        Navigation.InsertPageBefore(page, Navigation.NavigationStack[0]);
        await Navigation.PopToRootAsync();
        return;
    }
    await Navigation.PushAsync(page);
}
`

**Comment by Mahfouz0** [comment]
Yea

**Comment by m1049177** [comment]
> I am also experiencing this issue. It works if you start with a NavigationPage, it's _changing to a NavigationPage_ that's a problem. I was working around this by:
> 
> 1. Only set MainPage once and make sure it's a navigation page.
> 2. Instead of changing the MainPage, instead set the new page as the first page in the stack, then call PopToRootAsync().
> 
> Unfortunately Shell does not work inside a NavigationPage. You can set the main page to a Shell, but then you can't change back to a NavigationPage (e.g. to redirect back to a Login page).
> 
> ```cs
> private async Task PushAsync(Page page, bool clearBackHistory)
> {
>     if (clearBackHistory)
>     {
>         Navigation.InsertPageBefore(page, Navigation.NavigationStack[0]);
>         await Navigation.PopToRootAsync();
>         return;
>     }
>     await Navigation.PushAsync(page);
> }
> ```
