### ISSUE TITLE
MSB4044	The "GenerateRtxt" task was not given a value for the required parameter "JavaPlatformJarPath"

### ISSUE THREAD

**Issue by phuocvj** [dotnet/maui#23840]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

MyFirstMainApp (net8.0-android)	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.95\tools\Xamarin.Android.Resource.Designer.targets	65	

![image](https://github.com/user-attachments/assets/a5d084ac-3d65-4d4e-878e-f67501f28fa9)

**Comment by jfversluis** [comment]
I see a couple of related issues suggested by the bot and also [here](https://developercommunity.visualstudio.com/t/Error:-The-GenerateRtxt-task-was-not-g/10542833).

It seems like maybe something isn't right with the Android tooling. If you to to Tools > Android SDK does everything look alright there? And since this issue is now a few weeks older did you maybe resolve it already?
