### ISSUE TITLE
ListView is not scrolling on iOS

### ISSUE THREAD

**Issue by afcsoft** [dotnet/maui#23926]
### Description

Same issue as https://github.com/dotnet/maui/issues/7386#issue-1243753273. It is still there

### Steps to Reproduce

Create .net maui app
Populate ListView
Try to scroll on iOS device

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by kevinxufei** [comment]
I can repro this issue on the latest 17.11.0 Preview 5.0 (8.0.70).

**Comment by drasticactions** [comment]
I don't believe this is a bug,

https://github.com/dotnet/maui/issues/7386#issuecomment-1257761851

VerticalStackLayout doesn't have an intrinsic height for its inner elements, so ListView expands and
- Breaks Virtualization, since it has no height to bind to, it will render every cell
- Can't scroll, since the iOS ScrollView that manages the UITableView backing can't scroll because it's not bound to anything.

This is a change of behavior from Xamarin.Forms, and [has been this way since MAUI launched](https://learn.microsoft.com/en-us/dotnet/maui/migration/layouts?view=net-maui-8.0#stacklayout). Even if the scroll view did work, Virtualization would be broken so you still get behavior you probably don't want. 

If you switch to a Grid, it should work fine.

@PureWeen Is this correct?

**Comment by PureWeen** [comment]
Duplicate of #24078
