### ISSUE TITLE
Is VS Code fully support like Flutter ?

### ISSUE THREAD

**Issue by chhinsras** [dotnet/maui#2395]
Loving Maui but worried about the development experience. And I would love to use VS Code. Here are what I concerns

- [ ] component support
- [ ] Hot reload
- [ ] Performance
- [ ] Resource
- [ ] Intellisence

**Comment by jfversluis** [comment]
Thank you for voicing your concerns! Unfortunately, it's hard to deduce from a couple of keywords what you mean exactly :)

As for the VS Code support; since all the .NET MAUI bits are now part of .NET 6 and the CLI tooling, making it work with VS Code is possible. However, it will not be officially supported. At the time being, Visual Studio 2022 will provide you the best experience.

There is a discussion opened here with a similar request/question: https://github.com/dotnet/maui/discussions/46

Please give it your thoughts and upvote. All we do is based on data, if we see there is enough excitement, who knows what might happen.

**Comment by chhinsras** [comment]
> Thank you for voicing your concerns! Unfortunately, it's hard to deduce from a couple of keywords what you mean exactly :)
> 
> As for the VS Code support; since all the .NET MAUI bits are now part of .NET 6 and the CLI tooling, making it work with VS Code is possible. However, it will not be officially supported. At the time being, Visual Studio 2022 will provide you the best experience.
> 
> There is a discussion opened here with a similar request/question: #46
> 
> Please give it your thoughts and upvote. All we do is based on data, if we see there is enough excitement, who knows what might happen.

Looking forward to seeing your video on VS code tooling soon

**Comment by jfversluis** [comment]
I think James already has some over on his channel so you might want to check that out :)
