### ISSUE TITLE
Can't Change Printer in Print Dialog in .Net Maui Blazor Hybrid

### ISSUE THREAD

**Issue by meisam-dehghan** [dotnet/maui#23971]
### Description

I'd like to print a page in .Net Maui Windows application,but when I press Ctrl+P or click on the Print icon on a PDF Viewer ,the Print Dialog appears,but I can't change any settings including the Printer! This is a bug related to .Net Maui,because it workds when I run the it as a web app.
I'm using the latest version  of Visual Studio(17.10.5)
Similar Bug is reported here: https://github.com/microsoft/WindowsAppSDK/issues/4439

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net8.0-windows10.0.19041.0

**Comment by SmartmanApps** [comment]
Related: I haven't tried this again in MAUI, but I was never able to print in Xamarin for this precise reason of not being able to change the settings (on Windows). I was trying to print barcodes, which require high quality print to be able to be scannable, but settings changes would never stick and would never print at high quality.

**Comment by jfversluis** [comment]
It would be worth knowing if this is only in a Blazor Hybrid app or this also shows in a .NET MAUI app with a regular web view. That will narrow down if this is specific to our BlazorWebView implementation or .NET MAUI as a whole

**Comment by SmartmanApps** [comment]
@jfversluis 

> if this is only in a Blazor Hybrid app or this also shows in a .NET MAUI app

I originally ran into this issue in a Xamarin app, but have not got as far as trying it in MAUI yet, but the original issue was definitely around before Blazor was even part of the picture.

If you keep this open I can let you know when I get to that again (I have other business logic I need to implement first before I'll have things to print - with the Xamarin app we're just printing directly in Windows, rather than from the app, as a work-around). The issue for us is that no settings which are changed in the app (such as changing to high quality print) actually stick beyond exiting changing the settings. i.e. doesn't save, at all (not for print quality anyway). I suspect might be an issue with Windows not allowing MAUI to change system settings? I believe from memory this was a Windows-only issue (but I haven't tried any other platforms myself).

**Comment by meisam-dehghan** [comment]
The issue was gone once I updated all the NuGet packages to .Net 8.7.So,anyone who's running into this issue, is recommended to do so in the first place
