### ISSUE TITLE
Picker ItemDisplayBinding doesn't work with compiled bindings

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#23989]
### Description

When I use `ItemDisplayBinding` in 8.0.80 nightly or .NET 9 Preview 7, the picker doesn't populate as I'd expect. 

<img width="776" alt="Screenshot 2024-08-02 at 2 32 52 PM" src="https://github.com/user-attachments/assets/fef41d45-eab2-4463-b997-79afafab251b">

I can get around it using a `ToString` override on the model, or by providing the `x:DataType=models:VocabularyList`.

The `ContentPage` does specify a `x:DataType` for the view model. This doesn't work:

```csharp
<Picker x:Name="VocabPicker" 
    ItemsSource="{Binding VocabLists}"
    ItemDisplayBinding="{Binding Name}"                    
    SelectedItem="{Binding VocabList, Mode=TwoWay}" />
```

This does work:

```csharp
<Picker x:Name="VocabPicker" 
    ItemsSource="{Binding VocabLists}"
    ItemDisplayBinding="{Binding Name, x:DataType=models:VocabularyList}"                    
    SelectedItem="{Binding VocabList, Mode=TwoWay}" />
```

<img width="776" alt="Screenshot 2024-08-02 at 2 53 10 PM" src="https://github.com/user-attachments/assets/bc2341c0-bad7-45d9-93fd-094349207a33">

### Steps to Reproduce

https://github.com/davidortinau/SentenceStudio/blob/main/src/SentenceStudio/Pages/Lesson/LessonStartPage.xaml

My testing with the original code:

8.0.71 - Debug - Good
8.0.71 - Release - Good
8.0.80 - Debug - Sad
8.0.80 - Release - Good

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.61 SR6.1

### Affected platforms

iOS, Android, Windows, macOS

### Did you find any workaround?

Yes, as described

**Comment by simonrozsival** [comment]
This is likely caused by #23989 and it would also break with .NET 9 in Release mode where the binding would be compiled.

There is a mismatch between the declared `x:DataType` (`<ContentPage ... x:DataType="lesson:LessonStartPageModel">`) and the actual type of the binding context when the binding is applied (`lesson:VocabularyList`). Specifying the `x:DataType` for the binding is the right way to declare this binding going forward.

**Comment by StephaneDelcroix** [comment]
We believe #23989 is right and should be kept for .net9. I'm making dure a warning or an error is logged at compilation time

**Comment by StephaneDelcroix** [comment]
I did some testing, on the net9.0 branch (but should be similar on 'main'):
- ItemDisplayBinding is compiled if x:DataType is set on the {Binding}
- isn't compiled otherwise (without warning)

so, 
- we shouldn't prevent the Binding to be applied if there's a DataType mismatch in this case...
- we should issue a compilation-time warning before falling back if DataType is missing

**Comment by hungchips** [comment]
This is still happening on MAUI 8.0.82
