### ISSUE TITLE
CollectionView rendering hangs the apps 

### ISSUE THREAD

**Issue by chabiss** [dotnet/maui#23992]
### Description

Not sure what I'm doing wrong, but the layout of the collectionview, which contains only 119 elements, tank the performance of the Collection View. 

https://github.com/user-attachments/assets/a258a70e-d85b-47de-8509-3069a3e339df

### Steps to Reproduce

1.  Clone https://github.com/chabiss/periodictable
2. Build  the solution 
3.  Make sure the PeriodictableMaui project is the startup project
4. Launch the app on Windows
5. Click the button "List All Elements"

### Link to public reproduction project repository

https://github.com/chabiss/periodictable

### Version with bug

8.0.71 SR7.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

No

**Comment by ninachen03** [comment]
I can repro this issue at Windows platform on the latest 17.11.0 Preview 6.0(8.0.61 & 8.0.71)

**Comment by chabiss** [comment]
Switching to Release Build didn't improve the performance.

**Comment by chabiss** [comment]
Remove the wrapping VerticalStackLayout wrapping the CollectionView.  This improved the performance, but the initial load is still very slow

**Comment by Foda** [comment]
Hello! This appears to be caused by a combo of how your ViewModels are being used and a bigger issue with the Border control (https://github.com/dotnet/maui/issues/24123). 

While we work on a fix, one minor work-around would be to have different ViewModels for the AllElements page, and MainPage. Both ViewModels could then just reference one `PeriodicTableDataEngine`.

The issue is partially caused by both pages being bound to the same list of elements on the same instance of a ViewModel. This causes both pages to always remain in-memory (it leaks) and the elements also remain in the visual tree. When the element list is refreshed the Grid on the `MainPage` also updates even though it's not visible.
