### ISSUE TITLE
Maui Frame - Shadow on Frame not working on Maui

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#24168]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui-Frame---Shadow-on-Frame-not-working/10713304)._

---
Inserting:

<Frame.Shadow>
                    <Shadow Brush="Gray"
                        Offset="2,2"
                        Radius="18"
                        Opacity="1" />
                </Frame.Shadow>

Has NO effect whatsoever.

I found, that using BorderColor="Gray" had some effect.

But this is NOT a solution - mere a hack.

I want to have a real shadow on the frame.

---
#### Feedback Bot on 7/30/2024, 11:46 PM: 

(private comment, text removed)

---
#### Kurt Pedersen solved on 8/8/2024, 08:15 AM, 0 votes: 

<p>Sorry guys</p>
<p>There is NO problem anyway</p>
<p>Opposite to all other controls Frame needs this<br>
HasShadow=“True”<br>
in order to make shadow work</p>

**Comment by jfversluis** [comment]
Frame is being deprecated, you probably want to look into our new `Border` and `Shadow` APIs.

I will close this one as I think the changes of this being fixed will be low as the new APIs work and `Frame` will be going away.

**Comment by KurtOplev** [comment]
Hello

Once again sorry.

At first, I complained that Shadow didn't work on Frame.
Then I wrote that Shadow actually works on Frame if HasShadow was set to True.

But I wasn't aware that this had, to put it mildly, an unfortunate effect on the Expander wrapped in the Frame.

I have now tried setting Shadow on both Frame, Border, StackLayout and Expander.

The examples show:
Frame with Shadow 
	Shadow works
	CornerRadius works
	Expander is destroyed

Frame without Shadow, but with BorderColor 
	BorderColor instead of Shadow – can be accepted
	CornerRadius works
	Expander works 

Border with Shadow 
	Shadow does NOT work,
	Does NOT have BorderColor, but is not needed either, as Border automatically has BorderColor
	Does NOT have CornerRadius
	Expander is destroyed

Border without Shadow
	Does NOT have BorderColor, but is not needed either, as Border automatically has BorderColor
	Does NOT have CornerRadius
	Expander works 

StackLayout with Shadow
	Shadow does NOT work
	Does NOT have BorderColor
	Does NOT have CornerRadius
	Expander is destroyed

StackLayout without Shadow
	Does NOT have BorderColor
	Does NOT have CornerRadius
	Expander works

Expander with Shadow
	Shadow does NOT work
	Does NOT have BorderColor
	Does NOT have CornerRadius
	Expander works
	Wrong appearance – could work, but is not, as desired, gathered in one box

Please see repro here:
[KurtOplev/BorderShadow: Examples of Expander wrapped in different controls (github.com)](https://github.com/KurtOplev/BorderShadow)

Try opening and closing the Expander elements in the different examples.
Then you will see that the texts overlap each other, when the control has Shadow set.

The solution of Frame with BorderColor instead of Shadow is the only acceptable solution for now.
The solution with Border cannot be accepted despite the fact that there is an automatic BorderColor, as the CornerRadius does not exist on the Border.

So, when Frame is deprecated, I do NOT have an acceptable solution.

The optimal solution is:
	that Shadow on Border will work
	that it will be possible to set CornerRadius to Border 
	as well as of course making sure that Shadow does NOT destroy Expander's functionality.

Or that there is a completely different control that can give the desired results.
