### ISSUE TITLE
NavigationPage does not close reliably

### ISSUE THREAD

**Issue by AlphaNERD-** [dotnet/maui#24204]
### Description

I am facing an issue which causes a NavigationPage to "stick". Basically when i want to close the Page using Navigation.PopAsync, the same page is opened again. Another thing that can happen is that the previous page does pop up after a second tap on the back and going back from there or forward does not work properly anymore.

Something of note that may mess with the navigation is that i removed the AppShell. That is because in the original project the repro project is based on i couldn't figure out how to open a different page than the page declared in the AppShell.xaml depending on a few conditions.

### Steps to Reproduce

0. Clone my repro project.
1. Tap the Button "Show an error".
2. Use the Back button to go back to the previous page.
3. Tap the Button "Do something" to go to the next page.

Going forward and back has worked so far.

4. Tap the Button "Show an error".
5. Use the back button to go back again.
6. Tap the Button "Do something again" to go to the next page.

Going forward and back has worked again. The next page will automatically open an error page which you can't leave. Or you can leave that page but not the previous page. Anyway the navigation is broken now.

### Link to public reproduction project repository

https://github.com/AlphaNERD-/MAUIPageNotClosingDemo

### Version with bug

8.0.71 SR7.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

**Comment by ninachen03** [comment]
I can repro this issue at android platform on the latest 17.11.0 Preview 7.0 (8.0.80 & 8.0.70)
[MAUIPageNotClosingDemo-main.zip](https://github.com/user-attachments/files/16597976/MAUIPageNotClosingDemo-main.zip)

**Comment by PureWeen** [comment]
A few things here

1) You don't need to wrap every single page in a NavigationPage. You probably only need the root page to be wrapped into a root page

2) The reason that middle page is blank is most likely due to the fact that you're performing the push from inside a "Task". That's going to schedule that work off the dispatcher thread which is going to act in a somewhat undefined way. 

3) If I change the code inside `OnAppearing` to use the `Dipatcher` it all operates in a much more expected way. Page2 is pushing Page3 and then Page3 now pushes the ErrorPage. So your navigation stack is "Page2/Page3/ErrorPage", pushing a page from appearing doesn't interrupt the other page from getting pushed. You would need to pop it before pushing it.

If I change Page3 to this

![image](https://github.com/user-attachments/assets/3ca0f658-03f6-4f22-ad9b-05dad6aa6e94)

It all acts somewhat expected. All three pages get pushed onto the stack and then every time I click the back button OnAppearing fires on Page3 which then repushes the error page on the stack
