### ISSUE TITLE
[Windows] CollectionView Infinite Scroll Bug : Scroll Resets to First Item at End

### ISSUE THREAD

**Issue by WaelBenBe** [dotnet/maui#24578]
### Description

When I scroll to the end of the list, instead of loading more items or stopping at the last item, the scroll position unexpectedly resets to the first item in the list

### Steps to Reproduce

1. Implement infinite scrolling on a CollectionView.
2. Scroll through the items until you reach the end of the list.
3. Observe that the scroll position returns to the first item instead of loading more items or staying at the end of the list.

### Link to public reproduction project repository

https://github.com/WaelBenBe/InfinityScroll

### Version with bug

8.0

### Affected platforms

Windows

### Affected platform versions

Windows SDK

**Comment by jaosnz-rep** [comment]
I can repro this issue at Windows platform on the latest 17.12.0 Preview 1.0(8.0.82 & 8.0.80).

**Comment by Foda** [comment]
Hello! This can be fixed by setting the `ItemsUpdatingScrollMode` property to `KeepScrollOffset` on the `CollectionView`. [You can find more info about this topic here](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/collectionview/scrolling?view=net-maui-8.0#control-scroll-position-when-new-items-are-added)

**Comment by WaelBenBe** [comment]
@Foda thx for your comment , this fix the issue
