### ISSUE TITLE
Button control IsEnabled property not working when value is set to False. 

### ISSUE THREAD

**Issue by divyesh008** [dotnet/maui#24604]
### Description

I'm working on setting the Opacity of a Button based on the **IsEnabled** property. By default, the UI is not updating the Opacity when the IsEnabled property is set to False. 

To address this, I created a CustomButtonHandler, but it doesn't update the Opacity when the Button control is initially loaded, even though the handler sets it to 0.5 initially. 

Interestingly, the Opacity updates correctly if the IsEnabled value is changed at runtime.

Check the attached screen recording:

https://github.com/user-attachments/assets/4f11fd6e-25c7-42a7-93b5-39b00248883f

https://github.com/user-attachments/assets/08e42f49-61d5-44f6-a58b-12c30263d826

### Steps to Reproduce

1. Create new maui project 
2. Add Button control on the page, set BackGroundColor=Blue and TextColor=White
3. Set the IsEnabled property to false and run the app
4. Notice the appearance of the Button, it does not look like disabled 

### Link to public reproduction project repository

https://github.com/divyesh008/MauiButton_Issue.git

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms, No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

iOS 17.2, Android 14, Windows 10.0.17134.0

### Did you find any workaround?

No

**Comment by mattleibow** [comment]
I am not yet sure of why this issue is occurring, but I am thinking all of this could be resolved by using a VisualStateManager:

https://learn.microsoft.com/dotnet/maui/user-interface/visual-states

Here is the same idea with ImageButton from the styles in the template: https://github.com/divyesh008/MauiButton_Issue/blob/main/MauiButtonBug/Resources/Styles/Styles.xaml#L148-L160

It is very likely that even though you are setting opacity, another property is overriding that. 

Let me know if the VSM is what you are looking for and/or if it helps.

**Comment by divyesh008** [comment]
Not exactly. But I can use VSM for the same.
