### ISSUE TITLE
Provide more exception source info from the throwing codes

### ISSUE THREAD

**Issue by jingliancui** [dotnet/maui#24648]
### Description

https://github.com/dotnet/maui/blob/bcba26ff7651cfae171a45df0caca71d7f4b4d39/src/Controls/src/Core/Application/Application.cs#L517

Actually, I'll also can hit above code's exception in my application.
But the exception info doesn't provide where it occurred (stack trace).

I can also help to contribute if need.

### Steps to Reproduce

not need

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

provide more detail to the throwing message
for example
`	throw new NotImplementedException($"Either set {nameof(MainPage)} or override {nameof(Application.CreateWindow)} in {namespce.type.method/property}{line of the code's number}.");`

**Comment by mattleibow** [comment]
Windows is hard to debug... If you check the Data property in the exception info window, is there anything there?

This usually happens if you have not set a `MainPage` or overridden the `CreateWindow` in your application type. Are you able to attach a repro and some more info as to what your app is doing, how often this happens and is it reliably breaking?
