### ISSUE TITLE
Loading initial data from a json file of data 4000 in ObservableCollection is lagging the application to start.

### ISSUE THREAD

**Issue by tcimran** [dotnet/maui#24677]
### Description

I have some sample data in json of count 4000 and i tried to call this by batch , or using ObservableRangeCollection but the application wont start because i was trying to add the collection to ObservableCollection ,
```cs
[ObservableProperty]
private ObservableCollection<TaskMang> tasks;

public async Task LoadTasksFromJsonAsync()
    {
        Tasks.Clear();
        var filepath = "X:\\XXXX\\XXXXX\\XXXXX\\excel-to-json";

        if (!File.Exists(filepath))
        {
            // Handle file not found (e.g., notify user or log)
            return;
        }

        try
        {
            var jsonString = await File.ReadAllTextAsync(filepath);
            var jsonDocument = JsonDocument.Parse(jsonString);
            var root = jsonDocument.RootElement;

            if (root.TryGetProperty("Task_Master", out JsonElement taskArray))
            {
                foreach (var task in taskArray.EnumerateArray())
                {
                    var taskObj = new TaskMang
                    {
                        // Assuming TaskMang properties match JSON fields
                        TaskId = task.GetProperty("TASK_ID").GetInt32(),
                        TaskName = task.GetProperty("TASK_NAME").GetString(),
                        StartTime = task.GetProperty("START_TIME").GetString(),
                        EndTime = task.GetProperty("END_TIME").GetString(),
                        TimeTaken = task.GetProperty("TIME_TAKEN").GetString(),
                        ProjectName = task.GetProperty("PROJECT_NAME").GetString()
                    };

                    Tasks.Add(taskObj);
                }
            }
        }
        catch (Exception ex)
        {
            // Handle exceptions (e.g., log the error or notify the user)
        }
    }

```
![image](https://github.com/user-attachments/assets/16e7a0b9-a988-4653-81fe-f06f2efca723)

The main page is stuck to load the data to observablecollection and update the listview in mainpage.xaml. 

### Steps to Reproduce

1.Create a Maui Projec
2. add a viewmodel and inherit ObservableObject.
3. Create a [ObservableProperty]
private ObservableCollection<TaskMang> tasks;
4. take some random data in json with more than 200 records and call them using a method try async , sync, Task.Run(()) which gives same results.
5. Fetch json file using method(sample code provided above) and add to observable collection.

### Version with bug

9.0.0-preview.7.24407.4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows

### Did you find any workaround?

with same amount of data i couldnt find much of difference in below code but works some time. 
On looping add to a temporary list and then after the loop add below code.

Initialize Tasks with the loaded data
Tasks = new ObservableCollection<TaskMang>(temporarytasklist);

**Comment by drasticactions** [comment]
Can you please create a complete reproduction project of how you do this?

My guess, based on what you wrote, is that your code is blocking the UI Thread, as it has to process all of those items to add them independently to the ObservableCollection. So I'm unsure if this is a MAUI bug.

**Comment by mattleibow** [comment]
Also, please let us know which `ObservableRangeCollection` you are using, there are a few out there that do the same thing in different ways.

**Comment by tcimran** [comment]
> Can you please create a complete reproduction project of how you do this?
> 
> My guess, based on what you wrote, is that your code is blocking the UI Thread, as it has to process all of those items to add them independently to the ObservableCollection. So I'm unsure if this is a MAUI bug.

i researched some in stackoverflow and other blogs, my code is adding data from json/excel to a observablecollection what happens due to large volume of data the event onchangeofitems something is being called when each object is being added into it, to avoid adding each single time , i used observablerangecollection and i did "observableRangeCollectionObject.add(objectCollection)." but this to hold the thread for some reason.

**Comment by tcimran** [comment]
> Can you please create a complete reproduction project of how you do this?
> 
> My guess, based on what you wrote, is that your code is blocking the UI Thread, as it has to process all of those items to add them independently to the ObservableCollection. So I'm unsure if this is a MAUI bug.

Hi 

> Also, please let us know which `ObservableRangeCollection` you are using, there are a few out there that do the same thing in different ways.

I am using Mvvm.Helpers ObservableRangeCollection

**Comment by tcimran** [comment]
> Can you please create a complete reproduction project of how you do this?
> 
> My guess, based on what you wrote, is that your code is blocking the UI Thread, as it has to process all of those items to add them independently to the ObservableCollection. So I'm unsure if this is a MAUI bug.

Thank you so much for your quick response and insights! I’ve updated the project and added the DemoUploadAsync method in TaskMaViewModel to illustrate the issue. It seems the app hangs due to a heavy load or possibly the event firing during bulk additions to the observable collection. I appreciate any further feedback or suggestions you might have.

Here’s the link to the updated project: https://github.com/tcimran/TaskManagementDemo.git.

Thanks again for your help!

**Comment by mattleibow** [comment]
Thanks for the project, I was able to see a few issues and eventually got it loading and scrolling fast.

The main reason for the slow load is that the ListView is in a ScrollView. This means that instead of the list view only loading a few items at a time, the entire list is expanded and all the views are loaded. If you remove the outer ScrollView then it loads faster: https://github.com/tcimran/TaskManagementDemo/blob/master/TASKMNGMT/Pages/MainPage.xaml#L94

I also see that you have a fixed height and that you have it in a stack layout: https://github.com/tcimran/TaskManagementDemo/blob/master/TASKMNGMT/Pages/MainPage.xaml#L73 I would suggest rather removing the stack (or replacing with a grid) and instead add a new row in the containing grid: https://github.com/tcimran/TaskManagementDemo/blob/master/TASKMNGMT/Pages/MainPage.xaml#L16 Also, I see that is in a second scroll view so it may cause issues later on.

I think based on this, you are trying to make the whole page scrollable? Maybe if you put all the contents at the top in the list header, then it can scroll off the screen. But, if this is not the case, then also remove the root scroll view: https://github.com/tcimran/TaskManagementDemo/blob/master/TASKMNGMT/Pages/MainPage.xaml#L15

I managed to get better performance with this, but got even better perf when switching the ListView to a CollectionView. The CollectionView is new and has better perf in some scenarios. It also has additional features. Note: switching to CollectionView means the ViewCell element is no longer needed and you can put your UI directly in the template.

One reason that is also impacting perf is the ViewCell has an Appearing event that you are using to construct and modify the UI. This will have a perf impact as the UI needs to be constructed each time the list scrolls. And, when the cells are reused, you are potentially adding the same control multiple times.

I saw you set the binding context multiple times, once in the code behind and once in the XAML: https://github.com/tcimran/TaskManagementDemo/blob/master/TASKMNGMT/Pages/MainPage.xaml#L11-L14

There should be no need to set the binding context `BindingContext="{Binding}"` as this is basically saying use the current binding context for the binding context - which may trigger a reload of data: https://github.com/tcimran/TaskManagementDemo/blob/master/TASKMNGMT/Pages/MainPage.xaml#L94

I also notice that you have several instances of `{Binding Source={RelativeSource AncestorType={x:Type ###}}`. For example: https://github.com/tcimran/TaskManagementDemo/blob/master/TASKMNGMT/Pages/MainPage.xaml#L95C61-L95C75 In this case, the context is already MainPageViewModels so you should not need to have that at all.
