### ISSUE TITLE
[Bug] Blazor integration issue for iOS and MacOS StaticWebAssets.build.json does not exist

### ISSUE THREAD

**Issue by juanlao** [dotnet/maui#2468]
### Description
I created a .NET MAUI Blazor App and wanted to extract the blazor code to another project to see how we can integrate Blazor libraries. 
I was able to make it work in Android and WinUI, but in iOS and MacOS I am getting the error during compilation: "Manifest file ".../net6.0/StaticWebAssets.build.json" does not exist

### Steps to Reproduce

1.  Download sample project from my repo [here](https://github.com/juanlao/MauiIssues/tree/master/BlazorIntegration)
2.  Compile on a Mac with the command: "dotnet build -t:Run -f net6.0-maccatalyst"

### Expected Behavior
App with the Blazor sample running on Mac
### Actual Behavior
Getting the error during compilation: "Manifest file ".../net6.0/StaticWebAssets.build.json" does not exist

Don't really know if the problem is in the code or between my monitor and my chair ^_^

**Comment by Eilon** [comment]
Hi @juanlao , thank you for the bug report. It looks like this project was built with .NET MAUI Preview 7, which unfortunately had some issues with static web assets on certain platforms. Can you try installing .NET MAUI preview 8 (info here: https://devblogs.microsoft.com/dotnet/update-on-dotnet-maui/) and try the same scenario? We did a huge update for static web assets and this issue should be fixed in that update.

**Comment by juanlao** [comment]
Perfect, thanks!
it is solved :)
