### ISSUE TITLE
Black Screen when resuming iOS App when debugging

### ISSUE THREAD

**Issue by czuck** [dotnet/maui#24793]
### Description

On iOS, when app is minimized and then resumed it displays a black screen.  Stop the VS debugger and app resumes properly.

### Steps to Reproduce

Create a File New MAUI App.
Run the app.
Minimize the app, then resume it - the first time it normally works properly.
Minimize the app, then resume it - the screen is black.  repeat, the issue will persist.
Stop the debugger and resume the app, the screen paints.

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.6.1

**Comment by jfversluis** [comment]
@drasticactions so is this related to the preview or Hot Reload or something maybe?

**Comment by drasticactions** [comment]
@jfversluis I would need to debug it, but my guess based on that video is "kinda" leaning toward "yes"

Live Preview calls for screenshots from Visual Diagnostics in MAUI to update its view. It could be that calling it either in the background or when the window reloads is causing it to hang. But I don't think it's code directly inside of the hot reload agents that could cause it.

So it could be something that would need to be fixed in MAUI when calling for the screenshots, in the hot reload agents to not try to get screenshots if the app is backgrounded, or both. 

It should be moved to VSFeedback for now.
