### ISSUE TITLE
[Bug] Workload installation failed

### ISSUE THREAD

**Issue by fernandozago** [dotnet/maui#2483]
### Description
Trying to run the command:
  dotnet workload install maui
### Steps to Reproduce

1. Open Windows Terminal (or equivalent like cmd)
2. Run command: dotnet workload install maui

### Expected Behavior
Install the maui workloads 

### Actual Behavior
Exception was thrown:

Workload installation failed: One or more errors occurred. (microsoft.aspnetcore.authorization.msi.x64::6.0.0-rc.2.21455.6 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://aka.ms/maui-preview/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\".)

### Basic Information

- Version with issue: 
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/12010709/133326042-0fd0e43d-980b-42f2-a0a8-ddaa5433e29d.png)

**Comment by HeroinGyrl** [comment]
Same issue for me.

**Comment by drasticactions** [comment]
Either you global Nuget Config or where you're running the command from has the dotnet6 and maui nightly feeds included, so you're going to be getting main builds (In this case, RC2). If you don't intend to do that, you should clear those feeds from your global nuget or set the source for the workload install to _only_ be the public NuGet feed.

It's failing because it can't find `microsoft.aspnetcore.authorization.msi.x64`, probably because it doesn't exist. It's most likely because they don't have an MSI package for the workload, and the default currently in dotnet 6 is to use the MSI versions for workloads.

If you go into your dotnet directory (On Windows, `C:\Program Files\dotnet\metadata\workloads\6.0.100\installertype`), you can see a feature flag file called 'msi', delete it and rerun the command, it should work.

**Comment by fernandozago** [comment]
> The global Nuget Config (or where you're running the command from) has the dotnet6 and maui nightly feeds included, so you're going to be getting main builds (In this case, RC2). If you don't intend to do that, you should clear those feeds from your global nuget or set the source for the workload install to _only_ be the public NuGet feed. Just a heads up before you install!
> 
> It's failing because it can't find `microsoft.aspnetcore.authorization.msi.x64`, probably because it doesn't exist. It's most likely because they don't have an MSI package for the workload, and the default currently in dotnet 6 is to use the MSI versions for workloads.
> 
> If you go into your dotnet directory (On Windows, `C:\Program Files\dotnet\metadata\workloads\6.0.100\installertype`), you can see a feature flag file called 'msi', delete it and rerun the command, it should work.

Hello @drasticactions , Thank you for the reply.

It doesn`t worked.

I`m trying to use the latest bits of the net6 (with and maui).

Now, i'm getting a different error.

Workload installation failed: Failed to validate package signing.

Verificando Microsoft.AspNetCore.Authorization.6.0.0-rc.2.21455.6

error: NU3004: O pacote não está assinado. (The package is not signed)

Falha na validação da assinatura de pacote. (Package signature validation failed.)

Sorry, i'm translating because it's showing in my default language (pt-BR)

**Comment by Midnayt** [comment]
Hi. Now you can install Workload throw VS Installer
![SharedScreenshot](https://user-images.githubusercontent.com/31686881/133382058-4dd67060-45ff-4aa1-8438-ae51767c6058.jpg)

**Comment by juansturla** [comment]
I had a similar case, and running a powershell in admin mode worked for me

**Comment by MichaelPeter** [comment]
I had the same issue with the iOS and Mac. Deleting the MSI Worked

**Comment by drasticactions** [comment]
@fernandozago Then that package isn't properly signed and (I believe) the release installer doesn't allow for unsigned package workloads to be installed. That error was for Microsoft.AspNetCore.Authorization, so I would direct that issue their way if their daily packages are not signed right.

Having said that, if you install a daily SDK build (From https://github.com/dotnet/installer#installers-and-binaries or https://aka.ms/dotnet/6.0.1xx/daily/dotnet-sdk-win-x64.exe, since you're on Windows), those don't check for package signatures and it should install.

**Comment by jfversluis** [comment]
Some workarounds and solutions have been given here and in the meantime new versions have been released. I'm going to assume this is working properly by now. If you still have problems, feel free to open a new issue, thanks!
