### ISSUE TITLE
[iOS] Freezing issue on loading

### ISSUE THREAD

**Issue by RanjithkumarSyncfusion** [dotnet/maui#24895]
### Description
App freezes with infinite layout calls.

### Steps to Reproduce
Simply loaded a grid with 10 labels inside a scrollview and loaded the scrollview inside a content view.

I have attached the sample.
[ScrollViewSample.zip](https://github.com/user-attachments/files/17112925/ScrollViewSample.zip)

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.61 SR6.1

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

No.

### Relevant log output

```shell
-
```

**Comment by drasticactions** [comment]
@RanjithkumarSyncfusion 

Can you please put your sample in a GitHub repo rather than as a source blob? That helps make it easier to check out your code easily without needing to download it and virus scan it.

I ran your code and it worked fine for me on iOS and Mac Catalyst in net8.0 and net9.0. I'm not sure if I'm missing some context here with your application or if you added something to make it "work" here or not.

**Comment by jaosnz-rep** [comment]
This issue cannot be reproduced at iOS17.2/iOS 17.5 on the latest 17.12.0 Preview 2.0(8.0.90). There is no freezing problem.

**Comment by karthikraja-arumugam** [comment]
@RanjithkumarSyncfusion, we couldn't replicate the issue from our side, can you please add a valid reproduction link?

**Comment by jurganson** [comment]
I have been looking at the exact same issue, or at least very similar. The option in the OS that made a difference for me was the Text Size, which if its not in the exact center option, the app will freeze.

The option I am talking about is in iOS Settings > Display & Brightness > Text Size

Try to set that control to the exact center, and perhaps your issue is "worked around".

**Comment by RanjithkumarSyncfusion** [comment]
Hi all,

This happened due to sample mistake. Freeze issue no longer occurs for me. Thank you so much for the response @Everyone.
