### ISSUE TITLE
Failure to navigate to some pages on iOS and Mac Catalyst in 8.0.90 (works in 8.0.82, 8.0.40)

### ISSUE THREAD

**Issue by sumowesley** [dotnet/maui#24897]
### Description

Having previously suffered from the iOS crash when navigating pages (#23139 and #24032), I was keen to check for the update in 8.0.90. Unfortunately, while the navigation now works as expected, I have two applications where it refuses to load pages. On Mac, the rainbow coloured circle of death rotates, whereas iOS  just sits there. Changing back to 8.0.82 or even 8.0.40 (navigation issue not in that version), it works as expected.

### Steps to Reproduce

Not sure there are steps you can use to reproduce. On one application I have to click an item to go to another page, whereas the other application I'm clicking on a database search popup which stays visible on Mac Catalyst but then hangs (rainbow circle) or disappears on iOS showing the underlying screen but not showing search results.

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.82 SR8.2

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 17.5, MacOS 14.6.1

### Relevant log output

```shell
There is no crash event.
```

**Comment by jfversluis** [comment]
@sumowesley unfortunately without any relevant code or reproduction it will be impossible to determine what might be going on and if this is a bug in our SDK or something in your app code. Please find a way to uncover more specifics to your situation and share them with us so we can have a look.

Thanks!

**Comment by sumowesley** [comment]
@jfversluis, I understand the predicament. I've stepped through the view model constructor and the Appearing method we use in the EventToCommand definitions. The XAML is next.

**Comment by PureWeen** [comment]
@sumowesley if you pause the debugger or turn on first chance exceptions does that tell you anything?

**Comment by sumowesley** [comment]
> @sumowesley if you pause the debugger or turn on first chance exceptions does that tell you anything?

@PureWeen, looking at the first app and there was nothing evident in the debug cycle as it got through the ctor and appearing event without incident. We took out the XAML and replaced in one section at a time. The only thing we did find was that removing the below empty footer made it work:

```xaml
<lv:SfListView.FooterTemplate>
    <DataTemplate>
    </DataTemplate>
</lv:SfListView.FooterTemplate>
```
However, that is only part of the story. Removing our SfListView with all its data templates and replacing it with a bare-bones SfListView with just the empty footer template worked fine. Changing it to a CollectionView with an empty footer also worked. It must be a combination of our SfListView properties (we use a slightly modified version to be safety area aware but didn't use it as part of the problem solving), but a combination that works in 8.0.82 and not 8.0.90.

As for the other application, which is similar in behaviour at 8.0.90, it doesn't have the empty footer template. We'll keep looking.

**Comment by NanthiniMahalingam** [comment]
Hi @sumowesley Could you share a basic sample to replicate the reported issue?

**Comment by sumowesley** [comment]
> Hi @sumowesley Could you share a basic sample to replicate the reported issue?
@NanthiniMahalingam, here you go. It's an app that takes you to an opening page containing an Syncfusion SfListView. Using Maui controls and compatibility at 8.0.90, is doesn't show the screen in iOS or Mac Catalyst. At version 8.0.80 or 8.0.82, it does show the screen.  That footer template is the cause, but it works with that foot template in place in Windows and Android. Screenshots to follow.
https://github.com/sumowesley/TestSfListView8090.git

**Comment by sumowesley** [comment]
I'm sorry this took a little longer than planned as I have some ILLINK errors on Mac (it was fine on Thursday). As such the screens come from a few places.
* VS on Windows, remote linked to Mac for the iOS images
* VS on Windows for Windows and Android images
* Mac running app in release mode (no ILLINK errors , only a warning)

iOS with Maui 8.0.90
<img width="150" alt="TestingSfListView_iOS_8_0_90_opening" src="https://github.com/user-attachments/assets/6ad22a3f-7fba-4b2d-a7f7-39de043d2515">

iOS with Maui 8.0.82
<img width="150" alt="TestingSfListView_iOS_8_0_82_opening" src="https://github.com/user-attachments/assets/be2b6810-bdff-468e-bf25-d61c2a98e5c1">

Windows with Maui 8.0.90
<img width="300" alt="TestingSfListView_Windows_8_0_90_opening" src="https://github.com/user-attachments/assets/6377a6de-caf8-43b0-bc5f-f33b741e0844">

Android with Maui 8.0.90
<img width="150" alt="TestingSfListView_Android_8_0_90_opening" src="https://github.com/user-attachments/assets/8a684999-4aa2-425e-9753-f19a4ba63cbf">

Mac with Maui 8.0.80 in release mode
<img width="300" alt="TestingSfListView_Mac_8_0_80_opening" src="https://github.com/user-attachments/assets/7e4693ba-27e3-4a88-82cb-e3376c3f56c9">

Mac with Maui 8.0.90 in release mode: there is nothing to see. It loads the app and the icon appears, but there is no window.

**Comment by vishnumenon2684** [comment]
Hi @sumowesley , We have validated this issue and believe it is not originating from the framework SDK. The problem seems to occur when an empty footer template is added to the visual items in the list view. Specifically, we suspect that the issue lies within the `SfListView` control when handling an empty template.
From our observations, the issue does not appear to reproduce when `SfListView` is properly sized, such as when setting the parent grid's `RowDefinition` height to "Auto."
To obtain a more precise solution, we recommend reaching out to the Syncfusion support team, as they may be able to provide further guidance on this matter.
 
As a workaround solution, you can define an empty Label in the footer template instead of using a plain empty template. For some reason, the MAUI side creates Label content by default if the template is empty. By assigning a template that includes a Label, you can achieve the desired behavior. Please see the example below:
 
<syncfusion:SfListView.FooterTemplate>
         <DataTemplate>
                 <Label />
          </DataTemplate>
</syncfusion:SfListView.FooterTemplate>

**Comment by sumowesley** [comment]
@vishnumenon2684, that doesn't quite explain how it worked in the earlier versions of MAUI, e.g. 8.0.82, but I'm sure this is something Syncfusion will need to wrestle with.

**Comment by sheiksyedm** [comment]
> [@vishnumenon2684](https://github.com/vishnumenon2684), that doesn't quite explain how it worked in the earlier versions of MAUI, e.g. 8.0.82, but I'm sure this is something Syncfusion will need to wrestle with.

When an empty template is added to the view, it creates an empty label content by default. Suspect that the main issue is that the empty label is not being layout properly in the SfListView control alongside the actual list view contents.
 
Tested the same approach using an empty footer template in CollectionView, and it worked correctly without any issues. This leads us to believe the issue is related to how SfListView is handling layout. The problem may not have occurred in previous MAUI versions and seems to be exposed in the latest version.

**Comment by sumowesley** [comment]
@vishnumenon2684,  thank you for the explanation. I'll pursue with Syncfusion.
