### ISSUE TITLE
WebView causes empty window popup and closes immediately

### ISSUE THREAD

**Issue by jhastingsiii** [dotnet/maui#24933]
### Description

This only started happening recently without any code changes, guessing maybe a browser or windows update has caused the problem? There never used to be any kind of flickering popup. If you don't set the source property on the web view, the popup doesn't occur. The popup is hard to see with the default window size, make the window size smaller to see it easier.

### Steps to Reproduce

1. New MAUI app
2. New Page with a web view that has hardcoded source content
3. Navigate to the new page

https://github.com/jhastingsiii/busted-maui-webview

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
Can you please make a small repro project showing this? It makes it easier to establish the issue from a shared context in case anyone else can't.

**Comment by ITaluone** [comment]
I think I have a related problem. I am developing two WinUI apps which both have approximately the same setup.

My app setup is as follows (the same for both):
- WinUI app
- App creates a system tray icon
- App hides on startup; This is done in various places: 
  - `MauiProgram.cs``ConfigureLifecycleEvents()` 
 
```csharp
  builder.ConfigureLifecycleEvents(lifecycle =>
      {
#if WINDOWS
          lifecycle.AddWindows(lifecycleBuilder => lifecycleBuilder
              .OnPlatformMessage((window, _) =>
              {
                  if (!(IsStarting && ps.StartInSystemTray())) return;

                  GetAppWindow(window);

                  _appWindow.Hide();
              })
              .OnVisibilityChanged((_, args) =>
              {
                  if (IsStarting && ps.StartInSystemTray())
                  {
                      DisableStarting();
                      return;
                  }

                  if (!ps.Get<bool>(StorageKey.MinimizeToSystemTray)) return;

                  if (IsClosing || args.Visible)
                  {
                      App.ResizeSave();
                      return;
                  }

                  MinimizeToTray();
              })
              .OnWindowCreated(window =>
              {
                  // window.ExtendsContentIntoTitleBar = true; // https://github.com/dotnet/maui/issues/18773
                  GetAppWindow(window);

                  if (ps.StartAppMaximized() && _appWindow.Presenter is OverlappedPresenter p) p.Maximize();

                  _appWindow.Closing += (_, e) =>
                  {
                      e.Cancel = true;

                      if (ps.Get<bool>(StorageKey.DoNotQuitApp) && !ForceClose)
                      {
                          MinimizeToTray();
                          return;
                      }

                      SetClosing();
                      Application.Current?.Quit();
                  };
              }));
#endif
      });
  ```
   - The universal `App.cs` where I do some window resizing and such (and also check if it should launch in systray)

In the past, this setup prevents the app window to show at all on startup (just makes the systray icon (with H.NotifyIcon.Maui, btw) and nothing else, until the user opens the app by icon click.
This is the setup both share. 

But since today or so (I can not tell since when exactly, because I stumbled upon this today the first time) a blank window pops up, size is approx. window height and the width approx. width/2.

### What I tried:
- I tried to debug this, but cannot find a point when this appears to happen. 
- I updated MAUI to 8.0.91 today, so I reverted this -> didn't help
- I reverted back to the latest commit (aka release) -> did work the first recompile, but next recompile it is flickering again

### Conclusion
I can not tell what had changed, but it seems that MAUI is not the only actor in the story, because when I start the already released and deployed apps it works as it should. Probably a race condition with WASDK/MAUI or .NET SDK.

**Comment by jhastingsiii** [comment]
> Can you please make a small repro project showing this? It makes it easier to establish the issue from a shared context in case anyone else can't.
Yes, it wouldn't let me attach it to the original ticket for some reason, here it is.
[MauiApp1.zip](https://github.com/user-attachments/files/17149906/MauiApp1.zip)

**Comment by jhastingsiii** [comment]
> Hi @jhastingsiii. We have added the "s/needs-repro" label to this issue, which indicates that we require steps and sample code to reproduce the issue before we can take further action. Please try to create a minimal sample project/solution or code samples which reproduce the issue, ideally as a GitHub repo that we can clone. See more details about creating repros here: https://github.com/dotnet/maui/blob/main/.github/repro.md
> 
> This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

Broken bot? Not only did I provide the steps for reproducing the problem, but I also provided the source code as well.

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.12.0 Preview 2.0(8.0.91 & 8.0.3) 17.11.4 (7.0.101). Can not repro this issue at windows platform.

**Comment by RuddyOne** [comment]
I have also started seeing this issue with no code change. Do we know what this issue is and any workaround/fixes for now?

**Comment by ITaluone** [comment]
As I said: I think MAUI is not to blame here. My apps are `MAUI.Blazor` apps, so every launch of an app launches `WebView2` and revealing this issue at app startup immediately.

**Comment by rswilley** [comment]
I am having this same problem. Last week I didn't have this issue and with no code change I am seeing a flickering popup.

**Comment by MatthewKing** [comment]
I am having this same issue. No code changes.

**Comment by stephenquan** [comment]
I tried the workaround from https://github.com/MicrosoftEdge/WebView2Feedback/issues/4834#issuecomment-2381904393 by adding:

`Environment.SetEnvironmentVariable("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--window-size=0,0 --window-position=20000,20000");`

to my `App.xaml.cs` before `InitializeComponent();` and it appears to obfuscate the empty window popup. This might be a satisfactory workaround that can be put in place until this issue is fixed.

**Comment by PureWeen** [comment]
Adding this to our .NET9 SR1 milestone for tracking purposes

I'll update once a fix from WebView2 is out.

**Comment by Redth** [comment]
Thanks for the reports and the repro step details.

This one is unrelated to MAUI and is reproduceable with a plain .NET WinUI3 app.  We're waiting on an upstream fix for the issue already mentioned here: https://github.com/MicrosoftEdge/WebView2Feedback

**Comment by jhastingsiii** [comment]
This issue is fixed now with the latest Edge release Version 130.0.2849.46 (Official build) (64-bit)
