### ISSUE TITLE
Opening New Window On Android Not Working

### ISSUE THREAD

**Issue by Fred-Hudson-CST** [dotnet/maui#24955]
### Description

I have a multi-window application that works as expected on windows but on android pressing the open new window button in the app does nothing, by debugging I can see that the new window is created but when `App.Current?.OpenWindow(myWindow)` is called no new window is opened and `App.Current?.Windows` only contains 1 window the original one.

### Steps to Reproduce

Create a new app from the vs template file and attempt to open a new window with `App.Current?.OpenWindow(myWindow)`. this will fail to open a new window 

### Link to public reproduction project repository

https://github.com/Fred-Hudson-CST/TestOpenNewWindow

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

 NO

**Comment by drasticactions** [comment]
https://github.com/Fred-Hudson-CST/TestOpenNewWindow/blob/master/TestOpenNewWindow/Platforms/Android/MainActivity.cs#L7

The default LaunchMode is `LaunchMode = LaunchMode.SingleTop`, which won't launch the activity (and so won't create the MAUI Window). If you remove it or set it to "LaunchMode.Multiple" it should work.

You also don't need to do this, but going forward in .NET 9 the default App.xaml.cs overrides the CreateWindow function and sets the window on it, rather than using "MainPage." and if you're creating new Windows you should also handle this.

```
public partial class App : Application
    {
        public App()
        {
            InitializeComponent();
        }

        protected override Window CreateWindow(IActivationState? activationState)
        {
            return new Window(new AppShell());
        }
    }
```

https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/windows?view=net-maui-8.0

The docs don't mention the LaunchMode setting. I think in net7.0 it wasn't set, but now it is in net8.0. That matters here, it probably should be added to the docs as a setting that should change (or something else is happening that causes it to not work with SingleTop mode, but AFAIK it would never work with that.)

**Comment by jaosnz-rep** [comment]
I can repro this issue at Android platform on the latest 17.12.0 Preview 2.0(8.0.90 & 8.0.91).

**Comment by Fred-Hudson-CST** [comment]
@drasticactions thankyou very much this solves my issue, and yes I agree the docs should be updated to mention this, probably in the same section as the the Plist changes for mac and ios
