### ISSUE TITLE
Error APT2067 failed processing manifest

### ISSUE THREAD

**Issue by danroth27** [dotnet/maui#2500]
I created a .NET MAUI Blazor app with VS2022 P4, tried to build it and got this error initially:

Error APT2067 failed processing manifest. MauiApp1 C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.100-rc.1.12\tools\Xamarin.Android.Aapt2.targets 217

Error APT2260 resource style/Maui.SplashTheme (aka com.companyname.MauiApp1:style/Maui.SplashTheme) not found. This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file. MauiApp1 C:\Users\daroth\source\repos\MauiApp1\MauiApp1\Platforms\Android\AndroidManifest.xml 1

Error APT2260 resource xml/xamarin_essentials_fileprovider_file_paths (aka com.companyname.MauiApp1:xml/xamarin_essentials_fileprovider_file_paths) not found. This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file. MauiApp1 C:\Users\daroth\source\repos\MauiApp1\MauiApp1\Platforms\Android\AndroidManifest.xml 1

Rebuild then worked.

**Comment by Ghevi** [comment]
I also encounter this issue when trying to run the command `dotnet publish -f:net6.0-android -c:Release`

`
AndroidManifest.xml: error APT2260: resource style/Maui.SplashTheme (aka style/Maui.SplashTheme) not found. 
AndroidManifest.xml : error APT2260: This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file. 
Xamarin.Android.Aapt2.targets(217,3): error APT2067: failed processing manifest.
`

**Comment by kristinx0211** [comment]
Not reproducible with windows 10.0.19041.
