### ISSUE TITLE
Javascript Callbacks In WPF Blazor Not Working

### ISSUE THREAD

**Issue by musictopia2** [dotnet/maui#2544]
I tried the new preview of blazor control for hosting blazor content.  I am using a component that uses eventcallbacks from javascript.   That part is not working.  What is happening is instead of calling the c# method, it does nothing which means if the information is needed to render a page, then nothing renders.  The problem does not happen with webassembly or even blazor server side.

**Comment by Eilon** [comment]
Hi @musictopia2, this appears to be fixed now, probably because of the many fixes we did to handle static assets. I took portions of the code from your sample and here it is when it loads:

![image](https://user-images.githubusercontent.com/202643/133689152-835b115b-5485-4208-80d7-3d4a2afca42d.png)

And after I resize the window small:

![image](https://user-images.githubusercontent.com/202643/133689192-71e49fba-9532-4924-b06c-805770399b68.png)

And huge:

![image](https://user-images.githubusercontent.com/202643/133689235-21c9e7e3-7b93-4040-a642-c25decb5bfd0.png)

**Comment by musictopia2** [comment]
I saw it was fixed as of preview 5 even.  The time I reported the problem was preview 3.

**Comment by Eilon** [comment]
Ah, yes, sorry it took so long to get to this. We did an issue cleanup to consolidate most Blazor Desktop issues into this repo and found this bug.
