### ISSUE TITLE
BlazorWebView should support the "Fixed Distribution Mode" of the WebView2 runtime

### ISSUE THREAD

**Issue by stephansum** [dotnet/maui#2548]
**Current behaviour:** _BlazorWebView_ needs the _WebView2_ runtime to be installed on the system.

**Desired behaviour:** I would like to distribute a fixed _WebView2_ version along with my Blazor Desktop App (making my App working standalone). 

_WebView2_ already offers a fixed version distribution mode for that scenario: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#fixed-version-distribution-mode

However, using the new _BlazorWebView_ component there is currently no way to set the _BrowserExecutableFolder_ to specify the location of the fixed _WebView2_ binaries.  

See: https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebView/Platforms/Wpf/src/BlazorWebView.cs

**Comment by mkArtakMSFT** [comment]
This probably already works and we need to document it.

**Comment by Eilon** [comment]
For anyone wanting to do this in a .NET MAUI Blazor Hybrid app, here's what you need to do:

1. In `MauiProgram.cs` update the `CreateMauiApp()` method to set the location of the specific WebView2 Runtime that you want your app to use:
    ```c#
 	public static MauiApp CreateMauiApp()
	{
        Environment.SetEnvironmentVariable("WEBVIEW2_BROWSER_EXECUTABLE_FOLDER", @"C:\Program Files (x86)\Microsoft\EdgeWebView\Application\114.0.1823.58");

        var builder = MauiApp.CreateBuilder();
	...
    ```
2. Optional: It is recommended to ensure that the specified WebView2 Runtime is installed on the machine or otherwise you'll probably get some errors in your app:
   1. Have your app's installer check that the desired WebView2 Runtime is installed (and consider installing it automatically if needed)
   2. Have your app's startup code check the desired WebView2 Runtime is installed (and if it's not, offer to remedy the situation)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're going to address this through providing documentation on how to do it, and that is tracked through: https://github.com/dotnet/AspNetCore.Docs/issues/29882
