### ISSUE TITLE
Embedded web view for blazor hybrid

### ISSUE THREAD

**Issue by Mortezamir81** [dotnet/maui#25557]
### Description

Hello, why don't you make an internal web view like React Native for Blazer Hybrid so that running the program in different versions of Android, especially lower versions, will not be a problem? In the Android operating system, there are many modes for viewing the web on users' phones, and this causes many problems in the correct execution of the program on different devices. If I create a Blazer Maui application right now, I will definitely not be sure of its correct operation on different devices, and this is a very important issue in the business field.

### Public API Changes

-

### Intended Use-Case

-

**Comment by jfversluis** [comment]
Do you mean we build our own web view control?

In that case I'm pretty sure we're not going to do that. That will be a big undertaking and the paradigm of .NET MAUI is to map every abstract control to whatever is native on the underlaying platform.

Could you please confirm if that is what you mean?
Is there any specific reason for this request? I think you should be able to create identical interfaces with the big web render engines out there. On Windows and Android it should use the same engine and for iOS and macOS as well.

**Comment by Mortezamir81** [comment]
I don't mean to translate the web controls to Native controls, I mean that these web controls and js and css codes are rendered in the same way in different operating systems and it is not like that in Android 8 webview a series It doesn't support js and css and it is different in different androids...

**Comment by jfversluis** [comment]
I think we're saying the same thing. And I don't mean render the actual HTML and CSS elements to native controls. What I meant in this case is that the web views we are using are translated to their native counterparts. So that means when you specify a `WebView` in .NET MAUI we will use `WebView2` on Windows, `android.webkit.WebView` on Android and `WKWebView` on iOS and macOS.

If we want to make sure to render everything the same 100% of the time we would have to build our own web view component and always use that or maybe even our own rendering engine. That is not the core of our product and I don't see us ever doing that unfortunately.

Additionally, I think that the rendering engines out there should pretty much implement the standards and there shouldn't be a lot of differences between the platforms.

Anyway, sorry I can't give you the answer you want. Hope this still helps and explains a bit about the how and why.
