### ISSUE TITLE
Default configurations for Debug and Release mode

### ISSUE THREAD

**Issue by rezamohamed** [dotnet/maui#25675]
### Description

Is there a single source of truth for the defaults for a Debug config and Release config for Android and iOS? Combing through the plethora of information on the web has been frustrating, especially when a build works in Debug and fails in Release and you are trying to figure out the delta of the builds. The information currently available seems to be pure descriptors without telling how to enable, or disable them/or what the defaults are and how they are configured in CSPROJ. Or they are outdated or for a different platform altogether.

Offhand, there is  - linking, trimming, llvm, aot, multi-dex, r8, optimize, EmbedAssembliesIntoApk, to name a few. What are the correct means of enabling and disabling them in CSPROJ (especially now that a visual interface is not available in Mac, this is important)?

### Version with bug

8.0.92 SR9.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

requesting source of truth for iOS and Android

**Comment by ninachen03** [comment]
You may be using the Maui project, and the build in release mode failed. Could you give the specific error information?
 In order for us to investigate this further, could you please provide repro steps and sample project, What is the actual result? It would be very helpful if you could provide some screenshots of this problem.
This below document may be useful for setting up your project.
https://learn.microsoft.com/en-us/dotnet/maui/deployment/visual-studio-properties?view=net-maui-8.0
I'll give you a screenshot, just simply enabling AOT and LLVM 
![Image](https://github.com/user-attachments/assets/56aec628-4421-4c4b-95eb-1ad4e19bc2cf)

**Comment by jfversluis** [comment]
I think the reason that there is so much information is simply because there is no single source of truth here and its very much dependant on your situation and needs.

As for specifics to .NET MAUI, there is a doc on configuration options [here](https://learn.microsoft.com/dotnet/maui/deployment/visual-studio-properties). Those should cover the options that have a UI in Visual Studio (for Mac). I guess it could be a nice (community) initiative to have some screenshots of what in the VS for Mac UI maps to which of these options. Let me know if anyone does that!

Then for trimming we have information [here](https://learn.microsoft.com/dotnet/maui/deployment/trimming). And NativeAOT is [here](https://learn.microsoft.com/en-us/dotnet/maui/deployment/nativeaot).

Looking at `EmbedAssembliesIntoApk` which you specifically mention, that is something that is very specific to Android. So those can be found in the more .NET for Android [specific docs](https://learn.microsoft.com/dotnet/android/building-apps/build-properties).

I understand there are a lot of moving parts here, which is kind of by nature for a cross-platform framework I guess, but if you have any concrete ideas on how we can make it better, we'd love to hear that!

**Comment by SteveBush** [comment]
I proposed using Configuration.StartsWith('Debug') instead of Configuration == 'Debug' in issue #25874.  I also wanted to second that it's a pain in the ass to discover all of the build settings tied to 'Debug' and 'Release' configurations across Maui and dotnet.
