### ISSUE TITLE
vs 2022 with .net 9

### ISSUE THREAD

**Issue by kenspencer8996** [dotnet/maui#25704]
### Description

numerous xaml and c# class files lose the ability find files in certain namespaces

### Steps to Reproduce

open the CatorisCityApp9) project.
build.
see the CityscapeStreets.cs file.. It cant find the controller CityscapeStreetsController even though the correct using is set.

### Link to public reproduction project repository

https://github.com/kenspencer8996/CatorisCityApp9.git

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windowa 10

### Did you find any workaround?

not yet

**Comment by kenspencer8996** [comment]
Not sure if this is vs beta or .net 9 rc

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using  Visual Studio 17.12.0 Preview 5( 9.0.0-rc.2.24503.2 & 8.0.92 & & 8.0.3 & 7.0.101). Can repro this issue on windows platform.

**Comment by jfversluis** [comment]
I don't think this is an issue with .NET MAUI. 

First you want to remove all of these entries

https://github.com/kenspencer8996/CatorisCityApp9/blob/master/CatorisCityApp9/CatorisCityApp9.csproj#L61-L74

And you can remove all of these too: https://github.com/kenspencer8996/CatorisCityApp9/blob/master/CatorisCityApp9/CatorisCityApp9.csproj#L93-L209

Unfortunately Visual Studio sometimes adds these entries that are not needed and will actually cause issues.

After that, the error I get is about `UIHelpers` not being able to recognize `CityStreetMasterViewModel` which is because there are two. One [here](https://github.com/kenspencer8996/CatorisCityApp9/blob/master/CatorisCityApp9/Viewmodels/CityStreetMasterViewModel.cs) and one [here](https://github.com/kenspencer8996/CatorisCityApp9/blob/master/CatorisCityApp9/Objects/CityStreetMasterEntity.cs) (note the filename does not match the type, so maybe this is an error).

After that it can't find some other types like `RobberyMessageDetailEntity`, I can't find those, so maybe these weren't committed to the repository.

None of these errors have anything to do with a potential bug in .NET MAUI. As such, closing this one for now. Let us know if you think there is something still wrong. Thanks!
