### ISSUE TITLE
wrong version in latest release

### ISSUE THREAD

**Issue by devmanspi** [dotnet/maui#25712]
Hello,

the latest maui version is version 8.0.83. The version code was changed from 8.0.92 to 8.0.83.
Shouldn't the version be 8.0.93 now?

**Comment by jfversluis** [comment]
Thanks for keeping us honest! 😉 

It might seem a little weird, but this release was done as a service release on top of the 8.0.82 version. Namely [this PR](https://github.com/dotnet/maui/pull/25587) was merged to fix a security vulnerability.

Because of all the moving parts for .NET 9 and .NET 8 right now, this was released like this as a patch release for 8.0.83 because that is the version that will be shipped with Visual Studio.

Long story short, mostly internals here at Microsoft and we will resume regular services releases with "normal" versioning schemes after this 😄

**Comment by devmanspi** [comment]
Ok, thanks for clarifying that. I was actually a little confused what verison to use now.
