### ISSUE TITLE
iOS BackButton Title cannot be set to string.Empty or ""

### ISSUE THREAD

**Issue by FreakyAli** [dotnet/maui#25742]
### Description

Using Shell if you remove the back button title or set it to empty it does not work and just sets it to the previous page title. 
This worked fine on Xamarin.Forms 

### Steps to Reproduce

- Create two pages using Shell as the Navigation 
- Once you have navigate from Page 1 to Page 2
- On Page 2 use the below Behavior

```
<Shell.BackButtonBehavior>
     <BackButtonBehavior TextOverride="" />   
</Shell.BackButtonBehavior>
```

Expected Behavior: 

Back button text should show empty

Actual behavior: 

It will show a back button with the previous page title 

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

8.0.92 SR9.2

### Affected platforms

iOS

### Affected platform versions

All iOS devices I can find 

### Did you find any workaround?

No 

### Relevant log output

NA

**Comment by mattleibow** [comment]
@PureWeen I somehow feel this is an iOS "design" decision? The OS will use the previous title if you clear it.

@FreakyAli what happens if you use a blank string `" "`? Does iOS do any trimming? 

Everyone thought the ages was using a space... https://stackoverflow.com/questions/23853617/uinavigationbar-hide-back-button-text

You could use a `{OnPlatform iOS=' ', Default=''}` and then that will hopefully clear it. But yeah, iOS is "smart" and does what it wants.

**Comment by FreakyAli** [comment]
> @PureWeen I somehow feel this is an iOS "design" decision? The OS will use the previous title if you clear it.
> 
> @FreakyAli what happens if you use a blank string `" "`? Does iOS do any trimming? 
> 
> Everyone thought the ages was using a space... https://stackoverflow.com/questions/23853617/uinavigationbar-hide-back-button-text
> 
> You could use a `{OnPlatform iOS=' ', Default=''}` and then that will hopefully clear it. But yeah, iOS is "smart" and does what it wants.

The same thing happens when you give it a whitespace
