### ISSUE TITLE
It takes far too long for pull requests to be merged!

### ISSUE THREAD

**Issue by AlleSchonWeg** [dotnet/maui#25747]
There are some pull requests that contain bug fixes but do not make their way into MAUI. This is frustrating when you find a bug and the fix has been in the queue for months.
Why is that?
Samples:
https://github.com/dotnet/maui/pull/16252
https://github.com/dotnet/maui/pull/23599
https://github.com/dotnet/maui/pull/24429
https://github.com/dotnet/maui/pull/25068
https://github.com/dotnet/maui/pull/24766
https://github.com/dotnet/maui/pull/24425
https://github.com/dotnet/maui/pull/21025
...

For me this is an issue, because i don't know what i should do. Waiting or implement workaround or something other.

@kubaflo for example do a great job. He tried to fix a lot of things: https://github.com/dotnet/maui/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aopen+author%3Akubaflo
But more PR are open than merged.

**Comment by jfversluis** [comment]
We're doing what we can based on the priorities we see. 

What you could do to help is [try out the fixes on your project](https://youtu.be/B2FOBjZKm9k) and let us know if it seems to fix it. I can't promise that will instantly mean that we will merge it, but it helps us with getting confidence that the fix is indeed the right one.

Another approach to this could be to take a look at the code and see if you can implement that as a workaround for the time being in your project and ideally of course share that back so others can benefit too.

Thanks for this signal, but I don't think its super productive to have an issue open for this with potentially a whole discussion surrounding this which will only take away more from the time that we need to review PRs 😄 as such, closing this for now.

**Comment by AlleSchonWeg** [comment]
Thank you @jfversluis ,
i don't want a discussion.
But for us developers it is also super inefficient not to know why a PR is on hold. We see a bug and a PR which fixes the issue and then we are lost. Nobody knows if the merge will happen in 2 weeks, 2 month or never. This makes it difficult to plan releases.

**Comment by jfversluis** [comment]
I totally understand and believe me, it brings me no joy that this is the case. We're continually trying to improve our processes and do better. Unfortunately, we're also just people and only have 24 hours in a day and tons of things to do, just like you.

As to your point: I guess always assuming that it never gets merged will mostly circumvent that problem 😉 your priorities and ours might differ, so if you need any of this sooner rather than later, always plan as if no help will come from our side, then you'll always be happily surprised.

And as mentioned: if you can test out those fixes, that will at least give us some confidence that a fix works correctly and doesn't break other things, that is always super helpful and feel free to ping me and let me know.

**Comment by kubaflo** [comment]
Yeah the truth is that they just don’t like me haha..

But seriously, I don’t take it personally that some of my PRs sit around for months - I understand the team has its priorities. I’m genuinely happy about the ones that have been merged, and I’m sure the remaining ones helped folks find workarounds for their own bugs and keep things moving with their projects

Cheers!

**Comment by AlleSchonWeg** [comment]
Yes. Nobody should take this personally. This was not my intention. All do the best they can. But there is still space for improvement. And this delay is, in my opinion, one of the things that needs attention. It helps nobody if pr are forgotten. Not the users, the contributors  and not the Maui team.

**Comment by AlleSchonWeg** [comment]
@kubaflo you do a really good job with your contributions to this repository. Thank you very much.
Without your work Maui had a lot more annoying bugs. And you do this in your free time! This is amazing. 
Please keep going on.

**Comment by kubaflo** [comment]
@AlleSchonWeg thanks for your kind words! And, yes, I will certainly keep on going 😄
