### ISSUE TITLE
[Bug] tvos and macos are missing after installation of Visual Studio 2022 Preview 4

### ISSUE THREAD

**Issue by UweReisewitz** [dotnet/maui#2586]
### Description
I'm sorry for opening this issue in two repos (this is a duplicate of https://github.com/Redth/dotnet-maui-check/issues/126), but I'm not sure which team needs this information. 

tvos and macos are not part of the Preview 4 components. Check-maui is unable to install them afterwards. I believe they are missing in rc1?
### Steps to Reproduce
Install VS 2022 Preview 4, the workloads mentioned above are not available in the installer and cannot be installed later by maui-check
1. 
2. 
3. 

### Basic Information

- Version with issue: VS 2022 Preview 4
- Last known good version: N/A
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
