### ISSUE TITLE
Registry key does not show on registry editor but read/write works on Windows

### ISSUE THREAD

**Issue by shahadatshakil** [dotnet/maui#26299]
### Description

I am creating a simple registry key from MAUI app. The read and write on the key works fine. But when I try to view the key on the windows registry editor, it does not show there.

The registry key/value shows as expected when creating the project using dotnet 9. 
But doesn't show if the app is created with dotnet8. Same happens when first creating a dotnet 8 project and then change its version to dotnet 9.

What could be the actual reason for this?

**Test Code:**
```
            using (RegistryKey regEntry = Registry.CurrentUser.CreateSubKey("SOFTWARE\\MySoft\\MyLocation"))
            {
                regEntry?.SetValue("MyKey", "TestValue");
            }
```

Registry view:
![Image](https://github.com/user-attachments/assets/58497995-0909-417e-954d-ec395a962333)

### Steps to Reproduce

1. Create a .net MAUI app on windows platform.
2. Create a sample registry key at any location(for reference: `MainPage.xaml.cs` file on the test project). 
3. Run the application.
4. Open registry editor to check the key.

**Expected behavior:** The key is visible on the registry editor.
**Actual behavior:** The key is missing on the registry editor. But read write works fine.

### Link to public reproduction project repository

https://github.com/shahadatshakil/RegistryTestingNet8

### Version with bug

8.0.83 SR8.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK version 10.0.19041.0

### Did you find any workaround?

If I run the same code on a .net 9 MAUI app(tested on 9.0.0), the registry key and value shows on the registry editor. But this should be the same for other .net versions.

### Relevant log output

```shell

```

**Comment by jeremy-visionaid** [comment]
I'd guess this is due to MSIX packaging

**Comment by jfversluis** [comment]
Yeah I'm pretty confident this is not a .NET MAUI issue. It might be WinAppSDK? I'm not even sure and indeed it might have to do with packaged vs unpackaged: https://learn.microsoft.com/dotnet/maui/whats-new/dotnet-9?view=net-maui-9.0#windows-app-deployment

Reading your report again it seems you're saying that it doesn't work in .NET 8, but it does work in .NET 9. That would explain this: for .NET 8 .NET MAUI apps were packaged by default and I think they will have their own virtualized registry, because they have their own sandbox.

If you create a new .NET MAUI app with .NET 9, it will be unpackaged by default and run more like a regular app within Windows with access to all the things.

See the link above on how to switch between the two variations, that should help you make this also work for .NET 8. However, you want to be on .NET 9 anyway as .NET 8 for .NET MAUI will be out of support in May 2025.
