### ISSUE TITLE
Dynamically Added FlyoutItems During Navigation Not Displayed on Windows

### ISSUE THREAD

**Issue by NafeelaNazhir** [dotnet/maui#26391]
### Description

When adding FlyoutItems dynamically during navigation using the Shell.Navigating event, the newly added items do not appear in the flyout on Windows.
![Image](https://github.com/user-attachments/assets/4414f3a8-23c7-40bf-abac-90ebe9705fb5)
In other platforms
![Image](https://github.com/user-attachments/assets/3d33422b-012c-4d6a-8fca-1b71ce9b6cdd)

### Steps to Reproduce

1. Run the Sample [Issue11214Sample.zip](https://github.com/user-attachments/files/18023286/Issue11214Sample.zip)
2. Open the flyout and tap the FlyoutItem "Click Me You Should See Two Items".
3. Observed that Items are not appear.

Expected Behavior:
The dynamically added FlyoutItems should appear in the flyout .
Actual Behavior:
The dynamically added FlyoutItems do not appear in the flyout.

### Version with bug

9.0.12 SR1.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

Windows

### Relevant log output

```shell

```

**Comment by NirmalKumarYuvaraj** [comment]
Setting the SelectedItem of the NavigationView triggers the ItemInvoked event again, which in turn causes the OnNavigating method to be called twice. I found a PR that links this behavior to an underlying native issue.

Native issue PR - https://github.com/microsoft/microsoft-ui-xaml/issues/6397 .

The event firing a second time occurs because the current item is being updated in the [MapItems](https://github.com/dotnet/maui/blob/b615b738f902b9c7a7f4123ba6af63d65ccdeafe/src/Controls/src/Core/Handlers/Shell/ShellHandler.Windows.cs#L190) and [MapFlyoutItems](https://github.com/dotnet/maui/blob/b615b738f902b9c7a7f4123ba6af63d65ccdeafe/src/Controls/src/Core/Handlers/Shell/ShellHandler.Windows.cs#L193) methods. Commenting out these lines resolves the issue, but the flyout selection is no longer in sync with the shell.

PR - https://github.com/dotnet/maui/pull/10295.

For a workaround , we can simply returning the second call without performing any operation on windows platform resolves the issue and test case is passed.

#### Workaround
```c3
#if WINDOWS
	// Modifying SelectedItem in Navigation view causes the OnNavigated method to be called again. 
	int count = 0;
#endif


protected override void OnNavigating(ShellNavigatingEventArgs args)
{
		// Existing code

#if WINDOWS
		count++;
		if (count % 2 == 0)
			return;
#endif
	// Adding and removing logic here
	
}

```


![Image](https://github.com/user-attachments/assets/8f0bf494-91f8-4eda-904c-f2415ec0bb26)

**Comment by NafeelaNazhir** [comment]
The suggested workaround has been implemented successfully, and the issue is no longer reproducible.
