### ISSUE TITLE
MAUI building MAC catalyst Arm64 dll is not getting loaded and throws System.BadImageException

### ISSUE THREAD

**Issue by ashtkumar2023** [dotnet/maui#26500]
Hello Team,

1) I have a sample MAUI app targeting only **net7-maccatalyst-arm64/net8-maccatalyst-arm64** that generates the macatalyst-arm64. dll[Release, AnyCPU mode]. arm64-DLL is having resources like string text and icon.

2) I created a sample non-MAUI console app and tried to load the arm64 dll generated in step1 in this and this dll also throws BadImageException upon load through 'System.Reflection.Assembly'.

Upon load of the dll , "System.BadImageException" is thrown. Looks like MAUI building the arm64 dll is getting corrupted.

Attaching the sample console along with MAUI app.  Could you please look into this and let us the know the feedback ?

Attached is the  sample MAUI app and the console application targeting Net 8 [.[](url)]([dotNet7_Maui_App2.zip](https://github.com/user-attachments/files/18079137/dotNet7_Maui_App2.zip)
[LoadMaccatalystDll.zip](https://github.com/user-attachments/files/18079138/LoadMaccatalystDll.zip)
)

**Comment by jfversluis** [comment]
Could you please post your reproduction projects as public GitHub repositories?

**Comment by drasticactions** [comment]
.NET 7 MAUI support ended on [May 14th, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/maui) so you may want to upgrade to a newer, supported version of .NET.

Looking at the repo, it is only the .NET MAUI app, but I think you may be confused since you said "console app". A console app built on a Mac in .NET is not the same thing as a Mac bundle, so it working in a console app does not apply to one using the .NET Mac Catalyst SDK. You probably want to try building a .NET Mac Catalyst app that doesn't include the MAUI UI framework (`dotnet new maccatalyst`) and try it there. I can also see in the repo you're pulling in Dotfuscator, I'm not sure of the impact that could have on a Mac Catalyst build.

@rolfbjarne Would you have suggestions on what can be provided here?

**Comment by ashtkumar2023** [comment]
@drasticactions , I will be disregarding this issue and reopening a new bug with the template.

**Comment by rolfbjarne** [comment]
> 2\. I created a sample non-MAUI console app and tried to load the arm64 dll generated in step1 in this

This won't work; the output of a Mac Catalyst project is a self-contained app bundle (a `.app` directory). It's not possible to load selected pieces of this app bundle from elsewhere.

Exactly what do you need to do? If you could explain what you want done, we might be able to give alternative solutions to your problem.
