### ISSUE TITLE
The RealParent on Syncfusion.Maui.PdfViewer.SfPdfViewer has been Garbage Collected.

### ISSUE THREAD

**Issue by IllyaYushchenko** [dotnet/maui#26666]
### Description

Syncfusion PDF viewer if every now and then failing to open the PDF. It does not depend on file - same file can be opened normally a few times and the next attempt fails.

logs show this -
`Microsoft.Maui.Controls.Element: Warning: The RealParent on Syncfusion.Maui.PdfViewer.SfPdfViewer has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui`

### Steps to Reproduce

Create MAUI app and add Syncfusion PDF viewer 

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ios 17.5, 18.1, 18.2

### Did you find any workaround?

Havent noticed same issue on android, or maybe i just didint test enough, since it fails on iOS only sometimes.
Anyway iOs is the main priority now

### Relevant log output

```shell

```

**Comment by IllyaYushchenko** [comment]
upd,
on Android app crashes with
` Cannot access a disposed object. Object name: 'Syncfusion.Maui.Core.Platform.LayoutViewGroupExt' `

**Comment by IllyaYushchenko** [comment]
Hi! I\m unable to reproduce the issue in a new project. I will close the ticket for now

**Comment by Pmr-precure** [comment]
This also happens sometimes to MediaElement from Community toolkit. For us it happens when a page is playing a Video, and then we change to a new page by setting the App.Current.MainPage. 

![Image](https://github.com/user-attachments/assets/f3069acc-1c58-4f07-965a-3a63e0aadb50)
Seems like it could be fixed by having a try catch here. (But i have no idea how to do a PR with that added)

BR Pelle
