### ISSUE TITLE
[Bug] Cannot run MAUI on IOS Simulator

### ISSUE THREAD

**Issue by cdavernas** [dotnet/maui#2681]
### Description

Cannot run a MAUI app on IOS Simulator. Sometimes it will tell me I need a recipe file, sometimes it will bring up the "Pair To Mac" tool.

### Steps to Reproduce

1. Create a new MAUI app
2. Select iOS Simulators > Simulator
3. Start debugging

### Expected Behavior

The app should start running

### Actual Behavior

Either one of the following:

- Build fails with 'Need recipe file' error
OR
- Pops up the 'Pair to Mac' dialog

**Comment by drasticactions** [comment]
"Need recipe file" is a known issue with VS 2022 Preview 4, where Visual Studio will sometimes select "Windows Machine" from the launchprofile.json even though it's not selected for deployment. If this happens, make sure you have "net6.0-ios" selected as the target framework, then select "Windows Machine", then select the simulator or device you want to deploy to. That should then deploy to the correct device.

The issue is not directly related to MAUI. It's an IDE tooling issue.

For the Pair to Mac screen, that's what will happen you select iOS Simulator. When you pair to your mac, the drop-down should show the list of simulators. If you did pair, and it's not showing that, that's an IDE bug and I would file that with Visual Studio.

**Comment by cdavernas** [comment]
@drasticactions Allright, thank you, that did solve the problem!

As for iOS Simulator, I was under the impression that it was some kind of VM or Emulator allowing devs to test MAUI without owning/pairing a MAC. As per your comment, I realize that's not the case.

As far as I'm concerned, the issue is closed. Thanks again!
