### ISSUE TITLE
When can preview

### ISSUE THREAD

**Issue by qcjxberin** [dotnet/maui#274]
Net 5 has been officially released. When will MAUI release the preview version and start trying it out?

**Comment by realivanjx** [comment]
[This](https://github.com/dotnet/maui/wiki/Roadmap) says late 2020. Not really related to net 5 release.

**Comment by dotfelixb** [comment]
> [This](https://github.com/dotnet/maui/wiki/Roadmap) says late 2020. Not really related to net 5 release.

Not as in 31st December I hope

**Comment by VladislavAntonyuk** [comment]
> > [This](https://github.com/dotnet/maui/wiki/Roadmap) says late 2020. Not really related to net 5 release.
> 
> Not as in 31st December I hope

why not? you don't like New Year presents?)

**Comment by qcjxberin** [comment]
Everyone should hope that the sooner it will be launched, the better. I used to learn to use flutter, but now I start to use xamarin to learn, research and develop.

**Comment by Rand-Random** [comment]
I highly doubt that the timeframe will be met, because the development for xamarin 5 haven't finished, the plan was to finish with the .net release but it was postponed.

Currently they are on preview 4:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/5.0/5.0.0-pre4

Here you can see the xamarin roadmap, that is slightly outdated saying october/november
https://github.com/xamarin/Xamarin.Forms/wiki/Feature-Roadmap

Since MAUI is based on Xamarin they IMHO first have to finish Xamarin 5 before actually doing work besides from renaming namespaces for MAUI.

**Comment by qcjxberin** [comment]
It looks like it won't work this year

**Comment by lindexi** [comment]
It looks like it won't work this year

**Comment by dapks** [comment]
It looks like it won't work this year.
You can check it here: https://dapks.com/netboom-mod-apk-2/
