### ISSUE TITLE
[Bug] Scrollview is not scrolling vertically

### ISSUE THREAD

**Issue by RanjithkumarSyncfusion** [dotnet/maui#2768]
### Description
Can't able to scroll vertically even when ScrollView.Orientation is **Both** and the content height is greater than the scrollview height.

### Steps to Reproduce
1. Set scrollview orientation as Both.
2. Have a Content with size greater than scrollview Size.

### Expected Behavior
Scrollview should be scrollable vertically as well as Horizontally.

### Actual Behavior
Scrollview is scrolling horizontally only.

### Basic Information
- Version with issue: Preview 8
- Platform Target Frameworks: 
  - Android: API 29

### Reproduction Link
[ScrollingIssue.zip](https://github.com/dotnet/maui/files/7256558/ScrollingIssue.zip)

**Comment by FarjanaParveen** [comment]
Hi @hartez / @Eilon ,

Any update on this

**Comment by Eilon** [comment]
@FarjanaParveen sorry I don't have an update at this time, but maybe another team member can comment on this issue.

**Comment by hartez** [comment]
It's on our list to fix, but I can't say for certain when we will be fixing it.

**Comment by FarjanaParveen** [comment]
Hi @hartez,
Any update on this

**Comment by FarjanaParveen** [comment]
Hi @hartez/ @Eilon ,

I have analyzed maui source code for scrollview issue, found the root cause of this issue. ViewPort size is layout in horizontal scrollview instead of total size. Need to remove the OnLayout method in MauiScrollView

![image](https://user-images.githubusercontent.com/56529945/154413538-db98212e-d1c9-47d2-86d5-34208e48709a.png)

**Comment by FarjanaParveen** [comment]
Hi @hartez/ @Eilon ,

Any update on this?
