### ISSUE TITLE
Android SDK Manager and Device Manager are Not Opening in VS 2022 RC1

### ISSUE THREAD

**Issue by MRakesh** [dotnet/maui#2816]
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

<!-- Did you find any workaround for this issue? This can unblock other people while waiting for this issue to be resolved 

Images uploaded

![Android_SDK_Manager_Error](https://user-images.githubusercontent.com/9251825/135714764-0c23c4b2-3808-4a14-b476-402cfd5f0ead.PNG)

**Comment by pierrebrito** [comment]
I have the same problem.

**Comment by Eilon** [comment]
Thanks for the issue report! Could you use the [VS feedback tool](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) to report the issue? That way it will get to the routed to the right that owns this experience in VS.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks.
