### ISSUE TITLE
[Bug] 6.0.100-rc.1.1528 is not found in NuGet feeds

### ISSUE THREAD

**Issue by mmisztal1980** [dotnet/maui#2840]
### Description
Given I'm trying to install the workloads with the dotnet cli I'm getting an error message stating that the requested workloads are not available in the nuget feed:

```
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.workload.emscripten.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Downloading Microsoft.Maui.Core.Ref.android.Msi.x64 (6.0.100-rc.1.1528)
Downloading Microsoft.Maui.Core.Ref.android.Msi.x64 (6.0.100-rc.1.1528)
Workload installation failed. Rolling back installed packs...
Downloading microsoft.net.sdk.ios.manifest-6.0.100.msi.x64 (15.0.100-rc.1.1531)
Installation rollback failed: One or more errors occurred. (microsoft.net.sdk.ios.manifest-6.0.100.msi.x64::15.0.100-rc.1.1531 is not found in NuGet feeds https://api.nuget.org/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\".)
Workload installation failed: One or more errors occurred. (microsoft.maui.core.ref.android.msi.x64::6.0.100-rc.1.1528 is not found in NuGet feeds https://api.nuget.org/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\".)
```
or...
```
Workload installation failed: One or more errors occurred. (microsoft.maui.core.ref.ios.msi.x64::6.0.100-rc.1.1528 is not found in NuGet feeds https://api.nuget.org/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\".)
```

### Steps to Reproduce (Windows10)

1.  install .net 6 rc-1 sdk
2.  install vs2022 preview with maui enabled
3.  execute `dotnet install workload maui`  from the cmdline

### Expected Behavior

CLI should resolve the latest available packages from nuget (1.1608 instead of 1.1528)
https://www.nuget.org/packages/Microsoft.Maui.Core.Ref.android.Msi.x64/6.0.100-rc.1.1608

### Actual Behavior
Highlighted error messages are returned

### Workaround

None so far

**Comment by jfversluis** [comment]
I think you will need to add the feed as indicated [here](https://github.com/dotnet/maui/wiki/Installing-.NET-6#building-apps) until .NET 6 is officially released. Let me know if that helps

**Comment by drasticactions** [comment]
You don't need to use those nuget feeds in order to get MAUI, those are intended if you want newer or daily builds. If you do want to use those feeds, you can install a [daily .NET build](https://github.com/dotnet/installer#installers-and-binaries) which has the signing verification turned off by default.

You should be able to fix your issue by removing an `installertype` `msi` flag. This feature flag enables workloads to be installed via MSIs but those are missing from the feed. If you remove the flag, it will get the straight NuGet packages and those should be there.

- Go to `C:\Program Files\dotnet\metadata\workloads\6.0.100\installertype`
- You'll see a blank file with `msi`, remove it.
- Now rerun the dotnet workload command.

It should work now.

**Comment by rmarinho** [comment]
Hi @mmisztal1980  is this still a issue ?
