### ISSUE TITLE
[Bug] Method not found: 'Void Microsoft.Web.WebView2.Wpf.WebView2.add_AcceleratorKeyPressed

### ISSUE THREAD

**Issue by albertwoo** [dotnet/maui#2885]
### Description

I want to use blazor + wpf and set its DefaultBackgroundColor to Transparent. But DefaultBackgroundColor is enabled after Microsoft.Web.WebView2 1.0.790-prerelease.

So I tried to install Microsoft.Web.WebView2 1.0.992.28 which is the latest version. But I got below error:

MissingMethodException: Method not found: 'Void Microsoft.Web.WebView2.Wpf.WebView2.add_AcceleratorKeyPressed(System.EventHandler`1<Microsoft.Web.WebView2.Core.CoreWebView2AcceleratorKeyPressedEventArgs>)'.

### Expect

Upgrade dependency package (Microsoft.Web.WebView2) of Microsoft.AspNetCore.Components.WebView.Wpf and fix the error.

### Basic Information
Microsoft.AspNetCore.Components.WebView.Wpf: 6.0.100-rc.1.1608

**Comment by Eilon** [comment]
As of right now, the latest dev bits use WebView2 1.0.961.33:

https://github.com/dotnet/maui/blob/main/eng/Microsoft.Extensions.targets#L16

But 11 days ago a newer version 1.0.992.28 was released: https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.992.28

I'll get this updated. Thank you for the report!

**Comment by albertwoo** [comment]
Can we also expose DefaultBackgroundColor to BlazorWebView so we can set its value directly in xaml?

**Comment by Eilon** [comment]
This particular issue should already have been fixed due to another WebView2 update that was already done. But we'll update WebView2 to 1.0.1020.30 anyway.

As far as setting BackgroundColor in XAML, please log a new issue for that as well as any other properties you think ought to be "first class". We do provide access to the inner WebView2 via the `BlazorWebView.WebView` property, but you have to wait until it's actually created (it isn't necessarily "immediate" because several conditions must be true for it to be created).
