### ISSUE TITLE
[Bug] Need recipe file 

### ISSUE THREAD

**Issue by samminnella** [dotnet/maui#2942]
Getting the "need recipe file" error when trying to  run an Android build.

It seems to be some sort of syncing issue because if a switch from windows to android i get the error.

If i switch from window to iphone and then to android then builds and runs as expected.

This is using the razor template Maui Preview 9 (RC2)

**Comment by sharpninja** [comment]
I get this trying to deploy a Maui Blazor app to Windows 11.

**Comment by hartez** [comment]
See also: #3242

**Comment by devmikew** [comment]
I'm getting this today on running Essentials.Sample and on Windows machine.

**Comment by devmikew** [comment]
Also on trying to run  Maui.Controls.Sample.SingleProject on windows machine.

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
