### ISSUE TITLE
Review what events should fire when a view is removed from the visual tree

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#3163]
### Description

With https://github.com/dotnet/maui/pull/1692 we included the `HandlerChanged` method.
Actually fires after handler has created and set the native view, so, the NativeView is present and all of the VirtualView properties have been applied. 

When navigating back, and removing a view from the visual hierarchy disposing the native control, we must also invoke the method but with the Handler property set to null.

**Comment by mattleibow** [comment]
Are we expecting a back navigation to _not_ detach a handler?

We probably need those window events, but what is our plan with the cleanup of views/handlers once they are removed?

**Comment by PureWeen** [comment]
@mattleibow back navigation detaches the handler from the page but we don't currently propagate that through to every single control on the page.  That type of propagation was always a bit problematic on forms. Aggressively cleaning up and then recreating everything.

For example what if someone wants to reuse the page and not recreate all the native controls? Like if it has a native map or something? 

I think that removing the handlers from everything and an event indicating that the control is no longer part of the visual tree are two different things here. 

being removed from the visual tree doesn't mean we should remove all the handlers. For example, on Forms it's really annoying because you can't move a player from one layout to another. Forms auto disposes of the entire native tree.

**Comment by Redth** [comment]
Closed by #5027
