### ISSUE TITLE
[Net6][iOS] error MSB4044: The "ComputeBundleResourceOutputPaths" task was not given a value for the required parameter "BundleIdentifier".

### ISSUE THREAD

**Issue by arivoir** [dotnet/maui#3170]
Building a just created iOS Application doesn't work

> error MSB4044: The "ComputeBundleResourceOutputPaths" task was not given a value for the required parameter "BundleIdentifier".

To reproduce this issue you can "Create New Project"

![image](https://user-images.githubusercontent.com/17496741/139329672-f5e70ada-5472-4be9-9a40-32501d62ebf2.png)

Select "iOS Applicaton"

![image](https://user-images.githubusercontent.com/17496741/139329431-1a32d45d-0647-4772-92a4-bb1646e43274.png)

Connect to a mac

Build the project (F6). 

The error will appear in the "Error List" window.

Visual Studio 2022 Version 17.0.0 Preview 7.0

**Comment by Eilon** [comment]
Thanks for the issue report! Could you use the [VS feedback tool](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) to report the issue? That way it will get to the routed to the right that owns this experience in VS.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks.
