### ISSUE TITLE
[Bug] XAML Live preview don't work on Windows build

### ISSUE THREAD

**Issue by meilleur102** [dotnet/maui#3190]
Ive just download and install Vs2022 and Start a new maui project and when I launch the application with android, everything works perfectly fine on the Live preview. 
When I try to debug the application on windows machine, the live preview dont work. 
This is the message tha t I have 
![image](https://user-images.githubusercontent.com/42327867/139479136-04b6f5e1-0302-43f9-8e8c-3a85e9c8800a.png)

**Comment by JoschiGrey** [comment]
I experience the same issue with a freshly installed VS2022 Previous 7 and MAUI.

The Hot Reload Button is present, but pressing it does nothing and code changes aren't applied. Neither C# nor xaml changes. 

I sadly can't test if it works in the android emulator on my side, because that one misbehaves as well.

**Comment by davidortinau** [comment]
Fixed. I tested this in 6.0.101-preview.10.2068 (branch feed) and VS 17.1 Preview 1 (coming soon).
