### ISSUE TITLE
[Bug] Xamarin Page and View Templates break MAUI Apps

### ISSUE THREAD

**Issue by matt-goldman** [dotnet/maui#3200]
### Description
When adding a ContentView or ContentPage to a .NET MAUI app using Visual Studio, it uses the Xamarin templates. Once you do this, the .NET MAUI app will no longer build.

I'm not sure if this is a MAUI issue or a Visual Studio 2022 issue - however, the build fails at the .NET CLI too. 

### Steps to Reproduce

1.  Build a new .NET MAUI app
2.  Using Visual Studio, add a ContentView or ContentPage
3.  Try to build and run your .NET MAUI app

### Expected Behavior

The app builds and runs

### Actual Behavior

Multiple compiler warnings are thrown for `The name 'InitializeComponent' does not exist in the current context`

### Basic Information

- Version with issue:  .NET MAUI Preview 9
- Last known good version: NA
- IDE: Visual Studio 2022 17.0.0.0 Preview 7
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: None
- Affected Devices: All

### Workaround

With limited success, removing the views or pages added with the Xamarin templates, deleting the bin and obj folders (specifically obj) and cleaning/rebuilding the solution, you can run your app. This workaround does not work consistently though - probably because I have been unable to extricate all the of the Xamarin references.

**Comment by Xami3Shah** [comment]
whenever i create page with vs2022 then i have to remove the first line which contains "<?xml version="1.0" encoding="utf-8" ?>" 
and also the code for this page from csproj file. then it works fine.

**Comment by Eilon** [comment]
Eep! I think if the Xamarin.Forms item templates for ContentView and ContentPage show up then we need to make sure those get hidden from .NET MAUI apps. .NET MAUI does have its own ContentView and ContentPage item templates. For some reason in VS I see only the Xamarin.Forms versions but in the command line (`dotnet new ...`) I see the .NET MAUI ones.

**Comment by marwalsch** [comment]
@Eilon I was running in the same issue and was able to workaround by changing the template files' properties to  the following:
`.xaml`
Build Action:                        MauiXaml
Copy to Output Directory:  
`.xaml.cs`
Build Action:                        C# compiler
Copy to Output Directory:  Do not copy

However, the issue resurfaced and won't go away any-more. Is there anything I am missing? I was used to Intellisense going braindead with xaml from time to time but now VS won't even build anymore, which is why I presume it's a MAUI issue.

**Comment by jmmortega** [comment]
Same error here. I can replicate with any MAUI project, even [Microsoft Podcast sample project]. https://github.com/microsoft/dotnet-podcasts/tree/main/src/Mobile/Platforms

Working in Mac. Using the last preview version of .NET 6.0.2, last update of MAUI checked with maui check tool. 

I'm here for any help or information that I can share.

**Comment by Amir-Care** [comment]
Repro on VS 17.2.0 Preview 2.0 [32208.484.main]
Sample project: [MauiApp9 (1).zip](https://github.com/dotnet/maui/files/8158492/MauiApp9.1.zip)

**Comment by jfversluis** [comment]
In most recent versions we have a dedicated space for .NET MAUI templates. I think this should clear up the confusion. Unfortunately, the Xamarin.Forms templates do show up and that has been a separate issue since even before .NET MAUI was a thing. I think we will only get rid of that when Xamarin.Forms goes out of support.

![image](https://user-images.githubusercontent.com/939291/174030749-75a58837-08a3-4753-96cc-016410a1e574.png)

Let us know if there is still anything that impacts you in this area. Thanks!
