### ISSUE TITLE
[Enhancement] Image Animation

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#3207]
Hi,

Please add animation to the Image when loading, e.g. Fade, Zoom, etc..

Thanks,
Jassim

**Comment by jfversluis** [comment]
Hi Jassim, seems like a great idea! I would love for you to use the feature request template that we have in place so we can have a better understanding of how you would like to use this feature.

With just 1 line, as you might know from requirements in your own work, it's very open to interpretation and I would like for us to get it right instead of building something that you didn't ask for. Please open a new feature request with all the requested info.

Thanks!

**Comment by jrahma** [comment]
> Hi Jassim, seems like a great idea! I would love for you to use the feature request template that we have in place so we can have a better understanding of how you would like to use this feature.
> 
> With just 1 line, as you might know from requirements in your own work, it's very open to interpretation and I would like for us to get it right instead of building something that you didn't ask for. Please open a new feature request with all the requested info.
> 
> Thanks!

I would start with implementing a simple Fade and Zoom for the control which will give it a better look in any app.
