### ISSUE TITLE
Xaml Designer without debugging

### ISSUE THREAD

**Issue by meilleur102** [dotnet/maui#3218]
I can't figure it out why I can't see my Xaml design result whithout debugging the application. 
For example I clone the repo of the weather app to check one specific view how he did the visual and I can't see it whithout starting the app and going one by one with each view to see wish one it is...

Is there a way to still have the Xaml designer or the preview always on?

**Comment by jfversluis** [comment]
There is not, you should see it as a mirror of your emulator screen so you don't have to keep the windows side-by-side. There is an ongoing investment into making the experience better so that you can select elements in the preview and be brought to the XAML or vice versa, highlighting elements, etc. but I don't think there is any plans to bring (back) a full designer for now.
