### ISSUE TITLE
ContentProperty attribute ignored if base type is a Collection

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#3251]
Specifying the `ContentProperty` attribute for a type that implements `IEnumerable<T>` and an `Add(T)` method currently does nothing - the `ContentProperty` is ignored when processing the XAML. 

For instance, `HorizontalStackLayout` implements `IList<IView>`. If we define the following subclass:

```
[ContentProperty(nameof(Stuff))]
public class CustomControl : HorizontalStackLayout
{
	private readonly ObservableCollection<Thing> _stuff;

	public IList<Thing> Stuff
	{
		get
		{
			return _stuff;
		}
	}
}
```

and this XAML:

```
<CustomControl>
	<Button Text="Hello">
</CustomControl>
```

The Button will be directly added to the control as part of `IList<IView>`; the Stuff collection will be ignored.

This happens because `ApplyPropertiesVisitor()` checks for the collection type first, and only looks at the `ContentProperty` attribute if the collection type check fails. 

I've submitted a PR to partially address this - the question is whether it makes sense for ContentProperty to take precedence, and whether that would cause problems elsewhere. Tagging @StephaneDelcroix for comment.

**Comment by hartez** [comment]
PR #3252 partially addresses this, assuming it makes sense to address this. It swaps the order of the checks so that ContentProperty is considered first. 

3252 does _not_ address compiled XAML - that will require a bit more work.

**Comment by StephaneDelcroix** [comment]
Thanks for investigating this @hartez 

It doesn't make a lot of sense to have both a ContentProperty AND a IEnumerable, as whatever the priority is, one of the feature would be unaccessible from XAML.

Now, as in this case, we have both, what is a sensible priority ?

With the current priority (IEnumerable over Content), the behaviour of the inherited control is coherent with the C# collection construction:

```csharp
new CustomControl {
    new Button(),
    new Button()
};
```

behaves like 

```xaml
<CustomControl>
    <Button />
    <Button />
</CustomControl>
```

but if we swap the priorities, it won't be the case anymore...

In this case, I would recommend overriding Add() instead of trying to change the Content property, so the Xaml behaviour is in line with the c#.

If you choose to change it nevertheless, PR #3252 only covers the non-XamlC scenario, and is incomplete.
