### ISSUE TITLE
[Enhancement] FindByName inside BindableLayout.ItemTemplate

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#3257]
Hi,

Please allow the **FindByName** inside the **BindableLayout.ItemTemplate** without having to use a ViewModel to make it easier to access (read/write) the value of any control inside the BindableLayout.ItemTemplate's **DataTemplate**.

Thanks,
Jassim

**Comment by jfversluis** [comment]
I feel this kind of goes against the nature of what we're doing with templates. A template is something that is applied to a certain item from the collection. Hence it's kind of impossible to give something a name and find something by that name.

If we then factor in the virtualization that you might have, an item might not even exist at that time to save memory. This is not something that we can or want to do in my opinion.

Whenever you do feel otherwise I would love to learn more about why and how you would want to do this. Please use the proper feature request template to do so.
