### ISSUE TITLE
Unable to use razor files without adding partial class

### ISSUE THREAD

**Issue by kganil** [dotnet/maui#3301]
I created a WPF project with BlazorWebView and added some razor files into it. But the classes generated by the razor files are not visible for the build without adding a corresponding partial class. Another interesting problem is that the partial class is not extending the generated razor class (e.g. cannot override any of the razor component base class methods). A work around for this is to put all the razor files in an external razor class library. But It would be nice if we can add the razor files in WPF project without adding additional dummy partial classes.

**Comment by ByronAP** [comment]
Curious as to what your WPF project has to do with MAUI? Can you describe the connection or where you are using MAUI?

**Comment by kganil** [comment]
There is no connection to MAUI. I am using BlazorWebView to host blazor components in a WPF application (.net 6). I presume the issues related to BlazorWebView for WPF is tracked in this repository under area/blazor label

**Comment by Eilon** [comment]
Hi @kganil , this issue is tracked here: https://github.com/dotnet/wpf/issues/4421

Fortunately, there's an even easier workaround than using a Razor Class Library. You can keep the `*.razor` files in the main WPF project, but in one of the `.cs` files you can declare `public partial class MyRazorClass {}` (with no code in it!) and that will "trick" WPF into seeing the type. This works because the Razor compiler declares all the types as `partial` (meaning the type definition can be in more than one file), so the WPF XAML processor sees your manually declared empty partial class, and at runtime the real Razor-generated type is seen and used. Also, typically only 1 (or very, very few) types will need this treatment because the WPF XAML file generally only has one BlazorWebView that references one root component (though you certainly _can_ have as many as you want).

Hopefully a real fix is done in the WPF XAML processor, but in the meantime you can use the easy workaround.

**Comment by kganil** [comment]
In my case, I use many razor files organized in different folders/namespaces. My source code also uses keywords like nameof(MyRazorClass) in .cs code. All those razor components are now require a partial class.  The problem is not happening for MAUI Blazor Project

Is there corresponding issue reported in the WPF XAML side so that it can be tracked ?

**Comment by davidbuckleyni** [comment]
Why is this in maui wpf is not supported in maui

**Comment by Eilon** [comment]
This repo is where all the Blazor Hybrid BlazorWebView controls are located: .NET MAUI, WPF, and WinForms. The scenario in this bug report is really only a problem with BlazorWebView, so I think it's reasonable to be in this repo. (Yes, it's weird to have the WPF BlazorWebView in this repo, but it has nowhere else to live, and apartment rent is expensive in this city, so it stays on a sofa at MAUI's home 😁)
