### ISSUE TITLE
[Bug] No Android Splash screen on API 31

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#3306]
### Description

![Screenshot_1636413431](https://user-images.githubusercontent.com/41873/140833627-2609a1ad-c63d-45bf-b6fa-1e3753626f8d.png)

```
<MauiSplashScreen Include="Resources\appiconfg.svg" 
					  Color="#081B25" />
```

[WeatherTwentyOne.zip](https://github.com/dotnet/maui/files/7500697/WeatherTwentyOne.zip)

### Steps to Reproduce

1. Run on API 31

### Basic Information

- Version with issue: pre10

**Comment by davidortinau** [comment]
API 28:
![Screenshot_1636413656](https://user-images.githubusercontent.com/41873/140833749-4fc3f63b-f455-4456-88f1-930f6ae9f209.png)

**Comment by balloman** [comment]
Are there any updates on this? I see that API 31 changed how splash screens work, maybe this would be of some help? https://developer.android.com/guide/topics/ui/splash-screen/migrate

**Comment by kristinx0211** [comment]
repro on Android 11. repro sample:
[#3306.zip](https://github.com/dotnet/maui/files/8183334/3306.zip)

**Comment by MagicAndre1981** [comment]
The official AndroidX package is out now @balloman  :

https://www.nuget.org/packages/Xamarin.AndroidX.Core.SplashScreen

**Comment by rachelkang** [comment]
Hi folks! I've been investigating this issue the past couple weeks and learned a couple things.

The splash screen _does_ technically work on API 31+. The issue is that the splash screen _icon_ does not render when the app is launched for the first time (i.e. from the IDE, from a launcher, etc). It _does_ render properly when the app is terminated and restarted by clicking on the app icon. I've experimented with the new SplashScreen API that was introduced in API 31, and while there are changes, this issue at hand remains the same.

Moreover, this is consistent with the current behavior on the Android platform, and Android is aware of this issue. They're saying [this behavior is intended](https://issuetracker.google.com/issues/199776339#comment3), so it is unclear whether it will be changed. However, their new SplashScreen API is in beta, and there is some hope that they might [change this in a future stable release (1.1)](https://issuetracker.google.com/issues/216136037#comment4).

For the curious, here are some links to issues I've tracked down in the Android world:
- https://issuetracker.google.com/issues/199776339
- https://issuetracker.google.com/issues/205021357
- https://issuetracker.google.com/issues/206630113
- https://issuetracker.google.com/issues/207386164
- https://issuetracker.google.com/issues/216136037

We'll keep an eye out for any updates and revisit when they release a stable version of the SplashScreen API. In the meantime, if anyone has additional findings or discovers a workaround, you're always welcome to share!

**Comment by emorell96** [comment]
> Hi folks! I've been investigating this issue the past couple weeks and learned a couple things.
> 
> The splash screen _does_ technically work on API 31+. The issue is that the splash screen _icon_ does not render when the app is launched for the first time (i.e. from the IDE, from a launcher, etc). It _does_ render properly when the app is terminated and restarted by clicking on the app icon. I've experimented with the new SplashScreen API that was introduced in API 31, and while there are changes, this issue at hand remains the same.
> 
> Moreover, this is consistent with the current behavior on the Android platform, and Android is aware of this issue. They're saying [this behavior is intended](https://issuetracker.google.com/issues/199776339#comment3), so it is unclear whether it will be changed. However, their new SplashScreen API is in beta, and there is some hope that they might [change this in a future stable release (1.1)](https://issuetracker.google.com/issues/216136037#comment4).
> 
> For the curious, here are some links to issues I've tracked down in the Android world:
> 
> * https://issuetracker.google.com/issues/199776339
> * https://issuetracker.google.com/issues/205021357
> * https://issuetracker.google.com/issues/206630113
> * https://issuetracker.google.com/issues/207386164
> * https://issuetracker.google.com/issues/216136037
> 
> We'll keep an eye out for any updates and revisit when they release a stable version of the SplashScreen API. In the meantime, if anyone has additional findings or discovers a workaround, you're always welcome to share!

But it doesn't work well after you launch it again. It shows the wrong splashscreen at least in preview 14 (it needs to be tested in RC1).

The splashscreen set using `<MauiSplashScreen>` is not the one displayed but the icon set for the app using `MauiIcon`.
![image](https://user-images.githubusercontent.com/20151415/163916139-ac3a8090-c6f8-49b5-a98a-575ecdd94650.png)

**Comment by rachelkang** [comment]
@emorell96 If you're still experiencing that issue, please open a new issue with an attachment of your project or a sample project reproducing the issue so that we can investigate further! Thanks.
