### ISSUE TITLE
MAUI Blazor Template exception on runtime.

### ISSUE THREAD

**Issue by HeroinGyrl** [dotnet/maui#3344]
I created a MAUI Blazor template with the latest .NET 6 and Visual Studio 2022.

First of all the Template has a issue. in the `App.cs` a using statement is missing.
```cs
using Microsoft.Maui.Hosting;
```

the next issue is that whenever I run the template I get a exception:
```cs
Exception thrown: 'System.DllNotFoundException' in Microsoft.WindowsAppRuntime.Bootstrap.Net.dll
```

**Comment by bravecobra** [comment]
I'm having exactly the same issue

**Comment by jcmontoya** [comment]
same issue here

**Comment by cydolo** [comment]
workaround from this issue. https://github.com/dotnet/maui/issues/3312

`dotnet new --install Microsoft.Maui.Templates::6.0.101-preview.10.2068`

**Comment by bravecobra** [comment]
That didn't fix it for me. I had to run a "repair" on my VS2022 installation in the VS Installer. Apparently there is an upgrade issue some from previous versions.

**Comment by Eilon** [comment]
This does not appear to be Blazor specific, so removing that tag.

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
