### ISSUE TITLE
Unable to find IAnimationManager for 'Microsoft.Maui.Controls 

### ISSUE THREAD

**Issue by jeya-kasipandi** [dotnet/maui#3353]
### Steps to Reproduce

1. Add animation in view 
2. Call the animation method in  main view (animation view added in main view)touch event 
2. Add main view in xaml
3. Crash Occur like below
Unable to find IAnimationManager for 'Microsoft.Maui.Controls 

### Expected Behavior

Animation will work

### Actual Behavior

Crash Occur

**Comment by jeya-kasipandi** [comment]
Any update?

**Comment by jsuarezruiz** [comment]
Could you share information about the versions used?, or attach a small sample where reproduce it?. Thanks in advance.

**Comment by jeya-kasipandi** [comment]
Version Preview 9 
One more thing ,View Width and height set to -1, the crash issue occur.
When adding Xaml, the animation view width and height is set to -1;

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue with the latest Preview, could you attach a small sample where reproduce the issue?
https://user-images.githubusercontent.com/6755973/140737484-1ed4461a-20ac-4047-8fac-90022e966ff9.gif

**Comment by jeya-kasipandi** [comment]
[AnimationTesting.zip](https://github.com/dotnet/maui/files/7528431/AnimationTesting.zip)

**Comment by jeya-kasipandi** [comment]
Any update?

**Comment by jeya-kasipandi** [comment]
Any solution?

**Comment by markgr** [comment]
Any update?

**Comment by enisn** [comment]
Also happens while trying to animate **Label**

```
System.ArgumentException: Unable to find IAnimationManager for 'Microsoft.Maui.Controls.Label'. (Parameter 'animatable')
```

**Comment by jsuarezruiz** [comment]
Tried with main branch and cannot reproduce the issue. Could someone attach a small sample using latest Preview?, still can reproduce it?

**Comment by VincentBu** [comment]
I'm using 17.2.0 preview 2.1 but I can't repro this issue. @enisn  I write a sample which can animate Label with TranslateTo() method. Would you like to verify it?
[MauiApp3353.zip](https://github.com/dotnet/maui/files/8349063/MauiApp3353.zip)

**Comment by enisn** [comment]
> I'm using 17.2.0 preview 2.1 but I can't repro this issue. @enisn I write a sample which can animate Label with TranslateTo() method. Would you like to verify it? [MauiApp3353.zip](https://github.com/dotnet/maui/files/8349063/MauiApp3353.zip)

Yeah works well in [MauiApp3353.zip](https://github.com/dotnet/maui/files/8349063/MauiApp3353.zip) project.

But I am struggling to use it in another complex project and I realized it's all about **timing**, 
It's called at the first time while initializing. If I wait until page is appeared, then `TranslateTo()` method works well.

Here is my code:
https://github.com/enisn/Xamarin.Forms.InputKit/blob/develop/src/InputKit.Maui/Shared/Controls/AdvancedSlider.cs#L212-L216



I think it's not a real bug **BUT** it was working in Xamarin.Forms before _(https://github.com/enisn/Xamarin.Forms.InputKit/blob/develop/src/Xamarin.Forms.InputKit/Shared/Controls/AdvancedSlider.cs#L207)_

**Comment by vniehues** [comment]
I See the exact same behavior that @enisn is describing. 
In my case I trigger an animation (TranslateTo) in the ctor of my ViewModel (vastly simplified) and that will crash the application. 
If I wait for the page to load, everything works as expected.

**Comment by jamboort** [comment]
Will the #6364 fix be available in RC2? 

I am having this exact issue with community VS 2022 version 17.2.0 preview 4 animations work OK on the mainPage but not on a second content page.

This is the message I get.
System.ArgumentException: 'Unable to find IAnimationManager for 'Microsoft.Maui.Controls.Entry'. (Parameter 'animatable')'

**Comment by enisn** [comment]
According to @mattleibow review (https://github.com/dotnet/maui/pull/6364#pullrequestreview-950236327)
It seems there should be a better way to fix this issue instead of re-creating AnimationManager when it doesn't exist.

**Comment by marcusts** [comment]
This bug is back in VS 2022 17.3.0 (Preview 1.0).

Any call to Animation.Commit fails with **_"Unable to find IAnimationManager for xxx"_**

` joinedAnimation.Commit( _masterGrid, "fadeInOutAnimation", length: VIEW_FADE_IN_OUT_TIME );

This works fine in Xamarin.Forms _(identical code)_.



_I don't see your fix from 20 days ago -- is it merged and available for public use?  Here is my system info:_
----------------------------------------------------------------------------------------------------------------------------------------
Microsoft Visual Studio Professional 2022
Version 17.3.0 Preview 1.0
VisualStudio.17.Preview/17.3.0-pre.1.0+32505.426
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

ASP.NET and Web Tools 2019   17.3.122.33185
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.3.122.33185
Azure App Service Tools v3.0.0

C# Tools   4.3.0-1.22254.1+9919d7e7bd753404a5d2328e5e3fb2de635169f3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.3.7 (c1ffb2a)
Support for debugging Mono processes with Visual Studio.

Multiline Search and Replace   3.3
Adds multiline search and replace functionality to Visual Studio.

NuGet Package Manager   6.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2222701+751db1ebea5e6a9ecc7fa57fe447180422afa610
Provides languages services for ASP.NET Core Razor.

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript Tools   17.0.10420.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.3.0-1.22254.1+9919d7e7bd753404a5d2328e5e3fb2de635169f3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22178.3+6da0245a7ce4bb8483b8d1f2993c8ecaea967ad9
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.3.0.91 (main@7802af5)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.3.0.30 (remotes/origin/main@fb6442dc1)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.2.15 (2e3b60e)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.3.99.58 (main/64b22fc)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: adf1bc4
    Java.Interop: xamarin/java.interop/release/6.0.3xx@2a882d2d
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.38.2@7b1e016
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@fc3c2ac


Xamarin.iOS and Xamarin.Mac SDK   15.11.0.87 (406f3098e)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jamboort** [comment]
I fixed my issue by not calling the animations until after the controls have all initialized and rendered.
