### ISSUE TITLE
MAUI Project Template Has Build Errors

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3417]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-Project-Template-Has-Build-Errors/1577394)._

---
After installing the following workloads that I saw during the . NetConf today and creating a new project using the MAUI Preview Template with Blazor I get a bunch of build errors.. This is with VS 2022 Preview 1.0 on WIndows 10.. Are there prerequisites before I can install VS 2022 Preview 1.0?

! [image.png] (https://aka.ms/dc/image?name=Bc6189703c4d54b1abb13584e1d79f481637721032248180500_20211109-200704-image.png&tid=c6189703c4d54b1abb13584e1d79f481637721032248180500)
! [image.png] (https://aka.ms/dc/image?name=Bec0d134d3886482aac18e6cec68bb3e2637721032907256009_20211109-200809-image.png&tid=ec0d134d3886482aac18e6cec68bb3e2637721032907256009)

---
#### Feedback Bot on 11/10/2021, 00:11 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
