### ISSUE TITLE
Maui manifest is not signed at maui check at net 6.0.100 rc3

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#3423]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui-maniftest-wird-nicht-siginiert-bei-/1571436)._

---
[severity:I'm unable to use this version] [regression] [worked-in:newest releas candidate of VS22]
i have runned nte newest maui-check, and the maui manifest is not signed. Because this all my Projects are incompatible

---
#### Markus Lein on 11/3/2021, 08:37 PM: 

(private comment, text removed)
#### Feedback Bot on 11/3/2021, 10:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
