### ISSUE TITLE
MauiRazorClassLibrary sometimes doesn't build when building the SLN, causing StaticWebAssets to fail

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#3434]
This PR https://github.com/dotnet/maui/pull/3430 failed with some StaticWebAssets issues:

```
"D:\agent\1\s\src\BlazorWebView\samples\MauiRazorClassLibrarySample\MauiRazorClassLibrarySample.csproj" (GetCurrentProjectBuildStaticWebAssetItems target) (18:9) ->
(GetCurrentProjectBuildStaticWebAssetItems target) -> 
  D:\agent\1\s\bin\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(799,7): error : Manifest file at 'obj\Release\net6.0\staticwebassets.build.json' not found. [D:\agent\1\s\src\BlazorWebView\samples\MauiRazorClassLibrarySample\MauiRazorClassLibrarySample.csproj]


"D:\agent\1\s\Microsoft.Maui-net6.sln" (Build target) (1:2) ->
"D:\agent\1\s\src\Controls\samples\Controls.Sample.SingleProject\Maui.Controls.Sample.SingleProject.csproj" (default target) (2:22) ->
"D:\agent\1\s\src\Controls\samples\Controls.Sample.SingleProject\Maui.Controls.Sample.SingleProject.csproj" (Build target) (2:23) ->
"D:\agent\1\s\src\Controls\samples\Controls.Sample\Maui.Controls.Sample-net6.csproj" (GetMauiItems target) (7:27) ->
"D:\agent\1\s\src\BlazorWebView\samples\MauiRazorClassLibrarySample\MauiRazorClassLibrarySample.csproj" (ComputeReferencedStaticWebAssetsPublishManifest;GetCurrentProjectPublishStaticWebAssetItems target) (18:10) ->
(LoadStaticWebAssetsBuildManifest target) -> 
  D:\agent\1\s\bin\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(522,5): error : Manifest file at 'obj\Release\net6.0\staticwebassets.build.json' not found. [D:\agent\1\s\src\BlazorWebView\samples\MauiRazorClassLibrarySample\MauiRazorClassLibrarySample.csproj]

    55 Warning(s)
    2 Error(s)
```

It seems to be some sort of ordering issue where `MauiRazorClassLibrarySample` is not getting built early enough, so StaticWebAssets can't find its build output.

**Comment by mattleibow** [comment]
Should this be filed against MSBuild instead? Why would the order of the projects in a solution override the build order of the project dependencies? The order in the sln should not matter, since msbuild evaluates the project dependencies and creates its own order.

Unless sln files are more important than just a list of project and I have been living a lie?

**Comment by Eilon** [comment]
I think it depends on where the bug really is. It's true that the order in the SLN shouldn't matter, but the question is what's causing this issue. Are we doing something weird in our own CSPROJ files in this repo? Or does StaticWebAssets have an issue where it should be forcing a build, but doesn't? I think until we have more details, it's hard to say.

**Comment by mattleibow** [comment]
Makes sense.

However, regardless of our bad code or not, the order in the sln should not matter and either msbuild should always work or it should always fail.

**Comment by Eilon** [comment]
The other in the SLN shouldn't matter, if there are no other bugs in the build, which I don't think we can exclude as a possibility just yet. For example, if there's a bug in StaticWebAssets where it doesn't force an inner build correctly, it might sometimes pass (if something else forced an inner build), or fail (if the order of the build is such that nothing had a chance to force an inner build).

**Comment by mattleibow** [comment]
From @javiercn : https://github.com/dotnet/maui/pull/3430#issuecomment-971815491

I think something has changed in the build that is causing ResizetizeCollectItems to run super early in the build pipeline before dependent projects have been built, and that's why we are seeing this issue. If I'm not wrong, ResizetizeCollectItems is running before the dependencies have been built, and that is causing the failure.

![image](https://user-images.githubusercontent.com/6995051/142254110-859e33eb-b804-45d4-9156-30c5477875c4.png)

![image](https://user-images.githubusercontent.com/6995051/142254504-6dbdf7e5-3b1f-4dc8-887e-9dce2404d708.png)

It's not clear to me what the right solution for this is, I would expect that ResizetizeCollectItems only runs after all dependent projects have been built.

**Comment by mattleibow** [comment]
This might be the issue because `ResizetizeCollectItems` could run at any time and does not require a build to have taken place. All it does it evaluates the items in the project and return it to the main project.

For example, it locates all the `MauiImage` from one project and then adds it to the main project for later.\

Maybe the order in the sln was by coincidence that it always built the base project first so it was hidden. But resizetizer can run at any time as it is not part of the main build. All it needs is the nugets restored and then to influence it you can use either a depends on some target or before the collect task
