### ISSUE TITLE
[Enhancement] Being able to develop .NET MAUI apps from Linux

### ISSUE THREAD

**Issue by pablojimpas** [dotnet/maui#359]
## Summary
Since MAUI supports using the dotnet cli and VS Code, the use of full-fat Visual Studio isn't a requirement anymore. So...what are the blocking points to being able to develop MAUI apps from a Linux machine right now? What work needs to be done to port the mobile workloads?
It will be great to have this feature in order to truly embrace not only cross-platform apps but also cross-platform development 😎

## API Changes
None

## Intended Use Case
As a .NET 6 user I want to be able to develop any kind of app (mobile, web, desktop, IoT, games...) from the platform of my choice (Windows, macOS, Linux).

Implementing this feature would make possible developing MAUI apps using just the dotnet cli and any chosen editor (e.g VS Code) from a Linux system.

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/discussions/339

**Comment by pablojimpas** [comment]
@PureWeen sorry, I checked for duplicated issues but forgot about the discussions tab..

**Comment by saint4eva** [comment]
> #339

I believe this issue is for developing on Linux, and not developing for Linux?

**Comment by pablojimpas** [comment]
> 
> 
> > #339
> 
> I believe this issue is for developing on Linux, and not developing for Linux?

Exactly, this issue should be open unless there is a reason to discard this feature request... @PureWeen

**Comment by AraHaan** [comment]
Tbh if one can ``develop`` on linux, they would then expect to be able to RUN on linux too.


But then again I would like to be able to run gui programs on linux too, and not be limited to mobile, windows, or even a mac for gui development.

I guess only way to have xplat gui is to only use System.Drawing.Common and to use that to manually make every component that is inside of every OS so that way we achive xplat gui 😭.

**Comment by redradist** [comment]
I also expect being able to develop on Linux for Android and iOS Application since it requires only `dotnet cli`, there are no more excuse to not support development on Linux except if company want to tie developers to Windows platform ... but if it is try, why than Microsoft support MacOS development for Android and iOS Apps ??

I really wait being able to develop Android App on Linux based systems like it possible in all other frameworks: Flutter, NativeScript, ReactNative

**Comment by pablojimpas** [comment]
> @pablojimpas That issue [#339](https://github.com/dotnet/maui/discussions/339) is mostly for being able to develop for Linux distribution, seems like you should reopen this issue

I know but I can't reopen this issue, that should be done by @PureWeen or other member of the team.

**Comment by inkysquid** [comment]
Building on Linux important to support the default dotnet SDK docker image and many CI/CD tools (e.g. GitLab, BitBucket).
