### ISSUE TITLE
Bring DefaultRenderer concept to .NET MAUI

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#3594]
### Description

in XF if no renderer could be found for a given control then it would just get assigned `DefaultRenderer` which was capable of handling Gestures/backgrounds/etc..

Currently in .NET MAUI you'll just get an exception about no Handler found 

### Steps to Reproduce

- Create a control inheriting from VisualElement
- Use the control in your app

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All of them

### Did you find any workaround?

Register the handler yourself

**Comment by dotMorten** [comment]
This would be hugely valuable for 3rd party control vendors: If the experience is "add control, run, show nothing, go to stack overflow/forums and ask why nothing is rendering" it'll be a bit of a support nightmare having to teach everyone what to do every time they bring in a 3rd party control and need to know they need to call a specific non-standard configure API to bring them in. Those controls should have a default handler, and you'd only need to configure handlers if you want to override/control the rendering with custom handlers. IMHO things should "just work" out of the box.

**Comment by charlesroddie** [comment]
This hides bugs surely.

**Comment by AmrAlSayed0** [comment]
@charlesroddie Not really, a control that inherits from `VisualElement` but has no handler defined is expected to behave like a normal `VisualElement`. There is no reason to make those throw an exception. Also it should apply to other controls as well. A control inheriting from `Entry` should be given an `Entry` handler for free until a specific one is defined.

**Comment by MhAllan** [comment]
If I get exception I know something is missing, if I don't see anything I will rather chose another technology than MAUI

**Comment by PureWeen** [comment]
This is just replicating the exact same behavior that was inside Xamarin.Forms

It'd probably be too breaking to change how this works between XF and MAUI

**Comment by dotMorten** [comment]
> If I get exception I know something is missing,

The entire point of this issue is nothing should be missing. All controls should have a default handler defined. So only 3rd party control developers would really ever hit this issue until they get that default defined. But the current experience is that the control just renders blank until you explicitly declare a handler.

**Comment by IndianaGary** [comment]
I'm running into this now with a control using the latest Skia preview. It prompted me to ask "When does a control require its own Handler?" I had thought that the Skia Handler would be enough but apparently not. I agree, Maui should work out of the box. The current behavior, throwing an Exception, is confusing at best.

**Comment by mattleibow** [comment]
@dotMorten has been asking some questions and the more I think about this issue, the less I see a reason to actually have random views "just work".

Is there a practiacal example where someone has a `class MyView : View` and then does NOT want a handler? If you just want a basic block, then `BoxView` is that. Or `Border` even. Maybe you are thinking of `Spacer` controls? If that is the case, maybe we need a special view for that which is even better because we can skip the rendering and UI things. It literally becomes something that is layout only? @hartez do we have something like this already or were there ideas/thoughts for/against a "spacer" view?

**Comment by dotMorten** [comment]
> the less I see a reason to actually have random views "just work".

Agree here. I think the current exception is a lot easier to troubleshoot than a view rendering wrong. I still think we need a way to make 3rd party controls "just work" without the need for the .UseXXX methods on the builders, since the current alternatives aren't great.
