### ISSUE TITLE
Developing MAUI Blazor Project on VM ware Work station or Hyper V

### ISSUE THREAD

**Issue by nssidhu** [dotnet/maui#3613]
I am running into few error when developing MAUI Blazor Hybrid App on VM. I got the same error on both Hyper-V 11 on windows 11 as well as VMware Workstation 16.5

I have quite powerful Machine with 64GB RAM and 8GB Video Ram ,  i7-10870H CPU 

Are there any mitigation steps or recommendations ?

![image](https://user-images.githubusercontent.com/3267605/144360078-d32da92e-e998-41fa-ab73-593edc327f3c.png)

![image](https://user-images.githubusercontent.com/3267605/144360129-0a8a0b62-b590-4b10-b2b1-045075325fb7.png)

**Comment by Eilon** [comment]
It looks like it'll run fine, but without hardware acceleration. That just means that it'll be slower, but with full functionality. Otherwise, I guess you'll need to run the emulator on the actual machine and not in a VM.

For the GPU issue, maybe you can configure the emulator to use a different GPU mode? In Android Device Manager right-click on the emulator, select Edit, and choose a different GPU mode:

![image](https://user-images.githubusercontent.com/202643/144368919-4ffe7f07-e5af-4ae3-a325-94872f53590b.png)

**Comment by nssidhu** [comment]
It does not work.

![image](https://user-images.githubusercontent.com/3267605/144439688-bf3956c0-7443-4eeb-b77d-5bf92ccccabb.png)

![image](https://user-images.githubusercontent.com/3267605/144439344-6623bd8a-ae4d-43c8-837d-fd51bb11bcfd.png)

**Comment by Eilon** [comment]
Ah the emulator doesn't even start the Android OS? Then I think it's best to use the [VS feedback tool](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) to report the issue. That way it will get to the routed to the right that owns this experience in VS.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks.
