### ISSUE TITLE
BlazorWebView -> Unable to customize Blazor Startup

### ISSUE THREAD

**Issue by dannyBies** [dotnet/maui#3644]
### Description

I'm converting a Blazor WebAssembly app to dotnet Maui and tried copying the existing WebAssembly index.html to Maui.  This works great with a small change from
 `<script src="_framework/blazor.webassembly.js" autostart="false"></script>` 
to 
`<script src="_framework/blazor.webview.js" autostart="false"></script>`

In the WebAssembly app I am also customizing the Blazor startup:
`<script>Blazor.start({ loadBootResource: loadBootResourceUpdate });</script>`
When trying to use this in Maui I get the following error:
![image](https://user-images.githubusercontent.com/3967506/144595262-373189ab-f169-46ba-bc77-9416679ec745.png)

I know that `loadBootResource` is specific to WebAssembly but there are some other [options ](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-6.0)that some users might want to use.

The issue is that initializing the WebView will [automatically start Blazor](https://github.com/dotnet/maui/blob/59cd71eb47af208c5daa92629fe80917708868ac/src/BlazorWebView/src/WebView2/WebView2WebViewManager.cs#L99) without taking `autostart="false"` into account.

Note that this is not blocking for me as I currently don't need this functionality but just wanted to report this issue. I was just wondering if it's possible to have a custom startup for a blazor webview.

### Steps to Reproduce

1. Create a new Blazor Maui application
2. Make sure 
2. Add `<script>Blazor.start();</script>`
3. Notice the following error
![image](https://user-images.githubusercontent.com/3967506/144595262-373189ab-f169-46ba-bc77-9416679ec745.png)

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 11

### Did you find any workaround?

No workaround as far as I am aware

**Comment by Eilon** [comment]
In .NET MAUI we set `autostart=false` in `index.html` and then the BlazorWebView calls `Blazor.start()` once it is done setting everything up.

If your app code calls `Blazor.start()`, first, it might not work on some platforms (Android, in particular, I think), and then when the BlazorWebView starts, of course it will cause that error because Blazor can't be started twice.

Perhaps what we need is a way to set some startup parameters (e.g. `window.BlazorStartupParams = { 'p1' = X, 'p2' = 123 };` so that whoever calls `Blazor.start()`, those parameters will be picked up? Would that work for your scenario?

@SteveSandersonMS - any thoughts on this as a potential feature request?

**Comment by SteveSandersonMS** [comment]
@Eilon We have a feature due to @javiercn called JS initializers. This gives a way to compose startup options from multiple places. Might it cover this requirement? https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-6.0

**Comment by Eilon** [comment]
@dannyBies - can you check out [this doc ](https://docs.microsoft.com/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-6.0) and see if it handles everything you would need? Of course the WebAssembly-specific feature won't be supported here because there's no WebAssembly. But maybe that's enough to cover any other startup scenario?

**Comment by Eilon** [comment]
Oh actually it looks like maybe you already saw this doc? But it seems that with JS initializers you can probably do what you need? Right now I don't think that `blazor.webview.js` has anything to customize, but if that changes, we would want to make sure it works with autostart='false'

**Comment by dannyBies** [comment]
I must have read the old docs by accident as the JS initializers cover everything I could potentially need😄, thanks!
