### ISSUE TITLE
Support visualizer in vscode

### ISSUE THREAD

**Issue by Banyc** [dotnet/maui#3660]
### Description

A visualizer as an extension in vscode that folks can download from vscode marketplace and start developing MAUI project with a real-time frontend display.

### Public API Changes

```bash
code <project folder>
```

### Intended Use-Case

I don't have enough space on my computer for the bulky VS. Vscode is the best editor I can reach. Please support a visualizer extension in vscode. Thank you.

**Comment by GeraudFabien** [comment]
For maui you need android emulator or Windows Subsystem for Android (Both are really heavy). So if you're problem is space you will still have the same with VSCode. In fact VS with no module is not that big (850MB).

As for RealTime display you may prefer HotReload that ensure a true Wysiwyg experience. Since you don't have to mock evrey data and you could see animation and resize and performance and pixel perfect render (Based on the target).

**Comment by mycroes** [comment]
> For maui you need android emulator or Windows Subsystem for Android (Both are really heavy). So if you're problem is space you will still have the same with VSCode. In fact VS with no module is not that big (850MB).

Why would Android (subsys or emulator) be required for MAUI? I'm not sure if there actually is any reason someone would pick WPF, WinForms or Avalonia over MAUI when the development support is in good shape. I also think it's a fair request to have a visualizer / WYSIWYG editor in VS Code.

**Comment by kaashyapan** [comment]
Is it possible to develop for android using MAUI without using VS today ? i.e using text editor and command line only with either a phone connected or the android emulator running ... 
If not, is it on the roadmap ?

**Comment by jfversluis** [comment]
It has been announced that the best experience for developing .NET MAUI will be in Visual Studio. While VS Code will work to some extend, because .NET MAUI is part of the CLI tooling, we do not currently have plans to invest in making the experience for VS Code better.

You can use the Comet VS Code extension which will also work for regular .NET MAUI apps, but this is not officially supported.
