### ISSUE TITLE
[Windows]Unable to create CanvasImageSource 

### ISSUE THREAD

**Issue by karthikraja-arumugam** [dotnet/maui#3785]
### Description

With native draw view, we are facing the below exception in the windows platform alone.
**Cannot create CanvasImageSource sized 25200 x 45; MaximumBitmapSizeInPixels for this device is 16384.**

![image](https://user-images.githubusercontent.com/92788387/146313278-acd20b26-a86f-4b35-973e-478854f37132.png)

Please suggest any solution for the above issue.

### Steps to Reproduce

1. We are having custom control which have scroll view.
2. Inside scroll view we have a drawable view.
3. While providing more width size for ScrollView we are facing the exception.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

As of now, we have restricted the width size of the drawable view.

### Relevant log output

```shell
Cannot create CanvasImageSource sized 25200 x 45; MaximumBitmapSizeInPixels for this device is 16384.
```

**Comment by XamlTest** [comment]
@karthikraja-arumugam Could you provide your repro project, thanks?

**Comment by karthikraja-arumugam** [comment]
Hi Team,

Please check the attached sample, We are trying to create a draw view and sometimes the width is larger depending on the requirement. So while the width exceeds some point this exception throws from DrawView.

[MAUITestSample.zip](https://github.com/dotnet/maui/files/8242104/MAUITestSample.zip)

Note: I'm using - Dell laptop

**Comment by XamlTest** [comment]
Verified on Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32223.438.main]. Repro on Windows with above project.
![image](https://user-images.githubusercontent.com/97647558/158150913-4dada897-7a36-4ff7-a8fc-fafcafdb4d6a.png)

**Comment by mattleibow** [comment]
This appears to be a OS limitation. And, I would strongly recommend creating a image in memory of this size as some machines may run out of memory. In addition to this, you will be drawing the entire canvas (even when not on the screen) 60 times a second.

Instead of creating an image that has a massive size and then placing it on the screen inside a scrollview, you should instead create a view that is the size of the screen and then scroll the content. You can make use of the touch effects in the Maui Community Toolkit to track pointer positions and draw the content at an offset.
