### ISSUE TITLE
Unable to run any preview 10 maui/blazor projects

### ISSUE THREAD

**Issue by musictopia2** [dotnet/maui#3812]
### Description

When I create a brand new maui project using preview 10, if i try to click on any file or even use the dropdown to choose target to run, it hangs.  Worked perfectly with preview 7 though.

The previous version I had which worked perfectly was preview 7.  I never used previews 8 or 9.

When I used the visual studio installer to install preview 10 (including visual studio 2022 preview 1), then this happened.

### Steps to Reproduce

Create new maui/blazor app.
Then after filling in default options, then double click any file.
Then it hangs.

### Version with bug

Preview 10 (current)

### Last version that worked well

Preview 7

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

All platforms was affected

**Comment by musictopia2** [comment]
I tried even the maui that has no blazor and it still crashes.  I would be really disappointed if somehow maui won't even work.  Wish there was a way to go back to preview 7 which worked with no problems.

**Comment by Eilon** [comment]
Hi @musictopia2 , you're saying that Visual Studio is crashing, or the MAUI app itself?

If it's VS that is crashing, could you use the [VS feedback tool](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) to report the issue? That way it will get to the routed to the right that owns this experience in VS.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks.

**Comment by musictopia2** [comment]
Visual studio.  i can't even run the maui app.  It crashes before even attempting to run.   That is the default templates (with no custom code even).

**Comment by Eilon** [comment]
OK thanks for the report. Please use the VS feedback tool I mentioned because that will capture logs and get routed to the right team.

**Comment by musictopia2** [comment]
I did use the vs feedback.  However, it was ignored.  I would be really disappointed if next year when its released, if anybody had used any previews, then they can't do maui apps on their computers.

**Comment by Eilon** [comment]
@musictopia2 a lot of folks at Microsoft are on holiday/vacation until early January so they might be slow to respond to this issue.
