### ISSUE TITLE
No maui project template in  VS 2022 Version 17.1.0 Preview 1.1

### ISSUE THREAD

**Issue by KirillPom** [dotnet/maui#3822]
### Description

Run VS.
Despite having maui components installed there is no project template.
![image](https://user-images.githubusercontent.com/65759581/146941714-ed780f03-6eb4-499a-a46c-b3dc09df783c.png)

### Steps to Reproduce

Run VS.
Despite having maui components installed there is no project template.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

 VS 2022 Version 17.1.0 Preview 1.1

**Comment by alecsandru95** [comment]
Try and run the following command : dotnet workload install maui

**Comment by Eilon** [comment]
Hi, we think this issue has been fixed in more recent previews of .NET MAUI and Visual Studio. Please try installing the latest preview per the instructions at https://docs.microsoft.com/dotnet/maui/get-started/installation. If you are still experiencing an issue, please file a new issue with updated details.
