### ISSUE TITLE
InvalidateMeasure in child triggers parent measure

### ISSUE THREAD

**Issue by karthikraja-arumugam** [dotnet/maui#3831]
### Description

In our custom control, we have a nested layout, in which if we call InvalidateMeasure for child element it triggers parent measure. This causes a loop in our implementation.

Sometimes InvalidateMeasure doesn't trigger the calling layout's measure itself.

### Steps to Reproduce

[TestSample.zip](https://github.com/dotnet/maui/files/7760780/TestSample.zip)

1. Run the attached sample. It has the below implementation
Custom Control => Layout => Grid => ScrollView => DrawableView

2. Press the InvalidateSize button, it will invalidate the layout measure and it triggers custom control (parent layout) measure.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Android 9.0, Windows SDK 10.0.19041 

### Did you find any workaround?

No

**Comment by wenwen60** [comment]
Reproduce on 17.2.0 Preview 2.0 using Android 11, attach repro sample
[TestSample.zip](https://github.com/dotnet/maui/files/8131292/TestSample.zip).

**Comment by hartez** [comment]
> if we call InvalidateMeasure for child element it triggers parent measure

It is true that calling `InvalidateMeasure()` on a control may trigger the Measure of the parent control. That is expected behavior. 

> This causes a loop in our implementation.

I am not seeing a loop in the repro project you provided. Clicking the button calls the child's `InvalidateMeasure()`; the parent and child controls' `Measure()` methods are called, the controls are arranged, and the cycle ends. 

Could you tell us why you are trying to call `InvalidateMeasure()` on a child control?
