### ISSUE TITLE
Cannot use StaticResources for resources in App.xaml

### ISSUE THREAD

**Issue by dhindrik** [dotnet/maui#3878]
### Description

I am not able to use StaticResource.

### Steps to Reproduce

1 . Clone https://github.com/dhindrik/ResXapp
2. Run it, it will crash on start
3. Change StaticResource to DynamicResource in Views/MainView.xaml
4. Run it again, it will work.

I have tested on iOS and macOS.

I am using VS for Mac 2022, the latest public preview.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS15

**Comment by XamlTest** [comment]
Verified Repro with Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32227.94.main]. Repro Project is available: [3878.zip](https://github.com/dotnet/maui/files/8166196/3878.zip)

**Comment by StephaneDelcroix** [comment]
I'm not familiar with the mvvm framework you're using. are you sure the App is instantiated before the page ? App instantiation is responsible to set Application.Current, that enable resolving app-level {StaticResource}

**Comment by IndianaGary** [comment]
@StephaneDelcroix : This has nothing to do with MVVM. I suppose that DI could impact it if the App-level ResourceDictionary is built AFTER resolution of dependencies (any pages resolved would have InitializeComponent called before the App RD was built.) 

BTW, I can confirm that this issue still exists in RC2.

**Comment by StephaneDelcroix** [comment]
@IndianaGary StaticResource are resolved, using Application.Current, at the time the page is inflated. DynamicResource are evaluated at the same time, but reevaluated when something changes in the parent's list (like ultimately parenting your page to the Application). That's the difference, that's why StaticResource does not work and DynamciResource does. Application has to be initiated first, and I bet it's not the case here
