### ISSUE TITLE
Use AppleMaps for iOS Maps

### ISSUE THREAD

**Issue by MaxG-Enpal** [dotnet/maui#3918]
### Description

Hello, Dear Maui Team,

please use the native Apple Maps API on iOS to provide the best and efficient experience on iOS Devices.

Thank you!

**Comment by jfversluis** [comment]
Hey @MaxG-Enpal I'm curious why you open this (please see this as a hint to add a bit more detail to your story in the future as well and just use the templates that are in place 😄 ), because the Xamarin.Forms Maps have always used the platforms implementation on each of the OSes. So I'm not really sure what you're asking here?

**Comment by MaxG-Enpal** [comment]
> 

I read online a statement of a Developer that they want to use BingMaps/GoogleMaps on every platform, which would be a topic killer since AMaps has the best performance on Apple devices.

So I just really hope that this plan is discarded, and platform maps will stay in MAUI.

**Comment by jfversluis** [comment]
I appreciate your concern, but as documented [here](https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/map/map) each platform will use their own respective map by default, I don't see any reason why that would change for .NET MAUI. Closing this one for now :)
