### ISSUE TITLE
Unable to re-open MAUI project in Visual Studio 2022 (not preview)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#4024]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-re-open-MAUI-project-in-Visual/1576978)._

---
[severity:I'm unable to use this version] 
I installed the new release of Visual Studio 2022 (not preview) available since yesterday. 
I also installed MAUI workload from a command prompt
    dotnet workload install maui

![image.png](https://aka.ms/dc/image?name=B47ffc8b0766a4d27aca74f9a9de7bb82637720810165701199_20211109-195655-image.png&tid=47ffc8b0766a4d27aca74f9a9de7bb82637720810165701199)

I can create a new project and choosing the .Net MAUI App (Preview)

![image.png](https://aka.ms/dc/image?name=B922033bf92d442fb8f35d88db43c69b0637720810399221398_20211109-195717-image.png&tid=922033bf92d442fb8f35d88db43c69b0637720810399221398)

I see the solution and all the files inside.

![image.png](https://aka.ms/dc/image?name=B433fd41e0dee4fdf94e1bca2d98944e0637720810578958893_20211109-195736-image.png&tid=433fd41e0dee4fdf94e1bca2d98944e0637720810578958893)

I can compile the solution successfully.

If I close then re-open the solution it failed.

![image.png](https://aka.ms/dc/image?name=Bc9bd06411be14d0c98a4686b0f25df1c637720810781008170_20211109-195756-image.png&tid=c9bd06411be14d0c98a4686b0f25df1c637720810781008170)

I don'have problems for a simple Console App project. 
So the problem seems to be related to MAUI templates.

---
#### Feedback Bot on 11/9/2021, 10:26 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
This is expected behavior and as the messages states: this type of project is incompatible with that version of Visual Studio.

As .NET MAUI is still in preview and VS2022 17.0 is stable, we can't have preview bits in a stable release. That is why .NET MAUI support has been moved to VS2022 17.1 Preview and is actively blocked on the current stable release.

If you want to use .NET MAUI you should use VS2022 preview which can be installed side-by-side with the stable VS2022.
