### ISSUE TITLE
incompatible new maui project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#4025]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/incompatible-new-maui-project/1587422)._

---
[severity:I'm unable to use this version]
the project does not load after it has been created. Install vs2022 but something seems to be wrong.

---
#### Feedback Bot on 11/17/2021, 08:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
I hope the author of this ticket gets to see this!

I'm going to have to close one as it is right now because this is unfortunately too little information to go on. If you're still experiencing this problem in the latest versions feel free to ping us with additional information like error messages or logs.
