### ISSUE TITLE
Shell FlyoutWidth wrong first load on Windows

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#4144]
### Description

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/41873/149573806-dd332fa5-46e1-40f0-992a-10c3f27c7005.png">

The first load of the fixed (locked) flyout is the wrong width. It should be 68. 

```xaml
<Application.MainPage>
        <Shell 
            FlyoutWidth="68"
            FlyoutBackgroundColor="{StaticResource Background_Mid}"
            FlyoutBehavior="{OnIdiom Phone=Disabled, Default=Locked}">
```

### Steps to Reproduce

Run WeatherTwentyOne on Windows

Then navigate to Favorites and see the Flyout size properly.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Win11

**Comment by Redth** [comment]
Removing the item template the same behaviour persists:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/271950/150838924-4e77ff6e-ca4e-4b0c-80c8-76e8cac79e41.png)

Once you change the selection, it shrinks again, of course:
![image](https://user-images.githubusercontent.com/271950/150839031-788c466f-a4bb-4715-9e30-e0a60f28f78e.png)

The interesting thing is that this appears that the initial state of the flyout is just expanded/locked instead of the expected shrunk (not sure the winappsdk terminology).

So this may not be a MAUI measuring bug but rather a bug in the state of the winui control.
