### ISSUE TITLE
Default templates for both blazor and regular won't even compile

### ISSUE THREAD

**Issue by musictopia2** [dotnet/maui#4148]
### Description

When I go to file/new project and try to run on windows. it gives many compile errors.
Somehow says there is a conflict with preview 7.  I did at one point use preview 7.
I would be really disappointed if anybody who ever used preview 7 can't ever do maui apps.

### Steps to Reproduce

1.  Create new maui app
2.  Run the default template
Everytime, it won't even compile.
If I try to go to any of the code files, says many things don't even exist like IAppHostBuilder

The last version where everything worked great was preview 7.  However, in November when I installed the released version of .net 6, it completely broke all maui apps.

### Version with bug

Preview 11

### Last version that worked well

Preview 7

### Affected platforms

Windows

### Affected platform versions

All platforms was affected

**Comment by jfversluis** [comment]
Please uninstall all preview versions of .NET 6 and reinstall VS completely. I am fairly confident this should work then. Seeing that there aren't a lot of people with this same issue I think this is something specific to your environment rather than an issue on our side at this time. 

Closing this for now, let us know if there is still an issue if you've reset all these things. Thanks!
