### ISSUE TITLE
CBPeripheralsEventArgs unreachable

### ISSUE THREAD

**Issue by ITWT73** [dotnet/maui#4328]
### Description

CBPeripheral**_s_**EventArgs is not reachable under MAUI.

API IOS SDK 12 :
https://docs.microsoft.com/en-us/dotnet/api/corebluetooth.cbperipheralseventargs?view=xamarin-ios-sdk-12

### Steps to Reproduce

Under Maui project net6.0-ios plateform,
CBPeripheral[] peripherals;
new CBPeripheralsEventArgs(peripherals));

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

**Comment by rolfbjarne** [comment]
The `CBPeripheralsEventArgs` class doesn't exist anymore, because the events that needed the `CBPeripheralsEventArgs` class don't exist anymore (`CBCentralManager.RetrievedPeripherals` and `CBCentralManager.RetrievedConnectedPeripherals`).

These events don't exist anymore, because Apple completely removed them from their API.

What do you need the `CBPeripheralsEventArgs` class for?
