### ISSUE TITLE
Clean removal of previous versions of MAUI when a new one is installed

### ISSUE THREAD

**Issue by pierre01** [dotnet/maui#4344]
### Description

I am encountering many obstacles while installing MAUI that are not allowing me to compile my code,
This happened before but now with VS 2022 preview 4, I am stuck and I don't see how to clean my environment to allow a clean installation.

You should provide a tool to remove all previous MAUI workloads so the new ones can be installed properly.
Most common error is 
C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): **error NETSDK1147**: To build this project, the following workloads must be installed: maui-android

Same with maui-windows, maui-ios, etc....

### Public API Changes

No API related

### Intended Use-Case

Tool to cleanup previous installs of MAUI to allow clean install of new ones without conflicts

**Comment by jfversluis** [comment]
I understand how this idea came to be, however this should only be a problem during the previews. Typically this should install a lot better together with Visual Studio/.NET to begin with. If that turns out to be not the case somewhere down the road I think we should revisit. For now I'm going to assume this is a temporary pain we're going to have to deal with for now.
