### ISSUE TITLE
Build Error NETSDK1032 when changing Platform Target to x86 on Windows

### ISSUE THREAD

**Issue by BenBtg** [dotnet/maui#4503]
### Description

Build Error NETSDK1032	The RuntimeIdentifier platform 'win10-x64' and the PlatformTarget 'x86' must be compatible.	TestApp	C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets	196	if targetting x86 on Windows

### Steps to Reproduce

1. Create new MAUI app
2. Go project setting and set Platform target to x86
3. Build
4. Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1032	The RuntimeIdentifier platform 'win10-x64' and the PlatformTarget 'x86' must be compatible.	TestApp	C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets	196	

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

No

### Relevant log output

```shell
Build started...
1>------ Build started: Project: TestApp, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(196,5): error NETSDK1032: The RuntimeIdentifier platform 'win10-x64' and the PlatformTarget 'x86' must be compatible.
1>Done building project "TestApp.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
```

**Comment by mattleibow** [comment]
Are you building on a 32-bit machine/OS?

**Comment by alexkblount** [comment]
Building for X86. This can be achieved with a standard net6 console app. The issue here is being able to Pinvoke into a 32bit only dll. This was supported prior to net 6 as x86 was the default. We want to be able to specify the target platform to x86 so on both x86 and x64 the pinvoke into the 32bit dll will be successful.

**Comment by mattleibow** [comment]
Let me gather some more info. Typically you would just set the RuntimeIdentifier to whatever you wanted to target. For example, you would change the `win10-x64` to `win10-x86` in the csproj. However, even though this compiles, it appears to be trying to load some x64 dlls in a x86 process.

I am going to try reproduce this in a WinUI app and see what I can do as a workaround as well.

**Comment by mattleibow** [comment]
I created a bug to track this. Thanks for reporting it. https://github.com/microsoft/WindowsAppSDK/issues/2064

**Comment by shimingsg** [comment]
Verified Repro with windows. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EZw_pzX2B7hMoYKeh8r0O-YBiN86DXJSW4fUXDaR4cjRow?e=eKzsd2

**Comment by mattleibow** [comment]
I was mistaken. As per the error message, the RID of x64 and the platform of x86 are incompatible. However, this should not happen anymore with the 1.0.1 Windows App SDK and the upcoming RC build of MAUI #5333 and #5434 

With new .NET things, there are 2 options for selecting x86/x64/arm64:
 - set the Platform `<Platform>`
 - set the RID `<RuntimeIdentifier>`

They need to match exactly as they represent the "same thing" but to different parts of the build:
 - Platform is the the compiler mostly
 - RID is to the runtime

You _can_ use Platform in a .NET Maui app, but it is a bit messy because you need to adjust things for all the platforms and correctly set other things.

The easier option is to use the RID and change that with a condition if need be. This means you get an Any CPU managed .dll, but the final app is building for the platform you selected in the RID.
