### ISSUE TITLE
BasicBlazorComponentClick test fails on Android API 27 and earlier

### ISSUE THREAD

**Issue by pranavkm** [dotnet/maui#4517]
![Flaky-image](https://user-images.githubusercontent.com/174281/152618628-1cb90c5b-a07a-42ff-8395-d673e7678d34.png)

This test is one of 3 that affects the overall pass rate for the repo and we should prioritize fixing it.

**Comment by SteveSandersonMS** [comment]
Looks like increasing the timeout (https://github.com/dotnet/maui/pull/4543) didn't work: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5724063&view=ms.vss-test-web.build-test-results-tab&runId=32882308&resultId=100000&paneView=debug

```
System.Exception : Waited 7500ms but couldn't get controlDiv to have value '0'. Most recent value was 'null'.
```

However this doesn't look like flakiness to me. **In all 5 of the most recent builds, `android_device_tests_blazorwebview_X` failed for all X<28, and passed for all X>=28**. That can't be a coincidence, surely. This must mean that it works for Android API level 28 and above, but that the actual feature doesn't work on API level 27 and below. Note that API 28 = Android 9 (2018).

I'm assuming that since MAUI has tests going back to API level 23 (Android 6, 2015), that's what MAUI apps are supposed to support. We need to debug why BlazorWebView doesn't work that far back. It might be that we're using some JS APIs that didn't appear until later. Or it might be a problem in MAUI itself. I'm going to change the issue title to match this.

**Comment by SteveSandersonMS** [comment]
So it turns out I was wrong about the underlying functionality being broken. I've confirmed that `BlazorWebView` does actually work fine on API level 27. Even the test in question here (`BasicBlazorComponentClick`) runs and passes locally on API level 27.

As such, there must be some other reason why this test mechanism consistently fails on API <= 27 when running in CI, as in [this build](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5725455):

![image](https://user-images.githubusercontent.com/1101362/153190902-c68b5b86-955d-45dc-8be9-7d1e1bb510d2.png)

Inspecting logs from the API level 27 run, the following looks like a smoking gun:

```
02-08 09:52:06.734  5288  5288 I chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'innerText' of null", source:  (1)
02-08 09:52:06.736  5288  5288 I chromium: [INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token import", source: https://0.0.0.0/_framework/blazor.webview.js (1)
02-08 09:52:06.762  5288  5288 I chromium: [INFO:CONSOLE(2)] "Uncaught ReferenceError: Blazor is not defined", source:  (2)
```

Yes, it's very much not going to work if we use `import` and the browser engine is too old to support that. As for why the browser engine in CI is older than the one I get when using API level 27 locally, presumably the Chrome version isn't tied to the API level, so you could get different Android build or updates that affect the Chrome version independently of the API level. I don't know if the WebView browser engine version is determined by the installed Chrome app version, or whether that's a separate thing.

We need to work out how exactly we are defining the range of supported Android versions, and perhaps stop using `import` in `blazor.webview.js`.

**Comment by SteveSandersonMS** [comment]
Note that here's where we use dynamic import. It's not specific to blazor.webview.js:

https://github.com/dotnet/aspnetcore/blob/6a6be13f6d37e68802cdcf31999df2cd1912f7ae/src/Components/Web.JS/src/JSInitializers/JSInitializers.ts#L26

**Comment by SteveSandersonMS** [comment]
According to the following, Chromium gained support for `import` in version 63 (December 6th, 2017).

![image](https://user-images.githubusercontent.com/1101362/153196279-29514273-71a8-4210-a3cb-d098d74a941a.png)

The next major version of Android that was released after this date was Android 9 (Pie, August 6, 2018). This is also where API level 28 came in, which is also where our E2E test starts passing.

**Comment by SteveSandersonMS** [comment]
I'm not sure where we can get worthwhile statistics on the market share of different Chrome for Android versions. Online sources for browser market share data don't easily offer any breakdowns of Chrome for Android versions.

The [statistics for Android < 9 versions](https://gs.statcounter.com/android-version-market-share/mobile-tablet/worldwide) look pretty bad:

| Region | Usage of 8.1 and below |
| --- | --- |
| Worldwide | 27.48% |
| Europe | 21.15% |
| USA | 17.75% |
| China | 28.49% |

However, presumably a lot of these end users aren't actually still on Chrome 62, even if their device was like that when they bought it. If a lot of the Blazor developer community needed to support Chrome 62, then we'd have got a lot more pushback about Blazor on .NET 6, since it uses `import` in `blazor.webassembly.js` and `blazor.server.js`. I don't recall getting any complaints about that.

@dotnet/aspnet-blazor-eng @danroth27 Have we already got a defined plan for Android version support? Is it meant to be the same as MAUI itself? I suspect we're going to have to define it as being "the same devices that can use Blazor Server and Blazor WebAssembly in their browser", which is currently Chrome 63+.

The only alternative would be to refactor `blazor.webview.js` so that it doesn't attempt to parse any JS code that includes the `import` keyword when you're not actually using JS initializers. Then at least it would work by default on older browsers, and it would be the JS initializers feature specifically that requires a newer browser. However this isn't a great direction for us to go in, as we wouldn't be testing broadly on such old devices and don't want to be heavily limited on implementing newer features that require more recent browsers.

**Comment by javiercn** [comment]
Wholeheartedly agree with @SteveSandersonMS here. Our support matrix should be the intersection between Maui and Blazor. Supporting things outside that creates a broken experience and forces us to expand the Blazor support matrix which would require big changes and would have a severe impact on libraries.

As a compromise, we could think of a way that lets users get access to the files at build time so that they can transpile the sources and include necessary polyfills without us providing any guarantee that everything would be supported. (We won't block you, but we won't consider that scenario part of our support matrix)

**Comment by danroth27** [comment]
Adding @davidortinau and @jamesmontemagno to add their perspectives on our support matrix for MAUI.

**Comment by Eilon** [comment]
There are 2 issues with old Android support, give me a sec to find them.

**Comment by Eilon** [comment]
These are the two "older Android" issues I know of:

1. Android 5 (**very** old): https://github.com/dotnet/maui/issues/3023
2. Android 7.1 (*kinda* old): https://github.com/dotnet/aspnetcore/issues/39086#issuecomment-996248608

**Comment by danroth27** [comment]
> But even with all this, we'd be concluding that BlazorWebView's support range is a subset of MAUI's, since MAUI itself can also run on Android 5 even if the browser has not been updated. We couldn't strictly claim that BlazorWebView runs everywhere that MAUI does and might need to note that in some docs somewhere.

Agreed. I'll follow up to make sure this gets documented.

**Comment by jamesmontemagno** [comment]
https://apilevels.com/ is a good reference point... It really depends RN for example also support API 21+ and iOS 11+. Ionic seems to be the same with v6 supporting 5.0+ with Chromium 60+ on Android but iOS i only iOS 13+ which is interesting.

So I think maybe it is just documentation and have a "recommended" lowest version. I target API 26 personally now adays.

**Comment by Laftek** [comment]
Is there any way how to detect browser version installed on the device from within MAUI? Or any other way how to check if the browser version will be compatible with MAUI Blazor? 

I am asking for using this information to, for example display message: “Please update your browser app”. 

I am new to this so sorry if thats stupid question. Thanks.

@jamesmontemagno @SteveSandersonMS

**Comment by Eilon** [comment]
@Laftek please log a new issue. Comments on closed items will likely not get seen.
