### ISSUE TITLE
Acces to unique ID of the device

### ISSUE THREAD

**Issue by julienGrd** [dotnet/maui#4670]
### Description

I would like to have the unique id of the device, not the name, which can be personnalized by the user, and i need something more unique.

for xamarin, i found some answers on this link https://docs.microsoft.com/en-us/answers/questions/300760/unique-idenifier-for-device.html

I don't know id its still relevant and how to make it works in MAUI

Whats your recommandation on this ?

can we expect a property DeviceInfo.Id in the future or something like that ?

### Steps to Reproduce

1. no way to have the Device Id in MAUI

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Android 11

### Did you find any workaround?

No

**Comment by TomBruyneel** [comment]
I want to start by saying that it's probably not such a good idea to use that identifier, it would for example probably make more sense to use something like a firebase installation token. But if you want to proceed anyway, here is how:

You would do it more or less in the same way, even easier because of the DI extensions and the MauiAppBuilder

Add the interface from the link you provided somewhere in your project.

`public interface IGetDeviceInfo
    {
        string GetDeviceID();
    }`

Go to the Platforms folder -> Android and add a class GetDeviceInfo

`using static Android.Provider.Settings;

namespace YourNamespaceMakeSureItDoesntEndWithDotAndroid
{
    internal class GetDeviceInfo : IGetDeviceInfo
    {
        public string GetDeviceID()
        {
            var context = Android.App.Application.Context;

            string id = Android.Provider.Settings.Secure.GetString(context.ContentResolver, Secure.AndroidId);

            return id;
        }
    }
}`

And then add it to your DI services, for example like this:

`	public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
			})
			.Services.AddTransient<IGetDeviceInfo, GetDeviceInfo>();

		return builder.Build();
	}`

And that is it, you can now inject that interface anywhere you need it and get the id. For example in App.xaml.cs

`public partial class App : Application
{
	public App(IGetDeviceInfo getDeviceInfo)
	{
		InitializeComponent();

		var id = getDeviceInfo.GetDeviceID();

		MainPage = new MainPage();
	}
}
`

You would have to create the implementation file for all the platforms you want to support of course.

**Comment by julienGrd** [comment]
Ok thank you, it work as expected.

 i did some research about "firebase installation token" but i found nothing relevant, if you have some links ?

anyway its close on my side
