### ISSUE TITLE
Multiple Microsoft.Maui.*.dll's map same type name to the same xmlns

### ISSUE THREAD

**Issue by etvorun** [dotnet/maui#4720]
### Description

Multiple Microsoft.Maui.*.dll's map same type name to the same xmlns

### Steps to Reproduce

1. Examine Microsoft.Maui.Graphics.dll and Microsoft.Maui.Controls.dll in [ILSpy](https://github.com/icsharpcode/ILSpy)

**Actual**: they both contain types like Rectangle which is mapped into http://schemas.microsoft.com/dotnet/2021/maui namespace.
**Expected**: only one type from Microsoft.Maui.*.dll's should be mapped into same namespace
**Note**: when VS XAML parser processes e.g. `<Rectangle Margin='4'/>` it will pick up type from the first assembly where it is available. This causes errors like "Margin is not available in Rectangle".

Here is what I see in ILSpy
Microsoft.Maui.Graphics.dll
[assembly: XmlnsDefinition("http://schemas.microsoft.com/dotnet/2021/maui", "Microsoft.Maui.Graphics")]
public struct Microsoft.Maui.Graphics.Rectangle

Microsoft.Maui.Controls.dll
[assembly: XmlnsDefinition("http://schemas.microsoft.com/dotnet/2021/maui", "Microsoft.Maui.Controls.Shapes")]
public Microsoft.Maui.Controls.Shapes.Rectangle : Shape, IShape

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

all

**Comment by drasticactions** [comment]
This is a big issue. If we have any XAML Parsing errors, we can't Hot Reload, since we can't make informed actions on what to change.

IMO it may make sense to switch Maui.Graphics to a new XMLNS. If you're in XAML for MAUI, 99% of the time you're probably using Maui.Controls. Graphics is low level, so having to declare it seems reasonable to me as a compromise. It really stinks having to do it _right now_ given everything else, but that's probably the right thing to do here and would really help everyone out long term.

**Comment by Redth** [comment]
Related change: https://github.com/dotnet/Microsoft.Maui.Graphics/pull/318

**Comment by Redth** [comment]
Fixed
