### ISSUE TITLE
XAML editor no longer working for MAUI library in Preview 13

### ISSUE THREAD

**Issue by RichardMarsh** [dotnet/maui#4740]
### Description

Before updating to Preview 13, we would have two MAUI projects. One that is the app and another that would be a MAUI specific library. We'd put our shared XAML files in the shared library and edit them in the editor with no issue. 

After updating to  Preview 13, when opening a XAML file in the library it will no longer open even though the XAML is perfectly fine. 

Below are examples of the behaviour in a new solution

![image](https://user-images.githubusercontent.com/54434905/154415674-79d2dd10-eaeb-4d76-b4b0-f9cb97da5bea.png)

Opening a XAML file in the app project works fine

![image](https://user-images.githubusercontent.com/54434905/154415798-4a87122f-3750-4dd6-be7a-70ad02971b6b.png)

I also noticed that stylesheets pulled in from library projects no longer correctly provided their keys to XAML files in the main project.

### Steps to Reproduce

1. Create a new .NET MAUI App project in a new solution
2. Create a new .NET MAUI Library project in same solution
3. In the library project add new item -> .NET MAUI Content Page (XAML)  (note it can be any XAML file)
4. Double click the XAML file to open in editor
5. Screen should now be blank instead of showing the XAML

Replication repo: https://github.com/RichardMarsh/MauiApp1

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 12

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

NA

### Did you find any workaround?

No

**Comment by egvijayanand** [comment]
Facing the same issue needs a fix on priority.

**Comment by egvijayanand** [comment]
> "(note it can be any XAML file)"
> 
> That's not a MAUI issue, that's a Visual Studio issue. I would file that with [Visual Studio Feedback](https://developercommunity.visualstudio.com/spaces/8/index.html).

If it's for every XAML file, then it's an issue with VS. But XAML files in the App project works fine. The issue is only wrt to the Library project. In this case, it could be anyone's boundary.

**Comment by XamlTest** [comment]
Not reproduced on Windows(OS: 19044.1526).
Repro Project: [4740-MAUILibrary.zip](https://github.com/dotnet/maui/files/8140711/4740-MAUILibrary.zip)

**Comment by egvijayanand** [comment]
Screenshot from VS2022 17.2.0 Preview 1.0 running on Windows OS Ver. 10.0.22000.527

On the left is the XAML file from the class library project and on the right is the XAML file from the App project.

<img width="960" alt="VS2022-ClassLib-XAML-Blank-Page-Issue" src="https://user-images.githubusercontent.com/81947404/155708291-0ee31ad8-0975-4187-88b9-2af423934fec.png">

**Comment by XamlTest** [comment]
@egvijayanand We still cannot repro  this issue with your project, could you reset your VS settings or check the permission of the Xaml file, if still repro, please also try to Repair your VS from VS Installer.
![image](https://user-images.githubusercontent.com/97647558/156739921-9b90172c-e663-40be-8fca-7fbf37c6175a.png)

**Comment by egvijayanand** [comment]
> We still cannot repro this issue with your project

It's consistently simulating, here're the steps to reproduce the issue.

* Create a new `.NET MAUI Class Library (Preview)` project
* Add a new `.NET MAUI ContentPage (XAML)(Preview)` item
* Try to open the created Xaml file in VS

And found out the probable cause of the issue as well, the pre-built (Class Library) template published with .NET MAUI workload has `net6.0` as the first TargetFrameworks in the list.

https://github.com/dotnet/maui/blob/20657cc6e1a56f1031face55bb719805979d39ad/src/Templates/src/templates/maui-lib/MauiLib1.csproj#L4

Here, DOTNET_TFM_VALUE corresponds to `net6.0`

Generated output:

```xml
<TargetFrameworks>net6.0;net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>
```

Have attached the library project for your simulation.

[VSXamlIssue.zip](https://github.com/dotnet/maui/files/8185049/VSXamlIssue.zip)

To clear the error for time being:

* Remove the `bin` and `obj` folders (Since `TargetFrameworks` list is getting updated, need to remove these folders)
* Open the library project file in any text editor
* Delete the `net6.0` (including the semicolon that follows this value) and save the project file
* Now open the project/solution again in VS, this time Xaml file gets opened without any issue

There's some issue in this version of VS, as we're observing red squiggles when working with the files in the `Platforms` folder. This may be attributed to that also, if you conclude the same, kindly transfer this issue to them.

Refer issue #4931, the platforms selector is not working as expected in this VS 17.2 Preview 1.0

**Comment by hartez** [comment]
@XamlTest Your comments are confusing - you say you can't verify it but you've marked it with the "verified" label.

@egvijayanand I've seen this inside the MAUI solution itself. We've got an internal VS issue tracking it; hoping to see a fix soon.

**Comment by kristinx0211** [comment]
verified not repro on windows with vs 17.2.0 Preview 2.0 [32301.586.main].
