### ISSUE TITLE
VisualElement.Bounds's size does not match IView.Width/Height

### ISSUE THREAD

**Issue by etvorun** [dotnet/maui#4764]
### Description

VisualElement.Bounds's size does not match IView.Width/Height

### Steps to Reproduce

1. Open, build and run attached project.
2. Click on button.

**Actual**: text shows that StackLayout size obtained via VisualElement.Bounds does not match size obtained  via IView.Width/Height 
**Expected**: sizes match
[MauiApp13.zip](https://github.com/dotnet/maui/files/8091817/MauiApp13.zip)
![image](https://user-images.githubusercontent.com/48451158/154561217-d770ea41-23e0-4787-a532-e2dc290197c4.png)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

**Comment by v-xiaofchen** [comment]
Verified repro with windows and the above project.
![Picture12](https://user-images.githubusercontent.com/99376012/155667762-0c8c840c-80b5-4532-a1d7-21b6c9c9cefa.png)

**Comment by hartez** [comment]
The values don't match because they don't represent the same properties of a VisualElement/IView. 

This is, admittedly, confusing. 

`VisualElement.WidthRequest` and `VisualElement.HeightRequest` map to `IView.Width` and `IView.Height`, respectively. There are values set by the user to indicate the width/height a control should have. 

`VisualElement.Bounds` is equivalent to `IView.Frame`. If you are working with an IView and want the current width/height of the IView, you can use `IView.Frame.Width`/`IView.Frame.Height`. If you're working with a VisualElement and want the current width/height of the VisualElement, then you can use `VisualElement.Width`/`VisualElementHeight`, or `VisualElement.Bounds.Width`/`VisualElement.Bounds.Height`. 

The reasons for the disconnect between the names is backward compatibility. Xamarin.Forms had made some naming choices we didn't want to bring forward into MAUI.Core, but we had to leave those names intact in MAUI.Controls so that transitioning from Forms to MAUI.Controls would be as easy as possible.

**Comment by etvorun** [comment]
@hartez what API should we use for XAML Hot Reload to get size occupied by element when it is rendered in app? For example for WPF and UWP we use [UIElement.RenderSize](https://docs.microsoft.com/en-us/dotnet/api/system.windows.uielement.rendersize). Note that for WPF/UWP render size can differ from Width/Height, e.g. because of MinWidth/MinHeight.

**Comment by mattleibow** [comment]
I think you are wanting to use the `IView.Frame` property.

**Comment by hartez** [comment]
> Note that for WPF/UWP render size can differ from Width/Height, e.g. because of MinWidth/MinHeight.

Right, the equivalent properties in UWP/WPF would be ActualHeight and ActualWidth. 
Matt's correct, if you're doing this with a MAUI IView, you want to use IView.Frame.
