### ISSUE TITLE
[Android] TableView doesn't respond to click after first use/navigation

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#4809]
### Description

Until P13, `TableView` has worked well for me. I tend to use it in samples for navigation. The `TableView` presents a list of demos, and clicking on one navigates you to another page to demo a specific feature.

Now, in P13 on Android, after using `TableView` to navigate to a page, then navigating back to the `TableView` page, clicking on an item doesn't cause navigation to occur. Once you navigate back to the `TableView` page you're unable to navigate to another other page.

This problem doesn't occur on Windows.

[Triggers.zip](https://github.com/dotnet/maui/files/8108442/Triggers.zip)

### Steps to Reproduce

1. Run the attached sample on Android.
2. Navigate to a page.
3. Navigate backwards (back to the TableView). At this point you can't navigate again.

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 12

### Affected platforms

Android

**Comment by J-Swift** [comment]
Ran into this as well last week but wasn't sure if I broke something. In my project, the iOS version works but android stops responding after the 1st navigation.

**Comment by kristinx0211** [comment]
Verified repro with Android 11 and the above project.

**Comment by samhouts** [comment]
Couple of things. First, this project is now completely unable to launch because of https://github.com/dotnet/maui/issues/6366. Second, the TableView _is_ clickable still, but only if you wait for a little while. And each subsequent time that you navigate back and forth, "a little while" increases in length. There's probably a leak or loop that needs to be resolved.
