### ISSUE TITLE
"java.exe" exited with code 1

### ISSUE THREAD

**Issue by pierrebrito** [dotnet/maui#4853]
### Description

When trying to compile an android application, I get this error:
"java.exe" exited with code 1

Does anyone know what the problem is and how to fix it?

### Steps to Reproduce

N/A

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 13 (current)

### Affected platforms

Android

### Affected platform versions

Android

**Comment by jfversluis** [comment]
Hey @pierrebrito thanks for your question! However, the issues are more for whenever you want to request a feature or think there is a bug in our project :)

This particular error usually has a root cause on the Android level. Have a close look at the build output and logs if there is any other error message in there. If you can't figure it out I would suggest asking in the Microsoft Tech Community forums, join the DotNet Evolution Discord server or other sites like Stack Overflow that will get more responses probably.
