### ISSUE TITLE
[WinUI] Crashing issue in ScrollView with orientation horizontal

### ISSUE THREAD

**Issue by RanjithkumarSyncfusion** [dotnet/maui#4951]
### Description

When loading a ContentView inside a ScrollView(Horizontal) with BoxView as its content with HeightRequest greater than **allocated Height** of Scrollview, the application getting crashed with e.Exception {"A cycle occurred while laying out the GUI."}.

Same issue is occuring when loading Stacklayout with BoxView HeightRequest greater than **allocated Height** of Scrollview inside the ScrollView(Horizontal) .
![image](https://user-images.githubusercontent.com/59435340/155856268-24c9fda3-71bf-4adc-a770-5f73f12e01d4.png)

### Steps to Reproduce

1. Create a new Maui project
2. Add the following code as content to MainPage
`<ScrollView Orientation="Horizontal">`
    `<ContentView>`
        `<BoxView HeightRequest="700" BackgroundColor="Red"/>`
    `</ContentView>`
`</ScrollView>`
 
 or

`     <ScrollView Orientation="Horizontal">`
`        <StackLayout>`
`            <BoxView HeightRequest="700" BackgroundColor="Red"/>`
`        </StackLayout>`
`    </ScrollView>`
3.Run the sample

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.17763.0

### Did you find any workaround?
I haven't found a work around but i did found the root cause for the issue

**Root Cause**
Getting height constraint as Infinity from native call and allocated height of scrollview in CrossPlatfromMeasure in ContentView/StackLayout MeasureOverride() one after another infinitely.

**Comment by YuqinSong** [comment]
Verified Repro. Repro project is available:
[#4951.zip](https://github.com/dotnet/maui/files/8149861/4951.zip)

**Comment by rachelkang** [comment]
Starting to poke around this now - as mentioned, I'm noticing the crash only happens when the HeightRequest of a control is set to a super large value within a StackLayout/ContentView within a _horizontal_ ScrollView. If a smaller or no HeightRequest value is set or ScrollView orientation is different, there are no issues. This is also happening with Label, so it's not exclusive to BoxView.

A workaround is to set the ScrollView height to match the height of the control it's containing
