### ISSUE TITLE
Resolve services in ViewHandler is not working

### ISSUE THREAD

**Issue by javiercn** [dotnet/maui#5056]
As part of Blazor Maui we have a `BlazorWebViewHandler : ViewHandler<IBlazorWebView, ...>`.

As part of some work I was trying to Add a constructor to inject dependencies into the handler, but it seems that for some reason that is not working. I believe that is an scenario that should work.

To make sure it was not an issue with me trying to wire-up the dependencies, I tried to resolve the `IServiceProvider` (which should work) and resolve the dependency internally, but it also failed to resolve the IServiceProvider.

My understanding is that ViewHandler implementations are registered in DI and that resolving dependencies in them should be supported.

**Comment by PureWeen** [comment]
@javiercn Handlers aren't registered into the `ServiceProvider` they are registered into an internal collection that we use a factory to instantiate from. `Handlers` don't really fit the pattern of DI because they don't really have an `Interface` to `Implementation` type relationship.  `Handlers` are retrieved based on xplat elements that don't have `Service/Implementor` type relationship

We have an issue here to better create the handlers through `ActivatorUtilities` which should resolve ctor parameters
https://github.com/dotnet/maui/issues/4129

I do wonder though why your ctor parameters aren't resolving because we do have a fallback here
https://github.com/dotnet/maui/blob/cbace2dae4e69f35f2404e6414fe790a8267a623/src/Core/src/Platform/ElementExtensions.cs#L32 but I might have used the API incorrectly?

Here's a work in progress doc that talks about how resolution works a bit more
https://github.com/dotnet/maui/pull/4392

**Comment by PureWeen** [comment]
@javiercn your other option is from `SetVirtualView`, `Connect`, or `CreatePlatformView` to use MauiContext.Services to retrieve what you need.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2. We added the code about BlazorWebViewHandler: ViewHandler<IBlazorWebView, ...>, and no errors or warnings occurred. Not repro this issue.
