### ISSUE TITLE
Display chm Content in Webview

### ISSUE THREAD

**Issue by ThomasDallmeier** [dotnet/maui#5467]
### Description

Hello, please make it possible to display content from a chm file in the webview control. The chm file should be stored a a resource in the project. The call could be like 

`<webbrowser source="mk:@MSITStore:D:/sample.chm::/html/index.htm" />`

Thank you for your help

Thomas

### Public API Changes

no changes

### Intended Use-Case

I have many chm files with information about law. The would be so much easier to distribute then the many webhelp files.

**Comment by jfversluis** [comment]
Hey @ThomasDallmeier thank you for this suggestion! I'll be honest and say this is awfully specific. I had completely forgotten about chm files! I appreciate the fact that you still have a lot of them and they are no doubt still very useful, but since the format isn't supported anymore I highly doubt we will implement this anytime soon, also considering our other priorities right now. Your best chance is to either somehow find a way yourself to make it work or convert your chm files to something newer.

I'm going to close this one for now, but thank you for the suggestion!
