### ISSUE TITLE
Unable to build the latest MAUI (preview 14.0) project with VS 2022 for Mac Preview 7 (17.0 Preview, build 8001)

### ISSUE THREAD

**Issue by dsharkou** [dotnet/maui#5499]
### Description

Hi, MAUI team!

Probably it's not a place to post my question, sorry about that, but I'm interested in .Net MAUI and install the latest VS 2022 for Mac Preview 7 (17.0 Preview, build 8001), and I have an issue `.Net 6 Xamarin and MAUI projects are not supported with this version of Visual Studio. The included target frameworks are not supported: net6.0-ios|net6.0-maccatalyst`. I googled and found weird (more likely it's a joke) answer "[MAUI project support has been removed in VS for Mac 17.0](https://developercommunity.visualstudio.com/t/MAUI-projects-are-not-supported/1694129)".

What does it mean? How can we develop and run MAUI project now?
I can't even build the project

### Steps to Reproduce

1. Download the latest Visual Studio 2022 for Mac, Preview 7
2. Install MAUI workload, preview 14
3. Create project via cmd `dotnet new maui -n "MauiProject"`
4. Open this project in VS and try to build/deploy

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 14 (current)

### Affected platforms

iOS, macOS

### Affected platform versions

VS2022 for Mac Preview 7 (17.0 Preview, build 8001)

### Did you find any workaround?

Unfortunately haven't found

**Comment by dmccolloughOneGas** [comment]
@dsharkou You are unable to use VS for Mac 2022 Preview. Somebody decided that they didn't want to provide any functionality at this time to all of the VS for Mac users that want to get started with .NET Maui. 

Only way to have a supported IDE is to use Visual Studio 2022 for PC. Guess they don't understand that not everybody has access to a windows computer.

In the mean time, you can use a command prompt and build and run .Net Maui projects on a Mac.

Once you have created a .Net Maui project on your Mac.
Open Terminal
you can build the project by executing this command: dotnet build <ProjectName>.csproj -f net6.0-android

If you want to build for iOS or MacCatalyst, change the -f to net6.0-ios or net6.0-maccatalyst

If you want to build and run your project, its easiest to use the android emulator. Make sure it's already running and then execute the following command:
dotnet build <ProjectName>.csproj -t:Run -f net6.0-android

If you want to build and run on a iOS simulator, execute the following command
dotnet build <ProjectName>.csproj -tRun -f net6.0-ios -p:_DeviceName=:v2:udid=??????????????????????????

Follow the instructions in this link for finding the UDID of a iOS simulator on your Mac.
https://www.seanmcp.com/articles/find-an-ios-simulator-identifier/

Hope this helps.

**Comment by dsharkou** [comment]
@dmccolloughOneGas Thanks for your answer!
Is there any chance to see VS 2022 for Mac (not Preview) with built-in MAUI?

**Comment by dmccolloughOneGas** [comment]
Dzmitry,

I’m not sure I understand the question, I’ll answer to the best of my ability.

I develop / support Xamarin and Xamarin Forms applications for a living, that is my primary focus.

I have been trying to learn as much as I can about .NET Maui so that when it is released I can get started converting our applications.

Since I have no ability to use a IDE other than VS Code to try and play around with .NET Maui now, it’s making it very difficult to be prepared for the upcoming release.

I had removed VS 2019 for Mac from my Mac, had to re-install it when VS 2022 for Mac Preview 7 came out.

In my opinion, having VS 2022 for Mac (release version or preview version) installed without support for .NET Maui is just a waste of my computers disk space.

Until I see some kind of support for .NET Maui added back, I will not re-install it or do any further testing with it.

Let me know if that answered your question, if not. Please let me know what I missed.

Thanks

From: Dzmitry Sharkou ***@***.***>
Reply-To: dotnet/maui ***@***.***>
Date: Tuesday, March 22, 2022 at 4:37 PM
To: dotnet/maui ***@***.***>
Cc: "McCollough, David M." ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [dotnet/maui] Unable to build the latest MAUI (preview 14.0) project with VS 2022 for Mac Preview 7 (17.0 Preview, build 8001) (Issue #5499)

WARNING: This email was sent from an EXTERNAL source. Use extreme caution when clicking links or opening attachments. Please forward suspicious email to ***@***.***
________________________________

@dmccolloughOneGas<https://urldefense.com/v3/__https:/github.com/dmccolloughOneGas__;!!CDV5USbF!dRNJKl5Mr6fWEYUw2uRyovmiQbUmnuh417q6Jhu-AuStrfLfXRP5-0SlHCcN9Z93fAI09w$> Thanks for your answer!
Is there any chance to see VS 2022 for Mac (not Preview) with built-in MAUI?

**Comment by kristinx0211** [comment]
@dsharkou on mac, followed your repro steps, not repro this issue, using `dotnet new maui -n "MauiProject"` to create project from CLI, and then open project in vs to build is succeed. 
![image](https://user-images.githubusercontent.com/99457000/159611850-36540da1-6596-4a90-8fd3-7dc2bcdbe1e4.png)

**Comment by jfversluis** [comment]
Not a joke unfortunately, I will repeat my answer I just added to #5508 

>Two things are going on here:
>
> 1. As we're getting closer to GA, the GA version of Visual Studio for Mac will not have support for .NET MAUI. In fact, .NET MAUI projects will be actively blocked to not set any expectations, that is also what you are seeing here. The next preview (released together with VSMac GA) will continue to support .NET MAUI, just as happened with VS on Windows.
> 2. This code should not have been in this build yet though. It will be unblocked for the next preview until GA.
If you want to use it right now, either use the command-line tooling or maybe checkout VS Code and the Comet extension. Sorry for the inconvienence!

**Comment by dsharkou** [comment]
@jfversluis Thanks for your confirmation! I've got the idea.
Small question - do you have any expected release date for VS 2022 for Mac, and the date of VS2022 for Mac Preview (afterwards) release with .Net MAUI support?

**Comment by jfversluis** [comment]
I don't think anything has been made public about that at this time. The only thing I can point you to is the latest blog post: https://devblogs.microsoft.com/visualstudio/visual-studio-2022-for-mac-preview-7/

Keep your eye on the next one as it might have more information

**Comment by emorell96** [comment]
Maybe a dumb question, but if I have a MAUI project, can I build it on PC for a Mac? Is there any good docs on this? Not really for working on iOS but on MacCatalyst.

**Comment by jfversluis** [comment]
@emorell96 at this time it's not possible to build a macOS app through Windows.
