### ISSUE TITLE
Voiceover is not reading the search result after performing search operation.

### ISSUE THREAD

**Issue by Karan4495** [dotnet/maui#5698]
**GitHubTags:**
#.NET MAUI; #A11ySev2; #A11yMAS; #A11yTCS; #Benchmark; #iOS; #iPad; #WCAG1.3.1; #GH_.NETMAUI_IOS_Mar2022; #Info and Relationships​; #AINotInScope;

### Description

Voiceover is not reading the search result after performing search operation.

### Steps to Reproduce

1.Install and open ".NET MAUI" app.
2.Swipe till "search box".
3.Enter Recipe name in search box and search.
4.Verify Voiceover is not reading the search result after performing search operation or Not.

https://user-images.githubusercontent.com/100186395/161037501-ff1e3b55-0650-444c-b22d-1c63eae4ead0.mp4

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4(iPad)

### Relevant log output

```shell
Screen readers should read the search result after performing search operation. Voiceover should read how many records found with enter recipe name.
```

**Comment by v-longmin** [comment]
@Karan4495 Could you share your repro project for us? Thanks.

**Comment by rachelkang** [comment]
@Karan4495 Could you clarify the exact expected behavior? What exactly should the screen reader focus on after performing the search operation? Should it focus on the first search result? Should it read out all the search results? Should it focus on a new label that says "X results found"? Or is there some other expected behavior? Thanks :)

**Comment by Karan4495** [comment]
@rachelkang As per in bug voiceover should read how many result found and focus move to first search result.

**Comment by rachelkang** [comment]
@Karan4495 Thanks for clarifying! And just to make sure we're super clear on this - when exactly should the # of search results found be read / where exactly should the focus be at that point? Should we have a visual label for it that the focus goes to before the first search result? If there's no visual label necessary, where should the focus be when it is announced? Or should Voiceover read it after the focus moves to the first search result, before reading the first search result?

**Comment by PureWeen** [comment]
@Karan4495 do you have an example app that we can reference for this behavior? I've tested through a few of google apps (settings page) and in those cases after a search the focus always remains on the search box.  I noticed in our app it moves to the back button which does seem like a bug but it feels like the bug here is that focus should remain on the searchbox not that it should change focus to the results. Changing focus to the results seems like it would be unexpected for the user

**Comment by merriemcgaw** [comment]
@Karan4495 does this mean we can go ahead and close this issue and get it off the weekly overdue reports?

**Comment by merriemcgaw** [comment]
@rachelkang it doesn't look like I've got permission to assign this to @Karan4495 but that would be the quickest way to get the answer as to whether we are good to close this issue. I'm 90% sure we can, but I like to be sure. I have a meeting mid next week, so if there are issues you're waiting on the accessibility team to answer email the list to me this week.

**Comment by Karan4495** [comment]
As its Accepted behavior and after performing search operation focus remain on search field so closing the bug.
IOS Version: iPad(15.5) 
Added attachment for references.

https://user-images.githubusercontent.com/100186395/178661588-df3bbf46-9ccd-40f7-b3c7-209abbc93128.mp4
