### ISSUE TITLE
Hot reload not working after background color change of a control

### ISSUE THREAD

**Issue by ufancha** [dotnet/maui#5743]
### Description

Hot reload does not work after a background change of a control.

### Steps to Reproduce

1. add a BackgroundColor property to a control
2. remove the BackgroundColor property
3. hot reload the app 

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

all

### Did you find any workaround?

I have to hot restart the app.

**Comment by jfversluis** [comment]
Could you please provide a bit more info on the version of Visual Studio you are using exactly? Also have you made sure to press the Hot Reload button or you enabled the setting for perform a Hot Reload on save of the file?

**Comment by ufancha** [comment]
Hi @jfversluis i am using Version 17.2.0 Preview 2.1.  Yes, i hit the Hot Reload button and it doesn't work. when i try to change the BackgroundColor property to other values, the Hot Reload works, but when i remove the BackgroundColor property, the last Background color of the control stays there until a Hot Restart.

**Comment by shimingsg** [comment]
verified button and label not repro with VS 17.2.0 Preview 3.0 [32331.426.main] on Android

**Comment by drasticactions** [comment]
The "Hot Reload Button" is connected for C# Hot Reload and doesn't do anything specific for XAML Hot Reload, so pushing it won't do much.

@shimingsg I think the issue here is the user added a background color in XAML when there was none, then removed it. And it didn't change back to what it was before. 

AFAIK this is not a XAML Hot Reload issue, not directly anyway. When you add a background color, it's set as a property on that control. It sets it back to the "default" on that control (most likely null) when you remove it. You can most likely replicate this by doing the same actions from C# code behind. So the control is being properly set to whatever color it was, but MAUI is not redrawing that control once the empty value is applied.

**Comment by Redth** [comment]
The behaviour is a bit different in MAUI.... Removing the value or making it null/default is effectively a no-op, so the expectation is you need to set it to a specific color or have a style somewhere that sets an explicit color if you ever change the default and want to change it again.
