### ISSUE TITLE
BlazorWebView CSS is only applied to Windows app but not Android 

### ISSUE THREAD

**Issue by sturlath** [dotnet/maui#5750]
### Description

I have [this code base ](https://github.com/sturlath/Maui) (file new project today from 17.2.0 preview 2.1 on Windows) where I added some CSS to try out and it works fine when run on Windows Machine but not if I try it out on a Android device

Looks good on Windows
![image](https://user-images.githubusercontent.com/2386572/161304408-577369c1-da74-4753-95c6-1691c67d016e.png)

But this is how it looks on my Android device (Samsung Galaxy S7 (SM-G930F))
![image](https://user-images.githubusercontent.com/2386572/161303011-11130123-1110-4ffe-9b92-7d8f2fe5debc.png)

### Steps to Reproduce

Try out my [code ](https://github.com/sturlath/Maui) on an Android device.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8.0.0 (API 26)

**Comment by jfversluis** [comment]
Thanks for the report and linking your code, however either your repo doesn't exist or it's set to private :)

**Comment by sturlath** [comment]
Sorry @jfversluis it was private 🙈 you should now be able to view it.

**Comment by kristinx0211** [comment]
verified repro with 17.2.0 Preview 2.1.

**Comment by janseris** [comment]
Reproduced VS 2022 Professional 2022 (64-bit) - 17.2.0 Preview 2.1

**Comment by SteveSandersonMS** [comment]
@sturlath Thanks for the report. To narrow this down, could you please try the following?

* Try running this in the Android simulator with the newest device you can. It might be a limitation in CSS support on your Android version.
* Try to reproduce this using the same HTML/CSS plain MAUI WebView (not BlazorWebView). Does it also happen in that case?

**Comment by sturlath** [comment]
I works on a Nexus 10 - API 30 emulator I had (so I guess it should work on others)
![image](https://user-images.githubusercontent.com/2386572/161614370-88e52ffc-3040-4721-a984-6fe44d1e4852.png)

I´ll try to create a new project (with same CSS/HTLM) and see how that looks on the phone (I´m guessing you are interested in that right?). I´m sure I can manage to find it out in the next few days. Any change you could point me to a example repo that I could then plug my CSS/HTLM in?

**Comment by janseris** [comment]
When built for Pixel 5 API 30 (Android 11), it cannot be installed on Sony Xperia 5.
Signed APK shows "application cannot be installed" after attempting instalation.
Unsigned APK shows "error during package analysis" when opening the apk.

**Comment by janseris** [comment]
Running the application on Nexus 10 Release build yields the following result:

![image](https://user-images.githubusercontent.com/64279914/161629574-f47a0cf4-33e0-449d-be6d-040cea3a36c0.png)

`[System] Uncaught exception thrown by finalizer
[System] java.lang.IllegalStateException: Warning: Router objects should be explicitly closed when no longer required otherwise you may leak handles.
[System] 	at UM.finalize(chromium-TrichromeWebViewGoogle.apk-stable-410410686:4)
[System] 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
[System] 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
[System] 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
[System] 	at java.lang.Thread.run(Thread.java:923)
[System] Caused by: java.lang.Exception: AutocloseableRouter allocated at:
[System] 	at UM.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410686:7)
[System] 	at EP.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410686:6)
[System] 	at org.chromium.content.browser.framehost.RenderFrameHostImpl.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410686:10)
[System] 	at org.chromium.content.browser.framehost.RenderFrameHostImpl.create(chromium-TrichromeWebViewGoogle.apk-stable-410410686:1)
[System] 	at J.N.MjidYpBx(Native Method)
[System] 	at org.chromium.content.browser.webcontents.WebContentsImpl.r0(chromium-TrichromeWebViewGoogle.apk-stable-410410686:3)
[System] 	at K7.g(chromium-TrichromeWebViewGoogle.apk-stable-410410686:5)
[System] 	at com.android.webview.chromium.WebViewChromium.postMessageToMainFrame(chromium-TrichromeWebViewGoogle.apk-stable-410410686:4)
[System] 	at android.webkit.WebView.postWebMessage(WebView.java:1971)
[System] 	at crc64d693e2d9159537db.WebKitWebViewClient_JavaScriptValueCallback.n_onReceiveValue(Native Method)
[System] 	at crc64d693e2d9159537db.WebKitWebViewClient_JavaScriptValueCallback.onReceiveValue(WebKitWebViewClient_JavaScriptValueCallback.java:30)
[System] 	at X6.a(chromium-TrichromeWebViewGoogle.apk-stable-410410686:1)
[System] 	at org.chromium.android_webview.AwContents.w(chromium-TrichromeWebViewGoogle.apk-stable-410410686:1)
[System] 	at xr.run(Unknown Source:4)
[System] 	at android.os.MessageQueue.nativePollOnce(Native Method)
[System] 	at android.os.MessageQueue.next(MessageQueue.java:335)
[System] 	at android.os.Looper.loop(Looper.java:183)
[System] 	at android.app.ActivityThread.main(ActivityThread.java:7656)
[System] 	at java.lang.reflect.Method.invoke(Native Method)
[System] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[System] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**Comment by javiercn** [comment]
I installed the apk on the emulator and it seems to be working as expected.

I would suggest to anyone running into this issue that they first check to make sure that the files are inside the generated APK as a first step and if that's not the case, examine the binlog from the publish output.

**Comment by sturlath** [comment]
So much going here and so little time (and knowledge og Maui og both the webviews).

If somebody can change the code using webview I can run it on my device else Im not sure I can find time to do this until next weekend (can test the code np). And if you like logs or something else just let me know what to send.

Sorry for not having more time atm..

**Comment by janseris** [comment]
> Thanks everyone for commenting here.
> 
> We're getting a wide range of reports - some saying that there's a CSS problem, some that there's a problem with static images, some saying the apps don't even install, and others saying everything works fine.
> 
> In order for us to take action, we really need these different scenarios to be described in full detail so that we can try to reproduce them.
> 
> **If you are able to reproduce one of the problems above, could you please file a new issue, and give full repro steps?** This means providing the code that reproduces the issue as well as the deployment steps (e.g., to which device, and how it's being deployed).

I have provided all that info for my reports.

**Comment by janseris** [comment]
@SteveSandersonMS 
Yes, right - I tried the exact code posted by the issue creator without any modification.
I opened it in Version 17.2.0 Preview 2.1 just as issue creator and tried to run it just as he did - Windows and Android.
> I have [this code base](https://github.com/sturlath/Maui)

I just tried to reproduce the issue as is.

**Comment by TanayParikh** [comment]
> @TanayParikh Might this issue be a duplicate of something you looked into?

I don't believe so. Though this may be related to https://github.com/dotnet/maui/issues/7468 that @MackinnonBuck was looking into.

**Comment by javiercn** [comment]
@TanayParikh giving this to you.

Feel free to close if no further action is needed, since we haven't heard back.

**Comment by TanayParikh** [comment]
Is anyone still experiencing this issue in 7.0 RC2?
