### ISSUE TITLE
Shell.TitleColor is dark on top level FlyoutItem but white on secondary page

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#5757]
### Description

<img width="399" alt="image" src="https://user-images.githubusercontent.com/41873/161318331-9ae8b2a8-7170-45d2-8e75-f803b634bd2e.png">

Second page:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/41873/161318612-d79b4382-41df-409b-9f97-c0f760562391.png">

These are the relevant styles from https://github.com/davidortinau/ControlGallery/

```xaml
<Style x:Key="BaseStyle"
           TargetType="Element">

        <!-- BackgroundColor is the nav bar background color -->
        <Setter Property="Shell.BackgroundColor"
                Value="{StaticResource Primary}" />
        
        <!-- ForegroundColor is the icons and hamburger button -->
        <Setter Property="Shell.ForegroundColor"
                Value="{StaticResource Text_Dark}" />
        
        <!-- TitleColor is the text in the nav bar -->
        <Setter Property="Shell.TitleColor"
                Value="{StaticResource Text_Dark}" />
        
        <Setter Property="Shell.DisabledColor"
                Value="Green" />
        <Setter Property="Shell.UnselectedColor"
                Value="#CC0000" />
        <Setter Property="Shell.NavBarHasShadow"
                Value="False"/>
    </Style>
    <Style BasedOn="{StaticResource BaseStyle}"
           ApplyToDerivedTypes="True"
           TargetType="FlyoutItem" />
```

For reference these are the colors:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/41873/161318911-11a97117-520c-4131-9596-f16436295fd3.png">

### Steps to Reproduce

run ControlGallery on Android

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 30

**Comment by Mephisztoe** [comment]
I am on the current RC1 branch and experience a similar behavior:

This is my configuration for Shell.TitleColor:
```xaml
<Setter Property="Shell.TitleColor"
                Value="{AppThemeBinding Light={StaticResource White}, Dark={StaticResource PrimaryLight}}" />
```

When my android is set to darkmode, the TitleColor is correctly set through AppThemeBinding/Dark (i.e. whatever color I set here; in this case PrimaryLight which is #E8EFFF). When I set something like black here (#000000), the TitleColor is correctly set to black.

However, when switching to lightmode, the TitleColor seems NOT to be set through AppThemeBinding/Light. While trying to find out what's happening here, it even seems as if there is a problem with the keyword "White". Because when setting the Light color to something else (like "Grey1" which is in my case #FAF9F8), the TitleColor is correctly set in Light Mode...

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Not repro on Android with above project.
![image](https://user-images.githubusercontent.com/97647558/167247942-47df53c2-333a-469d-bb0f-d6402a890786.png)
![image](https://user-images.githubusercontent.com/97647558/167247952-a47f70e3-ad59-450f-a6c8-98acf7e874bc.png)

**Comment by samhouts** [comment]
Doesn't reproduce on 6.0.300-rc.4.5739
