### ISSUE TITLE
Publishing a Windows app doesn't produce an msix

### ISSUE THREAD

**Issue by eerhardt** [dotnet/maui#5884]
### Description

When I try to publish a Maui Windows app, it doesn't produce an msix. My understanding is that by default a Maui Windows app is a "packaged" app. So publishing the app for Windows should produce an msix.

### Steps to Reproduce

1. `dotnet new maui`
2. Temporary workaround to bring in the 1.0.2 windows sdk. Add the following to the .csproj:
```xml
	<ItemGroup>
	  <PackageReference Condition="$(TargetFramework.Contains('-windows'))"
	                    Include="microsoft.windowsappsdk"
						Version="1.0.2" />
	</ItemGroup>
```
3. `dotnet publish -f net6.0-windows10.0.19041.0 -c Release`

Inspect the `publish` folder. It should contain an msix file.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All Windows

**Comment by Redth** [comment]
@marb2000 @mattleibow let's discuss this in our next sync again.

We could add some opinionated default properties in MAUI but as we discussed maybe it's better to get them into the WindowsAppSDK so that the experience is consistent with and without MAUI projects using WASDK.

One idea is that we could condition these opinionated defaults based on dotnet build vs msbuild if that's a concern.

**Comment by mattleibow** [comment]
Maybe somethings like this could help:

```
<PropertyGroup Condition=" '$(Target)' == 'Publish' And '$(MSBuildRuntimeType)' == 'Core' And '$(Configuration)' == 'Release' ">
    <PublishAppxPackage Condition=" '$(PublishAppxPackage)' == '' ">True</PublishAppxPackage>
</PropertyGroup>
```
