### ISSUE TITLE
How to set a content page in MAUI full screen

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#5968]
### Description

I used this link:
https://stackoverflow.com/questions/71361984/how-to-set-a-contentpage-in-maui-full-screen-or-immersive
and is not open in full screen.

### Steps to Reproduce

1. Create MAUI app.
2.You could add the code below in MainActivity.cs of Maui project.

 protected override void OnCreate(Bundle savedInstanceState)
{
    base.OnCreate(savedInstanceState);
    Platform.Init(this, savedInstanceState);

    this.Window.AddFlags(WindowManagerFlags.Fullscreen);      
}
3.In ContentPage, it provides a easy way to hide the Bar to do the same thing with full screen via set the HasNavigationBar property to false.

<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
         xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
         x:Class="MauiApp1.MainPage"
         BackgroundColor="{DynamicResource SecondaryColor}"
         NavigationPage.HasNavigationBar="False">

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 14 (current)

### Affected platforms

Windows

### Affected platform versions

..

### Did you find any workaround?

NO

**Comment by jfversluis** [comment]
Hey @danies8 I appreciate you trying out our product and providing feedback, however it seems that a couple of these are "I found this link {link} and it's not working?" that is not really what these GitHub issues are for.

That something is not working can be for a lot of reasons, especially at this stage, since .NET MAUI is still in preview. Things are still changing. You're welcome to ask these questions on Stack Overflow or in the Discussions tab here and if you find that it is still not working and are convinced that the reason it is not working is because of a bug in our codebase, that is the moment to open an issue 😄 

Additionally, whether you are asking a question or reporting a bug, it is very helpful to provide more info like: what is not working? Does it give you an error? An exception? If yes, what is the message? What steps did you already take to try and fix this yourself? Etc. etc.

I love to help wherever I can, and I know the rest of the team as well, but this causes some noise in our issues list and distracts us from actually working on those to make our product more complete, stable and a joy to work with. I hope you understand.

Having all that said, I'm going to close this one for now. Let us know if you find something that has you convinced that it should actually be working but doesn't and tell us why. 

Thanks

**Comment by danies8** [comment]
Look how is open when the code is set, not with full screen.
I attached code
![image](https://user-images.githubusercontent.com/1079689/162727999-3494ca1c-8c70-43e0-993f-3bc5eb79fee0.png)
[Full Screen.zip](https://github.com/dotnet/maui/files/8463489/Full.Screen.zip)

**Comment by jfversluis** [comment]
The code in your link refers to Android, this screenshot shows it running on Windows. 

The code posted in the Stack Overflow question will only make it work for Android.

**Comment by danies8** [comment]
Are you going to implement this feature in window?
