### ISSUE TITLE
Externally hosted images cannot load on hybrid Android apps

### ISSUE THREAD

**Issue by Alby-o** [dotnet/maui#5986]
### Description

When loading an image from an external server, the image will not load on Android. This issue does not occur when running on a Windows machine. iOS / Mac is untested

### Steps to Reproduce

1. Create a new MAUI hybrid blazor project
2. Insert the image `<img src="https://avatars.githubusercontent.com/u/29965798?s=400&v=4" alt="avatar" />`
3. The image will not load

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Targeting sdk version 31, likely affects other versions too

### Relevant log output

```shell
Chrome inspector:

Failed to load resource: net::ERR_NAME_NOT_RESOLVED
```

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.2.0 Preview 2.1 [32317.152]. Repro on Android. Sample Project: [5986.zip](https://github.com/dotnet/maui/files/8469209/5986.zip)

**Comment by Alby-o** [comment]
Loading the image on the chrome browser on the emulator works 
![image](https://user-images.githubusercontent.com/29965798/163068758-96688194-3a0e-41d3-8c45-2ffd279ff621.png)

**Comment by codeaphex** [comment]
Got the same problem with a native android app.
I also noticed that in the emulator the CounterLabel doesn't show the value after clicking the button, which is weird since the whole text is updated.

| Windows | Android Emulator |
| -- | -- | 
| <img src="https://user-images.githubusercontent.com/39407721/163071726-769497ee-acaa-45f8-8841-de2ea2c2c848.png" width="300"> | <img src="https://user-images.githubusercontent.com/39407721/163074987-24805a85-7ee1-4a37-bd62-31107ef3dba8.png" width="300"> |
| Android Emulator | Android Device |
| <img src="https://user-images.githubusercontent.com/39407721/163073102-10c722fe-05d3-4fbf-8721-4e3d3c43ab0e.png" width="300"> | <img src="https://user-images.githubusercontent.com/39407721/163075128-ae2ff0ae-adb3-43e3-b538-2c6753d46bde.jpg" width="300"> |

**Comment by javiercn** [comment]
@Alby-o this is an issue in the Android Web view configuration.

We added the ability to configure this yourself in RC2 I believe.

@mkArtakMSFT @SteveSandersonMS @Eilon we probably need to make a decision here on what our default should be. However, I think it should be enabled by default for consistency with other platforms.

**Comment by Alby-o** [comment]
@javiercn Thanks for your response!

I see there is the BlockNetworkImage setting in BlazorAndroidWebView.Settings, however I am unsure of how to configure these settings from within my app. Is there any documentation on how to do so?

**Comment by SteveSandersonMS** [comment]
I just tried this with the latest RC release of MAUI and it worked without setting any extra config. That is, when running on Android, the `<img>` pointing to an external image on the web did load and display the image.

So I think there's no specific action to take, unless @Alby-o can still repro this problem on a new project on RC.
