### ISSUE TITLE
The SearchHandler is not rendered on Windows 

### ISSUE THREAD

**Issue by RafiHenig** [dotnet/maui#6036]
### Description

Windows does not seem to display SearchHandler while it does on Android and iOS

![bug](https://user-images.githubusercontent.com/40548296/163112090-a323d945-b099-4178-8883-1125195b8a50.jpg)

### Steps to Reproduce

MainPage.cs

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiAndIdentityServer.Pages.MainPage"
             xmlns:handlers="clr-namespace:MyMauiApp.Infrastructure.Handlers"
             BackgroundColor="{DynamicResource SecondaryColor}" Title="Index">

    <Shell.SearchHandler>
        <handlers:AppSearchHandler  Placeholder="Enter search term"
                                    ShowsResults="true" 
                                    SearchBoxVisibility="Expanded"/>
    </Shell.SearchHandler>

</ContentPage>
```

AppShell.cs

```
<Shell xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pages="clr-namespace:namespace:MyMauiApp.Pages"
             x:Class="namespace:MyMauiApp.Pages.AppShell"/>
    
   <ShellContent Title="Index"  Icon="home.png"  ContentTemplate="{DataTemplate pages:MainPage}" />

</Shell>
```

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

**Comment by pierre01** [comment]
I have the same issue!

**Comment by VincentBu** [comment]
repro on Windows:
![image](https://user-images.githubusercontent.com/44959937/164649852-6a5c1f98-be3c-4260-a538-335eb5dc51ff.png)

Search handler works fine on Android. Here is the screenshot:
![image](https://user-images.githubusercontent.com/44959937/164648916-2a7d8318-72dd-4aec-abf9-f5dc3b4c7ebe.png)

**Comment by PureWeen** [comment]
The code for the SearchHandler that I copied over from Forms is [here](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Handlers/Shell/ShellItemHandler.Windows.cs#L217-L257). I have no idea how well it works. It's just using the [AutoSuggestBox](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.navigationview.autosuggestbox?view=winui-3.0) property on `NavigationView`

Most likely this code should be moved into ShellHandler.Windows.cs and wired up to the mapper there.

The `SearchHandler` is a property that can be set on whatever the currently active page is so you can fire the Handler Update from [here](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Shell/Shell.cs#L1184)

```C#
Handler?.UpdateValue("SearchHandler") //This fires an update on the `ShellHandler`
```

There's a lot of pixel pushing we currently do against `NavigationView` in order to get it to work with the AppBar. I'm hoping adding the AutoSuggestBox just works and everything adjusts accordingly :-)
