### ISSUE TITLE
Maui and Grpc cannot work together on MacOS? 

### ISSUE THREAD

**Issue by kucint** [dotnet/maui#6057]
### Description

Hi,
using asp and maui in a single project results in "unsupported" runtime error message.

Questions:
1. why I get this error? Isn't grpc supposed to be independent from maui?
Grpc itself is supported under Windows, Linux and MacOS.
3. how to fix it?

I have created similar issue on Community Hub long time ago, no answer till now:
https://techcommunity.microsoft.com/t5/app-development/maui-and-grpc-cannot-work-together-on-macos/m-p/3046251

### Steps to Reproduce

1. create a standard maui project (from template).
2. remove iOS and Android from TargetFrameworks. Only windows and MacCatalyst shall stay (I want to build a cross platform desktop app).
`<TargetFrameworks>net6.0-maccatalyst</TargetFrameworks>`
`<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net6.0-windows10.0.19041</TargetFrameworks>`
4. add grpc nuget reference to the project
`<PackageReference Include="Grpc.AspNetCore" Version="2.41.0" />`
5. build the project.
Following error will be displayed:
1>C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(427,5): error NETSDK1082: There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'maccatalyst-x64'.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacCatalyst 

### Did you find any workaround?

no

**Comment by drasticactions** [comment]
I don't think your issue is MAUI specific; it's due to the ASP.NET Runtime Pack not existing (or not being found) for the .NET 6 Mac Catalyst SDK. You would hit this same issue if you created a new Mac Catalyst app without MAUI (`dotnet new maccatalyst`) and tried referencing it there.

I would go to https://github.com/xamarin/xamarin-macios and ask them directly about it.

**Comment by Eilon** [comment]
Indeed, @drasticactions is spot on.

This is tracked in the ASP.NET Core repo here: https://github.com/dotnet/aspnetcore/issues/35077

**Comment by kucint** [comment]
I see.
thanks for info

**Comment by Falco20019** [comment]
Since https://docs.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?view=aspnetcore-6.0#aspnet-core-grpc-server-requirements lists macOS as supported platform, I assume the issue is targeting `net6.0-maccatalyst` instead of only `net6.0`.

@Eilon can you confirm, that using the generic TFM would lead to usage of the correct runtime pack?

**Comment by Eilon** [comment]
@Falco20019 the runtime pack that is chosen depends on what runtime the code ends up running on. I do think that net6.0-maccatalyst is different from net6.0-macos, so if something is compatible with 'macos' then it won't automatically run on 'maccatalyst'.

**Comment by Falco20019** [comment]
Maybe @kucint had the same assumption than me and mistook that TFM.

So if his target as written in the initial post was to have Windows and macOS, correcting the TFM from net6-maccatalyst to net6-macos might solve the problem. Thanks for the clarification.

**Comment by kucint** [comment]
@Eilon @Falco20019 I already did this experiment and it did not help....

**Comment by Falco20019** [comment]
In response to https://github.com/dotnet/aspnetcore/issues/35077#issuecomment-1131355039 to not trigger notifications for all users:

I'm really not sure where your reference onto `Microsoft.AspNetCore.App` comes from. None of the referenced packages have it.

Are you sure that you don't have it left in one of your two csproj files? In this case, you would not even need to split it up into two packages since all of those have `netstandard2.1` versions and don't framework reference `Microsoft.AspNetCore.App`.

**Comment by kucint** [comment]
I am rather sure, I double checked it now.

Have a look into attached cs-project files:
[projects.zip](https://github.com/dotnet/maui/files/8727490/projects.zip)

included client projects:
- BVLabApp -> this is the Maui client app
- Interop.DataAnalysisService.Grpc -> this is a lib that is referenced by BVLabApp client app. it uses `Grpc.Net.Client`

additionally I send you as well server project
- Grpc.DataAnalysisService -> ASP grpc server app -> this one uses obviously `Grpc.AspNetCore`

protobuffers are shared between sever (Grpc.DataAnalysisService) and client (Interop.DataAnalysisService.Grpc)

I appreciate a lot your help. Thanks!

**Comment by kucint** [comment]
@Falco20019 
I have built a test application from scratch, that simulates my problem.
I have to admit that the problem is gone (at least partially).

- **MAUI app referencing grpc client in a second library -> builds and works as expected**.
- MAUI app directly referencing grpc in the same project -> causes some build problems that I do not understand.

Anyway, I have a "work around" that functions.
Now I have to find why my production app fails and where the undesired reference comes from.

Thanks for your very appreciated help!
Best.
