### ISSUE TITLE
Label not getting resized to the change in Text length on Android

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#6066]
### Description

Label not getting resized to the change in Text length on Android.

As the Text length changes, it is expected that the Label should resize itself to show the updated text.

_Note: Works fine on Windows but could not be able to test it on iOS/Mac Catalyst._

### Steps to Reproduce

1. Create a new .NET MAUI App project from the default template
2. Set the target platform as Android
3. Build and run the project
4. Hit the `Click me` Button repeatedly such that the Counter value moves into double-digit
5. Once it reaches that threshold, the label text disappears as it is not resizing to the content

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 14

### Affected platforms

Android, I was *not* able to test on other platforms

### Affected platform versions

Android 31.0

### Did you find any workaround?

Nope

### Relevant log output

```shell
NA
```

**Comment by matt-goldman** [comment]
I've encountered this problem too, and can confirm the issue does not occur on Windows.

I found that forcing the UI to update by changing other things, eg entering some text in an Entry, causes it to re-render and then it displays as expected.

I tested on Mac and iOS too, and wasn't able to confirm whether this issue occurs due to a bigger blocking issue: https://github.com/dotnet/maui/issues/6082

**Comment by PureWeen** [comment]
Duplicate https://github.com/dotnet/maui/issues/5717
