### ISSUE TITLE
skia engine in flutter

### ISSUE THREAD

**Issue by reader-man** [dotnet/maui#61]
Hi,
 I hope that this project starts with re-thinking of how skia is used in flutter, or other 2d/3d engines that use hardware acceleration, and does not need to use native OS controls, but simulate them.

this will minimize the OS Bindings, speed up the App, give ease for making the app run everywhere even in IoT/Web/TV/Watch later on, or on new OS(s)

We love MS Technologies, but as what happened to nokia, codac, if u don't up and running with the competition, you will be late.

and this is a new technology, that can be done from the ground up, to not have the same java ui controls mistake, of trying to use native controls and wrap them.

Regards.

**Comment by Amine-Smahi** [comment]
The idea is amazing, Hope the .NET folks think of this seriously.

**Comment by dhindrik** [comment]
There are a lots of reason to use native controls. Accessibility for example. It is faster to get updates out when the platforms are adding new feature because you don't have to recreate them.

But it would probably be possible to crrate bindings to the Flutter libraries and the create a backend to Maui based on them. But I think that should be created by the community.

**Comment by JohnGalt1717** [comment]
This is a must.  Yes, use the native controls inside your rendering just like say KendoUI, or any web library uses.  But skia the whole thing and give us a web version that goes with it. No more render differently per platform problems.

And honestly, it would be way better to just adopt flutter and put in C# and do to flutter what Edge is doing to Chromium which clearly has Google scared.  If you put C# in and the xamarin tooling for building cross platform components along with the Xamarin emulators and best yet, gave us free online emulators and build to store for iOS so we don't need a mac at all, you'd have an enormous win.  

the Xamarin bottom cross platform tooling because everyone ends up writing custom per platform code which is pretty awful in Flutter and requires serious platform chops in other languages. With Xamarin, none of that is needed which would drive people to use Microsoft Flutter instead of google dart flutter while still benefiting from the flutter rendering engine.

The later, because if Microsoft doesn't provide a path where developers never need a Mac, Windows is a non-starter for most end user developers and thus Windows native apps are a non-starter.  If you have to have a mac anyhow, you're not going to have a mac and a pc and you'll leave windows to the web browser and windows apps die and windows becomes a glorified browser platform like Chrombooks but costing more.  This has to be solved. The best way to do so is to just put ios emulators in the vs.net subscription and be done with it (or better yet vs code support).

Microsoft Flutter gives you all of Google's hard work, with Xamarin and all of that tooling which completely subverts google and MS get a chance in End User development again on the back of Google's work.

Win/Win.

**Comment by EydenJones** [comment]
They need to think about this and give a good reason why they choose the chosen strategy
I'm a fan of the flutter approach. I believe it's faster and less work / maintenance in the long run.

To quote Adam Pedley
> The last time my client cared for a native control was in 2015. After that I was mostly guided by UI designers who didn’t care, and now has gotten to the point where I have to spend time erasing the native look and feel from my apps. Its an industry trend though. Look at Facebook, Instagram etc. They all look almost identical on every platform.

**Comment by dhindrik** [comment]
> They need to think about this and give a good reason why they choose the chosen strategy
> I'm a fan of the flutter approach. I believe it's faster and less work / maintenance in the long run.
> 
> To quote Adam Pedley
> 
> > The last time my client cared for a native control was in 2015. After that I was mostly guided by UI designers who didn’t care, and now has gotten to the point where I have to **spend time erasing the native look and feel from my apps.** Its an industry trend though. Look at Facebook, Instagram etc. They all look almost identical on every platform.
> > https://xamarinhelp.com/saving-xamarin-forms/

Why not use Flutter?

**Comment by EydenJones** [comment]
> > They need to think about this and give a good reason why they choose the chosen strategy
> > I'm a fan of the flutter approach. I believe it's faster and less work / maintenance in the long run.
> > To quote Adam Pedley
> > > The last time my client cared for a native control was in 2015. After that I was mostly guided by UI designers who didn’t care, and now has gotten to the point where I have to **spend time erasing the native look and feel from my apps.** Its an industry trend though. Look at Facebook, Instagram etc. They all look almost identical on every platform.
> > > https://xamarinhelp.com/saving-xamarin-forms/
> 
> Why not use Flutter?

I do, but i love C# so much :)

**Comment by legistek** [comment]
> But it would probably be possible to crrate bindings to the Flutter libraries and the create a backend to Maui based on them. But I think that should be created by the community.

If the community made a Maui platform to interface with Flutter, wouldn't you're just be trading iOS/Android/UWP design choices for that of Flutter?

**Comment by dhindrik** [comment]
> > But it would probably be possible to crrate bindings to the Flutter libraries and the create a backend to Maui based on them. But I think that should be created by the community.
> 
> If the community made a Maui platform to interface with Flutter, wouldn't you're just be trading iOS/Android/UWP design choices for that of Flutter?

I would not use it, or maybe for specific cases depending on what clients designers want. Maybe it would be a good way to create it as a Visual so you easy can apply it to specific elements.

**Comment by yurkinh** [comment]
Actually it is already implemented with [Comet.Skia](https://github.com/Clancey/Comet/tree/dev/src/Comet.Skia) 
The question is: Will MS team use it (merge it) with MAUI?

**Comment by reader-man** [comment]
Weather MS, makes bindings to flutter UI Controls, or build upon skia engine or other 2d/3d engines, the main result is one.

the earlier might be faster in development but reliant on something else, and the later, might be slower in development, but non reliant on anyone else .

but the end result, MS cares more on easing development, so developers use MS Cloud Functionality, and by jumping from the wrongness that java have been made with its first UI controls that depend on each platform controls and their problems, to a base model, that does not rely on any platform specifics, and just giving themes for each platform, will make its development free from any dependencies/back-word support, and really shine in the speed/graphics side.

and as Adam Pedley said, big companies are having one theme for their apps, no matter what platform.

also, instead of having every release of this technology, adding more functionality, that is only adding more bindings to current device controls, MS can have its own controls, and speed up the feature additions.

mobiles/devices/IoT are getting faster GPUs every year, and the UI is slow in utilizing that huge power/efficiency/fidelity, which will ease the move to VR devices, by compiling the engine to that device.

and as we can see flutter in very small time, has eaten a lot of the market share, and it deserves that.

But as a C# developer, a .net/.net core developer, its still much better that dart.

So, MS you have this as an open source, just start the road map, and the community will help.
As a comment from loving heart: Don't be late as u did with internet explorer.

Regards.

**Comment by libin85** [comment]
> > They need to think about this and give a good reason why they choose the chosen strategy
> > I'm a fan of the flutter approach. I believe it's faster and less work / maintenance in the long run.
> > To quote Adam Pedley
> > > The last time my client cared for a native control was in 2015. After that I was mostly guided by UI designers who didn’t care, and now has gotten to the point where I have to **spend time erasing the native look and feel from my apps.** Its an industry trend though. Look at Facebook, Instagram etc. They all look almost identical on every platform.
> > > https://xamarinhelp.com/saving-xamarin-forms/
> 
> Why not use Flutter?

I think for the same reason why we have C# instead of Java. Its a choice. I have been personally using Xamarin for close to 6 years now. Xamarin was absolutely a revolution when it came out, we were able to make native UI in a cross-platform way. But as a community, we need to acknowledge that the industry have moved on, and the business don't care anymore of native looking UI for each platform. I am not claiming we should ditch the native controls. But adding skia controls would give a lot of options for our developers pick the right tool for their needs.

**Comment by adamped** [comment]
Since I'm been quoted on an almost 2 year old post, I thought I would provide my most recent opinion, though not much has changed.

Xamarin.Forms and MAUI are built with Native Controls in mind. I have seen no indication that Microsoft is going to change this approach with this product line. They are providing emulated features or controls to fill in gaps, so they don't always have to settle with lowest common denominator of all platforms, e.g. a Checkbox. But this is the extent they seem to be going at the moment.

**Emulated Controls and Canvas**

I'm a big fan of emulated controls. From my perspective it offers these benefits:

1) I am not restricted to the limitations or quirks of the platforms
2) Flutter has many accessibility options built in, so there is no need to compromise.
3) We don't get all the latest UI platform features instantly, but emulated controls can go beyond platform features too.
4) It's pixel perfect on every platform. I built an app recently in Flutter. I just tested it on Android locally, ran it through AppCenter to get the iOS version. Worked first time on iOS, pixel perfect. It was amazing.
5) Need new platform support? Create the Flutter Shell, Skia Engine and Event Bindings and now every Flutter app runs pixel perfect on that platform. The option to expand easily is there.

It took a lot of grinding from Flutter to reach that point, but they have a solid control/widget set and I haven't yet come across anything personally that I have missed from native controls. Platform APIs continue to be accessible instantly as your base project is native itself. I also use Visual Studio Code, so I get a familiar IDE.

**The S Curve of Innovation**

I originally heard this from Jim Keller, when he was talking about micro processors but it applies to most innovation. The S-Curve of innovation means as one technology reaches its maturity, the innovator starts below the capabilities of mature product but enters a growth phase that takes it higher.

This is how I see MAUI vs Flutter. XF/MAUI is entering it's final maturing phase, Flutter is in its growth phase.

**State Management and MVU**

MAUI has this MVU approach, that honestly I haven't looked into in great depth, but during my initial look into an MVU approach for Xamarin.Forms, renderers and native controls proved to be the blockage that couldn't be passed. If you have a native control, that control has state. That state needs to be bound or changes sent upwards, and your app state needs to be passed down.

In a true MVU approach, the view is generated each time and pushed down, but with Native Controls, they can change their state and that has to be pushed up. We can do all kinds of differential analysis and changes to manage this, but the complexities are challenging. I am not sure how MAUI is actually planning on getting around this. I am not sure they have considered what this approach actually entails. I will be impressed if they managed to solve a bi-directional state conflict resolution for this uni-directional state pattern.

Flutter has events that get sent back, then you push out a view again, but the view's state itself doesn't change until you do an update.

**C# vs Dart/Swift/Kotlin**

There are benefits to either approach. I love the C# direct to platform APIs, however I also love the fact I have access to every native package, gradle config etc in Flutter without going through Xamarin's binding and build tools. Both offer advantages, but if you are willing to learn a little Swift and Kotlin, you can still write most of your app in Dart, and you get access to everything native. Figuring out how to translate gradle.config to Xamarin builds is sometimes a pain. Plus the occasional missing binding or bug in build tools.

**My Opinion**

I don't think Skia Controls should be added to MAUI. Let MAUI run its course. It's for developers who want native controls and likely will continue to. I don't have any data on who wants native controls. I personally don't come across the need in any of my projects, but maybe I am not seeing a large market segment somewhere?

I think MS would be best doing a Xamarin Flutter binding similar to https://github.com/adamped/xamarin.flutter. Though I would change some of the ways I approach this.

Comet (https://github.com/Clancey/Comet) is also the other viable option as mentioned above, but MS would need to dedicate some serious resources to catch up with Flutter.

Unity even finished off the conversion of the Flutter Widgets to C# already (https://github.com/UnityTech/UIWidgets) But runs on Unity instead of the Flutter Engine. They did half the work already. They did release after I did my attempt. I wonder if they based any of it off my project? Don't mind if they did, it was all MIT. Though they only release the final conversion, not the scripts to do the conversion.

I see the MS community (and some employees) really wanting a Skia based approach and they are options. I just don't see any direction coming from MS officially, regarding this though. Hence it looks like management/leadership isn't buying into it for some reason.

If you want Skia controls, Dart isn't that different from C#, quite close actually, and the fact it isn't concurrent is a big plus. I would just suggest using Flutter rather than trying to change the course of this massive ship.

It's all about your professional opinion on what the best tool for the job is. If you think it's native controls then Xamarin.Forms and MAUI is for you. If you think its emulated controls, then Flutter is for you. Or maybe your enterprise dictates .NET, in which case you have no choice.

**Comment by cosminstirbu** [comment]
I have not really used much of Xamarin.Forms, as my team has mainly native iOS and Android skills so we focused on Xamarin Native (Xamarin.iOS and Xamarin.Android).

I do get the point that native controls / look and feel is not really a thing anymore - however doing your own drawing (e.g. Flutter) is not the only alternative.

Xamarin.Forms has adopted Material Visual which achieves more or less the same thing, keeping the benefits of accessibility and being more future proof (see: [iPadOS 13.4 mouse/trackpad cursor behavior](https://github.com/flutter/flutter/issues/52912)).

I guess I'd be happier with expanding the Visual API to support more "design languages" (e.g. Fluent and maybe there are more) - the main challenge there being that the controls overlap surface might not be large enough.

Anyhow, my point is that consistent look and feel isn't necessarily achieved only via doing your own drawing.

**Comment by dustincatap** [comment]
> Anyhow, my point is that consistent look and feel isn't necessarily achieved only via doing your own drawing.

I agree with this, but making something consistent by drawing is the easier path as compared to updating the native controls per platform.

**Comment by maxpiva** [comment]
It makes a lot of sense, to create the new UI under a common 2d/3d engine. I'm guessing one of the main problems with Xamarin Forms, is mapping all the original controls, they're all moving targets. So, controls are prone to bugs, or glitches, depending on the version and OS, also Microsoft has no say on how IOS 16, or Android 20 controls will evolve. Instead of putting all that engineering work for that, they could use this opportunity to do a clean slate. And manage the whole UI, instead of using someone else UI. IMHO, this will also serve them well in the future, to unify more the UI between all platforms. They could effectively port WinUI or unify both MAUI and WinUI.

As crazy as is sound, maybe DirectX or Direct3D porting is a possibility. Since our phones are no so different from the computers we use. Donno if that is possible legally (low level ), but probably they can create it over OpenGL ES, and SceneKit/METAL. It could be really interesting and not only for the UI.

**Comment by mrwcjoughin** [comment]
The whole point of Xamarin.Forms was to keep the unique look and feel of the underlying platform - and if you watch the full journey to one .NET video you will see that hasn't changed:
https://channel9.msdn.com/Events/Build/2020/BOD106?ocid=AID3012654&WT.mc_id=Build2020_pmmsocialblog

If you want to use something that has one GUI that isn't dependant on the underlying platform then use UNO https://platform.uno

**Comment by reader-man** [comment]
If the whole Idea of Xamarin.Forms, is to stay as is, without changing its underline renders, then, MS can begin a new parallel open source project that mimic Flutter, in making its base a 2d/3d engine, that benefit from the GPU/APU that's all around in most devices, and this will help it, in easing the unification of all platforms/OSs, and as the community is helping in shaping flutter, the same help will come in MS projects.

but i still think, as Xamarin.Forms render its xaml controls to native controls, it can make the 2d/3d engine as a unified render, at least, it can start a side project as a proof of concept, and Xamarin will stay as the binder for other native OS functionality.

and i agree with @maxpiva that following other vendors controls from version to another version, has its own maintenance dilemma.

**Comment by maxpiva** [comment]
There is more than one way to skin a cat. 

Will prefer to have stable controls and use skins if I want the native look. 

IMO Xamarin Forms is overengineering for the task and I think when people use, the native look and feel is not their list as primary, people are using it because Xamarin Forms, can leverage they software stack, maintain less code, and reuse all the work, and deploy on both android on ios, without coding native, one UI, they love it for that, and they hate it because, you know, bugs and do not work as intended (every Xamarin Forms programmer I know has issues).

Because let's face it, is a Frankenstein always evolving, and Xamarin playing whack a mole.

**Comment by yurkinh** [comment]
> There is more than one way to skin a cat.

I think it can be done with "Visual":
1. Visual = Default - renderers with native controls without any stylings
2. Visual = Material - renderers with native controls and Material stylings
3. Visual = Skia - renderers with SkiaSharp  controls (have the same look and feel on all platforms)
In this case, you will have a choice to make a whole application to look identically or particular controls

**Comment by maxpiva** [comment]
I have a Love-Hate relationship with Xamarin, will love to have the bugs and the quirks fixed. 

I have the opinion, they try to handle too many moving targets, without enough manpower, and not only at the UI level, but vendors also change their store API, toolchain, etc. continually. That affects the quality of the framework and tools greatly. So, or they increase the engineering power, and tame the beast. or they reduce the moving targets. 

Having a UI skinnable render engine, that could render current controls with Native Look & Feel, might be enough to start deprecating those franken-controls, reduce those moving targets, have a better architecture, and untie from vendor-specific limitations.

**Comment by adamped** [comment]
From my experience, native controls and managing the state between the native control and Xamarin.Forms control is the source of many bugs. The dreaded renderer layer :) As above, it's in a constant state of whack a mole.

Having discussed this at length before, I don't think XF or MAUI should implement any Skia controls. It would be better to start a new project from scratch without the native control baggage.

Personally I would love to see a Xamarin Flutter binding similar to https://github.com/adamped/xamarin.flutter

It would allow the use of the .NET ecosystem, even most of the Xamarin.Essentials plugin, that doesn't use UI and many other community plugins. Companies could even use their existing .NET code bases.

In terms of Skia controls, Flutter is too far ahead now. They have had years. Xamarin (the technology as a whole) is used for bringing .NET to many platforms. I believe it could focus on that mission, and use other UI frameworks, like Flutter to expand its appeal and also keep MAUI as a final maturing of XF. 

I would be interested to see how the .NET community reacts to a .NET Flutter. Many people get excited by it, unfortunately I never had the resources to bring it about myself. Think of F# for Flutter, its a great match up.

If MS were to start a new project for cross platform UI, it would have to be revolutionary beyond Flutter, which I have no idea what that would look like, at this point in time.

**Comment by timahrentlov** [comment]
It’s natural for MAUI to build upon XF, because this is what we’ve got right now. I for one look forward to rearchitect a few apps using MVU/Comet and drop XAML for good. This will be “good enough” for many of my apps. 

I do however get a bit concerned when MS still seem to ignore the success and developer appeal of Flutter. I get worried when key employees still touts the “native UI” benefits in blogs or videos. Or when they do “now the Xamarin button has a border” celebration posts while I’ve got Flutter animations left and right in the same twitter tweet. I DO understand that we need to use what we have, but this Comical Ali approach is not helping us. It has not gotten us very far since 2016. PancakeView (and now shadows) is the most important UI design “innovation” that has happened to XF in a while. That’s says a lot.

Like Adam, I do think that a .NET Flutter could be a good choice for those that do not need the native approach. Help us get both with MAUI. It is good to have a choice. In the old days MS was good at “embracing and extending”. Try it again with this :) - and imagine how it could be used in a WASM context.
