### ISSUE TITLE
Blazor Hybrid Dev Tools Console Logging

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/maui#6110]
This issue tracks adding a mechanism for logging to the Blazor Hybrid WebView Dev Tools Console. 

This would be via some sort of integration with `ILogger.Log`

### Discussed in https://github.com/dotnet/maui/discussions/6091

<div type='discussions-op-text'>

<sup>Originally posted by **Assassinbeast** April 13, 2022</sup>
I read this doc https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/developer-tools?view=aspnetcore-6.0&pivots=windows that we can open the Developer tools with Ctrl+Shift+I and see the Console logs.

But how do we write to the logs?

I have tried to add the `builder.Logging.AddConsole();` and `builder.Logging.AddDebug();`, to MauiProgram, but it didn't work.
Below code is what i tried:

```
public static class MauiProgram
{
	public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
			});

		builder.Services.AddMauiBlazorWebView();
		builder.Services.AddBlazorWebViewDeveloperTools();
		builder.Logging.AddConsole();
		builder.Logging.AddDebug();

		builder.Services.AddSingleton<WeatherForecastService>();

		return builder.Build();
	}
}
```

And then i added the _logger.LogInformation() to the Counter.razor

```
@using Microsoft.Extensions.Logging
@page "/counter"
@inject ILogger<Counter> _logger

<h1>Counter</h1>

<p role="status">Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code{
    	private int currentCount = 0;

		private void IncrementCount()
		{
			currentCount++;
			_logger.LogInformation(currentCount.ToString());
		}
}
```

Then i try to click on the "Click me" button, but there are no logs writing to the console

![mauilogging](https://user-images.githubusercontent.com/6762656/163294183-e2255bff-8768-42eb-967b-82132d6c0e17.jpg)

</div>

**Comment by TanayParikh** [comment]
Note; an interim workaround is: https://github.com/dotnet/maui/discussions/6091#discussioncomment-2568648

**Comment by unixbob** [comment]
Console.WriteLine from the razor page does work in the Webview, if you press F12 it opens the Edge / Webview debug console and you can see errors there

**Comment by javiercn** [comment]
@TanayParikh I don't think we should be logging to the browser console either from Console.WriteLine nor from ILogger.Log.

This is what Blazor Webassembly does because it is running C# on the browser, for other flavors of Blazor I don't think this is the right thing to do, as it might even introduce potential security issues if you load a script that replaces/hijacks whatever function is being used to write on the document context.

Console.WriteLine should behave the same way in a Blazor Maui app as it does in a non-Blazor Maui app, we shouldn't hijack it in any way to do something different as it can have unexpected consequences.

For a similar reason, I don't think we should add any sort of ILogger implementation to write to the browser console, as it traverses a trust boundary (which doesn't exist on webassembly, that's why its ok) and might accidentally expose sensitive information.

If we want to have a decent logging experience (at least during development) we should first look at the behavior on a non Blazor app.
* Does Console.WriteLine or ILogger.Log get output anywhere?
  * One likely place these are being output is on the Visual Studio Output window.
* If the output for ILogger doesn't show anywhere:
  * Should we have something inside AddBlazorWebview to make it do so?
  * Should we have a line in the template to turn logging during Debug?
  * Should we do nothing and just document how to add logging to your app?
* How do we configure logging for Development/Production as that normally happens in appsettings.json within ASP.NET Core apps, but these are not concepts we currently support in Maui apps.

Note that there is a "dissonance" here between ASP.NET Core and Maui in which ASP.NET Core has the concept of "Development" and "Production" that don't exist in Maui apps. The way we've decided to tackle this is to associate Development with `Debug` and Production with `Release`.

**Comment by TanayParikh** [comment]
> as it might even introduce potential security issues if you load a script that replaces/hijacks whatever function is being used to write on the document context.

> For a similar reason, I don't think we should add any sort of ILogger implementation to write to the browser console, as it traverses a trust boundary (which doesn't exist on webassembly, that's why its ok) and might accidentally expose sensitive information.

Can you please clarify the trust boundary we would be traversing in this case? Given both Blazor WASM & Blazor Hybrid are client side, I don't see how we'd be unintentionally exposing sensitive material?

> Does Console.WriteLine or ILogger.Log get output anywhere?
> - One likely place these are being output is on the Visual Studio Output window.

`ILogger.Log` should interface with the platforms native logging mechanism (ex. LogCat for Android, NSLog for iOS). `Console.WriteLine` does _not_ write to the VS (Debug) output window.

> If the output for ILogger doesn't show anywhere:
> - Should we have something inside AddBlazorWebview to make it do so?
> - Should we have a line in the template to turn logging during Debug?
> - Should we do nothing and just document how to add logging to your app?
> How do we configure logging for Development/Production as that normally happens in appsettings.json within ASP.NET Core apps, but these are not concepts we currently support in Maui apps.

I think having something similar to `AddBlazorWebViewDeveloperTools` (so `AddBlazorWebViewConsoleLogging`) may be the path forward here. It can also be guarded with `#if DEBUG` like we do with `AddBlazorWebViewDeveloperTools` to get around the Development/Production environment issue.

Really the goal of this functionality, in my opinion, is to provide a quick and easy way to debug and inspect app state. This becomes especially important for a MacOS development environment where we don't (yet) have comprehensive debug capabilities.

**Comment by danroth27** [comment]
I also think we shouldn't try to hijack `Console.WriteLine` in Blazor Hybrid apps. Maybe having an easy way to direct logging output to the browser dev console would be useful, but it feels weird to direct all app logging output there. How about we just provide a simple .NET API for calling `console.log`? It seems like that would be convenient for both Blazor Hybrid and Blazor Server apps.

**Comment by TanayParikh** [comment]
> I also think we shouldn't try to hijack `Console.WriteLine` in Blazor Hybrid apps.

@Eilon had also expressed concerns over using `Console.WriteLine`. The conclusion we'd reached in the offline discussion was to focus on `ILogger.Log` outputting to the developer console (should the user choose).

> How about we just provide a simple .NET API for calling console.log? It seems like that would be convenient for both Blazor Hybrid and Blazor Server apps.

This is already pretty straightforward, I'm not sure whether it's warranted to provide a direct API for this.

````csharp
_ = JSRuntime.InvokeVoidAsync("console.log", "some js runtime log");
```

**Comment by javiercn** [comment]
> Can you please clarify the trust boundary we would be traversing in this case? Given both Blazor WASM & Blazor Hybrid are client side, I don't see how we'd be unintentionally exposing sensitive material?

The boundary is between the browser context and the client device. The browser is sandboxed because the content is considered untrusted, hence making logs available to it via JS interop makes those details available to whatever potential untrusted code is running on the browser.

If you log to the document window, there is nothing preventing a third-party library from hijacking whatever JS function is being invoked to write to the console and sending that information elsewhere, which can easily disclose PII.

**Comment by javiercn** [comment]
> I also think we shouldn't try to hijack `Console.WriteLine` in Blazor Hybrid apps. Maybe having an easy way to direct logging output to the browser dev console would be useful, but it feels weird to direct all app logging output there. How about we just provide a simple .NET API for calling `console.log`? It seems like that would be convenient for both Blazor Hybrid and Blazor Server apps.

I don't think we need to provide anything. Users can do this themselves, and it is something that I would really discourage people from enabling.

The real feature is what @TanayParikh mentioned here:

> Really the goal of this functionality, in my opinion, is to provide a quick and easy way to debug and inspect app state. This becomes especially important for a MacOS development environment where we don't (yet) have comprehensive debugging capabilities.

That should be provided by the platform by forwarding the console output stream to the right place (VS output window, for example). At that point if someone wants to see the logging output, they can add the console logger provider to their app.

**Comment by TanayParikh** [comment]
Ah fair enough, I'm convinced. I'm fine to close this out then. 

cc/ @guardrex on:

> I don't think we need to provide anything. Users can do this themselves, and it is something that I would really discourage people from enabling.

due to the concerns @javiercn mentioned [above](https://github.com/dotnet/maui/issues/6110#issuecomment-1104051371).
