### ISSUE TITLE
sqlite path null

### ISSUE THREAD

**Issue by ltemimi** [dotnet/maui#6145]
### Description

Hi 
The sqlite path is null when ios is selected , the path works ok for windows and android

sqlitePath=
  Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) returns null

 var connectionString = Path.Combine(sqlitePath, "PlcBrowser.db3");

please help

### Steps to Reproduce

1. Create dotnet maui blazor project
2. Use entity framework db context to use sql lite
3. Test with Android OK
4. tets with windows OK
5. test with IOS path returneed is null

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Windows server 2022

### Did you find any workaround?

no

### Relevant log output

```shell
slqlite connection threw an exception
```

**Comment by drasticactions** [comment]
This is an EFCore bug and the same issue as https://github.com/dotnet/maui/issues/6050, I would check out this comment (https://github.com/dotnet/maui/issues/6050#issuecomment-1098428667) and try that, but this should be unrelated to MAUI itself.

**Comment by ltemimi** [comment]
Hi
I am not sure this is an ef core issue; it is plain C# trying to get the path of a special folder, it works fine for Windows and android but returns null for ios as a matter of fact it has nothing to do with sqlite as well

sqlitePath=
Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) returns null

**Comment by drasticactions** [comment]
You're right, I should have read the issue closer.

Most likely this is still not a MAUI issue, because MAUI does not control those paths. Those, I believe, come from the runtime (https://github.com/dotnet/runtime/blob/fa284882f1fec209d2cadd915c621078e8041228/src/mono/System.Private.CoreLib/src/System/Environment.iOS.cs#L41).

You could always use a different path (https://github.com/drasticactions/MauiRss/blob/main/MauiRss/Context/DatabaseContext.cs#L102-L114, for example), or take ask them or http://github.com/xamarin/xamarin-macios. If you want to verify it, try running the same code inside of a .NET 6 iOS app without MAUI. Most likely, it'll probably do the same. If it doesn't, then we got a problem here.

**Comment by ltemimi** [comment]
Hi
Thanks for the help, the Path.Combine is the issue I fixed that by just adding the strings.
Now we are back to EF core issue where db.Database.Migrate(); works for Windows and android and create the sqllite database correctly but gives the exception in IOS.
So it appears linked to EF Core indeed.

**Comment by VladislavAntonyuk** [comment]
for iOS you need additional settings for the connection. see example: https://vladislavantonyuk.azurewebsites.net/articles/Adding-SQLite-to-the-.NET-MAUI-application

**Comment by ltemimi** [comment]
HI @VladislavAntonyuk 
The suggestion above to add some code to the app delegate has worked thanks very much. So EF core migration can work for IOS
