### ISSUE TITLE
[Android] Setting the background color on entry changes the underline color as well

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#6207]
```C#
new Entry(){ Placeholder = "PlacheHolder", BackgroundColor = Colors.White, TextColor = Colors.Black, PlaceholderColor = new Color(0, 0, 0, 97) }
new Entry(){ Placeholder = "PlacheHolder" },
```

![image](https://user-images.githubusercontent.com/5375137/163886103-0fcc60dc-876a-4a02-a861-9d88d1318980.png)

**Comment by Symbai** [comment]
I just found this while searching how to change the color of the underline & caret (because changing the default colors in Styles.xaml in a new project has no effect, both remain purple). Now I know at least that changing background changes the underline color but when its a bug, how can I change the color when it has been fixed? Because there is no "UnderlineColor" property.

**Comment by mattleibow** [comment]
In android, the underline is part of the background drawable I think...

**Comment by PureWeen** [comment]
@Symbai I think you'd need to call `ViewCompat.setBackgroundTintList(et, colorStateList);` on the underlying control. You can do that via a mapper or access the control via the Handler on the EditText.
