### ISSUE TITLE
ViewHandler mapper extension methods won't reliably fire if mapper methods are replaced

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#6429]
https://github.com/dotnet/maui/issues/4714#issuecomment-1104871733

If you write the following code

```C#
global::Microsoft.Maui.Handlers.ViewHandler.ViewMapper.AppendToMapping("BackgroundColor",
	(handler, view) =>
	{

	});

global::Microsoft.Maui.Handlers.ViewHandler.ViewMapper.AppendToMapping("Background",
	(handler, view) =>
	{

	});
```

These will not fire for `Entry` because the `EntryHandler` replaces the `MapBackground` mapping on its mapper which means the call never reaches ViewHandler. This also means if we end up adding mappings to for inherited views later on it will cause the users code to stop firing if they had attached to a base class previously

**Comment by bakerhillpins** [comment]
Rather than write up a separate issue and link back to this I though it might be prudent to add to this issue since the end result is variability in Mapper function resolution.  I've been trying to author a control that inherits and overrides the `Microsoft.Maui.Controls.Label` and found that it's not behaving as I'd expect with regard to the mapper and overriding. 

For example: If I use the PropertyMapper constructor that takes a collection of IPropertyMappers:

 		public PropertyMapper(params IPropertyMapper[] chained)

the order of the chained Mappers (arguments in the constructor) can effect which handler gets called when both mappers override the same key. This is due to the fact that the first handler short circuits the algo.

			else if (Chained is not null)
			{
				foreach (var ch in Chained)
				{
					var returnValue = ch.GetProperty(key);
					if (returnValue != null)
						return returnValue;
				}
			}

The Chained search algo above is duplicated in both the `PropertyMapper.GetProperty(string key)` and the `PropertyMapper<TVirtualView, TViewHandler>.Add(string key, Action<TViewHandler, TVirtualView> action)` methods.  The Add method actually wraps up the inserted handler with this logic. It would seem that this duplication is unnecessary? 

The indexer on the `PropertyMapper<TVirtualView, TViewHandler>` class  also [wraps up the stored handler in an empty delegate](https://github.com/dotnet/maui/blob/d88b177510b0b25cf117f7b41cd21aab7b51e180/src/Core/src/PropertyMapper.cs#L174).  If this extra delegate is necessary then the `action` returned from the `GetProperty(key)` call on the line above should be null checked as `GetProperty` [can return null](https://github.com/dotnet/maui/blob/d88b177510b0b25cf117f7b41cd21aab7b51e180/src/Core/src/PropertyMapper.cs#L64).

I.e.  ` => action.Invoke(h, v));`  should be:  `=> action?.Invoke(h, v));`

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2. Not repro this issue.
