### ISSUE TITLE
PreferencesImplementation is inaccessable due to its protection level

### ISSUE THREAD

**Issue by VinceKellyBM** [dotnet/maui#6436]
### Description

When trying to use the new Preferences from Maui Essentials, I get the above error on this line of code

builder.Services.AddSingleton<IPreferences, PreferencesImplementation>();

Looking at the source code for maui, there is no access modifier on the class see below:

namespace Microsoft.Maui.Storage
{
	class PreferencesImplementation : IPreferences
	{
		static readonly object locker = new object();

### Steps to Reproduce

1. Create a new Maui app
2. Add builder.Services.AddSingleton<IPreferences, PreferencesImplementation>(); to the MauiProgram.cs

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

No

**Comment by kristinx0211** [comment]
repro on  vs 17.3.0 Preview 1.0 [32422.330.main].

**Comment by mattleibow** [comment]
The correct way to access the implementation is via the Preferences.Default property.

This property represents the OS default and is only settable by the framework.

For DI, the interface is used along with the custom implementations. If there is a VM or some library that wants to be DI compatible, then it needs to expose either a settable way itself or maybe just a ctor that expects the interface.

The reason for not having some dynamically changing property is now all services will need to handle changes and subscribing/unsubscribing to events. 

In most cases, this is enough because these implementations are not changed at runtime and forcing more complex code on implementers is not necessary.

This is also more DI friendly because having a value that can change under DI is not great and now we have 2 places to check for the real implementation.

If there is a reason to make this dynamically settable via some static API, then please open a specific issue on that so we can discuss.

**Comment by VinceKellyBM** [comment]
Hi Matthew, many thanks for your response, to be honest I was following another example of using another area of the Essentials as I could not find an example of how to use the preferences, the example I was following was using DI to use the Maps later on and I was not aware of Preferences.Default I have change my code to use this and it all works. Thanks again
