### ISSUE TITLE
Android.Webkit namespace is not found and project does not compile when classes are in Platform/Android directory

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#6610]
### Description

I am developing a MAUI Blazor application which is to be used on Android and Windows.
There is a special handler required for Blazor on Android for permissions.

Compiling the project for Windows fails because it doesn't know Android namespaces (expected behavior).
Because of that and not having to wrap the class in `#if ANDROID ... #endif`, I tried to move the code to Platform/Android which is the suggested way for platform-specific compilation
_**But then the code doesn't even compile for Android itself.**_

MauiProgram code source: https://stackoverflow.com/questions/70229906/blazor-maui-camera-and-microphone-android-permissions

classes code source: https://github.com/dotnet/maui/issues/4170

![image](https://user-images.githubusercontent.com/64279914/165761541-314e9916-750c-4ec7-a637-71ad7d955106.png)

Left - compiles:
[MauiApp4 classes in project root folder.zip](https://github.com/dotnet/maui/files/8583806/MauiApp4.classes.in.project.root.folder.zip)

Right - does not compile:
[MauiApp4 Platform.zip](https://github.com/dotnet/maui/files/8583056/MauiApp4.Platform.zip)

### Steps to Reproduce

New MAUI Blazor app
add code from above sources

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

probably all

### Did you find any workaround?
`#if ANDROID ... #endif` must be used for all Android specific classes and `using`s and these classes shall not be placed in Android/Platform directory

**Comment by Redth** [comment]
I suspect this is duplicate or related to #4726

**Comment by janseris** [comment]
Probably not exact duplicate because the application doesn't build in this case

**Comment by v-longmin** [comment]
Verified repro on 17.3.0 Preview 1.0 [32427.455.main]. Repro with above project.

**Comment by Redth** [comment]
This may have been conflated with the intellisense issue (which has a fix to greatly improve it in an upcoming release of VS 17.3 Preview 1), however trying out the repro solution, in this case I think it's a simple namespace conflict.

If you see the screenshot, I fixed this by adding `global::` in front of the use of `Android.` since the compiler can't tell the difference between the namespace the class is in and the nested WebKit namespace.

<img width="834" alt="Screen Shot 2022-05-05 at 4 14 31 PM" src="https://user-images.githubusercontent.com/271950/167018192-99e50f07-91ec-408c-8c32-e55fa9fba2c0.png">
