### ISSUE TITLE
OnPlatform with Thickness breaks XAML Hot Reload

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#6619]
### Description

```
<OnPlatform x:TypeArguments="Thickness"
        x:Key="VeryThick"
        Default="40,20"
        />
```

Try to hot reload a file where this exists, and nothing with hot reload.

a/ would like this valid XAML to hot reload
b/ would like for hot reload to continue working even if other xaml in the file is considered invalid

Errors:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	XLS0414	The type 'Thickness' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.	ControlGallery	C:\work\ControlGallery\src\ControlGallery\Resources\Styles\Styles.xaml	69	

> Severity	Code	Description	Project	File	Line	Suppression State
Error	XHR0008	The name "Thickness" does not exist in the namespace "http://schemas.microsoft.com/dotnet/2021/maui".	ControlGallery	C:\work\ControlGallery\src\ControlGallery\Resources\Styles\Styles.xaml	69	

> Severity	Code	Description	Project	File	Line	Suppression State
Error	XHR0008	The name "OnPlatform" does not exist in the namespace "http://schemas.microsoft.com/dotnet/2021/maui".	ControlGallery	C:\work\ControlGallery\src\ControlGallery\Resources\Styles\Styles.xaml	69	

### Steps to Reproduce

add that xaml to a resource dictionary and change anything else on the page

### Version with bug

Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

all

**Comment by drasticactions** [comment]
@etvorun Do you have any ideas what could cause this?

**Comment by etvorun** [comment]
@drasticactions I'll need to debug. Probably some bugs in our XAML parser.

**Comment by VincentBu** [comment]
repro with vs main build(32622.314), remove `OnPlatform x:TypeArguments="Thickness"` part, and the hot reload works again.

**Comment by svaldetero** [comment]
I have this same issue. It's because `Thickness` is in a different namespace. I was going to file a bug until I saw this one. Trying to add something like this:
```
<Frame>
  <Frame.Padding>
    <Thickness ... />
  </Frame.Padding>
</Frame>
```
Gives the same error _only on mac_. 
Adding the namespace fixes the issue on mac
`xmlns:maui="clr-namespace:Microsoft.Maui;assembly=Microsoft.Maui"`
and
```
<Frame>
  <Frame.Padding>
    <maui:Thickness ... />
  </Frame.Padding>
</Frame>
```

**Comment by drasticactions** [comment]
Hey, it worked! Yeah, I think this could be a parser issue. It _might_ be something that needs to be fixed in MAUI itself if it is with the namespace, but it would be better for us to track it there so we can put it into our sprints. I forgot about it until @svaldetero brought it back up.

**Comment by etvorun** [comment]
@mgoertz-msft, is this the same issue you fixed with https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/407399? Looking around I see that Microsoft.Maui.Thickness comes from Microsoft.**Maui.dll**. Yet it is Microsoft.**Maui.Controls.dll** which includes needed XmlnsDefinition. 
```
[assembly: XmlnsDefinition("http://schemas.microsoft.com/dotnet/2021/maui", "Microsoft.Maui", AssemblyName = "Microsoft.Maui")]
``` 

Question for @davidortinau, @Redth and MAUI team. Why owner assemblies do not have their own XmlnsDefinition attributes? In this case why Microsoft.Maui.dll does not have `[assembly: XmlnsDefinition("http://schemas.microsoft.com/dotnet/2021/maui", "Microsoft.Maui")]`. I find it strange that in order to make types in foo.dll XAML parser friendly one has to reference assembly bar.dll. Are there plans to improve that?

**Comment by mgoertz-msft** [comment]
@etvorun Correct, I added support for AssemblyName in Xmlnsdefinition, so this should work now in 17.3 Preview 3.
