### ISSUE TITLE
MAUI Blazor is loading forever on Android 6

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#6640]
### Description

> What do you see

I see
![image](https://user-images.githubusercontent.com/64279914/165866130-f12ba002-cec6-4415-b341-8905d25c2c73.png)

### Steps to Reproduce

Create a new MAUI Blazor app
Try run on emulated device -> default settings Pixel 5 with API 23 (Android 6)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 6

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android 6 with above project.

**Comment by drasticactions** [comment]
My guess is that it's not loading at all and it's erroring in some way. If you go to a Blazor WASM app in that emulator in the default browser, does it load?

**Comment by Eilon** [comment]
Might be specific to older Androids. I'm pretty sure we don't support Android 5 at all, but maybe there's some issue on Android 6.

**Comment by javiercn** [comment]
@janseris I would suggest opening the edge and going to edge://inspect/#devices opening the dev tools for the emulator and checking if there are errors on the console. It would also help if you turn on first chance exceptions and see if there is a relevant exception being thrown that might be causing the issue.

**Comment by janseris** [comment]
@javiercn I suggest this is done by MAUI support e.g. @XamlTest considering that the issue is verified on your end. I am not paid for testing MAUI.

**Comment by javiercn** [comment]
> Thank you for tip, however I suggest that this is done by MAUI support e.g. @XamlTest considering that the issue is verified on your end. I am not paid for being a beta-tester of MAUI (and moreover _**I don't have time to do it**_, I need to develop applications for our clients).
> It sounds like something you can do in Microsoft when the error has been successfully reproduced.

We understand that you are not here to help test the framework and that have other priorities. However the reason we regularly ask for more details is because in many cases it helps us speed up the process of coming to a resolution, when there is some missing setup or some configuration issue. 

We can always do this ourselves, but as you imagine, our resources are also limited and the more people can help with detailed error reports, the more people that enables us to help. We normally assume that when people run into an issue they already have the appropriate context/setup in place and takes them less to capture the information that it takes us to perform the necessary setup + capture.

I hope that helps clarify why we ask for more information even in these cases, if you can't or don't want to provide it, that's ok with us, we will still look at the issue and provide an answer/fix/workaround, it might just take us a bit longer.

**Comment by janseris** [comment]
@javiercn I think this doesn't take much effort to set up for people working with MAUI on daily basis (test team).

> Create a new MAUI Blazor app
> Try run on emulated device -> default settings Pixel 5 with API 23 (Android 6)

**Comment by MackinnonBuck** [comment]
@janseris I'm fairly certain it's an issue with the default installed WebView here, not the Android version. If you follow [this Stack Overflow answer](https://stackoverflow.com/questions/34291902/android-studio-emulator-does-not-come-with-play-store-for-api-23/34581874#34581874), there might be a way to install the latest version of Chrome from the Google Play Store, which should provide a WebView that works with .NET Maui Blazor apps.

**Comment by mkArtakMSFT** [comment]
Closing per @MackinnonBuck 's comment above.
