### ISSUE TITLE
Radiobutton doesn't appear correctly when FlowDirection is RightToLeft

### ISSUE THREAD

**Issue by hamiddd1980** [dotnet/maui#6708]
### Description

When **FlowDirection** is **RightToLeft** in Page, the **RadioButton** Content doesn't appear correctly.
For **RightToLeft** languages, the Content must be at the **Right side** , but currently the content goes to Left end(see below)

### Steps to Reproduce

1-Create a New MAUI Project
2-Android Manifest :a**ndroid:supportsRtl="true"**
3-Add new Page
4-Code:

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             FlowDirection="RightToLeft"
             x:Class="MauiApp29.Page1"
             IconImageSource="edit.png"
             Title="page1"
             BackgroundColor="GreenYellow"
             Padding="8">
    <ContentPage.Content>
        <VerticalStackLayout>
            <Label Text="What's your favorite animal?" />
            <RadioButton Content="Cat"/>
            <RadioButton Content="Dog" />
            <RadioButton Content="Elephant" />
            <RadioButton Content="Monkey"
                 IsChecked="true" />
        </VerticalStackLayout>
    </ContentPage.Content>
</ContentPage>
```
![Screenshot_1651337756](https://user-images.githubusercontent.com/57061231/166115241-d75b2bad-1258-4772-8790-c628430ec496.png)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 8

**Comment by kristinx0211** [comment]
can be reproduced on android 11.

**Comment by hartez** [comment]
Well, this one's a stumper. So, the behavior in the example is expected, because the text itself is LTR. However, if the text is changed to RTL (if "Cat" is replaced with "חתול"), then the alignment _should_ be correct, something like this:
![image](https://user-images.githubusercontent.com/538025/216214772-8170199f-78a4-4c0e-a8b4-501689b9647d.png)

That's how it works on native Android. And it seems like it should be working that way based on the properties that MAUI is setting for the RadioButton. But for some reason, the settings aren't taking. 

So somewhere in the stack we must be overwriting the desired native settings for TextAlignment or TextDirection (or something else that I'm missing).
