### ISSUE TITLE
[Bug] [Android] Fixed width on entrys and editors

### ISSUE THREAD

**Issue by rachelkang** [dotnet/maui#671]
### Description
Some entrys and editors appear to have a fixed width. Note this doesn't happen with all entrys and editors - it may be dependent on the presence of specific properties (?)

### Steps to Reproduce

1. Run MAUI sample on Android

### Expected Behavior
Text should take up the full width of the entry/editors

### Actual Behavior
Text gets cut short - see screen recording below

### Basic Information

- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  not tested
  - Android: 11 (probably also lower)
  - UWP:  not tested
- Affected Devices: Pixel 4a device, also simulators

### Screenshots
https://user-images.githubusercontent.com/21988533/113884321-dfbf3d80-978c-11eb-8087-3a0572dbdd87.mp4

**Comment by hartez** [comment]
Looks like this got fixed somewhere along the way - all of those Entry and Editor controls are allowing text all the way across the screen. (The short one in the middle has a MaxLength of 10, so that behavior is expected.)

![Screenshot_1620660078](https://user-images.githubusercontent.com/538025/117683392-41e6d600-b171-11eb-9925-7faf02288b36.png)
