### ISSUE TITLE
AVCaptureDevice.DevicesWithMediaType(AVMediaTypes.Video.ToString()); returns null

### ISSUE THREAD

**Issue by maxulm** [dotnet/maui#6728]
### Description

Using the following method AVCaptureDevice.DevicesWithMediaType(AVMediaTypes.Video.ToString()); returns null.

### Steps to Reproduce

Implement the following line of code and run it under iOS:
AVCaptureDevice.DevicesWithMediaType(AVMediaTypes.Video.ToString());

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS15.4

**Comment by jfversluis** [comment]
Probably because [this method has been deprecated](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1390520-deviceswithmediatype) by Apple, please use the replacement.

Additionally, for the future: this is not .NET MAUI specific. If anything it is something for .NET for iOS. Just FYI 😄

**Comment by maxulm** [comment]
@jfversluis you're speaking of xamarin for iOS?
Even the replacement returns null :/

**Comment by jfversluis** [comment]
Yeah this is really the platform stuff. To be honest I doubt something is bugged in the code, but if anything is wrong this would be part of: https://github.com/xamarin/xamarin-macios

Do you have the right permissions implemented and requested for the camera?
