### ISSUE TITLE
Document how to customize WebView settings in a Blazor MAUI app

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/maui#6823]

**Comment by MackinnonBuck** [comment]
We've added docs for customizing WebView settings [here](https://github.com/dotnet/docs-maui/pull/473/files#diff-1d6670b20e804046a9fde75695f665256c2b80f81de9c1cdb5515a349850af52R24).

To demonstrate advanced cases, we now have [this sample](https://github.com/MackinnonBuck/MauiBlazorPermissionsExample).

Closing since these two items sufficiently address WebView customization.
