### ISSUE TITLE
[Bug] [WinUI] NRE thrown when tabbing from Entry w/ Password

### ISSUE THREAD

**Issue by rachelkang** [dotnet/maui#690]
### Description

Tab navigation is essential to keyboard accessibility. On WinUI, an NRE is thrown when trying to tab from an entry with a password. The NRE is thrown from [this line in code](https://github.com/dotnet/maui/blob/9df7b78218c0b881df81f068642ed6c5ebec2e51/src/Compatibility/Core/src/Windows/FormsTextBox.cs#L302) and is reported as follows:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Maui.Controls.Compatibility
  StackTrace:
   at Microsoft.Maui.Controls.Compatibility.Platform.UWP.FormsTextBox.OnKeyDown(KeyRoutedEventArgs e) in C:\Users\rachelkang\maui\src\Compatibility\Core\src\Windows\FormsTextBox.cs:line 302
```

Note: App does not crash and pressing "Continue" multiple times allows the app to proceed execution

### Steps to Reproduce

1.  Run Microsoft.Maui.WinUI
2.  Go to Password Entry
3.  Press Keyboard Tab key

### Expected Behavior
Focus should navigate to the next control, and no NRE should be thrown

### Actual Behavior
NRE is thrown

**Comment by bkaankose** [comment]
This is mainly because WinUI is currently using CoreWindow for **UWP only** and Win32 HWND for packaged desktop apps. XF used CoreWindow because it was UWP, but WinUI3 is a packaged Win32 app. Luckily, we don't have anymore place other than this line you mentioned where we rely on CoreWindow in XF code. However, it's not the same for **CoreDispatcher**.

**CoreDispatcher** also is not supported in WinUI3 Desktop apps and controls that rely heavily on this should be refactored for WinUI port as well.

We have Dispatcher in compatibility for Windows, but it's built on top of CoreDispatcher. Thus will not work. That one needs to change to use dispatcher from our WinUI Window handle and old CoreDispatcher usages should be replaced with this one.

I'm sure @PureWeen has better plans to make it work 😃

**Comment by Redth** [comment]
No longer a repro on main :)
