### ISSUE TITLE
Issue in Clipping Images in Border

### ISSUE THREAD

**Issue by Ahamed-Ali** [dotnet/maui#6986]
### Description

1)Images are not perfectly fit as expected....In Android, Images are perfectly clipped without CornerRadius Only, but In Windows Images are not cropped correctly i.e see the below differences between android and windows

In Android without CornerRadius Works perfect 
<img width="89" alt="image" src="https://user-images.githubusercontent.com/102580874/167640643-b3675660-95d7-4c8c-8a7c-51eb284e7266.png">

 In Windows without CornerRadius not work as expected

<img width="143" alt="image" src="https://user-images.githubusercontent.com/102580874/167640122-defe5228-0ecf-4c2c-a23b-27eade1606ff.png">

2) Likewise by giving Corner Radius , Images are not perfectly fit in both android and windows, see the screenshots below

In Android by Giving Corner Radius, there is small gap in top and left side
<img width="96" alt="image" src="https://user-images.githubusercontent.com/102580874/167641093-7bac1386-a086-4aa8-9bd7-fbedd9f3bb5c.png">

In Windows by Giving Corner Radius, Images are not totally clipped inside the border

<img width="113" alt="image" src="https://user-images.githubusercontent.com/102580874/167639914-ddb45143-ca69-4e9b-8755-79da99d1c8de.png">

                                     

### Steps to Reproduce

1.Unzip the below project , I gave Corner Radius . Check with Corner Radius and also without Corner Radius in both Android and windows

[SampleGridCheck.zip](https://github.com/dotnet/maui/files/8661910/SampleGridCheck.zip)

2. Run the Project

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 9.0 and Windows10.0.19041.0

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by jsuarezruiz** [comment]
@Redth I think we have an interesting topic to discuss here.

Border is a special container where can define the border with an `IShape`. IShape only has the information needed to define a specific Shape (no Stroke, etc). However, when exposing IShape we use Shapes API (which implement ShapeView by exposing Stroke and many other properties). Similarly, Geometry implements IShape.

This leaves us with two ways to set the Stroke Shape:

```
<Border.StrokeShape>
    <RoundRectangleGeometry Rect="1,1,99,99" CornerRadius="50" />
</Border.StrokeShape>
```

```
<Border.StrokeShape>
    <RoundRectangle CornerRadius="50" />
</Border.StrokeShape>
```

![border-type-issue](https://user-images.githubusercontent.com/6755973/167647047-99b9c0d4-b30d-47b5-a80f-b94bd1599803.PNG)

We really had in mind to allow defining StrokeShape with IShape, but without properties like Stroke (Brush) or sizing (because the size is inherited from Border). But we don't have an ideal clean option. Using Geometry we must make adjustments to validate all cases. We can limit to using some specific type, or create a specific type.

![throw-exc-shape](https://user-images.githubusercontent.com/6755973/167647770-1c2c66aa-c8fb-4a19-a853-16c0b9e23cf5.PNG)

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32427.455.main]. Repro on Android and Windows with above project.

**Comment by pierre01** [comment]
I have observed the same issue for lower Border part See code and image below
![image](https://user-images.githubusercontent.com/2603287/170124493-dd81773d-a0e0-4602-a97e-2da34d2e34bb.png)

**Comment by sej69** [comment]
I'm hitting this now too.

**Comment by Visual-IT-2021** [comment]
Same here.
Works on iOS, fails on Android
