### ISSUE TITLE
Modify our templates to include a better version for iOS or build SupportedPlatforms into our targets

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#6996]
Currently our templates specify `14.2` for the `SupportedPlatform` which is a bit high for the iOS default. On the other platforms we specify the minimum so perhaps we should also set iOS to the lowest value as well?

As a better fix maybe it's better to include all these minimums in our targets files. Is there any reason to have these in the CSPROJ files?

**Comment by Eilon** [comment]
I agree there probably needs to be some change here. I had a default MAUI project created in VS Mac, using latest VS Mac, latest Xcode, latest everything. Running on MacCatalyst worked great. But VS Mac wouldn't let me target any iOS Simulator for _running_ and showed this warning in the build target dropdown instead: `Lower the 'Deployment Target' to see older simulators or check your Apple SDK path`.

It turns out that the target of iOS 14.2 was not allowed for some reason, and I had to change it to 15.4 to compile and run.

This is what's in the template: https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/MauiApp.1.csproj#L25

```csproj
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
```

And I changed it to:

```csproj
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.4</SupportedOSPlatformVersion>
```

And then it worked. I'm not sure if some defaults went out-of-whack, or if my installation had some problem, but this experience was not good, and it took me probably an hour to figure out why it wasn't working and how to fix.
