### ISSUE TITLE
I installed the MAUI workload, but I don't see New Maui project option in VS17.3.0

### ISSUE THREAD

**Issue by banko12** [dotnet/maui#7041]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by drasticactions** [comment]
Did you install the workload from dotnet CLI or from Visual Studio?

**Comment by codemonkey85** [comment]
I've installed from both and I too am not seeing the templates. I tried to "repair installation" for 17.3 Preview 1 through Visual Studio Installer, and that didn't fix it either.

**Comment by codemonkey85** [comment]
Ah, good news, I found a fix: run this in your command line.
```
dotnet new install Microsoft.Maui.Templates::6.0.300-rc.3.5667
```
![image](https://user-images.githubusercontent.com/1414036/167990919-0da231c1-7b1f-49a7-b1eb-b79819befff1.png)

**Comment by AlexeyStarkov** [comment]
Try to install this [extension](https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17)

**Comment by codemonkey85** [comment]
@joeloff I already have the templates in Visual Studio, after finding the fix I mentioned:

> Ah, good news, I found a fix: run this in your command line.
> 
> ```
> dotnet new install Microsoft.Maui.Templates::6.0.300-rc.3.5667
> ```
> 
> ![image](https://user-images.githubusercontent.com/1414036/167990919-0da231c1-7b1f-49a7-b1eb-b79819befff1.png)

**Comment by joeloff** [comment]
Great, if you hit a similar issue in the future, you can also gather some additional information by doing the following:

Set the following environment variables, e.g. after opening a Visual Studio Developer Prompt

```
SET VS_WTE_DIAGNOSTIC_MODE=File
SET VS_WTE_DIAGNOSTIC_VERBOSITY=2
SET VS_WTE_DIAGNOSTIC_TRACESWITCHES=ALL
SET VS_WTE_DIAGNOSTIC_OUTPUTFILE=%temp%\wte.log
```

Then launch VS using `devenv.exe`. There should be a log file called in `%temp%\wte.log` that should indicate which templates were located. Since you updated the package to 6.0.300, I suspect the 6.0.100 copy was replaced

**Comment by AlexeyStarkov** [comment]
> Ah, good news, I found a fix: run this in your command line.
> 
> ```
> dotnet new install Microsoft.Maui.Templates::6.0.300-rc.3.5667
> ```
> 
> ![image](https://user-images.githubusercontent.com/1414036/167990919-0da231c1-7b1f-49a7-b1eb-b79819befff1.png)

Small update for those who gets following error:
Error: Invalid option(s):
  Microsoft.Maui.Templates::6.0.300-rc.3.5667
  
Try to add **-i** after "install": **dotnet new install -i Microsoft.Maui.Templates::6.0.300-rc.3.5667**
It worked for me.
Besides the latest version of Templates package might be found here https://www.nuget.org/packages/Microsoft.Maui.Templates/

**Comment by jfversluis** [comment]
You might want to check it .NET 7 preview is installed (run `dotnet --version`), if that's the case the templates are installed but they won't show up. More info on that [here](https://github.com/dotnet/maui/wiki/Known-Issues#net-maui-templates-do-not-appear-in-visual-studio).

If the templates are not installed you can run `dotnet new -i Microsoft.Maui.Templates` to still get them. Please do not use the version that is at the end, especially not the one as advertized here because that is an older version. If you do not specify a version the newest ones will be installed.

We're investigating why the templates are not installed in some instances and will fix that. Since we have multiple issues about this I'm closing this one. Please let us know if you still can't get the templates to show up.
