### ISSUE TITLE
Net Maui Blazor App cannot pair to a mac

### ISSUE THREAD

**Issue by whann0205** [dotnet/maui#7359]
### Description

The Xcode license status couldn't be verified because Xcode has not been found on the default location of the connected Mac. Having Xcode installed and functional is necessary in order to build and run iOS apps, so please check that Xcode is correctly installed and that the path specified under iOS Settings is correct.

Have attached the xamarin log file to review.
Since it does not happen when i start VS with no Code (connects succesfully) nor
does it happen if choose a different template such as mobile blazor bindings,
i posted that here. Its strange that it happens with blazor net maui though....
Please help!

### Steps to Reproduce

Create a new project - Select .NET Maui Blazor App
Select Pair to mac

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

IOS

### Did you find any workaround?

[2022-05-20_11-49-21.1788.Ide.zip](https://github.com/dotnet/maui/files/8738448/2022-05-20_11-49-21.1788.Ide.zip)

**Comment by drasticactions** [comment]
This is not a MAUI issue that can be fixed in this repo. This is an issue with the Xamarin Pair-to-Mac experience. The issue here is that, yes, it can connect to the Mac, but it can't find Xcode. It only needs Xcode when it needs to build iOS specific things, and so it's not failing for some templates because they don't actually _need_ the paired Mac to build them. If you tried building and deploying another kind of iOS app, it would most likely fail.

```
Xamarin.Messaging.Integration.State.IOSServerStateContextExtensions Error: 0 : An error occurred while trying to get the current Xcode location in the connected Mac
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.Messaging.Integration.State.IOSServerStateContextExtensions.<GetXcodeLocationAsync>d__3.MoveNext() in D:
   ```

I would run through https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/ and verify you have Xcode set up correctly. If it's not in `/Applications/Xcode.app` you need to open up the Visual Studio settings to verify that it is working. If you still can't get it to work, file this feedback to https://developercommunity.visualstudio.com/home where the Platform team and work on and track this issue.

**Comment by whann0205** [comment]
Based on your "its not maui issue" answer i tried other "yes i need the mac build host" templates 
to see if they work. And indeed older Xamarin Forms Apps such as IOSApp(Xamarin), Mobile App(Xamarin Forms) were building without any problem.
So i went though the troubleshooting guides as you suggested again.
Nothing helped, to bring any net maui project to build.
It always complained about xcode...
The solution is: 
https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/troubleshooting
Subsection: Clearing the Broker, IDB, Build, and Designer Agents on the Mac

So clearing the XMA Cache does the trick!

The Problem has nothing to do with Xcode itself. 
Since i am testing this repo for quite a long time and different xcode versions,
it might have to do that some files in there points to a non existing path or dll.
