### ISSUE TITLE
[Maui Blazor] App becomes unresponsive when dragging and dropping text outside the window.

### ISSUE THREAD

**Issue by Abooow** [dotnet/maui#7390]
### Description

When selecting any text (can be links or images as well) in a .NET MAUI Blazor project (RC3) and then drag and drop it outside the app window, the app enters a weird state and becomes unresponsive. No click event works on links or buttons in this state. Not even the minimize, maximize or close buttons work.
Only when trying to move the window then, instead of actually moving the window, a file icon appears. When releasing the mouse button then all the previous click events will fire off at the same time and the app works as expected again.

Here is a video that demonstrates what happens:

https://user-images.githubusercontent.com/54490104/169640360-53c6fcb6-b7a5-4df0-84ff-db4bb3a564a1.mp4

### Steps to Reproduce

1. Create a .NET MAUI Blazor project.
2. Start the project.
3. Select any text, link or image and drag and drop it outside the app window and observe the bug 🐛

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 10.0.19044, Windows 11 10.0.25115

### Did you find any workaround?

Nope.

**Comment by kristinx0211** [comment]
verified repro on windows with 17.3.0 Preview 2.0 [32522.62.main].

**Comment by mkArtakMSFT** [comment]
Potentially related to: https://github.com/dotnet/maui/issues/2205

**Comment by Eilon** [comment]
I found it a bit hard to repro this, but it does still repro in a .NET MAUI Blazor app on Windows. When I get it into this state, I sometimes can quickly see what appears to be a "not allowed to copy" icon that seems impossible to get a screenshot of. After clicking around a bit, the app becomes responsive again and behaves normally.

Then I tried to repro it in a default WinUI3 app where all I did was add a WebView2 pointing to an arbitrary site:

```xaml
<WebView2 x:Name="wv2" Source="https://learn.microsoft.com"></WebView2>
```

And after much clicking around and trying to drag/drop text (which seems hard to do, sometimes), I did get it into a similar state with the "not allowed to copy" icon, which, after clicking a bit, goes back to normal.

I had to take a picture with my phone because for some bizarre reason Windows' screenshot feature doesn't capture that icon:

![image](https://user-images.githubusercontent.com/202643/205368203-47d58e8c-a70c-4c0e-9ad4-f6072549b407.png)

So, it seems there's an underlying issue with WebView2. I'll check if there is an existing issue or open a new one.

**Comment by Eilon** [comment]
Alright I think this is effectively a duplicate issue of this WebView2 issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2805 (which I logged due to another earlier MAUI issue report). That issue uses https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_draganddrop as the repro site and the exact same "app stops responding for a bit" issue happens there. So, anyone seeing this issue here, please go to the WebView2 issue and vote/comment on it. Thanks!
