### ISSUE TITLE
Getting started tutorial - hot reload is not working

### ISSUE THREAD

**Issue by tjakopan** [dotnet/maui#7441]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

In the MAUI "Getting started tutorial" where I need to change "Hello, World!" to "Hello, .NET MAUI!" hot reload is not working. I've changed the label text and saved the MainPage.xaml. I'm running it as windows application.

As soon as I edit MainPage.xaml in debug mode, the whole file gets underlined with squiggly line, and on mouseover, each xml element says something along the lines "The name "ContentPage" does not exist in the namespace ""http://schemas.microsoft.com/dotnet/2021/maui"."

OS: Windows 11 Pro, 10.0.22000 Build 22000
Visual Studio Community 2022 Version 17.3.0 Preview 1.1
The only extension I'm running is ReSharper 2022.1.1.

**Comment by drasticactions** [comment]
1. XAML Hot Reload does not rely on saving the current page to work. It updates after you stop typing. There are settings to force it to only update upon saving the page, but those are not the default.

2. Did you try restarting the app and trying again? We are tracking an issue where upon first project creation, the first time you try and edit XAML while the app is debugging, it shows the entire page as a rude edit (AKA The squiggly lines) saying that "XAML Hot Reload is not supported for this kind of edit." Restarting the app normally fixes that problem.

3. Can you file this issue under https://developercommunity.visualstudio.com/home? This is going to be something specific to the XAML Hot Reload tooling and not something that can be fixed by the team in this repo.

**Comment by tjakopan** [comment]
> 1. XAML Hot Reload does not rely on saving the current page to work. It updates after you stop typing. There are settings to force it to only update upon saving the page, but those are not the default.
I know, I thought I would force it by saving it, but it didn't help. I'm having all defaults because I'm not using VS usually, so it's a fresh preview install.


> 2. Did you try restarting the app and trying again? We are tracking an issue where upon first project creation, the first time you try and edit XAML while the app is debugging, it shows the entire page as a rude edit (AKA The squiggly lines) saying that "XAML Hot Reload is not supported for this kind of edit." Restarting the app normally fixes that problem.

I've restarted couple of times and tried it again now. I'm not getting "XAML Hot Reload is not supported for this kind of edit.", though.

> 3. Can you file this issue under https://developercommunity.visualstudio.com/home? This is going to be something specific to the XAML Hot Reload tooling and not something that can be fixed by the team in this repo.

Will do. Thanks

**Comment by drasticactions** [comment]
This issue was refiled under VS Feedback, closing this one.
