### ISSUE TITLE
[Android] Stream.Length is not supported from asset

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#7471]
### Description

It works well on Windows.

```
async Task LoadMauiAsset()
	{
		using var stream = await FileSystem.OpenAppPackageFileAsync("AboutAssets.txt");
		using var reader = new StreamReader(stream);

		var contents = reader.ReadToEnd();
	}

```
This is a sample from AboutAssets.txt file which is a part of the basic MAUI app template.

When opening any other file than a text file, I am copying the stream to a `MemoryStream` using `stream.CopyTo` method to be able to get `byte[]` - e.g. open image file embedded resource as `byte[]` for MAUI Blazor application to display it using `<img>` tag using `base64 `encoding. Btw the original stream returns just `string` _**(why?)**_ are embedded resources supposed to be string content by default?

Allocating the specified amount of bytes for the `MemoryStream` to prevent memory fragmentation is not possible - `stream.Length` doesn't work on the original stream.

### Steps to Reproduce

```
var stream = await FileSystem.OpenAppPackageFileAsync(filePath);
var ms = new MemoryStream((int)stream.Length); //crash -> Length not supported

```

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

probably all

**Comment by Eilon** [comment]
@janseris as far as I ever researched, on Android it is not possible in general to get the size of an asset, and you just have to open it and read to the end and count the bytes. I tried reading up on it again and it seems that some people have found ways, such as using Android AssetManager and calling the `Open(String, Access)` overload like `assetManager.Open("the_resource", Access.Random)`, and then perhaps the stream's Length becomes available? I know on Android it gets tricky because assets are usually compressed, so it doesn't know the length automatically (internally it knows the compressed length, but that isn't useful). I'm still surprised that it doesn't store the uncompressed length as metadata because it seems to me that would be useful quite often.

But, to be honest, I'd be a bit surprised if that `Open()` API actually worked, because a long time ago when I was trying to get the stream length I felt like I'd tried every option, and nothing worked. But I don't remember exactly what I did or didn't try, so maybe this does work. And if it does work, perhaps we should internally use that API in various places in .NET MAUI.

I suggest that if you can determine whether that API actually works as expected on .NET MAUI, we'd certainly consider changing to use it in several places.

**Comment by janseris** [comment]
@Eilon Thank you well I'm not going deep into Android API because I need to keep my app as general as possible - there are so many things to solve and try out besides this little thing.

**Comment by Eilon** [comment]
No worries, I'm not trying to create more work for you 😄 We'll keep this bug open so that we can investigate.

**Comment by VincentBu** [comment]
repro with vs main build(32606.310.main) on android emulator

**Comment by mattleibow** [comment]
One way to avoid this is to see if the stream `CanSeek` as `Length` is a "seeking" operation. Not all platforms support all features - hence the `CanSeek`.

In the case of Android (as @Eilon said) the OS does not actually allow you to see the length because the stream is loaded on-demand.

**Comment by 0xxCodemonkey** [comment]
Hi,
I'm also stumbling over the same problem on Android / MAUI right now.
Is there a general solution how to read all bytes of a filestream (FileSystem.Current.OpenAppPackageFileAsync) platform independent? Or how do I get the bytes on Android?

**Comment by mattleibow** [comment]
@0xxCodemonkey it depends on what you want to do:

- If you want to load an image/file using some API - you might be able to use the Stream directly and pass that
- If you want to just get the file onto disk - you can File.Create to a local/cache location and then CopyAsync
- If you want to get the string contents - you can use the StreamReader and ReadToEnd
- If you really just want raw bytes as you mention - you can create a MemoryStream and then either ToArray (make another copy) or just use the inner array buffer with TryGetBuffer and use that (no copy)

**Comment by 0xxCodemonkey** [comment]
Thanks for the tip, MemoryStream works for me here :) 👍

**Comment by janseris** [comment]
@mattleibow the point of this issue is getting byte[] size before reading it to be able to allocate without memory fragmentation. How can this be done for files in app package?
