### ISSUE TITLE
Entry show without Underline or Bottom line in MAUI GA

### ISSUE THREAD

**Issue by eramrit78** [dotnet/maui#7487]
I m trying a create a hello MAUI app 

<Entry Placeholder="I m a Entry Box" />

but it does not show any underline or bottom line in entry control in Android.
same issue in Editor also.

![Screenshot_1653525528](https://user-images.githubusercontent.com/48124576/170392406-06778d79-0793-4908-9f5f-80eaae959271.png)

![Screenshot_1653525536](https://user-images.githubusercontent.com/48124576/170392412-42c2408a-dc5b-4b93-8592-3da5b1c18dd0.png)

**Comment by angelru** [comment]
The same issue...

**Comment by PureWeen** [comment]
Probably related https://github.com/dotnet/maui/issues/6207

Default Style set to
https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/Resources/Styles/Styles.xaml#L105

**Comment by angelru** [comment]
> Probably related #6207
> 
> Default Style set to https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/Resources/Styles/Styles.xaml#L105

thanks!! i think this should be documented

**Comment by joergpichler** [comment]
This is still an issue with MAUI shipping with VS 17.3 Preview 6.

Any tips on how to work around it and get the underline back on Android?

**Comment by ibrahimlita** [comment]
Working 100% ;
https://github.com/ToolmakerSteve/MauiCustomEntryHandler

**Comment by jhonata0302** [comment]
this happens when setting the background color of the field, removing the background color solved it for me.

before:
![image](https://user-images.githubusercontent.com/15106637/212788233-640279f7-b5c2-4654-b349-9ef68624a53a.png)
![image](https://user-images.githubusercontent.com/15106637/212788386-2ec704a8-717e-471c-a7ab-8d3d092430a6.png)

after:
![image](https://user-images.githubusercontent.com/15106637/212788291-d9b540ef-942c-43e0-a447-ae073776525d.png)
![image](https://user-images.githubusercontent.com/15106637/212788331-e1d5d2a4-9db2-46d2-ae81-fd72190ef669.png)

**Comment by jfversluis** [comment]
I think this is fixed by the current version of the templates
