### ISSUE TITLE
Buttons missing ripple effect in windows?

### ISSUE THREAD

**Issue by AlMcLeanYF** [dotnet/maui#7492]
### Description

The behaviour of buttons is different when the sample app is ran on android emulator and in windows. On android they show a ripple effect when pressed, on windows they don't.

I'm not sure whether this is intended or not

### Steps to Reproduce

Can be reproduced from the standard Maui app.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 11, Windows 10.0.19041.0

**Comment by drasticactions** [comment]
Yeah, it is. MAUI Buttons are based on the platform's buttons. So a Button on Windows will look and act like a button on Windows, and a button on Android will look like Android, etc. That's because they are.

If you want to control those actions, you can look at the docs for how handlers work (https://docs.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize). If you don't want the ripple effect on Android, you can turn it off that way, and it will affect all buttons you make within your application.

**Comment by AlMcLeanYF** [comment]
Brilliant, thanks for the clarification
