### ISSUE TITLE
Not able to switch simulator when enabling MAUI embedding in .NET iOS-project

### ISSUE THREAD

**Issue by andreas-nesheim** [dotnet/maui#7540]
### Description

I was following [this guide](https://github.com/dotnet/maui/pull/5218) to test out embedding MAUI pages into a .NET iOS-project. Once I added the `UseMaui` attribute in my .csproj, I was no longer able to switch deployment target from the "Start" dropdown. It's stuck on the deployment target that was set before I added the attribute. I also experienced sometimes that, when switching between projects and switching back to this project, I wasn't able to deploy at all. I got a deployment error with the output "Please select a valid device before running the application."

### Steps to Reproduce

1. Create a File -> New "iOS Application" (the new .NET 6 template)
2. Select an iOS simulator as deployment target
3. Add the attribute `<UseMaui>true</UseMaui>` to the .csproj
4. Fix the build errors (add using statements)
5. Try to select a different iOS simulator

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

I tried to use some of the [tricks listed here](https://docs.microsoft.com/en-us/dotnet/maui/ios/pair-to-mac#build-ios-apps-from-the-windows-command-line), and with the `-t:Run` argument I was able to deploy via the command line.

**Comment by drasticactions** [comment]
I think this is a single project tooling issue within the IDE.

When you add the `UseMaui` tags, there's logic in the IDE for handling the cases where you would also have multiple target frameworks (TFMs). It could be that by adding the tag, it's assuming that it's also single project and messing up logic under the covers.

That issue can't be fixed in this repo, it should go to the Xamarin Platform team. Could you refile this issue to visual studio feedback (https://developercommunity.visualstudio.com/spaces/8/index.html)? That should also upload logs to help them figure out the issue.

**Comment by andreas-nesheim** [comment]
Ah, I see. I've filed it under Visual Studio feedback per your request.
