### ISSUE TITLE
DisableAsync Permission for Essentials

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#7563]
### Description

Hi,

Currently, there is only an option to RequestPermission as well as CheckPermission of course but there is no option to disable the permission so for example if a developer wants to enable and disable location permission he can only use Essentials for enabling but he must use platform-specific for disabling.

### Public API Changes

```
void SwitchLocation_OnChanged(System.Object sender, Xamarin.Forms.ToggledEventArgs e)
{
    if (e.Value == true)
    {

    }
    else
    {
        await Permissions.DisableAsync<Permissions.LocationWhenInUse>();
    }
}


```

### Intended Use-Case

Disabling permissions such as location, camera, media, phone, etc....

**Comment by ToolmakerSteve** [comment]
Why? You control your app code, if your code stops using a feature, then permission is no longer relevant. In what situation do you need to revoke a permission that has already been granted?

In the specific case of Location, if you stop calling `Geolocation.GetLocationAsync`, then I assume Android's internal logic goes back to its low-power state after its usual time delay (a few seconds IIRC). Though I confess I haven't tested Xamarin Essentials implementation - had written my own before that feature was in Essentials.

**Comment by ToolmakerSteve** [comment]
My point is that you can "revoke" the permission simply by remembering that user has asked the app to stop using it.

Then, you stop running any code that requires the permission. Which is exactly what you would do anyway, right? Or rather, if user attempts any action that would need that permission, you would ask them if they want to permit that again.

Under what scenario, do you consider it necessary to actually revoke the permission at the OS level (rather than simply no longer using that feature)?

**Comment by jrahma** [comment]
But that won't give the user the option to revoke, and when he goes to his Phone settings he can still see that my app has access to Location (for example) and this is a serious privacy concern.

**Comment by jfversluis** [comment]
I don't think this is possible on the underlaying plaforms and therefore we cannot implement this.
