### ISSUE TITLE
Not possible to use the decimal comma on the numeric keyboard in Android.

### ISSUE THREAD

**Issue by geertgeerits** [dotnet/maui#7582]
### Description

It is not possible to enter a comma as decimal point on the numeric keyboard of a Android phone.
So you can not enter a number with decimals in it.
This is a big problem for me because I writing financial programs.

Same happens with installed app on Android phone.
I can't test it on Apple products because I don't have one.

### Steps to Reproduce

1. Run the attached app.
2. Select the Pixel 5 - API 30 Android
3. Set the country of the Android phone to one that uses a comma for decimal point (ex. Dutch-Belgium).
4. Run the app and try to enter a comma on the numeric keyboard.
[MauiAppTestDecimalPoint.zip](https://github.com/dotnet/maui/files/8792989/MauiAppTestDecimalPoint.zip)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Pixel 5 API 30 Android 11.0

### Did you find any workaround?

No

**Comment by geertgeerits** [comment]
[MauiAppTestDecimalPoint.zip](https://github.com/dotnet/maui/files/8792989/MauiAppTestDecimalPoint.zip)

**Comment by Symbai** [comment]
Was about to create an issue myself. I can confirm the issue on my own project. But also the **PERIOD** can only be used once. Maybe @geertgeerits can check that too?

I.e. you can type:
`152.586`
but you cannot type:
`152.568.33`

This is a problem when you have to enter an IP address. Device: Pixel 5, API 31, Android 12

I was also able to test this on device: iPhone 13 iOS 15.4 and it works fine on iOS (PERIOD bug) but cannot test comma because the keyboard does not have a comma on iOS for me:
![image](https://user-images.githubusercontent.com/14368203/170862716-c12768a4-b94b-4770-bc88-a61c856699a0.png)
iOS: ![image](https://user-images.githubusercontent.com/14368203/170862751-add089a6-0e25-4681-9669-7b398335e5c7.png)

**Comment by geertgeerits** [comment]
I can also enter only 1 decimal point when using the numeric keyboard.

**Comment by ToolmakerSteve** [comment]
Unfortunately those behaviors are hardcoded by Android OS, for its Numeric keyboard. There have been many StackOverflow discussions of this for Xamarin Forms.

Sounds like Maui Essentials could use a more flexible numeric-oriented custom keyboard.

**Comment by VincentBu** [comment]
repro with vs main build(32627.411)

**Comment by TRadigk** [comment]
Hi all,

I would like to share my workaround for my scenario, which applies here:

_The user must be able to enter a positive/negative number with two or more decimals_ (typical currency situation).

This being the requirement I started coding a `double ` field in my viewmodel and binding it two way for my `Entry ` in Maui, which also has set Keyboard =Numeric. While testing on windows and using the keyboard, fulfilling the requirement is no issue. But doing so on android is not possible. Entering a "-" in front of the number is ok, but the decimal dot is removed when the next digit is entered.
Looking around the internet for a possible solution point towards implementing a custom android keyboard (with lots of code), sometimes installing Gboard (which doesn't to the trick, at least for this android version [API32]), or even to implement a behaviour for the Entry.

I tried successfully* the following for **german** localization (which might be good for any other country having ',' decimal character):

- `Entry` remains to have keyboard="Numeric"
- the bound field is changed from `double` to `string`**
- the value of `Entry` has '.' replaced with ','
- the value of `Entry` is then cast to `double` in viewmodel 

and 

*tested on android emulator with **german** language settings, as well as on Samsung Galaxy S10 with OneUi4.1 and Android 12 and native Samsung keyboard (in which the ',' is inaccessible).

** though the keyboard is set to Numeric, it is not that easy to enter anything wrong on android ... but one could easily implement an error message with it (required at least for Windows build) using Double.TryCast()

I would like to point out that this approach requires some few tweaks to be able to handle both valid decimal characters or "all" cultures, since from my research we are working around an issue which is present for years and had not been fixed either by Android or the framework supplier. I couldn't even find a definitive answer who is to fix this issue anyway.

**Comment by TWTIC** [comment]
I had the same problem with the german keyboard settings and decided to create my own numeric keyboard as a toolkit popup. I replaced "Entry" by "Label" and use this to display the value from the view model. Since a Label has no events it's embedded in an invisibible border that has a Tapped handler. I use the same handler for all numeric values in a view.

`
            <Border Grid.Row="3" Grid.Column="0" x:Name="InputAnzahl" StrokeThickness="0">
                <Border.GestureRecognizers>
                    <TapGestureRecognizer Tapped="InputSelected"/>
                </Border.GestureRecognizers>
                <Label x:Name="TextAnzahl" 
                   BackgroundColor="BlanchedAlmond"
                   HorizontalOptions="Fill" 
                   VerticalOptions="FillAndExpand"
                   HorizontalTextAlignment="End"
                   VerticalTextAlignment="Center"
                   Text="{Binding ArtikelListePos.Anzahl, StringFormat='{0:F3}'}"
                   Padding="5"/>
            </Border>
`
This requires a bit more code in code behind, but I can live with this.
`
    private async void InputSelected(object sender, EventArgs e)
    {
        NumericKeyboardProps props;

        if (sender == InputAnzahl)
        {
            props = new()
            {
                Title = "Eingabe Anzahl",
                Decimals = 3,
                OldValue = vm.ArtikelListePos.Anzahl
            };
            await DisplayKeyboard(props);
            
            if (props.ValueChanged)
            {
                vm.ArtikelListePos.Anzahl = props.NewValue;
                TextAnzahl.Text = String.Format("{0:F3}", vm.ArtikelListePos.Anzahl);
            }
        }
    }

    public async Task DisplayKeyboard(NumericKeyboardProps props)
    {
        var popup = new NumericKeyboard(props);
        await this.ShowPopupAsync(popup);
    }

`
![keyboard](https://user-images.githubusercontent.com/17636274/200854598-d63f23ae-9f59-4632-af73-982111ecf473.png)

**Comment by michaldivis** [comment]
Dealing with this issue is so painful 😞 I've finally managed to resolve it by using a 3rd party editor instead of the default `Entry` control. I'm using the [DevExpress' NumericEdit](https://docs.devexpress.com/MAUI/DevExpress.Maui.Editors.NumericEdit) which works great.

**Comment by RandomMauiDev** [comment]
When is this getting fixed, it's been more than a year since it was first reported?

**Comment by jfversluis** [comment]
I just tried this on .NET 8, and I think it's resolved there, can someone confirm? @geertgeerits?

Please tag me or close this issue directly if it's indeed resolved in .NET 8

**Comment by marcmognol** [comment]
Hi @jfversluis !

I test my use case and now it works.
For me issue was decimal value wasn't working when system language different than English. Now with French it works ok.

Thank you very much MAUI team.

Marc

**Comment by geertgeerits** [comment]
> I just tried this on .NET 8, and I think it's resolved there, can someone confirm? @geertgeerits?
> 
> Please tag me or close this issue directly if it's indeed resolved in .NET 8

Hi, I can confirm that it works as it should. Thank you.

**Comment by jfversluis** [comment]
Glad to hear, thanks for letting us know!

**Comment by TRadigk** [comment]
I also can confirm for german keyboard / android emulator now the decimal comma now has taken the job of the dot. Setting up english keyboard / emulator the dot is the decimal separator. This now works as expected, thanks Maui Team!
