### ISSUE TITLE
Application.Current.Resources  no keys available

### ISSUE THREAD

**Issue by HausBJB** [dotnet/maui#7585]
### Description

Hello, everyone,

I tried to load a style from code, unfortunately the ResourceDictionary shows me that it has 35 objects but no single key or value.

I don't know if I'm doing something wrong, but I can't load a style with a key

![image](https://user-images.githubusercontent.com/53478848/170870985-3828c3da-76d6-4144-bc6f-165d99cd9b94.png)
![image](https://user-images.githubusercontent.com/53478848/170871008-cdec2d95-1dd0-4cc2-af9f-62bc3ead9b24.png)
![image](https://user-images.githubusercontent.com/53478848/170871085-bab67db6-2060-4c36-bc5b-0800287c28ad.png)

### Steps to Reproduce

1. Create Maui App
2. Add Button in MainPage
3. Add code
```
    private void Button_Clicked(object sender, EventArgs e)
    {
		var res = Application.Current.Resources.MergedDictionaries.FirstOrDefault() as ResourceDictionary;

		if(res.ContainsKey("Primary"))
                {
        
                }
    }
```

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android API 31

**Comment by ToolmakerSteve** [comment]
Why do you do `.MergedDictionaries.FirstOrDefault()`?

Just look up key in `Application.Current.Resources` - that is the merger of the merged dictionaries.

**Comment by HausBJB** [comment]
Hello,
that doesn't work either, the key is simply not to be found

![image](https://user-images.githubusercontent.com/53478848/171098191-d01ee5ba-d559-495e-97ea-8ece2b74bffc.png)

**Comment by VincentBu** [comment]
repro with vs main build 32609.239. I also run into this issue on Windows

**Comment by breenbob** [comment]
This is happening for me also. We have a bunch of custom controls in a package that we reuse. We use keys to allow the controls to be styled to customer apps from App.xaml/other Xaml based theme. The controls are all throwing exceptions because the style Keys don't exist in Application.Current.Resources, even though they are in the MergedDictionaries.

I see same odd behaviour in that the item count for Resources shows as 0. This line throws an exception even though that key is in one of the Merged dictionaries:
![image](https://user-images.githubusercontent.com/6000851/177611606-755ce2d4-dc2e-4e0b-9d2e-d398d7999c1b.png)

Only the count of the MergedDictionaries shows a value, and they still show no Keys or Values.
![image](https://user-images.githubusercontent.com/6000851/177611880-3d6a1d1f-647d-463d-8135-9c69badc4611.png)

Though "Results View" in intellisense does list items:
![image](https://user-images.githubusercontent.com/6000851/177611929-6808f0b5-20eb-454d-8b93-6d5bfd22e4fb.png)

**Comment by BenBtg** [comment]
I've been working with a customer who is also seeing this issue.

**Comment by yvdh** [comment]
I am seeing the same thing: merged dictionary keys are not visible in the overall collection ...

**Comment by manuelesvi** [comment]
Same issue here. Application level styles are not being found using Application.Current.Resources straight.
