### ISSUE TITLE
Bug with Hot Reload : Different layout screen without applying any modification to it

### ISSUE THREAD

**Issue by dedet6** [dotnet/maui#7603]
### Description

When I run the application with the hot reload without applying any modification to it, the graphic layout of my elements is modified and I end up with a different layout even though I have not applied any modification.

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Add graphics elements
3. Set margin on this graphics elements
4. Run the application using Hot Reload

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

I don't use any margin for my applications, only width and height. However, my application is therefore no longer responsible.

**Comment by drasticactions** [comment]
I'm confused by what your issue is here. If I understand you correctly, you have an image and you added a margin to it, and it looks different than if you didn't add the margin... which seems correct? I have no idea how Hot Reload affects this?

Could you make a reproduction project and the exact steps you are running here, including what you expect to see? Also, if you turn off Hot Reload does it do the same thing?

**Comment by ToolmakerSteve** [comment]
I'd like to emphasize **if you turn off Hot Reload does it do the same thing?**.

If you get the same result, then it isn't a Hot Reload issue.

----------------------------

Also, "different layout" compared to *what*? Until you run it, there is nothing to compare it to.

Are you trying to say that you didn't get the layout you **expected**?
