### ISSUE TITLE
Changing the UserAppTheme does not change the colours appropriately 

### ISSUE THREAD

**Issue by ghost** [dotnet/maui#7664]
### Description

By following the steps given [here](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/system-theme-changes), I set the UserAppTheme to Light and I expect my App to only run in Light mode despite the PlatformAppTheme. 
```csharp
public App()
{
    InitializeComponent();
    this.UserAppTheme = AppTheme.Light;
    MainPage = new MainPage();
}
```

This is not the case though. If we are using AppThemeBinding the colours are evaluated against UserAppTheme but if we aren't using AppThemeBinding they are evaluated against PlatformAppTheme.

I have made a basic project to showcase the issue. 
There are 2 Labels in the Main Page:
- The first is using the default TextColor
- The second one changes the TextColor with AppThemeBinding

Both of them should be black but the first one isn't when we have Dark mode enabled on our device. That's because the first label depends on PlatformAppTheme instead of UserAppTheme.

[MauiApp1.zip](https://github.com/dotnet/maui/files/8812726/MauiApp1.zip)

### Steps to Reproduce

1. Download my sample application
2. Change your device's theme to Dark
3. Run the app and witness the colours on both controls
4. Both Labels' TextColor should be black but the first is white

Expected Result:
![image](https://user-images.githubusercontent.com/93717765/171417539-49e02090-c4d5-40bb-a260-5376084a9c1b.png)

Actual result:
![image](https://user-images.githubusercontent.com/93717765/171417400-aa4ec55e-efed-474b-9525-963a20976d91.png)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 11, Windows SDK 10

### Did you find any workaround?

The workaround is to always use AppThemeBinding.

**Comment by kristinx0211** [comment]
can be repro on android 12 with 17.3.0 Preview 2.0 [32601.361.main].
![image](https://user-images.githubusercontent.com/99457000/171580883-a2505a61-df2e-4ee1-b0bc-9fc5314d6019.png)

**Comment by FM1973** [comment]
Still a problem in my opinion.
I tried to set the theme using:
`Application.Current.UserAppTheme = AppTheme.Light;`
which doesn´t make a change. I.e. the trackcolor of the switch is still white on a real device using darkmode, although it shoul be gray using the light theme.

What I did as a workaround was using a handler to change the tracker color (in my case on Android).

`Microsoft.Maui.Handlers.SwitchHandler.Mapper.AppendToMapping("SwitchCustomization", (handler, view) =>
        {
            if (view is Switch)
            {
#if ANDROID
                handler.PlatformView.TrackTintList = ColorStateList.ValueOf(Color.Gray);
#endif
            }

        });`

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 7.0. Repro on Windows 11 and Android 13.0 with below Project:
[7664.zip](https://github.com/dotnet/maui/files/11459895/7664.zip)

![image](https://github.com/dotnet/maui/assets/97647558/cc8238b8-40ea-4f92-93fe-ce02bb6bef81)

![image](https://github.com/dotnet/maui/assets/97647558/141ace2e-1875-43d8-bf4c-5f19d96ab823)

**Comment by BretJohnson** [comment]
I've spent some time investigating this. For the two repro projects attached - the original one and the one recently attached by @XamlTest - the problem was that the `Styles.xaml` file wasn't included (the first sample project) or wasn't properly referenced from `App.xaml` (the @XamlTest attached project). Once that's fixed up, the theming works much better, including 
the UserAppTheme override. Without Styles.xaml present, controls use the OS default for the theming - and indeed don't support the UserAppTheme override. MAUI apps normally have `Styles.xaml` - it's there by default when creating a new MAUI app; for migrated Xamarin,Forms apps, you can supply it manually by copying it from a new MAUI app, if you want to use the MAUI styling and theming support.

@XamlTest  - I'm curious how you created a test MAUI app, like the one you attached, without Styles.xaml and shell present (as those are included in our new app template). What steps did you follow to create that test app - what was the starting point? I only ask in case there's some other scenario we should fix up (with templates, doc, or whatever) to help ensure that Styles.xaml is always included.

@Giuseppetm, @RonnyRos, others - with `Styles.xaml` in place and referenced from `App.xaml`, do you think there's anything else broken here? If not, we'll close this issue. But I do want to make sure there are no other problems - it worked for me, but I'm not ruling out there being some other issue, given the number of customers commenting on this.

@FM1973 - Your issue should be helped (I suspect) by https://github.com/dotnet/maui/pull/10758.

**Comment by XamlTest** [comment]
@BretJohnson We're just doing a bulk re-triage of issues to see if latest changes affected the behavior at all.

I am creating MAUI app with the new template, and then update the app according to the first sample project [MauiApp1.zip](https://github.com/dotnet/maui/files/8812726/MauiApp1.zip), but seems I missed something, after referenced Style.xaml from App.xaml, both Labels' TextColor are black.

![image](https://github.com/dotnet/maui/assets/97647558/d5239191-a762-4931-a1de-ebbf739594d5)

**Comment by BretJohnson** [comment]
@XamlTest - so it sounds like things are working properly for you now, with the updated App.xaml. Good deal.
