### ISSUE TITLE
Black area above and below the application with iOS

### ISSUE THREAD

**Issue by dedet6** [dotnet/maui#7721]
### Description

When I run my app on iOS there is a black area above and below the app. Therefore, the application is not displayed on the entire screen.

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Run the app on iOS
3. Observe the bug

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

### Did you find any workaround?

On an ipad there are no such black areas, it's only on iphones.

**Comment by jfversluis** [comment]
Hey there, thanks for the report! Unfortunately, the information in this issue is not enough to effectively diagnose the issue. If this is something a lot of people were hitting, which people would if this happens with just a File > New Project, we would see much more engagement on this issue or multiple similar issues. This makes me think that it has to be something more local to your project or development environment.

I'm going to close this for now. If this is still something that impacts you, please open a new issue with more relevant logs or ideally a reproduction project. At the very least a screenshot of what you are seeing would already greatly help.

Thanks
