### ISSUE TITLE
Vertical scrolling in <ScrollView Orientation="Both"> not working

### ISSUE THREAD

**Issue by usa-** [dotnet/maui#7811]
### Discussed in https://github.com/dotnet/maui/discussions/7796

<div type='discussions-op-text'>

<sup>Originally posted by **usa-** June  6, 2022</sup>
I start VS 2022 version 17.3.0 preview 1.1 (the latest one).
I create a new “.NET MAUI App” project.
In the MainPage.xaml file, I change the code inside the ContentPage element to the following:

```
    <ScrollView Orientation="Both">
        <Image Source="dotnet_bot.png" HeightRequest="1000" WidthRequest="1000" Aspect="AspectFit" />
    </ScrollView>
```

In the code-behind file, MainPage.xaml.cs, I delete the OnCounterClicked function.
In the debug destination drop-down list, I select the Android Emulator.
I run the application.
Expected behavior: I am able to scroll the image both vertically and horizontally.
Actual behavior: I am able to scroll the image only horizontally.</div>

**Comment by flipper09112** [comment]
+1

**Comment by xtuzy** [comment]
Today i also find it, dont' work at Android, work at Windows.

https://user-images.githubusercontent.com/17793881/188343081-b19055be-1bac-4002-96a9-54e2a2565d11.mp4

**Comment by ycaktirma** [comment]
I encountered this issue when trying to present tabular data in my application. I had to use ScrollView with Orientation property set to "Both" (So users can see the all data).
It didn't work. I found a temporary solution. You can't scroll diagonally but vertical and horizontal scrolls are working fine. Instead of creating one ScrollView and set its Orientation to "Both", we will create two of them. One is responsible for vertical scrolls and the other one is for horizontal scrolls.

1) Create  a ScrollView and set its Orientation to Vertical.
2) Create a ScrollView and set its Orientation to Horizontal
3) Set horizontal ScrollView's parent to vertical one. (If you set verticals parent to horizontal, it won't work. I don't know why.)

I am developing the UI without XAML. So I can only give an example in C#.
```csharp
var scrY = new ScrollView();
scrY.Orientation = ScrollOrientation.Vertical;

var scrX = new ScrollView();
scrX.Orientation = ScrollOrientation.Horizontal;

scrX.Parent = scrY;
scrY.Content = scrX;

var table = new VerticalStackLayout();
table.Parent = scrY;
scrX.Content = table;
```

I am using VerticalStackLayout as content.

I didn't test it using XAML but i guess it will be okay.

Note: I only tested in Android Emulator. Idk if it is working on windows or ios or any other platform.

https://user-images.githubusercontent.com/39536700/193585029-d06a3d7f-f0b1-4f7e-b0d2-18325c33de82.mp4

**Comment by PetroniloDev** [comment]
Probé esto y funcionó bien de arriba abajo

<ScrollView Orientation="Vertical">
           <ScrollView Orientation="Horizontal">
      </ScrollView>
    </ScrollView>
    
Luego hice esto y pude moverlo en diagonal, una maravilla 

<ScrollView Orientation="Vertical">
           <ScrollView Orientation="Both">
      </ScrollView>
    </ScrollView>

**Comment by PetroniloDev** [comment]
Primero hice esto, y se movió de arriba abajo bien
`<ScrollView Orientation="Vertical">
   
        <ScrollView Orientation="Horizontal">
       </ScrollView>
    </ScrollView>`
    
    Y luego hice esto, y se pudo mover en diagonal :D
`<ScrollView Orientation="Vertical">
   
        <ScrollView Orientation="Both">
       </ScrollView>
    </ScrollView>`

**Comment by tranb3r** [comment]
Any update ?

**Comment by usa-** [comment]
I doubt that there will be any :) I have moved my project to Android Studio / Kotlin, so now I know, that MAUI controls are wrappers around native Android controls with the same names, and the Android's ScrollView ir the one having the issue. If the developers of MAUI create a workaround using a combination of another controls, it will have another issues for sure.

**Comment by tranb3r** [comment]
> I doubt that there will be any :) I have moved my project to Android Studio / Kotlin, so now I know, that MAUI controls are wrappers around native Android controls with the same names, and the Android's ScrollView ir the one having the issue. If the developers of MAUI create a workaround using a combination of another controls, it will have another issues for sure.

But it works in xamarin forms, so surely it can be fixed in maui...

**Comment by xiaoyuvax** [comment]
> I doubt that there will be any :) I have moved my project to Android Studio / Kotlin, so now I know, that MAUI controls are wrappers around native Android controls with the same names, and the Android's ScrollView ir the one having the issue. If the developers of MAUI create a workaround using a combination of another controls, it will have another issues for sure.

met the same problme, but what is that "workaround"?  
@usa-
