### ISSUE TITLE
MAUI : LogMessage are not showing up anywhere

### ISSUE THREAD

**Issue by nssidhu** [dotnet/maui#7821]
### Description

I am using  Inject ILogger and writing log message, but i don't see any output anywhere.

public ILogger<Index> _Logger { get; set; }

```
 protected override Task OnInitializedAsync()
{
    _Logger.LogInformation("Log Message from ILogger");
    System.Diagnostics.Debug.WriteLine("Log Message from Diganostic");
    Console.WriteLine("Log Message from console");
}
```

Is there something else to be configured in Blazor MAUI ?

### Steps to Reproduce

1) Create Blazor MAUI App
2) In Index Page, after injecting the ILogger, inside OnInitializedAsync event 

```
protected override Task OnInitializedAsync()
{
    _Logger.LogInformation("Log Message from ILogger");
    System.Diagnostics.Debug.WriteLine("Log Message from Diganostic");
    Console.WriteLine("Log Message from console");
}
```

     

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android emulator 

### Did you find any workaround?

No

### Relevant log output

```shell
None
```

**Comment by javiercn** [comment]
@nssidhu thanks for contacting us.

Are you configuring a logging provider? Unlike asp.net core or blazor webassembly, I don't believe .NET Maui apps register a default ILoggerProvider implementation.

**Comment by nssidhu** [comment]
> @nssidhu thanks for contacting us.
> 
> Are you configuring a logging provider? Unlike asp.net core or blazor webassembly, I don't believe .NET Maui apps register a default ILoggerProvider implementation.

No I am not doing anything extra when compared to Blazor Wasm.
Any links to documents which tell about how to configure it ?

**Comment by Eilon** [comment]
I just started taking a look at this and here's what I've found so far. I've tested a default MAUI / MAUI Blazor app by selectively adding certain loggers (or none at all) in `MauiProgram.cs` like so:

```c#
services.AddLogging(logging =>
{
    logging.AddDebug();
    //logging.AddConsole();
    //logging.AddSimpleConsole();
    //logging.AddSimpleConsole(o => o.ColorBehavior = LoggerColorBehavior.Disabled);
});
```

| Logger | Windows | Android | iOS | MacCatalyst |
|---|---|---|---|---|
| Default (None) | None | None | None | None |
| Debug | VS Output<br>`NS.ClassName: Information: TheLogMessage` | VS Output<br>`[0:] NS.ClassName: Information: TheLogMessage` | ? | ? |
| Console | None | VS Output<br>`[DOTNET] [40m[32minfo[39m[22m[49m: NS.ClassName[0]`<br>`[DOTNET]       TheLogMessage` | ? | ? |
| SimpleConsole | None | VS Output<br>`[DOTNET] [40m[32minfo[39m[22m[49m: NS.ClassName[0]`<br>`[DOTNET]       TheLogMessage` | ? | ? |
| SimpleConsole(Color=Disabled) | None | VS Output<br>`[DOTNET] info: NS.ClassName[0]`<br>`[DOTNET]       TheLogMessage` | ? | ? |

Notes:
* By default, MAUI apps have no default log sinks at all: https://github.com/dotnet/maui/blob/8d9d5f8540ad26c149338f5719e818b5caf4e5b7/src/Core/src/Hosting/MauiAppBuilder.cs#L179-L186
* For Android, Console/SimpleConsole appear to be emitting [ANSI color codes](https://en.wikipedia.org/wiki/ANSI_escape_code), which causes the output to be hard to read, because the VS output window does not support ANSI color codes.
* I believe we should eventually come up with a set of loggers+options that work "out of the box" for all MAUI configurations, and enable them _in the template_, wrapped in `#if DEBUG ... logging.AddMauiLogging() ... #endif`, so that it has no default cost in MAUI itself, and is trivial for developers to tweak, if needed.

**Comment by nssidhu** [comment]
@Eilon 

Thanks for looking at this.

 I really Like the Blazor Hybrid approach over XAML Native, this is opening up the doors for Web Developers to write Native Mobile Apps as well ability to write once and run everywhere.

!! Great work and kudos to entire team !!

Few question 

I had to use **_builder_** prefix to service, which is different than what you have provided above.

```
 builder.Services.AddLogging(logging =>
        {
            logging.AddDebug();
            //logging.AddConsole();
            //logging.AddSimpleConsole();
            //logging.AddSimpleConsole(o => o.ColorBehavior = LoggerColorBehavior.Disabled);
        });
```
        
   Do I need to install any nuget package to get this working ?
   
   Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'ILoggingBuilder' does not contain a definition for 'AddDebug' and no accessible extension method 'AddDebug' accepting a first argument of type 'ILoggingBuilder' could be found (are you missing a using directive or an assembly reference?)

**Comment by Eilon** [comment]
@nssidhu for the Debug logger, add a reference to this package: https://www.nuget.org/packages/Microsoft.Extensions.Logging.Debug

And you're right, in my case I had an extra variable to shorten the syntax. By default in MauiProgram.cs you would need to do `builder.Services...`.

**Comment by Eilon** [comment]
The grid above is now filled out.

**Comment by Eilon** [comment]
Thinking about this further, I'm not sure it's a great idea to have a built-in helper in .NET MAUI, because it would require adding dependencies to more packages:

```csproj
	  <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="6.0.0" />
```

But it would also be quite ugly to have something like this in the project templates in `MauiProgram.cs`:

```c#
#if DEBUG
#if WINDOWS
        builder.Logging.AddSimpleConsole(o => o.ColorBehavior = Microsoft.Extensions.Logging.Console.LoggerColorBehavior.Disabled);
#else
        builder.Logging.AddDebug();
#endif
#endif
```

It's ugly enough to have `#if`'s, but having nested `#if`'s with conditions? Yikes!

**Comment by Eilon** [comment]
Not sure what I was thinking earlier, but for some reason I thought we needed to conditionally add debug vs. console loggers. I completely forgot that the Debug logger just works everywhere!

So my proposal is quite simple:

The various .NET MAUI project templates need two changes:

1. Add a reference in the CSPROJ to `<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="6.0.0" />`
1. Add these lines of code to `MauiProgram.cs`:
   ```c#
   #if DEBUG
   		builder.Logging.AddDebug();
   #endif
   ```

And that will enable a good default logging experience on every platform.

The code of the `Microsoft.Extensions.Logging.Debug` reference should be trivial because it brings in no real new dependencies (it depends on other things that are already referenced in all .NET MAUI projects), and the amount of code in it is trivial (a few dozen lines of mostly uninteresting code): https://github.com/dotnet/runtime/tree/main/src/libraries/Microsoft.Extensions.Logging.Debug/src

**Comment by Eilon** [comment]
PR to call `AddDebug()` in the project template: https://github.com/dotnet/maui/pull/8180
