### ISSUE TITLE
Slider Disabled style is inconsistent

### ISSUE THREAD

**Issue by pierre01** [dotnet/maui#7882]
### Description

The slider style in styles.xaml is inconsistent with the styles

![image](https://user-images.githubusercontent.com/2603287/172814201-2cab0824-895e-42b7-8fb8-47f4934d6724.png)

### Steps to Reproduce

Try to modify the Slider style in Styles.xaml to get the expected result above

The track is only a single color. regardless of the MinimumTrackColor and MaximumTrackColor values

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11 API 30 - Windows 11 Pro 22000.348

### Did you find any workaround?

No

**Comment by rachelkang** [comment]
Hi, @pierre01 - thanks for reporting this behavior! On appearance, it seems that the `MinimumTrackColor` is not getting applied to the control when it is disabled.

After some investigation, however, I've found that this is actually exactly the expected behavior, and the Android platform itself behaves in the same exact way. The reasoning behind this design is likely due to user interaction and accessibility; if the minimum and maximum track colors differ, the slider is made to look interactive, which is misleading to users since it is not interactive when it is disabled. 

Hope this is helpful! Let me know if you have any further questions.

**Comment by pierre01** [comment]
Thanks Rachel. It is not a big deal but inconsistent with windows where the sliders appear as expected.
This is on Windows:
![image](https://user-images.githubusercontent.com/2603287/174004401-41fe3168-e17d-4430-b8e2-e990499641c5.png)

This is on Android:
![image](https://user-images.githubusercontent.com/2603287/174004698-0522e064-5d99-4773-a7bf-6c6e9672798f.png)

**Comment by rachelkang** [comment]
@pierre01 You may be interested in checking out [AlohaKit](https://github.com/jsuarezruiz/AlohaKit), which is all drawn controls, and therefore can be used to render any behavior you wish

**Comment by pierre01** [comment]
@rachelkang Thank you for nudging me toward the Graphics API. It was an easy workaround, much more logical than using a disabled slider... Now, I need to make it look good.
Thank you!
![image](https://user-images.githubusercontent.com/2603287/175519952-8728a9ca-325a-4158-b002-5954a7a07b41.png)

**Comment by rachelkang** [comment]
Awesome!!! I'm happy to see/hear that - thanks for sharing :)
