### ISSUE TITLE
Dynamically changing view in ContentView content shows empty page (Android)

### ISSUE THREAD

**Issue by Quietscheente** [dotnet/maui#8040]
### Description

For my viewmodel first approach I use a ValueConverter to convert my viewmodels to views and display them in a

`<ContentView Content="{Binding CurrentPage, Converter={x:Static valueconverters:ViewModelToViewConverter.Instance}}"/>`

In the latest VS version (dotnet 6.0.400-preview.22301.10) this does not work anymore for Android, but worked before. It only shows empty space. Windows app works as expected.

### Steps to Reproduce

1. Create a viewmodel first app
2. convert the current viewmodel with a valueconverter to a `ContentView` and set it as a binding in a ContentView-Content
3. Changes in the current viewmodel result in an empty page

I will upload a short example that shows the bug

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Emulator Pixel 5 and local device Android 12

### Relevant log output

_No response
[ViewModelToViewConverter.zip](https://github.com/dotnet/maui/files/8908135/ViewModelToViewConverter.zip)
_

**Comment by Quietscheente** [comment]
[ViewModelToViewConverter.zip](https://github.com/dotnet/maui/files/8908125/ViewModelToViewConverter.zip)

**Comment by kristinx0211** [comment]
verified repro on android, can works on windows.

**Comment by hartez** [comment]
We should verify whether this is still a problem after #8136.

**Comment by Palku** [comment]
@hartez : If someone can write an easy minimal guide to develop with nightly builds which i guess contain #8136 we could try these things ourselves.
We've currently run into almost everything related to 8136 and would really like to try out the fix as soon as possible.

Our product has a hard deadline in two weeks and this is really frustrating.
Would be super nice with binaries of nightly and that the dotnet workload tooling supported going into nightly branch instead of "stable"
