### ISSUE TITLE
Pin target MAUI workload by using rollback file

### ISSUE THREAD

**Issue by ScofieldOY** [dotnet/maui#8066]
### Description

Since we updated to GA and stopped using the rollback files, that the incremental MAUI workload updates have started introducing problems due to the Telerik packages we are consuming... don't have the latest version match with it. so I wonder if we still can use the rollback file to lock GA MAUI version.

**Before**
MAUI workload  6.0.312 works well with Telerik lib: Telerik.UI.for.Maui.Trial.1.0.1
**After**
dotnet workload restore --source [https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json](https://aka.ms/dotnet6/nuget/index.json%C2%A0--source%C2%A0https://api.nuget.org/v3/index.json)

MAUI workload has been upgrade to 6.0.400 after I run the above cmd... but the 400 need higher version of Telerik lib instead of 1.0.1

### (Public) API Changes

N/A

### Usage Scenarios

> dotnet workload restore --from-rollback-file https://aka.ms/dotnet/maui/[some version].json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json

### Backward Compatibility

N/A

### Difficulty

Low

**Comment by ScofieldOY** [comment]
using this one to lock/pin the target MAUI workload:
mauiRollbackLink: https://aka.ms/dotnet/maui/6.0.300.json

**Comment by calebcartwright** [comment]
Scofield I suspect we can close this now given that newly provided rollback link has been working for us consistently and the original ask of the issue was for such a rollback file.

Hopefully the rollback files will continue to be provided and supported for newer SDK/workload versions, and those will be well documented/broadcast, but I don't know if there's anything else we'll need in the short term via this particular issue.

**Comment by ScofieldOY** [comment]
Closed by using mauiRollbackLink as workaround

**Comment by mobilewares** [comment]
Hi - 
I can't seem to get this working, urgently need to rollback MAUI to 6.0.300 (or similar) as the 6.0.400 (Android release) has completely broken my App. 

When I run (Attempting to get back to 6.0.300) : 
dotnet workload restore --from-rollback-file https://aka.ms/dotnet/maui/**6.0.300.json** --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json

I get this response/error :

Installing workloads:

Downloading **microsoft.net.sdk.android.manifest-6.0.400.msi.x64 (32.0.301)**
Workload installation failed. Rolling back installed packs...
**Workload installation failed: One or more errors occurred. (microsoft.net.sdk.android.manifest-6.0.400.msi.x64::32.0.301 is not found in NuGet feeds https://aka.ms/dotnet6/nuget/index.json;https://api.nuget.org/v3/index.json".)** 

So it appears to just be ignoring the 6.0.300 manifest and trying to install the 6.0.400 android manifest anyhow (and then failing on that)...

Did I not understand the instructions above - or is it just not possible to do this rollback to the last stable Android workloads?

Thanks in advance for anyone that can help - I really want to get back to dev on my MUAI project, waiting another 1-2 weeks for another VS22 release would be sad!

**Comment by calebcartwright** [comment]
I'll assume it's not and that you just added the asterisks for effect in the comment. The only other thing I'd suggest validating is that you're actually using a .300 sdk. We utilize a global.json file that pins the actual sdk version too, and the combination of that and the rollback file for the workload specification has been working fine for us

**Comment by ScofieldOY** [comment]
Just as Caleb mentioned, please check if you have global.json in your local
`{
  "sdk": {
    "version": "6.0.300",
    "rollForward": "disable"
  }
}`
and run this cmd to pin GA version
`dotnet workload restore --from-rollback-file https://aka.ms/dotnet/maui/6.0.300.json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json`

**Comment by mobilewares** [comment]
Hi ScofieldOY & calebcartwright - 
Thanks for your answers & help... It's still not working as expected. 

I'm assuming if all OK I can run from VS2022 17.3 Preview 2.0 to my Android emulator on Windows - or have I got this wrong & this is for some other usage (ie. launching from command line or for pipelines)?

Some notes below where I'm at.

> I'll assume it's not and that you just added the asterisks for effect in the comment.

Yes - I was just trying to make this bold for the post - no *'s are included...

> Just as Caleb mentioned, please check if you have global.json in your local
> `{ "sdk": { "version": "6.0.300", "rollForward": "disable" } }`

Thanks - I did not have this global.json/know about it.. I've added it to the project and it seems to have fixed the donet workload part at least. 

Here is the output now : 

```
>dotnet workload restore --from-rollback-file https://aka.ms/dotnet/maui/6.0.300.json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
Installing workloads: ios maccatalyst

Skipping NuGet package signature verification.
Downloading microsoft.net.sdk.android.manifest-6.0.300.msi.x64 (32.0.301)
Downloading microsoft.net.sdk.ios.manifest-6.0.300.msi.x64 (15.4.303)
Downloading microsoft.net.sdk.maccatalyst.manifest-6.0.300.msi.x64 (15.4.303)
Downloading microsoft.net.sdk.macos.manifest-6.0.300.msi.x64 (12.3.303)
Downloading microsoft.net.sdk.maui.manifest-6.0.300.msi.x64 (6.0.312)
Downloading microsoft.net.sdk.tvos.manifest-6.0.300.msi.x64 (15.4.303)
Downloading microsoft.net.workload.mono.toolchain.manifest-6.0.300.msi.x64 (6.0.5)
Downloading microsoft.net.workload.emscripten.manifest-6.0.300.msi.x64 (6.0.4)
Downloading Microsoft.iOS.Sdk.Msi.x64 (15.4.303)
Installing Microsoft.iOS.Sdk.15.4.303.0-x64.msi ...... Done
Downloading Microsoft.iOS.Windows.Sdk.Msi.x64 (15.4.303)
Installing Microsoft.iOS.Windows.Sdk.15.4.303.0-x64.msi ...... Done
Downloading Microsoft.iOS.Ref.Msi.x64 (15.4.303)
Installing Microsoft.iOS.Ref.15.4.303.0-x64.msi .... Done
Downloading Microsoft.iOS.Runtime.ios-arm.Msi.x64 (15.4.303)
Installing Microsoft.iOS.Runtime.ios-arm.15.4.303.0-x64.msi ..... Done
Downloading Microsoft.iOS.Runtime.ios-arm64.Msi.x64 (15.4.303)
Installing Microsoft.iOS.Runtime.ios-arm64.15.4.303.0-x64.msi ..... Done
Downloading Microsoft.iOS.Runtime.iossimulator-x86.Msi.x64 (15.4.303)
Installing Microsoft.iOS.Runtime.iossimulator-x86.15.4.303.0-x64.msi ..... Done
Downloading Microsoft.iOS.Runtime.iossimulator-x64.Msi.x64 (15.4.303)
Installing Microsoft.iOS.Runtime.iossimulator-x64.15.4.303.0.msi ..... Done
Downloading Microsoft.iOS.Runtime.iossimulator-arm64.Msi.x64 (15.4.303)
Installing Microsoft.iOS.Runtime.iossimulator-arm64.15.4.303.0-x64.msi ..... Done
Downloading Microsoft.iOS.Templates.Msi.x64 (15.4.303)
Installing Microsoft.iOS.Templates.15.4.303.0-x64.msi .... Done
Downloading Microsoft.NETCore.App.Runtime.Mono.ios-arm.Msi.x64 (6.0.6)
Downloading Microsoft.NETCore.App.Runtime.Mono.ios-arm64.Msi.x64 (6.0.6)
Downloading Microsoft.NETCore.App.Runtime.Mono.iossimulator-arm64.Msi.x64 (6.0.6)
Downloading Microsoft.NETCore.App.Runtime.Mono.iossimulator-x64.Msi.x64 (6.0.6)
Downloading Microsoft.NETCore.App.Runtime.Mono.iossimulator-x86.Msi.x64 (6.0.6)
Downloading Microsoft.NET.Runtime.MonoAOTCompiler.Task.Msi.x64 (6.0.6)
Downloading Microsoft.NET.Runtime.MonoTargets.Sdk.Msi.x64 (6.0.6)
Downloading Microsoft.MacCatalyst.Sdk.Msi.x64 (15.4.303)
Installing Microsoft.MacCatalyst.Sdk.15.4.303.0-x64.msi ..... Done
Downloading Microsoft.MacCatalyst.Ref.Msi.x64 (15.4.303)
Installing Microsoft.MacCatalyst.Ref.15.4.303.0-x64.msi .... Done
Downloading Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.Msi.x64 (15.4.303)
Installing Microsoft.MacCatalyst.Runtime-arm64.15.4.303.0-x64.msi ..... Done
Downloading Microsoft.MacCatalyst.Runtime.maccatalyst-x64.Msi.x64 (15.4.303)
Installing Microsoft.MacCatalyst.Runtime-x64.15.4.303.0.msi ..... Done
Downloading Microsoft.MacCatalyst.Templates.Msi.x64 (15.4.303)
Installing Microsoft.MacCatalyst.Templates.15.4.303.0-x64.msi .... Done
Downloading Microsoft.NETCore.App.Runtime.Mono.maccatalyst-arm64.Msi.x64 (6.0.6)
Downloading Microsoft.NETCore.App.Runtime.Mono.maccatalyst-x64.Msi.x64 (6.0.6)
Warning: Workload garbage collection failed with error: An item with the same key has already been added. Key: (Microsoft.NET.Runtime.MonoAOTCompiler.Task, 6.0.6).

Successfully installed workload(s) ios maccatalyst.
```
I'm not sure why it has that warning and just says it installed the ios maccatalyst on there - it's possible I never had maccatalyst included at all as I've been working on this MAUI version since a while ago and maybe macOS wasn't supported at that point and never included.

**However, when I load up VS2022 (17.3 Preview 2.0)** - it appears to still be trying to use the 6.0.400 SDK for MAUI and then also trying to get me to Nuget upgrade the Microsoft.Maui.Graphics package (I have edited my CSPROJ file to have 6.0.300 in there). I assume it would compile if I updated the Graphics package - but then solution would be on .400/,403 again which isn't what I want to achieve.

![image](https://user-images.githubusercontent.com/4155775/175204863-b93faefb-f5a6-4e62-a66c-74ecb99f8a3d.png)

![image](https://user-images.githubusercontent.com/4155775/175204821-a9831a4b-48e8-44e0-9880-f3365ef640b4.png)

Also, just to confirm (in case this is an issue) this is correct : the global.json appears in my project now - but has Build Action of 'None'. 

Any ideas here on how to get this working?  Note my primary build target for this project is Android (dev in the Emulators) and then to deploy directly to a Android 12.0 tablet. For time being WIndows/iOS/macOS is not needed on this.

thanks again!

**Comment by calebcartwright** [comment]
Sorry @mobilewares but I don't know the answers to your questions and I don't think this is something Scofield nor myself can really help you with. Fundamentally our need, and the ask of this issue, was for a rollback file that could be used to keep the workload versions pinned within the .300 band, and that ask has been satisfied.

I'd encourage you to open a new issue with all relevant details (probably including your proj file contents as well since it sounds like you've modified them manually) to see if someone from the Maui team can help you with the specifics of your solution/project.
