### ISSUE TITLE
.NET MAUI Templates not showing up - Windows 11, Visual Studio 2022 17.3.0 Preview 1.1

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8076]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-Templates-not-showing-up---Win/10061248)._

---
I installed Visual Studio 2022 17.3.0 Preview 1.1, including the .NET MAUI workload. However, when I search for MAUI to create a new project, no templates are listed. 

I read that there might be a problem with .NET 7, but dotnet --version lists 6.0.300.

Any help would be greatly appreciated!

---
#### Feedback Bot on 6/5/2022, 08:20 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
If the templates are not installed you can run `dotnet new -i Microsoft.Maui.Templates` to still get them. 

We're investigating why the templates are not installed in some instances and will fix that. Since we have multiple issues about this I'm closing this one. Please let us know if you still can't get the templates to show up.
