### ISSUE TITLE
MAUI Shell FlyoutContent Bug

### ISSUE THREAD

**Issue by HenJigg** [dotnet/maui#8148]
### Description

View:

![image](https://user-images.githubusercontent.com/42528522/174427871-1bb3fc38-d459-47d8-b818-cf898cba4ddf.png)

ViewModel:

public partial class AppShell : Shell
{
    public AppShell()
    {
        InitializeComponent();

        this.BindingContext = new AppShellViewModel();
    }
}

public class AppShellViewModel
{
    public AppShellViewModel()
    {
        flyoutItems = new ObservableCollection<string>();
        flyoutItems.Add("Page1");
        flyoutItems.Add("Page2");
        flyoutItems.Add("Page3");
    }

    private ObservableCollection<string> flyoutItems;

    public ObservableCollection<string> FlyoutItems
    {
        get { return flyoutItems; }
        set { flyoutItems = value; }
    }
}

### Steps to Reproduce

[MauiApp3.zip](https://github.com/dotnet/maui/files/8933141/MauiApp3.zip)

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

windows10.0.1904.0

### Did you find any workaround?

NO

**Comment by SarthakGz** [comment]
hmm code doesn't seems correct to me
Since you are explicitly setting Collection view BindingContext to shell this means CollectionView is trying to search FlyoutItems property in Shell class rather then in AppShellViewModel.
Remove line  BindingContext={x:Refrence shell} and you must be good to go I think

**Comment by PentaTech** [comment]
That binding probably comes from https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/shell/flyout
and that is one of many ways you have to change the menu appearence. You can basically change the whole Shell.FlyoutContent with a CollectionView bound to Shell's own FlyoutItems.

If you want to bind the whole menu though not only you have to remove BindingContext={x:Reference shell} but you also need to have at least one FlyoutItem for the first page in xaml otherwise you get a null reference exception

It makes sense since Shell needs to know what the first page is supposed to be but I find the lack of specific examples a bit confusing

[MauiApp31.zip](https://github.com/dotnet/maui/files/8985233/MauiApp31.zip)

**Comment by rmarinho** [comment]
yeah like the above users said the code for the example should be something like:

```
<Shell
    x:Class="MauiApp3.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiApp3"
    x:Name="shell">

    <FlyoutItem>
        <ShellContent ContentTemplate="{DataTemplate local:MainPage}" />
    </FlyoutItem>
    <Shell.FlyoutContent>
        <CollectionView  BindingContext="{x:Reference shell}" ItemsSource="{Binding BindingContext.FlyoutItems}">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Label
                        FontSize="18"
                        Text="{Binding}"
                        TextColor="Black" />
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
    </Shell.FlyoutContent>
</Shell>
```
