### ISSUE TITLE
FilePicker, no title seen, not sure what to expect?

### ISSUE THREAD

**Issue by gfmoore** [dotnet/maui#8173]
### Description

So I'm looking at the filepicker as per https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-picker?tabs=android

I have created a filepicker to get at a json file. I use the PickerTitle and expect to see a heading appear on the screen saying please pick an xxx.json file. 

I get the picker appear, but no sign of a title?  (note on pixel 5 emulator)

Here's my code
```
   //create custom filetypes
    var customFileType = new FilePickerFileType(
      new Dictionary<DevicePlatform, IEnumerable<string>>
      {
          { DevicePlatform.Android, new[] { "application/json" } },
      });

    PickOptions options = new()
    {
      PickerTitle = "", 
      FileTypes = customFileType,
    };

//then I use it
    options.PickerTitle = "Please select friends.json file";  //<--not seeing this anywhere

    await PickFriends(options);

//Here is the code for my picker, getting data from json and writing it to sqlite
  public async Task<FileResult> PickFriends(PickOptions options)
  {
    await App.Friends.DeleteAllFriendsAsync();
    try
    {
      var result = await FilePicker.Default.PickAsync(options);
      if (result != null)
      {
        using var stream = await result.OpenReadAsync();
        var friendsjson = JsonSerializer.Deserialize<List<Friend>>(stream);

        //Go through list and add to db
        foreach(Friend f in friendsjson)
        {
          await App.Friends.SaveFriendAsync(f);
        }


        Console.WriteLine("GM: JSON file data loaded");

      }

      return result;
    }
    catch (Exception ex)
    {
      Console.WriteLine("GM: Ooops in Json : " + ex.Message);
    }

    return null;
  }
```

Here is what I see
![Picker for friends no title](https://user-images.githubusercontent.com/22768967/174582597-b57f8d8c-a04e-4e7c-b098-9fff95cf48fb.png)

It's no big deal, just not what I expected.

### Steps to Reproduce

as above

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Pixel 5 API 30

### Did you find any workaround?

Nope, guess I could show an alert.

### Relevant log output

```shell
none
```

**Comment by jfversluis** [comment]
Thanks for the report! I've checked the code and it seems that the behavior is different per platform.

- iOS & Windows don't seem to use the title at all
- macOS does
- On Android I think it might show when you get the popup to pick an app to pick your actual file. So then it will only show when you have multiple apps installed that can pick a file. If there is only 1 app installed then it will skip that dialog and you'll never see the title. This is due to the nature of Android where you can have a multitude of apps to complete your actions.

I opened an issue for the Docs [here](https://github.com/dotnet/docs-maui/issues/635) so that we can make this a bit clearer, unfortunately there is no technical solution for this unless we would build or complete own filepicker interface which we won't do.

**Comment by gfmoore** [comment]
Good to know and thanks :)
