### ISSUE TITLE
On Android, Setting StringContent to HttpRequestMessage, make "GET" request become "POST" request.

### ISSUE THREAD

**Issue by yzbai** [dotnet/maui#8199]
### Description

I am using Fiddler to capture network traffic from android emulator. And I found when making Get request while setting a StringContent to HttpRequestMessage，in Fiddler，only “Post” request captured。

The Code looks like this:
``` c#
        HttpClient httpClient = new HttpClient();
        string anyUriWillbeOk = "https://github.com/";
        HttpRequestMessage requestMessage = new HttpRequestMessage(HttpMethod.Get, anyUriWillbeOk);

        requestMessage.Content = new StringContent("{}", Encoding.UTF8, "application/json");
        
        HttpResponseMessage responseMessage = await httpClient.SendAsync(requestMessage);
```
This issue is not seen under Windows.

Sample Project:
[MauiApp3.zip](https://github.com/dotnet/maui/files/8949065/MauiApp3.zip)

### Steps to Reproduce

1. Configure Fiddler and Android Emulator. You can refer to this link. [Capturing and Inspecting Android Traffic](https://docs.telerik.com/fiddler-everywhere/traffic/configure-android#capturing-and-inspecting-android-traffic)
2. Run the sample project, Click the "Test" button.
3. You can see the captured request in Fiddler, is "Post" but not "Get"

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

no

**Comment by Eilon** [comment]
@yzbai great, thank you!

**Comment by Eilon** [comment]
@yzbai unfortunately I was not able to get Fiddler working to capture the trace. Can you post a screenshot of what you're seeing when running in Android?

I wonder if this particular case what's happening is that GET requests generally don't have any bodies (and if supplied, it's supposed to be ignored), so something in the system is changing the GET to a POST because that way the body would be correctly interpreted by the remote app.

I'm not sure why exactly this would happen on Android - usually I would expect this to just pass along whatever data you specified, even if it is meaningless. I wouldn't expect any server to do anything with the body, but that's impossible to know in general.

Can you confirm whether you really want to send a GET with a body?

**Comment by yzbai** [comment]
@Eilon Thanks for  your explanation. I guess every platform has their own way of dealing a GET with body. It is not a MAUI Issue then. 
I used a asp.net web api as backend to receive Get request parameters using model binding. And I set a Json string body on Get rquest for simplicity and convenience. It worked well before.

I will close the issue and rethink this. 
Thanks.
