### ISSUE TITLE
An empty Row in Grid takes up no space

### ISSUE THREAD

**Issue by sretz** [dotnet/maui#8448]
### Description

A Grid Row that has nothing attached to it, is taking up not space despite all rows are defined as *.
![image](https://user-images.githubusercontent.com/80936576/176745525-354138a0-5fed-4dc4-9ffb-b1d4c95fe2b1.png)

### Steps to Reproduce

1. Download https://github.com/sretz/Reproduce.GridEmptyRow
2. Run on Android or Windows

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Andriod Pixel 5 - API 30 (Andriod 11), Windows Machine Framework net6.0-windows10.0.19041

### Did you find any workaround?

No

**Comment by hartez** [comment]
This is by design (and consistent with how Grids work in UWP/WPF). Your Grid is inside of a VerticalStackLayout; the VSL is allowed to take up as much vertical space as it needs. So all measurements for the VSL use a vertical constraint of infinity. In a Grid, a '*' means "evenly divide the remaining available space"; however, when the "remaining space" is infinite, that concept doesn't have any meaning. In that case, the '*' functions the same as a Grid row height of 'Auto'. So your first few Grid rows get the 'Auto' height of their Labels; the last row gets zero height because there is nothing in it. 

If you'd like your Grid rows to have a height despite having no content, I'd suggest setting a fixed row height. Or use a Grid as the root container for your page, so that the height is fixed and '*' will have it's usual meaning.
