### ISSUE TITLE
OnAppearing not triggered when going back from Modal page

### ISSUE THREAD

**Issue by marcmognol** [dotnet/maui#8513]
### Description

OnAppearing is not triggered when going back from Modal page.

### Steps to Reproduce

0. Download solution here 
[BugMauiModal.zip](https://github.com/dotnet/maui/files/9038845/BugMauiModal.zip)

1. Run solution
2. On MainPage, click on button to go the Second page
3. Go back with "Back button" located on navigation bar
4. On MainPage, label should display "Appeared 2" --> OK
5. On MainPage, click on button to go the Second page
6. From SecondPage, click on "Open modal" button
7. On modal page, click on "Close" button
8. On second page, abel should display "Appeared 2" but it displays "Appeared 1 time"--> Not OK

Mean, OnAppearing was not triggered in this case

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

N/A

**Comment by jsuarezruiz** [comment]
Verified, thanks for the attached sample and detailed steps.

**Comment by cdefgah** [comment]
The same behavior occurs when you go back from a regular content page too. OnAppearing of the displayed page is not triggered.

**Comment by Martyf101** [comment]
There is inconsistent usage of the HasAppeared property in Page.

In FlyoutPage, TabbedPage and MultiPage it is used to store a reminder that the SendAppearing() call needs to be made at the appropriate time in the page lifecycle after a current page switch.

However, in NavigationPage it is used as a state machine toggle to ensure an OnDisappearing must be made before another OnAppearing is fired.

In NavigationPage line 406:

		void FireDisappearing(Page page)
		{
			if (HasAppeared)
				page?.SendDisappearing();
		}

		void FireAppearing(Page page)
		{
			if (HasAppeared)
				page?.SendAppearing();
		}

I don't believe this should be the same check for both functions, and the second should be checking the inverse ( HasAppeared == false ). When MauiNavigationImpl calls FireAppearing() in OnPopAsync() this check will fail, leaving the page in a broken state, causing both the OnAppearing not to fire and the ensuing OnDisappearing when the page leaves, as  _hasAppeared doesn't get updated to True.

Minimizing the App will correct the HasAppeared state, or firing a SendAppearing() on the destination Page in ModalPopping as a temp workaround.

**Comment by borrmann** [comment]
Is this going to be fixed anytime soon?

**Comment by SailDev** [comment]
**Why has this not the highest priority?**

My **personal** opinion:
- The "appearing" events belong to the most important events in the whole system.
- You can't develop a serious application, without having reliable working lifecycle events. Period!

At the moment, the problems i have with modal pages (i.e. multiple popups) and **memory leaks in general**, forced me to redesign my whole application and to move everything (pages and view models) to singletons.

Now it's even more important, to have reliable lifecycle events, to manage the state of the view models.
Time, to add another workaround (maybe WeakReferenceMessenger).

All i want, **since december 2021**, is to publish a MAUI application, which looks acceptable and does not crash when it's used for more than 5 minutes.

**Comment by developer9969** [comment]
@rachelkang @samhouts  hi - very grateful if you could confirm that this fix also applies to OnNavigatedTo and will be part of the next Visual studio release..
Many thanks
