### ISSUE TITLE
it looks like the webpage at https:/0.0.0.0/ might be having issues

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8613]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/it-looks-like-the-webpage-at-https:00/10077204)._

---
[severity:It's more difficult to complete my work]
Hi,

We posted a while back regarding issues we are having moving a Blazor web app to a BlazorWebView within a MAUI Blazor app. We have a Blazor client project we are trying to embed in a BlazorWebView control, we've built the DLLs and we've created a .NET MAUI Blazor app, added references to the existing Blazor client/shared DLLs. We've changed Main.razor from

```razor
<Router AppAssembly="@typeof(Main).Assembly">
	<Found Context="routeData">
		<RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
        <FocusOnNavigate RouteData="@routeData" Selector="h1" />
	</Found>
	<NotFound>
		<LayoutView Layout="@typeof(MainLayout)">
			<p role="alert">Sorry, there's nothing at this address.</p>
		</LayoutView>
	</NotFound>
</Router>
```
to

```razor
<Router
    AppAssembly="typeof(Main).Assembly">
	<Found Context="routeData">
		<RouteView RouteData="@routeData" DefaultLayout="@typeof(BlazorApp4.Client.Shared.MainLayout)" />
        <FocusOnNavigate RouteData="@routeData" Selector="h1" />
	</Found>
    <NotFound>
		<LayoutView Layout="@typeof(BlazorApp4.Client.Shared.MainLayout)">
			<p role="alert">Sorry, there's nothing at this address.</p>
		</LayoutView>
	</NotFound>
</Router>
```

We've also changed MainPage.xaml from

```razor
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:MauiApp1"
             x:Class="MauiApp1.MainPage"
             BackgroundColor="{DynamicResource PageBackgroundColor}">

    <BlazorWebView HostPage="wwwroot/index.html">
        <BlazorWebView.RootComponents>
            <RootComponent Selector="#app" ComponentType="{x:Type local:Main}" />
        </BlazorWebView.RootComponents>
    </BlazorWebView>

</ContentPage>
```

to

```razor
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:MauiApp1"
             x:Class="MauiApp1.MainPage"
             BackgroundColor="{DynamicResource PageBackgroundColor}">

    <!--<BlazorWebView HostPage="wwwroot/index.html">-->
    <BlazorWebView HostPage="_content/BlazorApp4.Client/index.html">
        <BlazorWebView.RootComponents>
            <RootComponent Selector="#app" ComponentType="{x:Type local:Main}" />
        </BlazorWebView.RootComponents>
    </BlazorWebView>
</ContentPage>
```

Obviously we haven't done something right because we get a page saying 

>"Hmmm... can't reach this page" and "it looks like the webpage at https:/0.0.0.0/ might be having issues ..."

We previously posted about this and got a response but we were too slow in responding and it was closed, but we were told:

>If you moved all the assets to a razor class library, then your index.html is likely going to be in _content/ClassLibId/index.html and you'll have to adjust that in your BlazorWebView component.

hence the change to the line

```razor
 <BlazorWebView HostPage="_content/BlazorApp4.Client/index.html">
```

where BlazorApp4.Client is our class library id (and the DLL called BlazorApp4.Client.Dll has been added as a reference), but it hasn't worked as expected. Sorry we didn't get back to you but we were really busy with everything else and this took a backseat.

We still don't know what we are doing wrong. Our MAUI Blazor app is now bare-bones (the default project) with a few references to our Blazor DLL libraries. We just need to know how to successfully point the BlazorWebView control to our wwwroot\index.html in our library as opposed to the one within the default MAUI project under wwwroot.

Richard

---
#### Feedback Bot on 6/22/2022, 00:24 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by linkaiyu** [comment]
here is a repro, not exactly the same code used by the issue creator, but the same use case. In the MainPage.xaml the hostpage is set to "_content/<component name>/index.html which is located under <component name>/wwwroot

 <BlazorWebView x:Name="blazorWebView" HostPage="_content/ChartRCL/index.html"
                           HeightRequest="500"
                           WidthRequest="1200">
                <BlazorWebView.RootComponents>
                <RootComponent Selector="#app" ComponentType="{x:Type ChartRCL:ChartMain}" />
                </BlazorWebView.RootComponents>
            </BlazorWebView>

just launch the app and the error message will display.

https://github.com/linkaiyu/MauiBlazorApp2

**Comment by mkArtakMSFT** [comment]
Apparently it's currently not supported to load index.html from a Razor Class Library. We're going to treat this as a feature. We're going through a prioritization process for .NET 8 these days and hopefully this will meet the bar to include in the release.

**Comment by linkaiyu** [comment]
since this document states that the asset under wwwroot inside RCL is supported by all applications, it would make good sense to get it in.
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-6.0&tabs=visual-studio
"An RCL's static assets are available to any app that consumes the library.
Place static assets in the wwwroot folder of the RCL and reference the static assets with the following path in the app: _content/{PACKAGE ID}/{PATH AND FILE NAME}. "

**Comment by MackinnonBuck** [comment]
@linkaiyu In `MainPage.xaml`, if you change the following line:

```xaml
<BlazorWebView HostPage="_content/BlazorApp4.Client/index.html">
```

to:

```xaml
<BlazorWebView HostPage="wwwroot/_content/BlazorApp4.Client/index.html">
```

then things should work as expected (notice the added `wwwroot/`).

Would you be able to confirm that this fixes your issue? Thanks.

**Comment by linkaiyu** [comment]
@MackinnonBuck , thanks for the info. Using wwwroot path works, but it's only for the local content in the hosting application's wwwroot. It does not work for the content html file from a Razor component as indicated by @mkArtakMSFT 
hope this feature can make into next version as this will allow complete Razor componentization

**Comment by MackinnonBuck** [comment]
@linkaiyu I was able to get the repro project to work by making the change I mentioned in the last comment (and by copying the relevant CSS to the RCL).

That said, taking this approach is generally problematic because MAUI Blazor assumes that the host page is in the root of the content directory, so assets are loaded relative to the host page location. Having the host page exist in an RCL effectively means you can only load static assets from that RCL.

Fixing this will likely involve MAUI Blazor changing how it determines where the root of the content directory is.

**Comment by linkaiyu** [comment]
@MackinnonBuck, I tried your approach and yes loading the index.html file from RCL lib works for the HostPage property. This is great!
However I found another error, maybe it's also related to the path.

In the RCL lib, I have a Razor component code trying to load a js file but it fails with this error:

TypeError: Failed to resolve module specifier 'wwwroot/_content/ChartRCL/exampleJsInterop.js'
    at https://0.0.0.0/_framework/blazor.webview.js:1:723
    at https://0.0.0.0/_framework/blazor.webview.js:1:3337
    at new Promise (<anonymous>)
    at beginInvokeJSFromDotNet (https://0.0.0.0/_framework/blazor.webview.js:1:3311)
    at https://0.0.0.0/_framework/blazor.webview.js:1:42795
    at EventTarget.<anonymous> (<anonymous>:7:62)
    at EmbeddedBrowserWebView.<anonymous> (<anonymous>:1:37578)

where is the @code 
@code {
	private Lazy<Task<IJSObjectReference>> moduleTask;
	protected override async void OnInitialized()
	{
		ConnectorService.OnExecuteJS += OnExecuteJS;

		moduleTask = new(() => JSRuntime.InvokeAsync<IJSObjectReference>(
		"import", "wwwroot/_content/ChartRCL/exampleJsInterop.js").AsTask());  

		var module = await moduleTask.Value;  // exception happens here
	}
}

I've pushed the changes to the repo. You can just build and run, you will see the exception at line 25 of ChartMain.razor file

@mikeparker104

**Comment by MackinnonBuck** [comment]
@linkaiyu,

When the host page (index.html) is located in an RCL, all requests to static content must be relative to the location of the host page. However, this is going to be problematic when trying to load any static assets not located in the RCL. For that reason, I would highly recommend **not** having the host page in an RCL.

If you _really_ wanted to make the above snippet work, you would have to change the path `wwwroot/_content/ChartRCL/exampleJsInterop.js` to `/exampleJsInterop.js`, since the host page is `wwwroot/_content/ChartRCL/index.html`:

```razor
@code {
    private Lazy<Task<IJSObjectReference>> moduleTask;
    protected override async Task OnInitializedAsync()
    {
        moduleTask = new(() => JSRuntime.InvokeAsync<IJSObjectReference>("import", "/exampleJsInterop.js").AsTask());
        var module = await moduleTask.Value;
    }
}
```

But again, it's very likely you'll eventually run into an issue in the future where the only workaround is to move the host page out of the RCL and into `wwwroot/` in the host application.

Hope this helps!

**Comment by linkaiyu** [comment]
@MackinnonBuck , That works. Thanks!

For now it's OK with my customer since both the hosting page and the JS file is inside the RCL, which is what they want for a self contained component. 

for the future, it would be ideal to have the restriction removed so that content file can be either in the host app's wwwroot or RCL's wwwroot and let the path determine the location e.g. regardless of the location of HostPage location, the js file should have the path of wwwroot/_content/RCL/exampleJsInterop.js. This is needed because the code in the RCL does not have to depend on the knowledge of where the index.html file is specifified in the host app's MainPage.xaml.

**Comment by linkaiyu** [comment]
@mikeparker104 @danroth27 
for the future, it would be ideal to have the restriction removed so that content file can be either in the host app's wwwroot or RCL's wwwroot and let the path determine the location e.g. regardless of the location of HostPage location, the js file should have the path of wwwroot/_content/RCL/exampleJsInterop.js. This is needed because the code in the RCL does not have to depend on the knowledge of where the index.html file is specifified in the host app's MainPage.xaml.

**Comment by MackinnonBuck** [comment]
@linkaiyu I opened https://github.com/dotnet/maui/issues/11541 to track addressing this limitation. Feel free to give it a 👍 so it shows up as higher priority in our planning meetings 🙂

**Comment by MackinnonBuck** [comment]
Closing this out in favor of #11541
