### ISSUE TITLE
CollectionView is displaying incorrect images

### ISSUE THREAD

**Issue by MissedSte4k** [dotnet/maui#8676]
### Description

I'm creating an app, where I recieve a lot of images from MQTT (as byte[] (byte[] -> ImageSource)). I often clear everything and then get flooded by them over and over again. The problem I'm seeing for quite some time is this: the images are not consistant with the images that are actually being send to the app. It seems to be the caching strategy or caching still being saved in between the sessions. Most of the time it occurs and disappears as UI refreshes/updates (insert or deletion). 

### Steps to Reproduce

1. Download the sample project
[TestImages.zip](https://github.com/dotnet/maui/files/9092779/TestImages.zip)
2. launch the sample project on android and scroll to the bottom (hope it wont crash)
3. Open MainPage.xaml.cs and switch images in lines 23/24 from:
```
//Animals.Add(new Animal(base64CatImage, "cat" + a));
Animals.Add(new Animal(base64DogImage, "dog" + a));
```
to
```
		Animals.Add(new Animal(base64CatImage, "cat" + a));
		//Animals.Add(new Animal(base64DogImage, "dog" + a));

```
4. Launch the app again and scroll down

Expected behavior: 
First time you only saw dog images and now see only cat images

Actual behavior: 
Instead of seeing just cat images now, you see a dog images mixed in from time to time

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Sometimes refreshing the UI works o fix the issue, but it's just a very temporary problem and usually makes it fail in another place in the UI

**Comment by nCastle1** [comment]
Seeing the same behavior, also applies to iOS.

**Comment by emssejka** [comment]
I am also seeing this behavior.  Does anyone have a workaround?

**Comment by Symbai** [comment]
If you don't have many images a workaround is to write the image to disk giving it a unique(!) name and load it from disk.

**Comment by emssejka** [comment]
I believe I have tried that.  When my app starts up, it downloads images (.png) on the fly from my backend server and writes them to the app data location/folder.  The collection view xaml has an Image element which binds to a property on my object that specifies the image path.  Scrolling up and down through the items in the collection view causes the wrong images to appear in the wrong rows randomly.  Are you recommending something different?

**Comment by minglu** [comment]
+1

**Comment by emssejka** [comment]
I have also noticed that it appears to work fine when deployed to an iOS device...not sure if it is just Android.

**Comment by hartez** [comment]
As far as Android goes, I'm almost certain this isn't a CollectionView issue. There's nothing in the CollectionView cell reuse mechanism that persists across application runs. However, all the image loading on Android is done via Glide, and AFAIK Glide's default is to cache locally to storage. So if MAUI's not playing nice with Glide's caching, it would explain why this happens across application runs.

**Comment by hartez** [comment]
Yeah, I just managed to reproduce this without a CollectionView. Just two images in a StackLayout.

**Comment by hartez** [comment]
When using ImageSource.FromStream(), MAUI isn't providing any information to Glide that Glide can use to build a reasonable key for caching the object. Glide _requires_ a key implementation in a loader, but ours just uses `new ObjectKey(inputStream)`, which means that we're just keyed off of some generic values of a Stream object. There's nothing unique about it, so collisions are pretty much guaranteed. 

So an application runs, loads an image from a Stream via Glide, and Glide caches the image to disk with a key based on the Stream object. The next time the application runs and requests for Glide to load an image from a Stream, if the key created from the new Stream collides with the previous one (which is pretty much guaranteed to happen), then Glide loads up the cached image from disk, rather than the image from the actual Stream. 

The only solution to get the _correct_ image without API changes is to disable caching entirely for the `FromStream()` path; this will force Glide to actually load up what's in the Stream. 

In the future, if we want to provide the option of caching images from Streams, we'll need to add an overload to pass an optional cache key into `FromStream()`, and let the user define the key; we'd pass that value along to new overloads of `PlatformInterop.loadImageFromStream()`.

**Comment by emssejka** [comment]
Does this also apply to when the file(s) are not being loaded from a stream, but actually reside on the disk?

**Comment by Matmork** [comment]
Related to this? https://github.com/dotnet/maui/issues/12182
Happens both on Android and iOS

**Comment by hartez** [comment]
> Does this also apply to when the file(s) are not being loaded from a stream, but actually reside on the disk?

Depends on how you're loading them. If they're assets (included in the project and deployed with the application), then no - those shouldn't have any cache confusion (at least, I don't think so).

But if you're loading them from disk using FromStream(), then yes; this problem can occur.

**Comment by hartez** [comment]
> Related to this? #12182 Happens both on Android and iOS

Guessing this is a different problem; those are being loaded with URLs, so it's using a different mechanism. And presumably Glide is using the URL for a cache key.

**Comment by Matmork** [comment]
> Guessing this is a different problem; those are being loaded with URLs, so it's using a different mechanism. And presumably Glide is using the URL for a cache key.

Probably. Strange that half of the images have URL of _null_ but are still showing images.

**Comment by Maceeek** [comment]
Anyone found any workaround before #13111 is merged? This issue happens pretty often in my application and it's blocking me from making a release. Maybe writing my own Image control renderer?
