### ISSUE TITLE
MT1008: Failed to launch the simulator: Value cannot be null.

### ISSUE THREAD

**Issue by degenet** [dotnet/maui#8833]
### Description

The following error appears when trying to run the app in the simulator (MacOS Monterrey 12.4):

**error MT1008: Failed to launch the simulator: Value cannot be null.**

Things I've tried so far
- Disabled the Remote Simulator To Windows
- Disabled Hot Reload
- Emptied Xamarin cache folder on mac
- Deleted obj and bin folders / clean rebuild
- Tried running the following command in Terminal:

> launchctl list|grep UIKitApplication|awk '{print $3}'|xargs launchctl remove

The app however runs fine on my iPad Pro 12 on iOS 15.4 using Hot Reload.

### Steps to Reproduce

1. Create a new MAUI App
2. Select any iOS 15.4 Simulator
3. Run the app

I'm using 

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
- Hot Reload shouldn't affect launching the simulator or any app. For it to work, it requires the debugger to work, so the app has to have already launched.
- I would suggest trying a fresh iOS application (`dotnet new ios`) and see if that deploys, just to verify that none of the MAUI specific tooling is affecting it.
- I would also try deploying the app to the simulator from CLI, also to verify that it's something in the IDE.

As far as I can see, it's not something specific to MAUI, or something that could be fixed in this repo. I would file this to VS Feedback.

**Comment by degenet** [comment]
Hello drastications. Thank you for the suggestions and feedback. I will give them a try and file a report through VS Feedback if the issue persists.
