### ISSUE TITLE
RowDefinitions is now mandatory (was optional in Forms)

### ISSUE THREAD

**Issue by softlion** [dotnet/maui#8958]
### Description

With this XAML code in Xamarin Forms, the grid gets fiven 4 "Auto" rows automatically.   
With MAUI, the texts are superimposed each over the others:

```xaml
<Grid ColumnDefinitions="Auto,*">
   <Label Text="line 0" />
   <Label Grid.Row="1" Text="line 1" />
   <Label Grid.Row="2" Text="line 2" />
   <Label Grid.Row="3" Text="line 3" />
</Grid>
```

In MAUI you have to specify RowDefinitions, it is not optional anymore.

```xaml
<Grid ColumnDefinitions="Auto,*" RowDefinitions="Auto,Auto,Auto,Auto">
   <Label Text="line 0" />
   <Label Grid.Row="1" Text="line 1" />
   <Label Grid.Row="2" Text="line 2" />
   <Label Grid.Row="3" Text="line 3" />
</Grid>
```

Is this a bug or by design ?  
If it is by design, it's only there to make sure we can't migrate Xamarin Forms apps easily ? Or to make us write tons on aditionnal useless XAML to display a Grid ? Or to make us loose time when adding a row ? I really would like to know the motivation behind this.

### Steps to Reproduce

See above

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

Yes and no

### Relevant log output

```shell
none
```

**Comment by hartez** [comment]
> Is this a bug or by design ?

It's by design. Having to constantly verify that the Row/ColumnDefinitions matched with the attached property information was a performance drain in Forms, especially since most folks never use that capability. (IIRC, it's not even documented anywhere.) And no other Grid implementations (WPF, UWP, etc.) do this. So the current behavior is more in line with other implementations and performs better. 

It _is_ possible to reinstate this behavior by subclassing Grid and using a custom GridLayoutManager, but I realize that's not very helpful for your specific case. If we manage to get #9010 implemented, then you would be able to re-add this behavior for the Grid type itself. In the meantime, I'm afraid you'll have to fully specify your Row/ColumnDefinitions.

**Comment by softlion** [comment]
> So the current behavior is more in line with other implementations and performs better.

A source generator or a xamlc compilation would do that at compile time with 0 performance hit.
