### ISSUE TITLE
[Android] Bad z-index for item in a grid

### ISSUE THREAD

**Issue by roubachof** [dotnet/maui#9009]
### Description

I have several view in a grid:
* an Image
* a transparent Frame on top of the image
* 2 buttons overlapping the transparent frame thanks to negative margins

<img width="787" alt="image" src="https://user-images.githubusercontent.com/596903/181058666-5a014bda-8ef1-44e7-b2f4-4e5cb2796d9e.png">

Buttons should be on top of the frame, but they are beneath 😞 

![Screenshot_1658852459](https://user-images.githubusercontent.com/596903/181058944-ae9bee00-0ccb-45c0-ab4d-488f4e1bada4.png)

### Steps to Reproduce

launch the sample here on Android:
https://github.com/roubachof/Sharpnado.TaskLoaderView/tree/master/Retronado.Maui

Navigate to "Commands/Snackbar" page.

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

**Comment by dlandi** [comment]
More information: Android:  an item in a grid **surrounded by a frame** does not respect ZIndex. Remove the Frame and ZIndex works.

**Comment by hartez** [comment]
This has nothing to do with the Grid, this is a Frame issue.

**Comment by hartez** [comment]
So, the reason this happens with Frame is that Frame retains some default Android `Elevation` behaviors from Forms for backward compatibility reasons. There are several ways you can work around this:

You can use Border instead of Frame. Border doesn't have any intrinsic `Elevation` properties on Android, so it doesn't have this behavior:

```
<Grid RowDefinitions="300,*">
    <Border ... />
    <Button Grid.Row="1" ZIndex="10" Margin="0,-20,100,0" ...  />
</Grid>
```

You can wrap the Frame inside of a ContentView; this will give the Frame a new context for its `Elevation`, preventing it from elevating above the other controls in the Grid's context:

```
<Grid RowDefinitions="300,*">

    <ContentView>
        <Frame ... />
    </ContentView>

    <Button Grid.Row="1" ZIndex="10" Margin="0,-20,100,0" ...  />

</Grid>
```

You can force the Android `Elevation` property for the Frame to be zero using the `Elevation` platform-specific:

```
<ContentPage ...            
	xmlns:android="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.AndroidSpecific;assembly=Microsoft.Maui.Controls"
             >

	<Grid RowDefinitions="300,*">
        <Frame android:VisualElement.Elevation="0" ... />
        <Button Grid.Row="1" ZIndex="10" Margin="0,-20,100,0" ...  />
    </Grid>
</ContentPage>
```

Or you can disable the Frame's shadow:

```
<Grid RowDefinitions="300,*">
    <Frame HasShadow="False" ... />
    <Button Grid.Row="1" ZIndex="10" Margin="0,-20,100,0" ...  />
</Grid>
```

You could also customize the handler and disable the backward-compatible `Elevation` handling.

**Comment by npostma** [comment]
@hartez nice explanation! Your suggestions work like a charm. But the idea of MAUI is making one view for multiple platforms. Shouldn't this still considered as a bug?
