### ISSUE TITLE
[WPF] BlazorWebview in Transparent WPF window is non interactable

### ISSUE THREAD

**Issue by honzapatCZ** [dotnet/maui#9024]
### Description

When you put a BlazerWebview into a WPF Window with AllowTransparency = true, the resulting WebView is non interactable(click through, can't type, etc.).

![image](https://user-images.githubusercontent.com/26117393/181237311-a9f4fcfb-d033-4271-bd3a-62336aa706a5.png)

I suppose this can be somehow tied to #3395 as in both cases the WPF doesn't have any idea about interactions happening in the webview(ie don't know that something would have actually been clicked, etc.).

Note: I had to use the BlazorWebViewInitialized event to achieve full transparency(and use other features) would be cool if at least the DefaultBackgroundColor would be tied to the BlazorWebView XAML element's BackgroundColor.

### Steps to Reproduce

Add BlazorWebView to a Window that has AllowTransparency=True

Expected Outcome: Resulting rendered html would have transparent parts and would be fully working
Actual Outcome: The rendered html has transparent parts, but is not interactable

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

**Comment by Eilon** [comment]
Hi, I believe this is an issue with the WebView2 control itself. Please add your comments/votes to these issues so that the WebView2 team can address it:

* https://github.com/MicrosoftEdge/WebView2Feedback/issues/997
* https://github.com/MicrosoftEdge/WebView2Feedback/issues/286

Or if those don't look like exact matches, see if some others in this query are matches: https://github.com/MicrosoftEdge/WebView2Feedback/issues?q=is%3Aissue+is%3Aopen+transparent+wpf
