### ISSUE TITLE
ScrollView layout not updating after dynamic change.

### ISSUE THREAD

**Issue by josh-aw** [dotnet/maui#9078]
### Description

Certain combinations of layouts will fail to update sizing when the content is changed dynamically. I discovered this while laying out a complex page in my project and was able to narrow it down to the sample provided. If you resize the window the layout will then resize correctly.

[LayoutIssueSample.zip](https://github.com/dotnet/maui/files/9222288/LayoutIssueSample.zip)

https://user-images.githubusercontent.com/104639260/181818056-2c28c4f5-92f9-405d-b04d-fa5dfa8ec06d.mp4

### Steps to Reproduce

1. Run included sample
2. Click the toggle button, observe that green label's position is not properly updated.
3. Resize the window, the layout will update to the correct size.

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows

### Affected platform versions

Windows 10, iOS 15

### Did you find any workaround?

Resizing the window will force the layout to render correctly.

**Comment by jbizcloud** [comment]
Hey. I just tested in macOS and was not able to replicate with your code.

Maybe you can try using `VerticalOptions="FillAndExpand"` in `ScrollView` or `VerticalStackLayout`?

<img width="558" alt="Screen Shot 2022-07-30 at 10 06 30 PM" src="https://user-images.githubusercontent.com/75679603/182006559-dedb856c-2b54-430f-8bae-8241ea023217.png">

**Comment by RonnyRos** [comment]
For  iOS.
   
   <Grid RowDefinitions="9*,1*" VerticalOptions="FillAndExpand">
        <ScrollView Orientation="Vertical" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" VerticalScrollBarVisibility="Never" HorizontalScrollBarVisibility="Never">
            <Grid>
            
            </Grid>
            
           </ScrollView>

**Comment by jfversluis** [comment]
Hey everyone, thanks for this! I'm having a hard time understand what the status is of this. I see the initial report is for Windows, then macOS looks fine and then some iOS code is posted. On which platforms are we seeing this exactly? 😅 

Can I also ask for a reproduction project in the form of a GitHub repository please? Thanks!

**Comment by jcsnider** [comment]
@jfversluis here is a [reproduction case github repo](https://github.com/jcsnider/Maui9078_Scrollview_Resizing_IOS_Repro) for iOS devices.

I also captured a [screen recording](https://ascensiongamedev.com/resources/filehost/b9e28a3f47ea1387e93c1e86526df7ad.mov) which shows:
1. The app loads all of the elements for MainPage (slowly on an old iPhone 6) - these consist of some filler elements to encourage scrolling, and then webview elements which resize to their content's height.
2. I attempt to scroll down, I can only see a portion of the first video.
3. I rotate the device into landscape, which forces the layout to update, and then I rotate back to portrait mode.
4. I am then able to scroll down and see each of the elements within the scrollview.

In my reproduction case I use a Grid element within the ScrollView in order to layout the elements, but the issue persists if I use a VerticalStackLayout instead, so I am not sure if this is relevant to #9850 or not.

**Comment by hartez** [comment]
With #12912 in place, this issue no longer occurs with Windows or iOS.

**Comment by TonyLugg** [comment]
I'm having the same issue with Android.  I have data templates loaded with a template selector for carouselview.  If I have a ScrollView containing a VerticalStackLayout full of elements with some having bound IsVisible, making the elements visible after the fact does not display them.  It seems the ScrollView does not acknowledge the change in size of the stack layout.  If I remove the ScrollView everything works fine.  This is a port from Xamarin Forms which worked as expected.
