### ISSUE TITLE
[Feature Request] Add sync support to Maui SecureStorage

### ISSUE THREAD

**Issue by dg2k** [dotnet/maui#9204]
### Description

This Feature Request had already been made by @scotru for Xamarin SecureStorage as posted [here](https://github.com/xamarin/Essentials/issues/856). This is a renewed request for @jamesmontemagno to reconsider for .NET Maui.

In the interest of not re-inventing the wheel, I shall just reproduce the original Summary text and API Changes, courtesy of @scotru.

SecureStorage provides an async API via GetAsync and SetAsync methods. Implement Get and Set to provide an analogous synchronous API for situations that don't need/want async/await.

### Public API Changes

```csharp
public static string SecureStorage.Get(string key)
public static void SecureStorage.Set(string key, string value)
```

### Intended Use-Case

async/await tends to 'infect a codebase' propagating throughout. Some codebases do not need the additional complexity of async calls. Since on most platforms the SecureStorage operations are not actually performed async, provide access to a direct synchronous implementation without an async wrapper.

My own addition with full text [here](https://docs.microsoft.com/en-us/answers/questions/955720/can-sync-support-to-maui-securestorage-be-added-pl.html):

> ... most usage of SecureStorage shows up in a constructor, for example, database initialization where the encryption key is obtained as `await SecureStorage.GetAsync("cipherKey")`. Since an instance constructor cannot be async, the workaround, at best, is not elegant when a sync version like `SecureStorage.Get("cipherKey")` could save the day.

Please also see more rationale as comments from other developers as described in the [original request](https://github.com/xamarin/Essentials/issues/856).

**Comment by Redth** [comment]
We abstract multiple platforms for this API, one of which, uses async methods at the platform level (Windows).  As a result, we cannot implement this synchronously (lowest common denominator wins).  We can't just call .Wait() or .Result on the task because that has potential for bad things in your app.

If you want to take an opinionated and informed use of `GetAwaiter().GetResult()` in your own code because you've taken precautions _where_ and _how_ you use it to avoid deadlocking, that is up to you.

Sorry, but unfortunately this will not be implemented.
