### ISSUE TITLE
.net Maui Workload is not available to install on VS 2022 17.3 Preview 6 installer

### ISSUE THREAD

**Issue by jmblakl** [dotnet/maui#9222]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I'm running Windows 11 on a Parallels VM.  The underlying system is a 16" MacBook Pro M1 MAX running macOS Monterey version 12.3.  After grabbing the Visual Studio 2022 17.3 Preview 6 installer, The MAUI Workload is not available to select to install.  Neither are any of the individual components.  Its important to note that I DO NOT have .net 7 installed.

![image](https://user-images.githubusercontent.com/3864704/183206906-8789ce46-78ea-49ad-91fa-400457bdef85.png)

![image](https://user-images.githubusercontent.com/3864704/183204061-49e131ce-25fd-4b42-8d37-955d81b59e1f.png)

**Comment by yuanjifeng** [comment]
the same problem ,
![IMG_4953](https://user-images.githubusercontent.com/52353428/183284154-070c429d-4a11-4888-b50f-e22b703cee36.jpg)

**Comment by jfversluis** [comment]
I'm pretty sure that you have downloaded the arm64 version of Visual Studio which makes sense since you are running on an ARM chip. However, the workloads that are supported on arm64 aren't that many yet. Also, .NET MAUI is not a supported workload. For now, use the x64 version and the workload should show up fine.

If you still have issues, please report it through the Visual Studio report a problem menu, that will surface it to the right team to have a look at it. Thanks and have fun discovering .NET MAUI!
