### ISSUE TITLE
Unable to deploy maui apps to android devices

### ISSUE THREAD

**Issue by musictopia2** [dotnet/maui#9329]
I tried to create just a maui app with blazor to deploy to android.  I made no changes to the templates.
However, local devices don't even show up.  I tried to use xamarin forms and even on xamarin forms, local devices don't even show up.
Would be disappointing if a person can't even test apps on a real android device.
Used to work with older previews.  I even checked to make sure development mode was enabled on the android device and it was.  Even windows recognized the device but visual studio does not.  I upgraded to the third major update of visual studio 2022.

**Comment by SommerEngineering** [comment]
I have the same problem 😩. The emulated devices are not displayed either 🙁 . I can start the emulator via the Android Device Manager, but they are not displayed in Visual Studio. This is annoying because it worked yesterday with the Visual Studio Preview 🤷 . Today, with the final version it does not work anymore. @MS developers: can you pass this on to the Visual Studio team?

**Comment by SommerEngineering** [comment]
I reported the problem directly through Visual Studio. Here is the link where the issue can be up-voted.: https://developercommunity.visualstudio.com/t/MAUI:-Emulated-Android-devices-are-not-s/10116574

**Comment by musictopia2** [comment]
Actually I found out that I had to somehow disable the usb debugging, revoke the debugging.  Then reenable it again then allow always when it pops up when i plug back in.   After that, it worked (tried on 2 different devices).
