### ISSUE TITLE
Hot reload XAML does not work on new install (code works fine)

### ISSUE THREAD

**Issue by DonThompson** [dotnet/maui#9366]
### Description

I'm following the simple first getting started app: https://docs.microsoft.com/en-us/learn/modules/build-mobile-and-desktop-apps/4-exercise-create-your-first-maui-app

I upgraded VS2022 from 17.2.x to 17.3.0
I modified my installation to install the .NET MAUI workload.
I then started following the guide in the PhoneWord example.

I modified code in MainPage.xaml.cs, clicked Hot Reload, and the status bar reported "Code changes were applied successfully."
I noticed it should work with XAML as well, according to the tutorial, so I tried to change the words inside a text label.
Clicking Hot Reload says "No code changes were found."

I tried making a subsequent code change after this, which works (is detected, status bar updates, code change works) -- but that still doesn't apply my XAML change with it.
I also tried making other changes (adding new controls, removing controls) but it behaved the same incorrect way.

I checked to ensure all the options were enabled as described in the troubleshooting document @ https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-hot-reload-troubleshooting?view=vs-2022

### Steps to Reproduce

1. Create a File -> New .NET MAUI App
2. Run in debug mode
3. Change some code like ++ to += 2
4. Hot reload, see that your change works
5. Change some XAML, like "Hello, World" to "Hello there"
6. Hot reload, see that your change is not detected and the UI does not update

Expected outcome:  Your change is detected and your running update has the new changes.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

No

**Comment by DonThompson** [comment]
I was just able to test on Android and it seems to work fine there.  Windows is the one failing still.

**Comment by jfversluis** [comment]
Hey @DonThompson thanks so much for the detailed report and of course that you're looking into working with .NET MAUI! The issue you're seeing probably originates in our tooling though rather than the .NET MAUI SDK. I can totally understand this is not really clear as a user, so don't worry about it. However, in order for this to be diagnosed (and hopefully resolved!) in a quick way, I will add a label on here that will trigger a bot. That bot will give you the instructions needed to report this in the right place. That will also add all the right data for that team to look into it.

Thanks and have a great weekend!

**Comment by DonThompson** [comment]
Link to VS issue report:  https://developercommunity.visualstudio.com/t/Hot-reload-XAML-does-not-work-on-new-ins/10119170
