### ISSUE TITLE
DisplayAlert does not works in Windows, does in Android

### ISSUE THREAD

**Issue by geertgeerits** [dotnet/maui#9469]
### Description

In Windows no DisplayAlert box.

### Steps to Reproduce

1. Run the application in Android, you will see the DisplayAlert box.
2. Run the application in Windows, there is no DisplayAlert box.

GitHub:
https://github.com/geertgeerits/MauiAppTestDisplayAlert

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
@geertgeerits for now can you use Loaded to fire your displayalert code

**Comment by janseris** [comment]
@PureWeen is there anything that is not moved to backlog milestone?

**Comment by angelru** [comment]
None of the alerts work in windows

**Comment by angelru** [comment]
@PureWeen what do you mean by loaded?

**Comment by PureWeen** [comment]
@geertgeerits for your code here

https://github.com/geertgeerits/MauiAppTestDisplayAlert/blob/master/MauiAppTestDisplayAlert/MainPage.xaml.cs#L14

If you just use 
`this` instead of the  `MainPage` does that work?

**Comment by angelru** [comment]
> @geertgeerits for your code here
> 
> https://github.com/geertgeerits/MauiAppTestDisplayAlert/blob/master/MauiAppTestDisplayAlert/MainPage.xaml.cs#L14
> 
> If you just use `this` instead of the `MainPage` does that work?

it does not work

**Comment by PureWeen** [comment]
This looks like it will be fixed with .NET 7 

### Code running on .NET7 
![image](https://user-images.githubusercontent.com/5375137/188199441-bcaf20dc-63f8-4c6f-a22b-68bee3b63979.png)


For now if you move the call to the `Loaded` event that should achieve your desired result

### Code running on current stable .NET6 
![image](https://user-images.githubusercontent.com/5375137/188199660-c4cbd645-9243-43c4-8c71-4a19fcf9f6dd.png)
