### ISSUE TITLE
[Android] Slow scrolling, laggy performance

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#9485]
### Description

It is a list using CollectionView with elements using Border. It's a list of only 5 items, but there must be something wrong somewhere because it lags considerably.

![surfer-droid-scroll](https://user-images.githubusercontent.com/6755973/185075233-e048161d-363b-490e-b0d8-f0208a94fc26.gif)

### Steps to Reproduce

1. Download or sync https://github.com/jsuarezruiz/netmaui-surfing-app-challenge
2. Launch the App on Android and scroll the main page.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 and 13

**Comment by HausBJB** [comment]
This bug has been reported so many times, none of them will be fixed

**Comment by byme8** [comment]
In traces, I can see that the CollectionView calls SurfingApp!SurfingApp.Views.Templates.PostItemTemplate..ctor() again and again.
Looks like it recreates the whole view on every scroll.

Attaching traces. They contains everything that happens during the swipe gesture:
[maui-app-trace.speedscope.json.zip](https://github.com/dotnet/maui/files/9365519/maui-app-trace.speedscope.json.zip)

**Comment by jsuarezruiz** [comment]
> In traces, I can see that the CollectionView calls SurfingApp!SurfingApp.Views.Templates.PostItemTemplate..ctor() again and again. Looks like it recreates the whole view on every scroll.
> 
> Attaching traces. They contain everything that happens during the swipe gesture: [maui-app-trace.speedscope.json.zip](https://github.com/dotnet/maui/files/9365519/maui-app-trace.speedscope.json.zip)

Reviewed and can see the same. PostItemTemplate is created again and again.

**Comment by jedusei** [comment]
Related: https://github.com/xamarin/Xamarin.Forms/issues/8718#issuecomment-767615301

**Comment by HausBJB** [comment]
I have the same problem. How do you upload such an app to the Play Store? you will be laughed at immediately. certain things need to be fixed as a matter of priority.

**Comment by jedusei** [comment]
Hey guys, I've developed a workaround to this issue that you can use until the MAUI team provides an official fix. 
Please try it out and let me know whether it works for you too.

https://gist.github.com/jedusei/e15f45e1ae385d8b57413c168d3ef730

**Comment by HausBJB** [comment]
Hello when can I expect this fix for net 6?

**Comment by nextcodelab** [comment]
THIS WHAT I FELT IN ALL ALMOST .NET NATIVE CONTROLS... Yes it is real native, it undergo a lot of compilations, logics and codes before it landed to native view...

**Comment by angelru** [comment]
> Hola chicos, he desarrollado una solución para este problema que pueden usar hasta que el equipo de MAUI proporcione una solución oficial. Por favor, pruébalo y hazme saber si funciona para ti también.
> 
> https://gist.github.com/jedusei/e15f45e1ae385d8b57413c168d3ef730

This should improve scrolling with collectionview?

**Comment by jonathanpeppers** [comment]
Reviewing this app, the first thing I noticed that the `PostItemTemplate.xaml` has about 100 lines of styles inside. I moved this into the main `Styles.xaml`, so it isn't created for every row.

Next, I recording a `.speedscope` while scrolling: [surfer.zip](https://github.com/dotnet/maui/files/11065733/surfer.zip)

35% of the time is spent in:

![image](https://user-images.githubusercontent.com/840039/227617856-c8ab3c97-2c5d-4b5a-a9cc-6bc782f1a682.png)

This is deeply nested doing interop from C# -> Java -> C# -> Java many levels deep.

I think we should remove this C# method somehow:

https://github.com/dotnet/maui/blob/3859318f971b39b9d4a0e48492a3daed012cb695/src/Core/src/Platform/Android/WrapperView.cs#L93-L114

And put everything in Java, so nothing does interop at all here. I will investigate if it's even possible, because there may be a lot of C# logic happening here.
