### ISSUE TITLE
.NET MAUI App Service/Background Task

### ISSUE THREAD

**Issue by pwisk** [dotnet/maui#9598]
### Description

In UWP manifest I see declaration for App Service, but I can't add referencje to Windows Runtime Component (Universal Windows) as it was in pure UWP or Xamarin Forms. There is compability error.:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project MyAppAppService is not compatible with net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0). Project MyAppAppService supports: uap10.0.19041 (UAP,Version=v10.0.19041)	MyAppMaui	C:\Workspace\MyApp\MyApp-Features\MyAppMaui\MyAppMaui.csproj	1	

Is there any solution to handle background tasks in .NET MAUI for UWP?

### Public API Changes

I tried option for "in-process background task" https://docs.microsoft.com/en-us/windows/uwp/launch-resume/create-and-register-an-inproc-background-task and "out-of-process background task" https://docs.microsoft.com/en-us/windows/uwp/launch-resume/create-and-register-a-background-task

### Intended Use-Case

In my .NET MAUI app I need to synchronize data with external database. I need this functionality only in UWP version.

**Comment by mattleibow** [comment]
This is mainly because Maui for Windows is now a WinUI app - not UWP.

Not sure if this issue indicates that services are working or not: https://github.com/microsoft/microsoft-ui-xaml/issues/4200
But this does not look good: https://github.com/microsoft/microsoft-ui-xaml/issues/3838

Can you open an issue https://github.com/microsoft/microsoft-ui-xaml so the WinUI team can have a look and make sure it is all working. And if it is, they can recommend the best way forward.

**Comment by jfversluis** [comment]
Nothing more we can do on our side for this, closing it for now.
