### ISSUE TITLE
iOS CollectionView cell-reuse issues with Converters

### ISSUE THREAD

**Issue by edgiardina** [dotnet/maui#9791]
### Description

Porting this bug from Xamarin Forms, but with a MAUI reproduction project

https://github.com/xamarin/Xamarin.Forms/issues/14047

When using converters in a CollectionView, the collectionview will often not refresh/update all cells data if the data is generated from a converter, on iOS.

### Steps to Reproduce

Repository is here, but the gist is:

1. Create a collectionview
2. the datatemplate should have a converter that can change under conditions
3. trigger the converter's change binding in whatever way, the converters will often not visually refresh on screen (or require scroll or refresh to repair the state). 

Repro Repository
https://github.com/edgiardina/CollectionView-ConverterBug

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

No. 

### Relevant log output

```shell
no relevant logging
```

**Comment by edgiardina** [comment]
https://user-images.githubusercontent.com/3627193/187530724-1b5ad094-5fd4-4131-914e-49ad44432285.mov

**Comment by Redth** [comment]
It looks like the data source being invalidated doesn't always cause the items themselves to be invalidated.  I can see this on Android too.  Verified on .NET 7.0.50 of MAUI.

**Comment by hartez** [comment]
This is not a bug. 

Value converters are applied at the time of binding to a context (i.e., to a piece of data). They are also applied when the source value changes (assuming the change raises a PropertyChanged event). 

When an item is added to the ItemsSource of a CollectionView, the CollectionView does one of two things:

- If it has an old View available of the right type in the recycling pool, it re-uses that View 
- If not, it creates a brand-new View

It does this for performance reasons - creating new Views constantly as users scroll is expensive and slow. 

In the first situation, the CollectionView checks the piece of data the re-used View is bound to (its BindingContext). If the new data is different from the old data, it updates the BindingContext to the new piece of data. At that time, all the bindings in the View are applied, and any converters that happen to be in the View will be applied. 

But if the data in the re-used View is _already_ the same instance as the new data (i.e., if `oldElement.BindingContext.Equals(bindingContext)`), then it just leaves the re-used View as-is; it's already bound to the correct piece of data. 

It does this for performance reasons. Binding is expensive, especially in a View where there may be multiple nested Views with their own bindings, any of which may also trigger layout changes. So the View recycling mechanism avoids it when it's not necessary.

The behavior in your reproduction project is demonstrating this re-use of Views which are already bound to the correct data. Because they don't need to re-bind, the ValueConverters don't kick in to update the output values. 


There are several ways you can address this:

- You could include the unit system as a property of the Item's view model, and include that property when determining equality
- You could use multiple DataTemplates (one for each unit system) and use a DataTemplateSelector which switches on the selected user preference
- Depending on how much data you intend to display, a BindableLayout may be a suitable alternative

**Comment by edgiardina** [comment]
> You could include the unit system as a property of the Item's view model, and include that property when determining equality

Would this work with triggers? So instead of binding the label's Text to a converter, use DataTriggers switch between two properties in the viewmodel? 

I am fine accepting that this isn't possible with converters, but I would say that the CollectionView documentation could use a paragraph about this phenomenon, since at first glance, it appears that converters could be used in this way. And the ListView behavior is different (although, ListViews also allow you to specify how to virtualize, so I'm unsure how cell reuse options would affect this behavior.)

**Comment by hartez** [comment]
> Would this work with triggers? So instead of binding the label's Text to a converter, use DataTriggers switch between two properties in the viewmodel?

As far as I know, triggers _should_ work.

**Comment by hartez** [comment]
>  I would say that the CollectionView documentation could use a paragraph about this phenomenon

Agreed, and added to our to-do list: https://github.com/dotnet/maui/issues/11975
