### ISSUE TITLE
MediaPicker returns the page set by default in the shell

### ISSUE THREAD

**Issue by innomarcoItalia** [dotnet/maui#9810]
### Description

It needs set default item in shell, when you navigate to the photo page once you run MediaPicker (CapturePhotoAsync () or PickPhotoAsync ()) it returns the start page.
If you remove in AppShell.xaml.cs

```cs
menuShell.CurrentItem = start;
```

this works correctly

### Steps to Reproduce

Download the attached MauiPhoto project.
Compile and run on an Android device
- click hamburger icon
- click Photo
- click Take Photo and confirm the photo
- return StartPage 

......
comments   menuShell.CurrentItem = start   in AppShell.xaml.cs  

Compile and run on an Android device
- click hamburger icon
- click Photo
- click Take Photo and confirm the photo
- return photo correctly 

[MauiPhoto.zip](https://github.com/dotnet/maui/files/9460808/MauiPhoto.zip)

### Version with bug

6.0.486 (current)

### Last version that worked well

6.0.400

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11 - Android 12

**Comment by mattleibow** [comment]
The reason this happens is because you are setting the current page to be the start item in OnAppearing. When you navigate to the camera, the page disappears and then reappears - switching back to the start page each time.

If you want to use the OnAppearing, you need to detect if this is the first or subsequent time:

```cs
bool firstRun = true;

protected  override void OnAppearing()
{
    base.OnAppearing();

    if (firstRun)
        menuShell.CurrentItem = start;
    firstRun = false;
}
```

An alternative and maybe nicer way is to set the CurrentItem in the XAML as that is only evaluated once:

```xaml
<FlyoutItem ... CurrentItem="{Reference start}">
```
