### ISSUE TITLE
Screenshot doesn't work on iOS

### ISSUE THREAD

**Issue by MathieuM53** [dotnet/maui#9866]
### Description

I'm using the method Microsoft.Maui.Media.Screenshot.CaptureAsync() in a blazor hybrid project : on iOS platform, it returns a black screen.

Here is my code :

public async Task TakeScreenshotAsync()
{
    IScreenshotResult result = await Microsoft.Maui.Media.Screenshot.CaptureAsync();

    MemoryStream ms = new MemoryStream();
    await result.CopyToAsync(ms, ScreenshotFormat.Png, 100);
    byte[] data = ms.ToArray();
    await ms.DisposeAsync();

    var file = Path.Combine(FileSystem.CacheDirectory, "screenshot.png");
    await File.WriteAllBytesAsync(file, data);
    await Microsoft.Maui.ApplicationModel.DataTransfer.Share.Default.RequestAsync(new ShareFileRequest
    {
        Title = fileName,
        File = new ShareFile(file)
    });
}

### Steps to Reproduce

As the code in the description above :
1. call the method Microsoft.Maui.Media.Screenshot.CaptureAsync()
2. use a memory stream to get the result in a byte array
3. write the byte array in a file and store it on the cache directory
4. use the Share class to get the file
5. execute the code on iOS simulator or device : select the option "Save to Files" then open the file (the result is a black screen)

### Link to public reproduction project repository

n/a

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by PureWeen** [comment]
possibly related
https://github.com/dotnet/maui/issues/4835

**Comment by drasticactions** [comment]
The screenshot command does work, it just doesn't work in this very specific instance ;)

The screenshot APIs in MAUI are using the same image rendering APIs we introduced for rendering views to images. I guess that doesn't render the web view. Originally, those APIs called on the system level screenshot APIs to take a picture of the whole screen.

Those APIs could be added back as an option if you want to use the system level APIs for the "real" screenshot APIs, rather than using the image rendering stuff.

To work around it, you should be able to call this (https://docs.microsoft.com/ja-jp/dotnet/api/uikit.uiscreen.capture?view=xamarin-ios-sdk-12) to get the full view.

**Comment by drasticactions** [comment]
I know this is an issue, you don't need a repo. Just run the screenshot command with a web view and it won't render.

**Comment by MathieuM53** [comment]
Thanks for the workaround @drasticactions : it solved my problem.
(Sorry for my late answer but I had not been able to test it before because of the problem on the support for Xcode of the Visual Studio's release 17.3.4)
