### ISSUE TITLE
Centered StackLayout within StackLayout does not center

### ISSUE THREAD

**Issue by srqdevg** [dotnet/maui#9927]
### Description

If I create a stacklayout with both horizontal and vertical options set to 'Fill' is correctly fills the screen. But embedding a stacklayout and setting both horizontal and vertical options to center does nothing. A label within this stacklayout shows at the top left. I would expect the label to be centered both horizontally and vertically.

```xaml
<StackLayout BackgroundColor="Aqua" HorizontalOptions="Fill" VerticalOptions="Fill">
	<StackLayout BackgroundColor="Pink" HorizontalOptions="Center" VerticalOptions="Center">
		<Label Text="Test" />
	</StackLayout>
</StackLayout>
```

### Steps to Reproduce

1. Create new Maui App
2. Open main page
3. Replace ScrollView content with the above XAML
4. Run.

### Link to public reproduction project repository

.

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.22000.194

**Comment by NonameMissingNo** [comment]
Hey there, StackLayouts are kinda whack, would you mind trying it with either
A: A single grid
B: A grid, which has a stacklayout inside it

**Comment by srqdevg** [comment]
Both options A and B work, so it can be worked around.

**Comment by hartez** [comment]
> Version with bug
> 6.0 Release Candidate 3

Have you tried updating to a more recent version?

This is what I get when I use the XAML you posted:

![image](https://user-images.githubusercontent.com/538025/188685046-75e9082f-b82d-42e5-a053-2a3e736d76dd.png)

Which is what I would expect given the markup.

**Comment by srqdevg** [comment]
I tried this in preview 17.4 and yes it does center horizontally, but still not vertically. So, it is still broken

**Comment by hartez** [comment]
It's working as designed - a vertically-oriented StackLayout ignores the `VerticalOptions` of its children (since the whole point of it is to stack them). So the `VerticalOptions="Center"` on your inner StackLayout has no effect. 

If you want the text to be vertically centered as well, you should use a Grid:
```
<Grid BackgroundColor="Aqua" HorizontalOptions="Fill" VerticalOptions="Fill">
    <StackLayout BackgroundColor="Pink" HorizontalOptions="Center" VerticalOptions="Center">
        <Label Text="Test" />
    </StackLayout>
</Grid>
``` 

And depending on what your ultimate goal is, you might even be able to simplify this more:
```
<Grid BackgroundColor="Aqua">
    <Label BackgroundColor="Pink" HorizontalOptions="Center" VerticalOptions="Center" Text="Test" />
</Grid>
```

**Comment by srqdevg** [comment]
I would disagree. If I state that I want a control centered on screen, then that is what should happen. What it contains is irrelevant. In this case it should be vertically centered with the items within stacked vertically. And the actual XAML is much more complicated, I simplified it, to show that issue. And yes, I could rework the XAML, but this is a pre-existing Xamarin LOB that works fine. I'm in the process of evaluating whether it can be converted to Maui or not.

**Comment by hartez** [comment]
> And yes, I could rework the XAML, but this is a pre-existing Xamarin LOB that works fine.

When I paste your XAML into a new Xamarin.Forms project, it looks like this:

![image](https://user-images.githubusercontent.com/538025/188727883-5ce39977-1ffe-4e4b-9279-6912f2f7b0b6.png)

Not vertically centered.

Is it possible your Xamarin.Forms application uses `CenterAndExpand` rather than `Center`?

**Comment by hartez** [comment]
> Yes, my Xamarin Forms app used CenterAndExpand, but as that value has been deprecated, I changed to Center for Maui.

`Center` and `CenterAndExpand` do different things; that's why they are two different values. The behavior of StackLayouts with regard to `Start`, `Center`, and `End` hasn't changed; just as in XF, StackLayouts ignore the alignment values in their stacking direction. Otherwise they couldn't function as stacks. 

> that value has been deprecated

The 'AndExpand' values were deprecated precisely because they cause this confusion; they force StackLayouts to behave as if they were single-column (or single-row) Grids. The recommendation is to use a Grid rather than 'AndExpand', as I showed [upthread](https://github.com/dotnet/maui/issues/9927#issuecomment-1238411018).

**Comment by srqdevg** [comment]
I would disagree with closing this because there is a difference between the behavior of HorizontalOptions and VerticalOptions. Just because Xamarin did it one way, does not mean it is correct. As it currently stands  VerticalOptions does nothing, so either fix the behavior so that both options work the same or remove the VerticalOptions field for a stack layout as it has no use.
